openshift/verification-tests

- features/cli/oc_volume.feature
@jhou1 @sunilcio @lyman9966 could you help take a look? 
log: https://privatebin-it-iso.int.open.paas.redhat.com/?2c88b39b06c8c77e#cSjMvYDjUD/viYiJN7wupzzIXFkgfTnX047QGzKB5YU=
> fix_OCP-12194 outdated commands

- features/upgrade/machines/machines.feature
Adding one more test for autoscaler test. @sunzhaohua2 @miyadav PTAL
Tested and passed.
- prepare: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99284/
- check: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99286/
> Upgrade: Add autoscaler test

- features/step_definitions/dc.rb
- features/step_definitions/deployment.rb
- features/step_definitions/ds.rb
- features/step_definitions/rs.rb
- lib/common.rb
- lib/host.rb
backport of #1187
merge only after the other one is merged.
> backport fix proxy environment injection

- testdata/storage/vsphere/pod.json
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?9a160687258fb50a#sWz7WO5If2Pb4HTHZ/3u2Q4wQDSuk+5yiHNuM6zdfhg=)
> Update image url for vsphere

- features/cli/deploy.feature
- features/cli/oc_patch_apply.feature
- testdata/deployment/dc-with-pre-mid-post.yaml
- testdata/deployment/deployment-perme-failed-1.yaml
- testdata/deployment/deployment-perme-failed-3.yaml
- testdata/deployment/deployment-with-resources.json
- testdata/deployment/deployment1.json
- testdata/deployment/manual.json
- testdata/deployment/tc510612/hook-inheritance-secret-volume.json
- testdata/deployment/test-stop-failed-deployment.json
- testdata/deployment/testhook.json
- testdata/deployment/updatev1.json
- testdata/replicaSet/tc533162/rs_endpoints.yaml
@kasturinarra Could you please help review ? thanks.
> update with image degist

- testdata/scheduler/multiple-schedulers/pod-no-scheduler.yaml
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/100177/console
@kasturinarra  Please help review , thanks .
> update image with digest

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
Since `oc new app` is changed and `new_app_as_dc` is added.
So adding option --docker-image to `new_app_as_dc`
> Add option --docker-image to new_app_as_dc

- lib/rules/web/admin_console/4.5/style.xyaml
> Add rules for auto OCP-29799

- features/registry/registry.feature
@openshift/devexp-qe please help review this,thanks
Passed here [OCP-29696](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99624/consoleFull)
> Auto OCP-29696

- features/registry/registry.feature
- lib/openshift/image_content_source_policy.rb
Passed locally http://pastebin.test.redhat.com/871733
> Auto OCP-29693 OCP-29706

- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.1/logs.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/logs.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/logs.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/logs.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
> rules added for OCP-20688

- lib/openshift/service.rb
check if we get IPv6 address and encode in brackets
Needs testing on cluster with IPv6 services
> service: add IPv6 URL brackets and fix return

- features/networking/egress-ingress.feature
@zhaozhanqi @weliang1 @anuragthehatter @rbbratta 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1542/console
> Auto OCP-19615

- features/storage/csi.feature
Replace this pr https://github.com/openshift/verification-tests/pull/1138 , no code chaged
> Adding stage images test cases

- features/logging/kibana.feature
- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
@anpingli @yapei PTAL, thanks.
Runner-v3 log: https://url.corp.redhat.com/e51dc3b
cases: https://url.corp.redhat.com/1b92970
> auto kibana cases

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch.feature
- features/step_definitions/logging.rb
- lib/openshift/cluster_logging.rb
- lib/openshift/elasticsearch.rb
cases: https://url.corp.redhat.com/a1a125f
runner-v3 log: https://url.corp.redhat.com/46b52a7
> auto ES6 cases

- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
@yapei Please review. Thanks!
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/102125/console
> fix 4.5 encoded url for check_link_and_text

- features/networking/multus-ipv6.feature
- features/step_definitions/clouds/azure.rb
- features/step_definitions/cluster_configuration/cluster_config.rb
- features/step_definitions/cluster_configuration/csi.rb
- features/step_definitions/cluster_configuration/localstorage.rb
- features/step_definitions/cluster_configuration/snapshot.rb
- features/step_definitions/helper_services.rb
- features/step_definitions/logging.rb
- features/step_definitions/machine_healthcheck.rb
- features/step_definitions/metering.rb
- features/step_definitions/networking.rb
- features/step_definitions/pv.rb
- features/step_definitions/route.rb
- features/step_definitions/secrets.rb
- features/step_definitions/upgrade/3rd_operator.rb
- features/step_definitions/upgrade/etcd.rb
- features/svc-catalog_asb/asb.feature
- features/upgrade/sdn/policy-upgrade.feature
> Use BushSlicer::HOME

- features/networking/egress-ip.feature
Originally I combined OCP-21812 and  OCP-15473 into one auto script case.
Due to PR https://github.com/openshift/verification-tests/pull/933, we cannot use one auto test case script to track two or more cases in Polarion .  So move the scripts for OCP-15473 out from OCP-21812. 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1384/console
> Auto OCP-15473

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
Automated 7 ui test cases:
OCP-21166,OCP-21334,OCP-21161,OCP-21192,OCP-21363,OCP-21134,OCP-21132
Depend on PR:
https://github.com/openshift/cucushift/pull/7812
v3 job run on 4.5:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99571/console
v3 job run on 4.1:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99562/console
v3 job run on 4.2
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99567/console
v3 job run on 4.3:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99564/console
v3 job run on 4.4:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/99565/console
> Hongyli 7 alert ui

- features/cli/deploy.feature
Fix the code for stability as sometimes the test case is failing with the error below
Error from server (Conflict): error when replacing "/home/jenkins/workspace/Runner-v3/testdata/deployment/updatev1.json": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again
> Fix for stability

- tools/formatter.sh
> Add shell script to format cucshift feature file

- features/routing/route.feature
This is basically a re-push of PR #1222  which previously had conflicts due to rebasing while adding modification. The successful v3-runner job after the change is as below:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/104163/console
@lihongan, request for a peer review
> re-push modifications in lieu of PR #1222

- features/upgrade/node/scc.feature
Updated OCP-13065 upgrade auto
> Updated OCP-13065 upgrade auto

- lib/rules/web/ocm_console/archived_cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_idp.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/dropdown_items.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Here are the jenkins logs
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75906/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75847/console
@pruan-rht Could you please help to review?
* add the login step and the directory for ocm
* rename uhc to ocm
* fix typo issue
* package some elements and functions
* Fix action issues
* fix some issues and add archived cluster page rule
* finish action define for case OCP-25326
* Update the action names to meet the name rule
* update the stepdefinition of the 'open ocm portal'
* modify the stage web_console_url in config
* Locate cluster by name
* fix name to readable
* fix typo issue
* add rules for ocp22117
* Add actions: monitoring_tab_loaded check_logs_tab click_monitoring_tab …
> Finish some rules for the OCM UI automation testing (#37)

- tools/launch_instance.rb
> ERB trim mode '<' is invalid

- features/upgrade/api_auth/upgrade.feature
@xingxingxia please take a look!
> OCP-29741 upgrade auto

- features/cli/job.feature
> Fix test for stability

- features/logging/collector.feature
- testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
- testdata/logging/clusterlogging/example.yaml
- testdata/logging/clusterlogging/example_indexmanagement.yaml
- testdata/logging/clusterlogging/example_unmanaged.yaml
- testdata/logging/clusterlogging/scalebase.yaml
> reduce ES request cpu and memory

- features/upgrade/samples_operator/upgrade.feature
@xiuwang @wewang58 Please review, thanks!
> Upgrade check for OCP-27983

- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei @yanpzhan Please review, thanks!
> Add rules for OCP-29724

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/machine.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/machine.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/machine.xyaml
> add rule for OCP-21399

- features/upgrade/node/scc.feature
This should fix the could not find scenario problem.
/cc @sunilcio @lyman9966
> Remove case id from upgrade-prepare

- lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.1/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Depend on PR:
https://github.com/openshift/cucushift/pull/7874
Automate test cases:
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-24760
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-24097
Fix test failure:
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-21150
v3 Job
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/104548/console
> automate 2 tests and fix 1 test failure

- features/machine/machine_healthcheck.feature
OCP28859 - MHC MaxUnhealthy string value should be checked for '%' symbol .
* It prints a message in log for confirming that the remediation is short circuited , because the max unhelathy condition did not met , which confirms that it is validating the % symbol correctly 
*bugzilla which it tests - https://bugzilla.redhat.com/show_bug.cgi?id=1816606
>  OCP28859 - MHC MaxUnhealthy string value should be checked for '%' sym

- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
add rules for OCP-27582 
@yapei, pls help to review, thanks!
> add rules for OCP-27582

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
> auto case OCP-24478

- testdata/infrastructure/hpa/hello-pod.yaml
update from docker.io to quay.io
@jhou1 @sunilcio @lyman9966 could you help? 
Thanks,
> using quay images

- features/upgrade/sdn/policy-upgrade.feature
sometimes when the networkpolicy is created. maybe it need more time to make it take effect. here just add timestamp.
> update time wait to polciy take effect

- features/storage/negative.feature
> Fix file url

- features/build/stibuild.feature
- features/step_definitions/file.rb
Passed locally http://pastebin.test.redhat.com/875383
> Add obtain test dir

- features/upgrade/samples_operator/upgrade.feature
@openshift/devexp-qe Please help review, thx
> Auto OCP-29709

- features/upgrade/web/console-upgrade.feature
upgrade-prepare log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/107215/console
upgrade-check log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/107216/console
@SSshahan pls help to review
> update web case for disconnected env

- features/step_definitions/resources.rb
- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.4/deployment.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.5/deployment.xyaml
@yanpzhan  Can you help review?
> rules added for OCP-28297

- features/cli/oc_help.feature
Update the help output check.
@jhou1 @sunilcio @lyman9966 could you help with the review?
log: http://pastebin.test.redhat.com/877327
> Update help output - OCP11565

- tools/formatter.sh
```
-i, --no-snippets                Don't print snippets for pending steps.
```
/cc @pruan-rht @akostadinov
> Add option no-snippets to formatter.sh

- testdata/pods/pod-pull-by-tag.yaml
> Update image to support disconnect cluster

- features/step_definitions/logging.rb
- lib/openshift/cluster_logging.rb
- lib/openshift/elasticsearch.rb
Add methods to get the status field in the ClusterLogging and Elasticsearch.
> add methods for logging resources

- features/test/meta.feature
- features/test/project.feature
> test loop step

- features/upgrade/api_auth/upgrade.feature
Change the title of the prepare test case to consistent with  the title of  the upgrade-check case !
> Change the title of the prepare test case

- lib/rules/web/admin_console/4.2/logging_kibana.xyaml
- lib/rules/web/admin_console/4.3/logging_kibana.xyaml
- lib/rules/web/admin_console/4.4/logging_kibana.xyaml
- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
Add Kibana console rules.
@yanpzhan @anpingli Could you please help to review it?
> add rules for kibana

- features/networking/sdn.feature
https://privatebin-it-iso.int.open.paas.redhat.com/?0f8ec5c58b061cd5#IBm9d1js6f+7ngir4VfHDj63bxoho/0m78Jk0wps5Ko=
@zhaozhanqi @weliang1 @rbbratta @anuragthehatter 
Original PR was closed due to some messy files, open this new PR.
> Auto OCP-29299

- features/step_definitions/metering.rb
run log https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1688/console
> fix jira OCPQE-984

- features/networking/multicast.feature
- features/step_definitions/networking.rb
Update OCP-12930 to test multicast in both sdn and ovn cluster.
Log from testing ovn cluster
https://privatebin-it-iso.int.open.paas.redhat.com/?20b639f7e51bf0f1#F6eDX1T15+metBlqAuSZqY0NnIWWS1Ih60I2IKtdy5k=
Log from testing sdn cluster
https://privatebin-it-iso.int.open.paas.redhat.com/?51b00d522828fa79#WQ4rf16Txvfi5Ph7ioQRRrsc5J/HKQbJaMVZlnSPRg4=
> Same case to test both sdn and ovn cluster

- features/networking/multus.feature
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-excludeIP.yaml
Automate OCP-31999 - [SDN-556] Whereabouts with exclude IP address
Testing log: https://privatebin-it-iso.int.open.paas.redhat.com/?94d7420266fd084b#vUDBFXE732yi+I5bDYeKG4Q8Y6mpEmx/iLliNapTPOE=
@anuragthehatter @rbbratta @zhaozhanqi @huiran0826
> Automate OCP-31999

- features/logging/kibana.feature
- lib/rules/web/admin_console/4.1/logging_kibana.xyaml
- lib/rules/web/admin_console/4.2/logging_kibana.xyaml
- lib/rules/web/admin_console/4.3/logging_kibana.xyaml
- lib/rules/web/admin_console/4.4/logging_kibana.xyaml
- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
Adding automation scenario for https://bugzilla.redhat.com/show_bug.cgi?id=1823305. 
@anpingli @yanpzhan PTAL
Runner-v3 log: https://url.corp.redhat.com/99eb278
> automate case OCP-32002

- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
> add rule for OCP-26557

- features/cli/policy.feature
- features/cli/serviceaccount.feature
Some small fix to adapt the script to the new version(the changes have already cherry pick in low versions)!
@xingxingxia @rhpmali Please review.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/110609/console
> Some small fix to adapt the script to the new version

- features/networking/pod.feature
> OCP-26014 Pod readiness check for OVN, fix case id

- features/step_definitions/metering.rb
run log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1718/console
@akostadinov @liangxia PTAL, it should fix some of the failures.  Thx!
> corner cases fix for metering steps

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
@wangke19 @liangxia help review/merge, thanks!
> add oc create deploymentconfig with short -o

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/node.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/node.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/node.xyaml
This is for 4.5, will add 4.2, 4.3, 4,4 if it looks good.
> add OCP-19722 rules for 4.5

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Depend on PR:
https://github.com/openshift/cucushift/pull/7909
Automated 4 test cases:
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-21263
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-24604
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-21124
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-24601
Fix one test failure for uncertain order:
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-24760
V3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/108195/console
> Automated 4 UI test cases and fix 1 test failure

- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
> rules updated

- features/cli/deploy.feature
Fix for stability as i see that the test sometimes fail with below error
Error from server (Conflict): error when replacing "updatev1.json": Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "hooks": the object has been modified; please apply your changes to the latest version and try again
> Fix OCP-11695

- features/build/buildconfig.feature
@openshift/devexp-qe passed in local, PTAL thanks
> Fix OCP-11474

- features/images/rhel8_images.feature
[Pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/114277/)
@openshift/devexp-qe  PTAL, thanks
> Fix OCP-22958

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/pods.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/pods.xyaml
- testdata/deployment/hello-deployment-1.yaml
> add rules for OCP-26868

- lib/rules/web/admin_console/4.6/check_links.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/style.xyaml
Fixes for cases: OCP-29799 OCP-27901 OCP-24512
> fix web case for 4.6

- features/cli/serviceaccount.feature
oc new-app  generate deployment(>4.4) and deploymentConfig,this is for Compatible with different version OC
https://github.com/openshift/oc/pull/355
@xingxingxia @rhpmali  PTAL
> oc new-app  generate deployment(>4.4) and deploymentConfig,this is for Compatible with different version OC

- tools/install_os_deps.sh
- tools/jenkins/slaves/Dockerfile.rhel7
/cc @pruan-rht @akostadinov @zhouying7780 
```
Installing : autoconf-2.69-11.el7.noarch                                27/77 
install-info: No such file or directory for /usr/share/info/autoconf.info
```
> Add nodocs to yum install

- features/upgrade/security_compliance/fips.feature
@xiaojiey Hi, Please help to review the changes. Thanks!
> update output string for fips upgrade

- lib/rules/web/admin_console/4.4/builds.xyaml
> update a doc link for 4.4

- features/support/cucu_formatter.rb
- features/support/env.rb
- lib/polarshift/scenario_wrapper.rb
- lib/polarshift/test_case.rb
- lib/polarshift/test_record.rb
- lib/ssh.rb
- lib/test_case_manager.rb
- lib/world.rb
Test html log with the changes:
when after hook failed:
http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/07/09/23:31:33/Scale_Elasticsearch_nodes_by_nodeCount_2-_3-_4_in_clusterlogging/console.html
when everything succeeded:
http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/07/09/23:31:33/upgrade_OLM/console.html
> fixes to test result reporting and logging

- lib/rules/web/admin_console/4.4/goto.xyaml
Add missing rule for 4.4 of case OCP-21263
Track issue:
https://issues.redhat.com/browse/OCPQE-1300
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/117276/
> add missing rule for 4.4

- features/support/cucu_formatter.rb
- features/support/env.rb
- lib/polarshift/scenario_wrapper.rb
- lib/polarshift/test_case.rb
- lib/polarshift/test_record.rb
- lib/ssh.rb
- lib/test_case_manager.rb
- lib/world.rb
> (v3) fixes to test result reporting and logging

- features/networking/pod.feature
/cc @pruan-rht @anuragthehatter
> Fix undefined steps which is caused by typo

- testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml
set serviceAccount to fix pod permission issue
@jhou1 @sunilcio @lyman9966  could you help to take a looke?
> fixing server account issue

- features/networking/ovn_winc.feature
- features/networking/pod.feature
- features/step_definitions/networking.rb
- testdata/networking/windows_pod_and_service.yaml
Basic test to cover windows and linux pod connectivity
@zhaozhanqi @rbbratta @weliang1 @huiran0826 
Logs: https://privatebin-it-iso.int.open.paas.redhat.com/?ac1d54fa09f51fe7#42BCNJXHOiPThet/pMM0gK0YoEgfnla5LUscDvDte4I=
> Initiating Windows Container automation

- features/networking/sriov.feature
- features/step_definitions/sriov.rb
- lib/openshift/sriov_network.rb
- lib/openshift/sriov_network_node_policy.rb
- testdata/networking/sriov/namespace/43/ns.yaml
- testdata/networking/sriov/namespace/45/ns45.yaml
- testdata/networking/sriov/og/og.yaml
- testdata/networking/sriov/pod/sriov-without-resource-static.yaml
- testdata/networking/sriov/pod/sriov-without-resource-static.yaml-deployment
- testdata/networking/sriov/sriovnetwork/static-sriovnetwork.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice.yaml
- testdata/networking/sriov/subscription/sub.yaml
Draft one pr to auto sriov case
seems jenkins is down, run the in my local
http://pastebin.test.redhat.com/876540
@anuragthehatter @huiran0826 @rbbratta @weliang1 PTAL, thanks
> sriov case auto 

- lib/openshift/etcd_cluster.rb
@liangxia @pruan-rht @akostadinov this file seems miss require statement at the beginner, pls help to confirm and merge it, thanks
> fix_etcd_cluster_rb

- features/storage/node_operations.feature
- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
@chao007 @duanwei33  Please help review.
> Bug fix for oc_new_app_as_dc and OCP-15268

- features/node/seccomp.feature
- testdata/node/pod_nostat.json
This makes sure the image gets mirrored in disconnected env.
> Enable test for disconnected

- features/upgrade/storage/upgrade.feature
- testdata/storage/csi/csi-hostpath-attacher.yaml
- testdata/storage/csi/csi-hostpath-driverinfo.yaml
- testdata/storage/csi/csi-hostpath-plugin.yaml
- testdata/storage/csi/csi-hostpath-provisioner.yaml
- testdata/storage/csi/csi-hostpath-snapshotter.yaml
- testdata/storage/csi/csi-rbac.yaml
- testdata/storage/csi/csi-storageclass.yaml
- testdata/storage/csi/restorepvc.yaml
- testdata/storage/csi/snapshotclass.yaml
- testdata/storage/csi/volumesnapshot.yaml
@qinpingli @duanwei33 Please help check upgrade test case for snapshot
Pre-check:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/110659/console
Post-check:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/110699/console
> Auto upgrade tc OCP-28630

- features/step_definitions/sriov.rb
@pruan-rht  @liangxia lack " " due to include `.`. PTAL, thanks
> add quotation marks

- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.5/node.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/node.xyaml
Fix OCP-28297, OCP-19722 for 4.6.
Pass log on 4.6 https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/119753/console
> fix for web case

- lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
Fixed failures and created 3 new cases for 4.6
OCP-32857 - List all alerts and could filter alerts by state and severity
OCP-32858 - List all silences and could filter silences by state
OCP-32859 - List all alerting rules and could filter rules by severity and state
Depend on PR:
https://github.com/openshift/cucushift/pull/7973
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/118995/console
> fix failures and new case for 4.6

- lib/iaas/iaas.rb
- lib/world.rb
> properly fix fully qualified resource names cache

- features/networking/egress-ip.feature
- features/step_definitions/networking.rb
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1700/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1702/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1703/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1704/console
Note: Case OCP-25640 failed due to https://bugzilla.redhat.com/show_bug.cgi?id=1762580
@zhaozhanqi  @weliang1 @anuragthehatter @rbbratta
> auto some egressIP cases

- lib/openshift/resource.rb
> avoid race condition while checking delete deps

- lib/iaas/iaas.rb
Get cred from secret
@duanwei33 @akostadinov  Please help review.
> Bug fix for OCP-9685

- lib/test_case_manager.rb
OCPQE-1435
/hold
needs testing
> warn on missing artifacts

- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/projects.xyaml
@yanpzhan  Please review, thanks!
> Add rules for OCP-32152

- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/123631/console
> fix test failure 4.4 for case OCP-24601

- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/124582/console
> Hongyli fix testfailure OCPQE-1583

- features/step_definitions/networking.rb
Because we are parsing :response which includes stderr
we are parsing the error message instead of the stdout.
The fact that we have an timeout error with valid output
is not fatal for this step.
```bash
[00:34:22] INFO> Shell Commands: oc get clusternetwork default --template=\{\{.pluginName\}\}
redhat/openshift-ovs-networkpolicy
STDERR:
I0729 20:34:24.148105 1154034 request.go:621] Throttling request took 1.060477114s, request: GET:https://api.rbrattai-s46a24.qe.devcluster.openshift.com:6443/apis/operators.coreos.com/v1?timeout=32s
I0729 20:34:34.148292 1154034 request.go:621] Throttling request took 11.060291252s, request: GET:https://api.rbrattai-s46a24.qe.devcluster.openshift.com:6443/apis/app.triggermesh.io/v1alpha1?timeout=32s
I0729 20:34:44.348259 1154034 request.go:621] …
```
> networkplugin: workaround api timeout

- testdata/deployment/deployment-perme-failed-2.yaml
@kasturinarra  Please help review , thanks
> update for yaml format

- lib/rules/web/admin_console/4.3/browser_opts.yml
- lib/rules/web/admin_console/4.3/builds.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/browser_opts.yml
@yanpzhan  Help review the changes, comparison log 
Before the fix, we can see many `ElementClickInterceptedError` error  [log before the fix](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/124050/consoleFull)
After the fix, no more `ElementClickInterceptedError` errors [log after the fix](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/124417/consoleFull)
> fix 4.3 and 4.4 to support flexible scroll

- features/networking/ptp_operator.feature
- features/step_definitions/networking.rb
- testdata/networking/ptp/namespace/43/ns43.yaml
- testdata/networking/ptp/namespace/45/ns45.yaml
- testdata/networking/ptp/og/og.yaml
- testdata/networking/ptp/ptp_master.yaml
- testdata/networking/ptp/ptp_slave.yaml
- testdata/networking/ptp/subscription/sub.yaml
Auto OCP-25738, OCP-25740,OCP-26187
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1604/console
> auto some ptp cases

- tools/jenkins/slaves/Dockerfile.centos
- tools/jenkins/slaves/Dockerfile.rhel7
/cc @pruan-rht @akostadinov 
The same as https://github.com/openshift/verification-tests/pull/1409, but for image cucushift-public.
> Fix geckodriver download url for cucushift-public

- features/storage/dynamic_provisioning.feature
@qinpingli @chao007 
As discussed, I'd like add some steps to test volume "persistent", please help review.
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?9a5edb3354024989#YiwLSkVLFK3vK9t5iaEPvl4fK5uT18DZkxzzC918pQw=)
There is one step "And I verify that the IAAS volume with id "<%= cb.volumeID %>" was deleted" need to be fixed in another thread.
> Add step to test persistent

- features/step_definitions/operators.rb
- features/upgrade/marketplace/upgrade.feature
The modification has been verified on local environment. And the log is in the http://pastebin.test.redhat.com/890593.
> Delete CSC creation on OCP 4.5+

- features/networking/pod.feature
- testdata/networking/centos_latest_admin.yaml
Tested on 4.4,4.5 and 4.6 - OCP 33413
Logs: https://privatebin-it-iso.int.open.paas.redhat.com/?98628e852ce477a3#jnpIS4NC6qLXpVt9ZtQoZJ6jkxLBhnDL6RAzc+IPyVM=
@rbbratta @zhaozhanqi @huiran0826 @weliang1
> xt_u32 test coverage for SDN

- features/upgrade/machines/machines.feature
Fixes https://issues.redhat.com/browse/OCPQE-1662
> Add tear down

- testdata/authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json
- testdata/authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json
Upgrade the apiVersion of PodSecurityPolicySelfSubjectReview.
@xingxingxia @rhpmali PTAL!
> Upgrade the apiVersion of PodSecurityPolicySelfSubjectReview

- features/upgrade/workloads/oc-upgrade.feature
prepare job: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/123652/console
check job: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/123956/console
@kasturinarra Could you please help review , thanks.
> auto for OCP-33209

- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/node.xyaml
- lib/rules/web/admin_console/4.6/pods.xyaml
Fix 4.6  cases: OCP-23688,OCP-26868,OCP-19608
> fix for 4.6 web cases

- features/step_definitions/networking.rb
On OVN the default interface is `br-ex`.
If we use the `\W` regex to split the output,
the `\W` will match the `-` in `br-ex` since the
dash is not a word character `([A-z_])`
```
sh-4.2# ip route show default
default via 10.0.0.1 dev br-ex proto dhcp metric 800
```
switch to `\s` and split on whitespace to match `br-ex`
instead of `br`.
Idealy we would use `-j` to output JSON but the iproute2
version in the container doesn't support it yet.
> Fix ip route show default parsing

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
Depend on PR:
https://github.com/openshift/cucushift/pull/8037
V3 Job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/130925/console
Automated 2 cases
OCP-33446 - Node CPU stats should be accurate
OCP-33244 - [BZ 1846805] kubelet_running_pod_count shouldn't take into account completed pods
> automated 2 new test cases

- features/cli/resources.feature
[pass log](http://pastebin.test.redhat.com/892661) @openshift/devexp-qe PTAL, thanks
> Fix OCP-11882

- features/networking/sctp.feature
- features/step_definitions/networking.rb
- testdata/networking/sctp/load-sctp-module.yaml
- testdata/networking/sctp/sctpclient.yaml
- testdata/networking/sctp/sctpserver.yaml
- testdata/networking/sctp/sctpservice.yaml
Auotmate OCP-28757: Establish pod to pod SCTP connections
Test log: https://privatebin-it-iso.int.open.paas.redhat.com/?2689abc01f193f67#CN81T3gdCEElTAE7hOkvPYv0WBGCodhxsifOQWlOb50=
Please help to review the first SCTP test case, I will automate the rest cases after get your good comments,  thanks!
> Auotmate OCP-28757

- features/upgrade/monitoring/monitoring-upgrade.feature
Fix upgrade failure by updating metric name which is applicable to 4.4, 4.5 and 4.6
https://issues.redhat.com/browse/OCPQE-1847
Didn't update completely in the previous merge
https://github.com/openshift/verification-tests/pull/1438
> Hongyli fix upgrade failure

- features/cli/projects.feature
Failure: OCPQE-1665
Cause: 4.4- oc new-app create dc, but 4.5+ oc creates deployment.
Pass log: Runner-v3/132375/console
@wangke19 help review, thanks.
> fix OCP-11887

- features/step_definitions/scc.rb
- lib/world.rb
Address https://github.com/openshift/verification-tests/pull/1435/files#r470642284
> No teardown should apply to upgrade-prepare only

- features/networking/multus.feature
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-overlapping.yaml
Automate OCP-33579: Additional network IPAM should support changes in range and overlapping ranges
https://privatebin-it-iso.int.open.paas.redhat.com/?a449cdfe751037ed#/RgIIu72MhFPZOD+XpEmZpKzSKv0enf0s2Nf4fWukhU=
> Automate OCP-33579

- lib/rules/web/admin_console/4.3/customizations.xyaml
- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/node.xyaml
- lib/rules/web/admin_console/base/login.xyaml
@xiaocwan  Ready for your review
> some fix and new rules

- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
Depend on PR:
https://github.com/openshift/cucushift/pull/8065
Fixed issue:
OCPQE-1882: OCP-21199 Edit Alertmanager Silence - Invalid matcher is failed on 4.6
V3 Job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/137359/console
> fix test failures for product change

- lib/rules/web/admin_console/4.6/clustersettings.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
@yapei or @xiaocwan pls help to review, thanks!
> add rule for OCP-33125

- features/build/metrics.feature
> Add automation for OCP-33722 OCP-33220

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
add the necessary `oc_opts_end` and `exec_command` options and make sure `<global_options>` appear first
> add oc adm must-gather -- /usr/bin/gather_network_ovn_trace support

- lib/world.rb
According to [comments](https://github.com/openshift/verification-tests/pull/1444/files#r471415062) , add this PR.
> Add tag check for upgrade-prepare/check

- features/cli/deploy.feature
Fix undefined step in the code
> Fix undefined step in OCP-11877

- doc/reviewer_guide.adoc
- lib/openshift/prometheus.rb
- lib/openshift/resource.rb
> reviewers guide

- lib/openshift/prometheus.rb
- lib/openshift/thanos_ruler.rb
- lib/openshift/validating_webhook_configuration.rb
- tools/find_image.rb
Depend on PR:
https://github.com/openshift/cucushift/pull/8043
> change resource check to rb file method

- lib/log.rb
> fix deduplication of more than 256 messages where UTF is used

- lib/rules/web/admin_console/4.6/operator_hub.xyaml
@xiaocwan  Please help review ,thanks
> add rules for OCP-32151

- features/step_definitions/node.rb
https://issues.redhat.com/browse/OCPQE-2069
> more debug info on taint restore error

- features/networking/ovn.feature
- features/step_definitions/pod.rb
Keep Adding more scenarios related to NB DB to this PR
@rbbratta @zhaozhanqi @huiran0826 @weliang1 
Logs OCP-29954 : https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1595/console
> NB DB scenarios

- features/build/metrics.feature
> Auto ocp-33770 ocp-25598

- lib/rules/web/ocm_console/install_page.xyaml
@yasun1 @xueli181114 @yuwang-RH Please help review the update
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/137960/console
> Updated OCP-24070

- lib/api_accessor.rb
@xingxingxia @akostadinov PTAL!
This is for `OCPQE-2082`
> Delete new format oauth token

- features/step_definitions/node.rb
> more debug info on taint restore error (#1487)

- testdata/cloud-credential/cr-namespace-no-exist.yaml
- testdata/cloud-credential/cr.yaml
Added yaml file for cloud credential operator feature
@pruan-rht @wjiangjay those yaml files are used for cloudcredential.feature, could you please take a look?
> Add config file for cco feature

- OWNERS
> Add liangxia as approver for v3 branch

- features/cli/deploy.feature
Fix repo ruby-22-centos7 is not suitable  anymore changing it to ruby-25-centos7
> Fix case OCP-16443

- lib/rules/web/admin_console/4.6/check_links.xyaml
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/142761/console
> fix skip tour issue

- lib/rules/web/ocm_console/install_page.xyaml
Fix pull secret part of install page, here is jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/147072/console.
@yasun1 @xueli181114 @yuwang-RH Please help review, thanks
> Fix install page case

- features/step_definitions/rc.rb
> Fix indention

- features/step_definitions/operators.rb
- features/upgrade/marketplace/upgrade.feature
Modify the case OCP-22618 since there is no operatorsource from OCP 4.6.
> No operatorsource from 4.6

- features/logging/collector.feature
Customer scenario for https://bugzilla.redhat.com/show_bug.cgi?id=1796133
case: https://url.corp.redhat.com/8c7ba1f
Log: https://url.corp.redhat.com/6dd12f0
> auto case OCP-32197

- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
> fix OCP-27646 for operators

- features/cli/oc_idle.feature
- testdata/rc/idling-echo-server.yaml
modify image to use digest in order to run in disconnected env.
log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2207/console
@jhou1 @sunilcio @weinliu  Can you help to review? Thanks
> fix OCP-10941

- lib/log.rb
> use only character oriented methods with StringScanner

- lib/log.rb
> complete fix for log deduplication

- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.5/check_links.xyaml
- lib/rules/web/admin_console/4.6/check_links.xyaml
@yapei Please help to review. Thanks!
Passed on 4.6: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/147781/console
> Update oc downloads and license link OCP-25802

- features/step_definitions/descheduler.rb
Add lib to restore descheduler CR
> Add lib to restore descheduler CR

- lib/openshift/etcd_cluster.rb
- lib/openshift/kiali.rb
- lib/openshift/pgcluster.rb
@liangxia  pls help to review, thanks!
> add resource define

- features/step_definitions/networking.rb
> OCP-11286: change iptables flush to be more atomic

- features/step_definitions/catalog_source.rb
- lib/openshift/catalog_source.rb
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
Ready for review @pruan-rht  @liangxia  @yanpzhan  Please help review
> auto OCP-33743

- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml
Automated the following 4 cases
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-27841
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-34901
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21257
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-24439
Depend on PR:
https://github.com/openshift/cucushift/pull/8129
> new ui test cases

- lib/openshift/credential_request.rb
I need to add type for credentialsrequest if I want to use the step (admin ensures "my-cred-request" credentialsrequest is deleted).
> add type for credentialsrequest

- features/machine/machine.feature
This is to automate OCP-33455
Validated on AWS - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/152260/console
Azure - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/150151/console
> leader election log message validation

- features/build/metrics.feature
- features/build/stibuild.feature
- features/cli/build.feature
- features/cli/create.feature
- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/networking/egress-ingress.feature
- features/networking/service.feature
- features/step_definitions/pod.rb
- features/step_definitions/registry.rb
- features/upgrade/machines/machines.feature
- features/upgrade/node/hpa/upgrade.feature
> Use proper pod/pods

- features/upgrade/etcd/upgrade.feature
Auto case to check etcd image have been update to target release value after upgrade
> Auto case OCP-22665

- features/upgrade/workloads/scheduler-upgrade.feature
- testdata/scheduler/policy_upgrade.json
> Auto scheduler upgrade case

- lib/rules/web/admin_console/4.4/clustersettings.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/clustersettings.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.6/clustersettings.xyaml
> OCP-25832 - [web console] Check upgrade channels automate the test case.

- features/networking/egress-ingress.feature
- testdata/networking/ovn-egressfirewall/egressfirewall-policy1.yaml
- testdata/networking/ovn-egressfirewall/egressfirewall-policy2.yaml
- testdata/networking/ovn-egressfirewall/egressfirewall-policy3.yaml
Auto some egressfirewall cases. Here is the logs.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2177/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2176/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2175/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2174/console
Can you help review? Thanks!
@zhaozhanqi @weliang1 @anuragthehatter @rbbratta
> auto some egressfirewall cases

- lib/rules/web/admin_console/4.6/tables.xyaml
> rules added for OCP-33568

- features/networking/egress-ip.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1976/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1977/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1978/console
@anuragthehatter @zhaozhanqi @weliang1 @rbbratta
> Auto OCP-18316 OCP-18315 OCP-19785

- lib/rules/web/admin_console/4.6/check_links.xyaml
> auto OCP-33744

- features/cli/oc_set_build_hook.feature
[Pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/158205/) @openshift/devexp-qe PTAL, thanks
> Fix OCP-11602 in v3.11

- features/cli/build.feature
- features/cli/create.feature
- features/registry/remote.feature
OCP-11023,OCP-11139,OCP-12399 [passed log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/158350/console) 
OCP-10904 [passed log]( https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/158403/console)
@openshift/devexp-qe  Please help review, thanks
> Fix scripts for v3

- features/storage/nfs.feature
- features/storage/persistent_volume.feature
Patch for v3 branch.
@duanwei33 @chao007 Please help review.
> Bugfix for PV is deleted before PVC

- lib/openshift/pod.rb
@rhpmali , please check if this works for you.
> we need to set `-i` when stdin is provided

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/creation_cards_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Here is the Jenkins build log:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/147704/console
/assign @yasun1 @yapei @liangxia @pruan-rht Could you please help to review?
> Finish some rules for url redirection cases of OCM 

- features/cli/oc_set_deployment_hook.feature
Fix it in private cluster,@openshift/devexp-qe PTAL , thanks
[pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/159426/console)
> Fix OCP-11298

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
@yanpzhan  Could you help review? Thanks
> update OCP-27901 and add checkpoints

- features/build/dockerbuild.feature
@openshift/devexp-qe PTAL, thanks
> Fix OCP-15461 in v3

- testdata/storage/csi/csi-hostpath-plugin.yaml
Original image is deleted from quay, so mirror a new one.
@qinpingli @duanwei33 Please help review it.
> Add image hostpathplugin info

- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/3.11/goto.xyaml
@yapei  This is for https://issues.redhat.com/browse/OCPQE-2287 Please review.
PASS locally http://pastebin.test.redhat.com/903844
Will add job log.
> Add rules for 3.11 for OCP-19667 and OCP-19558

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/overview.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/overview.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/overview.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/overview.xyaml
> OCP-23609 - [web console] User could use keyboard shortcut on project resources page

- features/images/jenkins.feature
- lib/rules/web/images/jenkins_2/jenkins_2.xyaml
> Auto OCP-35068

- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
> add rules for OCP-33748

- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
Update the syslogserver configurations.
@anpingli PTAL.
> update syslogserver configurations

- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
@yapei, pls help to review, thanks!
> add rules for OCP-29690

- features/logging/cluster_log_forwarder.feature
- features/step_definitions/logging.rb
- features/step_definitions/logging_metrics.rb
- lib/openshift/cluster_log_forwarder.rb
- testdata/logging/clusterlogforwarder/clf-forward-with-different-tags.yaml
- testdata/logging/clusterlogforwarder/clf-forward-with-same-tag.yaml
Cases: https://url.corp.redhat.com/1a12958
Runner-v3 logs: https://url.corp.redhat.com/d7afc62
> add automation scenarios to test forward logs with tags

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
Fix ui automation cases: OCP-28796,OCP-28795,OCP-26297,OCP-24070,OCP-21090,OCP-30121,OCP-27839,OCP-25175. 
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/167465/console. 
Please help review, @yasun1 @xueli181114 @yuwang-RH
> Fix ui automation cases

- testdata/deployment/extensions/deployment.yaml
@kasturinarra Could you help review ? thanks.
> update for OCP-11326

- lib/rules/cli/4.5.yaml
> Add rules for oc diff

- lib/rules/web/admin_console/4.2/overview.xyaml
- lib/rules/web/admin_console/4.3/overview.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
- lib/rules/web/admin_console/4.5/overview.xyaml
- lib/rules/web/admin_console/4.6/overview.xyaml
@pruan-rht PTAL. here are the smoke test results for various versions
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2407/
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2408/
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2409/
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2411/
> OCP-23609-fix - e2e ci failure fix.

- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
> rules for OCP-33716

- lib/openshift/kubelet_config.rb
add cluster resource type "kubeletconfig", and test log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2371/console [ `And I ensure "kubelet-set-negative" kubeletconfig is deleted after scenario` test pass ]
@jhou1 @sunilcio @weinliu  Can you help to review? Thanks
> add resource type "kubeletconfig"

- features/registry/registry.feature
> Use available tag for OCP-29693 and OCP-29693

- features/networking/ovn.feature
Use explicit namespace in scale commands with `-n`
Move the CNO scale to 1 register cleanup steps to before
we scale down.
It seemed like the `oc exec` commands were timing
out, so we switched to using `grep` on the server
to filter the output, but for the negative test
the `grep` will not match `"hello-pod"` so the
`oc exec` returns exit status `1`, and the step
will fail.  Adjust the steps to expect the failure.
Fix the pod references when finding the leader pods.
When we find the OVN leader pod we cache the resource
so the leader pod appears as `pod(0)`, this broke
the pod references as the `test-pods` are now
`pod(1) and pod(2)` instead of `pod(0)` and `pod(1)`.
Instead grab the pods by label and reference them that way.
> Fix OVN tests: namespace, expect grep fail, pod(0) references

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
- lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
- lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/ocm_workflow.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
- lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
Here is the jenkins log
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/185715/console
/assign @yasun1 @yapei @liangxia Could you please help to review?
> Finish rules for creation page automation of OCM for OCP-29669 and OCP-23526

- features/networking/service.feature
seems 300 is not enough for some platform, update to 600
> update the 300 to 600 second

- lib/openshift/credentials_request.rb
Fix the wrong CredentialRequest(missing lowercase "s") type to CredentialsRequest type in .rb file
> Fix type CredentialsRequest issue

- features/cli/oc_import_image.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/runner-v3/187405/console
@openshift/devexp-qe Please review, thanks!
> Fix frequent error for case OCP-12765

- features/step_definitions/networking.rb
Now that I know how to create RHEL workers I can test on RHEL.
It turns out that the RHEL7 `bridge` JSON VLAN is output is different
from RHCOS
RHCOS JSON:
```json
[{"ifname":"bridge3","vlans":[{"vlan":1,"flags":["PVID","Egress Untagged"]}]},{"ifname":"veth66451995","vlans":[{"vlan":1,"flags":["PVID","Egress Untagged"]}]}]
```
RHEL7 JSON
```json
{"bridge3":[{"vlan":1,"flags":["PVID","EgressUntagged"]}],"vethb26eb609":[{"vlan":1,"flags":["PVID","EgressUntagged"]}]}
```
It looks like we can convert the loop to check `b[1]` first in case it is an Array.  Otherwise try `b["vlans"]`
> OCP-24488: Fix for RHEL7 workers

- testdata/networking/aosqe-pod-for-ping.json
- testdata/networking/generic_test_pod_with_replica.yaml
- testdata/networking/hostnetwork-pod.json
- testdata/networking/list_for_pods.json
- testdata/networking/nodeport_pod.json
- testdata/networking/nodeport_test_pod.yaml
- testdata/networking/pod-for-ping.json
- testdata/networking/pod_with_udp_port_4789.json
- testdata/networking/pod_with_udp_port_4789_nodename.json
@anuragthehatter @huiran0826 @rbbratta @weliang1 
updated all of yaml file with new image
please help check if I missed some other, thanks.
> update the image with new build

- features/machine/machine_healthcheck.feature
- lib/openshift/machine_health_check.rb
> Fix resource type MachineHealthCheck

- features/routing/haproxy-router.feature
- features/routing/idle.feature
- features/routing/route.feature
Adjusting some smoke test cases, and updating the author to me so that other team can reach the right person directly if they have some questions on the smoke cases.
@quarterpin please help take a look. Thanks.
> update smoke tag for network edge cases

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
> rules added for OCP-28832

- features/networking/sriov.feature
- features/step_definitions/sriov.rb
- testdata/networking/sriov/pod/sriov-deployment.yaml
- testdata/networking/sriov/pod/sriov-macvlan.yaml
- testdata/networking/sriov/pod/sriov-specified-cpu.yaml
- testdata/networking/sriov/sriovnetwork/intelnetdevice.yaml
- testdata/networking/sriov/sriovnetwork/mlx277netdevice.yaml
- testdata/networking/sriov/sriovnetwork/mlx278netdevice.yaml
- testdata/networking/sriov/sriovnetwork/static-sriovnetwork.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice-without-pf.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice.yaml
- testdata/networking/sriov/sriovnetworkpolicy/mlx277-netdevice-without-mtu.yaml
- testdata/networking/sriov/sriovnetworkpolicy/mlx277-netdevice.yaml
- testdata/networking/sriov/sriovnetworkpolicy/mlx278-netdevice.yaml
- testdata/networking/sriov/sriovnetworkpolicy/wrong/invalidname.yaml
- testdata/networking/sriov/sriovnetworkpolicy/wrong/non-deviceid
- testdata/networking/sriov/sriovnetworkpolicy/wrong/non-vondor
- testdata/networking/sriov/sriovnetworkpolicy/wrong/vfnum0
automated more cases and test pass in local
> auto sriov cases

- features/networking/ovn-egress-ip.feature
- features/step_definitions/networking.rb
- lib/openshift/egress_ip.rb
- testdata/networking/ovn-egressip/egressip1.yaml
Auto OCP-33618
Logs: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2473/console
Can you help take a look? Thanks!
@rbbratta @weliang1 @anuragthehatter @zhaozhanqi
> auto OCP-33618

- features/step_definitions/catalog_source.rb
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
@yapei  pls help to review, thanks!
> auto ocp-33250

- testdata/networking/multus-cni/Pods/1interface-host-device.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
- testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
- testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml
- testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
- testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
- testdata/networking/net_admin_cap_pod.yaml
@anuragthehatter ^^
also update the centos one.
> Imageupdate

- features/logging/deploy_logging_operators_via_console.feature
- features/step_definitions/logging.rb
- features/upgrade/logging/upgrade.feature
- lib/openshift/cluster_service_version.rb
- lib/rules/web/admin_console/4.4/logging_kibana.xyaml
- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
- testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
@anpingli @geliu2016 could you please help to review this PR? Thanks.
> add automation scenario for logging upgrading

- features/routing/route.feature
- features/step_definitions/helper_services.rb
since there is file named ca.pem in the /tmp of the image and cannot be overwrited by user. So change another name
@lihongan  PTAL,thanks.
> update ca to another file since there is same name exist

- features/step_definitions/crd.rb
- features/step_definitions/metering.rb
- features/step_definitions/resources.rb
@akostadinov @liangxia @yapei  PTAL.
> Wait for CRD to be running first before createing meteringconfig and do proper cleanup

- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
- lib/rules/web/admin_console/4.6/logging_kibana.xyaml
> update rules for case OCP-36102

- lib/openshift/pod_monitor.rb
Related to PR:
https://github.com/openshift/cucushift/pull/8213
> add pod monitor resource

- features/networking/multus-ipv6.feature
- features/networking/multus.feature
- features/networking/sriov.feature
- features/step_definitions/networking.rb
- testdata/networking/net_admin_cap_pod.yaml
1 update `/usr/sbin/ip` to `/sbin/ip`
2. update the net_admin_cap_pod.yaml file with origin image to use `conntrack`
@weliang1 @anuragthehatter @huiran0826 @rbbratta 
PTAL, thanks
> update the ip bin path

- features/step_definitions/helper_services.rb
@xingxingxia @barleyer please review. Added wait_for_tcp for ldap
Job link: Runner-v3-smoke/2497/console
> Added wait_for_tcp for ldap

- features/networking/sdn.feature
@huiran0826 @anuragthehatter @weliang1 @rbbratta  PTAL, thanks
logs: 
http://pastebin.test.redhat.com/916187
> auto case OCP-36287

- features/upgrade/storage/upgrade.feature
- testdata/storage/csi/csi-hostpath-plugin.yaml
Add selector to make the plugin pod scheduled to same node with other csi pods.
@qinpingli @duanwei33  Please help to view.
> Update for OCP-28630

- lib/rules/web/admin_console/4.4/quota.xyaml
- lib/rules/web/admin_console/4.5/quota.xyaml
- lib/rules/web/admin_console/4.6/quota.xyaml
- lib/rules/web/admin_console/4.7/check_links.xyaml
- lib/rules/web/admin_console/4.7/masthead.xyaml
- lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/quota.xyaml
Some element definition changes
> some rules changes

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
@yanpzhan  Could you help review? Thanks
> replace click_tab with new actions

- lib/rules/web/admin_console/4.4/machine.xyaml
- lib/rules/web/admin_console/4.5/machine.xyaml
- lib/rules/web/admin_console/4.6/machine.xyaml
- lib/rules/web/admin_console/4.7/machine.xyaml
> rules added for OCP-28203

- features/logging/elasticsearch.feature
- testdata/logging/clusterlogging/index_management_test.yaml
@anpingli PTAL, thanks
case: https://url.corp.redhat.com/e312b4b
runner-v3 log:  https://url.corp.redhat.com/3591f88
> add case ocp-28140

- features/logging/cluster_logging_operator.feature
/cc @QiaolingTang @anpingli 
Related with [OCPQE-2784](https://issues.redhat.com/browse/OCPQE-2784)
> Clean-up OCP-19875 (test case already removed in Polarion)

- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.4/secrets.xyaml
- lib/rules/web/admin_console/4.5/actions.xyaml
- lib/rules/web/admin_console/4.5/secrets.xyaml
- lib/rules/web/admin_console/4.6/actions.xyaml
- lib/rules/web/admin_console/4.6/secrets.xyaml
- lib/rules/web/admin_console/4.7/actions.xyaml
- lib/rules/web/admin_console/4.7/secrets.xyaml
@yanpzhan  Could you help review the changes?
> fix rules related with click_one_dropdown_action

- features/step_definitions/cli.rb
For Aleks's https://github.com/openshift/cucushift/pull/8229#discussion_r525081949
Pass log: Runner-v3/209171/console
@wangke19 @akostadinov help review/merge, thx.
> add step I wait for the last background process to finish

- lib/polarshift/request.rb
> PolarShift payload should be JSON

- lib/openshift/report.rb
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2527/console
> added support for testing report exipration parameter

- features/online/notification.feature
- features/online/quota.feature
@tzhou5 @yuwang-RH @yufchang @jhou1 
OCP-10334 - [online_private_635] Enable/Disable online notification in web console - UI
OCP-10341 - [online_private_635] User could update notification types in web console - UI
OCP-12700 - [online_pro] CRUD operation to the resource quota as project owner
OCP-13171 - [accountant] CRUD operation to the resource quota as project owner
```
$ grep -r OCP-10341 -A1 -B1
features/online/notification.feature-  # @case_id OCP-10334
features/online/notification.feature:  # @case_id OCP-10341
features/online/notification.feature-  Scenario: Enable/Disable online notification in web console - UI
$ tools/polarshift.rb update-automation --no-wait OCP-10334 OCP-10341
8: from tools/polarshift.rb:488:in `<main>'
7: from …
```
> Clean-up duplicate case ID

- lib/test_case_manager.rb
> proper method name

- lib/rules/web/admin_console/4.7/logging_kibana.xyaml
For logging 4.7, same rule as https://github.com/openshift/verification-tests/pull/1635.
> add rule for kibana

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch_operator.feature
- features/support/clusterlogging_env.rb
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
@anpingli @yapei PTAL, thanks
runner-v3 log: https://url.corp.redhat.com/436fdee
cases: https://url.corp.redhat.com/9774e1c
> logging dashboard cases

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/dropdown_items.xyaml
fix rules for OCP-21686 OCP-21685 OCP-22599 OCP-26848 OCP-26641
> Fix rules20201117

- features/step_definitions/metering.rb
added more informational prints and wait for the metering-operator pod to become ready first before creating the meteringconfig.
> fixes JIRA OCPQE-2814

- features/networking/ovn.feature
- features/step_definitions/project.rb
> OCP-37031: OVN handles projects that start with a digit

- features/networking/service.feature
> move the OCP-10216 to network path

- features/logging/cluster_logging_operator.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/212717/console
> Fix the resource mismatch issue between template and scenarios

- features/logging/cluster_log_forwarder.feature
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC3164.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC5424.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_default.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_invalid_values.yaml
- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
@anpingli @QiaolingTang please do the review.
> Automated rsyslog clusterlogforwarder test cases: #OCP-33627,32643,32967,32864

- features/routing/haproxy-router.feature
fix for https://issues.redhat.com/browse/OCPQE-2816
log:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2599/consoleFull
@quarterpin could you please help review? thanks
> fix OCP-11903 etc - cookies related cases

- features/networking/ovn-egress-ip.feature
- features/step_definitions/networking.rb
- testdata/networking/ovn-egressip/egressip2.yaml
- testdata/networking/ovn-egressip/egressip3.yaml
Auto some ovn egress IP cases.
Logs:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2485/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2486/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2487/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2488/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2489/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2490/console
> Auto some ovn egress ip cases

- features/registry/registry.feature
Docker Hub rate limiting policies，so change to use quay.io images
> Update dockerhub to use images in quay.io

- tools/launch_instance.rb
> try to handle TERM/INT gracefully and generate vminfo.yml

- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/storage.xyaml
- lib/rules/web/admin_console/4.4/style.xyaml
- lib/rules/web/admin_console/4.5/actions.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/storage.xyaml
- lib/rules/web/admin_console/4.5/style.xyaml
- lib/rules/web/admin_console/4.6/actions.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/storage.xyaml
- lib/rules/web/admin_console/4.6/style.xyaml
- lib/rules/web/admin_console/4.7/actions.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/configmap.xyaml
- lib/rules/web/admin_console/4.7/deployment.xyaml
- lib/rules/web/admin_console/4.7/storage.xyaml
- lib/rules/web/admin_console/4.7/style.xyaml
- lib/webauto/web4cucumber.rb
> some 47 rules updates

- features/networking/egress-ip.feature
- features/networking/service.feature
> replace caddy to nginx for network part

- features/build/dockerbuild.feature
- features/build/stibuild.feature
- features/cli/build.feature
- features/online/imagestreams.feature
- features/registry/is.feature
- features/registry/remote.feature
- features/step_definitions/networking.rb
- features/test/obsolete_update_from_api_object.feature
- features/test/registry.feature
- testdata/build/ocp11224/test-buildconfig.json
- testdata/build/ocp11474/test-buildconfig-s2i.json
- testdata/build/ocp11550/test-buildconfig.json
- testdata/build/ruby20rhel7-context-docker.json
- testdata/build/ruby20rhel7-invalidcontext-docker.json
- testdata/deployment/ocp10902/history-limit-dc.yaml
- testdata/pods/busybox-pod.yaml
- testdata/templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
/cc @jhou1 @xiuwang @pruan-rht
> Replace image from docker.io to quay.io

- lib/polarshift/request.rb
- lib/polarshift/test_record.rb
> Add update_caseruns_smart

- features/machine/machine.feature
fix OCP-33056 to make sure the machine could join the cluster.
> fix OCP-33056

- lib/rules/web/admin_console/4.4/route.xyaml
- lib/rules/web/admin_console/4.4/user_management.xyaml
- lib/rules/web/admin_console/4.5/route.xyaml
- lib/rules/web/admin_console/4.5/user_management.xyaml
- lib/rules/web/admin_console/4.6/route.xyaml
- lib/rules/web/admin_console/4.6/user_management.xyaml
- lib/rules/web/admin_console/4.7/catalog.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
- lib/rules/web/admin_console/4.7/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.7/overview.xyaml
- lib/rules/web/admin_console/4.7/route.xyaml
- lib/rules/web/admin_console/4.7/user_management.xyaml
@yanpzhan Can you help review? Thanks
> update some rules

- features/machine/machine.feature
- testdata/cloud/ms-aws/ms_tenancy_dedicated.yaml
OCP-37132
Here is the validation result 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/218820/console
@jhou1  @sunzhaohua2  PTAL , when you get time tommorrow.
> machineset with dedicated tenancy on aws

- features/cli/rolling_deploy.feature
- features/step_definitions/pod.rb
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/118013/console
@kasturinarra Please help review , thank.
> update for deployer pod collect logs

- lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.7/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.7/monitoring_metrics.xyaml
Related PR
https://github.com/openshift/cucushift/pull/8305
> fix 4.7 UI change caused test failure

- features/step_definitions/logging.rb
The eventrouter pod always in imagepullbackoff status, I checked the images in brew registry, there doesn't have image openshift4/ose-logging-eventrouter:v4.7(it only has image with image digest, it's hard to get the image digest when running automation), but it has rh-osbs/openshift-ose-logging-eventrouter:v4.7. To resolve the issue, I update the image registry, @anpingli PTAL, thanks.
> fix eventrouter imagepullbackoff issue in 4.7

- features/build/buildlogic.feature
- features/cli/build.feature
- features/images/rhel8_images.feature
- features/step_definitions/helper_services.rb
@openshift/devexp-qe  PTAL, thanks
> Replace image from docker to quay

- features/cli/status.feature
- testdata/cli/standalone-rc.yaml
- testdata/deployment/rolling.json
Fix image failures & change the output to match to right ones
> Fix image failures & output inconsistency

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
Add 4 new ocm ui case, please help review @yasun1 @xueli181114 @yuwang-RH 
Here is jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/225365/console
And the related PR: https://github.com/openshift/cucushift/pull/8306
> Add OCP-28136 OCP-35840 OCP-35653 OCP-35652

- features/upgrade/olm/upgrade.feature
> Fix OCP-22615

- lib/rules/web/ocm_console/archived_cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_machinepool_tab.xyaml
- lib/rules/web/ocm_console/cluster_detail_monitoring_tab.xyaml
- lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Here is the Jenkins log
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/230707/console
The failed cases are failed due to known issue
> Add rules for machine pool and fix some rules in OCM (#66)

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
- lib/rules/cli/4.5.yaml
@openshift/devexp-qe  PTAL thanks
> Add build option

- features/machine/machine_healthcheck.feature
Closing previous PR - https://github.com/openshift/verification-tests/pull/1763
Validations for both passed 
@jhou1  @sunzhaohua2  , have a look when time permits
> Fix 33714 34095

- features/step_definitions/scheduler.rb
Adjust existing function so that it accepts both kubescheduler & scheduler CRD.
> Adjust existing function to accept kubescheduler as well

- features/cli/job.feature
- testdata/job/job_with_0_activeDeadlineSeconds.yaml
- testdata/job/job_with_long_activeDeadlineSeconds.yaml
- testdata/templates/ocp11206/job.yaml
Fix image still use the docker.io.
> update for image pull failed

- testdata/routing/abrouting/abtest-websrv1.yaml
- testdata/routing/abrouting/abtest-websrv2.yaml
- testdata/routing/abrouting/abtest-websrv3.yaml
- testdata/routing/abrouting/abtest-websrv4.yaml
- testdata/routing/web-server-1.yaml
- testdata/routing/web-server-rc.yaml
@xiuwang please help take a look. thanks
> update nginx-alpine image digest

- features/step_definitions/scheduler.rb
Have updated the params as discussed in the patch here https://github.com/openshift/cucushift/pull/8327#discussion_r548801213
> Fix parameters in step definition

- features/cli/build.feature
- features/cli/oc_import_image.feature
@openshift/devexp-qe  please help review, thanks
> Replace docker images

- features/cli/deploy.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/234025/console
@kasturinarra Please help review , thanks.
> replace image with quay

- features/upgrade/cloudcredential/upgrade.feature
Add cloud-credential-operator component upgrade test.
> Automated cco upgrade test case

- features/storage/csi.feature
@duanwei33  Please help to review.
It is auto for prod env.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/231705/console
> Auto OCP-37827

- lib/webauto/web4cucumber.rb
> handle Unable to locate element collection

- lib/webauto/web4cucumber.rb
> revert changes in web4cucumber

- features/step_definitions/_constants.rb
- features/step_definitions/operators.rb
- features/test/apiserver.feature
@xingxingxia, Please help to review the PR, here is test results: Runner-v3-smoke/2641/console
> Make sure some conditions of the operator are ready

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_idp.xyaml
fix rules for OCP-21685  OCP-28661 OCP-23707 OCP-24006
> fix rules for OCP-21685  OCP-28661 OCP-23707 OCP-24006

- features/upgrade/workloads/scheduler-upgrade.feature
Fixing scenario name as it is same for both ocp43 and ocp44 cases due to which script is failing on 4.4
> Fix scenarioname

- features/step_definitions/file.rb
supersedes #1465
@rbbratta, do you think something important for you is missing from this PR or needs amendment?
/assign @rbbratta
> better testfile copy

- features/build/buildlogic.feature
> Replace docker image

- features/images/rhel8_images.feature
> fix OCP-31249

- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/overview.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/overview.xyaml
4.6 pass log https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/257715/parameters/
4.5 pass log https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/257716/console
> z-stream fixes

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_machinepool_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Here is the jenkins job
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/257863/console
> Update rules for machine pool creation in OCM 

- lib/openshift/catalog_source.rb
- lib/rules/web/admin_console/4.7/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
@yanpzhan  Ready for your review, PTAL thanks
> support added for OCP-37098

- features/networking/egress-ingress.feature
- testdata/networking/ovn-egressfirewall/egressfirewall-policy4.yaml
Auto EgressFirewall cases: OCP-37496,OCP-37495,OCP-37491
Logs:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2794/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2793/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2792/console
@zhaozhanqi @anuragthehatter @rbbratta @weliang1
> Auto some egressfirewall cases for dnsname

- lib/rules/web/admin_console/4.4/user_management.xyaml
- lib/rules/web/admin_console/4.5/user_management.xyaml
- lib/rules/web/admin_console/4.6/user_management.xyaml
- lib/rules/web/admin_console/4.7/user_management.xyaml
this is the rule updates and the feature fix PR is cucushift#8387
> rules update

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_idp.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
update rules for OCP-21685 OCP-26823 OCP-26641
> update rules for OCP-21685 OCP-26823 OCP-26641

- features/cli/oc_delete.feature
Runner-v3 log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/260598/console
> Fix case 12144

- lib/rules/web/admin_console/4.5/node.xyaml
- lib/rules/web/admin_console/4.6/node.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
- lib/rules/web/admin_console/4.7/node.xyaml
@pruan-rht Could you help review the fixes? Thank you!
> some rule updates

- features/upgrade/routing/upgrade.feature
- testdata/routing/operator/ingressctl-ns-shards.yaml
logs:
upgrade-prepare: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/265560/console
upgrade-check: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/265651/console
@quarterpin please help take a look. 
cc @jechen0648
> auto OCP-38812

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
[Pass  log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/265971/console) in 4.7 cluster, no need to change 4.6 files, it passed before @yapei  please check it, thanks
Related pr: https://github.com/openshift/cucushift/pull/8393
> Fix OCP-24106

- features/cli/projects.feature
@xingxingxia, update the -docker-image=quay.io/openshifttest/mysql-56-centos7 due to docker resource accessing limitation,  test results: Runner-v3/273047/console, please help to review.
> Fix pulling image limitation from docker

- tools/jenkins/slaves/Dockerfile.rhel7
Follow up of https://github.com/openshift/verification-tests/pull/1835
> Add option skip_if_unavailable to all repos

- lib/rules/web/admin_console/4.7/check_links.xyaml
@yapei  Please review it, thanks
[4.7 pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/267597/)
Fyi: no need to update 4.6 files, it [passed](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/267607/) in master branch
> Fix OCP-19675

- features/step_definitions/helper_services.rb
- lib/rules/cli/4.5.yaml
Add lib for `oc image info` command , and update "I have a registry in my project" with deploy. I've checked no case use the step: I have a registry in my project.  So the change will not effect other case. 
@kasturinarra  Please help review, thanks.
> update for auto-ocp-37363

- features/test/apiserver.feature
@xingxingxia, Fix the problem in https://github.com/openshift/verification-tests/pull/1719 mentioned at the last comments, here is test results: Runner-v3-smoke/2859/console, please help to review, thanks.
> Remove quotes from conditions

- testdata/logging/clusterlogforwarder/fluentd/secure/configmap.yaml
- testdata/logging/logforwarding/fluentd/secure/configmap.yaml
Runner-v3 log:  https://url.corp.redhat.com/342ffa2
@anpingli PTAL
> correct wrong configurations in secure fluentd server

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/monitoring.xyaml
- lib/rules/web/admin_console/4.5/monitoring.xyaml
- lib/rules/web/admin_console/4.6/monitoring.xyaml
- lib/rules/web/admin_console/4.7/monitoring.xyaml
@pruan-rht  Could you help review? Thank you
> update rules for OCP-25816

- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
fix rule for OCP-32152, pls help to review, thx! @yapei
> fix OCP-32152

- lib/launchers/o_c_m_cluster.rb
> Fix deleting OSD cluster via OCM

- lib/rules/web/admin_console/4.7/status.xyaml
Pass log on 4.7 https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/279085/console
Pass log on 4.6: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/279086/console
Pls help to review, thanks! @yapei
> fix OCP-21772

- features/networking/metrics.feature
- features/networking/ovn_winc.feature
ovn prometheus functionality check. This case might need upgdation in 4.8 as metrics are still being developed by dev
However we should keep checking 4.6  and 4.7 meanwhile
Logs:https://privatebin-it-iso.int.open.paas.redhat.com/?8d915e6f6d8980e9#FiKL5R5gfFYZcRi25kvhhsdJ2PvsK1p9RDNVsB7qQto
@zhaozhanqi @huiran0826 @weliang1 @rbbratta @asood-rh @brahaney @kedark3
> Ovn metrics

- features/step_definitions/logging.rb
Runner-v3 logs:
5.0: https://url.corp.redhat.com/2ca10c3 (case failed due to a known bug)
4.6: https://url.corp.redhat.com/ce3766d
4.5: https://url.corp.redhat.com/2fa8c1b
/cc @anpingli @gkarager PTAL, thanks.
> update the eventrouter image to match logging 5.0

- features/networking/ovn_ipsec.feature
- features/step_definitions/networking.rb
- lib/openshift/network_operator.rb
@rbbratta @zhaozhanqi @huiran0826 @asood-rh @brahaney @kedark3 @weliang1 Please provide comments if any
Test Logs: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2875/consoleFull
> IPsec automation and supported code

- features/step_definitions/web.rb
- lib/openshift/cluster_operator.rb
- lib/rules/web/admin_console/4.6/clustersettings.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.7/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
> add feature for OCP-33402

- features/step_definitions/networking.rb
Dump some debug info when multus pods are not all present
> Debug multus daemonset failures

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/creation_cards_page.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
The related PR: https://github.com/openshift/cucushift/pull/8426
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/298970/console
Please help review cases, thanks. @yasun1 @xueli181114 @yuwang-RH
> Add OCP-38887,OCP-38888 and update OCP-21090,OCP-22101,OCP-24973,OCP-25175

- features/networking/ovn-egress-ip.feature
- testdata/networking/ovn-egressip/egressip1.yaml
- testdata/networking/ovn-egressip/egressip2.yaml
- testdata/networking/ovn-egressip/egressip3.yaml
Updated "og" to "org"
Rerun cases passed and Log is here: 
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2901/console
@kedark3 @pruan-rht
> Update og to org

- lib/rules/web/ocm_console/archived_clusters.xyaml
- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/ocm_workflow.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Here is the jenkins log
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/300486/console
> Update rules for archive, add-on, cluster creation cases in OCM 

- features/step_definitions/operators.rb
syntax error.  https://www.geeksforgeeks.org/ruby-decision-making-if-if-else-if-else-if-ternary-set-1/#ifelseifladder
> fixes issue 1876

- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
Case OCP-21339 failed due to known bug: [SDA-3540](https://issues.redhat.com/browse/SDA-3540)
The related PR: https://github.com/openshift/cucushift/pull/8431
Please help review cases, thanks. @yasun1 @xueli181114 @yuwang-RH
> New auto OCP-35327,OCP-38889, update OCP-21339,OCP-25189

- features/step_definitions/container.rb
- lib/rules/web/admin_console/4.7/pods.xyaml
> add support for OCP-37526

- features/networking/operator.feature
After the debugging this case more times. the origin steps cannot make sure all nodes in the cluster in ready status after the scenario. since the machine replica number restore however the node may need time to terminate. So here update the step to make sure it more stable. 
logs: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2900/console
@anuragthehatter @huiran0826 @rbbratta @weliang1 @asood-rh @kedark3 @brahaney
> update case OCP-22202

- features/step_definitions/helper_services.rb
> fix private registry

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
Update OCP-28142,OCP-33436,OCP-33436,OCP-35652,OCP-38887,OCP-35653,OCP-35327.
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/304382/console
@yasun1 @xueli181114 @yuwang-RH Please help review cases, thanks
> Update xpath for multi OCM cases

- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
Pass log on 4.7: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/305381/console
@yapei, pls help to review, thanks!
> fix for 27495

- lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/dropdown_items.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
> Fix xpath in OCM (#70)

- tools/launch_instance.rb
> hotfix the decoding fix

- tools/launch_instance.rb
This reverts commit e60f47dd73c255d0db9393a93c7151d42f9259a4.
This reverts commit 63b0e1b33144d01bbb6c4491ebf1eab28d72a670.
> Revert the decoding fixes.

- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.5/route.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/route.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.7/route.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/pods.xyaml
- lib/rules/web/admin_console/4.8/route.xyaml
4.8 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/310243/console
> fix some rules

- features/step_definitions/local_storage.rb
- features/test/storage.feature
- lib/openshift/flakes/discovered_devices.rb
- lib/openshift/local_volume_discovery.rb
- lib/openshift/local_volume_discovery_result.rb
@duanwei33 Please review this and let me know if suits your needs
> added support for localvolumediscoveryresult

- lib/rules/web/admin_console/4.8/user_management.xyaml
> fix OCP-25762

- features/step_definitions/node.rb
Add func to run commands on host after scenario
> Add func to run commands on host after scenario

- lib/rules/web/admin_console/4.5/logs.xyaml
- lib/rules/web/admin_console/4.6/logs.xyaml
- lib/rules/web/admin_console/4.7/logs.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
> fix some rules in 4.8

- config/config.yaml
- lib/configuration.rb
@pjanouse, could you review and tell me what do you think about such changes?
2 issues fixed is that file content is base 64 encoded so we need to decode it.
Also added more methods from string so that usage of these values is more
transparent.
/assign pjanouse
> files are base64 encoded and better string emulation

- features/networking/egress-ingress.feature
Sometimes the case failed in ci as the response code is 204, not 200, updated the code to be compatible with 204. 
Logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/runner-v3/317271/console
@zhaozhanqi @anuragthehatter @weliang1 @rbbratta @asood @brahaney @kedark3
> fix OCP-11639

- lib/rules/web/admin_console/4.8/logs.xyaml
Removing the space in front of the button name.
> OCP-20688-Fix the button name by removing space from the front.

- features/storage/csi.feature
To resolve [this jira](https://issues.redhat.com/browse/OCPQE-3605) without modifying too many test run templates, merge OCP-37827 with OCP-30787 as they are doing the same thing.
@qinpingli PTAL
> Merge OCP-37827 with OCP-30787

- lib/rules/web/admin_console/4.3/customizations.xyaml
- lib/rules/web/admin_console/4.4/customizations.xyaml
- lib/rules/web/admin_console/4.5/customizations.xyaml
- lib/rules/web/admin_console/4.6/customizations.xyaml
- lib/rules/web/admin_console/4.7/customizations.xyaml
- lib/rules/web/admin_console/4.8/customizations.xyaml
Runner-v3 success for last three versions
4.8
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317563/parameters/
4.7
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317579/parameters/
4.6
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/317580/parameters/
Raised PR#8449 in cucushift to take care of feature file changes.
> OCP-25817 fix-the-button-name and taking care of prior versions also

- features/networking/multus-ipv6.feature
- features/networking/multus.feature
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/IPv6/macvlan-bridge-v6.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/host-device.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/ipam-dhcp.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/ipam-static.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-bridge.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-conf-without-master.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-private.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/macvlan-vepa.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/route-override.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-excludeIP.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-macvlan.yaml
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-overlapping.yaml
@weliang1 please help take look, thanks
> update the cniverion to 0.3.1

- features/upgrade/storage/upgrade.feature
@liangxia Could you help take a look for the format issue?
> Update upgrade case id for update-automation

- lib/openshift/console_operator.rb
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
> rules added for OCP-39596

- features/machine/machine.feature
- lib/openshift/machine.rb
- testdata/cloud/ms-aws/ms_default_values.yaml
- testdata/cloud/ms-aws/ms_tenancy_dedicated.yaml
thanks @sunzhaohua2 for pointing this , PTAL ..
>  Removed code , which wasnt checking status , would have passed always

- lib/rules/web/ocm_console/archived_cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Here is Jenkins result: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/6907/console
The related PR is: https://github.com/openshift/cucushift/pull/8466
Please help review cases, thanks. @yasun1 @xueli181114 @yuwang-RH
> Add OCP-39958 and update OCP-29426,OCP-21338,OCP-24973,28142

- features/machine/machine.feature
/cc @miyadav @jhou1 
```
$ tools/polarshift.rb update-automation OCP-32269
20: from tools/polarshift.rb:488:in `<main>'
19: from tools/polarshift.rb:262:in `run'
18: from /usr/share/gems/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
17: from /usr/share/gems/gems/commander-4.5.2/lib/commander/runner.rb:68:in `run!'
16: from /usr/share/gems/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
15: from /usr/share/gems/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
14: from /usr/share/gems/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
13: from tools/polarshift.rb:64:in `block (2 levels) in run'
12: from /home/lxia/code-bases/github.com/verification-tests/lib/gherkin_parse.rb:73:in `locations_for' …
```
> Fix case ID format

- features/networking/pod.feature
sometimes the auto steps may run fast caused the `conntrack` have not shown it
@huiran0826 @rbbratta @anuragthehatter @weliang1 @asood-rh @kedark3   @brahaney
> add waiting time to make sure case stable

- features/step_definitions/env.rb
Add func to check if cluster is SNO
> Add func to check if cluster is SNO

- features/build/buildconfig.feature
- features/build/dockerbuild.feature
- features/build/env.feature
- features/cli/build.feature
- features/cli/create.feature
- features/upgrade/build/build-upgrade.feature
- testdata/build/application-template-stibuild.json
- testdata/build/ruby20rhel7-template-sti.json
> Deprecate ruby:2.5

- features/logging/kibana.feature
https://bugzilla.redhat.com/show_bug.cgi?id=1925081 
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/318450/console
> Verify the token are encrypted in kibana log

- README.adoc
@pruan-rht adding some info about RVM for new users of this repo. Please review.
> Adding RVM info

- lib/openshift/daemon_set.rb
helper methods for https://github.com/openshift/cucushift/pull/8479
> added methods to support getting daemon set properties

- features/logging/cluster_logging_operator.feature
- testdata/logging/clusterlogging/cl_fluentd-buffer.yaml
- testdata/logging/clusterlogging/cl_fluentd-buffer_Invalid.yaml
- testdata/logging/clusterlogging/cl_fluentd-buffer_default.yaml
Automated test cases related [LOG-742](https://issues.redhat.com/browse/LOG-742)- Expose more fluentd knobs to support optimizing fluentd for different environments
@QiaolingTang @anpingli Please review
> Automation of LOG-742

- tools/polarshift.rb
> Add tag flaky to sync back to polarion

- features/upgrade/sdn/policy-upgrade.feature
Change the post upgrade check scenario description for test case OCP-38751 to resolve conflict another scenario name.
@zhaozhanqi 
@pruan-rht
> Scenario name change to avoid conflict

- features/build/buildconfig.feature
- features/build/dockerbuild.feature
- features/build/env.feature
- features/cli/build.feature
- features/cli/create.feature
- features/registry/is.feature
- features/registry/registry.feature
- features/registry/remote.feature
- testdata/build/application-template-dockerbuild.json
- testdata/build/ruby22rhel7-template-docker.json
- testdata/templates/ocp11552/ruby22rhel7-template-docker.json
- testdata/templates/ocp12041-s2i.json
> Modify source build using latest tag, docker build using quay.io images

- features/step_definitions/machine_set.rb
- lib/openshift/machine_set.rb
Update step `I pick a random machineset to scale` in case windows machineset is selected in a cluster with windows nodes. @jhou1 @miyadav please help to take a look.
> Update step `I pick a random machineset to scale`

- tools/polarshift.rb
fixes JIRA https://issues.redhat.com/browse/OCPQE-3399
> fix error when there's no CustomField in the original testrun

- features/cli/OWNERS
- features/infrastructure/OWNERS
- features/online/OWNERS
- lib/rules/web/admin_console/OWNERS
> Update feature owners/reviewers

- features/build/buildlogic.feature
- features/step_definitions/helper_services.rb
- features/step_definitions/registry.rb
- lib/rules/cli/4.5.yaml
@openshift/devexp-qe  The case passed on my localhost, http://pastebin.test.redhat.com/954310
Please help review, thanks
> Auto case OCP-40366

- features/networking/egress-ingress.feature
- features/networking/sdn.feature
- testdata/networking/ovn-egressfirewall/egressfirewall-policy5.yaml
Auto OCP-41132 OCP-41179
Logs:
https://privatebin-it-iso.int.open.paas.redhat.com/?748c12a2010d55a1#23GZVV2RSSVsWMN9Us3SJ4Cxmfokj9GgyTPXkb8WMk17
https://privatebin-it-iso.int.open.paas.redhat.com/?9b1b8a78f8f6e10b#BDZzPtVW6ta8Fpqkyi2oQPSv4s9FzcQ8CUfP3B3qvuey
Could you help take a look? Thanks!
@rbbratta @weliang1 @zhaozhanqi  @asood-rh @kakkoyun @brahaney
> Auto OCP-41132 OCP-41179

- features/storage/NoDiskConflict.feature
- features/storage/storage_class.feature
@duanwei33 @chao007 Please help review.
> Fix the automation issue found in aws test

- features/upgrade/build/build-upgrade.feature
- testdata/templates/ocp12041-s2i.json
> replace upgrade ruby image

- features/step_definitions/scheduler.rb
with the previous way the function can only be used with kube-scheduler, but with the change in this PR we should be able to be use it with any CR.
> Customize the function so that it can be used with any CR

- lib/rules/web/admin_console/4.8/clustersettings.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
Pass log on 4.8:
OCP-28832: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/319780/console
OCP-33125: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/319767/console
@yapei pls help to review, thanks!
> fix OCP-28832 OCP-33125

- features/step_definitions/kata.rb
- features/step_definitions/resources.rb
- lib/openshift/kata_config.rb
- testdata/kata/release-4.8/deployment.yaml
- testdata/kata/release-4.8/kataconfiguration_v1_kataconfig.yaml
> kata automation support for 4.8 release

- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Update multi cases about install page and creation page in OCM portal.
Related cases: OCP-24068,OCP-24069,OCP-24071,OCP-28794,OCP-25176,OCP-28796,OCP-36034,OCP-24070,OCP-26297,OCP-30121,OCP-25174,OCP-28795,OCP-27839,OCP-36001,OCP-24072,OCP-38888,OCP-38889,OCP-41209
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/37440/console
The related PR is: https://github.com/openshift/cucushift/pull/8522
@yasun1 @xueli181114 @yuwang-RH Please help review cases, thanks
> Update multi ocm cases due to new features

- features/step_definitions/nfd.rb
added support for NFD OLM CLI installation
> added support for NFD OLM CLI installation

- features/cli/build.feature
> Fix OCP-18962

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
- lib/rules/web/ocm_console/register_disconnected_cluster_page.xyaml
This update related with OCP-35327,OCP-21306,OCP-24973,OCP-39958,OCP-22101,OCP-28142,OCP-25189,OCP-28136,OCP-21090,OCP-21338,OCP-38887.
Jenkins cannot login successfully now, will paste the log later.
The related PR is: https://github.com/openshift/cucushift/pull/8528
@yasun1 @xueli181114 @yuwang-RH Please help review, thanks
> Fix multi ocm cases

- lib/manager.rb
- tools/openshift-ci/Dockerfile.centos
> [hotfix] for scenario skipping fix

- doc/configuration.adoc
master branch is for OCP 4, so use OCP4 by default, and in the examples.
/cc @pruan-rht @jhou1 @JianLi-RH
> Use OCP4 by default and as examples

- features/storage/NoDiskConflict.feature
@duanwei33 @chao007  Please help review, thanks!
> Add NoDiskConflicts label to the worker node only

- lib/world.rb
> Cucumber built-in parameter types happen before our transform hack and confuse our code with numeric values

- features/node/kata/install_uninstall.feature
- features/step_definitions/kata.rb
- features/test/kata.feature
- lib/openshift/kata_config.rb
- testdata/kata/release-4.8/deployment.yaml
- testdata/kata/release-4.8/subscription.yaml
@liangxia @cpmeadors @valtair1891 PTAL
> fix automation to work with new kata plugin image

- features/build/buildlogic.feature
@openshift/devexp-qe please help review it, thanks
> Update perl to use latest tag

- features/logging/cluster_log_forwarder.feature
- features/logging/logging_acceptance.feature
- features/step_definitions/logging.rb
- features/test/logging_metrics.feature
- lib/environment.rb
https://issues.redhat.com/browse/OCPQE-3595 
Adding env  var `logging_sub_envs`
```
logging_sub_envs:
clo:
catsrc: "test"
channel: "4.1"
eo:
catsrc: "redhat"
channel: "5.1"`
```
/cc @anpingli
> update env var for logging testing

- Gemfile
- OWNERS
- config/config.yaml
- config/cucumber.yml
- features/step_definitions/debug.rb
- features/step_definitions/transform.rb
- features/support/cucu_formatter.rb
- features/support/env.rb
- features/support/save_to_dir_embedding_formatter.rb
- features/test/debug.feature
- features/test/transformations.feature
- lib/configuration.rb
- lib/log.rb
- lib/manager.rb
- lib/polarshift/scenario_wrapper.rb
- lib/polarshift/test_case.rb
- lib/polarshift/test_record.rb
- lib/polarshift/test_suite.rb
- lib/test_case_manager.rb
- lib/test_case_manager_filter.rb
- lib/world.rb
- tools/launch_instance.rb
- tools/openshift-ci/Dockerfile.centos
@liangxia, I didn't test this change. I just went through recent pull requests
and added what I identifyied as necessary to backport + some conflict fixes.
HTH
> backporting of Cucumber 5, ReportPortal and other recent changes

- features/storage/csi_clone.feature
- testdata/storage/csi/pod_clone.yaml
- testdata/storage/csi/pod_pvc_sc.yaml
> automate OCP-27615: Clone a pvc with filesystem VolumeMode in the same namespace is successfully	

- lib/launchers/o_c_m_cluster.rb
- test/lib/launchers/o_c_m_cluster_test.rb
> ONEOCPDEPL-92: Reflect the latest changes in OCM

- features/upgrade/machines/machines.feature
Auto OCP-41175 Spot/preemptible instances should not block upgrade @jhou1 @miyadav please help to take a look.
Before upgrade:
```
[06:46:51] INFO> === End After Scenario: Spot/preemptible instances should not block upgrade - prepare ===
14 steps (14 passed)
4m1.068s
```
After upgrade:
```
[15:46:04] INFO> === End After Scenario: Spot/preemptible instances should not block upgrade ===
8 steps (8 passed)
1m40.336s
```
> [upgrade] Spot/preemptible instances should not block upgrade

- features/machine/machine_healthcheck.feature
- features/networking/egress-ip.feature
Same as https://github.com/openshift/cucushift/pull/8550, but for verification-tests.
/cc @miyadav @huiran0826 @jhou1
> Fix issue OCPQE-3994

- features/routing/OWNERS
> Add subteam approvers

- lib/openshift/infrastructure.rb
Used by PR:
https://github.com/openshift/cucushift/pull/8545
> Get config infrastructure

- features/upgrade/machines/machines.feature
@jhou1 @miyadav please help to review.
before upgrade:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/56080/console
after upgrade:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/56137/console
> fix "could not find all scenarios"

- features/upgrade/logging/upgrade_with_clf.feature
Fix failure when checking data in external ES, e.g.:  https://url.corp.redhat.com/08cbbc8
/cc @anpingli
> fix failure when checking data

- features/node/kata/smoke_tests.feature
automated case OCP-41263
runlog: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3101/console
> kata_smoke_test_suite

- features/support/save_to_dir_embedding_formatter.rb
- lib/log.rb
- lib/webauto/web4cucumber.rb
/cc @yapei @yanpzhan @pruan-rht @jhou1 @JianLi-RH  for review.
> Use attach to replace deprecated embed

- features/machine/machine_misc.feature
/cc @miyadav @jhou1  for review
> Update OCP-37744 to workaround OCPQE-3994

- features/support/save_to_dir_embedding_formatter.rb
- lib/log.rb
- lib/webauto/web4cucumber.rb
> Reorder the log info

- features/storage/csi.feature
@jhou1 @duanwei33 Please help review this test cases.
I will add test cases for other platform 
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/59795/console
> Add csi auto cases about Retain

- lib/rules/web/admin_console/OWNERS
> Add yapei as approver for web cases

- lib/rules/web/admin_console/4.8/builds.xyaml
- lib/rules/web/admin_console/4.8/catalog.xyaml
- lib/rules/web/admin_console/4.8/check_links.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.8/environments.xyaml
- lib/rules/web/admin_console/4.8/filters.xyaml
- lib/rules/web/admin_console/4.8/goto.xyaml
- lib/rules/web/admin_console/4.8/idp.xyaml
- lib/rules/web/admin_console/4.8/machine.xyaml
- lib/rules/web/admin_console/4.8/monitoring.xyaml
- lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.8/node.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/pods.xyaml
- lib/rules/web/admin_console/4.8/projects.xyaml
- lib/rules/web/admin_console/4.8/quota.xyaml
- lib/rules/web/admin_console/4.8/route.xyaml
- lib/rules/web/admin_console/4.8/search.xyaml
- lib/rules/web/admin_console/4.8/status.xyaml
- lib/rules/web/admin_console/4.8/storage.xyaml
- lib/rules/web/admin_console/4.8/style.xyaml
- lib/rules/web/admin_console/4.8/tables.xyaml
- lib/rules/web/admin_console/4.8/user_management.xyaml
> Test OWNERS in sub-folder

- tools/polarshift.rb
> added option to selective clone of run

- features/cli/policy.feature
- features/storage/dynamic_provisioning.feature
- features/storage/fsType.feature
- features/storage/persistent_volume.feature
- features/storage/quota.feature
- features/storage/reclaim_policy.feature
- features/storage/security.feature
- features/storage/storage_class.feature
- features/storage/vsphere.feature
> add smoke tag

- features/step_definitions/kata.rb
- testdata/kata/release-4.8/deployment.yaml
- testdata/kata/release-4.8/subscription.yaml
@cpmeadors can you PTAL?  I've tested it locally and the automated tests are passing once again after the modifications.
> kata subscription needs to be updated with the latest build

- features/step_definitions/volume_snapshot.rb
- testdata/storage/snapshot/volumesnapshotclass-aws.yaml
[test log](https://privatebin-it-iso.int.open.paas.redhat.com/?c748e00496127888#8fhtRQwNCSgMXs3UX7Db5QSKN55y5ppKUf4nFEBZg7S4)
@jhou1 @chao007 @liangxia   PTAL, thanks.
> Add step to create VolumeSnapshotClass

- config/config.yaml
- doc/configuration.adoc
- tools/launch_instance.rb
@akostadinov Please review the optimized implementation
WIP is due to missing docs (as we agreed it will be subject of ONEOCPDEPL-10 too), I'm going to create it and add as a separate commit.
> [ONEOCPDEPL-10] Added configuration block of environment variables

- tools/sync_tc_tags_to_polarion.sh
/cc @duanwei33 @pruan-rht @jhou1
> Add ability to exclude test cases for sync

- features/storage/csi_clone.feature
- testdata/storage/csi/pvc-clone.yaml
pass log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3104/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3107/console
@chao007 @jhou1 Could you please take a look?
> Automate for OCP-27689 and OCP-27690

- tools/sync_tc_tags_to_polarion.sh
@chao007 @liangxia PTAL, thanks.
> Add localvolume cases into ignore list

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
- lib/rules/web/ocm_console/subscription_page.xyaml
fix automation error for tzhou's cases
> fix automation error for tzhou's cases

- lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.8/goto.xyaml
> rules added for OCP-40405

- lib/rules/web/ocm_console/OWNERS
/cc @xueli181114 @yasun1 
I'm just adding an sample there, you can update the list at any time.
> Add OWNERS file for OCM

- features/storage/csi_clone.feature
[pass log](https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3143/consoleFull)
@jhou1 @chao007 PTAL, thanks.
> Automate OCP-30315

- features/logging/elasticsearch.feature
- features/step_definitions/logging.rb
- features/upgrade/logging/upgrade.feature
- testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
Add steps to process ES storage configurations when creating clusterlogging.
> update the step to deploy logging pods

- lib/openshift/volume_snapshot.rb
Current logic is wrong.  We just need to check for  status.readyToUse to be true to be considered 'ready'.  Also added method 'wait_til_ready'
```
Then the expression should be true> volume_snapshot("mysnapshot").wait_till_ready(user: user) # features/step_definitions/common.rb:133
[01:00:52] INFO> After 0 iterations and 21 seconds:
```      
@duanwei33, PTAL,
> fix volume_snapshot readiness check

- features/step_definitions/helper_services.rb
follow up https://github.com/openshift/verification-tests/pull/2024
@liangxia please take a look.
cc @zhaozhanqi
> [v3] update pod-for-ping to use image from quay.io

- features/build/dockerbuild.feature
- features/cli/oc_import_image.feature
@openshift/devexp-qe Please help to review, thanks!
> Fix image issues

- lib/openshift/volume_snapshot.rb
> fix missing update of iterations variable.

- features/step_definitions/kata.rb
1000 doesn't seem to be enough.  Make it  a full 20 minutes
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/73721/console
@liangxia PTAL and merge...this should make the testcase more reliable.
> longer kata deletion/installation timeout

- features/step_definitions/admin_console.rb
- features/step_definitions/cli.rb
- features/step_definitions/oauth.rb
- lib/rules/cli/4.5.yaml
> Auto OCP-22490 customize login page

- OWNERS
/cc @jhou1 @pruan-rht @JianLi-RH
> Add jianli as a global reviewer in verification-tests

- features/logging/cluster_log_forwarder.feature
- testdata/logging/clusterlogforwarder/fluentd/secure/secure-forward-cm.yaml
This is a PR for [OCPQE-3814](https://issues.redhat.com/browse/OCPQE-3814) JIRA task to Automate the case OCP-39786 for Logging
> JIRA OCPQE-3814: Automate the case OCP-39786

- lib/base_helper.rb
PR https://github.com/openshift/cucushift/pull/8597 depends on this and this should be merged firstly. 
Pass log: Runner/75195/console
@xingxingxia Please help to review when free. Thanks.
> add support for OCP-33656

- OWNERS
/cc @pruan-rht @JianLi-RH @dis016
> Add jhou1 as global approver

- features/storage/csi_clone.feature
- testdata/storage/csi/pvc-clone.yaml
pass log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3170/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3171/console
@jhou1 @chao007 PTAL
> Automate OCP-27617 and OCP-27686

- features/networking/egress-ip.feature
Auto OCP-40933 OCP-40928 OCP-40957 OCP-40956
Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3115/
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3116/
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3117/
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3118/
> Auto some sdn-1282 EgressIP cases

- lib/openshift/network_policy.rb
```
networkpolicies                       netpol           networking.k8s.io/v1                          true         NetworkPolicy
```
/cc @pruan-rht @asood-rh @jhou1
> Fix resource type for NetworkPolicy

- features/step_definitions/kata.rb
- lib/openshift/pod.rb
- testdata/kata/webhook/example-fedora.yaml
1. create a method to get the runtimeClass from a pod's spec
2. added missing testdata file for the case.
3. changed to use the newly created method.
> a few fixes for kata testing.

- features/step_definitions/networking.rb
Step definition to obtain endpoint publishing strategy.
OCP-40908
OCP-41944
> SDN-1340 test case step definition

- features/storage/csi.feature
Automate OCP-37558/OCP-37560/OCP-37562/OCP-37572. These Scenario Outline could be used for other csi drivers.
pass log: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3186/console
@jhou1 @chao007 PTAL
> Auto OSP smoke test case

- tools/jenkins/slaves/Dockerfile.rhel7
/cc @pruan-rht @jhou1 @JianLi-RH @dis016
> Keep dir /var/tmp/ in image cucushift-public

- features/build/buildlogic.feature
- features/cli/oc_portforward.feature
- features/networking/multus.feature
- features/networking/operator.feature
- features/networking/sdn.feature
found these issues while doing PR https://github.com/openshift/verification-tests/pull/2096
> formatting changes and use '&&' instead of 'and' for comparison

- features/step_definitions/kata.rb
1. added a step to get all pods in the cluster that are using kata as runtime
2. raise an error and exit if there are pods in the cluster with kata, so we don't have to wait until timeout, fail early to save time
> add a pre-check for pods running with kata before kataconfig deletion

- lib/openshift/deployment.rb
- lib/openshift/deployment_config.rb
> update lib for OCP-40533

- lib/rules/web/admin_console/4.8/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.8/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.8/style.xyaml
Fix UI failures caused by product change
Related to PR:
https://github.com/openshift/cucushift/pull/8602
v3 job for case OCP-21257
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/321158/
> Hongyli fix 4.8 failure

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
- lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/login.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
Update the place to check the error dialog when trying to create an invalid AWS cluster. The automation dialog is at here: http://pastebin.test.redhat.com/973991
> Fixed the error associated with OCP-21100, OCP 26751

- features/storage/csi_resize.feature
@jhou1 @duanwei33 Please help review resizing volume test case.
Have passed in local. But did not run from Jenkins now due to Jenkins issue today.
> Auto TC OCP-37479

- features/storage/csi_resize.feature
1. Add two cases for OSP and AWS platform with [pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?7445b5d0d446362c#4yAjjpSH62gBHFeXhPekdZqkQtoohkWi21aUidbjsumM)
2. Automate one resize negative test with [pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?18a789bda43d2b6f#FRkT9aydZcdYMSo1qvVJdwNHsXFuazdb4geT99oPPXF)
@jhou1 @chao007 PTAL, thanks.
> Add resize case for OSP and AWS

- features/storage/csi.feature
pass log: 
[OCP-37564](https://privatebin-it-iso.int.open.paas.redhat.com/?73dcee5ba6be18d5#GWaVy7BRMdqEjvrJMXACnhtRm2HVeN9m8uv5X7vxvQui) 
[OCP-24546/OCP-24572](https://privatebin-it-iso.int.open.paas.redhat.com/?e55679f92b5a8649#AVAuSYRNGGPAbBno33V3dMK6RWa6beDwzEi38yFrWsxv)
@chao007 @jhou1 PTAL
> Automate OCP-37564/OCP-24546/OCP-24572

- features/networking/multicast.feature
For case OCP-12926 and OCP-12977
1. Update to execute the cases in both SDN and OVN, right now they only be executed in SDN
2. Update to expect not all 5 packets lost in the client side due to Bug 1879241 - [OVN] Pods always lose one multicast packets
3. Allow 10 seconds for the multicast igmp group information shown up when execute "netstate -ng", it may fail as this CI testing (http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/06/24/10:38:23/Same_multicast_groups_can_be_created_in_multiple_tenant/console.html)
For case OCP-12930
Allow 10 seconds for the multicast igmp group information shown up when execute "netstate -ng", it random failed in CI testing (http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/06/24/10:38:23/Same_multicast_groups_can_ …
> Update multicast cases

- features/machine/machine.feature
@sunzhaohua2 @jhou1  , PTAL ..
This is to cover test for -https://bugzilla.redhat.com/show_bug.cgi?id=1953063 
Here are the results : https://url.corp.redhat.com/42346
> Adding test for BZ-1953063

- lib/rules/web/ocm_console/subscription_page.xyaml
Update the rules for OCP-25353. Testing is passed on local with the log http://pastebin.test.redhat.com/974067
> rewrite the case OCP-25353

- features/networking/egress-ip.feature
Fixed syntax error.
Log:https://privatebin-it-iso.int.open.paas.redhat.com/?3d30cbd4e1c88b92#FCVezjhwKG3Geq8nVSSSPZ2Yt32wvekYN7AX62uBjJMr
> fix syntax error

- features/step_definitions/logging.rb
Update the channel name per https://issues.redhat.com/browse/LOG-1421
/cc @anpingli
> update channel name

- lib/openshift/image_stream.rb
- lib/rules/web/admin_console/4.5/imagestream.xyaml
- lib/rules/web/admin_console/4.6/imagestream.xyaml
- lib/rules/web/admin_console/4.7/imagestream.xyaml
- lib/rules/web/admin_console/4.8/imagestream.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/storage.xyaml
feature updates PR cucushift#8620
> fix destructive rules

- features/build/stibuild.feature
@openshift/devexp-qe Please review, thanks!
> Fix OCP-22596

- features/storage/csi.feature
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?6bf0da9f0478aea2#5qWQJ3jWn4MKJptpTxKBqJt3JJ5yX7GxJxr9yRcynhEk)
> Automate OCP-37557/OCP-34144/OCP-37474

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
- lib/rules/web/ocm_console/cluster_idp.xyaml
- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
Fix the errors associated with automation. Including cases OCP24006, 24004, 23866, 26823, 26848, 22117, 21685, 27994, 36802. Execution log: http://pastebin.test.redhat.com/975598 and http://pastebin.test.redhat.com/975826.
> Chgu working (#3)

- lib/rules/web/ocm_console/OWNERS
> Add xueli181114 and yasun1 as OCM approvers

- lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
fix OCP-36912, pass log on 4.8: Runner-v3/321250/console
> fix web rule

- features/storage/csi.feature
@jhou1 @duanwei33 Please help to review.
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/98318/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/98336/console
> Add tc OCP-37511 and OCP-37478

- features/storage/security.feature
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?e0148f313558caf7#G5Kjt1R39kKz2Df7omAN4ucgLw87bJNKKo2jQxw5LSAw)
@chao007 PTAL.
> Fix docker.io pull limitation issue for v3

- tools/openshift-ci/Dockerfile
> Add dockerfile for unify CI

- tools/jenkins/slaves/Dockerfile.centos
- tools/jenkins/slaves/Dockerfile.rhel7
- tools/jenkins/slaves/Dockerfile.rhel8
- tools/openshift-ci/Dockerfile
- tools/openshift-ci/Dockerfile.centos
- tools/openshift-ci/Dockerfile.installer-example
For https://github.com/openshift/verification-tests/pull/2153#discussion_r666252588
/cc @pruan-rht @jhou1
> AOS -> OCP

- lib/rules/web/admin_console/4.6/operator_hub.xyaml
Pass log on 4.6: /Runner/100107/console @yapei, pls help to review, thanks!
> fix ocp-29198 4.6 rule

- features/storage/persistent_volume.feature
- features/storage/quota.feature
- features/storage/reclaim_policy.feature
Remove some cases' smoke tag which are duplicated or not suitable or no need for 3.11 release test.
> Remove smoke tag

- tools/openshift-ci/Dockerfile
The image built from cucushift repo will be used as the base image for this one, I tested this locally by replacing the `FROM` with cucushift image. 
@liangxia PTAL, thank you!
> Adding cucushift

- tools/polarshift.rb
This will allow user to get more information about a run.
> allow user to specify how much information to extract from a test-run

- OWNERS
> Add dis016 as global reviewer

- features/networking/ib-sriov.feature
- features/networking/sriov.feature
- features/step_definitions/sriov.rb
- lib/openshift/sriov_i_b_network.rb
- testdata/networking/sriov/ib/cx4/cx4-ib.yaml
- testdata/networking/sriov/ib/cx4/pod_ib.yaml
- testdata/networking/sriov/ib/cx4/pod_iboip.yaml
- testdata/networking/sriov/ib/cx4/sriovibnetwork-cx4.yaml
- testdata/networking/sriov/ib/cx5/cx5-ib.yaml
- testdata/networking/sriov/ib/cx5/sriovibnetwork-cx5.yaml
- testdata/networking/sriov/ib/cx6/cx6-ib.yaml
- testdata/networking/sriov/ib/cx6/pod-guid.yaml
- testdata/networking/sriov/ib/cx6/sriovibnetwork-cx6.yaml
- testdata/networking/sriov/ib/cx6/sriovibnetwork-static.yaml
auto sriov IB cases.
https://privatebin-it-iso.int.open.paas.redhat.com/?8e4e94a699b2c809#CfvybM9awcBqwo88ksGoVqtzoQpGLFNrXiwiyZ2NEzyY
@anuragthehatter @huiran0826  @weliang1 @rbbratta PTAL, thanks
> added IB cases

- tools/openshift-ci/Dockerfile
Using `htpasswd` to generate users to run cucushift in Prow
> Adding htpasswd

- features/step_definitions/helper_services.rb
@xingxingxia @pruan-rht  This PR is the cucushift/pull/8656 replacement to solve [OCPQE-3649](https://issues.redhat.com/browse/OCPQE-3649). Pass log: Runner-v3-smoke/3304, Runner-v3-smoke/3305, Runner-v3-smoke/3309, Runner-v3-smoke/3310, Runner-v3-smoke/3311 and Runner-v3-smoke/3312. Please help to review when free. Thanks!
> add wait for ldapserver pod Running status

- lib/rules/web/admin_console/4.9/logs.xyaml
-- check if the logs can be wrapped in the log viewer
The success Runner:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/122525/console
> OCP-41601-wrapLogs

- lib/rules/web/admin_console/4.8/logs.xyaml
- lib/rules/web/admin_console/4.9/logs.xyaml
> OCP-41601 add 4.8 rules for wrap logs

- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/logging/logging_acceptance.feature
- testdata/logging/clusterlogging/cl-storage-with-im-template.yaml
It takes too much time to run all the logging cases, there are some duplicated steps in many cases, to save time, merge some test cases into one case.
/cc @anpingli
> merge some logging cases

- features/step_definitions/logging.rb
Set default channel to `stable-5.2` when testing logging on OCP 4.9 and fix some issues when deleting clusterlogging.
runner job log: https://url.corp.redhat.com/a52ef61
/cc @anpingli
> update channel name and fix some issue when deleting clusterlogging

- features/build/metrics.feature
- features/images/rhel8_images.feature
> Fix OCP-33722

- features/build/dockerbuild.feature
- features/build/stibuild.feature
Add auto OCP-42157, OCP-42158, OCP-42159,OCP-42184,OCP-42185,OCP-42529
[Pass log](https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/321319/console)
@wewang58 @jitendar-singh Please help review, thanks
> Auto secret volume cases

- features/online/create.feature
- features/online/images.feature
- features/online/sti.feature
- features/storage/add_update_delete_volume.feature
@duanwei33 @liangxia @yasun1 PTAL. 
Confirmed storage test flake is fixed
> Fix and improve multiple @smoke tests

- Gemfile
For issue [OCPQE-4433](https://issues.redhat.com/browse/OCPQE-4433)
/cc @jhou1 @pruan-rht
> Add parallel_tests gem to support parallel execution in prow

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.9/check_links.xyaml
- lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.9/projects.xyaml
- lib/rules/web/admin_console/4.9/route.xyaml
- lib/rules/web/admin_console/4.9/search.xyaml
Fix for OCP-19532 OCP-21023 OCP-21461 OCP-21772 
Pass log: Runner/132549/console
@XiyunZhao or @schituku pls help to review when you're available, thanks!
> fix for web

- features/logging/cluster_log_forwarder.feature
Fix the scheme in URL when forwarding with TLS.
/cc @anpingli 
runner job log: https://url.corp.redhat.com/c6384ad
> update scheme to tls

- features/upgrade/api_auth/upgrade.feature
This PR fixes OCPQE-4544, the case uses an image not in the mirror list, will fail in disconnected env, see its failure there.
Jenkins is down. Local test passes pre-upgrade part. **Need Jenkins** to run post-upgrade part tomorrow and ask @yaoli-redhat @wangke19 to review then, otherwise the pre-upgrade part will delete the project created if run in **local** `cucumber features/upgrade/api_auth/upgrade.feature:$LINE`, this will make post-upgrade fail to get that project, @geliu2016 @JianLi-RH , how to locally run upgrade case to avoid this problem?
> Make the service-ca upgrade case can be run in disconnected env

- testdata/logging/clusterlogforwarder/fluentd/insecure/configmap.yaml
> Listen on both IPv4 and IPv6 

- features/networking/ovn.feature
- features/step_definitions/networking.rb
Auto OCP-38132
Logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/2965/consoleFull
@zhaozhanqi @anuragthehatter @weliang1 @rbbratta @asood @brahaney @kedark3
> Auto OCP-38132

- tools/openshift-ci/Dockerfile
> Update dockerfile to fit with prow CI

- tools/openshift-ci/Dockerfile
Fixes a failure in Prow https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/19910/rehearse-19910-periodic-ci-openshift-release-master-nightly-4.8-e2e-cucushift-private-aws/1427467879246204928/build-log.txt
@liangxia PTAL
> Allow writing to create Gemfile.lock

- lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
Runner/144426/console
Runner/144428/console
> update idp common rules

- lib/rules/web/admin_console/4.5/check_links.xyaml
- lib/rules/web/admin_console/4.6/check_links.xyaml
- lib/rules/web/admin_console/4.6/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/check_links.xyaml
- lib/rules/web/admin_console/4.7/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/check_links.xyaml
- lib/rules/web/admin_console/4.8/clustersettings.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
update for automation case 4.5-4.8
> update for automation case 4.5-4.8

- tools/case_id_splitter.rb
This PR add the `add-tags` feature the `tools/case_id_splitter.rb`. New tags can be added following this example:
```
verification-tests ➤ tools/case_id_splitter.rb add-tags --tags @gcp,@aws,@disconnected --cid OCP-22578     
Adding tag @gcp to /Users/jhou/Projects/verification-tests/features/tierN/apiserver/custom_resource.feature for test case OCP-22578
Adding tag @aws to /Users/jhou/Projects/verification-tests/features/tierN/apiserver/custom_resource.feature for test case OCP-22578
Adding tag @disconnected to /Users/jhou/Projects/verification-tests/features/tierN/apiserver/custom_resource.feature for test case OCP-22578
verification-tests ➤ tools/case_id_splitter.rb add-tags --tags @gcp,@aws,@disconnected --cid OCP-22578    
Test case OCP-22578 already has tag @gcp
Test case OCP-22578 …
```
> Implement tools to add tags to scenario

- lib/rules/web/ocm_console/cluster_list_page.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
- lib/rules/web/ocm_console/subscription_page.xyaml
@xueli181114 Please help review.
> fix automation failure for tzhou's cases on 20210820

- features/upgrade/api_auth/upgrade.feature
Finished script. Still testing. After test, will request @wangke19  and @yaoli-redhat  to review.
This depends on internal repo openshift-misc PR of number 65 . Only after that is merged, this PR can be merged.
BTW, @wangke19 , @yaoli-redhat , I can't @ you **in that repo**, seems you are not shown as member of that repo yet..
> Automate upgrade case OCP-34223

- features/step_definitions/oauth.rb
@xingxingxia this PR is to add common step 'authentication successfully rolls out after config changes' based on https://github.com/openshift/cucushift/pull/8676 feedback and should be merged before that. pass log: Runner-v3-smoke/3427 for OCP-23517/OCP-23514/OCP-23515 and Runner-v3-smoke/3428 for OCP-29916. Please help to review when free. thanks!
> Add common step for authentication rolls out after config changes

- lib/rules/web/admin_console/4.5/check_links.xyaml
- lib/rules/web/admin_console/4.6/check_links.xyaml
- lib/rules/web/admin_console/4.6/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/check_links.xyaml
- lib/rules/web/admin_console/4.7/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/check_links.xyaml
- lib/rules/web/admin_console/4.8/clustersettings.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.9/clustersettings.xyaml
- lib/rules/web/admin_console/4.9/dashboards.xyaml
- lib/rules/web/admin_console/4.9/user_management.xyaml
Update rules for OCP-36912,OCP-37098,OCP-25765
> Automation case update for OCP-36912,OCP-37098,OCP-25765

- features/machine/machine_misc.feature
- testdata/cloud/misc/deployment-40665.yaml
- testdata/cloud/misc/pvc-40665.yaml
@sunzhaohua2 @jhou1 PTAL ,
Test results , successfully executed - https://url.corp.redhat.com/Validation
> Automate case OCP-40665 , BZ-1990432

- features/step_definitions/metering.rb
Fixes https://issues.redhat.com/browse/OCPQE-5310>
the issue is that sharedPVC created two pvs, the test was checking for the wrong name.  
run log: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/155749/console
> Ocp 32004 fix

- OWNERS
/cc @shellyyang1989 @jhou1 @pruan-rht
> Add shellyyang1989 as global reviewer

- features/networking/ptp_operator.feature
- features/networking/sriov.feature
- features/storage/csi.feature
- features/upgrade/logging/upgrade_with_clf.feature
> Add stage-only tags

- lib/rules/web/ocm_console/install_page.xyaml
auto OCP-43052 and fixed some case and supplement OCP-26380
> auto OCP-43052 and fixed some cases and supplement OCP-26380

- features/build/buildconfig.feature
- features/build/buildlogic.feature
- features/build/dockerbuild.feature
- features/build/env.feature
- features/build/stibuild.feature
- features/cli/build.feature
- features/cli/create.feature
- features/cli/deploy.feature
- features/cli/oc_env.feature
- features/cli/oc_process.feature
- features/cli/oc_set_build_hook.feature
- features/cli/oc_set_deployment_hook.feature
- features/cli/pod.feature
- features/cli/policy.feature
- features/cli/projects.feature
- features/cli/route.feature
- features/cli/scale.feature
- features/cli/secrets.feature
- features/cli/serviceaccount.feature
- features/images/rhel8_images.feature
- features/node/proxy.feature
- features/registry/registry.feature
- features/rest/webhook.feature
- features/upgrade/build/build-upgrade.feature
The `@proxy` tag needs to be added to distinguish tests that can only be run in a cluster proxy deployment.
@liangxia @pruan-rht PTAL
> Add proxy tag

- features/build/stibuild.feature
- features/machine/machine.feature
- features/networking/pod.feature
- features/registry/registry.feature
> add disconnected tag

- lib/rules/web/ocm_console/cluster_detail.xyaml
- lib/rules/web/ocm_console/cluster_detail_overview_tab.xyaml
- lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
- lib/rules/web/ocm_console/osd_creation_page.xyaml
- lib/rules/web/ocm_console/osd_wizard.xyaml
- lib/rules/web/ocm_console/osd_wizard_billing_model.xyaml
- lib/rules/web/ocm_console/osd_wizard_cloud_provider.xyaml
- lib/rules/web/ocm_console/osd_wizard_cluster_details.xyaml
- lib/rules/web/ocm_console/osd_wizard_machine_pool.xyaml
- lib/rules/web/ocm_console/osd_wizard_networking.xyaml
- lib/rules/web/ocm_console/osd_wizard_review.xyaml
- lib/rules/web/ocm_console/osd_wizard_updates.xyaml
> Rewrite rules for the new ocm creation wizard

- features/routing/OWNERS
@quarterpin PTAL, thanks
cc @melvinjoseph86 @ShudiLi
> update routing owners

- lib/rules/web/admin_console/4.8/overview.xyaml
- lib/rules/web/admin_console/4.9/overview.xyaml
4.8 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/160911/console
4.9 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/160912/console
> fix OCP-20932 rules

- features/logging/logging_acceptance.feature
More will follow, right now we look forward to get these test pass in Prow by not running in parallel
> add console tag

- features/cli/oc_import_image.feature
lastTriggeredImageID change from spec to status
@wewang58 Please help review, thanks
> Fix lastTriggeredImageID issue

- features/logging/logging_acceptance.feature
Can't get them fixed in time, skipping and will remove the tags upon fixes to these tests
> tag unsable tests in Prow

- features/admin/quota.feature
https://bugzilla.redhat.com/show_bug.cgi?id=1885717 has been verified .the output changed a bit.
@sunilcio @lyman9966 @rhpmali  could you help take a look?
log:
http://pastebin.test.redhat.com/992441
cc: @jhou1 I got the @flaky removed
> fix OCP-12086

- features/build/OWNERS
- features/machine/OWNERS
- features/networking/OWNERS
- features/online/OWNERS
- features/registry/OWNERS
- features/routing/OWNERS
- features/storage/OWNERS
/cc @wzheng1 @xiuwang @anuragthehatter @zhaozhanqi @xueli181114 @yasun1 @lihongan @duanwei33 
Add you the permission to approve PRs in verification-tests.
You can add/update/remove teammates as co-approver/reviewer once the PR is merged
> Sync owners from cucushift repo

- features/upgrade/machines/machines.feature
Auto OCP-43331  @jhou1 @miyadav @yihguo please help to review.
> auto OCP-43331

- features/upgrade/sdn/egress-upgrade.feature
Auto OCP-44316 OCP-44315
Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3450/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3451/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3454/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3455/console
> Auto upgrade case for egressip and egressfirewall

- features/upgrade/sdn/multicast-upgrade.feature
Auto multicast upgrade case
Test log:
http://file.rdu.redhat.com/~weliang/multicast-pre-log
http://file.rdu.redhat.com/~weliang/multicast-post-log
> Auto multicast upgrade case

- features/upgrade/sdn/OWNERS
/cc @anuragthehatter @zhaozhanqi @jhou1 @pruan-rht
> Add OWNERS for SDN upgrade

- lib/rules/web/admin_console/4.9/projects.xyaml
- lib/rules/web/admin_console/4.9/search.xyaml
- lib/rules/web/admin_console/4.9/style.xyaml
Update for OCP-36165,OCP-32152,OCP-27550,OCP-19675
> Update for OCP-36165,OCP-32152,OCP-27550,OCP-19675

- doc/tags.adoc
This documents the tags used in cucushift, will be used as a reference for contributors to follow. 
> Documenting the tags added to cucushift

- features/networking/sdn.feature
- features/upgrade/sdn/service-upgrade.feature
add cases for this bug https://bugzilla.redhat.com/show_bug.cgi?id=1995871
> add cases OCP-43146

- lib/rules/web/admin_console/4.7/logging_kibana.xyaml
- lib/rules/web/admin_console/4.8/logging_kibana.xyaml
- lib/rules/web/admin_console/4.9/logging_kibana.xyaml
> add rules to create visualize on kibana

- features/upgrade/storage/upgrade.feature
From version 4.7+
/cc @duanwei33 @chao007 @jhou1 @Phaow
> snapshot for AWS platform

- doc/tags.adoc
- features/images/jenkins.feature
- features/logging/logging_acceptance.feature
Properly label these console tests in order to skip them in Prow.
@liangxia PTAL
> Using console tags

- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
Fix for issue: https://issues.redhat.com/browse/OCPQE-4901
> add rule for upgrade case

- features/upgrade/storage/upgrade.feature
Adding the case id. 
/cc @duanwei33  @jhou1
> [Automate-storage] [OCP-44578] [AWS-EBS-CSI] [Snapshot operator]

- features/storage/csi_resize.feature
Description: To check the pvc support for offline volume expansion.
Steps:
1) Create pvc, deployment.
2) Apply the patch to resize pvc size
3) Scale the dep to 0, wait untill pvc starts resizing.
4) Scale back the dep to 1, check the pvc size, write data.
> [Automate][OCP-41452][Azure CSI Resize] offline volume expansion

- features/cli/job.feature
- lib/openshift/cron_job.rb
Simplify the steps and outputs.
> Simplify OCP-17515

- features/upgrade/sdn/sctp-upgrade.feature
- testdata/networking/sctp/sctpclient-upgrade.yaml
- testdata/networking/sctp/sctpserver-upgrade.yaml
Automate sctp-upgrade test
Test logs:
http://file.rdu.redhat.com/~weliang/sctp-pre-log
http://file.rdu.redhat.com/~weliang/sctp-post-log
> Automate sctp-upgrade test

- features/networking/isolation.feature
- features/networking/sdn.feature
- features/networking/service.feature
> update tag for multitenant cases

- features/storage/csi_snapshot.feature
- testdata/storage/csi/volumesnapshotclass-azure.yaml
Description: Volume snapshot create and restore test
Steps: 
1) Create pvc from csi storage class(managed-csi) , pod from pvc. 
2) Check the pod status and write data.
3) Create a Volumesnapshot class, volumesnapshot and check the status.
4) Create a snapshot pvc from volumesnapshot, pod from snapshot pvc. 
5) Check the snapshot pvc/pod status, data content in the pod.
> [Automate][OCP-41449][Azure-csi-snapshot]with default parameters

- doc/tags.adoc
- features/networking/ovn.feature
- features/networking/ovn_ipsec.feature
- features/networking/pod.feature
- features/networking/sdn.feature
> Fix prow gcp rehearse tests

- features/logging/kibana.feature
- features/step_definitions/logging.rb
- features/upgrade/logging/upgrade.feature
- lib/rules/web/admin_console/4.5/logging_kibana.xyaml
- lib/rules/web/admin_console/4.6/logging_kibana.xyaml
- lib/rules/web/admin_console/4.7/logging_kibana.xyaml
- lib/rules/web/admin_console/4.8/logging_kibana.xyaml
- lib/rules/web/admin_console/4.9/logging_kibana.xyaml
Check two Kibana users during upgrade. One is authorized via group. (BZ1895581)
Move some steps to step definition and use the step 'custerlogging to be functional in the project'
Check new project log instead of comparing the doc number. I am worried about the Noisy data from buffer.
persistent some projects during upgrade.
> Add more Kibana verification in upgrade

- testdata/routing/abrouting/abtest-websrv1.yaml
- testdata/routing/abrouting/abtest-websrv2.yaml
- testdata/routing/abrouting/abtest-websrv3.yaml
- testdata/routing/abrouting/abtest-websrv4.yaml
- testdata/routing/web-server-1.yaml
- testdata/routing/web-server-rc.yaml
to fix https://issues.redhat.com/browse/OCPQE-5832
rebuild image for both arch (AMD and ARM).
@liangxia Please take a look.
cc @quarterpin @melvinjoseph86 @ShudiLi @aleskandro  @YuLi517
> update image nginx-alpine digest for ARM arch

- features/step_definitions/nfd.rb
1. labels for OCP < 4.8 are different
2. fix timing issue when creating namespace from OperatorHub is slower, so added a statement to make sure the namespace is present before doing anything else.
3. for OCP > 4.8, the nfd-master.yaml needs to be updated to include a section workerConfig https://github.com/openshift/cucushift/pull/8785
> fix psap automation failures

- features/networking/egress-ingress.feature
Fix issues https://issues.redhat.com/browse/OCPQE-5848 and https://issues.redhat.com/browse/OCPQE-5771
Logs:
http://file.apac.redhat.com/~huirwang/OCP-13506.log
http://file.apac.redhat.com/~huirwang/OCP-15005.log 
http://file.apac.redhat.com/~huirwang/OCP-33565.log
http://file.apac.redhat.com/~huirwang/OCP-37491.log
http://file.apac.redhat.com/~huirwang/OCP-37495.log
http://file.apac.redhat.com/~huirwang/OCP-37496.log 
http://file.apac.redhat.com/~huirwang/OCP-41179.log
> fix OCP-37496

- features/build/stibuild.feature
Passed in localhost
@wewang58 please help review, thanks
> Fix docker image

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch_operator.feature
- features/test/webconsole.feature
- features/upgrade/web/console-upgrade.feature
> Add tag console to support tests in Prow

- features/storage/csi.feature
Fix failures in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21988/rehearse-21988-periodic-ci-openshift-verification-tests-master-4.9-e2e-aws-cucushift-ipi/1441371247391805440
> Fix CSI failures for AWS IPI tests in Prow

- lib/rules/web/admin_console/4.6/catalog.xyaml
- lib/rules/web/admin_console/4.7/catalog.xyaml
- lib/rules/web/admin_console/4.8/catalog.xyaml
- lib/rules/web/admin_console/4.9/catalog.xyaml
4.8 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/180914/console
> simplify choose_project_from_dropdown_list

- tools/polarshift.rb
in addition to filter case status, we can filter by subteams as well by adding option subteam and csv list of subteam names.  This should do what @shivanthi-amara was asking for yesterday.
```./tools/polarshift.rb clone-run 20210917-0416 --status=FAILED --subteam=storage,network_edge```
> added ability to clone run with filter by subteams

- features/step_definitions/scc.rb
Co-work with https://github.com/openshift/cucushift/pull/8800
/cc @jhou1 @dis016 @pruan-rht  @yaoli-redhat
> Force steps that update SCC to tag destructive

- features/logging/collector.feature
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/182288/console
> collector name update in OCP-30084

- features/machine/machine.feature
/cc @JianLi-RH @dis016 @pruan-rht @jhou1
> Fix machineset clone

- features/upgrade/api_auth/upgrade.feature
- features/upgrade/jenkins/upgrade.feature
- features/upgrade/logging/upgrade.feature
- features/upgrade/node/node-upgrade.feature
- features/upgrade/sdn/externalIP-upgrade.feature
- features/upgrade/sdn/multus-upgrade.feature
- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/service-upgrade.feature
- features/upgrade/security_compliance/fips.feature
- features/upgrade/workloads/oc-upgrade.feature
/cc @jhou1 @liangxia @dis016 @pruan-rht
> Add tags for @upgrade-prepare tests

- features/networking/operator.feature
According to comments in https://github.com/openshift/verification-tests/pull/2422
/cc @zhaozhanqi @anuragthehatter @JianLi-RH @jhou1
> Fix test failure of OCP-27333 in Prow
