- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
Add rules for OCP-19717, pls help to review, @yapei or @SSshahan .
> Add rules for OCP-19717

- tools/jenkins/slaves/Dockerfile.centos
This update will allow a docker container to run bushslicer tests in ci-operator
> Update the dockerfile for containerized tests running BushSlicer.

- Gemfile
- config/config.yaml
- lib/iaas/iaas.rb
- lib/launchers/amz.rb
- lib/launchers/cloud_helper.rb
- tools/launch_instance.rb
Needs testing, do not merge yet.
> allow multiple AWS configs

- features/cli/oc_set_deployment_hook.feature
- features/cli/oc_set_probe.feature
Tested in locally  works, old pr closed @openshift/devexp-qe, pls help to review thx
> Fix some cases

- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/3.11/deployment.xyaml
- lib/rules/web/admin_console/3.11/goto.xyaml
- lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.0/deployment.xyaml
- lib/rules/web/admin_console/4.0/goto.xyaml
Add rules for ocp-19672
Pls help to review, @yapei or @SSshahan
> Add rules for ocp-19672

- tools/openshift-ci/Dockerfile.centos
Initial Dockerfile to be used in the openshift-ci.
ref [#2213](https://github.com/openshift/release/pull/2213)
> Init Dockerfiles for openshift-ci

- lib/rules/web/admin_console/4.0/secrets.xyaml
This is only for 4.0
@yapei Please review, thanks.
> replace set_pair_value by set_textarea_value

- lib/rules/web/admin_console/3.11/deployment.xyaml
- lib/rules/web/admin_console/4.0/actions.xyaml
- lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.0/deployment.xyaml
Following changes included:
1. `check_desired_pod_count` is removed
2. All rules related to `Actions` are moved to actions.xyaml
@openshift/ui-qe  comments are welcomed, let me know if anything is missed, thanks!
> rules update of remove check_desired_pod_count

- tools/jenkins/slaves/Dockerfile.centos
- tools/jenkins/slaves/Dockerfile.rhel7
@akostadinov @pruan-rht 
Idea coming from "[aos-devel] Dockerfile owners: this is better than rpm -V"
> Fail ealier if package missing

- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.0/secrets.xyaml
Adjust rules, passed locally.
@xiaocwan
> Fix web case

- features/online/images.feature
@yasun1 
Updated OCP-11614, here is Jenkins log: https://url.corp.redhat.com/86d4932. Please help review, thanks
> update scenario for OCP-11614

- lib/launchers/openstack10.rb
Now one can optionally select network for floating IPs.
> selectable floating IP pools

- lib/gherkin_parse.rb
> Fix case_id format

- features/step_definitions/route.rb
Adding two steps for router 4.0 compatibility, and first step is also for https://projects.engineering.redhat.com/browse/OPENSHIFTQ-12579
@akostadinov @pruan-rht @xingxingxia Please help review.
> adding router related steps for 4.0

- features/cli/policy.feature
- features/cli/projects.feature
- features/cli/serviceaccount.feature
Fixes for some outputs compatible issues.
> Fixes for some outputs compatible issues

- features/networking/build.feature
same as https://github.com/openshift/cucushift/pull/6903
> delete cache parameter step

- features/cli/pod.feature
OCP-22283 will replace OCP-10986 in 4.x
> Auto case for OCP-22283

- OWNERS
this should stop bombarding cryan....
> update owners of the project

- lib/environment.rb
Add authentication endpoint for 4.x
> Add authentication endpoint for 4.x

- lib/rules/web/admin_console/4.0/check_links.xyaml
- lib/rules/web/admin_console/4.0/status.xyaml
@yanpzhan Could you help to review? Thanks!
> Fix check_doc_get_started_with_cli and check_dim_resource_list

- features/cli/create.feature
OCP-22515 will replace OCP-10593 in 4.x
> Auto case OCP-22515

- features/cluster_configuration/csi.feature
- features/step_definitions/cluster_configuration/csi.rb
- features/storage/csi.feature
@liangxia @chao007 Please help to take a look. Thanks
> Make csi driver deployment as a case so that can be run as CVP

- lib/rest_openshift.rb
Add post_role_api step for OCP-22565
> Add post_role_api step for OCP-22565

- features/step_definitions/helper_services.rb
@akostadinov  @jhou1  @chao007  @weherdh  @qinpingli 
iSCSI initiator should only apply on nodes.
> iSCSI initiator should only setup on nodes

- lib/collections.rb
- lib/configuration.rb
> fix issue when YAML uses anchoring

- features/cli/deploy.feature
@xingxingxia  Please help review , have pass locally.
> update for case 10717

- lib/jira_rht.rb
> make jira create issue work and allow running on command line

- lib/rules/web/admin_console/4.0/common_ui_elements.xyaml
Fix 4.0 rules: create_resource_by_default_yaml
Pass log: http://pastebin.test.redhat.com/735665
@yapei or @xiaocwan pls help to review, thanks!
> Fix web rules

- features/step_definitions/registry.rb
@akostadinov (@wzheng1 fyi) please help check/merge, thanks
> add ocp4 registry

- config/config.yaml
- doc/webauto.adoc
@pruan-rht  @akostadinov 
The same with https://github.com/openshift/verification-tests/pull/114 , for v3 branch
> Update repository url

- lib/jira_rht.rb
- tools/tcms_query.rb
> modernize jira code

- lib/http.rb
- lib/polarshift/request.rb
- tools/polarshift.rb
> support for test case queries

- lib/rest_kubernetes.rb
addresses comment in issue https://github.com/openshift/verification-tests/issues/118
> handle differnt api url depending on the type of operation

- features/routing/route.feature
@pruan-rht could you please help merge this one. Thanks
log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39068/console
> fix OCP-13839 case ID

- lib/openshift/cluster_operator.rb
- lib/openshift/cluster_version.rb
> added api support for clusteroperator and clusterversion for 4.x

- features/step_definitions/crd.rb
- lib/openshift/kube_a_p_i_server.rb
- lib/world.rb
Add step for cluster crd backup restore.
> Step for cluster crd backup restore

- lib/openshift/cluster_operator.rb
- lib/openshift/resource.rb
addresses https://github.com/openshift/verification-tests/pull/127#discussion_r268840474.  @akostadinov  PTAL.
> moved methods to lib/resource and added a version check

- lib/launchers/amz.rb
- tools/aws.rb
- tools/launch_instance.rb
> AWS improvements

- features/storage/hostpath.feature
@weherdh  @chao007  PTAL
Jenkins log, Runner-v3/39454
> HostPath for 4.x

- features/step_definitions/storage_class.rb
@liangxia @chao007 Please help to review.
Log: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39494/console
> Update clone sc step to fix pvc bound issue

- features/networking/multus.feature
- features/step_definitions/networking.rb
testing log: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39584/console
@zhaozhanqi @anuragthehatter PTAL
> [networking] initiate the multus related testing automation

- features/networking/multus.feature
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39708/console
Two more cases for macvlan with different modes.
@zhaozhanqi @anuragthehatter PTAL. Thanks.
> [networking] automated more macvlan cases

- lib/rules/cli/kubectl-4.1.yaml
@zhouying7780 @akostadinov please help merge
> add kubectl for oc 4.1

- lib/openshift/cluster_service_class.rb
- lib/openshift/cluster_service_plan.rb
> added methods to get clusterSerivceBrokerName

- lib/openshift/resource.rb
> change condition check to default to cached: false

- features/networking/multus.feature
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39725/console
Automate the host-device case.
I copied the step from node.rb and removed the `host` part. Since it will fail on 4.0 cluster. And I just need to select a random node here. No matter the host is.
@anuragthehatter @zhaozhanqi PTAL
> [networking] automate the host-device cni plugin case for multus

- features/storage/storage_object_in_use_protection.feature
- lib/rules/cli/4.0.yaml
@weherdh @chao007  
Jenkins log, Runner-v3/39855
> Update OCP-18796 for 4.x

- features/cli/oc_expose.feature
Pass log job/Runner-v3/39817/console
@zhouying7780 please help review, thanks
> Fix OCP-10873

- features/storage/storage_object_in_use_protection.feature
@weherdh @chao007 
Jenkins log, Runner-v3/39874
> Update OCP-17254 for 4.x

- features/storage/persistent_volume.feature
@zhouying7780 fyi
@akostadinov please help merge, thanks!
Pass log: Runner-v3/39958/console
> Fix OCP-11933 pvc not bound status

- features/storage/storage_object_in_use_protection.feature
@weherdh @chao007 
Jenkins log, Runner-v3/39948
> Update OCP-17253 for 4.x

- features/service_catalog_tsb/tsb.feature
Add case OCP-21690 for tsb v3.x
Remove OCP-15486 which is automated using many steps from UI.
Here's the log
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39716/console
@chengzhang1016 @akostadinov @pruan-rht please help review and merge, thanks.
> add case OCP-21690 for tsb

- features/storage/iscsi.feature
@weherdh @chao007 
Jenkins log, Runner-v3/40000
> Update OCP-9638 for 4.x

- features/networking/operator.feature
- features/step_definitions/networking.rb
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39963/consoleFull
@anuragthehatter @zhaozhanqi  PTAL
> [networking] Automate network-operator cases

- features/cli/build.feature
- features/registry/is.feature
- features/registry/registry.feature
- features/registry/remote.feature
Pass in my local host.
@openshift/devexp-qe @akostadinov Could you help review this? 
Thanks~
> Fix OCP-19631

- features/step_definitions/pv.rb
- lib/openshift/cluster_resource.rb
- lib/openshift/project_resource.rb
- lib/openshift/resource.rb
@liangxia sorry, didn't have time to test this but I think it should resolve 
the issue your team is hitting.
> workaround bug 1610661

- features/cli/build.feature
- features/registry/remote.feature
Passed locally
@openshift/devexp-qe @akostadinov Could you help review this change? Thanks~
> Fix OCP-10904

- features/web/overview.feature
- lib/rules/web/console/3.10/overview.xyaml
- lib/rules/web/console/3.11/overview.xyaml
- lib/rules/web/console/3.6/overview.xyaml
- lib/rules/web/console/3.7/overview.xyaml
- lib/rules/web/console/3.9/overview.xyaml
Sometimes CVP fails due to build can't be running and deployment can't be triggered, so I removed some steps to make it more stable @SSshahan  Can you please review the changes? Let me know if something must be added
[A Jenkins Pass Log](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/40680/console)
@anpingli  FYI
> fix OCP-13641

- features/cluster_configuration/cluster_logging_operator.feature
- features/step_definitions/logging.rb
- features/step_definitions/logging_metrics.rb
- features/test/logging_metrics.feature
- features/test/new_api.feature
- lib/openshift/cluster_logging.rb
- lib/openshift/install_plan.rb
- lib/openshift/package_manifest.rb
- lib/openshift/project.rb
- lib/openshift/subscription.rb
Polarion: [OCP-21311](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21311).  @anpingli @QiaolingTang, PTAL.  Thanks!
> clusterlogging installation via OLM

- features/storage/storage_class.feature
I Removed zone in the sc
@liangxia @weherdh Please help review
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/40781/console
> Remove parameter zone in 4.x

- features/build/buildlogic.feature
- features/cli/oc_set_build_hook.feature
- features/cli/resources.feature
Passed in my local host, @openshift/devexp-qe pls help to review it, thanks
> Updated scripts for 4.x

- features/step_definitions/resources.rb
Update no project return step for 4.x
> update no project return step for 4.x

- features/cli/policy.feature
- lib/rules/cli/4.0.yaml
@chao007 @weherdh 
Tested the changes on OSO Starter, and it passed.
> No need to create storage class for OCP-10447

- lib/host.rb
same as #208 but v3
/assign @pruan-rht
> predictable workdir under Jenkins

- features/svc-catalog_asb/asb.feature
Fix the parameter in `I process and create:` step in case.
Here's the log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/41216/console
@akostadinov @pruan-rht  please help review and merge, thanks.
> fix parameters in case for oc process

- lib/local_process.rb
- tools/launch_instance.rb
please hold on merging before we test change with master branch
> fix running a command without arguments during install

- lib/local_process.rb
@jianlinliu, now this should fix #223 issue you reported, thank you!
> command might be array of two element array so handle it

- features/cli/deploy.feature
@zhouying7780 please help review, thanks!
> Fix OCP-12151

- features/storage/quota.feature
> Update OCP-14382 for 4.x

- features/step_definitions/storage_class.rb
- features/storage/storage_class.feature
- features/test/storage_class.feature
> Move annotation is-default-class from beta to stable

- features/networking/operator.feature
- features/networking/pod.feature
> Fix typo of author

- lib/openshift/a_p_i_service.rb
- lib/openshift/namespace.rb
- lib/openshift/storage_class.rb
simple additions... I'll just merge it.  Helper for https://github.com/openshift/cucushift/pull/7001
> added a couple of new openshift resource objects.  

- lib/openshift/deployment.rb
- lib/openshift/ingress_controller.rb
- lib/openshift/service_monitor.rb
potential helper for https://github.com/openshift/cucushift/pull/6991
> added new openshift objects to help another PR

- features/service_catalog_tsb/tsb.feature
Add tsb case OCP-14477 for v3.x
here's log: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/41740/console
@chengzhang1016 @jianzhangbjz @akostadinov @pruan-rht  please help review and merge, thanks.
> add tsb case OCP-14477

- lib/rules/web/admin_console/4.1/actions.xyaml
- lib/rules/web/admin_console/4.1/check_links.xyaml
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/deployment.xyaml
- lib/rules/web/admin_console/4.1/environments.xyaml
- lib/rules/web/admin_console/4.1/filters.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.1/projects.xyaml
- lib/rules/web/admin_console/4.1/secrets.xyaml
- lib/rules/web/admin_console/4.1/status.xyaml
- lib/rules/web/admin_console/4.1/storage.xyaml
@akostadinov @yapei   Add 4.1 rules for web console. please help to merge. thanks
> 4.1 rules for web

- features/service_catalog_tsb/tsb.feature
Add OCP-14477 for tsb v4.x
Copy from PR: https://github.com/openshift/verification-tests/pull/244
Here's log in v4.1 env.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/41741/console
@jianzhangbjz @cuipinghuo @akostadinov @pruan-rht please help review and merge, thanks.
> add OCP-14477 for tsb v4.x

- lib/rules/web/admin_console/4.1/deployment.xyaml
- lib/rules/web/admin_console/4.1/environments.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
@yapei  @akostadinov  please help to review rules for [OCP-20954](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-20954), thank you.
> rules for OCP-20954

- lib/rules/web/admin_console/4.1/check_links.xyaml
- lib/rules/web/admin_console/base/logout.xyaml
Add rules for case ocp-22330, scenario pr: https://github.com/openshift/cucushift/pull/7016
Pls help to review, @yapei  or @SSshahan . Thanks!
> Add rules for case ocp-22330

- lib/rules/web/admin_console/4.1/goto.xyaml
@SSshahan  please help review, thanks!
Pass log see runner-v3 #41838
> fix rules for secrets

- tools/common.sh
- tools/install_os_deps.sh
- tools/jenkins/slaves/Dockerfile.rhel8
- tools/jenkins/slaves/Dockerfile.rhel8_base
- tools/os_deps/deps.yum.RHEL8
Reverts openshift/verification-tests#251
Lets see what the error is and test on a clean VM.
> restore "RHEL8 jenkins slave agent"

- features/storage/storage_class.feature
> Simplify the logic of default storage class

- features/storage/storage_class.feature
3.x supports parameter zone in storage class, while 4.x does not support that.
Update 4.x to clone from default storage class to get rid of the unsupported parameter.
Not touching the auto script parameters, so it can support both 3.x and 4.x (though some parameters are not used in 4.x).
> Remove region/zone from storage class as 4.x does not support that

- lib/openshift/project.rb
- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/filters.xyaml
@yanpzhan  @SSshahan  Can you please help review?
All test cases have passed locally, when no changes are requested I can submit Jenkins pass log
> fix OCP-19532

- features/step_definitions/resources.rb
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/projects.xyaml
@yapei  fix rules for OCP-19577 Check project page, please help to review. Thanks.
> Fix rules for OCP-19577

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
Wait pr #260 , in which check_page_contains is replaced by check_page_match.
Will update my pr after that pr merged.
> Add rules for case OCP-19653

- features/storage/storage_class.feature
> Automate OCP-24259

- lib/iaas/iaas.rb
```
11:35:26 INFO> HTTP GET https://xxx.upshift.xxx:13000
11:35:26 INFO> HTTP GET took 0.368 sec: 300 Multiple Choices
11:35:26 INFO> HTTP POST https://xxx.upshift.xxx:13000/v3/tokens
11:35:26 INFO> HTTP POST took 0.363 sec: 404 Not Found
```
> Fix openstack auth-url

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
> update click_button_on_page to click_buttonin 4.1

- lib/bushslicer.rb
- lib/launchers/cloud_helper.rb
- lib/launchers/packet.rb
original PR https://github.com/openshift/verification-tests/pull/241
> Cherry-pick packet support to v3

- lib/launchers/openstack10.rb
Add a helper function to allocate floating ip from a known network.
This is step one for ipi on osp automation support.
> support to allocate floating ip from known network name

- features/step_definitions/registry.rb
- lib/rules/cli/3.0.yaml
- lib/rules/cli/3.3.yaml
- lib/rules/cli/4.0.yaml
Since OCP internal registry has huge change, so add two steps for it. @openshift/devexp-qe Please review, thanks!
> Add steps for 4.x registry

- features/step_definitions/oauth.rb
Add the OAuth backup and restore step.
> Add oauth backup and restore step

- features/step_definitions/oauth.rb
> fix indentation and took out debug statement

- features/build/buildlogic.feature
> Split 13914 mapping the e2e test scripts

- features/storage/cloud_provider.feature
> Merge scenarios into scenario outlines

- features/online/rolebindingrestriction.feature
- features/online/route.feature
Hi @yasun, could you please help review these cases? Thanks.
Here is the Jenkins output for route cases, OCP-16318,OCP-16319,OCP-16320,OCP-16321: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/42286/console
And here is the output for rolebinding cases, OCP-13115,OCP-13795: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/42288/console
> Update some cases

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
Add rule for scenario: https://github.com/openshift/cucushift/pull/7037
pls help to review, thanks! @yapei
> add rules for ocp-21034

- config/config.yaml
@akostadinov @pruan-rht @mffiedler @chao007 
4.0 isn't a valid release/version.
> Fix the version

- features/build/buildconfig.feature
- features/build/dockerbuild.feature
- features/cli/oc_set_probe.feature
- features/cli/secrets.feature
In 4.x, no mysql:5.6 in openshift project, so updated it, work in my local host
@openshift/devexp-qe pls help to review it thanks
> Update cases to fit 4.x

- features/step_definitions/crd.rb
- lib/openshift/open_shift_a_p_i_server.rb
- lib/world.rb
Add openshiftapiserver to the crd backup and restore
> Add openshiftapiserver to the crd backup and restore

- features/build/buildlogic.feature
- features/cli/build.feature
- features/cli/create.feature
> Remove eol imagestreamtags

- features/storage/dynamic_provisioning.feature
> Merge azure scenario into scenario outlines

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/environments.xyaml
- lib/rules/web/admin_console/4.2/filters.xyaml
- lib/rules/web/admin_console/4.2/secrets.xyaml
Pass log in [cucushift PR 7046](https://github.com/openshift/cucushift/pull/7046)
> some fixes

- lib/rules/web/admin_console/4.2/deployment.xyaml
@SSshahan  @xiaocwan  Can you help review? THanks
> auto OCP-24423

- features/build/buildlogic.feature
- features/cli/build.feature
- features/cli/scale.feature
@openshift/devexp-qe  please help review, thanks
> Remove eol istags

- features/step_definitions/helper_services.rb
> Update github raw file URL

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.1/status.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/status.xyaml
@yanpzhan  @SSshahan   Please help review, thanks
> auto OCP-21772 check user starter guide on projects

- features/step_definitions/operator.rb
@openshift/devexp-qe pls help to review it, thx
> Add  step to update operator operand managementstate

- features/storage/dynamic_provisioning.feature
> Fix scenario dynamic provisioning

- features/step_definitions/storage_class.rb
- features/test/storage_class.feature
> Add step to patch 4.x default storage class to non-default

- features/step_definitions/storage_class.rb
@akostadinov @pruan-rht 
Address comment in https://github.com/openshift/verification-tests/pull/311#discussion_r314185906
> Cache resource storage class

- features/build/env.feature
- features/cli/build.feature
@openshift/devexp-qe pls review it, thx
> Fix cases in 4.x

- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.1/projects.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/projects.xyaml
The console removed the `Resource` & `Dashboard` button on v4.2.
@yapei please help to review. thanks
> Fix OCP-19577

- features/step_definitions/admin_console.rb
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/customizations.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/customizations.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/base/login.xyaml
- lib/rules/web/admin_console/base/logout.xyaml
> auto OCP-22640 Add HTPasswd IDP on console

- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.1/route.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/route.xyaml
Add rules for ocp-21004, https://github.com/openshift/cucushift/pull/7072
@yapei, Pls help to review, thanks!
> Add rules for ocp-21004

- lib/openshift/resource.rb
fixes issues with the new logic for multiple apis introduced
> [hotfix] rename #type to #kind and fix logic

- tools/openshift-ci/verification_tests_ci_entrypoint.sh
please wait until #333 is merged
> verification_tests_ci_entrypoint.sh should call all ruby commands with SCL

- lib/openshift/o_auth.rb
@yapei this should fix the issue that you saw earlier.
> fix array filtering in which  elements are present

- lib/rules/cli/4.0.yaml
Update the manage node command for 4.x
> update manage cmd for 4.x

- lib/rules/web/admin_console/4.2/configmap.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
@xiaocwan  @yanpzhan  Help review, thanks
> auto OCP-24342

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/overview.xyaml
- lib/rules/web/admin_console/4.2/actions.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/overview.xyaml
@yanpzhan  @xiaocwan  Please help review,thanks
> auto OCP-20932

- features/step_definitions/_constants.rb
- features/step_definitions/cli.rb
Used in this scenario, https://github.com/openshift/cucushift/pull/7073/files#diff-878a6aeaa4a0ae5226030bbd4eacf809R33
@openshift/devexp-qe  please help review, thanks~
> Add merge type for patch command

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/imagestream.xyaml
Add rules for ocp-24263. 
@yapei or @SSshahan pls help to review.
> Add rules for ocp-24263

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/deployment.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
@yapei pls help to review. Thanks
> auto OCP-21085

- lib/openshift/config_imageregistry_operator_openshift_io.rb
@akostadinov @xiuwang Please review, thanks!
> Create imageregistry operator cluster resource

- lib/rules/web/admin_console/4.1/deployment.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
@yapei  please help to review. Thanks
> rules for OCP-25203

- lib/rules/web/admin_console/4.2/deployment.xyaml
Add 4.2 rules for OCP-20849
@yapei Please help to review the 4.2 rules. 4.1 is quite different from 4.2. So if it looks good,  IMO it's better to merge this one first to avoid conflict between 4.2 PRs. Also I'm continue to update 4.1 rules.
> Add 4.2 rules for OCP-20849

- lib/rules/web/admin_console/4.2/overview.xyaml
@yanpzhan  Can you help review? Thanks
> add rules for auto ocp-21000

- lib/rules/web/admin_console/4.1/deployment.xyaml
@hasha @yanpzhan Plz review, thanks!
> Add 4.1 rules for deployment image

- features/step_definitions/logging.rb
- features/step_definitions/logging_metrics.rb
- features/support/clusterlogging_env.rb
- features/test/logging_metrics.feature
- lib/openshift/cluster_logging.rb
- lib/openshift/elasticsearch.rb
@anpingli @pruan-rht PTAL.
In this PR, I added some scripts to parse different log collectors, and I changed the files we use to create subscriptions to make it could be run in OCP 4.2 cluster.
Here is the log: http://pastebin.test.redhat.com/792801
> modify steps to deploy logging operators

- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
@yapei or @SSshahan pls help to reivew, thanks!
> Add rule for ocp-23610

- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
PASS log on 4.2: http://pastebin.test.redhat.com/805431
@yapei pls help to review.
> fix for OCP-20932

- features/step_definitions/logging.rb
- lib/openshift/cluster_logging.rb
- lib/openshift/elasticsearch.rb
I added some functions in the resource `cluster_logging` and `elasticsearch`, @anpingli @pruan-rht @akostadinov PTAL, thanks.
> add new functions for logging

- features/networking/service.feature
Auto SDN case OCP-21814.
Any comments will be welcomed, thanks!
@zhaozhanqi @anuragthehatter @lihongan
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/44884/console
> Auto OCP-21814

- lib/rules/web/admin_console/4.2/storage.xyaml
Scenario pr: https://github.com/openshift/cucushift/pull/7110
Pls help to review when you are available, @yapei , thanks!
> Add rules for OCP-24415

- features/logging/4.x/permission.feature
@anpingli PTAL.
Polarion case https://url.corp.redhat.com/8d1e6e3
> auto case OCP-25364

- features/step_definitions/networking.rb
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/44981/consoleFull
@huiran0826 @anuragthehatter @weliang1
Could you help review, thanks
> add step for delete the specifid ovs pod

- lib/rules/web/admin_console/4.1/catalog.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
Add rules for ocp-21250.
@yapei or @SSshahan  pls help to review, thanks!
> add rule for OCP-21250

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/imagestream.xyaml
Add rules for ocp-23880, pls help to review, thanks! @yapei or @SSshahan
> Add rules for ocp-23880

- features/machine/machine.feature
- features/step_definitions/machine.rb
- features/step_definitions/machine_set.rb
- lib/openshift/machine.rb
- lib/openshift/machine_set.rb
- lib/openshift/node.rb
Automated several test cases for machine-api. Tested with `Runner-v3 job #44505` -- passed.
@sunzhaohua2 @pruan-rht Would you please review?
Thanks
> Automated tests for machine-api

- tools/case_id_splitter.rb
> Use sample test case ID to not interfere with other tools

- features/logging/4.x/cluster_logging_operator.feature
@anpingli  PTAL, thanks.
Polarion cases: https://url.corp.redhat.com/bfc0843
Log: https://url.corp.redhat.com/3b95aa4
> auto ocp21333

- features/logging/4.x/kibana.feature
- features/step_definitions/logging_metrics.rb
- lib/rules/web/images/logging/logging.xyaml
Polarion case: https://url.corp.redhat.com/7335487
> auto case OCP-25599

- lib/openshift/proxy_config_openshift_io.rb
@openshift/devexp-qe please help to review it, thx
> Added cluster 'proxy' functions

- lib/rules/web/admin_console/4.2/route.xyaml
Pls help to review, @yapei or @SSshahan , thanks!
> add rules for ocp-23580

- features/admin/pod.feature
@akostadinov @pruan-rht  Follow up for comments in #407  
https://github.com/openshift/verification-tests/pull/407/files#r339362339
> Replace manually registered clean-up with unified clean-up

- features/step_definitions/logging.rb
Due to bz1752073, sometimes there may have problems when running automation job, so I change the script to deploy EO before deploying CLO. @anpingli PTAL, thanks.
> deploy EO firstly due to bz1752073

- features/logging/collector.feature
- features/step_definitions/logging_metrics.rb
@anpingli  PTAL, thanks.
Polarion cases: https://url.corp.redhat.com/5f6efcf
> auto case OCP-25365 OCP-18147

- features/build/dockerbuild.feature
- features/build/stibuild.feature
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/runner-v3/46611/console
@openshift/devexp-qe please review, thanks!
> Fix script to more strong

- features/storage/fsType.feature
@chao007 @duanwei33 
Tested on a 4.3 GCP cluster for ext3/ext4/xfs, the tests passed.
> Update fsType scenarios

- lib/rules/web/admin_console/4.1/check_links.xyaml
- lib/rules/web/admin_console/4.2/check_links.xyaml
Rules for ocp-24016, @yapei or @xiaocwan
> update rule for OCP-24016

- features/machine/machine.feature
Automated new test cases. Tested locally and passed.
> Automated and OCP-25652

- features/test/webconsole.feature
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
@QiaolingTang  @jianzhangbjz  @yanpzhan  Please help review the rules added for operator subscription. Let me know if there's anything need updates
> add rules for operator subscription

- features/step_definitions/registry.rb
- lib/rules/cli/4.0.yaml
- lib/world.rb
@openshift/devexp-qe Please help review, thx
> Add parameter for new-app cmd

- features/storage/storage_class.feature
> Fix checkpoint of using default storage class

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/storage.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/storage.xyaml
- lib/rules/web/console/base/login.xyaml
@yapei , pls help to review, thanks!
> Add rules for ocp-20964

- features/storage/storage_class.feature
> Automate OCP-25789

- features/cli/oc_volume.feature
- features/step_definitions/helper_services.rb
- features/step_definitions/registry.rb
- features/storage/add_update_delete_volume.feature
- lib/rules/cli/4.0.yaml
> Replace obsoleted cmd "oc volume" with "oc set volume"

- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.3/browser_opts.yml
- lib/rules/web/admin_console/4.3/catalog.xyaml
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/configmap.xyaml
- lib/rules/web/admin_console/4.3/customizations.xyaml
- lib/rules/web/admin_console/4.3/deployment.xyaml
- lib/rules/web/admin_console/4.3/environments.xyaml
- lib/rules/web/admin_console/4.3/filters.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/imagestream.xyaml
- lib/rules/web/admin_console/4.3/node.xyaml
- lib/rules/web/admin_console/4.3/overview.xyaml
- lib/rules/web/admin_console/4.3/projects.xyaml
- lib/rules/web/admin_console/4.3/route.xyaml
- lib/rules/web/admin_console/4.3/secrets.xyaml
- lib/rules/web/admin_console/4.3/status.xyaml
- lib/rules/web/admin_console/4.3/storage.xyaml
@akostadinov  @pruan-rht  Can you help merge? I just copied all rule files to `4.3`
> add rule files for 4.3

- features/logging/deploy_logging_operators_via_console.feature
- features/step_definitions/logging.rb
- lib/openshift/subscription.rb
- lib/rules/web/admin_console/4.2/goto.xyaml
@anpingli @yapei  could you please help to review this? Thanks.
case: https://url.corp.redhat.com/42aeeb5
Log: https://url.corp.redhat.com/71579e0
> auto case OCP-22558 OCP-24292

- features/storage/cloud_provider.feature
> Fix OCP-11613

- features/cli/pod.feature
- features/cli/policy.feature
- features/cli/projects.feature
- features/cli/serviceaccount.feature
- lib/environment.rb
There are some changes on output.So we need to modify the output logs checking.
> Fix 4.x oauth team test cases steps

- features/networking/sdn.feature
- features/step_definitions/networking.rb
Auto OCP-25707
Log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/48225/console
@anuragthehatter @zhaozhanqi  @rbbratta @weliang1
Can you help review? Thanks!
> Auto OCP-25707

- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/monitoring.xyaml
@SSshahan   Can you help review?
> rules added for OCP-25816

- features/build/buildconfig.feature
- features/build/buildlogic.feature
- features/build/stibuild.feature
- features/cli/oc_import_image.feature
- features/cli/secrets.feature
- features/registry/remote.feature
@openshift/devexp-qe Please help review this change, thanks~
> Update to use ruby-25-* images to do docker build

- features/step_definitions/logging.rb
- lib/rules/web/images/logging/login.xyaml
@akostadinov PTAL. Since @anpingli has added post actions to create the `qe-app-registry` to the clusters launched by jenkins, I modify the script to use `qe-app-registry` when there has the resources. 
Besides, there are some changes when log in to the kibana console, I add a new action to click the `Log in with OpenShift ` button if this button exists.
PTAL, thanks a lot.
> some fixes for CI testing

- lib/openshift/console_links_console_openshift_io.rb
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yanpzhan  Please help review. Thanks
> add rule files for OCP-25791,OCP-25840

- features/storage/hostpath.feature
Limit PV/PVC in storage class so it does not interfere with other test cases.
@chao007 @duanwei33
> Fix OCP-9639

- Gemfile
- features/step_definitions/logging_metrics.rb
- features/step_definitions/metering.rb
- features/step_definitions/net.rb
- features/step_definitions/web.rb
- features/support/env.rb
- lib/bushslicer.rb
- lib/cli_executor.rb
- lib/common.rb
- lib/environment.rb
- lib/http.rb
- lib/login.rb
- lib/openshift/route.rb
- lib/platform/master_service.rb
- lib/rest.rb
- lib/rules/cli/4.0.yaml
- lib/webauto/chrome_extension.rb
- lib/webauto/resource/chrome_crx3/README
- lib/webauto/resource/chrome_crx3/crx3.pb.rb
- lib/webauto/resource/chrome_crx3/crx3.proto
- lib/webauto/resource/chrome_proxy/background.js.erb
- lib/webauto/resource/chrome_proxy/manifest.json
- lib/webauto/web4cucumber.rb
- lib/webauto/webconsole_executor.rb
- tools/shell_proxy.sh
Reverts openshift/verification-tests#464
/hold
> Revert "Revert "private cluster proxy support""

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
> fix OCP-23044

- features/svc-catalog_asb/svc-catalog.feature
change the wait time from none to 300s for the ups-broker success
> Update the wait time

- features/cli/deploy.feature
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/49498/consoleFull
@xingxingxia  please help review, thanks.
> update ruby-22 failed

- features/cli/secrets.feature
> Fix failing

- lib/rules/cli/4.0.yaml
> Add options to create_secret and sort them alphanumeric

- features/test/upgrade.feature
- lib/polarshift/request.rb
- lib/polarshift/test_case.rb
- lib/polarshift/test_suite.rb
> allow name suffix when matching scenarios to allow upgrade prepare test use case

- features/step_definitions/admin_console.rb
- features/step_definitions/logging_metrics.rb
- lib/rules/web/images/logging/logging.xyaml
- lib/rules/web/images/logging/login.xyaml
@anpingli @yapei PTAL, thanks.
> update rules for OCP-20172

- features/upgrade/etcd/upgrade.feature
@akostadinov @pruan-rht This should be a normal upgrade testcase script based on our final decision, pls help to review, thanks!
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/49815/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/49818/console
> Upgrade ocp 22606

- features/storage/OWNERS
@petr-muller @pruan-rht @akostadinov
> Add owners for storage part

- lib/openshift/console_cli_download_console_openshift_io.rb
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.3/customizations.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@xiaocwan  It looks like your auto cases OCP-24287, OCP-24316 are missing rules and wrong libs. I updated in this PR FYI
@yanpzhan  Can you help review? runner-v3 job is scheduled but not started yet #5​01​50
> rule fixes

- lib/rules/web/admin_console/OWNERS
@yapei @akostadinov @pruan-rht
> Add owners for admin-console

- features/storage/pre-bind.feature
Test [log](https://privatebin-it-iso.int.open.paas.redhat.com/?3fa62b42749efd97#Ilpa/w6zeEw2b7emK7HRXThqJPP48oLre/1ljYMO7Ic=)
> Limit PV/PVC in storage class, so OCP-10107 no longer destructive

- features/step_definitions/machineconfig.rb
- lib/openshift/flakes/machine_config_pool_spec.rb
- lib/openshift/machine_config.rb
- lib/openshift/machine_config_pool.rb
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/filters.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/filters.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei pls help to review, thanks!
> Add rules for OCP-22308

- features/storage/pre-bind.feature
Test [log](https://privatebin-it-iso.int.open.paas.redhat.com/?c3f511c8dd0fd459#jorkSL5f0WPmU4R2zhWi12JOGr8pX4PO79bIFY73mW0=)
> Limit pre-bind PV/PVC in storage class to not interfere with each other

- features/networking/multus.feature
- features/step_definitions/networking.rb
Some more multus cases automated 
OCP-24467,OCP-24489 and OCP-24488
@zhaozhanqi @weliang1 @huiran0826 @rbbratta
> More multus cases

- features/networking/multus.feature
- lib/openshift/network_attachment_definition.rb
- lib/openshift/networkattachmentdefinition.rb
- lib/world.rb
Keeping the mutlus automation rolling while more on the way
Covered here are OCP-21949,OCP-21793 and OCP-21949
@zhaozhanqi @huiran0826 @weliang1 @rbbratta
> multus automation

- features/networking/sdn.feature
Auto OCP-25706
Log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/49250/console
Can you help review?
@weliang1 @zhaozhanqi @anuragthehatter  @rbbratta
> Auto OCP-25706

- features/build/OWNERS
- features/images/OWNERS
@wzheng1 @akostadinov @pruan-rht
> Add owners for devexp

- lib/rules/web/admin_console/4.3/status.xyaml
@yapei  please help to review. thanks
> fix OCP-19669

- lib/rules/web/console/3.11/login.xyaml
- lib/rules/web/console/base/login.xyaml
@SSshahan please help review.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/52207/console
> Modify steps to click another button

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
> Fix for the rule check_key_and_action_link

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch_operator.feature
- features/step_definitions/logging.rb
When checking the CI testing results, the cases the curl metrics always failed, I open this PR to use another pod to execute the curl command. 
@anpingli @akostadinov  PTAL, thanks.
> fix issue: getting metrics failed

- features/images/rhel8_images.feature
> Fix the rhel8 images auto

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/deployment.xyaml
@yapei @yanpzhan Please review. Thanks!
> auto OCP-25773

- features/cli/build.feature
- features/cli/oc_import_image.feature
> Fix scrips failing

- features/logging/cluster_logging_operator.feature
This scenario always failed when running CI testing, the ES pods are pending due to limited resources, so I update the script to only check the new ES deployment is created or not, don't check the pod status. @anpingli PTAL, thanks.
> fix failure of scaling up es pods when running CI testing

- lib/rules/web/admin_console/4.3/operator_hub.xyaml
@yapei  could you help to review? Thanks
> auto OCP-24340

- features/networking/egress-ip.feature
- features/step_definitions/networking.rb
Update OCP-15471, Auto OCP-15472
Here is logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/51961/console
@zhaozhanqi @anuragthehatter @weliang1  @rbbratta
> Update OCP-15471,Auto OCP-15472

- features/cli/configmap.feature
- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/deploy_logging_operators_via_console.feature
- features/logging/elasticsearch.feature
- features/logging/kibana.feature
- features/logging/permission.feature
- features/networking/pod.feature
- features/networking/service.feature
- features/online/images.feature
- features/svc-catalog_asb/apb-update.feature
- features/web/k8s-deployments.feature
> Fix author format

- features/cli/limits.feature
- features/cli/secrets.feature
- features/images/jenkins.feature
- features/quickstarts/quickstarts.feature
/cc @pruan-rht @akostadinov 
One author per line, to easier the calculation of automation contribution in sub-teams, so we can add proper reviewers later based on the calculation.
> One author per line

- features/routing/abrouting.feature
- features/routing/haproxy-router.feature
- features/routing/ingress-route.feature
- features/routing/rate-limit.feature
- features/routing/route.feature
- features/routing/timeout.feature
This one just a follow up PR of https://github.com/openshift/verification-tests/pull/533
> update all related cases to use the new step [follow up #533]

- features/logging/eventrouter.feature
- features/step_definitions/logging.rb
- lib/openshift/daemon_set.rb
Add step to install eventrouter and automate eventrouter related case @anpingli  PTAL
Runner-v3 log: https://url.corp.redhat.com/1398aca
> automate eventrouter related case

- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/step_definitions/logging.rb
Removing unnecessary steps.
@pruan-rht could you please help to merge it ? Thanks.
> remove unnecessary steps

- features/networking/multus.feature
OCP-24490, OCP24491 and OCP-24607
@weliang1 @zhaozhanqi @huiran0826 @rbbratta
> More n more multus auto

- features/admin/OWNERS
- features/cli/OWNERS
- features/cluster_configuration/OWNERS
- features/infrastructure/OWNERS
- features/logging/OWNERS
- features/machine/OWNERS
- features/metrics/OWNERS
- features/networking/OWNERS
- features/online/OWNERS
- features/quickstarts/OWNERS
- features/registry/OWNERS
- features/routing/OWNERS
- features/svc-catalog_asb/OWNERS
- features/upgrade/OWNERS
- features/upgrade/etcd/OWNERS
- features/web/OWNERS
- features/web/service-catalog/OWNERS
Add some default reviewers based on script author in the sub-dir.
> Add default sub-team reviewers

- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei  please help to review, thanks!
> auto OCP-24330

- features/storage/local-storage-operator.feature
- lib/openshift/operator_source.rb
- lib/world.rb
Test [log](https://privatebin-it-iso.int.open.paas.redhat.com/?f4ea4263ded35ab5#h21bWmrsT+Pg/5z5PD531ptkMNKB3biGTJ/vehJtJGI=)
> Automate OCP-24493

- lib/rules/web/admin_console/4.0/projects.xyaml
- lib/rules/web/admin_console/4.1/projects.xyaml
- lib/rules/web/admin_console/4.2/customizations.xyaml
- lib/rules/web/admin_console/4.2/projects.xyaml
- lib/rules/web/admin_console/4.3/customizations.xyaml
- lib/rules/web/admin_console/4.3/projects.xyaml
@yapei please help to review, thanks
> fix  OCP-24316  OCP-21772

- features/registry/registry.feature
- features/step_definitions/dc.rb
- features/step_definitions/registry.rb
> Fix OCP-12400

- features/networking/multus.feature
Auto test case: OCP-25676
Logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/499/console
> Automate OCP-25676

- lib/openshift/console_external_log_link.rb
- lib/rules/web/admin_console/4.2/check_links.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/world.rb
@yapei please help to review, thanks!
> automated OCP-24416

- lib/rules/web/admin_console/4.2/check_links.xyaml
- lib/rules/web/admin_console/4.3/check_links.xyaml
[OCP-24286
](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-24286)@yapei  please help to review, thanks
> autocase OCP-24286

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/operator_hub.xyaml
@yapei  could you help to review the cases? Thanks
> auto OCP-25931 

- features/cli/policy.feature
Test [log](https://privatebin-it-iso.int.open.paas.redhat.com/?9692c05f33b957c7#Vcv2vUdMI8wMvjMokxJyt5TmcOrpZzUERolHS+eKnM0=)
> Simplify OCP-10467

- features/images/jenkins.feature
> Auto OCP-25401

- features/images/rhel8_images.feature
@openshift/devexp-qe please help to  review it, pass it in local.
> Auto OCP-22958

- lib/rules/web/admin_console/4.1/overview.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/overview.xyaml
- lib/rules/web/admin_console/4.3/overview.xyaml
@yanpzhan  Can you help review? Thanks
> rules added for OCP-21256

- lib/rules/web/admin_console/4.2/actions.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
Add rules for OCP-24232
@yapei or @xiaocwan pls help to review,thanks!
> add rules for OCP-24232

- lib/rules/web/admin_console/4.1/projects.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/projects.xyaml
- lib/rules/web/admin_console/4.3/projects.xyaml
@SSshahan  Can you help review?
> fix OCP-21772,OCP-19577

- lib/rules/web/admin_console/4.3/overview.xyaml
@SSshahan  @yapei Please review, thanks!
> Add rules for popover case OCP-25792

- lib/openshift/console_external_log_links_console_openshift_io.rb
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/logs.xyaml
@yanpzhan 
Please review, thanks!
> Add rules for OCP-25868

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/route.xyaml
@yanpzhan  Can you help review? Thanks
OCP-26040 is added too
> rules added for OCP-26170

- lib/openshift/console_yaml_samples_console_openshift_io.rb
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yanpzhan  Please help review. thanks
> rules for OCP-25817

- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei  Plz review, thanks!
@pruan-rht  This rule is duplicated which blocks all auto running, rebased and hope it gets merge asap, thanks!
> remove duplicated rule goto_one_pod_log_page

- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
Pls help to review, thanks! @yapei
> add rule for OCP-19725

- features/networking/multus.feature
- features/networking/operator.feature
- features/networking/pod.feature
- features/step_definitions/networking.rb
Putting comments in each case explaining whats changed and why.
@zhaozhanqi @huiran0826 @weliang1 @rbbratta 
Thanks Zhanqi for tracking spreadsheet for failed cases
> Fixes in various test cases

- features/networking/egress-ip.feature
Auto OCP-21812 OCP-15473
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/56299/consoleFull
@zhaozhanqi  @anuragthehatter @weliang1 @rbbratta
> Auto OCP-21812 OCP-15473

- lib/rules/cli/4.1.yaml
- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/user_management.xyaml
@yapei Plz review, thanks!
There is one rule **as below** I haven't commit, it needs to merge into lib/rules/web/admin_console/4.3/user_management.xyaml when [This PR ](https://github.com/openshift/verification-tests/pull/550/files) merged.
```
delete_user_from_kebab:
action: click_kebab_of_one_resource
action: choose_action_item_from_list
action: submit_changes
```
> Update rules for OCP-25763

- lib/openshift/template_instance.rb
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/catalog.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei pls help to review. Thanks!
> add rule for OCP-23615

- features/step_definitions/ds.rb
- lib/openshift/daemon_set.rb
> Add steps for OCP-26732

- lib/openshift/package_manifest.rb
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/user_management.xyaml
@yapei  please help to review, thanks!
> auto OCP-25765

- lib/rules/web/admin_console/4.3/goto.xyaml
@pruan-rht  could you help to merge it? console cases failed due to duplicated rules exist. 
@yapei  FYI.
> (Urgent)duplicated rules for console

- lib/rules/web/admin_console/4.3/overview.xyaml
Fix for OCP-25792, passed locally. @yapei, pls help to review, thanks!
> fix for OCP-25792

- lib/openshift/machine_autoscaler.rb
- lib/rules/web/admin_console/4.2/actions.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/node.xyaml
- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/node.xyaml
- lib/rules/web/admin_console/base/login.xyaml
- lib/webauto/web4cucumber.rb
@xiaocwan  @yanpzhan  Please help review the changes
> rules added for OCP-23688

- lib/rules/cli/4.1.yaml
@pruan-rht @akostadinov @jhou1 @yapei 
Note for the messages `242 additions and 247 deletions`,
1. Removed 2 empty line at the end of the file
2. Removed 3 duplicate options.
> Sort CLI cmd/options in alphanumeric order

- lib/rules/web/admin_console/3.11/goto.xyaml
@pruan-rht This is the 3.11 rule for OCP-19577.
Plz review and merge, thanks.
Will update OCP-19577 for feature file.
> add rule goto_one_dc_page for 3.11

- lib/rules/cli/4.1.yaml
@pruan-rht @akostadinov 
Follow up of https://github.com/openshift/verification-tests/pull/606
> Remove CLI CMD oc_secrets_new_*, replaced by secrets_new_*

- lib/rules/web/admin_console/4.1/catalog.xyaml
- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/catalog.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
> rules for OCP-21111

- features/web/create.feature
> Fix OCP-11171 for stable

- features/cli/policy.feature
- features/cli/projects.feature
- features/step_definitions/policy.rb
- lib/rules/cli/4.1.yaml
> Added missing CMD policy in add/remove role/cluster-role

- lib/environment.rb
`Common::Net.dns_lookup(fqdn, multi: true)` doesn't work in private cluster since no public DNS for the routes.
We have implemented a new step in https://github.com/openshift/verification-tests/pull/533 to get default router IP, but the step `I store default router subdomain in the :subdomain clipboard` doesn't work in private cluster either. And we find that the method `get_routing_details` mixed those two options in one method and cause error even when you only want to get `router_subdomain`.
This PR fixes the issue by adding one argument to split them.
> fix getting router subdomain

- lib/rules/cli/4.1.yaml
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.3/catalog.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei This is for 4.3, will update 4.2 rules when this one looks good. Please review, thanks!
> Automate OCP-24106

- lib/rules/cli/4.1.yaml
@pruan-rht @akostadinov 
Follow up of https://github.com/openshift/verification-tests/pull/609
/hold
until https://github.com/openshift/verification-tests/pull/609 and https://github.com/openshift/cucushift/pull/7322 are merged.
> Remove CLI CMD oadm_add/remove, replaced by oadm_policy_add/remove

- lib/rules/cli/4.1.yaml
@xingxingxia This request is required by pull request https://github.com/openshift/cucushift/pull/7326, the test results see pull 7326. Please help to review, thanks.
> add option api_version for oc explain

- features/networking/multus.feature
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/512/console
> Automate test case OCP-25909

- features/networking/egress-ip.feature
Logs: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/59622/console
Can you help review? Thanks!
@zhaozhanqi @weliang1  @anuragthehatter @rbbratta
> Auto OCP-15992

- features/step_definitions/pod.rb
- features/test/pod.feature
@anpingli  For https://projects.engineering.redhat.com/browse/OPENSHIFTQ-12910
> Show pod info when pod not ready

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
@pruan-rht Could you help to merge it asap please? Thanks!
This is caused by missing resolving one of many conflicts by the old PR #494
> a hot fix for merging resolving conflicts

- features/storage/persistent_volume.feature
Removed 4.1/4.2/4.3 from OCP-9931 in polarion.
Added OCP-26879..OCP-26884 for the checkpoints in 4.x
> Automate OCP-26879 till OCP-26884

- features/build/buildlogic.feature
> Auto OCP-19133

- features/networking/multus.feature
@pruan-rht Can you help merge it to unblock few CI failures? Re-ran to make sure
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/521/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/522/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/523/console
> Small optimizations and fixes found on CI runs

- features/upgrade/workloads/oc-upgrade.feature
@geliu2016 @xingxingxia  Please help review , thanks.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/60696/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/60705/consoleFull
> auto upgrade case ocp-13032

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/explore.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.2/projects.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/explore.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.3/projects.xyaml
Pls help to review, @yapei or @xiaocwan , thanks!
> Add rules for OCP-24306

- lib/local_process.rb
- tools/launch_instance.rb
not sure how nobody noticed that STDERR was missing in shell commands
> fix stderr output of shell commands in installer

- features/step_definitions/logging.rb
- lib/openshift/cluster_logging.rb
- lib/openshift/cron_job.rb
- lib/openshift/deployment.rb
- lib/openshift/elasticsearch.rb
- lib/openshift/log_forwarding.rb
- lib/openshift/prometheus_rule.rb
- lib/rules/web/images/logging/logging.xyaml
Adding methods and lib files for logging cases.
@pruan-rht could you please help to merge this PR? Thanks.
> add methods and lib files for logging cases

- tools/polarshift.rb
Hi @akostadinov @pruan-rht 
Add this command for get test cases results. It's copied from 4.x and will return a Json file for all test cases status. Could you help to review please? Thanks!
> add get-run for tools

- features/registry/registry.feature
- features/step_definitions/dc.rb
- features/step_definitions/registry.rb
- lib/rules/cli/4.1.yaml
> Auto OCP-18994 and OCP-18998

- features/registry/is.feature
Depend on https://github.com/openshift/verification-tests/pull/566
> Auto OCP-19196 and OCP-16495

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/idp.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/idp.xyaml
Add rules for ocp-23608 and ocp-23202
Pls help to review, thanks! @yapei
> Add rules for idp cases

- lib/rules/web/admin_console/3.11/common_ui_elements.xyaml
- lib/rules/web/console/3.11/login.xyaml
- lib/rules/web/console/base/login.xyaml
1. remove dup rule submit_changes
2. add rule from master to v3 check_page_match (original created in master by [this PR](https://github.com/openshift/verification-tests/pull/260/files#diff-e190485462a319dbbf1001a14f81b8d7))
@yapei  Please review, thanks!
> remove dup rule submit_changes, add rule from master to v3 check_page_match

- features/networking/multus.feature
- features/networking/operator.feature
- features/networking/service.feature
- features/step_definitions/networking.rb
Found during nightly CI runs
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/534/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/535/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/536/console
@zhaozhanqi @rbbratta @weliang1 @huiran0826 
@pruan-rht Can you help merging it?
> Few fixes and optimizations

- config/config.yaml
- features/step_definitions/ocm.rb
- features/step_definitions/ocm/ocm.rb
- lib/bushslicer.rb
- lib/environment.rb
- lib/rules/web/ocm_console/login.xyaml
- lib/user_manager.rb
/hold
/assign @yuwang-RH
supersedes #469
> OCM console testing support

- features/networking/multus.feature
Automation testing log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/513/console
> Automate test case OCP-25910

- lib/rules/web/admin_console/4.1/overview.xyaml
- lib/rules/web/admin_console/4.2/overview.xyaml
- lib/rules/web/admin_console/4.3/overview.xyaml
@yanpzhan  Can you help review?
> rules added for OCP-21270

- features/networking/multus.feature
Auto testing log: http://pastebin.test.redhat.com/826842
> Add multus default route overwrite

- lib/rules/cli/4.1.yaml
> Fix "oc create options"

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
@yapei  please help to review, thanks!
> rules for OCP-25793

- features/admin/pod.feature
@jhou1 @sunilcio @lyman9966 
Would you mind taking a look?
Execution log with the fix: http://pastebin.test.redhat.com/828686
> Fixing the issue pods try to get scheduled to master nodes

- tools/polarshift.rb
```
./tools/polarshift.rb clone-run 20191205-1157
Source run id '20191205-1157' cloned to new run id: '20191207-0022'
```
> added ability to clone a polarion testrun given a testrun id

- lib/rules/cli/4.1.yaml
@xingxingxia Could you pls help to review? Thanks.
> add dry-run options for 'oc debug' command

- features/step_definitions/pvc.rb
- features/step_definitions/secrets.rb
/cc @pruan-rht @akostadinov 
Could you help check ?
Also @duanwei33 @chao007 for awareness of the change.
> Remove useless version check in pvc steps

- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.4/browser_opts.yml
- lib/rules/web/admin_console/4.4/builds.xyaml
- lib/rules/web/admin_console/4.4/catalog.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/configmap.xyaml
- lib/rules/web/admin_console/4.4/customizations.xyaml
- lib/rules/web/admin_console/4.4/deployment.xyaml
- lib/rules/web/admin_console/4.4/environments.xyaml
- lib/rules/web/admin_console/4.4/explore.xyaml
- lib/rules/web/admin_console/4.4/filters.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/idp.xyaml
- lib/rules/web/admin_console/4.4/imagestream.xyaml
- lib/rules/web/admin_console/4.4/logs.xyaml
- lib/rules/web/admin_console/4.4/machine.xyaml
- lib/rules/web/admin_console/4.4/monitoring.xyaml
- lib/rules/web/admin_console/4.4/node.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
- lib/rules/web/admin_console/4.4/projects.xyaml
- lib/rules/web/admin_console/4.4/quota.xyaml
- lib/rules/web/admin_console/4.4/route.xyaml
- lib/rules/web/admin_console/4.4/secrets.xyaml
- lib/rules/web/admin_console/4.4/status.xyaml
- lib/rules/web/admin_console/4.4/storage.xyaml
- lib/rules/web/admin_console/4.4/user_management.xyaml
- lib/rules/web/admin_console/4.4/users.xyaml
@pruan-rht  @yanpzhan  please help to review, thanks. cc: @yapei
> add 4.4 rules for UI team

- .gitignore
> make sure vendor gem dir not committed

- features/networking/multus.feature
Fix the flake testing results for OCP-21489
Test log: http://pastebin.test.redhat.com/831805
> Fix OCP-21489

- lib/rules/web/console/base/login.xyaml
@yapei  The log in button text was changed in the latest 4.4 nightly build, updated the rule to be more common.
> Update log in rules

- lib/rules/cli/4.1.yaml
@pruan-rht Request you to please review and share feedback if any. Thanks!
> Add options for 'oc adm node-logs' command

- lib/openshift/flakes/pod_volume_spec.rb
- lib/openshift/pod_replicator.rb
> add volumes to PodReplicator

- features/networking/egress-ingress.feature
Using curl instead of ping for https://issues.redhat.com/browse/SDN-797
Test logs:
http://pastebin.test.redhat.com/833857
http://pastebin.test.redhat.com/833861
http://pastebin.test.redhat.com/833866
http://pastebin.test.redhat.com/833872
http://pastebin.test.redhat.com/833874
@zhaozhanqi @huiran0826 @rbbratta
> Using curl instead of ping

- lib/openshift/cluster_logging.rb
- lib/openshift/elasticsearch.rb
@akostadinov @pruan-rht PTAL, thanks.
> add curation_schedule method

- features/storage/nfs.feature
Limit PV/PVC in storage class, so it no longer interfere with other PV/PVC.
> Rewrite OCP-9572 to be non-destructive

- lib/rules/web/console/base/login.xyaml
> fix rules for idp selection

- lib/rules/web/admin_console/4.1/storage.xyaml
- lib/rules/web/admin_console/4.2/storage.xyaml
- lib/rules/web/admin_console/4.3/storage.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.4/storage.xyaml
@yapei  please help to review. thanks.
> Fix OCP-21461/OCP-21034

- lib/rules/cli/4.1.yaml
@xingxingxia @pdhamdhe Could you pls help to review? Thanks.
> add rules for oc comands

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/deployment.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/deployment.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/deployment.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/deployment.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
@SSshahan  Can you help review? Thanks
> 4.4 rule fixes

- features/images/jenkins.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/test/storage.feature
@xiuwang @pruan-rht @akostadinov
> Fix case_id

- features/networking/operator.feature
add one step to make sure all nodes changed to 'ready' otherwise it will affect the next case execution with error eg. error cannot get the token for user
> add one step to make sure all nodes are changed to ready

- features/cli/hpa.feature
update the matching content according to oc output. 
FYI: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/68534/console
> modify autocase OCP-10931

- lib/rules/web/admin_console/base/login.xyaml
@SSshahan  Can you help review? Thanks
> fix click_specified_idp

- lib/openshift/flakes/image_stream_tag_spec.rb
> annotations access for image stream tag specification

- features/build/buildconfig.feature
- features/build/buildlogic.feature
- features/cli/secrets.feature
- features/step_definitions/helper_services.rb
@openshift/devexp-qe Please help review this, thanks
> Replace old secret cmds

- features/networking/sdn.feature
Testing for bug https://bugzilla.redhat.com/show_bug.cgi?id=1796157
Testing Log:
http://pastebin.test.redhat.com/835579
@zhaozhanqi @huiran0826 @rbbratta
> Automate OCP-27655

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch_operator.feature
- features/step_definitions/logging.rb
- features/step_definitions/logging_metrics.rb
- lib/openshift/flakes/prometheus_rule_group_rule_spec.rb
- lib/openshift/flakes/prometheus_rule_group_spec.rb
- lib/openshift/flakes/service_monitor_endpoint_spec.rb
- lib/openshift/prometheus_rule.rb
- lib/openshift/service_monitor.rb
cases: https://url.corp.redhat.com/f645145
pass log: https://url.corp.redhat.com/d296b54
> logging alert rules testing

- features/build/buildlogic.feature
When tested in http_proxy env, always met http://pastebin.test.redhat.com/827395, cannot connect mirrorlist.centos.org in temporary container  , IMO It's not a issue, so update scripts.
@openshift/devexp-qe pls check, thanks
> Fix OCP-10745

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/monitoring.xyaml
- lib/rules/web/admin_console/4.4/projects.xyaml
@yanpzhan  @SSshahan  Please help review,thanks
> rules added for OCP-26984

- features/svc-catalog_asb/svc-catalog.feature
Sometimes will occur the clusterservicebroker type doesn't exist. Add the resource check before test the service catalog .
> add the check of clusterservicebroker before the testcases

- features/routing/abrouting.feature
The A/B routing test cases are not stable when just depending on `curl` and counting result. 
In the OCP 4.x test env, the number of router pod is not a fixed value and always more than one, and the config in each router is reloaded asynchronously, so the cases are random failed and need to debug manually. 
In order to make them more stable I'd like to update the cases to check the config directly (weight 0-256). 
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/72779/consoleFull
> update AB routing cases

- lib/openshift/cron_job.rb
- lib/openshift/pod_replicator.rb
@akostadinov @pruan-rht PTAL, thanks.
> add tolerations method

- lib/webauto/web4cucumber.rb
@akostadinov  @yapei  Make chromedriver to accept insecure cert automatically based on comment https://bugs.chromium.org/p/chromium/issues/detail?id=1056073#c6
@yanpzhan  @xiaocwan  FYI
> Fix chrome login issue

- features/cli/build.feature
@openshift/devexp-qe  please review it, thanks
> Fix OCP-10944

- features/cli/oc_secrets.feature
Since "oc secret new" is deprecated,we have to change it to "oc create secret".
> Since "oc secret new" is deprecated,we have to change it to "oc create secret".

- lib/launchers/dyn/dynect.rb
> fix issue when credentials do not come from env variable

- lib/openshift/image_manifest_vuln.rb
- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
@yanpzhan please help to review the pr, thx.
> Automated OCP-26029

- features/machine/autoscaler.feature
- features/step_definitions/machine.rb
- features/step_definitions/machine_set.rb
- lib/openshift/cluster_autoscaler.rb
- lib/openshift/machine_set.rb
Automated clusterautoscaler test case, @sunzhaohua2 @miyadav please review.
Tested locally.
```
[09:39:09] INFO> === End After Scenario: Cluster should automatically scale up and scale down ===
19 steps (19 passed)
15m47.689s
```
> Automate clusterautoscaler test case

- features/step_definitions/secrets.rb
To help with https://github.com/openshift/cucushift/pull/7422
@duanwei33 @chao007
> Fix the step to get Azure file secret name and key

- features/registry/registry.feature
> Auto OCP-18995

- features/upgrade/web/console-upgrade.feature
Add upgrade case for console, pls help to review. @yapei @geliu2016 
prepare and check pass log in: http://pastebin.test.redhat.com/838261
> Auto console case for upgrade

- features/networking/multus.feature
- features/networking/operator.feature
- features/test/version_compare.feature
4.0 isn't a valid version for OCP, replace it with 4.1
> Replace invalid version 4.0 with 4.1

- lib/rules/cli/4.1.yaml
Adding support for oc create_deployment to fix test case OCP-15156
> Adding support for oc create_deployment

- lib/rules/web/admin_console/4.3/users.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/users.xyaml
> fix OCP-25762 OCP-25931

- features/machine/autoscaler.feature
Automate 3 CAO cases. @jhou1 @miyadav please help to review, thanks.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/72746/console
> add CAO cases

- lib/rules/web/admin_console/4.4/masthead.xyaml
- lib/rules/web/admin_console/4.4/notification.xyaml
@yapei  please help to review. Thx!
> Automated OCP-27654

- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
> Auto OCP-20984

- features/step_definitions/operators.rb
- features/step_definitions/upgrade/3rd_operator.rb
- features/upgrade/tsb/upgrade.feature
@anpingli @chengzhang1016 @emmajiafan @cuipinghuo Please have a review, thanks!
> An example for 3rd operator upgrade automation

- features/storage/OWNERS
> Update reviewers for storage

- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/step_definitions/machine_set.rb
Per the comment https://github.com/openshift/verification-tests/pull/776/files#r389969728, it's good to have the clean-up registered in step definition.
@sunzhaohua2 @miyadav @akostadinov @liangxia PTAL.
> Register clean-up automatically

- features/storage/nfs.feature
The workaround for bug #1810971, I think it's not a storage bug, if we know what's the root cause, we should create a new case for it.
> Bug fix for nfs pv check data error

- features/step_definitions/web.rb
@yapei, @xueli181114, PTAL if it addresses your need.  Thx!
> helper step to close the current browser

- lib/rules/web/admin_console/4.4/deployment.xyaml
1) input_value xpath changed
2) page form changed, Search button has been removed, clicking anywhere else takes place for Search button. Here I click the radio button 
@SSshahan Please review. Thanks!
PASS locally on Firefox http://pastebin.test.redhat.com/842577
> fix OCP-20849 search_image for input_value xpath and search button removed issue

- lib/openshift/egress_network_policy.rb
> Helper for PR#752

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@xiaojiey Could you please help to review ? Thanks!
> Add clusterrolebinding command option

- features/machine/autoscaler.feature
I updated the cloned machinesets name to `machineset-clone-caseid`, please help to take a look. @jhou1 @miyadav
> update clone machineset name

- lib/rules/web/admin_console/4.4/catalog.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/deployment.xyaml
@yapei fix rules for OCP-23610,OCP-20954,OCP-25791 pls help to review.
> fix web cases

- features/networking/egress-ingress.feature
Auto OCP-13506
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/73870/console
@zhaozhanqi @weliang1 @anuragthehatter @rbbratta
> Auto OCP-13506

- lib/host.rb
> fix method to ignore garbage from stderr

- features/networking/service.feature
Auto test log for 6 cases:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/514/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/515/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/516/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/517/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/518/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/519/console
> Add service externalIP

- features/machine/autoscaler.feature
- features/step_definitions/machine_set.rb
@sunzhaohua2 @miyadav PTAL. Allow longer timeout for platforms like Azure.
> Autoscaler enhancement

- features/step_definitions/node.rb
- features/test/node.feature
Make precondition check of fips to a step for #745
Once we found a better way to do the precondition check, we only need to update the steps here, which is a one time change.
> Helper for #745

- lib/rules/web/admin_console/4.4/user_management.xyaml
[4.4 pass log](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75884/console)
> some rule fixes

- features/build/buildlogic.feature
@openshift/devexp-qe please review it, thanks
> Fix OCP-11767

- features/machine/machine.feature
test automation for - https://bugzilla.redhat.com/show_bug.cgi?id=1796344 
Execution successful - https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/74723/console
>  OCP27609 - Scaling machineset with PublicIp set to true

- features/step_definitions/scheduler.rb
- lib/openshift/pod.rb
- lib/openshift/priority_class.rb
Add support for resource type priority classes and also adds library which helps to delete a priority class after scenario.
> Add support for resource type priority classes

- features/registry/is.feature
It passed in my local host.
@openshift/devexp-qe please help review it, thanks
> Make time longer

- features/networking/pod.feature
- features/step_definitions/upgrade/3rd_operator.rb
- features/upgrade/tsb/upgrade.feature
If the file does not exist in v3-testfiles, help push it there.
> Use team repo

- lib/rules/cli/4.1.yaml
@xingxingxia could you please help review ? thanks .
> add create poddisruptionbudget

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/yaml.xyaml
- lib/rules/web/admin_console/4.4/yaml_page.xyaml
[OCP-23967](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-23967)
@yapei please help to review, thx
> automated OCP-23967

- lib/rules/web/admin_console/4.2/overview.xyaml
- lib/rules/web/admin_console/4.4/overview.xyaml
This case highly reproduced failure in automation runs.
Compared across versions from 4.2 to 4.4, only 4.2 needs to fix for the rule. 
Confirmed by running jobs with PASS log:
[PASS on 4.2](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/76635/console)
[PASS on 4.3](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/76644/console)
[PASS on 4.4](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/76641/console)
@yapei Help to review, thanks!
> Fix OCP-20932

- features/step_definitions/scheduler.rb
I actually wanted this function to be called at teardown so modified the function accordingly
> Modified the func for teardown

- lib/openshift/o_auth.rb
Add idp support for idp cases, pls help to review, thanks! @yapei
> update idp script

- features/step_definitions/node.rb
For OCP-14354 we need to delete a node, but the test will fail
unless we re-create it at the end.
Add two steps, one to save the node yaml to a clipboard and
the other to re-create the node from the clipboard yaml
> OCP-14354: add steps to restore deleted node from clipboard

- features/step_definitions/logging.rb
Adding steps to deploy rsyslog server.
Currently, we didn't figure out how to deploy rsyslog server as secure, so only insecure rsyslog server will be deployed.  I will add steps for the secure rsyslog server later.
> add step to deploy syslog server

- features/networking/service.feature
Auto OCP-11645
@zhaozhanqi @weliang1 @anuragthehatter @rbbratta 
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/68183/console
> Auto OCP-11645

- features/step_definitions/operators.rb
- features/upgrade/marketplace/upgrade.feature
- lib/openshift/catalog_source_config.rb
- lib/openshift/custom_resource_definition.rb
- lib/world.rb
@emmajiafan Could you help have a review? Thanks!
> Marketplace upgrade test

- features/upgrade/workloads/oc-upgrade.feature
@kasturinarra  could you help review ? thanks.
> update for ocp-13032 failed

- features/step_definitions/scheduler.rb
@xingxingxia @kasturinarra  could you please help review ? thanks
> add lib for scheduler cluster CR

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
> Auto OCP-27495

- lib/rules/web/admin_console/3.11/search.xyaml
- lib/rules/web/admin_console/4.0/search.xyaml
- lib/rules/web/admin_console/4.1/search.xyaml
- lib/rules/web/admin_console/4.2/search.xyaml
- lib/rules/web/admin_console/4.3/search.xyaml
- lib/rules/web/admin_console/4.4/filters.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/projects.xyaml
- lib/rules/web/admin_console/4.4/search.xyaml
@yapei pls help to review, thanks!
> Add rules for OCP-27550

- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
@yapei please help to review, thanks
> Automated OCP-19675

- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml
- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
- testdata/logging/logforwarding/rsyslog/rsyslogserver_svc.yaml
Hi @liangxia , I noticed you have changed the test files and scripts' url, some of my test files ([1], [2]) are missed, I'm adding these files, PTAL, thanks.
[1]https://github.com/openshift/verification-tests/blob/master/features/step_definitions/logging.rb#L406
[2]https://github.com/openshift/verification-tests/blob/master/features/step_definitions/logging.rb#L477-L478
> add some files for logging

- features/upgrade/marketplace/upgrade.feature
As title, solve this failure: http://virt-openshift-05.lab.eng.nay.redhat.com/buildcorp/Runner-v3/77291/console
> replace etcd with codeready-toolchain-operator

- features/networking/sdn.feature
Corrected testcase ID and added one more check as per test case steps (missed that earlier)
@pruan-rht Can you help merging this quick fix?
Re-run Logs: http://pastebin.test.redhat.com/847834
> Corrected test case ID and added an extra check

- lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
**Depend on the following PR**
https://github.com/openshift/cucushift/pull/7471
**Automated test OCP-28106 Developer query browser feature - common user**
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-28106
**preflight run pass with the following jenkins**
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/76675/
> hongyli automate case OCP-28106 verification-tests

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
**The PR depend on PR:**
https://github.com/openshift/cucushift/pull/7493
**Enhance test failures for the following cases in run Automation run(20200324-2020):**
These cases failed for there are too any alerts, the opened one is not in the view, so I add filter before open the alert
1. OCP-21144
2. OCP-21199
3. OCP-21150
**solved comments from Yadan in PR:**
openshift/verification-tests#787
> solve comments from Yadan and fix 4 test failures

- lib/launchers/openstack.rb
```
services:
......
openstack_osp16_titan25:
tenant_name: "shiftstack"
user: shiftstack_user
password: xxx
domain: { name: "Default" }
url: http://xx.xx.xx.xx:5000/v3/auth/tokens
key: openshift-qe
host_opts:
user: root
ssh_private_key: xxx.pem
class: SSHAccessibleHost
cloud_type: openstack
image: rhcos-xxx
proxy: http://xx.xx.xx.xx:8888
```
```
[1] pry(#<BushSlicer::DefaultWorld>)> iaas = iaas_by_service("openstack_osp16_titan25")                   
[2] pry(#<BushSlicer::DefaultWorld>)> iaas.get_floating_ips                                              
=> [{"id"=>"079ba68e-8f88-493b-bccb-780b1dbea2a5",                                                       
"tenant_id"=>"af00b96789454b3d8b86b4140e836427", …
```
> [OSP] add proxy support for private OSP

- lib/launchers/openstack.rb
Reverts openshift/verification-tests#851
need better approach
> Revert "[OSP] add proxy support for private OSP"

- features/logging/elasticsearch.feature
- features/step_definitions/logging.rb
- testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
@anpingli I'm updating the scenario OCP-22050 to make it more simple, PTAL, thanks.
> simplify OCP-22050

- features/cli/secrets.feature
http://pastebin.test.redhat.com/847614
@kasturinarra Could you please help review ? thanks.
> update for failed

- features/machine/machine_healthcheck.feature
Adding the node drain checkpoint. @sunzhaohua2 @miyadav PTAL.
```
[03:49:55] INFO> === End After Scenario: Remediation should be applied when the unhealthyCondition 'Ready' is met ===
12 steps (12 passed)
18m1.937s
```
> Verify node is drained when machine is deleted

- features/routing/route.feature
> Remove debug step in scenario for OCP-14059

- features/svc-catalog_asb/svc-catalog.feature
Add the wait time for "my-secret",delete the "Given admin ensures "ups-broker" clusterservicebroker is deleted" since the cluster delete the ups-broker after every auto cases.
@jianzhangbjz  @chengzhang1016  Please help give a review. Thank you!
> modify the wait time for secret

- features/upgrade/tsb/upgrade.feature
As title, the correct template name should be `tsb-cr-template.yaml`, see:
https://github.com/openshift-qe/v3-testfiles/blob/master/olm/tsb-cr-template.yaml
> fix the template reference

- lib/rules/cli/4.4.yaml
@kasturinarra Could you please help review ? thanks.
> add lib for inspect command

- features/support/clusterlogging_env.rb
- testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
- testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
- testdata/logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml
- testdata/logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
- testdata/logging/loggen/container_json_log_template.json
- testdata/logging/loggen/container_json_unicode_log_template.json
use image digest instead of tag
@anpingli PTAL, thanks
> use image digest

- lib/rules/web/admin_console/4.1/catalog.xyaml
- lib/rules/web/admin_console/4.2/catalog.xyaml
- lib/rules/web/admin_console/4.3/catalog.xyaml
- lib/rules/web/admin_console/4.4/catalog.xyaml
4.4 pass log Runner-v3#80841
4.3 pass log  Runner-v3#80833
4.2 pass log  Runner-v3#80834
4.1 pass log  Runner-v3#80836
@yanpzhan  Please help review the fix, thanks
> fix clear issue for OCP-21250

- features/cli/build.feature
- testdata/deployment/skopeo-deployment.json
- testdata/templates/tc539699/build.yaml
@openshift/devexp-qe please help review it, thanks
> fix OCP-11023

- testdata/networking/aosqe-pod-for-ping.json
- testdata/networking/hostnetwork-pod.json
- testdata/networking/list_for_pods.json
- testdata/networking/multus-cni/Pods/1interface-host-device.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
- testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
- testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
- testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
- testdata/networking/net_admin_cap_pod.yaml
- testdata/networking/nodeport_pod.json
- testdata/networking/pod-for-ping.json
- testdata/networking/pod_with_udp_port_4789.json
- testdata/networking/pod_with_udp_port_4789_nodename.json
@huiran0826 @anuragthehatter @weliang1 @rbbratta 
since for disconnect cluster need to use 'digest' for image
> update image tag to digest

- features/upgrade/security_compliance/fips.feature
@pdhamdhe @liangxia Please help to review, Thanks.
> add prepare tag for OCP-25821

- lib/rules/web/admin_console/4.1/filters.xyaml
- lib/rules/web/admin_console/4.1/search.xyaml
- lib/rules/web/admin_console/4.2/filters.xyaml
- lib/rules/web/admin_console/4.2/search.xyaml
- lib/rules/web/admin_console/4.3/filters.xyaml
- lib/rules/web/admin_console/4.3/search.xyaml
- lib/rules/web/admin_console/4.4/filters.xyaml
- lib/rules/web/admin_console/4.4/search.xyaml
- lib/rules/web/admin_console/4.5/filters.xyaml
- lib/rules/web/admin_console/4.5/search.xyaml
- lib/webauto/web4cucumber.rb
@yanpzhan  @SSshahan  Please help review thanks
> rules added for fixing OCP-19532

- features/step_definitions/web.rb
- lib/openshift/cluster_version.rb
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.5/check_links.xyaml
@pruan-rht  @yapei This is for checking a new page on new window which is opened by Click action.
Also I add a url value in `@result[:url]` for [this test case.](https://github.com/openshift/cucushift/pull/7508)
Please help review, thanks!
> Add rules for OCP-25761

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/deployment.xyaml
- lib/rules/web/admin_console/4.1/goto.xyaml
- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/deployment.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/deployment.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/deployment.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/deployment.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- testdata/hpa/hpa_rubyex.yaml
@yapei please help to review, thanks
> Automated OCP-19695

- features/build/stibuild.feature
Here is test result: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/81518/console
> automate OCP-22596

- lib/rules/web/admin_console/4.3/projects.xyaml
- lib/rules/web/admin_console/4.4/projects.xyaml
- lib/rules/web/admin_console/4.5/projects.xyaml
@SSshahan  please help review,thanks
> fix OCP-26910

- features/registry/registry.feature
@openshift/devexp-qe please check it, thanks
> Fix OCP-23030

- features/step_definitions/helper_services.rb
> Fix step "CA trust is added to the pod-for-ping"

- testdata/customscheduler/my-scheduler.yaml
- testdata/customscheduler/pod-customscheduler.yaml
- testdata/customscheduler/pod-defaultscheduler.yaml
- testdata/customscheduler/pod-noscheduler.yaml
Add files required to test custom scheduler
> Add files required for custom scheduler

- testdata/networking/multus-cni/Pods/1interface-host-device.yaml
> update the image digest

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/check_links.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
@yapei could you help to review? Thanks
> fix OCP-24106 OCP-25761

- lib/rules/web/admin_console/4.4/catalog.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/catalog.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
@yapei please help to review. Thanks.
> Automated OCP-27666

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@liangxia Could you please help review and merge, thanks.
> update inspect rules

- lib/openshift/cron_job.rb
@liangxia could you please help take a look? Thanks.
> update cronjob method

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@kasturinarra  Please help review ? thanks.
> add must-gather command

- features/routing/abrouting.feature
- features/routing/haproxy-router.feature
fix relative path for OCP-11970 etc. 
@liangxia
> fix relative path for OCP-11970 etc

- features/networking/multus.feature
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/whereabouts-macvlan.yaml
Auto cases OCP-28633 - [SDN-556] Dynamic IP address assignment with Whereabouts	
Automation logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/859/consoleFull
> Auto case OCP-28633

- features/routing/abrouting.feature
- features/routing/haproxy-router.feature
follow up https://github.com/openshift/verification-tests/pull/946
Sorry I forgot to verify them locally and one extra `"` was introduced by mistake.
@liangxia
> follow up 946: remove extra double quotes

- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
@yapei Fix for OCP-25817.
PASS locally, please review, thanks.
> Add a rule to check sidebar loaded for OCP-25817

- lib/openshift/machine_set.rb
> machines method for MachineSet

- features/upgrade/machines/machines.feature
We had updated this already, we forget an upgrade test, this pr addresses that.
@sunzhaohua2 @miyadav PTAL
> Use a cloned machineset to test

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
Add checkpoint for case OCP-22308
> fix script for OCP-22308

- features/upgrade/etcd/upgrade.feature
/cc @geliu2016 @kasturinarra @pruan-rht
> Fix an upgrade scenario

- features/step_definitions/machine_set.rb
This improves the fails on OSP and on 4.3 version. @miyadav @sunzhaohua2 PTAL
> Make test stable on osp

- features/admin/quota.feature
- features/build/genericbuild.feature
- features/cli/build.feature
- features/cli/deployment.feature
- features/cli/job.feature
- features/cli/policy.feature
- features/cli/secrets.feature
- features/images/jenkins.feature
- features/networking/egress-ingress.feature
- features/online/route.feature
- features/routing/http2.feature
- features/routing/idle.feature
- features/step_definitions/cluster_configuration/csi.rb
- features/step_definitions/cluster_configuration/localstorage.rb
- features/step_definitions/file.rb
- features/step_definitions/helper_services.rb
- features/test/scc.feature
- features/web/create.feature
- features/web/hooks.feature
@barleyer @xingxingxia @liangxia @pruan-rht
> special step to obtain test data files

- features/networking/multus.feature
- testdata/networking/multus-cni/NetworkAttachmentDefinitions/route-override.yaml
Test log:  https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/914/console
> Auto work for OCP-28518

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei Plz review, thanks!
Will add rules on 4.4 as well if you look good.
> Add rules for OCP-27590

- lib/rules/web/admin_console/4.4/projects.xyaml
Always failed by [page changing during running](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/85363/console)
[Now it PASS](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/85374/console)
@yapei Plz review, thanks!
> Fix OCP-21772 for unstable issues

- features/step_definitions/deployment.rb
> Add step for OCP-29435

- testdata/storage/vsphere/storageclass.yml
Update to fix OCP-13386/13387/13388
1. Remove default sc to avoid impacting other cases.
2. Remove datastore, case failed for vsphere6.7 env.
[Pass log ](https://privatebin-it-iso.int.open.paas.redhat.com/?7018c3bad86bd8ce#D+mHtoGjIoiUCG+2KIfi0xLblnxfkMLjuZjz4pNeIgI=)
> Update: Fix OCP-13386/13387/13388

- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei pls help to review, thanks!
> add rules for OCP-27835

- features/storage/regression.feature
- testdata/storage/misc/damonset.json
From OCP4.4, the ds version is apps/v1
> Bug fix for OCP-16485

- features/svc-catalog_asb/asb.feature
moving test cases OCP-15328,OCP-16086,OCP-16087 from internal cucushift (https://github.com/openshift/cucushift/pull/7581) to verification-test for stage pipeline automation. 
@anpingli @emmajiafan @jianzhangbjz @chengzhang1016 Please have a review, thanks!
> moving asb stage cases from cucushift to verification-test

- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yanpzhan  @xiaocwan  Can you help review?
> rules added for OCP-29198

- features/storage/iscsi.feature
- testdata/storage/iscsi/pod-security.json
- testdata/storage/iscsi/pv-rwo.json
[Pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?5ecde0c006a94217#AkTLy/dReQgMRaB1HX+JhngvhP/bedkZlsvrczZO8T4=)
> Update: Change test file path for OCP-9638

- tools/jenkins/slaves/Dockerfile.centos
- tools/jenkins/slaves/Dockerfile.rhel7
To support OCPQE-129
/cc @akostadinov @pruan-rht @xltian @jhou1
> Add pip and minio to interact with S3 bucket

- features/upgrade/routing/upgrade.feature
Tested locally and passed.
@geliu2016 Could you please take a look?
> auto OCP-29747 and 29747

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/style.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/style.xyaml
> Add web rules for OCP-24307

- features/storage/quota.feature
Updated for using common test file, and also helpful for disconnect env.
[Pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?a8affdc97dca5955#phxnBFguMGZnvL8PiWg2SNN5pJgbAZchQWYJT/aDO6A=)
> Update: Fix OCP-14173

- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei please help to review thanks
> rules for OCP-28954

- lib/rules/web/admin_console/4.2/environments.xyaml
- lib/rules/web/admin_console/4.2/goto.xyaml
- lib/rules/web/admin_console/4.3/environments.xyaml
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/environments.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/environments.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
@xiaocwan  Can you help review? Thanks
> add rules for OCP-21245

- features/routing/ingress-route.feature
- testdata/routing/ingress/test-ingress.json
The test case gets executed properly with this change applied. The successful v3 runner task link is as below:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/87646/console
@lihongan - Request for a peer review.
> update ingress source OCP-18789

- testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
- testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
- testdata/logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml
- testdata/logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
- testdata/logging/loggen/container_json_log_template.json
- testdata/logging/loggen/container_json_unicode_log_template.json
Change the image registry to `quay.io/openshifttest`
> use images from quay.io

- testdata/deployment/skopeo-deployment.json
- testdata/image/gitserver/gitserver-ephemeral.yaml
- testdata/templates/tc539699/build.yaml
> Update image to pull from quay.io/openshifttest

- testdata/olm/catalogsource-template.yaml
@liangxia  Added a test file based on your suggestion
> add test files for OCP-29198

- testdata/routing/abrouting/caddy-docker-2.json
- testdata/routing/abrouting/caddy-docker.json
- testdata/routing/caddy-docker-2.json
- testdata/routing/caddy-docker.json
- testdata/routing/header-test/dc.json
- testdata/routing/list_for_caddy.json
- testdata/routing/routetimeout/httpbin-pod-2.json
- testdata/routing/routetimeout/httpbin-pod.json
- testdata/routing/websocket/pod.json
- testdata/routing/wildcard_route/caddy-docker.json
@xiuwang @quarterpin Please take a look. Thanks.
> update routing images to use quay

- features/cli/oc_portforward.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/87447/console
resole the failed with proxy env. 
@kasturinarra Please help review , thanks.
> update for proxy failure

- testdata/networking/aosqe-pod-for-ping.json
- testdata/networking/hostnetwork-pod.json
- testdata/networking/list_for_pods.json
- testdata/networking/multus-cni/Pods/1interface-host-device.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-bridge.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-private.yaml
- testdata/networking/multus-cni/Pods/1interface-macvlan-vepa.yaml
- testdata/networking/multus-cni/Pods/2interface-hostdevice-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-hostdevice.yaml
- testdata/networking/multus-cni/Pods/2interface-macvlan-macvlan.yaml
- testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml
- testdata/networking/multus-cni/Pods/generic_multus_pod.yaml
- testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml
- testdata/networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
- testdata/networking/net_admin_cap_pod.yaml
- testdata/networking/nodeport_pod.json
- testdata/networking/pod-for-ping.json
- testdata/networking/pod_with_udp_port_4789.json
- testdata/networking/pod_with_udp_port_4789_nodename.json
Change the image registry for sdn  to quay.io/openshifttest
@zhaozhanqi  @xiuwang @pruan-rht
> Update image registry to quay.io for sdn

- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.4/style.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/style.xyaml
> Auto OCP-24305

- features/upgrade/storage/upgrade.feature
- testdata/storage/misc/deployment.yaml
@piqin 
I created a new pr with the update for your comments:
1. Add "storage" operator version matchs the current cluster version
2. Add check storage class name from the "storage" operator
[Pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?0560959c181fe174#IvJRvYs7A8TaRRo0O2GCIpZXUrsezb8vTKsm3lmWZJ0=)
> Add: automate upgrade case OCP-23501

- features/cli/oc_registry.feature
- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
Here is test result: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/81811/console
> Automated OCP-21926

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@kasturinarra Please help review , thanks.
> add lib for oc extension plugin

- lib/rules/web/admin_console/4.5/masthead.xyaml
> fix OCP-27654

- features/upgrade/sdn/policy-upgrade.feature
Add one sdn upgrade case.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1012/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1011/console
@geliu2016 @zhaozhanqi @liangxia  Could you help review? Thanks!
> Auto upgrade OCP-22707

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@liangxia Could you please help review and merge , thanks.
> add image option for debug command

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@qinpingli @liangxia  Could you please help review ? thanks.
> add permanent image as default value

- features/logging/cluster_logging_operator.feature
- features/logging/elasticsearch_operator.feature
- features/logging/eventrouter.feature
- features/step_definitions/logging.rb
The post action to sync images has been changed, when execute automation testing, always hit issue `ImagePullBackOff`, so I changed the image when deploying eventrouter. @anpingli  PTAL.
> fix eventrouter issue: ImagePullBackOff

- lib/rules/web/admin_console/4.4/style.xyaml
- lib/rules/web/admin_console/4.5/style.xyaml
@yapei or @xiaocwan pls help to review.
> add rules for OCP-26887

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@xingxingxia @wangke19 please review, Thanks
> Added oc adm release info

- config/config.yaml
- lib/environment.rb
We have to specify version info when trigger automation. We would like to get the version info automatically (from ClusterVersion).
> Get version info from ClusterVersion

- lib/rules/web/admin_console/4.2/filters.xyaml
- lib/rules/web/admin_console/4.3/filters.xyaml
- lib/rules/web/admin_console/4.4/filters.xyaml
- lib/rules/web/admin_console/4.5/filters.xyaml
Fix rule for OCP-24306, pls help to review @yapei or @xiaocwan , thanks!
> fix for OCP-24306

- features/cli/job.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/87453/console
@kasturinarra  Please help review , thanks
> update for more stable

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
@xiaojiey Could you please help to review _oc adm release info_ command options ? Thanks
> Added options for oc adm release info

- lib/rules/web/admin_console/4.1/actions.xyaml
- lib/rules/web/admin_console/4.2/actions.xyaml
- lib/rules/web/admin_console/4.3/actions.xyaml
- lib/rules/web/admin_console/4.4/actions.xyaml
- lib/rules/web/admin_console/4.5/actions.xyaml
- lib/rules/web/admin_console/4.5/builds.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
- lib/rules/web/admin_console/4.5/deployment.xyaml
- lib/rules/web/admin_console/4.5/overview.xyaml
- lib/rules/web/admin_console/4.5/route.xyaml
@yapei  please help to review, thanks!
fix OCP-21270,OCP-25795,OCP-20932,OCP-19558,OCP-26170,OCP-27584
Fixed below failed cases in automation run: 
```cucumber -p polarshift features/tierN/web/admin-console/overview.feature:201 # Scenario: Check stateful set on overview page
cucumber -p polarshift features/tierN/web/admin-console/overview.feature:386 # Scenario: Group resources
cucumber -p polarshift features/tierN/web/admin-console/deployments.feature:184 # Scenario: Check basic process of create/delete DC from image
cucumber -p polarshift features/tierN/web/admin-console/build.feature:99 # Scenario: Check deprecation note of pipeline build strategy
cucumber -p polarshift features/tierN/web/admin-console/overview.feature:5 # Scenario: Check app resources on overview page
cucumber -p …
```
> Fix ui cases

- features/networking/ptp_operator.feature
Auto OCP-25940 for stage testing.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1075/console
@zhaozhanqi @liangxia
> Auto OCP-25940

- lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
- lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
Make monitoring UI cases work on old releases 41,42,43
depend on PR:
https://github.com/openshift/cucushift/pull/7690
v3 run on 41
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89511/console
V3 run on 42
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89512/console
v3 run on 43
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89515/console
v3 run on 44
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89516/console
> Hongyali make ui case work 41 42 43

- features/upgrade/samples_operator/upgrade.feature
> image-registry/samples/openshift-controller-manager operator upgrade

- features/step_definitions/images/jenkins.rb
- features/upgrade/jenkins/upgrade.feature
- lib/rules/web/images/jenkins_2/jenkins_2.xyaml
> Auto jenkins upgrade case

- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei  could you help to review?  Thanks
> Auto OCP-29477

- features/step_definitions/helper_services.rb
- testdata/storage/iscsi/iscsi-target.json
- testdata/storage/nfs/nfs-server.yaml
Did some test for iscsi/nfs pass.
> Update: Modify iscsi/nfs image url for disconnect env

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/90216/console
@kasturinarra Please help review. thanks.
> add create deploymentconfig lib

- lib/rules/web/admin_console/4.1/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
- lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
Depend on PR:
https://github.com/openshift/cucushift/pull/7701
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/90206/console
> Fix failure test OCP-28106 in polar run_20200508-0647

- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
- lib/rules/web/admin_console/base/logout.xyaml
Fix for cases: OCP-26029  OCP-22330 
@yapei or @xiaocwan , pls help to review, thanks!
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89564/
https://paste.centos.org/view/8c04708f
> fix for web cases

- lib/openshift/project.rb
@kasturinarra @liangxia Could you please help review , thanks . 
I've tested on my localhost and pass.
> replace -v with  --suggest for oc status

- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/logging/eventrouter.feature
- features/step_definitions/logging.rb
- features/step_definitions/logging_metrics.rb
- lib/openshift/service.rb
Update the scenarios to match the logging 4.5 changes, @anpingli PTAL
> fixes for logging 4.5

- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
Add lib for oc create cronjob & oc create job
> Add oc_createcronjob&createjob functionality

- features/upgrade/api_auth/upgrade.feature
Not tested yet. Pushed just for @rhpmali to reference for his upgrade case auto that is similar. After tested, will request review from @wangke19 @rhpmali
> OCP-22673 upgrade auto

- features/cli/oc_patch_apply.feature
change run to create_deploymentconfig command.
> Fix auto case OCP_10696

- features/upgrade/api_auth/upgrade.feature
> Fix format for api auth upgrade

- features/upgrade/etcd/upgrade.feature
@liangxia Just fix a update for this autoscript, pls help to reivew it. thanks
> fix_err_OCP-22606

- features/cli/deploy.feature
@kasturinarra Could you please help review ? thanks
> update for ocp-9563

- features/step_definitions/node.rb
- features/upgrade/routing/upgrade.feature
logs:
upgrade-prepare: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91346/consoleFull
upgrade-check: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91357/consoleFull
@geliu2016 @quarterpin Please help take a look, thanks.
> auto OCP-30501

- features/networking/multicast.feature
Auto test OCP-12930
@anuragthehatter @rbbratta @zhaozhanqi @huiran0826
Test log:
https://privatebin-it-iso.int.open.paas.redhat.com/?054484217cd21488#l7m4xqz5l6bHY7M0TQ3+nYv8EpMZJ05zH+O1KnOqCqM=
> Auto test OCP-12930

- features/cli/build.feature
--image has been removed since 4.5 @openshift/devexp-qe please help review, thx
> Replace --image option

- lib/openshift/imagepruners_imageregistry_operator_openshift_io.rb
@openshift/devexp-qe Please help to review.
> Add image pruners

- features/upgrade/sdn/policy-upgrade.feature
Add one SDN upgrade test cases
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/69321/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/69322/console
@geliu2016 @akostadinov @pruan-rht  could you help review, thanks.
> add networkpolicy upgrade case

- features/upgrade/build/build-upgrade.feature
@openshift/devexp-qe  pls review it, thanks
> Fix OCP-13025

- features/upgrade/api_auth/upgrade.feature
Not test yet, only pushed it first. Preparing the test environment for auto test. Will let @xingxingxia  @rhpmali  review later.
> Auto OCP-19470

- features/step_definitions/operators.rb
Address this issue: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/05/13/20:45:16/upgrade_Marketplace/console.html
details: https://coreos.slack.com/archives/CPJQCSN49/p1589428260244800
> change the getting version way

- features/upgrade/build/build-upgrade.feature
@pruan-rht  @liangxia  Could you help to merge, thanks
[upgrade-prepare job](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91896/)
[upgrade-check job](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91922/)
> Using ruby:2.5 instead of latest tag

- features/networking/pod.feature
- features/step_definitions/networking.rb
http://pastebin.test.redhat.com/850360
@rbbratta @weliang1 @zhaozhanqi @huiran0826
> OCP-26373 and OVN funtionality check def

- features/logging/collector.feature
- features/step_definitions/logging.rb
> add step to check logs

- features/step_definitions/logging_metrics.rb
Fix issue when curl es endpoint with token. @pruan-rht Could you please help to merge it?
> fix issue when curl with token

- lib/openshift/stateful_set.rb
@openshift/devexp-qe please review it, thanks
> Add generation function for statefulset

- features/upgrade/monitoring/monitoring-upgrade.feature
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
Automated 2 test cases
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-29061
https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-29300
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21148
Dependent on PR:
https://github.com/openshift/cucushift/pull/7735
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/92058/console
> automated 3 UI tests and fix upgrade typo

- features/upgrade/machines/machines.feature
/cc @jhou1 @pruan-rht @akostadinov
> Fix upgrade prepare for OCP-27664/22712

- features/node/node.feature
Image is mirrored to quay, now updating automation to remove reference in docker.io.
@sunilcio @weinliu @lyman9966 PTAL.
> Use quay.io

- features/cli/policy.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91415/console
@xingxingxia  pls take a look,thanks!
> Wait some time to make steps pass through.

- features/cli/policy.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/92737/console
Since there was a change about the `download step`,add a step to make a copy of the defination file for modification.
@xingxingxia please take a look.
> A small fix about the download step change

- features/upgrade/monitoring/monitoring-upgrade.feature
https://issues.redhat.com/browse/OCPQE-476
Check points  | "alertname": "Watchdog" | keep changing, so change code to check  | Watchdog |
> fix monitoring upgrade issue OCPQE-476

- lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.2/projects.xyaml
- lib/rules/web/admin_console/4.2/user_management.xyaml
- lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.3/projects.xyaml
- lib/rules/web/admin_console/4.3/user_management.xyaml
- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/user_management.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
- lib/rules/web/admin_console/4.5/user_management.xyaml
> Add rules for OCP-24281

- features/upgrade/node/node-upgrade.feature
- testdata/customresource/custom_kubelet.yaml
@jhou1 @sunilcio @weinliu Can you help to take a look ? Thanks
logs is here: 
http://pastebin.test.redhat.com/865326
> add upgrade case OCP-13022

- features/upgrade/node/hpa/upgrade.feature
Running log: http://pastebin.test.redhat.com/865458
@jhou1 @sunilcio @lyman9966 could you help with the review? Thanks.
cc @geliu2016
> Automate OCP-13016 (node hpa upgrade test)

- lib/rules/web/admin_console/4.2/style.xyaml
- lib/rules/web/admin_console/4.3/style.xyaml
- lib/rules/web/admin_console/4.4/style.xyaml
- lib/rules/web/admin_console/4.5/style.xyaml
Add rules for OCP-24223.
@yapei or @xiaocwan pls help to review, thanks!
> add rules for OCP-24223

- features/upgrade/workloads/oc-upgrade.feature
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91956/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/91863/console
@kasturinarra Could you please help review , thanks .
> add noproxy

- features/networking/OWNERS
change the default owner of sdn team 
@liangxia @pruan-rht
> change the review Owner

- features/upgrade/monitoring/monitoring-upgrade.feature
Fix issue by checking an API which is applicable to many releases.
https://issues.redhat.com/browse/OCPQE-522
Have tested on both 4.5 and 4.4
> fix upgrade issue to check common api to many versions

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/dashboards.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/dashboards.xyaml
@yanpzhan  Please help review thanks
> rules added for OCP-27586

- features/web/OWNERS
- features/web/service-catalog/OWNERS
```
[lxia@ocp verification-tests]$ git branch
* master
owner
v3
[lxia@ocp verification-tests]$ ls -lR features/web/
features/web/:
total 8
-rw-rw-r--. 1 lxia lxia   64 May 21 14:08 OWNERS
drwxrwxr-x. 2 lxia lxia 4096 May 21 14:08 service-catalog
features/web/service-catalog:
total 4
-rw-rw-r--. 1 lxia lxia 62 May 21 14:08 OWNERS
```
/cc @pruan-rht @akostadinov
> Clean-up OWNERS from empty folders

- features/routing/operator.feature
- testdata/routing/operator/ingressctl-nsowner.yaml
log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/93625/console
@quarterpin PTAL, thanks
> auto OCP-27594

- features/cli/deploy.feature
@kasturinarra  Please help review , thanks.
> replease new-app with create dc

- lib/rules/web/admin_console/4.1/check_links.xyaml
- lib/rules/web/admin_console/4.2/check_links.xyaml
- lib/rules/web/admin_console/4.3/check_links.xyaml
- lib/rules/web/admin_console/4.4/check_links.xyaml
- lib/rules/web/admin_console/4.5/check_links.xyaml
> Auto OCP-29200

- testdata/configmap/pod-configmap-command.yaml
- testdata/configmap/pod-configmap-env.yaml
- testdata/configmap/pod-configmap-volume1.yaml
- testdata/configmap/pod-configmap-volume2.yaml
- testdata/hpa/rc-hello-openshift.yaml
- testdata/job/job-secret-env.yaml
- testdata/pods/graceful-delete/0.json
- testdata/pods/graceful-delete/default.json
- testdata/pods/pod-with-nodeselector.yaml
- testdata/pods/selector-east.json
- testdata/pods/tc533910/readiness-probe-exec.yaml
- testdata/quota/pod-notbesteffort.yaml
- testdata/rc/idle-rc-1.yaml
- testdata/rc/idle-rc-2.yaml
- testdata/secrets/secret-env-pod.yaml
@jhou1 @sunilcio @weinliu  please have a look, thanks
> update image to pull from quay.io

- lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
@yapei please help to review, thanks
> rules for OCP-27631

- features/images/jenkins.feature
- lib/rules/web/images/jenkins_2/jenkins_2.xyaml
@openshift/devexp-qe  Resolve `Log in` button issue, below 4.4, the text is `Log I n` , in 4.4 and 4.5, the text is `Log in` 
Passed locally http://pastebin.test.redhat.com/868459
> Fix jenkins login issue

- features/machine/machine.feature
…https://bugzilla.redhat.com/show_bug.cgi?id=1831717
*Removing the step of copying yaml to modify
V3 runner - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/93069/console
> Updated test case  - OCP27609

- features/cli/job.feature
- lib/rules/cli/4.1.yaml
- lib/rules/cli/4.4.yaml
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1290/console
@kasturinarra  Please help review , thanks
> update cronjob lib and ocp-17515

- features/build/env.feature
- features/cli/create.feature
- features/cli/oc_set_probe.feature
- features/images/rhel8_images.feature
- features/upgrade/build/build-upgrade.feature
Now new-app create deployment not dc in latest 4.5 oc client, so updated scripts
related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1836833
> Fix new-app cases

- testdata/secrets/tc483168/first-secret-pod.yaml
- testdata/secrets/tc483168/second-secret-pod.yaml
I haven't finished going through all my scripts, since some external team is using this repo to test Openshift on power.
@jhou1 @sunilcio @lyman9966 PTAL
> Replace to use quay images

- lib/openshift/cluster_service_version.rb
- lib/openshift/custom_resource_definition.rb
- lib/rules/web/admin_console/4.3/goto.xyaml
- lib/rules/web/admin_console/4.4/builds.xyaml
- lib/rules/web/admin_console/4.4/goto.xyaml
- lib/rules/web/admin_console/4.5/builds.xyaml
- lib/rules/web/admin_console/4.5/goto.xyaml
> add rules for OCP-25803

- features/step_definitions/helper_services.rb
ocp4.5: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1438/console
ocp4.4: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1440/console
@kasturinarra Please help review , thanks .
> update for proxy config

- lib/rules/cli/4.5.yaml
Update generator option for oc run in 4.5
> fix oc run --generator rule

- features/step_definitions/machine.rb
Even though we did our best effort to wait for machine to be deleted, occasionally a machine would escape the wait logic because its deletionTimestamp isn't added timely.
Previously: When a machine has a deletionTimestamp, wait for the machine to be removed in tear down. Works most of the time, problematic when deletionTimestamp isn't added timely before we invoke `machine.deleting?` method.
Changes: Compare the list of original machine names with list of current machine names, the `current - original` is the list of machines to be deleted. Admin ensures every of them is deleted. 
With this change test tear down could properly clean up every machine provisioned.
> Ensure every provisioned machine is deleted in test tear down

- features/upgrade/node/hpa/upgrade.feature
@jhou1 @sunilcio @lyman9966 
Could you help take a look? 
Running log after fix http://pastebin.test.redhat.com/870367
> fix_OCP-12194 project issues

- features/step_definitions/helper_services.rb
@openshift/devexp-qe PTAL, thanks
[pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/runner-v3/98214/console)
> Fix proxy step for OCP-14476

- lib/openshift/cluster_logging.rb
- lib/openshift/collector.rb
- lib/openshift/elasticsearch.rb
- lib/openshift/kibana.rb
Add and update lib files for logging CRDs. @pruan-rht PTAL, thanks.
> add and update logging crd lib files

- features/logging/permission.feature
- features/step_definitions/logging_metrics.rb
Runner-v3 log: https://url.corp.redhat.com/f12bb3d
> add permission cases for ES6

- lib/rules/web/admin_console/4.4/operator_hub.xyaml
- lib/rules/web/admin_console/4.5/operator_hub.xyaml
> rules for OCP-27646

- lib/rules/cli/4.5.yaml
> Fix cronjob lib for 4.5
