- features/step_definitions/config_map.rb
@jechen0648 this should work for you.
> get the leader node from config_map

- features/build/dockerbuild.feature
- features/upgrade/sdn/multicast-upgrade.feature
- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/sctp-upgrade.feature
[OCPQE-5687](https://issues.redhat.com/browse/OCPQE-5687) add azure-upi tags for prow job
/cc @jhou1 @pruan-rht @liangxia @JianLi-RH
> OCPQE-5687 add azure-upi tags for prow job

- features/networking/ovn-egress-ip.feature
Auto OCP-42925
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3687/console
> auto OCP-42925

- features/upgrade/api_auth/upgrade.feature
- features/upgrade/cloudcredential/upgrade.feature
- features/upgrade/logging/upgrade.feature
- features/upgrade/logging/upgrade_with_clf.feature
- features/upgrade/machines/machines.feature
- features/upgrade/routing/upgrade.feature
- features/upgrade/samples_operator/upgrade.feature
- features/upgrade/sdn/egress-upgrade.feature
- features/upgrade/storage/upgrade.feature
- features/upgrade/svcat/upgrade.feature
- features/upgrade/tsb/upgrade.feature
> Correct test tags for upgrading test

- lib/rules/web/ocm_console/install_page.xyaml
Fix OCP-21338,OCP-38889,OCP-38887,OCP-38888,OCP-25175,OCP-35840,OCP-26297,OCP-30121.
@yasun1 @xueli181114 @yuwang-RH Please help review, thanks
Here is Jenkins run result: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/206360/console
Related PR: https://github.com/openshift/cucushift/pull/8849
> Fix automation error on several ocm cases

- features/upgrade/sdn/ipsec-upgrade.feature
I have included pod-pod and node-node scenarios post upgrade on IPsec clusters
Logs:
Pre-upgrade: https://privatebin-it-iso.int.open.paas.redhat.com/?ec4e39cdfbe70d23#GupsjEU85gmn2mL2PateRTaXaKb8M1rpkWXMUiAF9pAA
Post-upgrade: https://privatebin-it-iso.int.open.paas.redhat.com/?c6f0a2b5331af27b#8pqbd7UheH96A1kTNqBGDcfFBVoeUUJteoEzi7i95jvi
> IPsec upgrade scenarios to improve networking quality

- features/routing/route.feature
@lihongan, @quarterpin, request for a peer review
CC: @melvinjoseph86
thanks
> OCPQE-6448: OCP-12564 improve and optimize the automation scripts

- lib/launchers/amz.rb
- lib/polarshift/test_record.rb
- lib/test_case_manager.rb
- tools/datahub_cli.rb
2nd try for https://github.com/openshift/verification-tests/pull/2408. I've added more debug statements (prints out the status of the upload).  With my testing, I've not seen any missing logs yet.  @jhou1 @liangxia @JianLi-RH @dis016, PTAL.  Pls merge if there are no objections .. I'll monitor the status.
20211101-1909
20211103-1815
20211103-0619
20211102-1944
To test this, I've added an option the the `ci-monitor-helper` a script o check if a testrun's logs are downloadable.
> Upload logs to upshift s3 bucket

- features/networking/sctp.feature
- features/upgrade/sdn/sctp-upgrade.feature
OCP-29645: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/213354/console
OCP-28757, OCP-28758, OCP-28759: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/213356/console
cc @pruan-rht @weiliang1
> OCPQE-6726: fixes netcat path

- features/networking/egress-ingress.feature
@asood-rh  @zhaozhanqi   Please review the PR,  here is the running log:  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3692/console
> add OCP-44940 to egress-ingress.feature

- features/networking/ovn-egress-ip.feature
Fix failures in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/23373/rehearse-23373-periodic-ci-openshift-verification-tests-master-ocp-4.10-e2e-aws-cucushift-ipi-destructive/1457624130198179840
/cc @JianLi-RH @dis016 @pruan-rht @jhou1
> Fix failures in Prow

- features/logging/elasticsearch.feature
- features/logging/kibana.feature
- features/step_definitions/logging_metrics.rb
- features/upgrade/logging/upgrade.feature
/cc @QiaolingTang @anpingli @jhou1 @JianLi-RH
Console test cases need to be deal with specially in Prow currently.
/hold
until we merge https://github.com/openshift/cucushift/pull/8870
> Add tag console to web console tests

- tools/polarshift.rb
As a follow up of https://github.com/openshift/verification-tests/pull/2448
/cc @pruan-rht @zhaozhanqi @jhou1
> Reorganize clone-run

- features/upgrade/security_compliance/fips.feature
Fix one failure in https://testgrid.k8s.io/redhat-openshift-ocp-release-4.10-informing#periodic-ci-openshift-verification-tests-master-ocp-4.10-e2e-aws-cucushift-ipi
/cc @JianLi-RH @dis016 @pruan-rht @jhou1
> Add tag fips

- features/kata/install_uninstall.feature
- features/kata/pod.feature
- features/kata/smoke_tests.feature
We need to add @flaky to the tests, in order to exclude them for now from CI runs
> Adding flaky tag to tests

- lib/rules/web/admin_console/4.10/check_links.xyaml
- lib/rules/web/admin_console/4.10/clustersettings.xyaml
- lib/rules/web/admin_console/4.10/status.xyaml
- lib/rules/web/admin_console/4.6/clustersettings.xyaml
- lib/rules/web/admin_console/4.7/clustersettings.xyaml
- lib/rules/web/admin_console/4.8/clustersettings.xyaml
- lib/rules/web/admin_console/4.9/clustersettings.xyaml
> updates 410 rules

- features/upgrade/jenkins/upgrade.feature
- features/upgrade/sdn/externalIP-upgrade.feature
- features/upgrade/sdn/multus-upgrade.feature
@liangxia @pruan-rht @JianLi-RH @dis016 PTAL. This fixes two upgrade-check failures.
> Sync the upgrade-prepare and upgrade-check versions

- lib/openshift/secret.rb
For comment https://github.com/openshift/verification-tests/pull/2478#discussion_r749829851
> Disable overwrite of secrets's quiet option

- features/step_definitions/common.rb
> Do not show the expression info when contains secret

- tools/openshift-ci/Dockerfile
/cc @jhou1 @yapei 
Steps are copied from https://github.com/openshift/verification-tests/blob/master/tools/jenkins/slaves/Dockerfile.rhel7
> Add Chrome and its driver to support web tests in Prow

- features/step_definitions/common.rb
Add a step for saving CR to a file directly without outputing
@liangxia @jhou1 please help review this one and https://github.com/openshift/cucushift/pull/8886
> Add a step for saving CR directly

- features/machine/machine.feature
- features/upgrade/machines/machines.feature
This PR modified tags of OCP-43331 and OCP-37706 to be consistent with polarion.
@sunzhaohua2 @miyadav @jhou1 PTAL, thanks!
> update OCP-43331,OCP-37706 tags

- features/step_definitions/web.rb
- lib/rules/web/admin_console/4.10/customizations.xyaml
- lib/rules/web/admin_console/4.10/goto.xyaml
- lib/rules/web/admin_console/4.9/customizations.xyaml
- lib/rules/web/admin_console/4.9/goto.xyaml
> add support for plugin cases

- features/step_definitions/web.rb
> Fixes openshift/verification-tests#2415

- features/upgrade/workloads/descheduler-upgrade.feature
Fix the issue discussed in https://coreos.slack.com/archives/CPJQCSN49/p1637238263371100
> Fix could not find all scenarios: OCP-40536

- lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
Jenkins log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/216344/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/216360/console
Please help review. @yasun1 @xueli181114 @yuwang-RH
Related PR: https://github.com/openshift/cucushift/pull/8869
> Auto case OCP-45544 OCP-45545

- features/upgrade/machines/machines.feature
```
[lxia@lxiabox upgrade]$ grep -r 'Scenario' machines/machines.feature 
Scenario Outline: Cluster operator should be available after upgrade - prepare
Scenario Outline: Cluster operator should be available after upgrade
Scenario: Cluster operator should be available after upgrade - prepare
Scenario Outline: Cluster operator should be available after upgrade
```
> Simplify the machines upgrade codes

- doc/tags.adoc
Documenting the current in-used tags. @liangxia PTAL
> Adding docs for supported tags

- features/networking/egress-ip.feature
Auto OCP-46244 which is from customer bug.
Test Log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3733/console
/cc   @openshift/team-sdn-qe
> Auto OCP-46244

- features/step_definitions/node.rb
@liangxia ^^ Could you help review this?
> exclude the windows worker

- features/step_definitions/secrets.rb
- lib/openshift/secret.rb
> OCPQE-7067: Fix security issue in step "admin obtains the cloudcredentials from cluster"

- OWNERS
/cc @jianlinliu @gpei @jhou1 
The `OWNERS` file in openshift/release are synced from the `OWNERS` file we used here.
> Add gpei/jianlinliu as approver to support tests in Prow

- lib/log.rb
Fix issue in https://coreos.slack.com/archives/CH76YSYSC/p1637906272082100?thread_ts=1637724031.447100&cid=CH76YSYSC
/cc @jhou1 @dis016 @JianLi-RH @pruan-rht
> Fix undefined method `split` for Array

- features/upgrade/workloads/descheduler-upgrade.feature
As of today test was failing due to the error "no specification for user index 0 in a scenario @users tag (RuntimeError)", added @users=upuser1,upuser2 to fix the same.
> Add @users=upuser1,upuser2 to the uprade prepare & check

- features/upgrade/monitoring/monitoring-upgrade.feature
- lib/openshift/prometheus.rb
> Simplify OCP-29797

- features/upgrade/sdn/ipsec-upgrade.feature
@openshift/team-sdn-qe My bad. Quick fix causing upgrade test to fail.
Logs: https://privatebin-it-iso.int.open.paas.redhat.com/?0a411fc0afb4423a#HgXtpa3UNGhsDSPM1ks5Xe3TmE3nHu765AK5VdSzQk2f
> Default interface fetching

- testdata/deployment/rolling.json
@kasturinarra Please help review , thanks.
runner log for arm64 profile; https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/238392/console
runner log for normal profile: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/238393/console
> update the image for rolling deployment

- lib/rules/web/ocm_console/creation_cards_page.xyaml
- lib/rules/web/ocm_console/install_page.xyaml
Here is Jenkins run result: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/237567/console
Please help review the case, thanks. @yasun1 @xueli181114 @yuwang-RH
The related PR: https://github.com/openshift/cucushift/pull/8916
> Auto case OCP-45427

- lib/cli_executor.rb
- lib/local_process.rb
Thanks for @xingxingxia's idea.
@jhou1 @xingxingxia  @dis016 @JianLi-RH @pruan-rht : please help review, thanks ~ !
CC @kasturinarra @zhouying7780 @wangke19 @lihongyan1 @XiyunZhao of original PR.
Related with https://github.com/openshift/cucushift/pull/8915 and https://github.com/openshift/verification-tests/pull/2524
> Hide sensitive info from CMDs/logs

- features/networking/multicast.feature
Suggested by https://docs.google.com/presentation/d/18jZ2VmgshJxIe0gOo84oT0zXTT2Z6pR3CV1Kl64vmv8/edit#slide=id.gdd009258c0_0_15, update test case tile to use namespace.
> Update test case title to use namespace

- lib/log.rb
/cc @jhou1 @dis016 @JianLi-RH @pruan-rht 
You can check `source: data:` in Runner/239052
> [HOTFIX] Hide sensitive info

- lib/rules/web/ocm_console/install_page.xyaml
> installpage update

- features/networking/build.feature
for fix this issue https://issues.redhat.com/browse/OCPQE-7408
this case is multitement cases, we need this tag in order to it can be running on correct cluster. 
@jhou1 @liangxia
> update tag with multitemant for cases

- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/insecure/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/transport_tls/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth_with_transport_tls/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/insecure/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/transport_tls/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth_with_transport_tls/deployment.yaml
- testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
- testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
testrun: [OS-20211130-1050](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=OS-20211130-1050)
> OCPQE-6978: elasticsearch image update

- features/storage/dynamic_provisioning.feature
This fixes [OCPQE-7428](https://issues.redhat.com/browse/OCPQE-7428) and [OCPQE-7407](https://issues.redhat.com/browse/OCPQE-7407).
The final step can be skipped because having this step would require us to configure gce/aws... properly in the test repository. @duanwei33 @Phaow PTAL
> Fix OCPQE-7407

- features/upgrade/routing/upgrade.feature
This test case is based on the customer scenario where an idle workload  will be unidled after upgrade without any manual intervention.
> Unidling a route work without user intervention

- features/upgrade/routing/OWNERS
/cc @lihongan @jhou1 @pruan-rht
> Add routing owners for upgrade test

- features/networking/sriov.feature
- testdata/networking/sriov/pod/sriov-specified-cpu.yaml
- testdata/networking/sriov/sriovnetwork/intel-dpdk.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-dpdk.yaml
There is project nodeport-upgrade already exist in `features/upgrade/sdn/service-upgrade.feature`.  so change it 
@anuragthehatter ^^
> update  sriov related failed cases

- features/networking/service.feature
@weliang1 @anuragthehatter  @zhaozhanqi  Please review this PR, here is the runner log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3750/console
> Add OCP-43493 into service.feature

- config/cucumber.yml
/cc @jhou1 @dis016 @pruan-rht @JianLi-RH
> Add profile plain with log level to plain

- lib/rules/web/admin_console/4.10/monitoring_metrics.xyaml
Runner job:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/240046/console
> fixed case failure caused by product change

- testdata/customscheduler/pod-customscheduler.yaml
- testdata/customscheduler/pod-defaultscheduler.yaml
This PR has been tested for the following test cases and attached is the Jenkins and test case logs
Jenkins job -1) https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/runner-v3-smoke/3792/console
2) https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/parallel-runner/2639/
[OCP-33764
](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/12/01/19%3A03%3A27/Validate_Pod_with_only_one_TopologySpreadConstraint_topologyKey_zone_and_maxSkew_1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20211202%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20211202T180701Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=7d65cf1cca91af69319c5979c7ba61dfe754d726e0f3d06c083a3a4062e059cb)
[OCP-33765 …
> OCPQE-6993 Replaced pause with hello-openshift multiarch image

- lib/rules/web/admin_console/4.10/check_links.xyaml
- lib/rules/web/admin_console/4.10/clustersettings.xyaml
- lib/rules/web/admin_console/4.8/check_links.xyaml
- lib/rules/web/admin_console/4.9/check_links.xyaml
OCP-23012 pass log:
4.8: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245720/console
4.9: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245723/console
4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245722/console
OCP-33125
4.10 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245722/console
> Aumation fix for OCP-23012, OCP-33125

- features/routing/route.feature
logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245697/console
@melvinjoseph86 @ShudiLi @quarterpin  Please help take a look. thanks.
> update OCP-16368 and replace docker with nginx image

- lib/rules/web/admin_console/4.10/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.9/operator_hub.xyaml
Pass log on 4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/246394/console
@XiyunZhao or @yapei
> fix for ocp-27495

- features/routing/route.feature
log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247789/console
@quarterpin @melvinjoseph86 @ShudiLi Please help take a look. Thanks.
> update OCP-14059 to remove dependence of caddy image

- features/cli/projects.feature
This is to enable OCP-11887 for arm clusters
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245594/console
> OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (projects)

- lib/webauto/web4cucumber.rb
Try to fix the unknown arguments error for Chrome
jenkins log on private cluster(with proxy configured)  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247866/console 
jenkins log on normal cluster(no proxy) https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247757/consoleFull
> fix Chrome unknown arguments error

- lib/webauto/web4cucumber.rb
This is for Firefox fix ONLY!
Jenkins pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/247659/console 
local pass log http://pastebin.test.redhat.com/1014280
@yanpzhan  @XiyunZhao @liangxia  @jhou1 Could you help review? Thanks!
> fix unknown arguments error

- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
pass log on 4.7: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/252529/console
pass log on 4.8: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/252530/console
> fix ocp-36912

- features/networking/service.feature
auto case OCP-47087 and Move nodePort case from cucushift repo to verification-tests https://github.com/openshift/cucushift/pull/8901
http://pastebin.test.redhat.com/1016453
> add nodeport case from bug and update the existing cases

- testdata/customscheduler/pod-customscheduler.yaml
- testdata/customscheduler/pod-defaultscheduler.yaml
testrun: [OS-20211214-0908](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=OS-20211214-0908)
> OCPQE-6993: rebuild paues image

- testdata/routing/websocket/pod.json
testrun:[OS-20211215-0711](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=OS-20211215-0711)
> OCPQE-6983: rebuild hello-websocket image

- features/upgrade/sdn/ipsec-upgrade.feature
This fixes failure in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24731/rehearse-24731-periodic-ci-openshift-verification-tests-master-stable-4.9-upgrade-from-stable-4.8-upgrade-verification-tests-baremetal-ipi/1471764064664293376
> Add network-ovnkubernetes for relevant upgrade test

- testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml
testrun: [OS-20211213-0812](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=OS-20211213-0812)
> OCPQE-6989: rebuild origin-cluster-capacity image

- features/upgrade/api_auth/upgrade.feature
```
[lxia@homepc verification-tests]$ grep -r OCP-22734
features/upgrade/api_auth/upgrade.feature:  # @case_id OCP-22734
features/upgrade/api_auth/upgrade.feature:  # @case_id OCP-22734
```
> Remove duplicate case ID

- features/networking/ipv6_dualstack.feature
- features/step_definitions/networking.rb
@openshift/team-sdn-qe PTAL, thanks
> add nodeport case for ipv6

- lib/rules/web/admin_console/4.10/monitoring_metrics.xyaml
Fixed https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-21263
runner job:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/261392/
> xpath change caused product change

- features/networking/egress-ip.feature
auto case OCP-46637 which is from customer bug: https://bugzilla.redhat.com/show_bug.cgi?id=2024880
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3815/console
> auto case OCP-46637

- lib/rules/web/admin_console/4.10/check_links.xyaml
- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.10/monitoring.xyaml
- lib/rules/web/admin_console/4.10/route.xyaml
- lib/rules/web/admin_console/4.10/style.xyaml
For case OCP-29209,OCP-25791,OCP-25840,OCP-27586,OCP-26040,OCP-29799
> fix 4.10 automation failure

- features/upgrade/machines/machines.feature
/cc @JianLi-RH @pruan-rht @jhou1 @dis016
> Fix tags in machine upgrade tests

- lib/rules/web/admin_console/4.10/dashboards.xyaml
the fix is for cases OCP-27901,OCP-28297 and OCP-19817
> fix automation failed

- features/upgrade/api_auth/upgrade.feature
- features/upgrade/build/build-upgrade.feature
- features/upgrade/cloudcredential/upgrade.feature
- features/upgrade/etcd/upgrade.feature
- features/upgrade/logging/upgrade.feature
- features/upgrade/machines/machines.feature
- features/upgrade/marketplace/upgrade.feature
- features/upgrade/monitoring/monitoring-upgrade.feature
- features/upgrade/node/node-upgrade.feature
- features/upgrade/node/scc.feature
- features/upgrade/olm/upgrade.feature
- features/upgrade/routing/upgrade.feature
- features/upgrade/sdn/egress-upgrade.feature
- features/upgrade/sdn/externalIP-upgrade.feature
- features/upgrade/sdn/multus-upgrade.feature
- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/service-upgrade.feature
- features/upgrade/security_compliance/fips.feature
- features/upgrade/storage/upgrade.feature
- features/upgrade/web/console-upgrade.feature
- features/upgrade/workloads/oc-upgrade.feature
Sync tags between upgrade prepare/check, mainly for the tag baremetal-upi, and several others as well.
Hi @jhou1 @dis016 @pruan-rht @JianLi-RH  Could you help check ?
> Sync tags between upgrade prepare/check

- features/upgrade/sdn/egress-upgrade.feature
Fix failure in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24942/rehearse-24942-periodic-ci-openshift-verification-tests-master-stable-4.9-upgrade-from-stable-4.8-upgrade-verification-tests-vsphere-upi/1478591823914995712
Hi @jhou1 @JianLi-RH @dis016 @pruan-rht  Could you help check ?
> Add network tag for OCP-44316

- testdata/build/ruby20rhel7-context-docker.json
@pruan, as discussed on slack.
> Fix repo for ruby-hello-world-context-dir

- lib/log.rb
Hi @jhou1 @jianlinliu @JianLi-RH @dis016 @pruan-rht , could you help check ?
> Add password to sensor word

- features/step_definitions/cli.rb
This is framework support for https://github.com/openshift/cucushift/pull/8988's upcoming fix change (i.e. [this review suggestion](https://github.com/openshift/cucushift/pull/8988#discussion_r779550497)), which needs several times of curl watches in background and needs check them.
> Support for Jaya's cucushift #8988

- features/networking/ovn.feature
Fix failure in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/23413/rehearse-23413-periodic-ci-openshift-verification-tests-master-nightly-4.10-e2e-azure-cucushift-ipi-destructive/1481112159621484544
Hi @jhou1 @dis016 @JianLi-RH @pruan-rht  Could you help check ?
> Fix OCP-26138

- features/networking/sgw-lgw-migration.feature
- features/step_definitions/networking.rb
Just a starting point to cover lgw-sgw migration and vice versa. @huiran0826 Need few egress IP cases as well here which you think are imperative to be added into it. Once this merge and you can add cases you think need to be added here. Plan for now is to run all checks in one scenario so they can be run on same cluster which nightly CI configure.
We don't want scenario to grow big but just the important one's you think are important to check on migration as regular regression will also be tested on CI brought up LGW clusters
I will upload testing logs soon.
> Lgw integeration and sgw<->lgw migration

- lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
fix for ocp-27631, ocp-22308
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/276387/console
> fix for 4.7

- features/storage/csi.feature
- features/storage/csi_clone.feature
- features/storage/csi_snapshot.feature
To fix https://issues.redhat.com/browse/OCPQE-8134
@jhou1 PTAL, thanks.
> Add qeci tag for cinder CSI Driver cases

- features/networking/sgw-lgw-migration.feature
Add egress cases to scenario sgw<->lgw
Testlog: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3891/console
/cc  @openshift/team-sdn-qe
> Add egress cases to scenario sgw-lgw

- lib/openshift/horizontal_pod_autoscaler.rb
@yanpzhan  Could you take a look ?
Tested with OCP-13016 and OCP-19695, both passed
> Fix for OCP-19695

- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.9/dashboards.xyaml
Pass log for cases OCP-42112,OCP-19695 on 4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/281161/console
Pass log for OCP-19695  on 4.8: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/281162/console
> update web rules

- tools/cloud_usage.rb
- tools/instance_summary.rb
Print out summary for AWS-CHINA region in the daily cloud-usage-summary.
> added summary for AWS-China

- features/step_definitions/networking.rb
The old `docker0` rule was removed
`OPENSHIFT-FIREWALL-ALLOW -i docker0 -m comment --comment "from docker to localhost" -j ACCEPT`
https://github.com/openshift/sdn/pull/345
Also for step failures, `@result[:message]` is never displayed, use `logger.info`.
Use `info` level because we expect this to fail at one step in the test.
> OCP-11286: remove docker0 rule and log failures for debug

- features/step_definitions/metering.rb
- features/step_definitions/nfd.rb
- lib/openshift/node_feature_discovery.rb
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/291115/console
depends on https://github.com/openshift/cucushift/pull/8835
> Fix nfd for 4 9

- features/upgrade/routing/upgrade.feature
will revert this after the debugging.
@quarterpin @melvinjoseph86 @ShudiLi  PTAL, thanks
> setting routing cases as inactive temporarily for debugging purpose

- features/step_definitions/file.rb
/cc @miyadav @dis016 @JianLi-RH @pruan-rht @jhou1
> Fix indention issue in file.rb

- lib/bushslicer.rb
- lib/launchers/a_r_m_rdu2.rb
- lib/launchers/cloud_helper.rb
Tested by https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/71100/
> ARMOCP-46: Adding ARM RDU2 Bare Metal IaaS

- tools/openshift_qe_slack.rb
Outputing summary to team-qe channel instead to lessen the noise in forum-qe
@mffiedler can you pls take a look when you have a chance.  I've tested it already and it works.  I want to merge it today if possible to cut down the noise in `#forum-qe` in slack.
> fix slack notification error.

- tools/instance_summary.rb
- tools/openshift_qe_slack.rb
@liangxia @jhou1 PTAL and merge.  I've tested it already and it works.
> use slack ruby api to post message and to team-qe channel

- tools/instance_summary.rb
we should really do a DB lookup instead of hard-coding.
> fix pricing issue and packet price lookup logic

- features/upgrade/routing/upgrade.feature
1. revert the PR https://github.com/openshift/verification-tests/pull/2652
2. remove the GCP tag from some cases (for debugging purpose) 
@quarterpin @melvinjoseph86 @ShudiLi PTAL, thanks
> revert routing cases to active and update tag for GCP

- config/config.yaml
- features/support/cucu_formatter.rb
- lib/bushslicer.rb
Per discussion in https://coreos.slack.com/archives/CPJQCSN49/p1644325801134459
/cc @jmekkatt @pruan-rht @dis016 @JianLi-RH @jhou1
> Fix urls for cucushift in logs

- features/networking/multus.feature
Automate OCP-46116: [BZ 1897431] CIDR support for additional network attachment with the bridge CNI plug-in
Test log:
http://file.rdu.redhat.com/~weliang/OCP-46116.txt
> Automate OCP-46116

- features/upgrade/routing/upgrade.feature
pre upgrade check: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/313279/console
post upgrade check: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/313282/console
> Ocp45955 rework3

- lib/launchers/alicloud.rb
- tools/cloud_usage.rb
- tools/instance_summary.rb
@jhou1 @liangxia @JianLi-RH @dis016  PTAL.  Example output
```
+-----------------------------------------------+--------+--------------+---------------+----------+-----------+-----------------------+
|                     name                      | uptime | flexy_job_id |     type      | cost ($) |  region   |      inst_prefix      |
+-----------------------------------------------+--------+--------------+---------------+----------+-----------+-----------------------+
| jiwei-201-vtbrg-worker-us-east-1a-lfpqw       | 0.29   | not found    | ecs.g6.large  | 0.04     | us-east-1 |                       |
| jiwei-201-vtbrg-worker-us-east-1b-cs4hh       | 0.31   | not found    | ecs.g6.large  | 0.04     | us-east-1 |                       |
| jiwei-201-vtbrg-master-0                      | …
```
> added alicloud usage summary support

- features/step_definitions/scc.rb
/cc @dis016 @JianLi-RH @pruan-rht @jhou1
> Simplify SCC cleanup

- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/webauto/web4cucumber.rb
Fix proxy issue in https://issues.redhat.com/browse/OCPQE-8619
Pass log on proxy cluster :job/ocp-common/job/Runner/317907/console
> fix web issue

- doc/prow/query_singlenode-tests.json
/cc @xiuwang @jhou1 @dis016 @JianLi-RH @pruan-rht
> OCPQE-8799: Add query for singlenode

- features/upgrade/sdn/egress-upgrade.feature
According to conversation in https://coreos.slack.com/archives/CH76YSYSC/p1643894678417879
Hi @jhou1 @dis016 @JianLi-RH @pruan-rht Could you help check ?
> OCPQE-8837: Mark OCP-45349 as flaky

- testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_deployment.yaml
- testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
To review by @asood-rh 
cc @LiangquanLi930 for visisbility
> ARMOCP-232: Updates rsyslogd-container image for logforwarding cases

- doc/prow/4.11/query_aws_ipi_tests.json
- doc/prow/4.11/query_aws_upi_tests.json
- doc/prow/4.11/query_azure_ipi_tests.json
- doc/prow/4.11/query_azure_upi_tests.json
- doc/prow/4.11/query_baremetal_ipi_tests.json
- doc/prow/4.11/query_baremetal_upi_tests.json
- doc/prow/4.11/query_gcp_ipi_tests.json
- doc/prow/4.11/query_gcp_upi_tests.json
- doc/prow/4.11/query_openstack_ipi_tests.json
- doc/prow/4.11/query_openstack_upi_tests.json
- doc/prow/4.11/query_upgrade.json
- doc/prow/4.11/query_vsphere_ipi_tests.json
- doc/prow/4.11/query_vsphere_upi_tests.json
/cc @jhou1 @dis016 @pruan-rht @JianLi-RH
> Add query for 4.11

- features/cli/oc_import_image.feature
- features/cli/oc_registry.feature
- features/registry/is.feature
- features/registry/registry.feature
- features/upgrade/samples_operator/upgrade.feature
Tests in Prow and upgrade tests in Jenkins both need the tag.
> Add tag 4.11

- tools/jenkins/slaves/Dockerfile.rhel8
Hi @jhou1 @jianlinliu @pruan-rht @dis016 @JianLi-RH  Could you help check ?
> OCPQE-8979: Fix RHEL 8 based Jenkins agent image

- testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_deployment.yaml
To review by @aleskandro and @pruan-rht 
Local test run passed.
> Fix image tag for rsyslog server

- features/step_definitions/logging.rb
Fix https://issues.redhat.com/browse/OCPQE-8932, the failure happens when channel name is `stable`,  below step will always fail:
```
success = wait_for(180, interval: 10) {
(subscription(subscription).installplan_csv.include? channel) || (subscription(subscription).installplan_csv.include? (channel.split('-')[1]))
}
```
Here add a step to check channel name first, if it's `stable`, then only compare pre installed CSV version and new install CSV version.
/cc @anpingli
> fix OCPQE-8932

- tools/jenkins/slaves/Dockerfile.rhel8
/cc @jhou1 @dis016 @pruan-rht @JianLi-RH 
We are using env USER_PATHS in our images, also we need the write permission to /etc/pki.
> Several changes to RHEL 8 Jenkins agent image

- features/networking/ovn_ipsec.feature
- features/upgrade/sdn/ipsec-upgrade.feature
@zhaozhanqi Quick fix Please help looking at it.
> Added ipsec tags

- lib/rules/web/admin_console/4.10/operator_hub.xyaml
- lib/rules/web/admin_console/4.11/operator_hub.xyaml
pass log when url opens with yaml view: http://pastebin.test.redhat.com/1034894
pass log when url opens with form view: /job/ocp-common/job/Runner/343576/console
> fix for ocp-28832

- features/cli/deploy.feature
@kasturinarra  for https://issues.redhat.com/browse/OCPQE-7609, I can't figure out the root cause and can't reproduce , so add the events to help debug . please help review , thanks .
> add events to debug

- features/cli/oc_expose.feature
- testdata/deployment/OCP-10873/dc.yaml
- testdata/deployment/OCP-10873/svc.json
@wangke19 @jmekkatt Regarding jira https://issues.redhat.com/browse/OCPQE-8475, raising PR. Please review.
test run details- /ocp-common/job/Runner/345347/console
> Adding nginx alpine image

- features/step_definitions/logging.rb
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/no_user/configmap.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/no_user/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/configmap.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/no_user/configmap.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/no_user/deployment.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/configmap.yaml
- testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/deployment.yaml
Update ES image to fix below issue on arm64:
```
/usr/share/elasticsearch/bin/elasticsearch-env: line 67: /opt/jdk-15.0.1+9/bin/java: cannot execute binary file: Exec format error
```
/cc @anpingli @kabirbhartiRH
> update ES image

- doc/prow/query_connected-tests.json
- doc/prow/query_disconnected-tests.json
- doc/prow/query_noproxy_tests.json
- doc/prow/query_proxy_tests.json
- doc/prow/query_stage_only_tests.json
> OCPQE-9149: Add query for proxy and disconnected test cases

- features/registry/remote.feature
@liangxia Please help review this, thanks
> OCP-10904 has been fixed on 4.11 and 4.10,remove flaky tag

- Gemfile
- features/step_definitions/nfd.rb
depends on https://github.com/openshift/cucushift/pull/9076
> fix UI to use 'stable' channel

- features/networking/egress-ingress.feature
@zhaozhanqi @liangxia  PTAL, thanks!
> Add noproxy and connected tags to egressnetworkpolicy cases

- features/step_definitions/logging_metrics.rb
This PR fixes https://issues.redhat.com/browse/OCPQE-9397.
> fix OCPQE-9397

- doc/prow/query_network-multitenant.json
- doc/prow/query_network-openshiftsdn.json
- doc/prow/query_network-ovnkubernetes.json
/cc @zhaozhanqi @jhou1 @JianLi-RH @dis016 @pruan-rht
> Add query for network

- features/upgrade/sdn/policy-upgrade.feature
> update ovn case tag

- doc/prow/query_network-networkpolicy.json
@liangxia for openshiftsdn ,we have networkpolicy and multitenant cases, so add this one
for openshift-sdn plugin cases filter. 
networkpolicy:      @openshiftsdn && not @multitenant
multiteannt :         @ openshift-sdn && not @networkpolicy
> add one networkplicy query

- lib/openshift/node.rb
- lib/rules/web/admin_console/4.10/goto.xyaml
- lib/rules/web/admin_console/4.10/logs.xyaml
- lib/rules/web/admin_console/4.10/node.xyaml
- lib/rules/web/admin_console/4.11/goto.xyaml
- lib/rules/web/admin_console/4.11/logs.xyaml
- lib/rules/web/admin_console/4.11/node.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.6/node.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
- lib/rules/web/admin_console/4.7/logs.xyaml
- lib/rules/web/admin_console/4.7/node.xyaml
- lib/rules/web/admin_console/4.8/goto.xyaml
- lib/rules/web/admin_console/4.8/logs.xyaml
- lib/rules/web/admin_console/4.8/node.xyaml
- lib/rules/web/admin_console/4.9/goto.xyaml
- lib/rules/web/admin_console/4.9/logs.xyaml
- lib/rules/web/admin_console/4.9/node.xyaml
Added rules, related scenario in https://github.com/openshift/cucushift/pull/9081
@XiyunZhao or @yapei pls help to review, thanks!
> add auto fix in OCP-20688 OCP-19722

- lib/rules/web/admin_console/4.10/goto.xyaml
- lib/rules/web/admin_console/4.11/goto.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
- lib/rules/web/admin_console/4.8/goto.xyaml
- lib/rules/web/admin_console/4.9/goto.xyaml
Update rule for : https://github.com/openshift/cucushift/pull/9088
> fix OCP-27601

- features/networking/build.feature
> remove proxy tag

- testdata/networking/sriov/sriovnetworkpolicy/intel-dpdk.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice-without-pf.yaml
- testdata/networking/sriov/sriovnetworkpolicy/intel-netdevice.yaml
- testdata/networking/sriov/sriovnetworkpolicy/mlx277-netdevice-without-mtu.yaml
- testdata/networking/sriov/sriovnetworkpolicy/mlx278-netdevice.yaml
- testdata/networking/sriov/sriovnetworkpolicy/wrong/invalidname.yaml
- testdata/networking/sriov/sriovnetworkpolicy/wrong/non-deviceid
- testdata/networking/sriov/sriovnetworkpolicy/wrong/non-vondor
- testdata/networking/sriov/sriovnetworkpolicy/wrong/vfnum0
just remove rootdevice in order to it can work on different hardware
> remove rootdevice

- lib/rules/web/admin_console/4.10/clustersettings.xyaml
- lib/rules/web/admin_console/4.11/check_links.xyaml
- lib/rules/web/admin_console/4.11/clustersettings.xyaml
Pass log for ocp-33125 on 4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/392159/console
Pass log for ocp-24512 on 4.11: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/392160/console
> fix OCP-33125 OCP-24512

- features/upgrade/etcd/upgrade.feature
Hi @geliu2016 ,
Its working fine on both connected and disconnected platforms with proxy and without proxy.
Please find the below logs.
[connected profile no proxy](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4193/console)
[disconnected with proxy](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4189/console).
Could you please take a look.
>    fix the test on disconnected profiles

- features/networking/sriov.feature
- features/upgrade/sdn/service-upgrade.feature
- testdata/networking/sriov/sriovnetworkpolicy/wrong/non-deviceid
> fixed vf number and negative log

- features/machine/machine.feature
This case is rewrite with golang https://github.com/openshift/openshift-tests-private/pull/3289
> remove OCP-33040 as it is rewrited with golang

- features/networking/ovn_winc.feature
- features/step_definitions/networking.rb
> skip scenario for windows worker

- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.10/goto.xyaml
- lib/rules/web/admin_console/4.11/dashboards.xyaml
- lib/rules/web/admin_console/4.11/goto.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/goto.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.7/goto.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.8/goto.xyaml
- lib/rules/web/admin_console/4.9/dashboards.xyaml
- lib/rules/web/admin_console/4.9/goto.xyaml
update rule for https://github.com/openshift/cucushift/pull/9086
> add auto to OCP-19817

- features/registry/is.feature
- features/registry/remote.feature
@liangxia @pruan-rht Hi, please help review this, thanks
> Not not use openshift imagestream

- features/upgrade/jenkins/upgrade.feature
This resolves OCPQE-9602. @liangxia PTAL
> Mark jenkins upgrade test as flaky

- features/step_definitions/nfd.rb
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/398414/console (4.11)
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/398564/console (4.7)
PTAL
> fix 4.7 NFD UI failure

- testdata/routing/header-test/dc.json
@quarterpin @melvinjoseph86 @ShudiLi PTAL, thanks
> update routing dc apiVersion

- features/upgrade/etcd/upgrade.feature
/cc @geliu2016 @juzhao @dis016 @pruan-rht @jhou1 @JianLi-RH
> OCPQE-9841: Add several tags for upgrade-prepare

- lib/rules/web/admin_console/4.10/operator_hub.xyaml
- lib/rules/web/admin_console/4.11/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.9/operator_hub.xyaml
4.11 pass log Runner/402620/console 
4.9 pass log Runner/402621/console
4.8 pass log Runner/402640/console
> fix OCP-32151 rules

- testdata/authorization/scc/ocp11762/dc.json
- testdata/authorization/scc/ocp11762/scc_hostdir.yaml
- testdata/cli/application-template-stibuild-with-mount-secret.json
- testdata/deployment/dc-with-pre-mid-post.yaml
- testdata/deployment/dc-with-two-containers.yaml
- testdata/templates/ui/application-template-stibuild-without-customize-route.json
I see that some more testdata files needed fix, so raising a pr here
> Fix non groupified resources

- features/upgrade/etcd/upgrade.feature
fix OCP-22606
Hi @geliu2016 
Could you please have a look. Excluded this test from execution on disconnected profiles.
> fix OCP-22606

- features/upgrade/machines/machines.feature
Remove OCP-41804 as it is rewriten with golang https://github.com/openshift/openshift-tests-private/pull/3330
@jhou1  @liangxia please help to take a look.
> remove OCP-41804 as it is rewriten with golang

- lib/rules/web/admin_console/4.10/operator_hub.xyaml
- lib/rules/web/admin_console/4.11/operator_hub.xyaml
- lib/rules/web/admin_console/4.6/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
- lib/rules/web/admin_console/4.9/operator_hub.xyaml
- lib/rules/web/admin_console/base/login.xyaml
Pass log on 4.11 /job/ocp-common/job/Runner/404382/console
> fix ocp-29690

- features/cli/build.feature
- features/logging/logging_acceptance.feature
Those tests have been consistently failing for more than a week. Taken them out from CI.
/cc @anpingli @jhou1 @JianLi-RH @dis016 @pruan-rht
> Exclude flaky test

- testdata/build/application-template-stibuild.json
- testdata/image-streams/ocp10721.json
- testdata/logging/loggen/container_json_log_template.json
- testdata/templates/ocp11023/build.yaml
- testdata/templates/ocp11943/dc.json
/cc @jhou1  @xiuwang @anpingli @zhouying7780 @kasturinarra
> Fix multiple failures in Prow CI

- lib/launchers/o_c_m_cluster.rb
- test/lib/launchers/o_c_m_cluster_test.rb
> Fix 'multi_az' option when creating OSD4 clusters

- testdata/logging/clusterlogforwarder/37508.yaml
- testdata/logging/clusterlogforwarder/clf-multiple-external-logstore-template.yaml
- testdata/logging/clusterlogforwarder/fluentd/insecure/clusterlogforwarder.yaml
- testdata/logging/clusterlogforwarder/fluentd/secure/clusterlogforwarder.yaml
- testdata/logging/clusterlogforwarder/multiple_receiver/clf_fluent_es.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC3164.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC5424.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_default.yaml
- testdata/logging/clusterlogging/deploy_clo_via_olm/4.2/clo-sub-template.yaml
- testdata/logging/eleasticsearch/deploy_via_olm/4.2/eo-sub-template.yaml
- testdata/logging/eventrouter/internal_eventrouter.yaml
- testdata/logging/loggen/container_json_unicode_log_template.json
Fix https://issues.redhat.com/browse/OCPQE-6091
> fix OCPQE-6091

- features/networking/service.feature
@zhaozhanqi PTAL. Added one mroe step to make this feature check properly as per https://github.com/openshift/ovn-kubernetes/pull/1063
The changes fails on 4.10 build but passes on cluster bot build with referenced PR
> Adding another step to validate Nodeport ETP=local properly

- lib/rules/web/admin_console/4.11/check_links.xyaml
Update checkpoint (check_logo_in_masthead & check_logo_in_about_modal) for new feature in OCP 4.11
Pass log: [OCP-4.11](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/419258/console)
> Fix case OCP-29200 for OCP 4.11

- lib/rules/web/admin_console/4.11/imagestream.xyaml
Pass log on 4.11: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/421632/console
> fix ocp-23880

- doc/prow/query_heterogeneous.json
/cc @aleskandro @YuLi517 @jhou1 @JianLi-RH @dis016 @pruan-rht
> OCPQE-9784: Add query for heterogeneous

- features/cli/oc_secrets.feature
- features/cli/policy.feature
- features/infrastructure/scheduler.feature
- features/kata/smoke_tests.feature
- features/logging/permission.feature
- features/machine/machine.feature
- features/machine/machine_healthcheck.feature
- features/machine/upi_gcp.feature
- features/networking/egress-ingress.feature
- features/networking/egress-ip.feature
- features/networking/multus.feature
- features/networking/pod.feature
- features/networking/sgw-lgw-migration.feature
- features/registry/registry.feature
- features/service_catalog_tsb/tsb.feature
- features/storage/NoDiskConflict.feature
- features/storage/csi_clone.feature
- features/storage/csi_resize.feature
- features/storage/security.feature
[ and ] are special chars for regexp, which blocks some of our scripts from functioning.
> Remove special chars from scenario names

- lib/rules/web/admin_console/4.11/monitoring_metrics.xyaml
Fixed some failure for product change:
Detail see https://issues.redhat.com/browse/OCPQE-10103
Jenkin job：
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/426026/console
> Fix some failure for product change

- features/upgrade/etcd/upgrade.feature
Hi @geliu2016 ,
Could you please have a look.
Please find the execution [log](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4290/console)
> fix-issue-ocp-22606

- testdata/build/application-template-stibuild.json
- testdata/hpa/dc-hello-openshift.yaml
- testdata/image/gitserver/gitserver-ephemeral.yaml
- testdata/quota/quota_template.yaml
- testdata/templates/OCP-13259/samplepipeline.yaml
> Fix apiVersion

- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/dashboards.xyaml
Pass log for 411: job/Runner/432589
> Fix 411 auto case OCP-27590,OCP-29210

- features/networking/egress-ip.feature
Fix OCP-25460
Test log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4403/console
/cc @openshift/team-sdn-qe @jechen0648
> fix OCP-25640

- Gemfile
- lib/bushslicer.rb
- lib/iaas/iaas.rb
- lib/launchers/cloud_helper.rb
- lib/launchers/ovirt.rb
- tools/os_deps/deps.deb
- tools/os_deps/deps.dnf.fedora
- tools/os_deps/deps.yum.RHEL8
- tools/os_deps/deps.yum.fedora
ovirt-sdk gem being installed via Gemfile
> Implementation of ovirt modules

- lib/rules/web/admin_console/4.10/monitoring.xyaml
- lib/rules/web/admin_console/4.11/monitoring.xyaml
- lib/rules/web/admin_console/4.6/monitoring.xyaml
- lib/rules/web/admin_console/4.7/monitoring.xyaml
- lib/rules/web/admin_console/4.8/monitoring.xyaml
- lib/rules/web/admin_console/4.9/monitoring.xyaml
rule updated to be more reliable
> fix OCP-25816 rules

- testdata/descheduler/kd-sub-template.yaml
Add right apiversion for template kind
> Add right apiversion for template

- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/machine/machine_healthcheck.feature
- features/machine/machine_misc.feature
- features/machine/upi_gcp.feature
- features/step_definitions/machine.rb
- features/step_definitions/machine_healthcheck.rb
- features/step_definitions/machine_set.rb
- features/upgrade/machines/machines.feature
- lib/openshift/machine_health_check.rb
- lib/openshift/machine_health_check_machine_openshift_io.rb
- lib/openshift/machine_machine_openshift_io.rb
- lib/openshift/machine_set_machine_openshift_io.rb
Tested on aws, seems no new issues were found. @jhou1 @miyadav @huali9 PTAL
Enable CAPI regression run 20220526-0954
Disable CAPI regression run 20220530-0605
> update machine related sources to use full name

- features/logging/elasticsearch.feature
- features/logging/logging_acceptance.feature
- features/step_definitions/logging.rb
Removed some checkpoints from this case and added a step to check each logging pods's logs.
Log: https://url.corp.redhat.com/7f2009a
> fix logging acceptance case

- features/networking/ovn.feature
For split brain we DROP packes from peer master, but for IPv6
addresses we need to use `ip6tables` command
> OVN: use ip6tables for IPv6 addresses

- lib/rules/web/admin_console/4.11/quota.xyaml
Pass log on 4.11: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/459896/console
> update for OCP-21958

- features/step_definitions/networking.rb
- features/upgrade/sdn/sctp-upgrade.feature
Resolve ticket https://issues.redhat.com/browse/OCPQE-10576,
Analysis for original issue please see comments in above ticket. 
Test log:
Cluster without proper workers: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4450/console
General cluster:  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4452/console
> Fix ocp 44765

- tools/jenkins/slaves/Dockerfile.rhel8
/cc @jianlinliu @gpei @jhou1 @JianLi-RH @dis016 @pruan-rht
> Add repo for ansible 2.9

- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.11/dashboards.xyaml
- lib/rules/web/admin_console/4.6/dashboards.xyaml
- lib/rules/web/admin_console/4.6/logs.xyaml
- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.9/dashboards.xyaml
rule update for ocp-27852. scenario update in https://github.com/openshift/cucushift/pull/9192
> fix auto for web

- lib/base_helper.rb
/cc @jhou1 @pruan-rht @JianLi-RH @dis016
> Fix a logic error in selector_to_label_arr

- features/networking/multicast.feature
OCP-45022 tests the multicast pods function across the nodes. 
Add some steps to OCP-12926 and cover this function.
Meanwhile, revert the codes in https://github.com/openshift/verification-tests/pull/2901, reasons please see https://github.com/openshift/verification-tests/pull/2901#issuecomment-1160083865
Testlogs:
OCP-12926 -- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4487/console
OCP-12929 -- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4488/console
@weliang1 @jechen0648  Could you take a look? Thanks a lot!
> Cover 45022

- lib/cucuhttp.rb
- lib/polarshift/request.rb
Added retry to Polarshift when there's a connection issue.
> added method for http_request with retry to be used with polarshift

- tools/case_id_splitter.rb
> Update tag tool to support proxy/network/arch

- lib/polarshift/request.rb
- lib/polarshift/scenario_wrapper.rb
- lib/polarshift/test_case.rb
- lib/polarshift/test_record.rb
- lib/polarshift/test_suite.rb
> OCPQE-10970: Explicit return for logic error

- lib/polarshift/test_record.rb
> OCPQE-10970: Make msg "scenario not part of this test record" more clear

- features/logging/logging_acceptance.feature
- features/step_definitions/logging.rb
- testdata/logging/clusterlogging/cl-storage-with-im-template.yaml
- testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
Set default pvc size to 20Gi as it's the minimum size allowed in alibaba cloud. 
Skip the not ready pods when checking logs.
> set default pvc size to 20Gi

- doc/prow/query_4.12.json
> Add query for 4.12

- lib/polarshift/test_record.rb
- lib/polarshift/test_suite.rb
- lib/test_case_manager_filter.rb
Some debug codes are added to help debug skip_this_scenario. Now the issue is fixed, it's time to do the cleanup.
> Do cleanup after debug skip_this_scenario

- doc/prow/README.md
- doc/prow/query_aws-ipi.json
- doc/prow/query_aws-upi.json
- doc/prow/query_azure-ipi.json
- doc/prow/query_azure-upi.json
- doc/prow/query_baremetal-ipi.json
- doc/prow/query_baremetal-upi.json
- doc/prow/query_gcp-ipi.json
- doc/prow/query_gcp-upi.json
- doc/prow/query_openstack-ipi.json
- doc/prow/query_openstack-upi.json
- doc/prow/query_vsphere-ipi.json
- doc/prow/query_vsphere-upi.json
> Include all priority test cases in query

- features/storage/csi_clone.feature
Inactive OCP-27686 since it supports different sc.
@duanwei33 please help to review it.
> Inactive OCP-27686

- features/registry/is.feature
[OCP-11805,OCP-11298,OCP-19196,OCP-16495 all passed](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/500340/console)
@zhouying7780 @kasturinarra Please help review, thanks
> check imagestreamtag before using

- features/routing/haproxy-router.feature
- features/routing/route.feature
- features/routing/timeout.feature
https://issues.redhat.com/browse/OCPQE-10301
@quarterpin @melvinjoseph86 @ShudiLi PTAL, thanks
> adding tags for rosa/osd/aro

- features/networking/egress-ip.feature
- features/networking/pod.feature
add @admin tag due to step `Given the env is using "OpenShiftSDN" networkType` added
https://github.com/orgs/openshift/teams/team-sdn-qe ^^
> add admin tag

- features/cli/oc_expose.feature
- features/cli/projects.feature
- features/upgrade/api_auth/upgrade.feature
Added tag for apiserver test cases to run in prow ci. 
@wangke19 PTAL once you have time.
> Added tag for apiserver tests

- features/test/node.feature
- lib/environment.rb
This fix the issue of:
1. I run commands on the host
2. oc debug
/cc @kasturinarra @xingxingxia @JianLi-RH @dis016 @pruan-rht @jhou1
> OCPQE-11705: Fix "PodSecurity violation error"

- features/admin/quota.feature
It takes longer time than I expacted, adding @flaky before finishing debugging
OCP-12292
OCP-10706
OCP-11927
OCP-11348
> Tagging flaky before finishing debugging

- features/admin/quota.feature
Update to flaky before finishing debugging.
> flaky ocp 12086

- features/cli/deploy.feature
@kasturinarra Please help review , thanks .
> add @rosa @osd_ccs @aro

- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/machine/machine_healthcheck.feature
- features/machine/machine_misc.feature
> add tags for rosa/osd/aro

- lib/rules/web/admin_console/4.9/user_management.xyaml
Pass log for 4.9: 583415/console
> Update rule for 25765 on 4.9

- features/networking/pod.feature
- features/networking/sdn.feature
Need to add pod privileges in 412 for this case as well
> OCP-25294 and OCP-23543 quick fix

- features/networking/multus.feature
Following the sample to fix an issue for OCP-21855 in https://issues.redhat.com/browse/OCPQE-11808
> Add @flaky for OCP-21855

- lib/rules/web/admin_console/4.6/projects.xyaml
pass log on 4.6 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/589865/console
error before the updates
```
09-01 13:58:10.254      When I run the :check_timestamp web action                                             # features/step_definitions/web.rb:13
09-01 13:58:10.254        [05:57:47] INFO> running web action check_timestamp ... 
09-01 13:58:10.254        [05:57:47] INFO> element..
09-01 13:58:10.254        [05:57:47] INFO> found 0 element elements with selector: {:xpath=>"//span[contains(@data-test, 'timestamp')]"}
09-01 13:58:10.254        [05:57:48] INFO> found 0 element elements with selector: {:xpath=>"//span[contains(@data-test, 'timestamp')]"}
09-01 13:58:10.254        [05:57:49] INFO> found 0 element elements with …
```
> fix cases on 4.6

- lib/webauto/web4cucumber.rb
add `--disable-extensions` and `--headless` arg when launching chrome to see if we can reduce chrome crash issue
> fix chrome crash issue

- features/build/dockerbuild.feature
- features/cli/configmap.feature
- features/cli/deploy.feature
- features/cli/downwardapi.feature
- features/cli/hpa.feature
- features/cli/oc_patch_apply.feature
- features/cli/oc_secrets.feature
- features/cli/oc_volume.feature
- features/cli/policy.feature
- features/cli/secrets.feature
- features/containers/containers.feature
- features/routing/haproxy-router.feature
- features/routing/route.feature
- features/storage/security.feature
- features/storage/storage_class.feature
- features/web/check_page.feature
- features/web/create.feature
- features/web/deployments.feature
> Add subteam info to scenario name

- features/routing/haproxy-router.feature
- features/routing/route.feature
To address the jira issue: https://issues.redhat.com/browse/OCPQE-11839
log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/594598/console
@quarterpin @melvinjoseph86 @ShudiLi Please help take a look. Thanks.
> fix the test image tmp folder permission issue

- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/tables.xyaml
- testdata/pods/pod-invalid.yaml
fix ocp-33568 pass log on 4.12 Runner/587959/console
ocp-27950 pass log on 4.12: Runner/590011/console
@yapei
> fix web rule for 4.12

- features/admin/quota.feature
Fix ocp-10706, default secrets numbers updated, 3 less default ones .
> Fix ocp-10706, default secrets updated

- features/step_definitions/logging.rb
To fix failures in [OCPQE-11339](https://issues.redhat.com//browse/OCPQE-11339)
> OCPQE-11339: fix imagepullbackoff issue when testing eventrouter

- features/networking/egress-ingress.feature
quick fix for OCP-15017
test log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4996/console
> fix OCP-15017

- features/networking/ovn_ipsec.feature
This one escaped the earlier fixes radar of host network pod usecases. Quick fix.
> PSa on OCP-37392

- tools/openshift-ci/Dockerfile
A second attempt to fix [OCPQE-11756](https://issues.redhat.com//browse/OCPQE-11756)
@liangxia @yapei PTAL
> Change the .local dir location

- features/images/jenkins.feature
@liangxia Please help merge, thanks
> Disable jenkins cases

- features/cli/oc_expose.feature
@wangke19 @dpuniaredhat In this PR we are fixing pod security issue. Please review this PR 
Test run details-  Runner-v3-smoke/5018/
> security fix

- features/networking/sctp.feature
Fix podSecurity issue for sctp cases
OCP-29645:https://privatebin.corp.redhat.com/?642dd704de5a28c3#KFhnqe77CJhf4q9jA81vzJwbPT5MvKgS7o4edW59En9
OCP-28759:https://privatebin.corp.redhat.com/?c79e9f94312d2aea#8Cgb6QVrVfP8jzVAiB46CKUUruK9ck7HvZDVgkU8zk9m
> fix pod security issue

- features/storage/hostpath.feature
Hi Team,
Kindly PTAL,
Add podsecurity for 4.12version
Pass Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/620130/console
Failure Logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/620065/console
/assign @chao007 @duanwei33 @Phaow @radeore
> storage-412-addpodsecurity

- features/networking/multus.feature
Fix for https://issues.redhat.com/browse/OCPQE-12203
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5031/console
> Fix pod security issue for OCP-24490

- lib/rules/web/admin_console/4.12/storage.xyaml
ocp-24415 pass log on 4.12 /ocp-common/job/Runner/626267/console
> fix ocp-24415

- lib/webauto/web4cucumber.rb
Fix for https://issues.redhat.com/browse/OCPQE-12261
Before, failed on https_proxy cluster: ocp-common/job/Runner/629523/console
After, passed on https_proxy cluster: ocp-common/job/Runner/629533/console
> remove --headless

- lib/rules/web/admin_console/4.12/dashboards.xyaml
- testdata/pods/pod-invalid.yaml
revert changes in https://github.com/openshift/verification-tests/pull/3021
> revert changes to pod-invalid.yaml

- features/logging/cluster_logging_operator.feature
- features/step_definitions/logging.rb
1. fix [OCPQE-9545](https://issues.redhat.com//browse/OCPQE-9545)
2. fix issue imported by PR 3067
> fix logging failures

- doc/prow/query_alicloud-ipi.json
- doc/prow/query_alicloud-upi.json
/cc @jhou1 @pruan-rht @gpei @jianlinliu
> Add query for alicloud

- features/upgrade/api_auth/upgrade.feature
This includes fix for 
https://issues.redhat.com/browse/OCPQE-7331 
https://issues.redhat.com/browse/OCPQE-10705 
cc: @xingxingxia @zhouying7780
> Fix failures of OCP-29741, OCP-41198

- features/upgrade/sdn/service-upgrade.feature
Fix pod Security issue for case OCP-44259
Test log:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5040/console
> fix podsecurity issue for idle service

- doc/prow/query_nutanix-ipi.json
- doc/prow/query_nutanix-upi.json
> Add query for nutanix

- features/upgrade/sdn/ipsec-upgrade.feature
Seems like this case is failing most of time due to these issues
Logs(Pre/post): upgrade-prepare, upgrade, upgrade-check 
https://privatebin.corp.redhat.com/?ddcfe288cf6df6ac#Gfu5BVA6mL5zFq7ybfTZndyDRAD9wWPQehoxzXoV8z1c
> PSA labels and ensuring pod deletion

- features/networking/ib-sriov.feature
- features/networking/sriov.feature
pass logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5126/console
> add label for project for 4.12 version

- lib/rules/web/admin_console/4.12/monitoring_alerts.xyaml
fix 4.12 error in OCP-21150/OCP-29300
https://issues.redhat.com/browse/OCPQE-12648
runner job:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/658650/console
> 4.12 monitoring_alerts updates-2

- doc/prow/query_ibmcloud-ipi.json
- doc/prow/query_ibmcloud-upi.json
> Add query for ibmcloud

- features/cli/deploy.feature
> fix failed

- lib/rules/web/admin_console/4.10/dashboards.xyaml
added one more step `change_to_openshiftapiserver_ns` to workaround the bug https://bugzilla.redhat.com/show_bug.cgi?id=2072883
> add one more step

- features/storage/quota.feature
Hi Team, 
Kindly PTAL, 
Issue: pod not reaching to running state as pod security issue. 
Execution logs: 
With fix: 412 cluster PASS 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/665126/console
11-08 14:57:40.441  1 scenario (1 passed)
Without fix: 412 cluster FAIL 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/665136/console
/@assign @chao007 @duanwei33 @Phaow @radeore
> OCP-14173 podsecurity412 fix

- doc/prow/query_4.13.json
> Add query for 4.13

- features/upgrade/api_auth/upgrade.feature
- features/upgrade/build/build-upgrade.feature
- features/upgrade/cloudcredential/upgrade.feature
- features/upgrade/etcd/upgrade.feature
- features/upgrade/logging/upgrade.feature
- features/upgrade/machines/machines.feature
- features/upgrade/monitoring/monitoring-upgrade.feature
- features/upgrade/node/node-upgrade.feature
- features/upgrade/node/scc.feature
- features/upgrade/routing/upgrade.feature
- features/upgrade/samples_operator/upgrade.feature
- features/upgrade/sdn/egress-upgrade.feature
- features/upgrade/sdn/externalIP-upgrade.feature
- features/upgrade/sdn/ipsec-upgrade.feature
- features/upgrade/sdn/multicast-upgrade.feature
- features/upgrade/sdn/multus-upgrade.feature
- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/sctp-upgrade.feature
- features/upgrade/sdn/service-upgrade.feature
- features/upgrade/security_compliance/fips.feature
- features/upgrade/storage/upgrade.feature
- features/upgrade/web/console-upgrade.feature
- features/upgrade/workloads/descheduler-upgrade.feature
- features/upgrade/workloads/oc-upgrade.feature
- features/upgrade/workloads/scheduler-upgrade.feature
/cc @JianLi-RH @shellyyang1989 @jiajliu @jhou1
> Add 4.13 tag for upgrade and sync tags for prepare/check

- features/networking/service.feature
Update master to worker due to hosted cluster do not have master role
> update case to support hypershift hosted cluster

- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/goto.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/goto.xyaml
- lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
Update rules for OCP-24106,OCP-22343 
@yapei
> update rules for hypershift cluster

- doc/prow/query_hypershift-hosted.json
/cc @jhou1 @pruan-rht @JianLi-RH @dis016
> Add query for hypershift

- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.11/dashboards.xyaml
- lib/rules/web/admin_console/4.12/dashboards.xyaml
- lib/rules/web/admin_console/4.13/dashboards.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
- lib/rules/web/admin_console/4.9/dashboards.xyaml
4.12 Hypershift pass log Runner/675109/console
Normal 4.12 pass log Runner/675136/console
Normal 4.11 pass log Runner/675140/console 
Normal 4.10 pass log Runner/675138/console
> update rules when querying by node

- features/networking/ovn_winc.feature
Fix failure of OCP-37519
Test log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5230/console
@zhaozhanqi @anuragthehatter
> fix  OCP-37519

- lib/webauto/web4cucumber.rb
This change is for debugging the error reported in [OCPQE-12378](https://issues.redhat.com//browse/OCPQE-12378)
> Debug issue ocpqe12378

- features/routing/haproxy-router.feature
still seeing the case failed randomly in CI, so update the script to check the haproxy.config instead of result of curling.
@melvinjoseph86 @ShudiLi PTAL, thanks.
log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/679116/console
> to make OCP-10043 more stable

- lib/polarshift/request.rb
When Polarion succeed to create test run, work as previous, no retry.
```
bash-4.4# tools/polarshift.rb create-run -f /67_IPI\ on\ Nutanix\ \&\ FIPS\ on\ \&\ OVN\ \&\ CSI\ pvc.test_run.yaml --no-wait 
[09:17:21] INFO> HTTP POST user@https://POLARSHIFT-URL/project/OSE/run
[09:17:22] INFO> HTTP POST took 1.055 sec: 202 Accepted | application/json 267 bytes
[09:17:22] INFO> to check operation status manually, you can: curl 'https://POLARSHIFT-URL/polarion/request/63847ca2a0de9600108de648' -u user:thepassword
waiting for operation up to 360 seconds..
[09:17:22] INFO> HTTP GET user@https://POLARSHIFT-URL/polarion/request/63847ca2a0de9600108de648
[09:17:23] INFO> HTTP GET took 1.049 sec: 200 OK | application/json 92 bytes
[09:17:38] INFO> HTTP GET …
```
> OCPQE-13027: Retry when Polarion failed to create test run

- lib/launchers/amz.rb
- tools/cloud_watch.rb
- tools/resource_monitor.rb
> Cloud watch utilty to give a warning to the team when vpc & s3 buckets are approach to the max.

- features/upgrade/monitoring/monitoring-upgrade.feature
Jenkins job
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/680401/
> update upgrade case

- features/upgrade/logging/upgrade.feature
/cc @anpingli 
To fix https://issues.redhat.com/browse/OCPQE-12997
> remove version 4.9 from logging upgrade case

- features/machine/machine.feature
@jhou1 @huali9 @sunzhaohua2 PTAL , when time permits . 
This case is [failing](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/all/288693/23905002/23905072/log?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1hrghcxlbgshc%252Cti_s4scyws6guht%252Cti_sok676b1k8j5%252Cti_r1ifkmkw19o1) , due to text check , updated that .
changed text - ......openshift-machine-api/`machine-api-provider-ibmcloud-leader...`
Validation below - 
```
-hm9q4-worker-3-qlx74" to indexer
I1221 06:21:11.591692       1 nodelink_controller.go:57] Adding providerID "ibm://fdc2e14cf8bc4d53a67f972dc2e2c861///miyadav-2112v1-hm9q4/07a7_7373ab98-bbbe-4704-aae2-a2ff98b2520b" for node "miyadav-2112v1-hm9q4-worker-3-qlx74" to indexer
I1221 …
```
> text check update

- features/routing/rate-limit.feature
- features/routing/timeout.feature
follow up https://github.com/openshift/cucushift/pull/9433
@melvinjoseph86 @ShudiLi PTAL, thanks
> adding disconnected tag for httpbin related cases

- features/machine/machine_misc.feature
Met several time, this case failed, manually test it passed, increase time to make it more stable. @miyadav @jhou1 @huali9 PTAL, thanks!
> increase time for OCP-35454

- features/networking/isolation.feature
multi cases with `&` will cause some issue.  Here remove one
Thanks @liangxia finding this issue.
> remove one case id

- lib/webauto/web4cucumber.rb
Follow up of https://github.com/openshift/verification-tests/pull/3176 and https://github.com/openshift/verification-tests/pull/3177
> Remove outdated options in old version watir

- features/logging/cluster_log_forwarder.feature
- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/logging/eventrouter.feature
- features/logging/forward_logs_to_external_elasticsearch.feature
- features/logging/kibana.feature
- features/logging/permission.feature
Added the logging5.6 tag so that we can filter and run these Logging cases from Prow.
> Add logging5.6 and logging5.7 tag for Logging cases in order for us to run the cases on Prow.

- features/admin/quota.feature
The used pods number varies. Update to checking the total quotas
logs http://pastebin.test.redhat.com/1087494
> update quota checking parts for OCP-12086

- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/service-upgrade.feature
> update ip with ip_url for ipv6 address

- features/upgrade/routing/upgrade.feature
the fix is to address [OCPQE-13604](https://issues.redhat.com//browse/OCPQE-13604) and [OCPQE-12307](https://issues.redhat.com//browse/OCPQE-12307)
> the fix is to address OCPQE-13604 and OCPQE-12307

- Gemfile
- lib/webauto/web4cucumber.rb
- tools/jenkins/slaves/Dockerfile.centos
- tools/jenkins/slaves/Dockerfile.rhel7
- tools/jenkins/slaves/Dockerfile.rhel8
- tools/openshift-ci/Dockerfile.centos
Reverts openshift/verification-tests#3201
> Revert "Download webdrivers automatically"

- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
pass log on 4.9: ocp-common/job/Runner/741358/console
pass log on 4.12:ocp-common/job/Runner/741364/console
> update web rule for OCP-25765

- features/step_definitions/logging.rb
Update logging channel and this PR can fix OCPQE-13908. 
/cc @anpingli
> OCPQE-13908: update logging channel

- features/admin/pod.feature
Remove SNO tag for 11925. 
The test need two nodes or more
> Remove SNO tag for 11925

- lib/rules/web/admin_console/4.10/pods.xyaml
- lib/rules/web/admin_console/4.11/pods.xyaml
- lib/rules/web/admin_console/4.12/pods.xyaml
- lib/rules/web/admin_console/4.13/pods.xyaml
- lib/rules/web/admin_console/4.9/pods.xyaml
fix OCP-37526 rules, 
4.13 pass log in Runner/745695/consoleFull
4.12 pass log Runner/745717/consoleFull
> fix OCP-37526 rules

- lib/rules/web/admin_console/4.13/dashboards.xyaml
This change is only needed for OCP4.13
Pass log: Runner/746543/console
> Fix the changes for OCP-42205

- tools/openshift-ci/Dockerfile
> Fetch arch info on demand

- lib/webauto/web4cucumber.rb
To address the issue
```
2023-02-09 04:36:39 WARN Selenium [DEPRECATION] [:caps_browsers] Remote::Capabilities.chrome is deprecated. Use Options.chrome instead.
```
We've compared the test results in master branch and devel branch. Total 230 test cases, and we run the same test on four different clusters on both master branch and devel branch, we only got 2, 2, 4, 3 failures for devel branch in each test run, while 4, 3, 3, 3 failures in master branch.
> Selenium: Use Options, as Remote::Capabilities is deprecated

- lib/rules/web/admin_console/4.9/operator_hub.xyaml
Pass log on 4.9: ocp-common/job/Runner/749827/console
> fix OCP-28832

- features/cluster_configuration/cluster_logging_operator.feature
- features/logging/cluster_log_forwarder.feature
- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/logging/forward_logs_to_external_elasticsearch.feature
- features/logging/kibana.feature
- features/logging/permission.feature
Added '@logging5.5' for running OpenShift Logging 5.5 cases on Prow CI.
> Added @logging5.5 tag for running Logging cases on Prow

- lib/rules/web/admin_console/4.13/goto.xyaml
- lib/rules/web/admin_console/4.13/route.xyaml
Failure log Runner/753773/console
Pass log Runner/753815/console
The failure only happens on 4.13
> fix set_service_name rule

- tools/sync_tc_tags_to_polarion.sh
/cc @weinliu @jhou1 @JianLi-RH @dis016 @pruan-rht
> Skip sync for OCP-14799

- doc/prow/query_4.14.json
> Add query for 4.14

- testdata/hpa/hpa_rubyex.yaml
pass log on 4.13: /ocp-common/job/Runner/759664/console
> update hpa testfile

- features/logging/cluster_log_forwarder.feature
- features/logging/cluster_logging_operator.feature
According to the webapp, we have lots of 100% failure scenarios, this is a partial attempt to stop executing failed tests until they prove to have value again. Please consider re-enabling them provided they are failing due to product bugs or you have an enhancement.
Adding @kabirbhartiRH @gkarager in mention for awareness.
/assign @liangxia
> Stop executing flaky tests, part 2

- features/cli/pod.feature
Fix docker image pull error for OCP-22283
Pass Log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/761133/console 
@xingxingxia PTAL
> Fix docker image pull error for OCP-22283

- lib/rules/web/admin_console/4.10/user_management.xyaml
- lib/rules/web/admin_console/4.11/user_management.xyaml
- lib/rules/web/admin_console/4.12/user_management.xyaml
- lib/rules/web/admin_console/4.13/user_management.xyaml
- lib/rules/web/admin_console/4.14/user_management.xyaml
- lib/rules/web/admin_console/4.8/user_management.xyaml
- lib/rules/web/admin_console/4.9/user_management.xyaml
pass log in https://github.com/openshift/cucushift/pull/9485
> update for ocp-25765

- features/step_definitions/nfd.rb
4.10 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5835/console
4.12 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5837/console
@lenahorsley @liqcui @wabouhamad PTAL
> fix nfd automation to be able to run on 4.12

- lib/webauto/web4cucumber.rb
Added `--headless` and `--disable-extensions` options when starting Chrome
> try to fix chrome crash issue

- features/upgrade/sdn/policy-upgrade.feature
Sorry, this was missed as a part of #3267 
> disable case on hypershift temporarily

- tools/openshift-ci/Dockerfile
[OCPQE-14239](https://issues.redhat.com//browse/OCPQE-14239) fix prow failure and add ansible to verification-test image
/cc @pruan-rht @liangxia @JianLi-RH @jhou1 @shellyyang1989
> fix OCPQE-14239  add ansible to verification-tests image

- features/logging/cluster_log_forwarder.feature
- features/logging/cluster_logging_operator.feature
- features/logging/collector.feature
- features/logging/elasticsearch.feature
- features/logging/elasticsearch_operator.feature
- features/logging/forward_logs_to_external_elasticsearch.feature
- features/logging/logging_acceptance.feature
- features/step_definitions/logging.rb
- features/support/clusterlogging_env.rb
- features/upgrade/logging/upgrade_with_clf.feature
- testdata/logging/clusterlogforwarder/kafka/amq/04_kafka_my-cluster_amqstreams_template.yaml
- testdata/logging/clusterlogforwarder/kafka/amq/05_kafkatopics_amqstreams.yaml
- testdata/logging/clusterlogforwarder/multiple_receiver/clusterlogforwarder.yaml
- testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_invalid_values.yaml
- testdata/logging/clusterlogging/5.7/cl-storage-with-im-template.yaml
- testdata/logging/clusterlogging/5.7/cl_fluentd-buffer.yaml
- testdata/logging/clusterlogging/5.7/cl_fluentd-buffer_Invalid.yaml
- testdata/logging/clusterlogging/5.7/cl_fluentd-buffer_default.yaml
- testdata/logging/clusterlogging/5.7/clusterlogging-storage-template.yaml
- testdata/logging/clusterlogging/5.7/example_indexmanagement.yaml
- testdata/logging/clusterlogging/5.7/example_unmanaged.yaml
- testdata/logging/clusterlogging/5.7/fluentd_only.yaml
- testdata/logging/clusterlogging/5.7/index_management_test.yaml
- testdata/logging/clusterlogging/5.7/scalebase.yaml
Fix failures in logging 5.7
/cc @anpingli @IshwarKanse
> fix failures in logging 5.7

- features/networking/multus.feature
- features/networking/pod.feature
- features/step_definitions/networking.rb
due to this bug https://issues.redhat.com/browse/OCPBUGS-10321
Here add a workaround for those cases which using debug pods and run `ip` command
> add a workaround for ip command due to bug 10321

- lib/rules/web/admin_console/4.9/clustersettings.xyaml
pass log Runner/776871/console
> fix doc url for 4.9

- features/logging/logging_acceptance.feature
Update logging acceptance case:
1. remove steps to check logging dashboards in OCP console
2. remove steps to check index management jobs. 
Log: https://url.corp.redhat.com/a5a2bc5
> Update acceptance case

- Gemfile
- lib/launchers/amz.rb
- tools/launch_instance.rb
copy over changes for launcher.rb and amz.rb from `master` branch to `v3` branch https://redhat-internal.slack.com/archives/CPJQCSN49/p1680771064451389.
Install log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Launch%20Environment%20Flexy/147102/console
Remove log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/any-test-jobs-go-there/job/Remove_VMs_v3/1/console
@jianlinliu  @gpei @liangxia @jhou1  PTAL
> migrate Dynet to use Route53 to commit to v3 branch only

- features/logging/eventrouter.feature
- features/step_definitions/logging.rb
Fix failures in [OCPQE-11339](https://issues.redhat.com//browse/OCPQE-11339) and [OCPQE-5845](https://issues.redhat.com//browse/OCPQE-5845).
/cc @anpingli
> fix OCPQE-11339 and OCPQE-5845

- lib/rules/web/admin_console/4.10/operator_hub.xyaml
Update switch_to_form_view's selector from id to XPath
Pass Log 410: Runner/786626/console
> Fix OCP-28832 automation fail issue in 4.10

- lib/openshift/bare_metal_host_metal3_io.rb
- lib/rules/web/admin_console/4.10/baremetalhost.xyaml
- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.10/dashboards.xyaml
- lib/rules/web/admin_console/4.10/goto.xyaml
- lib/rules/web/admin_console/4.10/tables.xyaml
- lib/rules/web/admin_console/4.11/baremetalhost.xyaml
- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/dashboards.xyaml
- lib/rules/web/admin_console/4.11/goto.xyaml
- lib/rules/web/admin_console/4.11/tables.xyaml
- lib/rules/web/admin_console/4.12/baremetalhost.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/dashboards.xyaml
- lib/rules/web/admin_console/4.12/goto.xyaml
- lib/rules/web/admin_console/4.12/tables.xyaml
- lib/rules/web/admin_console/4.13/baremetalhost.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/dashboards.xyaml
- lib/rules/web/admin_console/4.13/goto.xyaml
- lib/rules/web/admin_console/4.13/tables.xyaml
- lib/rules/web/admin_console/4.14/baremetalhost.xyaml
- lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.14/dashboards.xyaml
- lib/rules/web/admin_console/4.14/goto.xyaml
- lib/rules/web/admin_console/4.14/tables.xyaml
rules for [OCP-62692](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-62692) https://github.com/openshift/cucushift/pull/9524
> auto baremetalhost case

- doc/prow/query_s390x.json
To support IBM folks
/cc @jhou1  @pruan-rht  @JianLi-RH @dis016
> Add query for s390x

- lib/rules/web/admin_console/4.13/dashboards.xyaml
- lib/rules/web/admin_console/4.14/dashboards.xyaml
@yapei @yanpzhan This PR is ready for review, pass log is in cucushift - #9534
> Update OCP-36912 to fix unstable issue

- features/admin/scc.feature
- features/cli/create.feature
- features/storage/nfs.feature
Some tests fail with following error on Power
```
Error from server (Forbidden): violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "hello-openshift" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "hello-openshift" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "hello-openshift" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "hello-openshift" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
cc: @pravin-dsilva
> To add proper privilege to projects

- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
4.14 pass log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/798447/console
> improve auto

- features/step_definitions/logging.rb
To avoid hitting below issue, per https://strimzi.io/docs/operators/in-development/deploying.html#proc-disabling-fips-mode-cluster-operator-str, disable fips mode for amq operator when the cluster has FIPS enabled.
```
status:
conditions:
- lastTransitionTime: "2023-05-09T06:42:27.181325Z"
message: 'java.io.IOException: getPBEAlgorithmParameters failed: PBEWithHmacSHA256AndAES_256
AlgorithmParameters not available'
reason: RuntimeException
status: "True"
type: NotReady
observedGeneration: 1
```
Similar to https://github.com/openshift/openshift-tests-private/pull/9301
/cc @anpingli @IshwarKanse 
Log: https://url.corp.redhat.com/c33dd7d
> disable FIPS_MODE in amq-streams-cluster-operator when FIPS is enabled in the cluster

- features/upgrade/sdn/multus-upgrade.feature
Reverts openshift/verification-tests#3324
> Revert "Remove static users for multus upgrade case"

- features/upgrade/node/node-upgrade.feature
This case can't run on hypershift cluster, so remove hypershift tag
> disable hypershift for OCP-13022

- features/upgrade/storage/upgrade.feature
/cc @duanwei33 @chao007 @Phaow
> OCPQE-15438: Add subteam and case ID info to scenario name for storage

- features/upgrade/storage/upgrade.feature
1. Add @inactive tag to disable OCP-44578 due to fix https://issues.redhat.com/browse/OCPQE-15462
2. Add @storage tag for upgrade case
> Remove OCP-44578 and add storage tag for upgrade case

- lib/rules/web/admin_console/4.12/route.xyaml
This changes will impact OCP-21023,OCP-21004,OCP-21007,OCP-19608,OCP-26170
Pass log for 4.12: /Runner/803619/console
> Backport PR3233 for fail case

- lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
The change will impact cases:
OCP-20748,OCP-25795,OCP-19672,OCP-19532,OCP-19675,OCP-23580,OCP-19653,OCP-24306,OCP-21958,OCP-24342
OCP-23681,OCP-23682,OCP-41964,OCP-25931,OCP-41964
Pass log:
4.14: Runner/808377/
4.13: Runner/808378/
4.12: Runner/808417/
4.11: Runner/808428/
4.10: Runner/808429/
> Fix inspector error found in CI

- lib/rules/web/admin_console/4.10/overview.xyaml
- lib/rules/web/admin_console/4.11/overview.xyaml
- lib/rules/web/admin_console/4.12/overview.xyaml
- lib/rules/web/admin_console/4.13/overview.xyaml
- lib/rules/web/admin_console/4.14/overview.xyaml
Pass log on 4.14: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/807545/console
on 4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/807548/console
> fix for OCP-20984

- features/step_definitions/storage_class.rb
Hi Team,
Kindly PTAL.
Discussion: https://redhat-internal.slack.com/archives/C02221SB07R/p1686315404107699
Logs:
AWS: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/811536/console
GCP: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/811537/console
/assign @chao007 @duanwei33 @Phaow @radeore
> add volumebindingmode

- README.adoc
> Fake, trigger build

- lib/rules/web/admin_console/4.10/baremetalhost.xyaml
- lib/rules/web/admin_console/4.11/baremetalhost.xyaml
- lib/rules/web/admin_console/4.12/baremetalhost.xyaml
- lib/rules/web/admin_console/4.14/baremetalhost.xyaml
> Fix OCP-62692 rules issue

- lib/rules/cli/4.14.yaml
@kasturinarra @liangxia Please help review . thanks
> add oc end option for create deployment

- lib/rules/web/admin_console/4.9/overview.xyaml
Update Rules for OCP-20984 for 4.9
Pass log: /Runner/821561/
> Fix OCP-20984 in 4.9

- lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
Rollback rule to 4.9
Pass log: Runner/821532/
> Fix OCP-27550 in 4.9

- features/upgrade/security_compliance/fips.feature
Logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/821702/console
> fix oc debug errors for OCP-25821

- features/networking/sctp.feature
Move OCP-28759 to go from 4.10
@zhaozhanqi @anuragthehatter  PTAL, thanks!
> move OCP-28759 to go from 4.10

- features/cli/job.feature
@kasturinarra Please help review , thanks .
> add wait time for pod

- features/networking/service.feature
> update url with ipv4 address and ipv6 address

- features/cli/projects.feature
Jira issue [OCPQE-14924](https://issues.redhat.com/browse/OCPQE-14924)
> [OCPQE-14924] remove test OCP-12193 from cucushift moved to ginkgo

- features/logging/kibana.feature
To fix failures in https://issues.redhat.com/browse/OCPQE-16096.
/cc @anpingli
> resolve failures: Failed to create index pattern app (RuntimeError)

- lib/rules/web/admin_console/4.7/dashboards.xyaml
- lib/rules/web/admin_console/4.8/dashboards.xyaml
Pass log for 4.8 in http://pastebin.test.redhat.com/1106493
> fix for ocp-36912

- lib/rules/web/admin_console/4.6/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
Pass log for 4.7: Runner/845603/
Ticket: https://issues.redhat.com/browse/OCPQE-16118
> Update rule for OCP-28832

- lib/rules/web/admin_console/4.6/operator_hub.xyaml
- lib/rules/web/admin_console/4.7/operator_hub.xyaml
- lib/rules/web/admin_console/4.8/operator_hub.xyaml
-   Fix only for OCP 4.6 4.7 4.8
-   Add missed rule create_operand_anzo
-   The rule of switch_to_form_view has been updated in PR#3401
Pass log for OCP4.7: /Runner/846059/
Ticket: https://issues.redhat.com/browse/OCPQE-16121
> Add rule for OCP-33716

- features/networking/metrics.feature
- features/networking/ovn-egress-ip.feature
- features/networking/ovn.feature
- features/step_definitions/networking.rb
@openshift/team-sdn-qe This is for cucshift/verification-tests repo
The changes were done based on same description as in 
https://github.com/openshift/openshift-tests-private/pull/10506
Please help checking you test s any on this repo and report feedback. Thanks
> OVN IC Post merge readiness for cucushift

- features/node/seccomp.feature
Do not help to hunt feature issues, and no requirment link (jira/trello), lower the priority to high. and make it retired
> Retire OCP-32065

- tools/jenkins/slaves/Dockerfile.rhel8
Based on https://developer.chrome.com/blog/chrome-for-testing/#how-can-i-get-chrome-for-testing-binaries
and the version info comes from https://googlechromelabs.github.io/chrome-for-testing/
> OCPQE-16557: [JenkinsCI] Install chrome and chromedriver via npx

- tools/jenkins/slaves/Dockerfile.rhel8
- tools/openshift-ci/Dockerfile
```
08-27 19:40:47.328        [19:40:46] INFO> Launching Chrome
08-27 19:40:47.328        unknown error: cannot find Chrome binary (Selenium::WebDriver::Error::UnknownError)
08-27 19:40:47.328        #0 0x563c71b6be23 <unknown>
08-27 19:40:47.328        #1 0x563c718947a7 <unknown>
08-27 19:40:47.328        #2 0x563c718bd77a <unknown>
08-27 19:40:47.328        #3 0x563c718bca25 <unknown>
08-27 19:40:47.328        #4 0x563c718fcd92 <unknown>
08-27 19:40:47.328        #5 0x563c718fc3af <unknown>
08-27 19:40:47.328        #6 0x563c718f3de3 <unknown>
08-27 19:40:47.328        #7 0x563c718c7a7b <unknown>
08-27 19:40:47.328        #8 0x563c718c881e <unknown>
08-27 19:40:47.328        #9 0x563c71b2d638 <unknown>
08-27 19:40:47.328        #10 0x563c71b31507 <unknown>
08-27 19:40:47.328        #11 …
```
> OCPQE-16557: Add chrome into PATH

- tools/openshift-ci/Dockerfile
Apply the same as in https://github.com/openshift/verification-tests/pull/3414 to Prow CI.
> OCPQE-16557: [ProwCI] Fix chrome and chromedriver

- features/upgrade/api_auth/upgrade.feature
- features/upgrade/build/build-upgrade.feature
- features/upgrade/cloudcredential/upgrade.feature
- features/upgrade/machines/machines.feature
- features/upgrade/monitoring/monitoring-upgrade.feature
- features/upgrade/node/hpa/upgrade.feature
- features/upgrade/node/node-upgrade.feature
- features/upgrade/node/scc.feature
- features/upgrade/routing/upgrade.feature
- features/upgrade/sdn/egress-upgrade.feature
- features/upgrade/sdn/externalIP-upgrade.feature
- features/upgrade/sdn/ipsec-upgrade.feature
- features/upgrade/sdn/multicast-upgrade.feature
- features/upgrade/sdn/multus-upgrade.feature
- features/upgrade/sdn/policy-upgrade.feature
- features/upgrade/sdn/sdn2ovn-migration.feature
- features/upgrade/sdn/service-upgrade.feature
- features/upgrade/security_compliance/fips.feature
- features/upgrade/storage/upgrade.feature
- features/upgrade/web/console-upgrade.feature
- features/upgrade/workloads/descheduler-upgrade.feature
- features/upgrade/workloads/oc-upgrade.feature
- features/upgrade/workloads/scheduler-upgrade.feature
/cc @zhaozhanqi @jhou1 @pruan-rht
> OCPQE-16581: Add tag 4.14 for several upgrade tests

- tools/case_id_splitter.rb
> Add support for ppc64le and s390x

- features/logging/logging_acceptance.feature
To fix failure in [OCPQE-16472](https://issues.redhat.com//browse/OCPQE-16472).
/cc @anpingli
> fix OCPQE-16472

- lib/webauto/web4cucumber.rb
/cc @yanpzhan @XiyunZhao @jhou1 @pruan-rht
> Set default browser_type to chrome

- features/machine/machine_misc.feature
FYI: @prb112 @juliemathew @aleskandro
> Remove ppc64le and s390x tags for vsphere test

- testdata/customscheduler/pod-customscheduler.yaml
- testdata/customscheduler/pod-defaultscheduler.yaml
FYI: @juliemathew @prb112 @aleskandro
> Fix test failures on ppc64le

- features/step_definitions/deployment.rb
@kasturinarra @liangxia could you please help review , thanks
> add more information to debug failed deployment

- features/networking/ovn.feature
- features/networking/pod.feature
> remove 4.14 label for ovn db raft cases since OVN IC

- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/operator_hub.xyaml
pass log on 4.13: http://pastebin.test.redhat.com/1109482
> fix OCP-25931 

- features/step_definitions/deployment.rb
@liangxia So sorry , should be this one. please help review and merge . 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/860609/console
> replace logs by describe

- tools/openshift-ci/Dockerfile
With @yanpzhan's help, finally we've made this working as expected.
The changes have been verified in https://github.com/openshift/release/pull/43575
/cc @yanpzhan @pruan-rht @jhou1 @JianLi-RH @dis016
> Use fixed version of chrome/chromedriver

- tools/jenkins/slaves/Dockerfile.rhel8
The same as https://github.com/openshift/verification-tests/pull/3448, but for Jenkins CI.
> Use fixed version of chrome/chromedriver in Jenkins CI

- features/cli/pod.feature
Fixing Failure caused by below error 
`Error --docker-image has been deprecated, Deprecated `
Execution Result: 
job/Runner/863143/console
> [OCPQE-17037] Fix test failure OCP-22283

- features/machine/machine.feature
test needs to be skipped for platform:None
@sunzhaohua2 @huali9 @dtobolik @jhou1 PTAL when time permits 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/866324/console
> to reduce issues for sno when installed as platform None

- features/networking/isolation.feature
- features/upgrade/node/hpa/upgrade.feature
/cc @JianLi-RH @dis016 @pruan-rht
> Sort version tags

- features/cli/oc_set_deployment_hook.feature
- features/cli/oc_set_probe.feature
@kasturinarra Please help review , thanks .  resolve https://issues.redhat.com/browse/OCPQE-17076
> replace the image tag with digest

- features/cli/deploy.feature
- features/cli/oc_volume.feature
- features/cli/route.feature
- features/cli/serviceaccount.feature
- features/step_definitions/cli.rb
Pass log in Runner/870489/console
> Support import_mode

- features/upgrade/routing/upgrade.feature
add step to ensure LB is provisioned in upgrade with route shards case
@melvinjoseph86 @ShudiLi  please help take a look. Thanks
> add step to ensure LB is provisioned

- lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/operator_hub.xyaml
> fix OCP-29724/OCP-24478

- features/networking/sdn.feature
@anuragthehatter ^^  due to https://issues.redhat.com/browse/OCPBUGS-14465
> remove versions

- testdata/descheduler/kubedescheduler-4.14.yaml
Adding 4.14 test data yaml file for descheduler
> Adding 4.14 test data yaml file

- lib/rules/web/admin_console/4.14/clustersettings.xyaml
- lib/rules/web/admin_console/4.15/clustersettings.xyaml
Update OCP-33125 link_url for ticket https://issues.redhat.com/browse/OCPQE-17847
> Update OCP-33125 link_url

- lib/rules/web/admin_console/4.15/filters.xyaml
- lib/rules/web/admin_console/4.15/operator_hub.xyaml
- lib/rules/web/admin_console/4.15/search.xyaml
pass log on 4.15: job/ocp-common/job/Runner/888483/console  and job/ocp-common/job/Runner/888488/console
@XiyunZhao
> fix ocp-19532 ocp-33053

- lib/rules/web/admin_console/4.15/dashboards.xyaml
Case currently failed with Bug
update the script for automation failure
> Fix OCP-19817 in 4.15

- lib/rules/web/admin_console/4.15/filters.xyaml
pass log on 4.15:job/Runner/888614/
> Update set_filter_strings selector in 4.15

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/node.xyaml
pass log in 4.15: job/Runner/888725/
> Fix OCP-19722 in 4.15

- lib/rules/web/admin_console/4.15/storage.xyaml
- lib/rules/web/admin_console/4.15/user_management.xyaml
Pass log on 4.15: job/Runner/888726/
> Fix OCP-24415,OCP-25762 in 4.15

- lib/rules/web/admin_console/4.15/style.xyaml
pass log on 4.15: /job/Runner/888623/
> Update OCP-36165 in 4.15

- lib/rules/web/admin_console/4.15/deployment.xyaml
- lib/rules/web/admin_console/4.15/goto.xyaml
Pass log in 4.15:/job/Runner/888643/
> Fix OCP-20849 in 4.15

- lib/rules/web/admin_console/4.15/route.xyaml
Pass log in 4.15:job/Runner/888644/
> Fix OCP-26040 in 4.15

- testdata/job/job_with_0_activeDeadlineSeconds.yaml
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/890898/console
> add more wait time for job pod

- lib/rules/web/admin_console/4.15/projects.xyaml
- lib/rules/web/admin_console/4.15/search.xyaml
- lib/rules/web/admin_console/4.16/projects.xyaml
- lib/rules/web/admin_console/4.16/search.xyaml
> Fix OCP-27550 in 4.15&4.16

- lib/rules/web/admin_console/4.15/clustersettings.xyaml
- lib/rules/web/admin_console/4.16/clustersettings.xyaml
Running log: /job/Runner/891849/
Case failed with bug: https://issues.redhat.com/browse/OCPBUGS-22681
> Fix OCP-33125 in 4.15&4.16

- lib/rules/web/admin_console/4.15/filters.xyaml
- lib/rules/web/admin_console/4.15/operator_hub.xyaml
- lib/rules/web/admin_console/4.16/filters.xyaml
- lib/rules/web/admin_console/4.16/operator_hub.xyaml
Pass log on 4.15: ocp-common/job/Runner/891878/console
/assign @XiyunZhao 
/cc @XiyunZhao
> fix  OCP-19608, OCP-26877,OCP-33743

- lib/rules/web/admin_console/4.15/overview.xyaml
- lib/rules/web/admin_console/4.16/overview.xyaml
> Fix OCP-20832 in 4.15&4.16

- lib/rules/web/admin_console/4.15/quota.xyaml
- lib/rules/web/admin_console/4.16/quota.xyaml
> Fix OCP-21958 in 4.15&4.16

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
> fix OCP-25931 in 4.15&4.16

- lib/rules/web/admin_console/4.15/node.xyaml
- lib/rules/web/admin_console/4.16/node.xyaml
> Fix OCP-23044 in 4.15&4.16

- lib/rules/web/admin_console/4.15/dashboards.xyaml
- lib/rules/web/admin_console/4.16/dashboards.xyaml
> Fix OCP-28297 in 4.15&4.16

- lib/rules/web/admin_console/4.15/pods.xyaml
- lib/rules/web/admin_console/4.16/pods.xyaml
> Fix OCP-37526 in 4.15&4.16

- lib/rules/web/admin_console/4.15/operator_hub.xyaml
- lib/rules/web/admin_console/4.16/operator_hub.xyaml
> Fix OCP-27835 in 4.15&4.16

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
> fix OCP-32152 in 4.15&4.16

- lib/rules/web/admin_console/4.15/logs.xyaml
- lib/rules/web/admin_console/4.16/logs.xyaml
> Fix OCP-41601 in 4.15&4.16

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/yaml.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/yaml.xyaml
pass log on 4.15: job/ocp-common/job/Runner/892565 , /job/ocp-common/job/Runner/892596/
/assign @XiyunZhao 
/cc @XiyunZhao
> fix OCP-23967 OCP-24106

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/environments.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/environments.xyaml
pass log on 4.15 job/ocp-common/job/Runner/892564/console
> fix OCP-21245

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/monitoring.xyaml
- lib/rules/web/admin_console/4.15/overview.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/monitoring.xyaml
- lib/rules/web/admin_console/4.16/overview.xyaml
pass log on 4.15: /job/ocp-common/job/Runner/893724/console
> fix ocp-29209

- lib/rules/web/admin_console/4.15/check_links.xyaml
- lib/rules/web/admin_console/4.15/overview.xyaml
- lib/rules/web/admin_console/4.16/check_links.xyaml
- lib/rules/web/admin_console/4.16/overview.xyaml
pass log on 4.15: job/ocp-common/job/Runner/893735/console and /job/ocp-common/job/Runner/893746/console
@XiyunZhao @yapei
> fix ocp-24512 ocp-23609 ocp-25792 

- lib/rules/web/admin_console/4.15/check_links.xyaml
- lib/rules/web/admin_console/4.16/check_links.xyaml
> Fix OCP-29220 in 4.15&4.16

- lib/rules/web/admin_console/4.15/baremetalhost.xyaml
- lib/rules/web/admin_console/4.16/baremetalhost.xyaml
> Fix OCP-62692 in 4.15&4.16

- lib/rules/web/admin_console/4.15/dashboards.xyaml
- lib/rules/web/admin_console/4.16/dashboards.xyaml
> Fix OCP-42205 in 4.15&4.16

- lib/rules/web/admin_console/4.15/logs.xyaml
- lib/rules/web/admin_console/4.16/logs.xyaml
pass log on 4.15 job/ocp-common/job/Runner/894455/console
> fix ocp-41926

- lib/rules/web/admin_console/4.11/catalog.xyaml
pass log in https://github.com/openshift/cucushift/pull/9686
> fix ocp-24223 for 4.11

- features/upgrade/api_auth/OWNERS
- features/upgrade/api_auth/upgrade.feature
> fix OCP-41198 failure tag

- lib/rules/web/admin_console/4.15/dashboards.xyaml
- lib/rules/web/admin_console/4.16/dashboards.xyaml
pass log on 4.15: ocp-common/job/Runner/896328/console
> fix ocp-27586

- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/style.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/style.xyaml
Ticket: https://issues.redhat.com/browse/OCPQE-18888 
Pass log for 4.15: job/Runner/896729/
Pass log for 4.16: job/Runner/896730/
> Update PF class name for style checking

- features/logging/cluster_logging_operator.feature
- features/logging/logging_acceptance.feature
/cc @anpingli @kabirbhartiRH 
Part of https://issues.redhat.com/browse/OCPQE-18959
> try several times when searching data in ES with normal user

- features/logging/logging_acceptance.feature
More context in https://redhat-internal.slack.com/archives/CH76YSYSC/p1705569180819609?thread_ts=1702352801.055539&cid=CH76YSYSC
/cc @anpingli @QiaolingTang @pruan-rht @jhou1
> Mark OCP-37508 as flaky

- features/step_definitions/networking.rb
Also fix else/end indent after elseif
> OCPQE-16741: OVN: fix leader step to use the correct clipboard

- lib/rules/web/admin_console/4.14/monitoring.xyaml
Ticket: https://issues.redhat.com/browse/OCPQE-19130
Pass log:/job/Runner/903502/
> Fix OCP-29209 in 4.14

- features/routing/timeout.feature
to address https://issues.redhat.com/browse/OCPQE-19163
@melvinjoseph86 @ShudiLi PTAL, thanks
> improve OCP-11635 for stability

- features/networking/multus.feature
Add @4.16 @4.15 @4.14 @4.13 @4.12 @4.11 for this test case.
> Execute OCP-33579 in latest release

- tools/openshift-ci/Dockerfile
pass log in container: https://privatebin.corp.redhat.com/?2f2e138e4e33039a#AwjMWB1TCXqvF8ZQBsk2ZZ2zuwX6pNpsMt8Gj1yU2pZP
@liangxia @yapei
> update chrome with new version

- lib/rules/web/admin_console/4.16/clustersettings.xyaml
- lib/rules/web/admin_console/4.16/operator_hub.xyaml
pass log 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/916409/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/916223/console
@yapei
> fix ocp-42949 ocp-33125

- lib/rules/web/admin_console/4.15/operator_hub.xyaml
- lib/rules/web/admin_console/4.16/operator_hub.xyaml
Fix xpath for case OCP-27495
Pass log for 4.16: /job/Runner/916262/
Pass log for 4.15: /job/Runner/917136/
Ticket: https://issues.redhat.com/browse/OCPQE-19859
> Fix rules xpath for case OCP-27495

- lib/openshift/subscription.rb
Pass log for ocp-24478 and ocp-29724 on 4.16: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/918893/console
/assign @yapei 
/cc @yapei @XiyunZhao
> fix subscription nil:NilClass issue

- lib/rules/web/admin_console/4.11/operator_hub.xyaml
pass log on 4.11 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/922362/console
> fix ocp-26029 for 4.11

- lib/rules/web/admin_console/4.15/clustersettings.xyaml
pass log on 4.15 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/922641/console
> fix ocp-33125

- doc/prow/query_level0.json
- features/admin/scheduler.feature
- features/cli/serviceaccount.feature
- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/upgrade/machines/machines.feature
- features/upgrade/monitoring/monitoring-upgrade.feature
- features/upgrade/security_compliance/fips.feature
@pruan-rht @jhou1 @wsun1 @chengzhang1016
> Add level0 tag

- features/networking/metrics.feature
This was skipped in earlier PR https://github.com/openshift/verification-tests/pull/3566
@openshift/team-sdn-qe PTAL. nit change
> limit 37704 until 4.13

- lib/rules/web/admin_console/4.15/style.xyaml
Fix OCP-36156 script issue in OCP-4.15 only
Pass log: job/Runner/938958/
> Fix OCP-36156 script issue

- features/networking/ovn.feature
Context in https://redhat-internal.slack.com/archives/C01UHADN91U/p1713469212238189
> Move OCP-26091 from scenario outline to scenario

- features/storage/csi.feature
- features/storage/csi_resize.feature
Hi Team, 
PTAL when ever get a chance. 
Sub task: https://issues.redhat.com/browse/OCPQE-21267 
cc: @chao007 @duanwei33 @Phaow @radeore
> fix tag location

- lib/rules/web/admin_console/4.12/operator_hub.xyaml
- lib/rules/web/admin_console/4.13/operator_hub.xyaml
- lib/rules/web/admin_console/4.14/operator_hub.xyaml
- lib/rules/web/admin_console/4.15/operator_hub.xyaml
- lib/rules/web/admin_console/4.16/operator_hub.xyaml
Increase time waiting for `Console plugins` section on CSV details to appear
> update rules for OCP-39596

- features/networking/sdn.feature
@anuragthehatter 
Tag the test with '@fdp' for PROW CI workflow
> Add tag for PROW CI workflow

- features/storage/cloud_provider.feature
We'd like to refresh the vefication-tests image to pick up a code change in cucushift repo, to support tests in Prow CI.
> Small change to trigger image refresh

- tools/resource_monitor.rb
our VPC limits is 200 now not 100.  @liangxia @yunjiang29 PTAL.
> update VPC limits value

- features/step_definitions/project.rb
To support https://github.com/openshift/release/pull/51675
> Workaround for wrong oc client version

- features/cli/hpa.feature
Add version tags for OCP-11576
> Add version tags for OCP-11576

- lib/environment.rb
Follow up of https://github.com/openshift/verification-tests/pull/3603
> Fix undefined local variable or method 'env'

- lib/environment.rb
/cc @pruan-rht @JianLi-RH @dis016
> Fix undefined local variable or method 'user'

- features/networking/service.feature
> tag ETP ITP for fdp

- features/networking/multicast.feature
@anuragthehatter PTAL
cc @weliang1
> Update tags for FDP - OVN

- features/step_definitions/cluster_version.rb
- features/test/new_api.feature
- lib/openshift/cluster_version.rb
helper for #3623
example run.
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/7581/console
> added support to get capabilities for clusterversion

- features/networking/multus.feature
> To remove the extra quote

- lib/rules/web/admin_console/4.14/operator_hub.xyaml
pass log on 4.14 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/995690/console
> update 4.14 rule

- lib/rules/web/admin_console/4.12/storage.xyaml
- lib/rules/web/admin_console/4.13/storage.xyaml
- lib/rules/web/admin_console/4.14/storage.xyaml
- lib/rules/web/admin_console/4.15/storage.xyaml
- lib/rules/web/admin_console/4.16/storage.xyaml
- lib/rules/web/admin_console/4.17/storage.xyaml
https://issues.redhat.com/browse/OCPBUGS-29777 changed the behavior how user select `Access Mode` 
hence updating rules to reflect the changes
4.16 pass log Runner/997510/console
4.17 pass log Runner/997520/console
> fix access mode selection

- features/upgrade/sdn/multicast-upgrade.feature
- features/upgrade/sdn/sdn2ovn-migration.feature
@weliang1 @liangxia PTAL, thanks
> remove qeci tag

- lib/rules/web/admin_console/4.12/actions.xyaml
- lib/rules/web/admin_console/4.13/actions.xyaml
- lib/rules/web/admin_console/4.14/actions.xyaml
- lib/rules/web/admin_console/4.15/actions.xyaml
- lib/rules/web/admin_console/4.16/actions.xyaml
- lib/rules/web/admin_console/4.17/actions.xyaml
pass log in https://github.com/openshift/cucushift/pull/9785
> update rules for ocp-19653

- lib/rules/web/admin_console/4.12/baremetalhost.xyaml
- lib/rules/web/admin_console/4.13/baremetalhost.xyaml
- lib/rules/web/admin_console/4.14/baremetalhost.xyaml
- lib/rules/web/admin_console/4.15/baremetalhost.xyaml
- lib/rules/web/admin_console/4.16/baremetalhost.xyaml
- lib/rules/web/admin_console/4.17/baremetalhost.xyaml
fix failure in https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.17-amd64-nightly-baremetalds-ipi-ovn-ipv4-fips-f14-ui/1816416687101054976/artifacts/baremetalds-ipi-ovn-ipv4-fips-f14-ui/cucushift-e2e/build-log.txt 
pass log on 4.17: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1003371/console
> update rule for ocp-62692

- lib/rules/web/admin_console/4.14/operator_hub.xyaml
pass log in 4.14 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1015497/console
> fix rule for 4.14

- features/admin/quota.feature
Fix automation of OCP-10706 & OCP-11927
> Fix automation of OCP-10706 & OCP-11927

- features/cli/hpa.feature
> Add 4.17 tag for OCP-11576

- features/cli/oc_set_probe.feature
to debug https://issues.redhat.com/browse/OCPQE-3204  ;
@kasturinarra   Please help review , thanks
> remove the step for deployment failure

- lib/rules/web/admin_console/4.17/operator_hub.xyaml
Fix OCP-27495 rule issue, and this issue is impact OCP 4.17 only
Pass log on 4.17: job/Runner/1025335/ 
For ticket: https://issues.redhat.com/browse/OCPQE-25280
> Fix OCP-27495 rule issue

- lib/rules/web/admin_console/4.18/monitoring_metrics.xyaml
cherry pick https://github.com/openshift/verification-tests/pull/3652 to 4.18, 4.18 branch is added
> cherry pick verification-tests#3652 to 4.18

- features/networking/service.feature
the case sometimes failed if the worker0 is same with pod located hostip. so here upgrade from worker to master here
cc @asood-rh 
https://issues.redhat.com/browse/OCPQE-25505
> update cases OCP-47087

- lib/rules/web/admin_console/4.17/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.17/goto.xyaml
- lib/rules/web/admin_console/4.17/route.xyaml
- lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.18/goto.xyaml
- lib/rules/web/admin_console/4.18/route.xyaml
> fix route rules

- features/upgrade/web/console-upgrade.feature
- lib/rules/web/admin_console/4.14/dashboards.xyaml
- lib/rules/web/admin_console/4.15/dashboards.xyaml
- lib/rules/web/admin_console/4.16/dashboards.xyaml
- lib/rules/web/admin_console/4.17/dashboards.xyaml
- lib/rules/web/admin_console/4.18/dashboards.xyaml
Add one small upgrade scenario. Since cypress tests are all skipped on vsphere profile the new TC can only be automated in cucushift
> auto OCP-76051

- features/networking/ovn_ipsec.feature
@huiran0826 @liangxia PTAL, thanks
> add tags for ipsec

- lib/rules/web/admin_console/4.13/deployment.xyaml
- lib/rules/web/admin_console/4.14/deployment.xyaml
- lib/rules/web/admin_console/4.15/deployment.xyaml
- lib/rules/web/admin_console/4.16/deployment.xyaml
- lib/rules/web/admin_console/4.17/deployment.xyaml
- lib/rules/web/admin_console/4.18/deployment.xyaml
make sure charts are loaded instead of only checking chart title
> update check_workloads_metrics rules

- lib/rules/web/admin_console/4.17/route.xyaml
- lib/rules/web/admin_console/4.18/route.xyaml
pass log on 4.17: ocp-common/job/Runner/1049214/console
/assign @yapei
/cc @yapei
> fix OCP-26170

- lib/rules/web/admin_console/4.12/route.xyaml
- lib/rules/web/admin_console/4.13/route.xyaml
- lib/rules/web/admin_console/4.14/route.xyaml
- lib/rules/web/admin_console/4.15/route.xyaml
- lib/rules/web/admin_console/4.16/route.xyaml
- lib/rules/web/admin_console/4.17/route.xyaml
- lib/rules/web/admin_console/4.18/route.xyaml
pass log on 4.18: ocp-common/job/Runner/1049567/consoleFull OCP-19608 failed due to bug https://issues.redhat.com/browse/OCPBUGS-43034
pass log on 4.16: ocp-common/job/Runner/1049568/console
pass log on 4.17: ocp-common/job/Runner/1049582/console
/assign @yapei
/cc @yapei
> fix route ca case

- features/machine/autoscaler.feature
- features/machine/machine.feature
- features/machine/machine_healthcheck.feature
- features/machine/machine_misc.feature
Add @mapi @ccm @cas tags so that we can select our cases to run on rebase. @miyadav @huali9 @shellyyang1989
> OCPQE-20701: Add tags to run on rebase

- lib/rules/web/admin_console/4.18/dashboards.xyaml
Update rule for OCP-42205
Currently, there is still a bug in the case, so the pass log cannot be provided
For ticket: https://issues.redhat.com/browse/OCPQE-26281
> update rule for OCP-42205

- README.md
Limit ruby version to ruby 2.7 as that's the version we've verified in the process.
> Limit ruby version to ruby 2.7

- lib/rules/web/admin_console/4.18/check_links.xyaml
pass log on 4.18: job/ocp-common/job/Runner/1056599/console
/assign @yapei
> fix ocp-29200

- lib/rules/web/admin_console/4.18/catalog.xyaml
- lib/rules/web/admin_console/4.18/check_links.xyaml
- lib/rules/web/admin_console/4.18/search.xyaml
pass log on 4.18: ocp-23610 ocp-common/job/Runner/1058400/console
ocp-27601 job/ocp-common/job/Runner/1058466/console
ocp-24512 job/ocp-common/job/Runner/1058506/console
> fix ocp-23610 ocp-27601

- doc/configuration.adoc
We are using chrome-for-testing in UI automation, update the doc to reflect that.
> Update chrome download url

- lib/rules/web/admin_console/4.18/route.xyaml
- lib/rules/web/admin_console/4.18/search.xyaml
pass log on 4.18: /job/ocp-common/job/Runner/1060467/console
@yapei
> fix ocp-27550 ocp-21004

- lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.18/logs.xyaml
Pass log on 4.18: /job/ocp-common/job/Runner/1060369/console
@yapei
> fix ocp-41926 ocp-24306

- features/cli/resources.feature
@kasturinarra Please help review, thanks
> remove 11882 and added code to golang

- features/routing/route.feature
Related to task: https://issues.redhat.com/browse/OCPQE-26166
> remove tags for route whitelist tests due to ginkgo migration OCPQE-26166

- lib/rules/web/admin_console/4.18/dashboards.xyaml
Fix OCP42205 rule in OCP4.18
4.18 pass log: /job/Runner/1063955/
> Fix OCP42205 rule in OCP4.18

- lib/rules/web/admin_console/4.18/customizations.xyaml
- lib/rules/web/admin_console/4.18/idp.xyaml
pass log on 4.18: /job/ocp-common/job/Runner/1064240/console
> fix idp cases

- lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.18/storage.xyaml
pass log on 4.18 job/ocp-common/job/Runner/1064185/console
> fix ocp-21034 ocp-20964

- features/upgrade/node/hpa/upgrade.feature
Fix the format of test case OCP-13016
> Fix OCP-13016

- lib/rules/web/admin_console/4.18/operator_hub.xyaml
Fix OCP-33053 javascript issue
For ticket:https://issues.redhat.com/browse/OCPQE-27131 
Pass log on 4.18: /job/Runner/1070256/
> Fix OCP-33053 javascript issue

- features/machine/machine.feature
@sunzhaohua2 PTAL 
based on our discussion removing tag.
> removed tag for hypershift-hosted, test not valid

- testdata/hpa/hpa_phpex.yaml
update testfile for https://github.com/openshift/cucushift/pull/9851
> update for ocp-19695

- features/upgrade/web/console-upgrade.feature
Add case ID and team name so that we can easily identify test results in ReportPortal
> add team and case ID for better visibility

- testdata/routing/routetimeout/httpbin-pod.json
@melvinjoseph86 @ShudiLi @rhamini3 PTAL, thanks
follow up https://github.com/openshift/release/pull/59287
> Update testdata httpbin image

- testdata/hpa/hpa_phpex.yaml
update testfile for https://github.com/openshift/cucushift/pull/9855
> fix opc-19695

- lib/rules/web/admin_console/4.18/search.xyaml
- lib/rules/web/admin_console/4.19/search.xyaml
Improve pass ratio for ocp-27550, resolve failure recorded in https://issues.redhat.com/browse/OCPQE-26514 
Pass log on 4.18 https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1084963/console
> update rule for ocp-27550

- features/machine/machine.feature
This is already rewrite in golang, golang case id 36489
> update tags as already supported in golang

- features/routing/route.feature
address https://issues.redhat.com/browse/OCPQE-28064
cc @melvinjoseph86 @ShudiLi @rhamini3
> OCPQE-28064 migrate to ginkgo

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/storage.xyaml
fix ocp-24415 failure in issue https://issues.redhat.com/browse/OCPQE-28123
pass log on 4.19: job/ocp-common/job/Runner/1095323/console
> fix ocp-24415 for 4.19

- testdata/routing/routetimeout/httpbin-pod.json
- testdata/routing/test-client-pod.yaml
- testdata/routing/websocket/pod.json
@melvinjoseph86 @ShudiLi @rhamini3 PTAL
follow up https://github.com/openshift/cucushift/pull/9870
> update pod yaml with securityContext

- lib/rules/web/admin_console/4.19/catalog.xyaml
- lib/rules/web/admin_console/4.19/projects.xyaml
pass log on 4.19 
ocp-25931 /ocp-common/job/Runner/1106399/console
ocp-26910 /ocp-common/job/Runner/1106400/console 
fix https://issues.redhat.com/browse/OCPQE-28611
> fix ocp-26910 ocp-25931

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/dashboards.xyaml
Fix OCP-27901 in 4.19 only
Pass log: /job/Runner/1095807/console
For ticket: https://issues.redhat.com/browse/OCPQE-28151
> fix OCP-27901 in 4.19

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
Fix OCP-19672 on 4.19 only
Pass log: /job/Runner/1108796/
For ticket: https://issues.redhat.com/browse/OCPQE-28662
> Fix OCP19672 on 4.19 only

- testdata/routing/abrouting/abtest-websrv1.yaml
- testdata/routing/abrouting/abtest-websrv2.yaml
- testdata/routing/abrouting/abtest-websrv3.yaml
- testdata/routing/abrouting/abtest-websrv4.yaml
- testdata/routing/test-client-pod.yaml
- testdata/routing/web-server-1.yaml
- testdata/routing/web-server-rc.yaml
Follow up https://github.com/openshift/openshift-tests-private/pull/23323
Update to latest image with new certificates.
@melvinjoseph86 @ShudiLi @rhamini3 PTAL, thanks
> update the nginx-alpine image

- lib/rules/web/admin_console/4.19/check_links.xyaml
Fix OCP-29200 on OCP4.19 only, as the xpathis changed on OCP4.19
Pass log: ./job/Runner/1110408/
For ticket: https://issues.redhat.com/browse/OCPQE-28724
> Fix OCP-29200 on OCP4.19 only

- lib/rules/web/admin_console/4.19/style.xyaml
Fix OCP-36165 xpath change on OCP4.19
Pass log: job/Runner/1110576/
For ticket: https://issues.redhat.com/browse/OCPQE-28732
> Fix OCP-36165 xpath change on OCP4.19

- lib/rules/web/admin_console/4.19/status.xyaml
Update Xpath for OCP-21772 on 419
Pass log:/job/Runner/1113504/
> Update Xpath for OCP-21772 on 419

- lib/rules/web/admin_console/4.19/overview.xyaml
Update Xpath for OCP-20932 on 4.19
Pass log: /job/Runner/1113456/
> Update Xpath for OCP-20932 on 4.19

- lib/rules/web/admin_console/4.19/environments.xyaml
Update xpath for OCP-19858 & 19558 & 20183 on 4.19
pass log: /job/Runner/1113455/
job/Runner/1113477/
> Update xpath for OCP-19858 & 19558 & 20183  on 4.19

- lib/rules/web/admin_console/4.19/goto.xyaml
Update xpath for OCP-20849 on 4.19
Pass log: /job/Runner/1113452/
> Update xpath for OCP-20849 on 4.19

- lib/rules/web/admin_console/4.19/style.xyaml
Update Xpath for OCP-24223 on 4.19
Pass log: /job/Runner/1113779/
For ticket: https://issues.redhat.com/browse/OCPQE-28849
> Update Xpath for OCP-24223 on 4.19

- lib/rules/web/admin_console/4.19/catalog.xyaml
- lib/rules/web/admin_console/4.19/operator_hub.xyaml
Paas log on 4.19: job/ocp-common/job/Runner/1113783/console
fix issues:
https://issues.redhat.com/browse/OCPQE-28855
https://issues.redhat.com/browse/OCPQE-28856
> fix ocp-27666 OCP-39596

- lib/rules/web/admin_console/4.19/style.xyaml
Update Xpath for OCP-24307 on 4.19
Pass log: /job/Runner/1113776/
For ticket: https://issues.redhat.com/browse/OCPQE-28847
> Update Xpath for OCP-24307 on 4.19

- lib/rules/web/admin_console/4.19/style.xyaml
Update Xpath for OCP-24305 on 4.19
Pass log: /job/Runner/1113777/
For ticket: https://issues.redhat.com/browse/OCPQE-28848
> Update Xpath for OCP-24305 on 4.19

- lib/rules/web/admin_console/4.19/logs.xyaml
- lib/rules/web/admin_console/4.19/yaml.xyaml
PASS log on 4.19: /job/ocp-common/job/Runner/1113791/console
job/ocp-common/job/Runner/1113792/console
fix issue https://issues.redhat.com/browse/OCPQE-28860
> fix ocp-23967 ocp-20688

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/overview.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1113802/console
job/ocp-common/job/Runner/1113803/console
fix issues:
https://issues.redhat.com/browse/OCPQE-28872
https://issues.redhat.com/browse/OCPQE-28873
https://issues.redhat.com/browse/OCPQE-28874
> fix ocp-23609 ocp-25817 ocp-25793

- lib/rules/web/admin_console/4.19/operator_hub.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1113830/console 
job/ocp-common/job/Runner/1113833/console
https://issues.redhat.com/browse/OCPQE-28887
https://issues.redhat.com/browse/OCPQE-28889
> fix ocp-27495 ocp-33743

- lib/rules/web/admin_console/4.19/user_management.xyaml
Update Xpath for OCP-25765 on 4.19
Pass log: job/Runner/1113817/
For ticket: https://issues.redhat.com/browse/OCPQE-28879
> Update Xpath for OCP-25765 on 4.19

- lib/rules/web/admin_console/4.19/logs.xyaml
Update toggle_log_wraps for OCP-41601 on 4.19
Pass log: job/Runner/1113820/
For ticket: https://issues.redhat.com/browse/OCPQE-28883
> Update toggle_log_wraps for OCP-41601 on 4.19

- lib/rules/web/admin_console/4.19/overview.xyaml
Update Xpath for OCP-25792 on 4.19
Pass log: job/Runner/1113823/
For ticket: https://issues.redhat.com/browse/OCPQE-28885
> Update Xpath for OCP-25792 on 4.19

- lib/rules/web/admin_console/4.19/customizations.xyaml
Update OCP-24316 on 4.19
Pass log: job/Runner/1113835/
for ticket: https://issues.redhat.com/browse/OCPQE-28888
> Update OCP-24316 on 4.19

- lib/rules/web/admin_console/4.19/dashboards.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1114043/console
issue https://issues.redhat.com/browse/OCPQE-28895
> fix ocp-38262

- lib/rules/web/admin_console/4.19/quota.xyaml
issue https://issues.redhat.com/browse/OCPQE-28896
pass log job/ocp-common/job/Runner/1114045/console
> fix ocp-21958

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/operator_hub.xyaml
Fix OCP-28832 on 4.19
Pass log : job/Runner/1114047/
For ticket: https://issues.redhat.com/browse/OCPQE-28901
> Fix OCP-28832 on 4.19

- lib/rules/web/admin_console/4.19/operator_hub.xyaml
Fix OCP-33748 on 4.19
Pass log： job/Runner/1114048/
For ticket: https://issues.redhat.com/browse/OCPQE-28902
> Fix OCP-33748 on 4.19

- lib/rules/web/admin_console/4.19/style.xyaml
Update Xpath for OCP-29799 on 4.19
Re-submit the change on https://github.com/openshift/verification-tests/pull/3771/ to get it merge
> Update Xpath for OCP-29799 on 4.19

- tools/jenkins/slaves/Dockerfile.gpc.rhel9
Add RHEL9 based agents for Jenkins
> OCPQE-28963: Add dockerfile for rhel9 agent

- lib/rules/web/admin_console/4.19/projects.xyaml
Fix OCP-32152 & OCP-27550 on 4.19
Pass log: job/Runner/1114110/
For ticket: https://issues.redhat.com/browse/OCPQE-28964
> Fix OCP-32152 & OCP-27550 on 4.19

- lib/rules/web/admin_console/4.19/check_links.xyaml
Update function for OCP-24016 & OCP-22330
Pass log: job/Runner/1114129/
For ticket: https://issues.redhat.com/browse/OCPQE-28976
> Update function for OCP-24016 & OCP-22330 on 4.19

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1114411/console
https://issues.redhat.com/browse/OCPQE-28986
> fix ocp-33053

- lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
- lib/rules/web/admin_console/base/logout.xyaml
update in https://github.com/openshift/verification-tests/pull/3759 didn't work for z-stream version.
pass log on 4.19 job/ocp-common/job/Runner/1114432/console
> fix ocp-22640

- lib/rules/web/admin_console/4.19/dashboards.xyaml
Jenkins pass log Runner/1114784/console
> fix OCP-27901

- lib/rules/web/admin_console/4.19/deployment.xyaml
- lib/rules/web/admin_console/4.19/overview.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1114793/console
> fix ocp-23609 ocp-19695

- lib/rules/web/admin_console/4.19/clustersettings.xyaml
- lib/rules/web/admin_console/4.19/operator_hub.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1115155/console
> fix ocp-33125 ocp-27495

- lib/rules/web/admin_console/4.19/check_links.xyaml
pass log on 4.19: job/ocp-common/job/Runner/1115160/
> fix ocp-24287

- lib/rules/web/admin_console/4.19/monitoring.xyaml
pass log on 4.19: /job/ocp-common/job/Runner/1115159/console
> OCP-27584 OCP-25816

- lib/rules/web/admin_console/4.19/operator_hub.xyaml
- lib/rules/web/admin_console/4.19/yaml.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1115432/console
> fix ocp-39596 ocp-23967

- lib/rules/web/admin_console/4.19/dashboards.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1115431/console
> fix ocp-27586 ocp-27901

- lib/rules/web/admin_console/4.19/clustersettings.xyaml
- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/dashboards.xyaml
- lib/rules/web/admin_console/4.19/overview.xyaml
- lib/rules/web/admin_console/4.19/route.xyaml
PASS log on 4.19 job/ocp-common/job/Runner/1115445/console
> fix ocp-19608 ocp-23609 ocp-37098

- lib/rules/web/admin_console/4.19/operator_hub.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1115466/console
https://issues.redhat.com/browse/OCPQE-28902
> fix ocp-33748

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1115465/console
> fix ocp-32152 ocp-33716

- features/routing/haproxy-router.feature
Since PR https://github.com/openshift/openshift-tests-private/pull/24545 was merged, removed those test cases from verification-tests repo
@lihongan @melvinjoseph86 @rhamini3 please help review, thanks.
> migrate cookies test cases

- lib/rules/web/admin_console/4.19/catalog.xyaml
- lib/rules/web/admin_console/4.19/clustersettings.xyaml
- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
Fix failure in https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.19-automated-release-gcp-ipi-f999/1919051448763551744/artifacts/gcp-ipi-f999/cucushift-e2e/build-log.txt
pass log on 4.19 job/ocp-common/job/Runner/1115554/console 
job/ocp-common/job/Runner/1115559/console
> fix ocp-33125 ocp-24106

- features/upgrade/machines/machines.feature
> OCPQE-29574: fix no specification for user index 0 in a scenario @users tag

- lib/rules/web/admin_console/4.19/check_links.xyaml
- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
pass log on 4.19: job/ocp-common/job/Runner/1115568/console
job/ocp-common/job/Runner/1115569/console
> fix ocp-24016 ocp-23681 ocp-21034

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/deployment.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1115570/console 
job/ocp-common/job/Runner/1115571/console
> fix ocp-20849 ocp-25762

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/explore.xyaml
- lib/rules/web/admin_console/4.19/goto.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1115590/console
> fix ocp-22308 ocp-24306

- lib/rules/web/admin_console/4.19/catalog.xyaml
pass log 4.19 /job/ocp-common/job/Runner/1115586/console
> fix ocp-23610

- lib/rules/web/admin_console/4.19/check_links.xyaml
- lib/rules/web/admin_console/4.19/operator_hub.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1115762/console
> fix skip guide tour

- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/goto.xyaml
- lib/rules/web/admin_console/4.19/monitoring.xyaml
pass log on 4.19 job/ocp-common/job/Runner/1115765/console
> fix ocp-27584 ocp-26734

- lib/rules/web/admin_console/4.19/customizations.xyaml
- lib/rules/web/admin_console/4.19/storage.xyaml
pass log on 4.19 /job/ocp-common/job/Runner/1115918/console
> fix ocp-20964

- testdata/deployment/deployment1.json
/job/ocp-common/job/Runner/1115926/console
> update test file for ocp-24423

- lib/rules/web/admin_console/4.19/monitoring_metrics.xyaml
fix indent for check_zoom_value
> fix indent for check_zoom_value

- tools/openshift-ci/Dockerfile
To support https://github.com/openshift/release/pull/66323
> Install junit-report-merger

- features/upgrade/routing/upgrade.feature
@melvinjoseph86 @ShudiLi @rhamini3 PTAL, thanks
> disable some NE upgrade cases

- lib/rules/web/admin_console/4.20/check_links.xyaml
- lib/rules/web/admin_console/4.20/idp.xyaml
> fix ocp-23929

- lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.17/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.19/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.20/common_ui_elements.xyaml
On 4.20 the delete icon doesn't have text now.
> fix ocp-21085

- features/upgrade/routing/upgrade.feature
@melvinjoseph86 @ShudiLi @lihongan PTAL
> OCPQE-30174: Remove tags for migrated upgrade tests

- features/networking/multus.feature
- features/networking/ovn.feature
- features/networking/service.feature
please help review the 3 cucushift level0 cases
> add level0 tag to cucushift auto cases

- lib/rules/web/admin_console/4.20/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.20/operator_hub.xyaml
pass log on 4.20 /job/ocp-common/job/Runner/1116273/console
> fix ocp-28832 ocp-27631 ocp-27646

- lib/rules/web/admin_console/4.20/catalog.xyaml
- lib/rules/web/admin_console/4.20/filters.xyaml
> fix ocp-27666

- lib/rules/web/admin_console/4.20/actions.xyaml
- lib/rules/web/admin_console/4.20/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.20/goto.xyaml
- lib/rules/web/admin_console/4.20/storage.xyaml
pass log on 4.20 /ocp-common/job/Runner/1116416/console
> fix OCP-23681

- lib/rules/web/admin_console/4.20/common_ui_elements.xyaml
- lib/rules/web/admin_console/4.20/filters.xyaml
- lib/rules/web/admin_console/4.20/operator_hub.xyaml
- lib/rules/web/admin_console/4.20/secrets.xyaml
track in https://issues.redhat.com/browse/OCPQE-30581 https://issues.redhat.com/browse/OCPQE-30582 https://issues.redhat.com/browse/OCPQE-30583
will paste log soon.
> fix ocp-28832 ocp-19532 ocp-20020

- lib/rules/web/admin_console/4.20/goto.xyaml
- lib/rules/web/admin_console/4.20/operator_hub.xyaml
Pass log on 4.20 /job/ocp-common/job/Runner/1116541/console
track issue: https://issues.redhat.com/browse/OCPQE-30612 https://issues.redhat.com/browse/OCPQE-30613 https://issues.redhat.com/browse/OCPQE-30614
> fix OCP-27590 OCP-27495 OCP-29198
