openshift/verification-tests

testdata/deployment/skopeo-deployment.json

New multiarch image replacement for skopeo, this is required by other test cases. I have raised another PR https://github.com/openshift/cucushift/pull/8852 to test this.

New multiarch image replacement for skopeo

---

features/upgrade/machines/machines.feature

this change should help to not get error , I dont see any issue as with one-label also we can confirm that pod is created successfully 
@jhou1 , @sunzhaohua2 , let me know if any concerns 
trying to fix - https://issues.redhat.com/browse/OCPQE-4934
4.1 - 
```
[miyadav@miyadav ~]$ oc get pods -l cluster-autoscaler=default,k8s-app=cluster-autoscaler
No resources found in openshift-machine-api namespace.
[miyadav@miyadav ~]$ oc get pods -l cluster-autoscaler=default,app=cluster-autoscaler
NAME                                          READY   STATUS    RESTARTS   AGE
cluster-autoscaler-default-5c8c597bfc-wqb75   1/1     Running   0          21m
```
```
4.10
[miyadav@miyadav ManualRun]$ oc get pods -l cluster-autoscaler=default,k8s-app=cluster-autoscaler --kubeconfig 410 
NAME …
```

pod verification fails , because 4.1 had 'app' instead of 'k8s-app' key

---

features/logging/cluster_log_forwarder.feature

Fix failure:
```
11-03 10:41:43.937      And <%= daemon_set("<%= cb.collector_name %>").replica_counters[:desired] %> pods become ready with labels:         # features/step_definitions/pod.rb:134
11-03 10:41:43.937        | logging-infra=<%= cb.collector_name %> |
11-03 10:41:43.937        (eval):1: unterminated string meets end of file
11-03 10:41:43.937        ...mon_set("<%= cb.collector_name 
11-03 10:41:43.937        ...                               ^
11-03 10:41:43.937        (eval):1: syntax error, unexpected end-of-input, expecting ')' (SyntaxError)
11-03 10:41:43.937        /home/jenkins/ws/workspace/ocp-common/Runner/lib/world.rb:492:in `eval'
11-03 10:41:43.937        /home/jenkins/ws/workspace/ocp-common/Runner/lib/world.rb:492:in `block in transform_value'
11-03 10:41:43.937 …
```

fix failure: unterminated string meets end of file ...mon_set("<%= cb.collector_name 

---

testdata/authorization/scc/ocp11207/pod1.json
testdata/authorization/scc/ocp11207/pod2.json

This MR replaces the client-cert image with the new multi-arch image.
Refers [OCPQE-6705](https://issues.redhat.com/browse/OCPQE-6705)
[OCP-11189](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/11/05/05%3A56%3A50/Limit_to_create_pod_to_access_hostPID?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20211105%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20211105T061157Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=de8a6a0940596c3ec461007543fa43236c3ebe366864e8f0506cbaaa6fb5e62d) - limit_to_create_pods
[OCP-11207](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/11/05/05%3A54%3A56/Container_securityContext_should_take_precedence_when_it_conflict_with_PSC?X-Amz-Algorithm=AWS4-HMAC- …

OCPQE-6705: Replaced with multiarch image

---

features/step_definitions/helper_services.rb

This MR replaces the registry image with the new multi-arch one.
Refers OCPQE-5516, [OCPQE-6707](https://issues.redhat.com/browse/OCPQE-6707)
[OCP-12059](http://10.14.89.4:3000/url/generate?key=logs/2021/11/04/10:11:13/Pull_image_with_secrets_from_private_remote_registry_in_the_OpenShift_registry) - devexp
[OCP-38860](http://10.14.89.4:3000/url/generate?key=logs/2021/11/04/10:11:12/Check_oc_image_mirror_with_multi-arch_images_--filter-by-os_not_wildcard) - master

OCPQE-6707: Replacing multiarch registry image

---

features/step_definitions/helper_services.rb

This MR replaces the LDAP image with the new multi-arch one.
Refers [OCPQE-5516](https://issues.redhat.com/browse/OCPQE-5516), [OCPQE-6701](https://issues.redhat.com/browse/OCPQE-6701)
[OCP-10714](http://10.14.89.4:3000/url/generate?key=logs/2021/11/04/07:58:43/Sync_ldap_groups_to_openshift_groups_from_ldap_server-groups_rfc2307_sync-config_yaml_tc5_1664604480) - security
[OCP-10794](http://10.14.89.4:3000/url/generate?key=logs/2021/11/04/08:13:41/Failed_sync_group_should_prompt_tolerate_errors_when_tolarate_errors_flag_is_true) - security
[OCP-11244](http://10.14.89.4:3000/url/generate?key=logs/2021/11/04/07:58:43/Sync_ldap_group_to_openshift_group_with_paging_from_ldap_server) - security …

OCPQE-6701: new multiarch image for ldap helper service

---

features/upgrade/sdn/policy-upgrade.feature

Found ```nodeport-upgrade``` namespace already exist in other feature so better aligning this usecase to ```conntrack-upgrade``` namespace. Found its causing conflict. Just a quick fix. @pruan-rht Can you help merging it quick is possible? Thanks

namespace fix in upgrade case

---

features/step_definitions/helper_services.rb

Testcases ran:
[OCP-11189](http://10.14.89.4:3000/url/generate?key=logs/2021/11/05/16:29:04/Limit_to_create_pod_to_access_hostPID) - security
[OCP-11564](http://10.14.89.4:3000/url/generate?key=logs/2021/11/05/20:37:06/oc_exec_rsh_and_port-forward_should_work_behind_authenticated_proxy-oc) - master
[OCP-14476](http://10.14.89.4:3000/url/generate?key=logs/2021/11/05/14:06:03/Redact_proxy_users_and_passwords_in_build_logs) - buildapi
[OCP-21060](http://10.14.89.4:3000/url/generate?key=logs/2021/11/05/20:37:04/oc_exec_rsh_and_port-forward_should_work_behind_authenticated_proxy-kubectl) - master

OCPQE-6702: Replacing squid-proxy with multiarch one

---

lib/bushslicer.rb
lib/environment.rb

Fix issue in https://coreos.slack.com/archives/C01UHADN91U/p1636349302059500

Length limit of EXECUTOR_NAME as we have 63 chars limit for project name in OCP

---

features/step_definitions/file.rb
features/upgrade/machines/machines.feature

@jhou1  @huali9 @sunzhaohua2 PTAL , when possible , the test works fine , but some times unable to get values for split2 , I have debugged but couldn't figured out , why is that happening sometimes .
This is created for - https://url.corp.redhat.com/internal
```
I1103 14:45:10.175436       1 machine_webhook.go:589] Validating AWS providerSpec
I1103 14:45:11.227074       1 machine_webhook.go:490] Validate webhook called for Machine: miyadav-0311-85g24-master-1
I1103 14:45:11.227095       1 machine_webhook.go:589] Validating AWS providerSpec
I1103 14:45:12.141879       1 machine_webhook.go:490] Validate webhook called for Machine: miyadav-0311-85g24-master-2
I1103 14:45:12.141902       1 machine_webhook.go:589] Validating AWS providerSpec
I1103 14:48:30.984960       1 …
```

upgrade auto test - OCP-39845

---

doc/prow/4.10/query_upgrade.json
doc/prow/4.8/query_upgrade.json
doc/prow/4.8/query_upgrade_sanity.json
doc/prow/4.9/query_upgrade.json
doc/prow/4.9/query_upgrade_sanity.json
features/upgrade/api_auth/upgrade.feature
features/upgrade/build/build-upgrade.feature
features/upgrade/cloudcredential/upgrade.feature
features/upgrade/etcd/upgrade.feature
features/upgrade/jenkins/upgrade.feature
features/upgrade/logging/upgrade.feature
features/upgrade/machines/machines.feature
features/upgrade/marketplace/upgrade.feature
features/upgrade/monitoring/monitoring-upgrade.feature
features/upgrade/node/hpa/upgrade.feature
features/upgrade/node/node-upgrade.feature
features/upgrade/node/scc.feature
features/upgrade/olm/upgrade.feature
features/upgrade/routing/upgrade.feature
features/upgrade/samples_operator/upgrade.feature
features/upgrade/sdn/egress-upgrade.feature
features/upgrade/sdn/ipsec-upgrade.feature
features/upgrade/sdn/policy-upgrade.feature
features/upgrade/sdn/service-upgrade.feature
features/upgrade/security_compliance/fips.feature
features/upgrade/storage/upgrade.feature
features/upgrade/web/console-upgrade.feature
features/upgrade/workloads/oc-upgrade.feature
features/upgrade/workloads/scheduler-upgrade.feature

This PR adds 4.8 tag to the upgrade-prepare and ugprade-check for EUS tests.
Also I synced the tags between upgrade-prepare and upgrad-check which could help reduce some test flakes.
@liangxia @JianLi-RH @dis016 @pruan-rht PTAL

Sync upgrade-prepare and upgrade-check tags, and adding 4.8 for eus

---

features/cli/build.feature

- Updating the OCP-11139 Create applications only with multiple db images	
- Removing mongodb reference from the test

removing mongodb reference from the test

---

features/storage/csi_snapshot.feature

Looks like the OCP-27727 is mistakenly copy/paste in https://github.com/openshift/verification-tests/pull/2139
/cc @duanwei33 @chao007 @jhou1 @pruan-rht

Fix OCP-27727

---

testdata/logging/clusterlogging/cl-storage-with-im-template.yaml

To fix https://issues.redhat.com/browse/OCPQE-6808 
The issue is: the curator was deployed, but before checking the job status, we didn't update the schedule of cj/curator. Since  curator is deprecated and we imported index management from logging 4.5, here I removed the curator from clusterlogging. 
/cc @anpingli

remove curator from clusterlogging

---

testdata/templates/ssh-git/ssh-git-dc.yaml

[OCP-10982](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:21/oc_new-app_to_gather_git_creds) - buildapi
[OCP-11479](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:17/Build_from_private_git_repo_with_wrong_auth_method) - buildapi
[OCP-11720](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:14/Build_from_private_git_repo_with_without_ssh_key) - buildapi
[OCP-11896](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:14/Create_new-app_from_private_git_repo_with_ssh_key) - buildapi
[OCP-14264](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:14/Use_build_source_secret_based_on_annotation_on_Secret_--ssh) - buildapi
[OCP-15507](http://10.14.89.4:3000/url/generate?key=logs/2021/11/06/04:20:14/Creates_a_new_application_based_on_th …

OCPQE-6703: ssh-git-server-openshift multiarch

---

testdata/routing/header-test/dc.json

Parallel runner job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/parallel-runner/575/parameters/
Test cases involved:
[OCP-10762](http://10.14.89.4:3000/url/generate?key=logs/2021/11/08/06:52:22/Check_the_header_forward_format) - network_edge
[OCP-11883](http://10.14.89.4:3000/url/generate?key=logs/2021/11/08/06:52:22/Be_able_to_add_more_alias_for_service) - network_edge
[OCP-12122](http://10.14.89.4:3000/url/generate?key=logs/2021/11/08/06:52:20/Alias_will_be_invalid_after_removing_it) - network_edge
[OCP-13254](http://10.14.89.4:3000/url/generate?key=logs/2021/11/08/06:52:21/The_HTTP_X_FORWARDED_FOR_should_be_the_client_IP_for_ELB_env) - network_edge
[OCP-14678](http://10.14.89.4:3000/url/generate?key=logs/2021/11/08/06:52:25/Only_the_host_ …

OCPQE-6704: http-header-test multiarch image

---

features/routing/route.feature
features/step_definitions/helper_services.rb
features/step_definitions/route.rb
testdata/routing/test-client-pod.yaml

The purpose of the PR is to add new test-client-pod that reusing the (nginx-alpine) image that owned by network edge team, and to decouple the hello-sdn image that used by pod-for-ping.
With the PR, we are expecting to reduce/minimize the risk of updating test image that not owned by ourselves. 
No new image is introduced, just copied and updated the step
```
Given /^I have a pod-for-ping in the#{OPT_QUOTED} project$/ do |project_name|
``` 
log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/220045/console
@quarterpin @melvinjoseph86 @ShudiLi  Please help take a look. Thanks,

new test-client-pod for routing testing

---

features/step_definitions/helper_services.rb

According to the [log](https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-openshift-verification-tests-master-ocp-4.10-e2e-vsphere-cucushift-upi/1460033053387657216/build-log.txt) iscsi-target namespace was terminated and recreated, there is a chance the termination did not finish and the creation starts.
From a test perspective, the `iscsi-target` namespace does not need to be deleted after scenario, it serves as a test service to provide PV to pods. The `steps` automatically registers clean up, so using `cli_exec` instead.
@duanwei33 @Phaow PTAL
```
[09:58:24] INFO> Exit Status: 0
[09:58:24] INFO> === End After Scenario: iSCSI block volumeMode support ===
14 steps (14 passed)
1m57.975s
[10:02:52] INFO> Exit Status: 0
[10:02:53] INFO> === End After …
```

iscsi-target namespace should not be deleted after scenario

---

features/storage/csi_snapshot.feature

Looks like the aws_cred could not get from the secret in AWS disconnect cluster with [failed log](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/11/09/09%3A04%3A35/Volume_snapshot_create_and_restore_test-gp2-csi?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20211111%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20211111T002218Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=8d2788a2d9a5cc861140e3ba37617130131ca6e4805b3d7f8d4bde849d336b84) when using the env.iaas[:type] :
`09:31:03 INFO> Shell Commands: oc get secrets aws-creds --output=yaml --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_admin.kubeconfig --namespace=kube-system`
STDERR:
Error from server (NotFound): secrets "aws-creds" not found
[pass …

Fix snapshot cases due to aws_cred issue

---

lib/openshift/secret.rb

/cc @jhou1 @JianLi-RH @dis016 @pruan-rht 
Tested with `features/storage/storage_class.feature:241` on a 4.10 AWS cluster locally, and the secrets info are not show.

Do not show secrets info by default

---

features/step_definitions/descheduler.rb
features/upgrade/workloads/descheduler-upgrade.feature
lib/environment.rb
testdata/descheduler/01_kd-project.yaml
testdata/descheduler/02_kd-og.yaml
testdata/descheduler/kd-sub-template.yaml
testdata/descheduler/kubedescheduler-4.7.yaml
testdata/descheduler/kubedescheduler-4.8.yaml
testdata/descheduler/kubedescheduler-4.9.yaml
testdata/descheduler/operatorgroup.yaml

Adding pre & post upgrade test cases to perform descheduler upgrade. @anpingli as discussed in the meeting today i am adding my questions here.
1) I see the below test only update descheduler operator in production from one version to other, how can i make this test work with nightly builds , stage etc ? Could you please help clarify ? Thanks !!

Auto descheduler upgrade

---

features/step_definitions/route.rb

the test-client-pod image hasn't installed bash command yet but `bash` is required in this step, so revert to pot-for-ping for now.
@liangxia Please take a look. Thanks.
cc @quarterpin @melvinjoseph86 @ShudiLi

update curl in step store an available router IP

---

lib/rest.rb

Previously,
```
[02:52:35] INFO> HTTP GET testuser-43@https://oauth-openshift.apps.***RH***.com/oauth/authorize
[02:52:36] INFO> HTTP GET took 1.117 sec: 302 Found
[02:52:36] INFO> REST get_user for user 'BushSlicer::APIAccessor:@ocp4', base_opts: {:options=>{:api_version=>"v1", :accept=>"application/json", :content_type=>"application/json", :oauth_token=>"sha256~******"}, :base_url=>"https://api.***RH***.com:6443", :headers=>{"Accept"=>"<accept>", "Content-Type"=>"<content_type>", "Authorization"=>"Bearer <oauth_token>"}}, opts: {:username=>"~"}
[02:52:36] INFO> HTTP GET https://api.***RH***.com:6443/apis/user.openshift.io/v1/users/~
[02:52:37] INFO> HTTP GET took 1.042 sec: 200 OK | application/json 503 bytes
[02:52:37] INFO> cleaning-up user testuser-43 projects
[02:52:37] INFO> Shell …
```

OCPQE-7067: Move token info from INFO to DEBUG level in logger

---

lib/local_process.rb

Previously,
```
[02:52:40] INFO> Exit Status: 0
[02:52:40] INFO> Shell Commands: oc login --token=sha256\~****** --server=https://api.***RH***.com:6443 --kubeconfig=/home/jenkins/ws/workspace/Runner-v3-smoke/workdir/ocp4_testuser-43.kubeconfig --insecure-skip-tls-verify=true
Logged into "https://api.***RH***.com:6443" as "testuser-43" using the token provided.
You don't have any projects. You can try to create a new project, by running
oc new-project <projectname>
```
Now,
```
[03:17:16] INFO> Exit Status: 0
Logged into "https://api.***RH***.com:6443" as "testuser-43" using the token provided.
You don't have any projects. You can try to create a new project, by running
oc new-project <projectname>
```

Move login info from logger.info to logger.debug

---

lib/launchers/o_c_m_cluster.rb

This new version contains a fix for obtaining api.url
https://github.com/openshift-online/ocm-cli/issues/226

Upgrade ocm-cli default version to 0.1.59

---

testdata/pods/graceful-delete/0.json
testdata/pods/graceful-delete/10.json
testdata/pods/graceful-delete/default.json

This MR replaces the sigcapture image with the new multi-arch image.
Link to Jenkins runner [job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/parallel-runner/1414/). The one failed test case in this runner job should be discarded as it is out of scope.
Refers [OCPQE-6708](https://issues.redhat.com/browse/OCPQE-6708)
[OCP-10705](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/11/18/02%3A47%3A12/Default_termination_grace_period_is_30s_if_it_s_not_set?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20211118%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20211118T192329Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=cb3508582b523c7e6006c1d67464de3b …

OCPQE-6708: Replaced sigcapture with hello-openshift multi-arch extended image

---

lib/cli_executor.rb

When the login failed due to any reason, the login commands are printed out.
```
11-23 06:48:46.953        [06:48:31] INFO> cleaning-up user testuser-20 projects
11-23 06:48:46.953        
11-23 06:48:46.953        [06:48:32] INFO> Exit Status: 0
11-23 06:48:46.953        
11-23 06:48:46.953        STDERR:
11-23 06:48:46.953        error: net/http: TLS handshake timeout
11-23 06:48:46.953        
11-23 06:48:46.953        [06:48:44] INFO> Exit Status: 1
11-23 06:48:46.953        cannot login with command: `oc login --token=sha256\~****** --server=https://api.******.com:6443 --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_testuser-20.kubeconfig --insecure-skip-tls-verify=true` (RuntimeError)
```
/cc @jhou1 @dis016 @JianLi-RH @pruan-rht

OCPQE-7067: Move login info to logger.debug when login failed

---

features/machine/machine_misc.feature
features/storage/csi_snapshot.feature
features/storage/storage_class.feature
lib/log.rb

This will protect sensitive information in logger. The logger format it generates will look like. 
```
apiVersion: v1
data:
azure_client_id: [PROTECTED_DATA]
azure_client_secret: [PROTECTED_DATA]
```

Protect sensitive information from logger

---

lib/local_process.rb

Previously we move all the commands to logger.debug as some of the commands contains sensitive info, https://github.com/openshift/verification-tests/pull/2494

Move specific commands which contains sensitive info to logger.debug

---

lib/log.rb

This fixes, when the `msg` sent to logger is nil. @liangxia @pruan-rht @anpingli @QiaolingTang PTAL
```
[14:15:41] INFO> 1 iterations for 2 sec, returned 6 pods, 6 matching
undefined method `split' for nil:NilClass (NoMethodError)
/home/anli/cucushift-runtime2/verification-tests/lib/log.rb:189:in `censor'
/home/anli/cucushift-runtime2/verification-tests/lib/log.rb:118:in `log'
/home/anli/cucushift-runtime2/verification-tests/lib/log.rb:131:in `info'
```

Fix NoMethodError in censor

---

lib/log.rb

/cc @jhou1 @dis016 @JianLi-RH @pruan-rht 
Test log,
```
And I run the :get client command with: # features/step_definitions/cli.rb:13
| resource | secrets |
[02:37:45] INFO> Shell Commands: oc get secrets --kubeconfig=/home/lxia/workdir/lxiabox-lxiax/ocp4_testuser-43.kubeconfig
NAME                       TYPE                                  DATA   AGE
builder-dockercfg-rcr8p    kubernetes.io/dockercfg               1      3s
builder-token-kgwq2        kubernetes.io/service-account-token   4      3s
builder-token-rb29r        kubernetes.io/service-account-token   4      3s
default-dockercfg-tkbpm    kubernetes.io/dockercfg               1      3s
default-token-kgvlw        kubernetes.io/service-account-token   4      3s
default-token-pfkql …
```

Update censor's keywords

---

features/upgrade/sdn/policy-upgrade.feature

` wait up to xx seconds for the steps to pass` loop the steps inside it until reach the desired status, or fail due to timeout reached.
While the operation to switch to pseudo admin and switch project only need to do once, so move it out of the loop step.

Optimize OCP-40620

---

lib/log.rb

1. The `data:` part is also contained in `kind: secret`.
2. `data:` mistakenly mask `metadata:`, which mask most of the commands outputs.
/cc @jhou1 @dis016 @JianLi-RH @pruan-rht 
Tried with non-admin and admin to get secrets in yaml/json within user's/openshift-config project, the sensitive info are protected.
```
When I run the :get client command with:                       # features/step_definitions/cli.rb:13
| resource | secret |
| o        | yaml   |
[02:33:07] INFO> Shell Commands: oc get secret -o yaml --kubeconfig=/home/lxia/workdir/lxiabox-lxiax/ocp4_testuser-43.kubeconfig
[02:33:09] INFO> Exit Status: 0
Then the step should succeed                                   # features/step_definitions/common.rb:4
waiting for operation up to …
```

Update keyword for censor

---

lib/local_process.rb

Sometimes we need to hide the CMDs (e.g, `oc login`), sometimes we need to hide the CMDs' output (e.g, `oc get secrets -o yaml`).
/cc @jhou1 @dis016 @JianLi-RH @pruan-rht 
Add several cases which we need to hide the CMDs.
```
11-26 09:34:42.612      When I run the :exec admin command with:                                                               # features/step_definitions/cli.rb:31
11-26 09:34:42.612        | n                | openshift-monitoring                                                                                                                                          |
11-26 09:34:42.612        | pod              | prometheus-k8s-0 …
```

Hide several CMDs which contains sensitive info by default

---

features/step_definitions/logging.rb
testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/http/user_auth_with_transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/6.8/https/user_auth_with_transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/http/user_auth_with_transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth/deployment.yaml
testdata/logging/clusterlogforwarder/elasticsearch/7.12/https/user_auth_with_transport_tls/deployment.yaml
testdata/logging/clusterlogforwarder/fluentd/insecure/configmap.yaml
testdata/logging/clusterlogforwarder/fluentd/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/deployment.yaml
testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_configmap.yaml
testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_deployment.yaml
testdata/logging/clusterlogforwarder/rsyslog/rsyslogserver_svc.yaml
testdata/logging/logforwarding/elasticsearch/insecure/deployment.yaml
testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml
testdata/logging/logforwarding/fluentd/insecure/deployment.yaml
testdata/logging/logforwarding/fluentd/secure/deployment.yaml
testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml
testdata/logging/logforwarding/rsyslog/rsyslogserver_svc.yaml

- support non-privileged mode by modifing the Dockerfile. (Main chmod 755 workdir). The images had been pushed to quay.io/openshift-tests.
- Remove the code about sa and scc
- Replace 514 with 6514 in syslog as the non-privilege user can not bind port <1024.
- The rsyslogserver is still using 514. so no change in CLF.

Remove privileged configuration and support Arm

---

testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml

That is a follow up to https://github.com/openshift/verification-tests/pull/2501.   We forgot to update the port in logforwarding.
Test pass on 4.6
- OCP-28541 - Forward logs via syslog_buffered - ConfigMap
- OCP-27757 - Forward logs to syslog - Configmap
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/239053/console

use port 6514 in OCP-28541

---

lib/local_process.rb

What's the changes in the PR,
1. Add one more CENSOR_CMD `oc rsh`
2. Use regexpr for CMD check
In default/info mode,
```
[01:50:49] INFO> Exit Status: 0
Logged into "https://api.***:6443" as "testuser-43" using the token provided.
```
In debug mode,
```
[01:49:56] INFO> Exit Status: 0
[01:49:56] DEBUG> Shell Commands: oc login --token=sha256\~*** --server=https://api.***:6443 --kubeconfig=/home/lxia/workdir/lxiabox-lxiax/ocp4_testuser-43.kubeconfig --insecure-skip-tls-verify=true
Logged into "https://api.***:6443" as "testuser-43" using the token provided.
```
/cc @jhou1 @xingxingxia @dis016 @JianLi-RH @pruan-rht

Add CENSOR_CMD and use regexp for CMD check

---

features/storage/csi_clone.feature

Add steps to make sure the pvc is in "bound" status before the clone action. 
Also fix [OCPQE-7457](https://issues.redhat.com/browse/OCPQE-7457) to have enough info when it fails.

Enhance OCP-27690

---

lib/rules/web/ocm_console/cluster_detail_access_control_tab.xyaml
testdata/networking/egress-ingress/qos/iperf-rc.json
testdata/networking/egress-ingress/qos/iperf-server.json
testdata/networking/iperf_nodeport_service.json

This MR replaces the iperf3 image with the new multi-arch image.
Link to Jenkins runner [job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/parallel-runner/2115/). The one failed test case in this runner job should be discarded as per the slack conversation with @zhaozhanqi  
Refers [OCPQE-6985](https://issues.redhat.com/browse/OCPQE-6985)
[OCP-10817](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2021/11/24/18%3A05%3A48/Traffic_flow_shouldn_t_be_interrupted_when_master_switches_the_leader_positions?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20211124%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20211124T183438Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X- …

OCPQE-6985: Replaced iperf3 with mcast-pod multi-arch image

---

features/step_definitions/networking.rb

Fix the regex to match
```
Servers:
6e24 (6e24 at ssl:[fd2e:6f44:5dd8::81]:9643) (self) next_index=11214 match_index=11517
90fb (90fb at ssl:[fd2e:6f44:5dd8::68]:9643) next_index=11518 match_index=11517 last msg 350 ms ago
```
match first string in the parens, the everything from the first colon to a colon digit
close-paren sequence

OVN: fix find leader for IPv6

---

features/upgrade/routing/upgrade.feature

After the actual upgrade it is notice from CI run, the test-client-pod is not present in the cluster. So the step is modified to include creation of Hello pod and then executing in it.

modification for recreating hello pod for ping

---

features/cli/secrets.feature
features/step_definitions/helper_services.rb
testdata/image/gitserver/gitserver-ephemeral.yaml
testdata/image/gitserver/gitserver-persistent.yaml

The new gitserver container is based on alpine and doesn't have `/bin/bash`.  Using `/bin/sh` instead.

OCPQE-6968 : gitserver - use sh instead of bash 

---

lib/local_process.rb

@xingxingxia @wangke19 
- Added the regex pattern to CENSOR_CMDS (from /lib/local_process.rb) for excluding sensitive information shown in commands used in api-server test cases.
- In tests , We are calling _oc exec_ command and passing _skopeo_ command definition as an argument . _skopeo_ command contains the --dcreds option followed a username and password. 
See here http://pastebin.test.redhat.com/1013376
- With this PR , we would avoid printing during the test runs and make sure our sensitive info is not exposed.
- Test case execution result against the PR could find here : http://pastebin.test.redhat.com/1013382
- Reference ticket is OCPQE-7094.
Kindly review the change and let me know your feedback. Thanks

Added regex to CENSOR_CMDS to exclude sensitive commands used in api-server test cases.

---

features/cli/status.feature
testdata/cli/standalone-rc.yaml
testdata/rc/idling-echo-server.yaml

test run:[OS-20211208-0703](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=OS-20211208-0703)

OCPQE-6990: replace origin-base with base-alpine

---

features/upgrade/node/node-upgrade.feature

The wait time for this test is 1980s(and it's not enough per the [log here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/24349/rehearse-24349-periodic-ci-openshift-verification-tests-master-ocp-4.10-upgrade-from-stable-4.9-upgrade-verification-tests-openstack-ipi/1468428276362907648/artifacts/upgrade-verification-tests-openstack-ipi/cucushift-upgrade-pre/build-log.txt)), adding this tag to exclude it from common prow jobs and run it in the upcoming long-duration test jobs
@liangxia PTAL

Add long-duration tag

---

features/cli/serviceaccount.feature

Cases involved are: OCP-11494,OCP-11112,OCP-12536,OCP-28016,OCP-12263,OCP-9853,OCP-30394,OCP-30395,OCP-12037,OCP-10719,OCP-21033,OCP-11531
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/246213/console

OCPQE-7692: Replaces hello-openshift:openshift with multiarch

---

testdata/authorization/scc/ocp11762/dc.json

PR to replace mysql-56-centos7 with a multi-arch image for OCP-11762 on ARM
~~https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245578/~~
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245972/

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (admin)

---

testdata/secrets/ocp12281/first-secret-pod.yaml
testdata/secrets/secret-pod-2.yaml

Test cases involved: OCP-12281,OCP-12310
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245934/

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (secret)

---

testdata/quota/ocp11754/pod-request-limit-valid-3.yaml
testdata/quota/ocp11927/pod-request-limit-valid-4.yaml
testdata/quota/ocp12049/pod-request-limit-valid-1.yaml
testdata/quota/ocp12145/pod-request-limit-valid-2.yaml
testdata/quota/ocp12206/pod-request-limit-invalid-3.yaml
testdata/quota/ocp12256/pod-request-limit-invalid-2.yaml
testdata/quota/ocp12292/pod-request-limit-invalid-1.yaml
testdata/quota/pod-besteffort-terminating.yaml
testdata/quota/pod-besteffort.yaml
testdata/quota/pod-completed.yaml
testdata/quota/pod-notterminating.yaml
testdata/quota/pod-terminating.yaml

OCP-11754,OCP-11927,OCP-12049,OCP-12145,OCP-12206,OCP-12256,OCP-12292,OCP-10278,OCP-10801,OCP-11251,OCP-11983,OCP-11348,OCP-10945,OCP-11568,OCP-12086,OCP-11780,OCP-10279,OCP-12080,OCP-11111
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245981/console
OCP-11780 failed, but it is `inactive`.
Some are just replaced with the hello-openshift multiarch image.

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (quota)

---

testdata/descheduler/kubedescheduler-4.9.yaml

KubeDescheduler apiVersion has been changed to v1 so fixing the same.

Fix apiversion for kubedescheduler cluster object

---

features/build/buildlogic.feature
features/build/dockerbuild.feature
features/build/stibuild.feature
features/cli/build.feature
features/test/registry.feature
features/upgrade/build/build-upgrade.feature
testdata/build/application-template-dockerbuild.json
testdata/build/ocp11224/test-buildconfig.json
testdata/build/ocp11474/test-buildconfig-s2i.json
testdata/build/ocp11550/test-buildconfig.json
testdata/build/ruby20rhel7-invalidcontext-docker.json
testdata/build/ruby22rhel7-template-docker.json
testdata/downwardapi/ocp10628/downward-example.yaml
testdata/templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
testdata/templates/ocp11023/build.yaml
testdata/templates/ocp11552/ruby22rhel7-template-docker.json

Information about testing of these changes is reported in Polarshift, testrun OS-20211207-1759.
Some tests fail for reasons that seem to be beyond the changes from this PR

OCPQE-7624: Replaces ruby build images with multiarch one

---

testdata/deployment/Inline-logs.json
testdata/deployment/deployments_nobc_cpulimit.json
testdata/deployment/ocp10725/hook-inheritance-secret-volume.json
testdata/deployment/test-stop-failed-deployment.json

Test cases involved: OCP-11384,OCP-10633,OCP-10725,OCP-11494,OCP-11135,OCP-12133
~~https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245701/console~~
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245973/

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (deployment)

---

testdata/templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
testdata/templates/ocp10033/sample-app-database-dc-resources-large-invalid.json
testdata/templates/ui/application-template-stibuild-without-customize-route.json

Cases involved: 
OCP-10033,OCP-12057,OCP-11897,OCP-12255,OCP-10289,OCP-11518,OCP-21117,OCP-10695,OCP-21118,OCP-10276,OCP-12247,OCP-12131,OCP-9768,OCP-21111,OCP-10592,OCP-15974,OCP-11627
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245923/
OCP-12057: fails both on original code and new one, as per
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245977/

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (templates)

---

testdata/build/application-template-stibuild.json

OCP-12040,OCP-11155,OCP-13683,OCP-11044,OCP-11248,OCP-10798,OCP-11834,OCP-12021,OCP-12642,OCP-21063
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245948/console
*** Failed scenarios ***
- 12-07 12:31:57.511 cucumber -p polarshift -p dir_embedder features/tierN/admin/groups_users.feature:139 # Scenario: Add/remove edit and admin role to the cluster group in one or more projects (OCP-11155)
Re-run at: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245984/console
- 12-07 12:31:57.511 cucumber -p polarshift -p dir_embedder features/tierN/cli/oc_export.feature:87 # Scenario Outline: Export resource as json or yaml format by cli (OCP-21063)
Failed for other reasons (--export is not an …

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (build)

---

features/upgrade/sdn/policy-upgrade.feature

Tested in upgrade path from 4.9->4.10
[
{
"completionTime": "2021-11-24T16:01:44Z",
"image": "registry.ci.openshift.org/ocp/release:4.10.0-0.nightly-2021-11-24-030137",
"startedTime": "2021-11-24T14:50:19Z",
"state": "Completed",
"verified": false,
"version": "4.10.0-0.nightly-2021-11-24-030137"
},
{
"completionTime": "2021-11-24T13:20:40Z",
"image": "registry.ci.openshift.org/ocp/release@sha256:9f143e47e6cf2e880af243ab3e23e0b6db0f75559c1782f9edf911906a50878e",
"startedTime": "2021-11-24T12:52:36Z",
"state": "Completed",
"verified": false,
"version": "4.9.0-0.nightly-2021-11-24-022504"
}
]
Test logs:-
http://file.rdu.redhat.com/~asood/OCP-44978-pre.log
http://file.rdu.redhat.com/~asood/OCP-44978-post.log

Network policy ACL Logging Upgrade test (Networking Quality OKR)

---

features/upgrade/routing/upgrade.feature

Usually the "hello-pod" will be removed after the node rebooting during upgrade, but it might be still running in abnormal scenario, so adding the step to ensure it is deleted in upgrade-prepare then it can be recreated in upgrade-check.
@quarterpin @melvinjoseph86 @ShudiLi please help take a look. thanks.

fix OCP-45955

---

testdata/cli/application-template-stibuild-with-mount-secret.json

This replaces mysql-56-centos7 image with a multiarch one on cli features.
Tests involved are: OCP-15029,OCP-21021,OCP-10673,OCP-21037,OCP-12909,OCP-12911,OCP-12913,OCP-12914,OCP-12983,OCP-12893,OCP-12894,OCP-12896, OCP-11147
They were run in this job:
~~https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245566/~~
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245995/console
OCP-12909 failed but it is inactive.
OCP-15029 and OCP-21021 also fail due to reasons that are beyond this PR, see other results with no changes from this PR in Polarion.

OCPQE-6967: Replaces mysql-56-centos7 image with multiarch one (cli)

---

features/upgrade/api_auth/upgrade.feature

The original command generate too many logs.
```
$ oc get clusterroles.rbac -o yaml | wc
17610   31457  339285
```
/cc @wangke19 @xingxingxia @jhou1

Shorten logs generate by OCP-19470

---

testdata/routing/routetimeout/httpbin-pod-2.json
testdata/routing/routetimeout/httpbin-pod.json

Runners log here:
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/252156/console (The three scenarios failed here are fixed in the next run)
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/252198/console 
- https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/252200/console
They are tracked by testrun OS-20211213-1425 in Polarshift.
cc @quarterpin @lihongan

OCPQE-6709: httpbin multiarch image

---

features/networking/ovn.feature
features/step_definitions/networking.rb

OCP-38132 is inactive
fix variable interpolation, use `#{var}` not `${var}`
```
[15:53:13] INFO> Set the ${custom_hostname} to ovn external_ids successfully.
```
```
[15:57:18] INFO> Set the ovn external_ids to 'master-0-0' successfully.
```

OCP-38132: set inactive and fix variable interpolation

---

features/upgrade/cloudcredential/upgrade.feature

From ocp 4.8, co cloud-credential Upgradeable default False if cco is in Manual mode, added judgment to this scenario.
version 4.1 
job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/254866/console
version 4.10 and cco manual mode
job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/254867/console
version 4.10 and cco non-manual mode
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/254869/console

Fix issue OCPQE-5054

---

features/upgrade/sdn/ipsec-upgrade.feature

This fixes https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24726/rehearse-24726-periodic-ci-openshift-verification-tests-master-stable-4.9-upgrade-from-stable-4.8-upgrade-verification-tests-baremetal-ipi/1471671965688270848 
```
Scenario: Confirm node-node and pod-pod packets are ESP enrypted on IPsec clusters post upgrade
And I use the "ipsec-upgrade" project
Message:
can not switch to project ipsec-upgrade (RuntimeError)
./features/step_definitions/project.rb:118:in `/^I use the "(.+?)" project$/'
features/upgrade/sdn/ipsec-upgrade.feature:75:in `I use the "ipsec-upgrade" project'
```

make sure tags are aligned between prepare and check

---

features/upgrade/routing/upgrade.feature
features/upgrade/sdn/multicast-upgrade.feature
features/upgrade/sdn/sctp-upgrade.feature

This fixes failures from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24763/rehearse-24763-periodic-ci-openshift-verification-tests-master-ocp-4.10-upgrade-from-stable-4.9-upgrade-verification-tests-gcp-upi/1472825528590274560

Sync upgrade tags

---

features/upgrade/sdn/egress-upgrade.feature

Fix the failure in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24848/rehearse-24848-periodic-ci-openshift-verification-tests-master-nightly-4.10-upgrade-from-stable-4.9-upgrade-verification-tests-vsphere-ipi/1473884216667148288
```
Scenario: Check sdn egressip is functional post upgrade
When I use the "sdn-egressip-upgrade1" project
Message:
can not switch to project sdn-egressip-upgrade1 (RuntimeError)
/verification-tests/features/step_definitions/project.rb:118:in `/^I use the "(.+?)" project$/'
features/upgrade/sdn/egress-upgrade.feature:264:in `I use the "sdn-egressip-upgrade1" project'
```
```
$ grep -r -B5 'Check sdn egressip is functional post upgrade' 
features/upgrade/sdn/egress-upgrade.feature-
features/upgrade/sdn/egress-upgrade.feature- …
```

Fix OCP-45349

---

features/storage/csi.feature

The 4.10 nightly after 12-18, we find the the managedFields have changed, so removing this step to temporarily fix automation issue 
http://10.14.89.4:3000/url/generate?key=logs/2021/12/24/06:29:57/Check_CSI_Driver_Operator_installation-pd_csi_storage_gke_io_standard-csi_gcp-pd-csi-driv_0079663997
@Phaow PTAL

temporarily fix automation issue

---

features/upgrade/api_auth/OWNERS
features/upgrade/api_auth/upgrade.feature

@xingxingxia @wangke19 @jmekkatt Raising PR OCP-34223 fix for one time failed error but upgrade success.
Created temporary log and tested - http://pastebin.test.redhat.com/1017715

OCP-34223 fix for one time failed error but upgrade success

---

features/upgrade/sdn/policy-upgrade.feature

OCP-44901 only contains iaas tags for upgrade check, but does not have those tags in upgrade preapre, thus upgrade check failed due to project does not exist. E.g, failure in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/24870/rehearse-24870-periodic-ci-openshift-verification-tests-master-nightly-4.10-upgrade-from-eus-4.8-upgrade-paused/1474297167140098048
```
$ grep -r -B5 'Conntrack rule for UDP traffic should be removed when the pod for NodePort service deleted post upgrade'
features/upgrade/sdn/policy-upgrade.feature-
features/upgrade/sdn/policy-upgrade.feature-  # @author anusaxen@redhat.com
features/upgrade/sdn/policy-upgrade.feature-  @admin
features/upgrade/sdn/policy-upgrade.feature-  @upgrade-prepare …
```

Sync tags between upgrade prepare/check for OCP-44901

---

features/step_definitions/logging.rb

Fix failure:
```
12-30 08:52:24.096          Given external elasticsearch server is deployed with:                                                               # features/step_definitions/logging.rb:965
12-30 08:52:24.096            | version      | 6.8                    |
12-30 08:52:24.096            | scheme       | <scheme>               |
12-30 08:52:24.096            | client_auth  | <client_auth>          |
12-30 08:52:24.096            | project_name | <%= cb.es_proj.name %> |
12-30 08:52:24.096            | secret_name  | pipelinesecret         |
12-30 08:52:24.096        [00:52:13] INFO> Shell Commands: oc project jsf84 --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_testuser-0.kubeconfig
12-30 08:52:24.096        Already on project "jsf84" on server …
```

fix failure: unknown parameter name "CLIENT_AUTH"

---

features/upgrade/workloads/scheduler-upgrade.feature

OCP-34164 only contains iaas tags for upgrade check, but does not have those tags in upgrade prepare, thus upgrade check in Prow failed due to those preparation steps are not executed. 
```
$ grep -r -B8 'Upgrading cluster when using a custom policy for kube-scheduler should work fine'
features/upgrade/workloads/scheduler-upgrade.feature-Feature: scheduler with custom policy upgrade check
features/upgrade/workloads/scheduler-upgrade.feature-  # @author knarra@redhat.com
features/upgrade/workloads/scheduler-upgrade.feature-  @upgrade-prepare
features/upgrade/workloads/scheduler-upgrade.feature-  @admin
features/upgrade/workloads/scheduler-upgrade.feature-  @destructive
features/upgrade/workloads/scheduler-upgrade.feature-  @4.10 @4.9 @4.8 …
```

Sync tags between upgrade prepare/check for OCP-34164

---

features/upgrade/workloads/descheduler-upgrade.feature

OCP-40536 only contains iaas tags for upgrade check, but does not have those tags in upgrade prepare, thus upgrade check in Prow failed due to those preparation steps are not executed.
```
$ grep -r -B8 'upgrade descheduler from 4.x to 4.y'
features/upgrade/workloads/descheduler-upgrade.feature-Feature: Descheduler major upgrade should work fine
features/upgrade/workloads/descheduler-upgrade.feature-  # @author knarra@redhat.com
features/upgrade/workloads/descheduler-upgrade.feature-  @admin
features/upgrade/workloads/descheduler-upgrade.feature-  @upgrade-prepare
features/upgrade/workloads/descheduler-upgrade.feature-  @users=upuser1,upuser2
features/upgrade/workloads/descheduler-upgrade.feature-  @destructive
features/upgrade/workloads/descheduler-upgrade.feature:  Scenario: [upgrade] - …
```

Sync tags between upgrade prepare/check for OCP-40536

---

lib/configuration.rb

When user input "\n" for `BUSHSLICER_CONFIG` ENV, it will failed with the following error:
```
01-04 10:59:56.182  + run_installer template -c private-templates/functionality-testing/aos-4_10/upi-on-aws/versioned-installer -l jialiu59
01-04 10:59:56.182  + ruby tools/launch_instance.rb template -c private-templates/functionality-testing/aos-4_10/upi-on-aws/versioned-installer -l jialiu59
01-04 10:59:56.788  /home/jenkins/ws/workspace/ocp-common/Flexy-install/flexy/lib/collections.rb:108:in `merge': no implicit conversion of false into Hash (TypeError)
01-04 10:59:56.788  	from /home/jenkins/ws/workspace/ocp-common/Flexy-install/flexy/lib/collections.rb:108:in `deep_merge'
01-04 10:59:56.788  	from /home/jenkins/ws/workspace/ocp-common/Flexy-install/flexy/lib/configuration.rb:47:in `block …
```

strip BUSHSLICER_CONFIG inputing

---

features/cli/build.feature
testdata/build/ruby20rhel7-context-docker.json

- OCP-11139: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/270683/console
- OCP-12115: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/270678/console
- OCP-37309: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/270686/console
- OCP-39745: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/270687/console
/hold
Blocked by:
- https://github.com/openshift-qe/content-mirror/pull/1
- https://github.com/openshift-qe/ruby-hello-world-context/pull/9

OCPQE-8067: Fix buildapi test cases

---

lib/launchers/o_c_m_cluster.rb

Sometimes, the metrics are synced after 3 hrs. The bug is reported at
https://issues.redhat.com/browse/OHSS-2640
Some test cases do not require these metrics.
So, we should allow to skip the waiting for them.

Allow to skip waiting for OSD metrics

---

lib/rules/web/admin_console/4.10/dashboards.xyaml

Fix below failure when running case OCP-37508 on OCP 4.10:
```
Given evaluation of `["Elastic Nodes", "Elastic Shards", "Elastic Documents", "Total Index Size on Disk", "Elastic Pending Tasks", "Elastic JVM GC time", "Elastic JVM GC Rate", "Elastic Query/Fetch Latency | Sum", "Elastic Query Rate | Top 5", "CPU", "Elastic JVM Heap Used", "Elasticsearch Disk Usage", "File Descriptors In Use", "FluentD emit count", "FluentD Buffer Availability", "Elastic rx bytes", "Elastic Index Failure Rate", "FluentD Output Error Rate"]` is stored in the :cards clipboard # features/step_definitions/common.rb:128
waiting for operation up to 360 seconds..
Given I wait up to 360 seconds for the steps to pass: …
```

fix logging failure

---

features/machine/machine.feature

@jhou1 @sunzhaohua2 @huali9 , PTAL 
[Output](https://docs.google.com/document/d/13sJ2CDZ6lgvDLjpf4KQMEgRDetubcAXsizOhM4o2Peo/edit?usp=sharing)

cloud-controller-manager should not show empty version(2037680-bz)

---

features/networking/pod.feature
features/step_definitions/networking.rb

sometimes with interval is 1, this transfer is 0.00 Byte.  So here update the interval to 2 to make sure the result more stable. 
```
[06:06:23] INFO> Shell Commands: oc exec iperf-rc-d4nmg  --kubeconfig=/home/zzhao/workdir/dhcp-140-240-zzhaox/ocp4_testuser-22.kubeconfig -n 3pk8p  -i -- sh -c iperf3\ -c\ 10.129.2.195\ -i\ 1\ -t\ 12s
Connecting to host 10.129.2.195, port 5201
[  5] local 10.131.1.138 port 39148 connected to 10.129.2.195 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  2.05 MBytes  17.2 Mbits/sec   48   17.4 KBytes       
[  5]   1.00-2.00   sec   426 KBytes  3.49 Mbits/sec   18   17.4 KBytes       
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec   15   17.4 KBytes       
[  5]   3.00-4.00   sec   487 KBytes  3.99 …
```

update the interval to 2 from 1 to make this more stable

---

features/routing/route.feature

Modified for bug 2030574 console service uses older "service.alpha.openshift.io" for the service serving certificates
4.9.0-0.nightly-2022-01-17-015913:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/281215/
4.10.0-0.nightly-2022-01-18-044014:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/281233/
@lihongan, @quarterpin, @melvinjoseph86 Please review the change of OCP-14059, thanks.

Updated for OCP-14059

---

lib/openshift/horizontal_pod_autoscaler.rb

Fix failure in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-verification-tests-master-nightly-4.10-upgrade-from-stable-4.9-upgrade-verification-tests-aws-ipi/1483343307747627008/artifacts/upgrade-verification-tests-aws-ipi/cucushift-upgrade-check/build-log.txt
```
Given I wait up to 600 seconds for the steps to pass:                     # features/step_definitions/meta_steps.rb:33
"""
Then expression should be true> hpa('resource-cpu').current_replicas(cached: false) > 2
And expression should be true> hpa.current_cpu_utilization_percentage > hpa.target_cpu_utilization_percentage
"""
......
INFO> last 3 messages repeated 4 times
[10:38:09] INFO> Exit Status: 0
comparison of Integer with nil failed (ArgumentError)
(eval):1:in `>' …
```

Fix "comparison of Integer with nil failed"

---

features/upgrade/machines/machines.feature

Fix OCP-43331, as cloud-controller-manager works from 4.9. Now this failed in 4.7 and 4.8. @jhou1 @miyadav @huali9 please help to take a look.
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/282282/console

Fix OCP-43331

---

features/networking/ovn.feature

election timer was 5 seconds, but now is 16 seconds and convergence also depends
on the number of masters. 40 seconds was not enough to converge with a 5 master
cluster, increase wait.
ref:
BZ 1883662 - [sbdb][raft] Tune out of the box timer to be 16sec

OVN Raft: increase wait due to increase in election timer

---

features/networking/metrics.feature

4.10 has introduced two metrics ports for ovnkube-node 9103 and 9105. It has been 9103 so far until 4.9.
This use case is failing on 4.10 due to reason that existing logic is fetching 9105 port as oppose to 9103
Fixing it to make sure it find port corresponding to 'metrics' value in `oc get ep ovn-kubernetes-node -ojson`
Ran on all 4.8,4.9 and 4.10. Thanks
9105 was added an ovn-metrics in 4.10 basically collecting ovn-controller metrics https://github.com/openshift/cluster-network-operator/pull/1236/files#diff-665322f4b107d73e9e1780a1256948e0f85ad2c260c45e7cb635b8b2866ac5bb
Logs: https://privatebin.corp.redhat.com/?82f0ea2fdfeb92c5#7svy6GD45WPE2mJTJQMA4CQ1tVrqZs9SFztosrCLCAjZ

Changing logic to grep ep port for ovnkube-node

---

features/machine/machine.feature

Update OCP-37706 tags @miyadav @huali9 @jhou1 please help to take a look.
baremetal clusteroperator is disabled on all platform in 4.7, 4.8 and 4.9 version and enabled on vsphere and osp in 4.10 version. For 4.10 we have a new test case to cover, refer to https://github.com/openshift/verification-tests/pull/2632

Update OCP-37706 tags

---

features/machine/machine.feature

@jhou1 @huali9 @sunzhaohua2 PTAL , till 4.9 it was supposed to be disabled by default enabled 4.10 onwards on vsp, osp , baremetal
```
`        versions:
- name: operator
version: 4.10.0-0.nightly-2022-01-17-223655
[05:31:42] INFO> Exit Status: 0
Then the expression should be true> cb.co_disabled["status"]=="False"                                                   # features/step_definitions/common.rb:141
[05:31:42] INFO> === After Scenario: Baremetal clusteroperator should be enabled in vsphere and osp ===
[05:31:42] INFO> Shell Commands: rm -r -f -- /home/miyadav/workdir/miyadav-miyadavx
[05:31:43] INFO> Exit Status: 0
[05:31:44] INFO> === End After Scenario: Baremetal clusteroperator should be enabled …
```

baremetal operator to be enabled by default(vsp&osp)

---

features/cli/create.feature
lib/base_helper.rb

```    
error: ImageStream.image.openshift.io "cjx6--vh" is invalid: metadata.name: Invalid value: "cjx6--vh": must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"
```
When use dns952 type to generate string, non-hyphen may be joined together, it will cause application creation failed.
Passed on my local host. @wewang58 Please help review, thanks

Update app name creation

---

lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
lib/rules/web/admin_console/4.10/logs.xyaml
lib/rules/web/admin_console/4.10/operator_hub.xyaml
lib/rules/web/admin_console/4.9/common_ui_elements.xyaml
lib/rules/web/admin_console/4.9/operator_hub.xyaml

OCP-41926 Ability to view past logs when available for pods only(not build logs)
OCP-41601 Ability to wrap log lines in the log viewer using a toggle    
OCP-20688 Check log streaming panel     
Pass log on 4.10: 
job/ocp-common/job/Runner/292423/console
job/ocp-common/job/Runner/292422/console

fix web rules

---

tools/openshift-ci/Dockerfile

https://issues.redhat.com/browse/OCPQE-8472 
verification-tests repo is affected by centos8 EOL. It's temporary fix until we update our base images to stream8. 
/cc @pruan-rht @liangxia @JianLi-RH @jhou1 @jmekkatt

fix for OCPQE-8472

---

features/upgrade/workloads/scheduler-upgrade.feature

One of the upgrade-prepare test case always gets picked up even after marking it 'Not Automated' and removing content from 'AutomationScript' field. As suggested by vadim adding @flaky tag so that test wont be picked up. Having this test case run is causing kube-scheduler upgrades to fail.

Adding flaky tag so that test wont be picked up during prepare

---

features/networking/build.feature

@pruan-rht as discussed, this removes the automation tags for the inactive cases OCP-15731 and OCP-15744 in #2372

Fixes OCP-15731 and OCP-15744, reactivated by #2372

---

lib/launchers/o_c_m_cluster.rb

There is an issue with 0.1.59 which blocks users to log in.

Update ocm-cli default version to 0.1.61

---

testdata/build/ruby20rhel7-context-docker.json

case has been broken since last modification in January.
```
STDERR:
error: error parsing ruby20rhel7-context-docker.json: json: offset 2621: invalid character '}' looking for beginning of object key string
```

case's testdata json was in mal-formatted JSON

---

features/machine/machine.feature
features/step_definitions/machine_set.rb
lib/openshift/machine_set.rb
testdata/cloud/ms-aws/proxy-clusters/ms_default_values.yaml
testdata/cloud/ms-aws/proxy-clusters/ms_tenancy_dedicated.yaml

@pruan-rht , have a look if time permits ..
The clusters which are installed behind proxy , have a slightly different yaml for machineset 
where subnet id can be got using something like 
`x.spec.template.spec.providerSpec.value.subnet.id` whereas for all other clusters configs it is like `x.spec.template.spec.providerSpec.value.subnet.filters` and also the testdata file that we use have list for subnet , whereas it is just key value pair for proxy clusters.
the changes done using this PR will make it work for all profiles where proxy is not used .(It was earlier failing for non-proxy as well) 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/296030/console 
Please provide if any suggestion I could try , basically need condition to modify …

default values to create machineset for clusters 

---

lib/environment.rb

@xingxingxia @wangke19 @gangwgr In recent test case failure analysis (Refer https://issues.redhat.com/browse/OCPQE-8433 - Part B) exposed that , the service project or namespace created by test framework for hosting a debug pod for running node commands were always same for all the tests . This may leads to potential issues like failing the test case execution one after other due to existence of namespace(as described in ticket) especially when the service namespace fails or slow in cleanup, deletion etc. So this PR would help us to pick unique name for service project or namespace.
Jenkins job against the PR -  Runner-v3-smoke/3907/console
Kindly review the same and let me know your feedback. Thanks.

Randomize name of the service project/namespace created by test framework.

---

tools/os_deps/deps.deb

These are needed to run `cucushift` under Debian system.

added libraries for Debian based system

---

features/logging/cluster_log_forwarder.feature
testdata/logging/clusterlogforwarder/kafka/amq/04_kafka_my-cluster_amqstreams_template.yaml

The version 2.7.0 deprecated. Must move to 3.0.0
Test Pass on cluster-logging.5.4.0-59 on OCP 4.10 using https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/309214/console

update the kafka version

---

features/upgrade/routing/upgrade.feature

This is to address the timeout issue to testcase when the curl happens just after the creation of the test client pod

Ocp45955 rework3

---

features/registry/is.feature

https://issues.redhat.com/browse/OCPQE-8323
The build doesn't create due to ruby imagestream not ready, it may caused by sample operator destructive operation.
So update to use a quay image which will reduce dependence on samples operator.

Enhance ocp-16495

---

features/networking/sriov.feature
testdata/networking/sriov/sriovnetworkpolicy/mlx277-netdevice.yaml

small update:
1. expand time since the worker will be reboot when creating vfio-pci type/mlx VF
2. remove rootdevice since the pciaddress maybe change to another when worker reboot
3. update logs with the correct show

update some unstable cases

---

features/upgrade/workloads/scheduler-upgrade.feature

Removing version tags from upgrade-prepare & upgrade-check so that tests does not get executed. When these tests are being executed in an upgrade path which contains 4.10 kube-scheduler always goes to crashLoopBackOff state due to a recent change introduced in 4.10 (Removal of scheduler-policy)

Removing version tags so that test does not get executed

---

lib/openshift/resource.rb

/cc @gangwgr @xingxingxia @jhou1 @dis016 @pruan-rht 
Tested on the same cluster,
Without the changes in this PR,
```
Given operator "kube-apiserver" becomes non-progressing within <%= cb.wait_time %> seconds                        # features/step_definitions/operators.rb:164
[05:10:30] INFO> ......
[05:10:32] INFO> Exit Status: 0
[05:10:52] INFO> Shell Commands: oc get clusteroperators kube-apiserver --output=yaml --kubeconfig=/home/jenkins/workdir/b86a29ab7df1-rootx/ocp4_admin.kubeconfig
STDERR:
The connection to the server api.rgangwar-21de3.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
[05:10:53] INFO> Exit Status: 1
error getting BushSlicer::ClusterOperator 'kube-apiserver' existence: 
STDERR:
The …
```

Retry when server refuse connection during restart on SNO

---

tools/openshift-ci/Dockerfile

CentOS reached its EOL and the `images` prow test is still based on it.
While doing another [PR](https://github.com/openshift/verification-tests/pull/2702), a few errors on these tests occurred (see build logs in the bottom).
This PR is to be merged **after** (**blocked by**) the [cucushift one](https://github.com/openshift/cucushift/pull/9031/files). 
Its scope is twofold: moving from CentOS Stream 8 and refactoring the layers of the built image in CI.
The job should start working fine when the [cucushift PR](https://github.com/openshift/verification-tests/pull/2702) is merged and the [generated cucushift image](https://github.com/openshift/release/blob/cf72ec45499cc4a402803a59117ed0d5a4af52ae/ci-operator/config/openshift/cucushift/openshift-cucushift-master.yaml) promoted, as it is the …

Fix prow ci `images` job

---

Gemfile
lib/launchers/ibmcloud.rb
tools/cloud_usage.rb
tools/instance_summary.rb

example of output
```
+--------------------------------------+--------+--------------+----------+----------+--------+--------------------------+
|                 name                 | uptime | flexy_job_id |   type   | cost ($) | region |       inst_prefix        |
+--------------------------------------+--------+--------------+----------+----------+--------+--------------------------+
| jshu-0223-test2-cbtkc-worker-3-2ktnd | 0.5    | 79021        | bx2-4x16 | 0.1      | eu-gb  | jshu-0223-test2-cbtkc    |
| jshu-0223-test2-cbtkc-worker-2-t8hvj | 0.51   | 79021        | bx2-4x16 | 0.1      | eu-gb  | jshu-0223-test2-cbtkc    |
| jshu-0223-test2-cbtkc-worker-1-pxpg6 | 0.51   | 79021        | bx2-4x16 | 0.1      | eu-gb  | jshu-0223-test2-cbtkc    |
| jshu-0223-test2-cbtkc-master-1 …
```

added ibmcloud support to monitor our IBM cloud daily cluster usage

---

features/step_definitions/oauth.rb
features/step_definitions/operators.rb

Fixing [OCPQE-8730](https://issues.redhat.com/browse/OCPQE-8730).
The failure has 2 parts to fix:
One is:
```
01:15:12 INFO> #### Operator authentication Expected conditions: {"Progressing"=>"True"}
#<RuntimeError: The authentication operator still didn't become {"Progressing"=>"True"} after 180 seconds>
```
It actually had become "Progressing"=>"True". But the poll interval is too big and the transition to False is quick in SNO env. We need use small interval for SNO env.
The other issue is:
```
01:15:12 INFO> Shell Commands: oc replace -f - --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_admin.kubeconfig
oauth.config.openshift.io/cluster replaced
error: You must be logged in to the server (Unauthorized)
01:16:44 ERROR> #<RuntimeError: error getting projects by …
```

Make co/authentication rotation robust in SNO env test

---

features/networking/egress-ip.feature
features/networking/ovn-egress-ip.feature
features/upgrade/sdn/egress-upgrade.feature

Resolve https://issues.redhat.com/browse/OCPQE-8837.
Changes:
1. Add tags @ qeci to cases which need curl ip-echo service as they have dependency to QE CI environment. 
2. Add tags @network-ovnkubernetes to ovn egressip cases.
@liangxia 

Update egressip related tags

---

features/upgrade/sdn/sctp-upgrade.feature
testdata/networking/externalip_pod_upgrade.yaml
testdata/networking/multus-cni/Pods/generic_multus_pod_upgrade.yaml

@openshift/team-sdn-qe ^^ PTAL, thanks
fix two issue. 
1. update hello-sdn image with multiarch 
2. update time to 1600 to load sctp module , due to sometimes 800 seconds is not enough to load sctp module for all workers.  see https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-upgrade/job/upgrade-producer/3461/consoleFull

update hello-sdn image with multiarch image

---

lib/rules/web/admin_console/4.7/status.xyaml

The error message will disappear on page when too many results found on fuzzy query, that's the reason why the case failed. So this changes is to make sure only one result can be found

Fix OCP-21034

---

features/cli/deploy.feature

Increasing the time as i see that the pod is still in terminating state which causes pattern hooks-2 to be found With this fix i am hoping we should not be seeing any more failures with respect to this case.

Fix OCPQE-7477

---

features/cli/deploy.feature

I see that test has failed twice with error below, so adding a step in the code to make sure that pod appears before moving to other step.
"failed to delete deployer/hook pod hooks-1-hook-pre for deployment #1: pods "hooks-1-hook-pre" not found

Fix OCPQE-8520

---

features/upgrade/routing/upgrade.feature

Some of vsphere and bare metal profiles scale up rhel worker nodes in the cluster, to ensure router pods can work on those nodes so this case scales router pods to make them run on all worker nodes.
But ingress often hit unscheduled worker node issue during a upgrade and blocked the upgrade, the PR is trying to mitigate the problem by decreasing the number of router pods. Let's keep an eye on upgrade CI to see if it is helpful for troubleshooting and debugging.
@quarterpin @melvinjoseph86 @ShudiLi Please help take a look. Thanks.

update the replicas of router pods

---

tools/jenkins/slaves/Dockerfile.rhel8

The PR fix/work-around below issue.
Issue 1, stderr: No user exists for uid xxx
```
[](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/347019/console#)[](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/347019/console#)[](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/347019/console#)[](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/347019/console#)03-09 12:16:28.025  [Pipeline] {
03-09 12:16:28.069  [Pipeline] stage
03-09 12:16:28.069  [Pipeline] { (clone repos)
03-09 12:16:28.086  [Pipeline] checkout
03-09 12:16:28.951  The recommended git tool is: NONE
03-09 12:16:33.314  using …
```

OCPQE-8979: Fix RHEL 8 based Jenkins agent image

---

testdata/logging/clusterlogforwarder/fluentd/insecure/deployment.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/deployment.yaml
testdata/logging/logforwarding/fluentd/insecure/deployment.yaml
testdata/logging/logforwarding/fluentd/secure/deployment.yaml

Fix imagepullbackoff issue, for example: [OCPQE-8500](https://issues.redhat.com/browse/OCPQE-8500)
/cc @anpingli

fix OCPQE-8500:  use image digest

---

tools/jenkins/slaves/Dockerfile.rhel8

We run the container with a very large random uid, but it does not have name mapping to it in /etc/passwd.  And the git used in the RHEL 8 image need that.
```
sh-4.2$ id
uid=1002280000 gid=0(root) groups=0(root),1002280000
sh-4.2$ id -un
id: cannot find name for user ID 1002280000
1002280000
```

OCPQE-8979: Fix ID issue

---

features/step_definitions/networking.rb

Before the real multus testing steps running, https://github.com/weliang1/verification-tests/blob/master/features/step_definitions/networking.rb#L605 will check the numbers of desired_multus_replicas , available_multus_replicas and env.nodes.count,  if the conditions are not met, the script will exit with status: 0 and log " Multus is not running correctly!"
The previous running scripts(not multus cases) or other reasons May cause cluster in this bad state. Update the script to give 120 seconds for continue checking multus status before exiting the testing.

Wait for 120 seconds for checking multus status

---

features/machine/machine.feature

@jhou1  @huali9  @sunzhaohua2  PTAL . Disconnect clusters taking more time for machine to move to `Running` status
Validation result - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/331839/console
In response to  - https://issues.redhat.com/browse/OCPQE-6298 
change to polarion also needed for making `Disconnect as No` for the similar test. [37132 - reported in Jira]

Increase wait time for disconnected clusters

---

features/networking/ovn.feature

increase threshold until we only fail when there is a real error
In this case jitter was 3.26201295671534

OCP-26139: increase jitter threshold

---

features/networking/ovn_ipsec.feature
features/step_definitions/networking.rb
features/upgrade/sdn/ipsec-upgrade.feature

This scenario is observing frequent failures and it took some time to diagnose on various platforms.
Socat sendto opens a raw IP socket and sends an IP packet of length less than 40 bytes at the receiver. various link level headers etc are added to that increasing its packet length. ESP traffic have been checked on OVN br-ex  interface and the packet length at such link layer might varies depending on platforms and MTUs. tcpdumps/pcaps experiments revealed that keeping size less than 1500 is able to catch such packets in these tests across all the platforms.
In short link layer modified the size of packet as per platforms and MTUs in picture. Hence changing tcpdump command to be able to successfully capture such packets.
Also this scenario is being running most of time in non-ipsec …

changing packet size  to accommodate various platforms

---

features/upgrade/api_auth/upgrade.feature

Failures: [OCPQE-8683](https://issues.redhat.com/browse/OCPQE-8683)
For originally reported failure in its "Description", reason is auto execution of steps is fast, need add waiting.
For another failure in its later comment, reason is upgrade framework does not ensure post-upgrade job uses the same test user as the pre-upgrade job.
Pass log:
Pre-upgrade: ocp-c1 job/Runner/363732/console
Post-upgrade: ocp-c1 job/Runner/363741/console
@y4sht please review, thx!

Fix OCP-41198 upgrade scenarios

---

features/upgrade/logging/upgrade.feature

don't run logging upgrade on baremetal  as the persistent volumes are provided by nfs pod. the nfs pod may be in the bad status. that may make Logging ES can not find the storage and thus can not be terminated.
https://issues.redhat.com/browse/OCPQE-8922

don't run logging upgrade on baremetal  

---

features/step_definitions/logging.rb
lib/openshift/elasticsearch.rb

Fix https://issues.redhat.com/browse/OCPQE-9246
During upgrade, ES pods performs rolling-upgrade, the cluster health status will be `green` temporarily, so checking the cluster health and upgrade status in CR elasticsearch isn't proper. Here change to check the ES cluster health and compare the ready pods in CR elasticsearch and the pods in the logging project. 
/cc @anpingli

fix OCPQE-9246

---

features/upgrade/workloads/scheduler-upgrade.feature

I see that test is not suitable to run with 4.10 & 4.11 also if ci/user tries to upgrade from 4.7->4.10 upgrade will still fail as scheduler cannot be upgraded by having policy configmap set. So skipping the test, i will add other tests with checks to make sure that kube-scheduler pods run fine after upgrade.

Adding @flaky tag so that test gets skipped

---

testdata/logging/clusterlogforwarder/fluentd/insecure/configmap.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/cm-mtls-share.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/cm-mtls.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/cm-serverauth-share.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/cm-serverauth.yaml

When testing forward logs to fluentd with logging 5.4, some infra container logs are stored into app.log, the root cause is we change the source to `/var/log/pods/` in logging 5.4. 
Update the fluentd configuration to fix this issue.

update fluentd configuration

---

features/upgrade/storage/upgrade.feature

To fix https://issues.redhat.com/browse/OCPQE-9371
We have snapshot upgrade with AWS EBS CSI Driver, so disable this one which uses hostpath csi driver
@chao007 @ropatil010 PTAL

disable the snapshot upgrade case which uses hostpath csi driver

---

features/upgrade/monitoring/monitoring-upgrade.feature

Since 4.11 removed Grafana resources, these codes should be removed as well.

update OCP-29797 post upgrade check for grafana change

---

doc/prow/query_network-openshiftsdn.json

In Polarion it is `env_network_backend.KEY:(openshift\-sdn __all__)`, but the `\` show as unknown escape character.
After some testing, found `\` is not needed in the query.

Fix query for network-openshiftsdn

---

lib/webauto/web4cucumber.rb

with this change, chrome browser will be launched with correct args(including --disable-dev-shm-usage, which help reduce crash issue)
```
2022-03-29 09:49:34 INFO Watir Creating Browser instance of chrome with user provided options: {:http_client=>#<Watir::HttpClient:0x0000000005449b20 @open_timeout=180, @read_timeout=600>, :options=>{:browser_name=>"chrome", :accept_insecure_certs=>true, "goog:chromeOptions"=>{:element_scroll_behavior=>1, :args=>["--no-sandbox", "--disable-setuid-sandbox", "--disable-gpu", "--disable-infobars", "--disable-dev-shm-usage"]}}}
```
this also fix several JIRA issues such as https://issues.redhat.com/browse/OCPQE-9095
@yanpzhan @liangxia

fix chrome args

---

features/upgrade/workloads/descheduler-upgrade.feature

With 4.10 there were recent changes to descheduler where the descheduler cluster pod comes up then terminates immediately to start securely, so adding some wait to make sure that test here does not fail.

Add wait so that descheduler cluster pod comes up fine

---

features/networking/service.feature

remove step `Then the step should fail`
since sometimes Exit Status is 0
like 
https://s3.upshift.redhat.com/cucushift-html-logs/logs/2022/04/01/16%3A17%3A19/User_can_expand_the_nodePort_range_by_patch_the_serviceNodePortRange_in_network?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20220402%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20220402T060759Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=33b02ea2d61854cc768300f2e1d2e6c96809a714ff607fb270608431068dd61c

update not stable steps

---

features/upgrade/sdn/egress-upgrade.feature

Resolve issue : https://issues.redhat.com/browse/OCPQE-9596
The prepare case didn't include @network-ovnkubernetes @network-openshiftsdn tags that caused the prepare case not selected and later post case failing. 
/cc @zhaozhanqi  @anuragthehatter @liangxia

Update tags for case OCP-44315

---

features/step_definitions/node.rb
features/upgrade/routing/upgrade.feature
lib/openshift/node.rb

To fix https://issues.redhat.com/browse/OCPQE-9496  since router pods cannot be scheduled to windows worker nodes.
@quarterpin @melvinjoseph86 @ShudiLi  Please help take a look. Thanks.

update OCP-30501 to count the number of linux workers

---

features/networking/ovn.feature
features/step_definitions/networking.rb

BZ 2022144: `sbdb` will CrashLoopBackOff when there is a stale PID file.
Regular `pkill` will send `SIGTERM` which allows the container to cleanup
the pid file somehow in one of the hooks.  To simulate a crash we need
to kill without chance of cleanup and leave a stale PID.
Now that https://github.com/openshift/cluster-network-operator/pull/1256
is merged we can test without breaking the cluster
s/openfolw/openflow/

OVN: use pkill -9 to simulate crash and fix typo

---

features/upgrade/sdn/ipsec-upgrade.feature

Need to add OVNK backend check in ```upgrade-check``` scenario too. This will enable ipsec tests to be skipped on non supported profiles during ```upgrade-check``` as well.
Check step was added in upgrade-prepare in the following PR
Ref:https://github.com/openshift/verification-tests/pull/2751
@zhaozhanqi @liangxia Quick merge. Thanks

skip step to be honored post upgade too

---

testdata/descheduler/kubedescheduler-4.11.yaml

I see that the testdata file for kubedescheduler 4.11 is missing due to which the test is failing, adding the same to resolve the issue.

Add testdata file for kubedescheduler 4.11

---

features/upgrade/sdn/egress-upgrade.feature

Resolve https://issues.redhat.com/browse/OCPQE-9744
Original failure because of get "http/1.1" output but expect "http/1.0", change another content to check.
Test log:
Before upgrade: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4196/console
post upgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4197/console

fix egressfirewall upgrade case

---

features/storage/csi_clone.feature

Cinder CSI Driver is not released in 4.6, so remove it from Polarion and cucushift code.
@jhou1 PTAL

Remove unsupported release for OCP-27617

---

features/registry/registry.feature

Test case OCP-29693 requires post-action to create imageContentSourcePolicy image-policy-aosqe, so it is not suitable to test in Prow CI.
/cc @xiuwang @jhou1 @JianLi-RH @dis016 @pruan-rht

Fix prow ci failure for OCP-29693

---

testdata/networking/egress-ingress/dns-egresspolicy1.json
testdata/networking/egress-ingress/dns-egresspolicy2.json
testdata/networking/egress-ingress/dns-egresspolicy4.json
testdata/networking/egressnetworkpolicy/egressnetworkpolicy_1000.yaml
testdata/networking/egressnetworkpolicy/egressnetworkpolicy_1001.yaml
testdata/networking/egressnetworkpolicy/limit_policy.json

Update apiVersion for kind "EgressNetworkPolicy"  to "network.openshift.io/v1"
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/402709/

Update apiVersion for EgressNetworkPolicy

---

doc/prow/query_amd64.json
doc/prow/query_arm64.json

This is to support [OCPQE-9784](https://issues.redhat.com//browse/OCPQE-9784), which will be used to add tags for amd64/arm64
/cc @aleskandro @YuLi517 @jhou1 @wsun1

OCPQE-9784: Add query for architecture

---

features/networking/pod.feature

sometimes met the following issue (ovs-ofctl show nothing) when run ovs-ofctl command
add timeout to make this stable
```
[36m[33m[09:10:45] INFO> Exit Status: 0[0m[0m
[36m[33m[09:10:46] INFO> Shell Commands: oc exec sdn-2trzc  --kubeconfig=/tmp/dir2/workdir/ocp4_admin.kubeconfig -n openshift-sdn  --container=sdn -i -- ovs-ofctl -O openflow13 dump-flows br0[0m[0m
[36m[0m
[36mSTDERR:[0m
[36mE0123 09:10:47.770081   45172 v2.go:105] read /dev/stdin: resource temporarily unavailable[0m[0m
[36m[33m[09:10:48] INFO> Exit Status: 0[0m[0m
[32mThen the step should [32m[1msucceed[0m[0m[32m[90m                                             # features/step_definitions/common.rb:4[0m[0m
[31mAnd [31m[1mthe[0m[0m[31m output should [31m[1mcontain[0m[0m[31m:[90m …
```

add timout to make case more stable

---

lib/launchers/openstack.rb

This is needed by https://gitlab.cee.redhat.com/aosqe/flexy-templates/-/merge_requests/1149

openstack launcher - add a function to map network id to name

---

features/upgrade/storage/upgrade.feature
features/upgrade/workloads/descheduler-upgrade.feature

The `[]` are special character in regexp, remove them from the scenario name so that  several tools rely on regexp works.
Will sync the scenario name change back to Polarion after PR merge.
/cc @ropatil010 @duanwei33 @kasturinarra @jhou1 @JianLi-RH @dis016 @pruan-rht

Remove special char from Scenario name and sync tags

---

features/upgrade/samples_operator/upgrade.feature

Fixed a bug in the sync-tags script, which previously use `/` for address part in command sed, now replaced with `#`.
Since the scenario line contains multiple `/` which breaks the script, the scenario is missed at previous batch tag sync.
/cc @xiuwang @jhou1 @JianLi-RH @dis016 @pruan-rht

Sync upgrade tags from check to prepare for sample operator

---

testdata/build/ruby20rhel7-template-sti.json

```
Given I obtain test data file "build/ruby20rhel7-template-sti.json"                                                                                # features/step_definitions/file.rb:1
And I process and create "ruby20rhel7-template-sti.json"                                                                                           # features/step_definitions/cli.rb:131
STDERR:
error: failed to read input object (not a Template?): resource mapping not found for name: "ruby-helloworld-sample" namespace: "" from "ruby20rhel7-template-sti.json": no matches for kind "Template" in version "v1"
ensure CRDs are installed first
```
/cc @jitendar-singh @jhou1 @JianLi-RH @dis016 @pruan-rht

OCPQE-9923: Fix apiVersion

---

features/step_definitions/logging.rb
features/test/logging_metrics.feature
features/upgrade/logging/upgrade.feature

This PR:
1. add a step to check remaining CPU and memory on linux worker nodes before deploying logging to avoid hitting issue like:
```
0/8 nodes are available: 2 node(s) didn't match node selector, 3 Insufficient memory, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```
2. log the clusterlogging and elasticsearch status before checking logging pods' status for failure debugging. 
/cc @anpingli

fix OCPQE-9774

---

features/cli/policy.feature
testdata/authorization/scc/PodSecurityPolicyReview.json
testdata/authorization/scc/PodSecurityPolicySubjectReview.json

Failure to be fixed: see [logs here](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2022/04/21/14%3A07%3A34/User_can_know_which_serviceaccount_and_SA_groups_can_create_the_podspec_against_the_curre_1852026995?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20220425%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20220425T031821Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=0863762dc03d1ce31288e688920dbc81eb99a4c0aeda9d07a5375ce7f5a3f98d):
```
resource mapping not found for name: "" namespace: "" from "PodSecurityPolicyReview.json": no matches for kind "PodSecurityPolicyReview" in version "v1"
```
The failures are same category as https://github.com/openshift/cucushift/pull/9106, to avoid duplicate typing, please read the first comment in …

Hot fix for outdated apiVersion in test files for scc-review cases OCP-9552, OCP-9553

---

tools/install_os_deps.sh

Fix the ci/prow/images failure which block auto merge of PRs.
```
Package zlib-1.2.11-18.el8_5.x86_64 is already installed.
Error: 
Problem: package zlib-devel-1.2.11-17.el8.x86_64 requires zlib(x86-64) = 1.2.11-17.el8, but none of the providers can be installed
- cannot install both zlib-1.2.11-17.el8.x86_64 and zlib-1.2.11-18.el8_5.x86_64
- cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

[hotfix] Add --allowerasing and --skip-broken when dnf install

---

features/cli/deploy.feature

Currently i sometimes see that the test fail because shardB or shardA is not available. Adding in some wait time to make sure that test does not fail & also replacing docker_image with image as it has been deprecated.

Adding some wait time so that test case does not fail

---

features/step_definitions/machine.rb

If the env under testing is not IPI or is not in the ready status we expect, skip this test instead of raising an error.
@sunzhaohua2 @miyadav @huali9 PTAL

Skip a scenario if env is not IPI

---

features/build/stibuild.feature
features/images/jenkins.feature

The following cases are marked `@flaky` because nearly 100% of the time they are failing. For proof refer to [this job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci_monitor/job/testcases_analyze/54/console)
/assign @liangxia

Mark build api tests as flaky

---

features/networking/metrics.feature

This is causing failure in recent 4.11 runs as this metric was removed from 4.11. As per checking with dev, this one is really not needed to check in prior releases as well due to low customer importance. So removing this from script. Anyways our script intention is to make sure we are able to curl random metrics and prometheus queries are not broken, which is okay,

removing skipped_nbctl_daemon metric

---

features/networking/egress-ip.feature
features/storage/csi_resize.feature
lib/gherkin_parse.rb

If test case ID suffix with whitespaces, we will get below error when running ` tools/polarshift.rb update-automation`
```
[verification-tests]# tools/polarshift.rb update-automation --no-wait OCP-46637
8: from tools/polarshift.rb:553:in `<main>'
7: from tools/polarshift.rb:270:in `run'
6: from /usr/share/gems/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
5: from /usr/share/gems/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
4: from /usr/share/gems/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
3: from /usr/share/gems/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2: from /usr/share/gems/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
1: from tools/polarshift.rb:64:in `block (2 …
```

Fix RuntimeError "could not find locations for case IDs"

---

features/upgrade/sdn/externalIP-upgrade.feature

Will Resolve ticket https://issues.redhat.com/browse/OCPQE-10087
The case failed after upgrade because it was trying to get the external IP from nodes[0]'s internal IP, however, after upgrades, the nodes[0] might not the same node as before upgrade.
Fixed it by getting externalIP from service directly.
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4397/console

Resolve 10087

---

features/networking/pod.feature

sometimes the output too large cause failed. So here only grep wanted value.

enhance cases

---

Gemfile

parallel_tests/cucumber upgrade from 3.8.1 to 3.10.0 earlier this week, which break parallel testing of cucushift in Prow CI.
```
$ podman images | grep -E '87042656c28d|1df7752c33ba|08eb6b18522c'
registry.ci.openshift.org/ci/verification-tests          latest      08eb6b18522c  29 hours ago  2.2 GB
<none>                                                   <none>      1df7752c33ba  9 days ago    2.18 GB
<none>                                                   <none>      87042656c28d  3 weeks ago   2.12 GB
#####################################################################################################
$ podman run -it --rm 87042656c28d bash
[root@b4c323c5d657 /]# gem list | grep parallel
parallel (1.22.1)
parallel_tests (3.8.1)
[root@b4c323c5d657 /]# parallel_cucumber -n 2 …
```

OCPQE-10360: [hotfix] Use parallel_tests with v3.8.1

---

features/cli/deploy.feature

I see that replacing it with image does not work with versions less than 4.11, so replacing it with app_repo so that it works with all versions of ocp

Replace image with app_repo

---

features/machine/machine_misc.feature
testdata/cloud/misc/nginx-pod.yaml

@jhou1 @sunzhaohua2 @huali9 PTAL . 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/444887/console
Raised this to fix -- https://issues.redhat.com/browse/OCPQE-7384 , we found it many times.

Fix string validation and image location (docker->quay)

---

features/networking/service.feature
features/networking/sgw-lgw-migration.feature
features/step_definitions/networking.rb

- Nodeport cases compatibility with IPv6 single stack (we discussed it on slack last week). This is failing on single stack IPv6
- 30 seconds hard wait added in gateway migration tests (comment added on why)
- A step is added into nodeport scenario to align with https://github.com/openshift/verification-tests/blob/master/features/networking/service.feature#L799. It was added an an improvement post customer bug so keeping aligned in both scenarios

IPv6 improvements for nodeport and hard delay for gw migration

---

features/logging/logging_acceptance.feature
features/step_definitions/logging_metrics.rb

Fix failure:
```
And the expression should be true> cb.index_data['docs.count'] > "0"
no implicit conversion of String into Integer (TypeError)
```

fix OCP-30084

---

lib/iaas/iaas.rb

The BareMetal provider (set when installing through BM IPI) is currently not supported.
This PR set it as for BareMetal UPI installations with `none` as type and no `provider` object. Further changes could be needed after testing is unblocked by this enablement.
Link to a failed case due to the missing provider: http://10.14.89.4:3000/url/generate?key=logs/2022/05/24/23:11:56/OCP-43338_Allow_ETCD_Ciphers_customization

Enable support for BareMetal provider (IPI)

---

features/networking/pod.feature
features/networking/service.feature
features/networking/sgw-lgw-migration.feature
testdata/networking/pod-for-ping-with-hostport.yml

Noticed pod hosport image doesn't had our right sdn image path linked. Fixed that. That is being used in OCP-25294 which only had versions coverage until 4.4, strange. I manually added later versions to that. And verified it works.
Make couple of more nodeport case IPv6/IPv4 compatible with braces logic.
PTAL @openshift/team-sdn-qe 
Logs: https://privatebin.corp.redhat.com/?d68737f2c8635330#HwK5zX8MNmF1vEWYKjd53qGYjonvsxXECFXaP5rV2cb9

IPv6 coverage for couple of more node related cases

---

features/step_definitions/networking.rb
features/upgrade/sdn/externalIP-upgrade.feature

Resovle ticket https://issues.redhat.com/browse/OCPQE-10460 
The issue failed due to PR https://github.com/openshift/verification-tests/pull/2862/files.
In Azure cluster, .status.addresses[0].address is not the IP address, but hostname, that cause the case failing.
```
status:
addresses:
- address: huirwang-0531a-r44mf-master-0
type: Hostname
- address: 10.0.0.6
type: InternalIP
```
Secondly as in PR https://github.com/openshift/verification-tests/pull/2862/files changed the way to get the IP address, no need to get sdn pod, so the test pod index here also changed. 
```
-    step %Q/I run command on the node's sdn pod:/, table("| ip | -4 | route | show | default |")
+   inf_address = admin.cli_exec(:get, resource: "node/#{node_name}", output: "jsonpath={.status.addresses[0].address}")
``` …

fix getting nodes internalIP

---

features/step_definitions/helper_services.rb
testdata/pods/ldapserver.yaml

This PR changes how the ldapserver pod is run, letting an admin user do that. The PR also makes use of a new yaml resource in the testdata folder for future purposes (e.g., if the image can be rebuilt to run in a more restricted context with precise capabilities).
Some of the currently failing test cases run through this branch [here](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/451402/console).

Fixes ldapserver related cases

---

features/networking/sgw-lgw-migration.feature

Arghh...one of those check missed in this use case as well (gw migration)
When externalTrafficPolicy is Local, the host should be able to access the resource from its node_ip:port itself
Same changes went in standalone ETP Local sceanario via https://github.com/openshift/verification-tests/pull/2831
Not a big deal @openshift/team-sdn-qe

ETP=cluster behavior check in gw mode migration as well

---

features/networking/sdn.feature

Seems like this usually fails on platforms having mellanox card as they tend do more unmanaged infs like
```
ens4f0v4: unmanaged "Mellanox MT27800" ethernet (mlx5_core), 8E:A7:7F:D1:D7:2D, hw, mtu 1500 
ens4f0v5: unmanaged "Mellanox MT27800" ethernet (mlx5_core), 46:CD:4A:77:48:CC, hw, mtu 1500 
ens4f0v6: unmanaged "Mellanox MT27800" ethernet (mlx5_core), 0A:1B:D7:23:BF:A4, hw, mtu 1500 
```
We want to make sure veths are unmanaged and 'br-int' `geneve` and `tunnel` too. Changed condition 
to satisfy the test on all platforms

condition check fix for unmanaged infs on OCP

---

features/logging/cluster_logging_operator.feature
testdata/logging/clusterlogging/cl_fluentd-buffer.yaml
testdata/logging/clusterlogging/cl_fluentd-buffer_Invalid.yaml
testdata/logging/clusterlogging/cl_fluentd-buffer_default.yaml

Fix failure:
```
06-07 13:08:37.768      Given the expression should be true> (cb.fluent_conf).include? "flush_mode lazy"      # features/step_definitions/common.rb:141
06-07 13:08:37.769        [05:08:37] INFO> singular expression detected skipping left & right operand eval() ...
06-07 13:08:37.769        expression returned non-positive status: false (RuntimeError)
06-07 13:08:37.769        /home/jenkins/ws/workspace/ocp-common/Runner/features/step_definitions/common.rb:168:in `/^(?:the )?expression should be true> (.+)$/'
06-07 13:08:37.769        features/logging/cluster_logging_operator.feature:271:in `the expression should be true> (cb.fluent_conf).include? "flush_mode lazy"'
```

fix OCP-33894

---

lib/cli_executor.rb
lib/local_process.rb
lib/rules/cli/4.5.yaml

Fix issue PR Link: https://github.com/openshift/cucushift/pull/9174
There is a new command in 4.11 version: oc create token, So a new rule needs to be added to help to fix [OCPQE-10552](https://issues.redhat.com/browse/OCPQE-10552)
Self review is done, please help CR, thanks a lot. @xingxingxia @y4sht 
Test Runner:  **/job/ocp-common/job/Runner/460020/console**
Passed Log:
**06-07 19:50:41.870  1 scenario (1 passed)
06-07 19:50:41.870  24 steps (24 passed)
06-07 19:50:41.870  0m28.816s**

Add a new rule(oc create token) to fix issue in OCPQE-10552

---

features/step_definitions/scc.rb

Fix issue in [OCPQE-9578](https://issues.redhat.com/browse/OCPQE-9578)
Error description
1. When restoring SCC restricted-v2 in 4.11, need to delete uid & resourceVersion
2. `oc create -f` has race condition with the cluster's automatic recreation. so using `oc replace -f`
Local cucumber test log pastebin in 4.11: 1056926
Local cucumber test log pastebin in 4.10: 1056939
self review is done, please help CR, thanks a lot. 
@xingxingxia @y4sht

Fix OCPQE-9578

---

features/step_definitions/networking.rb

Resolve [OCPQE-10621](https://issues.redhat.com//browse/OCPQE-10621)
The case failing in dual-stack cluster because getting the InternalIP would return both IPs in dual-stack cluster.  Fix it by using the first one.
```
[04:28:35] INFO> Shell Commands: oc get node/master-00.newugd-14211.qe.devcluster.openshift.com --output=jsonpath\=\{.status.addresses\[\?\(@.type\=\=\"InternalIP\"\)\].address\} --kubeconfig=/home/jenkins/ws/workspace/ocp-upgrade/upgrade-producer/workdir/ocp4_admin.kubeconfig
06-07 12:28:36.265        147.28.154.109 2604:1380:4642:7e00::f5 
```
Dual-stack test log:
https://privatebin.corp.redhat.com/?dd304cd2159d593a#DfmyZzjdn2Di3MaXM8ESQD1csjVtcdERe6vr62neTHwT
IPv4 Common cluster test log:
https://privatebin.corp.redhat.com/?f1b85d1f8360d1cb#6qGH3fp1apQBmQGR6hJY1xyhZcE4jA …

Resolve OCPQE-10621

---

features/step_definitions/user.rb

Many cases failed at below steps:
```
Given I find a bearer token of the system:serviceaccount:<%= cb.project1 %>:default service account
Given I switch to the system:serviceaccount:<%= cb.project1 %>:default service account
Given I use the "<%= cb.project2 %>" project
#<RuntimeError: no api accessors for user default>
lib/api_accessor_owner.rb:23:in `api_accessor'
```
OCP-10642 [failure link](https://url.corp.redhat.com/dc85832)
OCP-11135 [failure link](https://url.corp.redhat.com/fefdebd)
Reason: in kube 1.24, serviceaccount's YAML does not have a secret-based token any more. We need explicitly create a token when using the serviceaccount.
Pass log: https://url.corp.redhat.com/5ae0e98
@redHatGong @y4sht help review, thx, cc @liangxia

Fix serviceaccount 'RuntimeError: no api accessors for user'

---

features/step_definitions/logging.rb
features/test/logging_metrics.feature

1. Ignore known issues when checking logging pods' logs. 
2. Print all the the error logs when there has error in the logs.
Log: https://url.corp.redhat.com/f88fd24

ignore known issues

---

features/machine/machine_healthcheck.feature

Now failed with error `#<RuntimeError: pattern not found: (?-mix:timeout: Invalid value: ".*": spec.unhealthyConditions.timeout)>` @jhou1 @miyadav @huali9 PTAL
Test result: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/471272/console

Fix OCP-34095

---

features/networking/ovn.feature

replace `vsphere` with a wildcard to support Baremetal
`'{.items[*].status.platformStatus.baremetal.apiServerInternalIP}'`

OCP-46285: fix apiServerInternalIP query for baremetal

---

features/upgrade/api_auth/upgrade.feature

Failure: `  features/upgrade/api_auth/upgrade.feature:239:in `the expression should be true> cluster_operator('kube-apiserver').condition(type: 'Progressing')['status'] == "False"' `
Failure Reason: **irrelevant lines for case**
Fix: remove unneeded lines

fix OCP-29741

---

lib/launchers/amz.rb

This should fix the premature exit for jenkins run when the html file is missing.  @jhou1 @liangxia  @dis016 @JianLi-RH PTAL
```
06-17 08:22:15.869  /home/jenkins/.gem/bundler/ruby/2.7.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_uploader.rb:40:in `size': No such file or directory @ rb_file_s_size - /home/jenkins/ws/workspace/ocp-common/Runner/workdir_cucu_formatter/OCP-30356_Normal_User_can_only_view_project_owned_by_himself/console.html (Errno::ENOENT)
06-17 08:22:15.870  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_uploader.rb:40:in `upload'
06-17 08:22:15.870  	from /home/jenkins/.gem/bundler/ruby/2.7.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/customizations/object.rb:440:in `upload_file'
06-17 08:22:15.870  	from …
```

fix premature exit for s3 upload

---

features/step_definitions/user.rb

A couple of SA cases failed due to last fix not fully considering all argument formats of this step.
Failures like: [OCP-11135](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2022/06/21/13%3A28%3A39/OCP-11135_Could_grant_admin_permission_for_the_service_account_username_to_access_to_other_project?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20220623%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20220623T015042Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=5a9eacf85545932797227f3f282267f2e227bac7248240f85704cf0bdd4c7c27), [OCP-12643](https://s3.upshift.redhat.com/cucushift-html-logs/logs/2022/06/21/13%3A28%3A56/OCP-12643_Could_grant_edit_permission_for_the_service_account_username_to_access_to_its_own_project?X-Amz-Algorithm=AWS4-HMAC-SHA256 …

Fix SA "I find a bearer token ..." step def

---

lib/polarshift/test_suite.rb
lib/test_case_manager_filter.rb

Reverts openshift/verification-tests#2920
It cause issue when the test case is already reserved in other jobs.
```
06-27 15:03:20.318  [07:03:19] INFO> Updating PolarShift test case OCP-12652 with Running status and duration of 0.0 seconds
06-27 15:03:20.318  [07:03:19] INFO> HTTP POST user@[https://polarshift-api-*.com/project/OSE/run/20220627-0652/records](https://polarshift-api-*.com/project/OSE/run/20220627-0652/records%1B[0m)
06-27 15:03:20.318  [07:03:19] INFO> HTTP POST took 0.026 sec: 409 Conflict
06-27 15:03:20.318      Given I have a project              # features/step_definitions/project.rb:7
......
06-27 15:03:20.318  undefined method `in_progress?' for nil:NilClass (NoMethodError)
06-27 15:03:20.318  /home/jenkins/ws/workspace/ocp-common/Runner/lib/polarshift/test_suite.rb:15 …
```

Revert "OCPQE-10931: skip scenario properly"

---

lib/common.rb
lib/manager.rb
lib/test_case_manager.rb

```
Randomized with seed 11921
[16:55:25] INFO> === At Exit ===
OCP-29199 - could not find all scenarios
OCP-33053 - could not find all scenarios
```
Most of the times, those "could not find all scenarios" are due to scenarios are not suitable for the current TEST_MODE set in Runner job

Make those "could not find all scenarios" more clearly

---

features/networking/pod.feature

The aim of this conntrack case is to make sure entries related to pod which no more exist shouldn't be present in conntrack table. We were searching that since beginning on our clusters grepping nodeport value casually but why not using podIP which is the aim here.
The existing logic will work fine if we dont have external gateway configured on cluster else breaks
On VZ IPI BM cluster conntrack rules are complicated involving gateways/spk and transalate nodeport, IP/port to differnet values confusing this individual case to fail on such.
I have run case on both clusters now and it works as expected
Normal AWS cluster: https://privatebin.corp.redhat.com/?a9738e9d8729e098#DxeQ4w5aPG1M3VyY4tFxp615phueCXwqpaBeFk2qz3aW
IPI BM vz cluster: …

search pod ip intead of nodeport

---

features/step_definitions/networking.rb
features/upgrade/sdn/egress-upgrade.feature
testdata/networking/ovn-egressfirewall/limit_policy_dualstack.json

Resolved  https://issues.redhat.com/browse/OCPQE-9910, add support for dualstack cluster for case OCP-44315.
dualstack cluster log:
PreUpgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4235/console
PostUpgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4236/console
ovn log:
PreUpgrade: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4237/console
PostUpgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4238/console
sdn log:
PreUpgrade: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4239/console
PostUpgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp …

Add support for dualstack cluster for OCP-44315

---

lib/launchers/openstack.rb

- added get_network_free_capacity_by_name(osp_network_name)
- added get_network_free_capacity_by_id(osp_network_id)

[ONEOCPDEPL-70] Introducing OSP launcher methods for getting OSP network capacity

---

features/networking/sctp.feature
features/step_definitions/networking.rb

1. Resolved below failure for OCP-28759, sometimes cluster doesn't have 2 available workers which caused the below error happening.  Move it after the step `Given I install machineconfigs load-sctp-module` as it has the checking workers step.
```
the Internal IP of node "<%= cb.workers[1].name %>" is stored in the :worker1_ip clipboard ==>@  [features/step_definitions/networking.rb:990](https://github.com/openshift/verification-tests/blob/edd90951b465c880dc41d371073263c4321615c9/features/step_definitions/networking.rb#L990)
#<NoMethodError: undefined method `name' for nil:NilClass>
```
2. Sometimes before executing the SCTP cases, the nodes are already in not correct status, to avoid this kind of failures, add one more step checking before the load sctp module. …

resolve OCPQE-10816

---

lib/environment.rb
lib/openshift/project.rb

After https://github.com/openshift/verification-tests/pull/2928 merged, I'm searching the CI logs to verify the fix do works or not.
Then found the issue not only exist for `oc debug`, but also exist for normal operations. E.g,
```
490594/log-[2022-06-29T23:24:15.947Z]     Given I obtain test data file "quota/pod-completed.yaml"                # features/step_definitions/file.rb:1
490594/log-[2022-06-29T23:24:28.091Z]     When I run the :create client command with:                             # features/step_definitions/cli.rb:13
490594/log-[2022-06-29T23:24:28.091Z]       | f | pod-completed.yaml |
490594/log-[2022-06-29T23:24:28.091Z]       [23:24:15] INFO> Shell Commands: oc create -f pod-completed.yaml --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_testuser-28.k …
```

OCPQE-8870: wait for project annotation "openshift.io/sa.scc.uid-range"

---

lib/test_case_manager_filter.rb

We've tried https://github.com/openshift/verification-tests/pull/2920 to fix the skip scenario issue. But revert the change later as it caused issue when the test case is already reserved.
Before making another fix, I'd like to check those test_case_finished events in detail, especially for the "HTTP POST took 0.036 sec: 409 Conflict" which is hard to simulate manually.
/cc @jhou1 @pruan-rht @JianLi-RH @dis016

Output the test_case_finished event to help debug OCPQE-10970

---

lib/test_case_manager.rb
lib/test_case_manager_filter.rb

The error is,
```
07-05 19:59:18.365    Scenario: OCP-24691 Defined Multiple allowedCIDRs                                                 # features/networking/service.feature:353
07-05 19:59:18.365  [11:59:18] WARN> logic error
07-05 19:59:18.365  [11:59:18] WARN> trying to start Cucumber scenario for test case #<Cucumber::Core::Test::Case:0x0000000018c22078>: OCP-24691 Defined Multiple allowedCIDRs
07-05 19:59:18.365  [11:59:18] WARN> but we are using test record from: OCP-30057 OVN DB should be updated correctly if a resource only exist in NB db but not in Kube API
```
The issue is that
let's assume we have two test cases, caseA and caseB. caseA has skip_this_scenario in one of its steps due to conditions can not met (e.g, scenario requires at least two nodes, but we are on SNO, which …

OCPQE-10970, OCPQE-10931: Add handler for skip_this_scenario

---

lib/test_case_manager.rb

We only allow change current_test_record from nil to non-nil, and vice versa.
```
def current_test_record=(value)
if @current_test_record.nil? && value ||
@current_test_record && value.nil?
@current_test_record = value
elsif @current_test_record
raise "current test record not cleared before setting new one"
else
raise "unsetting current test record while it is already unset"
end
end
```
so add a check before set it to nil.

OCPQE-10970: Fix RuntimeError: unsetting current test record while it is already unset

---

lib/polarshift/test_suite.rb

We have error message as below,
```
07-05 21:27:14.144  [13:27:13] WARN> logic error
07-05 21:27:14.144  [13:27:13] WARN> trying to start Cucumber scenario for test case #<Cucumber::Core::Test::Case:0x0000000017584b40>: OCP-26139 Traffic flow shouldn't be interrupted when master switches the leader positions
07-05 21:27:14.144  [13:27:13] WARN> but we are using test record from: OCP-32205 Thrashing ovnkube master IPAM allocator by creating and deleting various pods on a specific node
07-05 21:27:14.144  logic error: starting test case '#<Cucumber::Core::Test::Case:0x0000000017584b40>' that is not part of current test record
```

Remove duplicate error info

---

features/upgrade/api_auth/upgrade.feature

In upgrade CI pipeline jobs, it has been reported multiple times that , prepare case of OCP-41198 i.e. "apiserver and auth related upgrade check.Upgrade action will cause re-generation of certificates for headless services to include the wildcard subjects - prepare" has failed with timeout while checking the secret object created in test step. Hence I would like to increase the wait timeout to 120s to see how it works in execution ( This would not make any difference in already passing scenario execution only it would wait additional 60s before it fails with timeout in failing cases.)
Please note that, with same profile ,in multiple isolated test executions, we weren't reproduced this error.
Reference ticket  :  [OCPQE-10514](https://issues.redhat.com/browse/OCPQE-10514), …

Increased default wait timeout from 60s to 120s while checking secret in OCP-41198

---

features/step_definitions/networking.rb
testdata/networking/sgw-lgw-cm.yaml

It was noticed by @pruan-rht and came to my attention that existing logic is dumping huuuge logs for ovn masters during such tests. Probaly because master logs keeps filling up when many tests run on such clusters.
Earlier we didn't have great logic to check local vs shared modes on such clusters but now we have as this is being exposed via api in CNO. Also 4.9 takes a bit more time for operators to reconcile so increases time wait in general
Optimised logic and added impoved 4.9 support as well
Logs excert on 4.9: https://privatebin.corp.redhat.com/?ac87016468c10d4a#8ugYNaYu3K971H3jApBXpzfACGccecxmBkKNkrXByQ7W
Logs excerpt on 4.10+: https://privatebin.corp.redhat.com/?9933f35b394e63b9#9kzLMQgry25RJcAwKc5yKeAqnVCXzGFJsX2ker24Jf1K
No more enormous logging :)

gw mode improvements

---

features/step_definitions/logging.rb

Sometimes the ds/collector is not removed automatically after removing clusterlogging, and the step `I wait for the resource "daemonset" named "#{cb.collector_name}" to disappear` causes premature test execution termination. Here add a step to remove the ds if it's not removed automatically.

fix OCPQE-11171

---

features/upgrade/sdn/multus-upgrade.feature

https://issues.redhat.com/browse/OCPQE-10840: Upgrade testing will reboot all the nodes. The root cause for this issue is the dynamic address may be changed after nodes get rebooting, use static IP for pod’s secondary interface instead of dynamic, the IP should keep same before and after rebooting the nodes 
Test Log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4646/console
After rebooting nodes:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/4647/console

Update multus upgrade test

---

features/upgrade/routing/upgrade.feature

Since idling is not functional with OVN on 4.6/4.7, but we don't want remove tag `@network-ovnkubernetes` from this case, so the alternative solution is remove the old release tag.
@melvinjoseph86 @quarterpin @ShudiLi please help take a look, thanks,

update idling case for upgrade testing

---

lib/rules/web/admin_console/4.10/dashboards.xyaml
lib/rules/web/admin_console/4.11/dashboards.xyaml
lib/rules/web/admin_console/4.12/dashboards.xyaml
lib/rules/web/admin_console/4.6/dashboards.xyaml
lib/rules/web/admin_console/4.7/dashboards.xyaml
lib/rules/web/admin_console/4.8/dashboards.xyaml
lib/rules/web/admin_console/4.9/dashboards.xyaml

1. button class can easily change so removed class from xpath expression
2. `Cluster Utilization` card has 5 categories, most times not all categories are viewable so updated to scroll all into view before further checking

fix rules for OCP-27586

---

features/kata/install_uninstall.feature
features/kata/pod.feature
features/kata/smoke_tests.feature

The below tests are not reqd and are covered in our golang tests. Removing them by adding the inactive tag.
The respective polarion work items have also been marked inactive
cc @pruan @cpmeadors @dis016

Adding @inactive tags to tests

---

lib/openshift/resource.rb

In [OCPQE-8433](https://issues.redhat.com/browse/OCPQE-8433?focusedCommentId=20220756&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20220756), we have seen that , SNO case had been prematurely exited from test execution during a destructive case i.e. when new revision rolled out for kube-apiserver operator, SNO reports as "connection to the server xyz was refused - did you specify the right host or port?" till the operator becomes available. Currently the framework is not able to handle this properly and it raise exception [here](https://github.com/openshift/verification-tests/blob/70f9b2a5affb5764837df23b38169817ca3dd5d9/lib/openshift/resource.rb#L66). To avoid this situation i.e allowing SNO cases to retry and proceed further, we need to change the …

Bypass the premature exit of case or execution due to kube-apiserver operator roll out in SNO cases.

---

features/upgrade/workloads/descheduler-upgrade.feature

Adding flaky tag because i see that the test fails often when upgrade happens with in the same version i.e(4.7.nightly-> 4.7.nightly1 / 4.9.0 -> 4.9.1 etc). Will need to check how to handle case for this kind of situation. Currently it works only when from and to versions are different i.e (4.9 -> 4.10 / 4.11 -> 4.12)

Adding flaky tag to skip the test unti automation is fixed

---

features/upgrade/sdn/policy-upgrade.feature

Fix to enable test to run on SingleStack IPv6 cluster.
Tested on the following profiles:-
private-templates/functionality-testing/aos-4_11/upi-on-baremetal/versioned-installer-packet-dual_stack
private-templates/functionality-testing/aos-4_10/upi-on-baremetal/versioned-installer-packet-single_stack-http_proxy-fips-ipsec-ci

Fix the test to run on Singlestack IPv6 cluster

---

features/networking/metrics.feature

Due to recent sa token behavior change, replacing prometheus sa token logic.Instead we can get metrics relayed on port 9109 via sdn pods only. FYI In case of SDN we relay metrics on all sdn network pods irrespctive of controller, master or worker pod
Logs: http://pastebin.test.redhat.com/1068170

fixed prometeus sa token issues

---

features/step_definitions/logging.rb
lib/openshift/elasticsearch.rb

To resolve below failure:
```
07-28 23:27:44.846        undefined method `dig' for nil:NilClass (NoMethodError)
07-28 23:27:44.846        /home/jenkins/ws/workspace/ocp-upgrade/upgrade-consumer/lib/openshift/elasticsearch.rb:144:in `es_pods'
07-28 23:27:44.846        /home/jenkins/ws/workspace/ocp-upgrade/upgrade-consumer/lib/openshift/elasticsearch.rb:148:in `es_master_pods'
07-28 23:27:44.846        /home/jenkins/ws/workspace/ocp-upgrade/upgrade-consumer/lib/openshift/elasticsearch.rb:152:in `es_master_ready_pod_names'
```

resolve failure: undefined method for nil class

---

testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_configmap.yaml
testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml

The keyword infra-write,app-write are dropped from Logging 5.4 update syslog.conf filter to match this change.
version <=5.1:  [infra-write,app-write, audit-write]  present
version = 5.2,5.3:  both [infra-write,app-write, audit-write]  and [logType:  applicaiton,logType:  infrastructure,  logType audit] present,
version >=5.4  only  [logType:  applicaiton,logType:  infrastructure,  logType audit]  present

update the configmap of rsyslogserver

---

lib/bushslicer.rb

`project_name = "prj-" + EXECUTOR_NAME.downcase + "-" + project_suffix.sample(4).join`
4 + x + 1 + 4, while x = 56 + 1, cause project name to be 66 chars, exceed the max length of 63 chars for project.
/cc @duanwei33 @jhou1 @pruan-rht

Project name must be no more than 63 chars

---

features/upgrade/sdn/policy-upgrade.feature

Small fix. In rare cases a match for 10.x.x.3 will have success in 10.x.x.32 as well..etc
```contain``` must be replaced by ```match``` in cucumber steps for such queries
Logs: http://pastebin.test.redhat.com/1070481

contain should be match

---

testdata/cloud/autoscaler-auto-tmpl.yml

Change the workload request cpu from `500m` to `1100m`, as the previous value `500m` cannot work on vsphere autoscaler, we already reported bug to dev https://bugzilla.redhat.com/show_bug.cgi?id=2111721, but dev will not fix this, so we can only use workaround which is increasing the workload cpu resource request. @sunzhaohua2 @miyadav @jhou1 PTAL, thanks!
test result on aws:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/536818/console
test result on azure:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/536817/console
test result on vsphere:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/536956/console

change workload

---

features/networking/ipv6_dualstack.feature
features/step_definitions/networking.rb

[05:12:51] INFO> === After Scenario: OCP-40581:SDN Project should be in isolation when using multitenant policy for ipv6 dual stack ===
[05:12:51] INFO> Shell Commands: rm -r -f -- /root/workdir/preserve-zzhao-rootx
[05:12:52] INFO> Exit Status: 0
[05:12:53] INFO> === End After Scenario: OCP-40581:SDN Project should be in isolation when using multitenant policy for ipv6 dual stack ===
1 scenario (1 skipped)
42 steps (42 skipped)
0m25.399s
skip those two scenarios for that not ipv6 dual stack cluster. 

update for ipv6 dual stack scenarios

---

features/networking/egress-ingress.feature
features/networking/egress-ip.feature
features/networking/ovn-egress-ip.feature
features/networking/pod.feature
features/networking/sdn.feature
features/networking/service.feature

OVN will be default network type in 4.12 version,  so the default workflow will be OVN. so here enhance the step to make sure scenarios are working on correct cluster in case. 
thus in Prow CI config, we do not need to specified the network type tag
before:
```
E2E_RUN_TAGS: '@aws-ipi and @network-openshiftsdn and not @fips'
```
after :
```
E2E_RUN_TAGS: '@aws-ipi and  not @fips'
```
and another in cucushift repo https://github.com/openshift/cucushift/pull/9250

add step to make sure the scearios running correct cluster

---

features/machine/machine.feature
features/step_definitions/machine.rb

@sunzhaohua2 @huali9 PTAL .
This test fails consistently due to error message changed(Forbidden error is no more , it gives invalid configuration and machineset is created successfully )  , more details can be found here - https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/396/200732/11501975
[Error](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-azure-ipi-resourcegroup-p1/1559570771666276352/artifacts/e2e-azure-ipi-resourcegroup-p1/cucushift-e2e/build-log.txt) log 
Validation results - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/563832/console

Fix error message+logic to pick the latest machine name

---

features/step_definitions/descheduler.rb
features/upgrade/workloads/descheduler-upgrade.feature

Previously only upgrading major versions of descheduler was working with the existing code i.e (4.7 -> 4.8, 4.8 -> 4.9) and post upgrade check was always failing when upgrade was happening with in the same version i.e (4.7.rc -> 4.7.rc2). With this PR it should be fixed and we should not be seeing any failures with respect to post upgrade check for descheduler case.

Removing flaky tag plus updating the code to upgrade minor versions as well

---

features/step_definitions/helper_services.rb

When using "oc apply/create -f" to create iscsi-target server pods violates PodSecurity on 4.12, it used hostpath so need ns privilieged. Modify the default create ns of the iscsi-target server to openshift-iscsi-target solve the issue. And it should also work on previously releases.
**[Flake record](https://${report-portal-Domain}/ui/#prow/launches/all/204729?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D2)**
**[Test record ](https://${jenkins-Domain}/job/ocp-common/job/Runner/572210/console)**

Fix flakes of 19110|19150

---

features/step_definitions/helper_services.rb

@Phaow @duanwei33 @liangxia I forgot to say previous https://github.com/openshift/verification-tests/pull/2999 will fire one important alert on cluster due to https://github.com/openshift/cluster-kube-apiserver-operator/pull/1362 alert definition. We must add other labels to avoid the alert for pod creation. The audit label must be added. The warn label is optional, but why not make the warn output gone.
Pass log: job/Runner/575626/console
@Phaow @duanwei33 @liangxia help review and merge, thanks!

Add other labels to avoid alert

---

features/step_definitions/helper_services.rb

Failure log: https://url.corp.redhat.com/e73923f due to error:
Error from server (Forbidden): error when creating "ldapserver.yaml": pods "ldapserver" is forbidden: violates PodSecurity "restricted:v1.24": unrestricted capabilities (container "ldapserver" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "ldapserver" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "ldapserver" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
Pass log: job/ocp-common/job/Runner/575624/console
@zhouying7780 @liangxia help review / merge, thanks!

Add pod security labels to namespaces

---

features/step_definitions/project.rb

PodSecurity restricted enabled by default on 4.12, used hostpath cases need namespace set to privilieged. Add setup privileged project util for using privilieged namespace scenarios.
**[Flake record](https://${report-portal-Domain}/ui/#prow/launches/454/207510/12395570/12395797/log?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)**
**[Test record ](https://${jenkins-Domain}/job/ocp-common/job/Runner/577369/console)**

Add setup privileged project util

---

features/admin/quota.feature

Using `oc describe` to check DeadlineExceeded, instead of `oc get`

Fix OCP-11348

---

features/storage/cloud_provider.feature
features/storage/csi.feature
features/storage/csi_resize.feature
features/storage/csi_snapshot.feature
features/storage/dynamic_provisioning.feature
features/storage/fsType.feature
features/storage/hostpath.feature
features/storage/negative.feature
features/storage/node_operations.feature
features/storage/persistent_volume.feature
features/storage/pre-bind.feature
features/storage/reclaim_policy.feature
features/storage/security.feature
features/storage/storage_class.feature
features/storage/vsphere.feature

When there are multiple `Examples` for scenario outlines, some of the tags are shared across those examples, which need to put ahead of the scenario outline.
/cc @duanwei33 @chao007 @Phaow

Fix tags for scenario outlines in storage

---

features/storage/security.feature

PodSecurity restriction enabled by default on 4.12, updated test script to use new step definition for Project setup with privileged namespace.
[**Flake record**](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/all/212125/13089063/13090011/log?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)
[**Jenkins test record**](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/587000/)

Fix flake OCP-9700

---

features/networking/ovn_ipsec.feature
features/networking/pod.feature
features/step_definitions/networking.rb
features/step_definitions/project.rb
features/upgrade/sdn/ipsec-upgrade.feature
features/upgrade/sdn/policy-upgrade.feature
testdata/networking/net_admin_cap_pod.yaml

Simlar to https://github.com/openshift/verification-tests/pull/3001/files (as debug pod is also hostnw pod), we also need a def under our networking.rb to support various host network pod usecases which are failing on 4.12
we  pass `nil` the logic if env < 4.12
Logs: https://privatebin.corp.redhat.com/?cdaa9fa5248e2208#236gaH3wzHKBX4c77p1xvgL43DiUvMot9L5iQnKYPxs9

pod security for hostnw pods

---

features/upgrade/sdn/service-upgrade.feature

Since there is known issue for idle https://bugzilla.redhat.com/show_bug.cgi?id=2041307 and this will not be fixed before 4.8 version, and only document mention this issue and workaround
So remove 4.6 and 4.7 version in order to always failed cases in CI

remove 4.6 and 4.7 version since there is known issue

---

lib/rules/web/admin_console/4.10/dashboards.xyaml
lib/rules/web/admin_console/4.11/dashboards.xyaml
lib/rules/web/admin_console/4.12/dashboards.xyaml
lib/rules/web/admin_console/4.6/dashboards.xyaml
lib/rules/web/admin_console/4.7/dashboards.xyaml
lib/rules/web/admin_console/4.8/dashboards.xyaml
lib/rules/web/admin_console/4.9/dashboards.xyaml

before the changes, we see errors
```
09-01 14:00:55.179      When I run the :check_cluster_utilization_items web action                         # features/step_definitions/web.rb:13
09-01 14:00:55.179        [06:00:47] INFO> running web action check_cluster_utilization_items ... 
09-01 14:00:55.179        [06:00:47] INFO> elements..
09-01 14:00:55.179        [06:00:48] INFO> found 1 element elements with selector: {:xpath=>"//h2[text()='Cluster Utilization']"}
09-01 14:00:55.179        [06:00:48] INFO> found 1 element elements with selector: {:xpath=>"//h4[text()='CPU']"}
09-01 14:00:55.179        [06:00:51] INFO> found 1 element elements with selector: {:xpath=>"//h4[text()='Memory']"}
09-01 14:00:55.179        [06:00:51] INFO> found 1 element elements with selector: …
```

fix OCP-27586

---

features/upgrade/sdn/policy-upgrade.feature

@openhift/team-sdn-qe PTAL
https://issues.redhat.com/browse/OCPQE-11801
Increase the time for step to succeed. It was just 10sec, most of the test steps have 30 secs.
Tested on cluster private-templates/functionality-testing/aos-4_7/ipi-on-gcp/versioned-installer-restricted_network-private_cluster-ci
[asood@asood verification-tests]$ oc version
Client Version: 4.12.0-0.nightly-2022-07-25-055755
Kustomize Version: v4.5.4
Server Version: 4.7.0-0.nightly-2022-08-27-004627
Kubernetes Version: v1.20.15+98b2293

Increase time for the step to succeed

---

features/admin/quota.feature

Fix ocp-12292 message check issue
log:
```[weinliu@rhel8 verification-tests]$ cucumber features/admin/quota.feature:60
Using the default, devel and _devel profiles...
Feature: Quota related scenarios
@flaky @admin @4.12 @4.11 @4.10 @4.9 @4.8 @4.7 @4.6 @vsphere-ipi @openstack-ipi @gcp-ipi @baremetal-ipi @azure-ipi @aws-ipi @vsphere-upi @openstack-upi @gcp-upi @baremetal-upi @azure-upi @aws-upi @upgrade-sanity @singlenode @proxy @noproxy @disconnected @connected @network-ovnkubernetes @network-openshiftsdn @heterogeneous @arm64 @amd64
Scenario: OCP-12292:Node The quota usage should NOT be incremented if Requests and Limits aren't specified # features/admin/quota.feature:60
[08:01:55] INFO> === Before Scenario: OCP-12292:Node The quota usage should …
```

Fix ocp-12292 message check issue

---

features/step_definitions/descheduler.rb

PR fixes two issues here:
=======================
1. I see that upgrades from 4.11.y to 4.11.z are failing to create csv version with out the version 4.11 present in here, so fixing the same.
2. I see that descheduler channels does not have '-' in its channel name and when using the existing code it fails with error **no implicit conversion of nil into String**, so fixing the same.

Adding the missing descheduler version

---

features/networking/sdn.feature

for fix this issue 
```
tests/blob/7647a55fff682d249b4c65bbb36c19a57a8fa5a6/features/step_definitions/common.rb#L141)
#<RuntimeError: expression returned non-positive status: false left_operand: ["1.8.4"], right_operand: ["1.8.4", "8.460"] >
[features/step_definitions/common.rb:168](https://github.com/openshift/verification-tests/blob/7647a55fff682d249b4c65bbb36c19a57a8fa5a6/features/step_definitions/common.rb#L168):in `/^(?:the )?expression should be true> (.+)$/'
[features/networking/sdn.feature:237](https://github.com/openshift/verification-tests/blob/7647a55fff682d249b4c65bbb36c19a57a8fa5a6/features/networking/sdn.feature#L237):in `the expression should be true> cb.iptables_version_host == cb.iptables_version_pod'
When
```
test pass
```
[10:24:51] INFO> Shell …
```

update response to stdout

---

tools/openshift-ci/Dockerfile

```
bash-4.4$ /usr/bin/google-chrome-stable --help
mkdir: cannot create directory '/.local': Permission denied
touch: cannot touch '/.local/share/applications/mimeapps.list': No such file or directory
[0909/093802.341461:FATAL:chrome_main_delegate.cc(419)] execlp failed: No such file or directory (2)
Trace/breakpoint trap (core dumped)
```
```
[root@e1c884393f98 /]# mkdir .local
[root@e1c884393f98 /]# chmod -R 777 .local
```
No longer seeing permission problem
```
bash-4.4$  /usr/bin/google-chrome-stable --no-sandbox
[296:296:0909/094042.030243:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[296:296:0909/094042.033301:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
[0909/094042.051325:ERROR:nacl_helper_linux.cc(315)] NaCl helper process running without a …
```

Fix permission issue for chrome launch

---

features/step_definitions/project.rb

To fix [OCPQE-11935](https://issues.redhat.com//browse/OCPQE-11935):
Checked this step "admin creates a project with a random schedulable node selector" is only used by storage team, and adding the namespace label.
[Failed in CI](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/396/219006?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D4)
[pass log ](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/600542/console)
@Phaow PTAL, thanks

Podsecurity issue fix for OCP-14665 and OCP-14673

---

features/cli/oc_secrets.feature
features/cli/pod.feature
features/cli/policy.feature
features/cli/projects.feature
features/cli/serviceaccount.feature

Selected Auth 4.10 ~ 4.12 valid non-destructive cases for these tags:
```
$ cd verification-tests
$ cucumber --dry-run --name Authentication --tags 'not @destructive' --tags '(@4.12 or @4.11 or @4.10)' --tags 'not @inactive' -f summary | tee ~/my/rosa-aro-osd.scenarios
oc_secrets.feature
OCP-10631:Authentication Project admin can process local directory or files and convert it to kubernetes secret -
...
$ ALL=`grep -o 'OCP-[0-9]*' ~/my/rosa-aro-osd.scenarios`
$ for CaseID in $ALL
do
FileName=`grep --include "*.feature" -HlR $CaseID`
sed -i "/Scenario: $CaseID"':Authentication/i \
@osd_ccs @aro @rosa' "$FileName"
done
```
@zhouying7780 @liangxia please help review/merge, thanks!

Add osd_ccs @aro @rosa tags for Auth

---

features/networking/sdn.feature

Due to https://issues.redhat.com/browse/OCPBUGS-994, admin should not run any pods under default ns. Update case to be inactive. 

Add @inactive tag

---

features/admin/quota.feature

Defeault secret numbers got updated on 4.11 and 4.12
1) update the secret numbers check
2) leave 4.11 and 4.12 only
log: http://pastebin.test.redhat.com/1073583

Fix ocp-11927 secret numbers

---

features/networking/egress-ingress.feature
testdata/networking/aosqe-pod-for-ping.json

1. Revert https://github.com/openshift/verification-tests/pull/3042, as that change failed in 4.10,the pod couldn't be created successfully.
2. Fix original issue OCP-19615 by adding "And the appropriate pod security labels are applied to the namespace"
Test logs:
4.10: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5021/console 
4.12: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5022/console

Revert pr3042

---

features/upgrade/workloads/descheduler-upgrade.feature

Eventhough Step status becomes :running of exactly 1 pods labeled already contains wait logic,  i see that the test is failing, so wrapped the statement in another wait.
```
And status becomes :running of exactly 1 pods labeled:                                            # features/step_definitions/pod.rb:88
| name=descheduler-operator |
[12:00:56] INFO> oc get pods --output=yaml -l name\=descheduler-operator --kubeconfig=/home/knarra/workdir/knarra-knarrax/ocp4_admin.kubeconfig -n openshift-kube-descheduler-operator
[12:00:56] INFO> 1 iterations for 2 sec, returned 1 pods, 1 matching
waiting for operation up to 900 seconds..
And status becomes :running of exactly 1 pods labeled:                                            # …
```

Adding extra timeout here because the current one is not sufficient

---

lib/webauto/web4cucumber.rb

Before this change, I can see errors in local container
```
unknown error: Chrome failed to start: exited abnormally.
(unknown error: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Selenium::WebDriver::Error::UnknownError)
#0 0x56406407b693 <unknown>
#1 0x564063e74b0a <unknown>
```

fix OCPQE-11756

---

lib/polarshift/request.rb

For situation in which the user did not clone the `private` repo, print out a more meaning error message and suggestion rather than the plain old ruby .nil error.

added a more meaningful error message

---

features/networking/sdn.feature

Quick fix: This usecase was initially created keeping RHCOS nodes in mind. Howver it was noticed in recent prow failures that it might behave a bit different if a RHEL node is chosen. Confirmed with dev, its  not a product issue but some RPMs etc used on RHEL/RHCOS are certainly different and responsible for those
Whats changed
- The RHEL node vs sdn pod on same RHEL node might same version of nftables but pod might add additional sub version suffix to it due the fact that sdn containers are adding extra RPMS later during installation
For e.g
The node might contain main version as "1.8.4" but pod might dump "1.8.4", "1.512". We want to make sure 1.8.4 should sync across both at least
Node says <main_version>
pod says <main_version, sub_version>
- Also SDN containers sometime in rare cases …

fixing iptables usecase OCP-24543

---

features/step_definitions/logging.rb

To fix failure in [OCPQE-8932](https://issues.redhat.com//browse/OCPQE-8932):
From https://gitlab.cee.redhat.com/aosqe/jenkins-jcasc-n/-/blob/master/scripts/OCPQE-11466/upgrade_cluster_logging.sh#L9-10, in OCP 4.12 the channel is `stable-5.6`.
As the `catsrc/qe-app-registry` is enabled in [Prow CI](https://github.com/openshift/release/tree/master/ci-operator/step-registry/enable-qe-catalogsource), we should always have channel `stable-5.6` in our test clusters, here change the default channel name to `stable-5.6` when testing in OCP 4.12. 
/cc @anpingli

fix OCPQE-8932

---

features/machine/machine.feature

As we have converted it to ginkgo  , there were issues related to test selection and it was selected in disconnect=no also 
https://github.com/openshift/openshift-tests-private/blob/master/test/extended/clusterinfrastructure/machines.go#L539
backport merged as well till 4.10 
@sunzhaohua2 @huali9 @jhou1 , it looks safe to remove it . 
example [failure](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/396/235764/15828076/15828446/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.issueType%3Dti001%252Cti_1hrghcxlbgshc%252Cti_s4scyws6guht%252Cti_sok676b1k8j5%252Cti_r1ifkmkw19o1)

converted to ginkgo no longer needed

---

lib/rules/web/admin_console/4.10/user_management.xyaml
lib/rules/web/admin_console/4.11/user_management.xyaml
lib/rules/web/admin_console/4.12/user_management.xyaml
lib/rules/web/admin_console/4.6/user_management.xyaml
lib/rules/web/admin_console/4.7/user_management.xyaml
lib/rules/web/admin_console/4.8/user_management.xyaml
lib/rules/web/admin_console/4.9/user_management.xyaml

added one step to filter user name to reduce the failures when there are many users
```
INFO> found 0 element elements with selector: {:xpath=>"//a[text()='testuser-36']//ancestor::tr//button[@data-test-id='kebab-button']"}
```
4.10 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/639104/console 
4.12 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/639114/console
4.6 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/639115/console
4.8 pass log https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/639116/console

fix OCP-25765

---

testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_deployment.yaml
testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml

- use one image to support both TLS and none tls cases
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/640767/console

update rsyslogd-container images

---

features/cli/oc_expose.feature

Fixed securityContext & seccompProfile issue for test OCP-10873 failure.
Execution Result : [642779](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/642779/console)

Fixed OCP-10873 failure

---

features/step_definitions/logging.rb
lib/openshift/cluster_network.rb

When the cluster has `network_plugin_mode: "multitenant"`, EO can't update the ES status as they're not in the same project, here add a step to make project/openshift-operators-redhat network global in these clusters.

fix OCPQE-11446

---

lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
lib/rules/web/admin_console/4.9/common_ui_elements.xyaml

workloads list page URL has been updated from `kind` to `group-version-kind` format, so move all changing text to rules 
take all namespace deploymentconfig list page URL as example, it was `all-namespaces/deploymentconfigs` but now it is `all-namespaces/apps.openshift.io~v1~DeploymentConfig`

update rules for OCP-32152

---

lib/rules/web/admin_console/4.12/storage.xyaml

the `input` element has different html definition for setting PVC size and expanding PVC size, so create a new step `set_expand_size`

fix OCP-23681

---

features/upgrade/sdn/policy-upgrade.feature

This is exception case whish used NET_ADMIN pod post upgrade and PSa labels are not persistent across upgrades. Quick fix @openshift/team-sdn-qe

quick PSa fix

---

features/networking/egress-ingress.feature

Resolve ticket, https://issues.redhat.com/browse/OCPQE-12619
Curling immediately after the egressfirewall applied may got failed sometimes especially when it contains many rules, adding timeout to avoid this.
Test log on sno cluster:  https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5121/console

fix failure in OCP-41179

---

features/upgrade/logging/upgrade.feature

To fix [OCPQE-3947](https://issues.redhat.com//browse/OCPQE-3947), remove namespaces `openshift-logging` and `openshift-operators-redhat`, let upgrade-prepare deploys logging operators.
/cc @anpingli

fix OCPQE-3947

---

features/upgrade/sdn/multus-upgrade.feature

Removing @users in `https://github.com/openshift/verification-tests/pull/3097/files#diff-deed1f9aea2eaeda53415aa72219c9479601c89758c737e506fa090d5cf65248L6` cause test failed in `https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/33684/rehearse-33684-periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-e2e-vsphere-ipi-sdn-migration-ovn-p2/1587822254731825152/artifacts/e2e-vsphere-ipi-sdn-migration-ovn-p2/cucushift-upgrade-prepare/build-log.txt` 
`https://github.com/openshift/verification-tests/pull/3097/files#diff-deed1f9aea2eaeda53415aa72219c9479601c89758c737e506fa090d5cf65248L6` passed in the local run without those @users, seems e2e env still need those tags.
Add @users back to the code now. …

Add @users back to test case

---

features/networking/sdn.feature

This case failes intermittenly at rules step. sometime SDN pod has a rule more than node or reverse. Upon talking to dev (Jacob, who owns [SDN-341](https://issues.redhat.com//browse/SDN-341)) this is normal as sometimes sdn leader can create rule specific to container and same goes for node. He suggested to keep checking binary version in longer run so this rules logic is redundant. Let me know if anybody has concerns

rules checking logic redundant for iptables across pod and node

---

features/upgrade/sdn/policy-upgrade.feature

In rare circumstances if output dump is say
```udp      17 29 src=10.129.2.133 dst=10.129.2.134 sport=47249 dport=8080 src=10.129.2.134 dst=10.129.2.133 sport=8080 dport=47249 mark=0 secctx=system_u:object_r:unlabeled_t:s0 zone=22 use=2 ```
and pod IP to search is ```10.129.2.13``` , the logic would pass assuming pod IP being a subset of ```10.129.2.133```.
Improved grep logic to add w flag to dump output just matching with those IPs and adding a white space in match expression to fix that subset logic

improved fetch logic for pod IPs

---

features/upgrade/sdn/ipsec-upgrade.feature

Quick fix: Doubling the time from 2s to 4 s for tcpdump ESP captures. Noticed rarely in prow that ESP packets might not be visible for the node in question in 2sec dump. Will see how it goes in prow for sometime. Thanks

time increase for tcpdump capture

---

testdata/logging/clusterlogforwarder/rsyslog/insecure/rsyslogserver_deployment.yaml

@anpingli @zhaozhanqi PTAL
bundle exec cucumber features/upgrade/sdn/policy-upgrade.feature:534 fails with error message.
14:48:25] INFO> Shell Commands: http_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@bastion.vmc.ci.openshift.org:3128
https_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@bastion.vmc.ci.openshift.org:3128
oc exec rsyslogserver-568959987b-9m7k9  --kubeconfig=/home/asood/workdir/asood-asoodx/ocp4_admin.kubeconfig -n rsyslog-server  -i -- grep -w verdict\=allow /var/log/messages
STDERR:
E1109 09:48:26.925162  256314 v2.go:105] read /dev/stdin: resource temporarily unavailable
grep: /var/log/messages: Permission denied
oc -n rsyslog-server exec -it rsyslogserver-568959987b-9m7k9 -- bash
bash-5.1$ ls -l /var/log/messages
-rw-------. 1 root root 0 Oct  9 13:59 …

Use updated image that permission on /var/log/messages to make it readable

---

testdata/routing/operator/ingressctl-nsowner.yaml

remove `router-certs-default` setting since hypershift host cluster uses another secret.

update NE testdata for hypershift testing

---

features/logging/logging_acceptance.feature
features/step_definitions/logging.rb
testdata/logging/clusterlogging/cl-storage-with-im-template.yaml
testdata/logging/clusterlogging/cl_fluentd-buffer.yaml
testdata/logging/clusterlogging/cl_fluentd-buffer_Invalid.yaml
testdata/logging/clusterlogging/cl_fluentd-buffer_default.yaml
testdata/logging/clusterlogging/clusterlogging-storage-template.yaml
testdata/logging/clusterlogging/example.yaml
testdata/logging/clusterlogging/example_indexmanagement.yaml
testdata/logging/clusterlogging/example_unmanaged.yaml
testdata/logging/clusterlogging/index_management_test.yaml
testdata/logging/clusterlogging/scalebase.yaml

This PR:
1. set default requests memory to `2Gi` for ES
2. set channel to `stable` when testing on OCP 4.12 to avoid below issue:
```
[36mspec:[0m
[36m  channel: stable-5.6[0m
[36m  installPlanApproval: Automatic[0m
[36m  name: elasticsearch-operator[0m
[36m  source: redhat-operators[0m
[36m  sourceNamespace: openshift-marketplace[0m
```

increase memory for ES pods and set default channel to stable

---

features/images/rhel8_images.feature

@liangxia 
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-22595 is deprecated since 4.7, I update this case, please help review, thanks

Remove 22595 from 4.12

---

features/networking/metrics.feature

Since 4.11+ OVN master metrics are now being exposed to kubernetes elected OVN master pod instead earlier they were exposed to all OVN masters. This case was passing most of the time as co-incidentally it was selecting right master..heh.
This is already implemented in right way in `openshift-tests-private` repo but needed fix here. Also https://github.com/openshift/verification-tests/pull/3043 introduced a new helper function, thanks @pruan-rht for that which we can use here and in long run to use kube elected ovn master wherever needed in fixes
Logs: https://privatebin.corp.redhat.com/?e17d1275802e6bd1#3tfTyUskQ9u3DNvx3ueWfPM2jtLnR3UvXk3BSd9Uge2f

OCP-37704 should point to kubernetes elected ovn master pod to fetch ovn exposed metrics

---

features/step_definitions/helper_services.rb

PR to fix [OCPQE-11977](https://issues.redhat.com/browse/OCPQE-11977) and [OCPQE-11976](https://issues.redhat.com/browse/OCPQE-11976).
Before the fix, when there is a unhealthy iscsi-target pod, it only remove but not create a new one like [failed job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/667401/console).
This is the [successful job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/667402/console). 
@radeore @Phaow @chao007 @ropatil010 PTAL.

Recreate the iSCSI pod after deleting

---

features/cli/configmap.feature

due to this pr(https://github.com/openshift/verification-tests/pull/3079/files) add seccomp, will lead to failure of OCP-11255 in version < 4.11, so remove label of < 4.11

fix OCP-11255, remove label of < 4.11

---

features/logging/eventrouter.feature

When debugging https://url.corp.redhat.com/9efeb20, I found the case OCP-25899 was tested, and it's outdated, here remove it from the test scenario.

remove outdated case

---

features/step_definitions/storage_class.rb
features/storage/fsType.feature
testdata/storage/misc/in-tree-storageClass-template.yaml
testdata/storage/misc/storageClass-with-stable-annotations.yaml

Hi Team,
kindly PTAL.
Issue: https://issues.redhat.com/browse/OCPQE-12840
Problem statement: Test cases impacted wrt intree tc after CSI Migration.
4.11: Azure, Cinder
4.12: GCP, AWS
Fix: Making all cucushift related tc wrt intree instead of doubling them in ginkgo by adding 1 function definition.
Calling this function definition will fix most of the issues related to CSI Migration.
Scenario Outline: Setting mountOptions for StorageClass
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5206/console 412 GCP
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5207/console 412 AWS
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5208/console 412 Az
Scenario: …

storage-intreetests-verificationtests

---

lib/webauto/web4cucumber.rb

Pass log on different env:
ipi-on-gcp/versioned-installer-filestore-CSI-ci: Runner/680138/
ipi-on-aws/versioned-installer-arm-ovn-efs-sts-ci: Runner/680153/
upi-on-vsphere/versioned-installer-vmc7-secureboot_enabled-static_network:Runner/680163/
Pass log on local:
[pass.log](https://github.com/openshift/verification-tests/files/10109681/pass.log)

Fix issue for OCPQE-12378

---

lib/polarshift/request.rb

After we bring in the retry logic, we got two failed jobs due to create_run failed, the others works good. So bump up the retry times a little bit, and wait 60 seconds before retry.
/cc @jhou1 @pruan-rht @chengzhang1016 @Xia-Zhao-rh

OCPQE-13027: More retries when create_run fail, and sleep before retry

---

features/step_definitions/storage_class.rb

Hi Team, 
Kindly PTAL,
Payload: 4.10.43
Platform: OSP 
Issue: #<RuntimeError: Unsupported iass_type `openstack`> 
PR about: Fix platform name + to small letters, we are not hitting Unsupported iass_type. 
Logs: 
Openstack: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5239/console 
storageclass.storage.k8s.io/sc-33sqm created
[04:47:38] INFO> Exit Status: 0
Error about: ImagePullBackOff in pod container creation
GCP: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5241/console
AWS https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5240/console
/assign @chao007 @duanwei33 @Phaow

storage-fixplatformname

---

features/machine/autoscaler.feature
features/machine/machine.feature
features/machine/machine_healthcheck.feature
features/machine/machine_misc.feature
features/machine/upi_gcp.feature

Due to test  failures on hypershift-guest clusters ( as these tests are not needed) removing tag
PTAL @jhou1 @sunzhaohua2 @huali9

removed @hypershift-hosted cluster tag

---

features/storage/cloud_provider.feature

1. These cases are not deactivated from Polarion and cases have a good pass rate in Jenkins CI, so remove "@inactive" tag to bring them back
2. Use normal deployment instead of new-app
3. Adding waiting time for expected behavior
[pass log](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/676851/console)
@chao007 @Phaow @ropatil010 PTAL, thanks.

use normal deployment instead of new-app

---

features/step_definitions/logging.rb

When debugging test results on ROSA and OSD, alway seeing below failure:
```
Message: failed OCP-37508:Logging One logging acceptance case for all cluster
Type: failed
Text:
Scenario: OCP-37508:Logging One logging acceptance case for all cluster
Given I wait up to 360 seconds for the steps to pass:
Message:
undefined method `[]' for nil:NilClass (NoMethodError)
(eval):1:in block in <top (required)>'
./features/step_definitions/common.rb:142:ineval'
./features/step_definitions/common.rb:142:in /^(?:the )?expression should be true> (.+)$/'
./features/step_definitions/transform.rb:33:incall'
./features/step_definitions/transform.rb:33:in block in singleton class'
./features/step_definitions/meta_steps.rb:48:inblock (2 levels) in <top (required)>'
./lib/base_helper.rb:160:in wait_for' …
```

add label to logging namespaces

---

features/step_definitions/networking.rb
features/upgrade/sdn/egress-upgrade.feature
features/upgrade/sdn/multicast-upgrade.feature

Remove "Given the cluster is not migration from sdn plugin" for test cases multicase, egressfirewall and SDN-egressIP which are supported after sdn to ovn migration in 4.12.

Update three cases supported in sdn2ovn migration

---

features/networking/multus.feature

After debugging https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/all/276500/22372643?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED, then found out most multus cases need `And the appropriate pod security labels are applied to the namespace`

And the appropriate pod security labels for multus cases

---

lib/rules/web/admin_console/4.10/operator_hub.xyaml
lib/rules/web/admin_console/4.11/operator_hub.xyaml
lib/rules/web/admin_console/4.12/operator_hub.xyaml
lib/rules/web/admin_console/4.13/operator_hub.xyaml
lib/rules/web/admin_console/4.7/operator_hub.xyaml
lib/rules/web/admin_console/4.8/operator_hub.xyaml
lib/rules/web/admin_console/4.9/operator_hub.xyaml

- remove `check_required_badge_during_installation` rule since it is not used in any feature
[yapei@yapei-mac cucushift (fix)]$ grep -nr 'check_required_badge_during_installation' web/admin-console
- updated rules checking `Required` badge to be simpler and more stable

fix OCP-33743

---

features/upgrade/workloads/descheduler-upgrade.feature

sometimes i see that test is failing with error that there are two pods existing and none of them in running state, one could be in containercreating and another could be in terminating state. So adding wait time to make sure that old pod dies completely and new pod comes up fine.
11-20 06:04:24.487      And status becomes :running of exactly 1 pods labeled:                                            # features/step_definitions/pod.rb:88
11-20 06:04:24.487        | name=descheduler-operator |
11-20 06:04:24.487        [00:34:24] INFO> oc get pods --output=yaml -l name\=descheduler-operator --kubeconfig=/home/jenkins/ws/workspace/ocp-upgrade/upgrade-consumer/workdir/ocp4_admin.kubeconfig -n openshift-kube-descheduler-operator
11-20 06:04:24.487        [00:34:24] INFO> 1 iterations for 1 …

Add wait time so that descheduler operator pod comes up fine

---

features/upgrade/sdn/egress-upgrade.feature
features/upgrade/sdn/multicast-upgrade.feature

Fix `no specification for user index 0 in a scenario @users tag (RuntimeError)` in [OCPQE-13180](https://issues.redhat.com/browse/OCPQE-13180)

Fix OCPQE-13180

---

lib/polarshift/request.rb
tools/polarshift.rb

depends on https://gitlab.cee.redhat.com/aosqe/polarshift/-/merge_requests/26 which adds the API support in the backend.

added CLI support to sync run from Polarion to Polarshift

---

features/step_definitions/storage_class.rb

Hi Team, 
As known issue from framework side wrt iaas_type, fixing only from storage point of view. 
Profile: versioned-installer-customer_vpc-disconnected_private_cluster-arm-ci
Image: installer_payload_image: registry.ci.openshift.org/ocp-arm64/release-arm64:4.11.0-0.nightly-arm64-2022-12-09-094448
Issue description and fix written here: https://issues.redhat.com/browse/OCPQE-13208
Execution log: 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/702783/console
12-20 11:28:24.103  8 scenarios (8 passed)
/assign @chao007 @duanwei33 @Phaow

storage-identifyplatform fix

---

features/routing/haproxy-router.feature

Decrease the number of`rate-limit-connections.rate-tcp` to make it easy to be triggered
@melvinjoseph86 @ShudiLi PTAL, thanks.

Update OCP-11619 for stability

---

features/step_definitions/operators.rb
features/test/operators.feature
lib/openshift/cluster_operator.rb

This check will exit upon the first clusteroperator failure instead of checking more since the timeout is 30 minutes for each.
@weliang1 PTAL, this should address your needs.

added step to check all clusters operators are ready

---

features/build/env.feature

The test case failed as it would try to search for deployment with the name "ruby-hello-world-1". Instead, it created a deployment with the name "ruby-hello-world"

Fixes OCP-11543

---

features/build/buildlogic.feature

It failed while canceling the build as one of the builds would not be canceled. After reducing the number of counts by 1, the tests were successful.

Fixes OCP-24154 and OCP-24158

---

testdata/descheduler/kubedescheduler-4.12.yaml

I see that descheduler upgrade prepare test is failing due to missing testdata file for 4.12, so adding the same. Also some data needs to be updated in 4.11 yaml file so adding the same.

Add testdata for descheduler 4.12 & modify for 4.11

---

features/logging/collector.feature
lib/openshift/cluster_logging.rb

To fix failure:
```
#<RuntimeError: expression returned non-positive status: false left_operand: #<Set:
{"10.143.1.169", "10.143.1.87", "10.143.1.60", "10.143.1.89", "10.143.1.208", "10.143.1.215"}
>, right_operand: #<Set:
{"10.143.1.87", "10.143.1.169", "10.143.1.208", "10.143.1.60", "10.143.1.89", "10.143.1.215", "10.143.1.43"}
> >
features/step_definitions/common.rb:168:in `/^(?:the )?expression should be true> (.+)$/'
```
Some nodes have been scaled up and some nodes have been scaled down before this case, collector pods are running during that period and logs in these nodes are all collected. When executing this case, the nodes in the cluster are not the same as the nodes in ES data, here change to check if the node IPs in ES data contain all the nodes' IP in the cluster. 
Log: …

fix OCPQE-7318

---

lib/webauto/web4cucumber.rb

Fix the issue,
```
01-03 02:05:52.565        [18:05:52] INFO> Launching Chrome
01-03 02:05:52.565        undefined method `gsub' for #<Selenium::WebDriver::Remote::Capabilities:0x0000558616a8e778> (NoMethodError)
01-03 02:05:52.565        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:166:in `new'
01-03 02:05:52.565        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:166:in `browser'
01-03 02:05:52.565        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:505:in `goto_url'
01-03 02:05:52.565        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:255:in `block in run_action'
01-03 02:05:52.565        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:251:in `each' …
```

OCPQE-13355: Fix undefined method 'gsub'

---

lib/polarshift/request.rb
tools/polarshift.rb

@awolffredhat this PR should address your need to reset a polarshift run using CLI.  PTAL.  
```
pruan@fedora ~/workspace/bushslicer (master●)$ ./tools/polarshift.rb reset-run OS-20220526-1835
waiting for operation up to 360 seconds..
[18:23:38] INFO> HTTP GET user@http://localhost:3000/project/OSE/run/OS-20220526-1835
[18:23:38] INFO> HTTP GET took 0.013 sec: 200 OK | application/json 3105 bytes
[18:23:38] INFO> HTTP POST user@http://localhost:3000/project/OSE/run/OS-20220526-1835/records
[18:23:38] INFO> HTTP POST took 0.010 sec: 200 OK | text/plain 1 bytes
[18:23:38] INFO> Run OS-20220526-1835 has been updated to 'Waiting'
pruan@fedora ~/workspace/bushslicer (master●)$ ./tools/polarshift.rb reset-run OS-20220526-1835 --status=Failed
waiting for operation up to 360 seconds..
[18:23:49] …
```

add ability to reset the run-status of a Polarshift run using CLI

---

lib/webauto/web4cucumber.rb

Fix issue
```
INFO> Launching Firefox Marionette/Geckodriver
#<NoMethodError: undefined method `gsub' for #<Selenium::WebDriver::Remote::Capabilities:0x00005630081279b8>>
```
/cc @yapei @xingxingxia @jhou1 @chengzhang1016

OCPQE-13355: Fix undefined method 'gsub' for firefox

---

features/step_definitions/networking.rb
features/upgrade/sdn/sdn2ovn-migration.feature

Automate OCP-54166: CNO support custom OVNKube joint network CIDR
This case is created under features/upgrade/sdn subfolder where the test cases will be used for sdn2ovn migration testing too.  As scripts checked, this case can only be tested by migration testing.
Test log:
prepare before migration:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5367/console
check after migration:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5368/console

Automate OCP-54166

---

features/machine/machine.feature
features/machine/machine_healthcheck.feature
features/machine/machine_misc.feature
features/machine/upi_gcp.feature

PR https://github.com/openshift/verification-tests/pull/3150 try to remove tag hypershift-hosted, but adds unexpected empty line, which break one of our scripts.
```
01-11 13:53:58.693  /home/jenkins/ws/workspace/ocp-tools/sync-tc-tags-to-polarion/lib/gherkin_parse.rb:91:in `block (2 levels) in locations_for': invalid line following OCP-22115 comment:    (RuntimeError)
```
This PR remove those unexpected empty lines.  Will use a follow up PR to fix the script.
@miyadav @jhou1 @sunzhaohua2 @huali9

Remove unexpected empty line before scenario name

---

features/upgrade/machines/machines.feature

Add flaky for OCP-41803, met this cases failed several times, the node became NotReady during/after upgrade, causing the upgrade to fail because of bug https://bugzilla.redhat.com/show_bug.cgi?id=1916575,once this bug is verified, will remove flaky label. @jhou1 @miyadav @huali9 PTAL, thanks!
https://issues.redhat.com/browse/OCPQE-12006
https://issues.redhat.com/browse/OCPQE-11993
https://issues.redhat.com/browse/OCPQE-12680

add flaky for OCP-41803 as of bug 1916575

---

lib/gherkin_parse.rb

When there are empty lines exist before `Scenario` as introduced in https://github.com/openshift/verification-tests/pull/3150, got error,
```
01-11 13:18:23.364  /home/jenkins/ws/workspace/ocp-tools/sync-tc-tags-to-polarion/lib/gherkin_parse.rb:91:in `block (2 levels) in locations_for': invalid line following OCP-28108 comment:    (RuntimeError)
```
The empty lines are removed in https://github.com/openshift/verification-tests/pull/3186, but we should tolerate the empty lines, too.

Skip empty lines when parse scenario name/id

---

features/step_definitions/oauth.rb

to fix https://issues.redhat.com/browse/OCPQE-13518, when oauth operator restart , 400s will timeout . 
@xingxingxia  could you please help review , thanks.

add more time for oauth operator restart

---

features/logging/elasticsearch.feature
features/logging/logging_acceptance.feature
features/step_definitions/logging.rb

Fix failure:
```
And default storageclass is stored in the :default_sc clipboard ==>@  [features/step_definitions/storage_class.rb:225](https://github.com/openshift/verification-tests/blob/dc75f2d8dd581f79b7b5aa3b1b6504722092042c/features/step_definitions/storage_class.rb#L225)
11:30:22 INFO> Shell Commands: oc get storageclasses --output=yaml --kubeconfig=/home/jenkins/agent/workspace/ocp-cucushift-Runner/workdir/ocp4_demouser13.kubeconfig
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
creationTimestamp: "2023-01-11T11:10:21Z"
labels:
local.storage.openshift.io/owner-name: local-block
local.storage.openshift.io/owner-namespace: openshift-local-storage
name: localblock
resourceVersion: "97378"
uid: 9037e643-6372-48dc-bd20-4c2560760e03
provisioner: …
```

fix failure when getting storage class

---

features/networking/service.feature
features/upgrade/sdn/externalIP-upgrade.feature

Resolve externalIP failure in IPv6 single cluster,ticket https://issues.redhat.com/browse/OCPQE-13697.  Moreover, add  timeout to make the case more stable. 
Tested in single IPv6 cluster:
pre-upgrade: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5518/console
post-upgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5519/console
Another updated two cases test logs:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5520/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5521/console
Tested in IPv4 cluster locally as well, all passed.
@openshift/team-sdn-qe  PTAL, thanks!

fix sctp failure in ipv6 single cluster

---

README.adoc

Chrome is the suggested browser from UI team, so update the README to use chrome instead of firefox, to avoid external teams to met unexpected issues when first adapt to cucushift tests.
/cc @yapei @yanpzhan @jhou1 @pruan-rht

Set browser to chrome in README

---

Gemfile

We've been experience breaking UI automation issue several times from selenium-webdriver due to newer version comes out. So we'd like to limit selenium-webdriver to a specific working version to avoid such issue from happening again.
The idea is that we want to limit most of the gems, but change only one gem each time, get it in and let the automation run for a week or two, move to next gem if no issue found/report.
/cc @yapei @yanpzhan @XiyunZhao 
/cc @pruan-rht @jhou1

Limit selenium-webdriver to 4.8.0

---

features/networking/multicast.feature
features/upgrade/sdn/multicast-upgrade.feature

Fix multicast cases failure in single IPv6 cluster. 
Tested in IPv6 single cluster:
pre-upgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5525/console
post-upgrade:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5526/console
Other multicast cases:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5527/console
Tested on ipv4 cluster locally, passed as well.
@openshift/team-sdn-qe  PTAL, thanks!

fix multicast failure in IPv6 single stack cluster

---

Gemfile
lib/webauto/web4cucumber.rb
tools/jenkins/slaves/Dockerfile.centos
tools/jenkins/slaves/Dockerfile.rhel7
tools/jenkins/slaves/Dockerfile.rhel8
tools/openshift-ci/Dockerfile
tools/openshift-ci/Dockerfile.centos

Previously, we use `curl` to download both latest `chromedriver` (required by browser Chrome) and latest `geckodriver` (required by browser Firefox) in the dockerfile/image, no matter whether we are using chrome or firefox for the tests.
According to http://watir.com/guides/drivers/,
We recommend using the [webdrivers gem](https://rubygems.org/gems/webdrivers) to automatically ensure that the latest driver is downloaded, and placed in a location where Selenium can access it.
The version of `chromedriver` will depend on the version of Chrome you are using it with:
For versions >= 70, the downloaded version of `chromedriver` will match the installed version of Google Chrome. More information [here](http://chromedriver.chromium.org/downloads/version-selection).
For versions <= 69, …

Download webdrivers automatically

---

features/step_definitions/helper_services.rb

In case there are feature changes for pod security, reuse existing steps will let us implement the changes in one place (rather than multiple places with the same codes).

Reuse existing steps to add podSecurityLabel to project

---

features/networking/multus.feature

OCP-22504 failed most time in QE-e2e testing recently, but it will passed most time when running locally.
Failed log:
`    [32mWhen I run oc create over "[32m[1m1interface-macvlan-bridge.yaml[0m[0m[32m" replacing paths:[90m                                                                                           # features/step_definitions/cli.rb:60[0m[0m
[32m| ["metadata"]["annotations"]["k8s.v1.cni.cncf.io/networks"] | macvlan-bridge-25657 |[0m
[36m[33m[07:00:10] INFO> {"apiVersion":"v1","kind":"Pod","metadata":{"generateName":"macvlan-bridge-pod-","labels":{"name":"macvlan-bridge-pod"},"annotations":{"k8s.v1.cni.cncf.io/networks":"macvlan-bridge-25657"}},"spec":{"containers":[{"name":"macvlan-bridge-pod","image":"quay.io/openshifttest/hello-sdn@sha256:c89445416459e7adea9a5a …

Remove one check step

---

features/step_definitions/networking.rb

some times the cluster already exit the coredumpctl but not this case related.  So here just add one step to make sure the cluster is normal at the beginnig.
to resolvv https://issues.redhat.com/browse/OCPQE-13897
and with another PR https://github.com/openshift/cucushift/pull/9462

update case 19552

---

features/machine/machine_healthcheck.feature

@jhou1 @sunzhaohua2 @huali9 PTAL , as reported by Zhaohua , this change should fix it . We were checking reconciliation logs earlier, hence it failed .
Validation results - 
```
`      [08:57:13] INFO> Exit Status: 0
cp /home/miyadav/verification/verification-tests/testdata/cloud/mhc/mhc_malformed.yaml mhc_malformed.yaml
Given I obtain test data file "cloud/mhc/mhc_malformed.yaml"                                                                                                # features/step_definitions/file.rb:1
When I run oc create over "mhc_malformed.yaml" replacing paths:                                                                                             # features/step_definitions/cli.rb:60
| n  | openshift-machine-api |
[08:57:13] …
```

mhc webhooks are validating it before pushing to api-server

---

features/step_definitions/networking.rb

According to slack conversation https://redhat-internal.slack.com/archives/GLDDW02SJ/p1676400962812149, update this step step to skip 'not sdn' cluster. 
SDN:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5564/console
OVN: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/5563/console
@openshift/team-sdn-qe  PTAL, thanks!

fix network plugin checking failure

---

lib/rules/web/admin_console/4.10/operator_hub.xyaml
lib/rules/web/admin_console/4.11/operator_hub.xyaml
lib/rules/web/admin_console/4.12/operator_hub.xyaml
lib/rules/web/admin_console/4.13/operator_hub.xyaml
lib/rules/web/admin_console/4.9/operator_hub.xyaml

on 4.13 text "console plugins" becomes "console plugin", remove it form text check. Pass log on 4.13: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/746523/console

update for ocp-41964

---

features/networking/multus.feature

https://github.com/openshift/verification-tests/pull/3215 is not enough to fix https://issues.redhat.com/browse/OCPQE-13866
The step of " And evaluation of `@result[:response].match(/pod\/(.*) created/)[1]` is stored in the :pod_name clipboard" also failed in the latest payload due to the code changing.
The important check for this test case is to make sure the infor of "cannot find a network-attachment-definition" will be displayed when oc describe pod, and this is the last check step in the script.
For above reasons, we can skip the step of " And evaluation of `@result[:response].match(/pod\/(.*) created/)[1]` is stored in the :pod_name clipboard" and just check the pod's description will show the correct error log.
Test log: …

Remove more un-needed checking steps

---

lib/rules/web/admin_console/4.10/check_links.xyaml
lib/rules/web/admin_console/4.11/check_links.xyaml
lib/rules/web/admin_console/4.12/check_links.xyaml
lib/rules/web/admin_console/4.13/check_links.xyaml

The changes are for the update for the download page
Pass log 
4.13: /Runner/751788/console
4.12: /Runner/751790/console
4.10: /Runner/751791/console

Fix the change for OCP-33744

---

lib/webauto/web4cucumber.rb

tries to resolve https://issues.redhat.com/browse/OCPQE-13174, we have seen following error occurring in CI logs quite often 
```
02-27 16:06:46.926        [08:06:41] INFO> embedding "2023-02-27T08:06:41+00:00-screenshot.png"
02-27 16:06:46.926        [08:06:41] INFO> elements..
02-27 16:06:46.926        [08:06:41] INFO> found 1 element elements with selector: {:xpath=>"//button[@data-test-id='perspective-switcher-toggle']"}
02-27 16:06:46.926        Unable to locate element collection from {:xpath=>"//li//h2[contains(., 'Administrator')]"} due to changing page (Watir::Exception::LocatorException)
02-27 16:06:46.926        /home/jenkins/ws/workspace/ocp-common/Runner/lib/webauto/web4cucumber.rb:685:in `get_elements'
02-27 16:06:46.926 …
```

resolve unable to locate element error

---

tools/openshift-ci/Dockerfile

Using curl to download jq from github is not stable enough in Prow steps, which cause installation flaky. Integrate jq in the verification-tests image to avoid the flaky.

OCPQE-14089: Integrate jq in the verification-tests image

---

testdata/descheduler/kubedescheduler-4.13.yaml

Currently testdata file for kubedescheduler 4.13 is missing, so adding the same.

Add testdata file for kubedescheduler 4.13

---

features/step_definitions/machine_set.rb

@huali9 @jhou1 @sunzhaohua2  PTAL , as reported if we have cluster like below - 
> [miyadav@miyadav 1_march]$ oc get machineset
> NAME                         DESIRED   CURRENT   READY   AVAILABLE   AGE
> huliu-gcp1a-82jdt-worker-a   0         0                             3h54m
> huliu-gcp1a-82jdt-worker-b   0         0                             3h54m
> huliu-gcp1a-82jdt-worker-c   0         0                             3h54m
> huliu-gcp1a-82jdt-worker-f   0         0                             3h54m
We were getting `what MachineSetMachineOpenshiftIo are you talking about? (RuntimeError)` error , to mitigate that , made this change.
Don't think it would cause any regression .
Validation : https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runne …

even if replicas is zero , we copy machineset

---

tools/openshift-ci/Dockerfile

Using curl to download yq from github is not stable enough in Prow steps, which cause installation flaky. Integrate yq in the verification-tests image to avoid the flaky.

OCPQE-14089: Integrate yq in the verification-tests image

---

features/step_definitions/networking.rb
features/upgrade/sdn/egress-upgrade.feature

Update existing steps to prepare ovn2sdn automation
OVN migrate to SDN
oc get network.operator cluster  -o jsonpath={.spec.migration.networkType}
return: OpenShiftSDN
SDN migrate to OVN
oc get network.operator cluster  -o jsonpath={.spec.migration.networkType}
return: OVNKubernetes

Prepare ovn2sdn automation

---

features/step_definitions/logging.rb
features/upgrade/logging/upgrade.feature

Many tests failed at:
```
oc exec elasticsearch-cdm-4ht50v5g-3-7ccfc9c895-b9nkb  --kubeconfig=/home/jenkins/ws/workspace/ocp-upgrade/upgrade-producer/workdir/ocp4_admin.kubeconfig -n openshift-logging  --container=elasticsearch -i -- bash -c es_util\ \'--query\=\*/_count\?format\=JSON\'\ -d\ \'\{\"query\":\ \{\"match\":\ \{\"kubernetes.namespace_name\":\ \"logging-upg-prep-1\"\}\}\}\'\ -X\ GET
{"count":0,"_shards":{"total":11,"successful":11,"skipped":0,"failed":0}}
STDERR:
E0301 22:25:20.977300   33592 v2.go:105] read /dev/stdin: resource temporarily unavailable
[22:25:21] INFO> Exit Status: 0
Can't find logs from project 'logging-upg-prep-1' in 600 seconds (RuntimeError)
```
I'm not able to reproduce the failure, here add a step to check pod's status in project 'logging-upg-prep-1' and …

fix OCPQE-14200 and OCPQE-11093

---

testdata/storage/azure-file/azf-rolebind.yaml

The ServiceAccount/persistent-volume-binder is under ns/kube-system.
@liangxia Could you help take a looks?
cc @ropatil010

indent correction

---

features/machine/upi_gcp.feature

According to the webapp, we have lots of 100% failure scenarios, this is a partial attempt to stop executing these tests until they have value again. Please consider re-enabling them provided they are failing due to product bugs or you have an enhancement.
cc @sunilcio @sunzhaohua2 for awareness.

Stop running 100% failing test scenarios, cloud and node

---

features/machine/upi_gcp.feature
features/step_definitions/machine.rb

OCP-34697 and OCP-25034 failed on GCP UPI cluster which has no machineset, 
`Machinesets are not enabled, there are no machines (RuntimeError)`
but for such case, we should skip the test, not reporting error. so update to skip the test cases for such case.
@sunzhaohua2 @miyadav @jhou1 PTAL, thanks!
test cases passed on GCP UPI cluster which has machineset:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/763586/console
test cases skipped on GCP UPI cluster which has no machineset:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/763597/console

skip for no machineset on UPI

---

features/upgrade/machines/machines.feature

@jhou1 @liangxia @miyadav @huali9 PTAl, this is for https://github.com/openshift/release/pull/37261 run machineset scale up/down in prow upgrade jobs.
```
$ bundle exec cucumber --tags '@upgrade-check and @4.12 and @aws-ipi and not @fips and not @customer and not @flaky and not @inactive and not @prod-only and not @qeci and not @security and not @stage-only and @cloud' --dry-run
1 scenario (1 skipped)
```

Add @cloud tag for upgrade case running in Prow

---

testdata/routing/test-client-pod.yaml
testdata/routing/web-server-1.yaml
testdata/routing/web-server-rc.yaml

adding `securityContext.seccompProfile` for some test pods to avoid error message 
```
violates PodSecurity "restricted:latest"
```
when creating the pod resources with admin user in non-default namespace.
@melvinjoseph86 @ShudiLi Please help take a look. Thanks

update securityContext for some test pods

---

features/machine/machine_misc.feature

This was not needed as , it is not returning any cli output which was causing the test case to fail , it was due to earlier [commit](https://github.com/openshift/verification-tests/pull/3244) .
Failures noticed from - http://10.14.89.3:3000/failed_tests , filter using OCP-37744
Here are the failure details due to it - 
```
`      undefined method `[]' for nil:NilClass (NoMethodError)
./features/step_definitions/common.rb:5:in `/^the step should( not)? (succeed|fail)$/'
features/machine/machine_misc.feature:138:in `the step should succeed'`
```
Validation - 
```
`waiting for operation up to 3600 seconds..
When I run the :logs admin command with:                                                                                                                     # …
```

Introduced bug by adding 'succeed' validation

---

features/machine/machine.feature

This case failed on azure private cluster.
`Error from server (providerSpec.publicIP: Forbidden: publicIP is not allowed in Azure disconnected installation with publish strategy as internal): admission webhook "validation.machineset.machine.openshift.io" denied the request: providerSpec.publicIP: Forbidden: publicIP is not allowed in Azure disconnected installation with publish strategy as internal`
This is already covered in [OCP-36489](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-36489) on Azure. and OCP-36489 already automated in golang, in golang, we handle both cases (private and not private).
so remove this case on azure in cucushift.
@sunzhaohua2 @miyadav  @jhou1 PTAL, thanks!

remove OCP-27609 on Azure

---

testdata/routing/test-client-pod.yaml
testdata/routing/web-server-1.yaml
testdata/routing/web-server-rc.yaml

Reverts openshift/verification-tests#3256
I see some errors in 4.9 and the pod cannot be created, so revert the change for now.
```
Error from server (Forbidden): error when creating "web-server-1.yaml": pods "web-server-1" is forbidden: unable to validate against any security context constraint
```
@melvinjoseph86 @ShudiLi PTAL. thanks

Revert "update securityContext for some test pods"

---

features/machine/machine.feature

32269,42346,39639,48464,48463,37132
PR https://github.com/openshift/openshift-tests-private/pull/8114
PR-https://github.com/openshift/openshift-tests-private/pull/8062
PR-https://github.com/openshift/openshift-tests-private/pull/8054/
@sunzhaohua2 @huali9 @jhou1 PTAL , when time permits , there might be few issue we need to handle during cherry-pick to old < 4.10 versions.
multiple tests are covered in one PR to let us remove them from cucushift.

tests removed covered by ginkgo merged PRs

---

features/step_definitions/machine.rb

@sunzhaohua2 @jhou1 @huali9 PTAL 
skipped when no worker machineset present in IPI cluster - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/759563/console
Executed successfully when machineset is present - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/759562/console
this is to mitigate failures due to profile where machineset is removed completely .

 To handle failures in profile with(IPI) but no workers

---

features/step_definitions/networking.rb

The hypershift hosted clusters do not have master nodes, therefore changing the step definition to use multus pod running on specific node.
The step definition change to use multus pod on  worker node other than the one running the back end pod of the service. 
Tested on cluster created with profile private-templates/functionality-testing/aos-4_13/ipi-on-aws/versioned-installer-ovn-hypershift-ci
Test logs can be found here 
http://file.rdu.redhat.com/asood/OCP-41944-hh.log
http://file.rdu.redhat.com/asood/OCP-40908-hh.log
http://file.rdu.redhat.com/asood/OCP-41083-hh.log

Fix for hosted hypershift

---

lib/rules/web/admin_console/4.13/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.14/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPQE-14422
click_actions_button action is used in expire_alert_from_actions action, due to 4.13 UI change, the old xpath would cause case failed, update xpath for click_actions_button due according to 4.13 UI element change
```
expire_alert_from_actions:
action: click_actions_button
action: click_expire_alert_button
click_actions_button:
element:
selector:
xpath: //button[@aria-label='Actions'][@data-test-id='actions-menu-button']
op: click
click_expire_alert_button:
params:
button_text: Expire silence
action: click_button_text 
```
tested along with https://github.com/openshift/cucushift/pull/9498
4.12 runner job passed:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/767262/console
4.13 runner …

update xpath for click_actions_button due to 4.13 UI element change for for OCP-21144/OCP-32857/OCP-32858

---

features/networking/pod.feature
features/upgrade/sdn/policy-upgrade.feature

These tests are have masters dependency and shouldn't be run on hosted clusters

removed hypershift-hosted labels from few cases

---

lib/rules/web/admin_console/4.12/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.13/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.14/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPQE-14398
since 4.12, UI added "Negative matcher" checkbox on "Create silence" page, the element is after "RegEx" checkbox.
the check_use_regular action is used OCP-21363,OCP-21166,OCP-21192 cases and defines as
```
check_use_regular:
element:
selector:
xpath: //span[text()='Alert labels']/ancestor::div[@class='co-m-pane__body-group']//input[@type='checkbox']
op: click
```
since there are 2 checkbox on page now, the action would select the second checkbox  "Negative matcher", not the "RegEx" which we wanted to check.
This PR updates the xpath to strictly select the  "RegEx" checkbox
```
xpath: //span[text()='Alert labels']/ancestor::div[@class='co-m-pane__body-group']//label[text()='RegEx']/input[@type='checkbox']
```
4.12 runner job passed: …

fix check_use_regular xpath for 4.12/4.13/4.14

---

features/upgrade/routing/upgrade.feature

temporarily remove tag due to https://issues.redhat.com/browse/OCPBUGS-10604
@LiangquanLi930 PTAL, thanks

temp remove hypershift-hosted tag from dns upgrade case

---

features/upgrade/routing/upgrade.feature

To address https://issues.redhat.com/browse/OCPQE-14529 
We don't have good way to just skip profile with remote worker in cucushift, so remove tag "baremetal-upi" for now.
In future we can re-implement this case with Ginkgo framework and add logic for remote worker.

fix OCPQE-14529: remote worker issue

---

features/upgrade/sdn/policy-upgrade.feature

Logs before upgrade
bundle exec cucumber features/upgrade/sdn/policy-upgrade.feature:298
<pre>
Now using project "policy-upgrade5" on server "https://api.asood-3241.qe.devcluster.openshift.com:6443".
[15:52:36] INFO> Exit Status: 0
waiting for operation up to 900 seconds..
Given a pod becomes ready with labels:                                                        # features/step_definitions/pod.rb:1
| name=test-pods |
[15:52:37] INFO> oc get pods --output=yaml -l name\=test-pods --kubeconfig=/home/asood/workdir/asood-asoodx/ocp4_admin.kubeconfig -n policy-upgrade5
[15:52:37] INFO> 1 iterations for 1 sec, returned 1 pods, 1 matching
And evaluation of `pod(2).ip_url` is stored in the :p5pod1ip clipboard …

Fix upgrade test to use modified step definition

---

lib/webauto/web4cucumber.rb

In our last fix for chrome crash issue, we added two additional flags `--headless` `--disable-extensions` (they are not the root cause of chrome crash though)
remove them to fix the error on proxy env
```
unknown error: failed to wait for extension background page to load: chrome-extension://aclcanenaacekdmjiifonplhjidphjin/_generated_background_page.html
from unknown error: page could not be found: chrome-extension://aclcanenaacekdmjiifonplhjidphjin/_generated_background_page.html (Selenium::WebDriver::Error::UnknownError)
```
pass log on proxy env: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/771517/console 
pass log on normal env: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/77152 …

fix failed to wait for extension background page to load

---

features/step_definitions/descheduler.rb

with out the fix here i see that test is failing because it is unable to find kubedescheduler cluster object as it is switching over to openshift-monitoring project with the recent updated code.

Update descheduler rb file to have project name

---

lib/rules/web/admin_console/4.14/catalog.xyaml

in OCP 4.14, `Resource type` was shown on the deploy page by default, hence removed the logic to click on `Resource type` button

update rules for deploy from image

---

tools/openshift-ci/Dockerfile

Supports https://github.com/openshift/release/pull/38103, to workaround issue as below, before we submit the fix to openshift-ansible repository (and get their approval).
```
TASK [openshift_node : Get cluster version] ************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_node/tasks/version_checks.yml:4
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: 1007580000
<localhost> EXEC /bin/sh -c 'echo ~1007580000 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /.ansible/tmp `"&& mkdir "` echo /.ansible/tmp/ansible-tmp-1681142912.4549086-776-152307679452199 `" && echo ansible-tmp-1681142912.4549086-776-152307679452199="` echo /.ansible/tmp/ansible-tmp-1681142912.4549086-776-152307679452199 `" ) && sleep 0'
<localhost> …
```

Add write permission for /.ansible

---

tools/openshift-ci/Dockerfile

Support https://github.com/openshift/release/pull/38103 to fix error `fatal: Unable to create '/usr/share/ansible/openshift-ansible/.git/index.lock': Permission denied`
/cc @shellyyang1989 @pruan-rht @jhou1 @JianLi-RH @dis016

Fix permission for folder openshift-ansible

---

tools/openshift-ci/Dockerfile

```
$ git checkout release-4.10
error: pathspec 'release-4.10' did not match any file(s) known to git
```
/cc @gpei @shellyyang1989 @jhou1 @JianLi-RH @pruan-rht @dis016

Remove option depth when git clone as we need the older release branch

---

tools/openshift-ci/Dockerfile

Permission 777 is too open, 
```
[WARNING]: Ansible is being run in a world writable directory
(/usr/share/ansible/openshift-ansible), ignoring it as an ansible.cfg source.
```
/cc @dis016 @pruan-rht @jhou1 @JianLi-RH

Assign proper permission for folder openshift-ansible

---

features/logging/logging_acceptance.feature

When testing on rosa-hypershift-guest cluster, the cluster sometimes doesn't have audit logs, here add a step to make node generates audit logs by adding an audit rule on worker node to monitor the files under `/var/log/pods/` directory. 
/cc @anpingli @IshwarKanse

add step to generate audit logs

---

features/machine/machine.feature
features/step_definitions/machine.rb
lib/openshift/dns.rb

@jhou1 @sunzhaohua2 @huali9  PTAL , this is to fix - one of the case mentioned [here](https://issues.redhat.com/browse/OCPQE-10145?focusedId=22075597&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22075597) 
Validation (For failing cases to make it skip ) - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/784464/console
Regular cases - https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/784463/console
Jenkins flake might cause job to stuck , here is the cluster which confirms creation - 
```
[miyadav@miyadav ~]$ oc get machines
NAME                                  PHASE     TYPE            REGION        ZONE            AGE
default-valued-33056-h2pxx …
```

GCP defaulting machineset creation to skip for clusters when no publicZone exists

---

features/step_definitions/machine.rb

In prow, for aws cluster with rhel nodes, the [rhel nodes are created by machineset](https://github.com/openshift/release/blob/master/ci-operator/step-registry/workers-rhel/aws-provision/workers-rhel-aws-provision-commands.sh) although these nodes are created by machineset, but we can't scaling up directly as some additional steps are required, so I want to skip the test for the clusters with rhel nodes. Now almost all destructive cases failed in [aws-ipi-proxy-sdn-workers-rhel8](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/613/362063/34785011?item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)
@jhou1 @miyadav @huali9 PTAL

skip testing on cluster with rhel nodes

---

features/networking/build.feature
features/networking/operator.feature
features/networking/ovn_winc.feature
features/networking/service.feature

Some of the test authors are no longer on the SDN team, these tests have been failing for a while, making as flaky. Advice to either disable them or rewrite them.
```
case id	subteam	assignee	test type	pass %	failed %	skipped %	limit	date
OCP-10926	SDN	yadu	cucushift	0	0	100	100	2023-03-19
OCP-11335	SDN	yadu	cucushift	0	0	100	100	2023-03-19
OCP-11795	SDN	bmeng	cucushift	0	100	0	100	2023-03-19
OCP-12658	SDN	bmeng	cucushift	0	0	100	100	2023-03-19
OCP-14273	SDN	hongli	cucushift	0	100	0	100	2023-03-19
OCP-15734	SDN	zzhao	cucushift	0	100	0	100	2023-03-19
OCP-15741	SDN	zzhao	cucushift	0	100	0	100	2023-03-19
OCP-24694	SDN	anusaxen	cucushift	0	100	0	100	2023-03-19
OCP-24918	SDN	Anurag Saxena (anusaxen)	cucushift	0	100	0	100	2023-03-19
OCP-25856	SDN	Anurag Saxena (anusaxen)	cucushift	0	100	0	100 …
```

Mark SDN 100% failing scenarios as flaky

---

features/step_definitions/logging.rb

To fix failure: https://redhat-internal.slack.com/archives/CH76YSYSC/p1682476488689379

ignore normal messages when checking logs in ES pod

---

lib/rules/web/admin_console/4.12/catalog.xyaml
lib/rules/web/admin_console/4.13/catalog.xyaml

Remove the logic of "click on Resource type button" in OCP4.13 and 4.12, based on the changes on PR 3292 
Since there is no "resource type" related function on the subsequent version page, only the rule of 4.12&4.13 is updated
Pass log
4.12: Runner/793940
4.13: Runner/793941

Backport change of PR3292

---

features/networking/multus.feature

Case failed in https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-arm64-nightly-baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7/1653874772552978432/artifacts/baremetal-compact-agent-ipv4-static-disconnected-proxy-p1-f7/cucushift-e2e/build-log.txt
Case OCP-22504 is very flaky in CI testing. 
It has 50% pass/fail rate in http://10.14.89.3:3000/prow_test_cases/OCP-22504
But it always passed in manual testing.
Mark this case with label @flaky now.

Make-OCP22504-flaky

---

features/storage/NoDiskConflict.feature
features/storage/cinder.feature
features/storage/cloud_provider.feature
features/storage/csi.feature
features/storage/csi_clone.feature
features/storage/csi_resize.feature
features/storage/csi_snapshot.feature
features/storage/dynamic_provisioning.feature
features/storage/fsType.feature
features/storage/hostpath.feature
features/storage/local-storage-operator.feature
features/storage/negative.feature
features/storage/nfs.feature
features/storage/node_operations.feature
features/storage/persistent_volume.feature
features/storage/pre-bind.feature
features/storage/quota.feature
features/storage/reclaim_policy.feature
features/storage/regression.feature
features/storage/security.feature
features/storage/storage_class.feature
features/storage/storage_object_in_use_protection.feature
features/storage/vsphere.feature

Currently, cucushift has no label to unselect storage cases in baselinecaps-none profiles in CI, which make all cucushift storage cases failed.
This PR is to add storage tag.
See https://issues.redhat.com/browse/OCPQE-15009

Add storage tag

---

lib/rules/web/admin_console/4.10/common_ui_elements.xyaml
lib/rules/web/admin_console/4.11/common_ui_elements.xyaml
lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
lib/rules/web/admin_console/4.9/common_ui_elements.xyaml

added a new rule `click_link_text` which enables user to click on exact text

fix OCP-19722 rules

---

features/upgrade/sdn/multus-upgrade.feature

No need static users for multus upgrade case.
@asood-rh @openshift/team-sdn-qe PTAL
Test log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/6218/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/6219/console

Remove static users for multus upgrade case

---

testdata/networking/sriov/ib/cx5/cx5-ib.yaml

pfname are different in rhel8 (ib0) and rhel9(ibp94s0) to be compatible

add another pfname

---

features/upgrade/cloudcredential/upgrade.feature

CCO doesn't exist on Hypershift hosted cluster so its upgrade tests shall be removed

Remove CCO Upgrade test for Hypershift hosted cluster

---

features/upgrade/machines/machines.feature

Seems this file was missed when we removing @hypershift-hosted tag before https://github.com/openshift/verification-tests/pull/3150 and it's complaining the error now. https://redhat-internal.slack.com/archives/C02JEKXJ3JS/p1684995330315169?thread_ts=1684989779.318769&cid=C02JEKXJ3JS
@sunzhaohua2 @miyadav @jhou1 PTAL, thanks!

remove @hypershift-hosted tag

---

features/upgrade/workloads/scheduler-upgrade.feature

To explicitly trigger a image build process for verification-tests, so that we can bring in code changes in cucushift.

OCPQE-15438: Add subteam and case ID info to scenario name for workloads

---

features/networking/multus.feature

`ip -f inet addr show eth0` cannot be worked for ipv6 single stack cluster. since it's inet6
So here using `ip_url` to be compatible ipv4 and ipv6

update get the eth0 ip address to ipv6 single cluster

---

features/step_definitions/networking.rb

This was a long pending fix as per discussion https://redhat-internal.slack.com/archives/GLDDW02SJ/p1668593109540909
Small change, < 4.13 we have `ovn-kubernetes-master` config map which is helpful is providing kubernetes elected OVN leader but for 4.13+ there is no config map so get lease is only option apparently.
Thanks

Kubernetes elected OVN leader fix to prevent few CI failures

---

features/networking/pod.feature

This is one of the case failing frequently in CI, why? Probably due to race
I was able to repro it once in every 3 runs
```
Given I ensure "<%= cb.host_pod1.name %>" pod is deleted
And a pod becomes ready with labels:
```
The above steps means a pod has been deleted successfully and a new pod readiness is expected as that earlier pod was backed by an rc.
But due to some reason when a pod gets deleted and terminated successfully, the next step is storing old pod name. However if i add a 5 second delay after ensure, its not. So clearly a race among oc get and what api is responding at a certain time. Anyways I don't want to re-invent what ensure step is doing and things after that as such step is being leveraged by other teams in misc scenarios. So simple logic is moving that step later in …

shifting a step later in conntrack case check

---

features/machine/machine_misc.feature

To support vsphere 8 in prow, @miyadav @huali9 PTAL
periodic-ci-openshift-openshift-tests-private-release-4.12-amd64-nightly-vsphere-8-ipi-ovn-etcd-encryption-p2-f14

fix OCP-37180

---

features/upgrade/sdn/policy-upgrade.feature

to resolve this issue https://issues.redhat.com/browse/OCPQE-15646
not sure why pod terminal in that node.  but we better do not specified nodeName in case that node has any issue. 
I guess original want to test the pod can be access in different node.  so here add another multus pod.

remove nodeNmae for rc

---

lib/rules/web/admin_console/4.10/operator_hub.xyaml

on `4.10` the Form/YAML view has different definition
OCP-32151 pass log on 4.10 Runner/817696/console

some rules fixes

---

lib/rules/web/admin_console/4.10/actions.xyaml
lib/rules/web/admin_console/4.11/actions.xyaml
lib/rules/web/admin_console/4.12/actions.xyaml
lib/rules/web/admin_console/4.13/actions.xyaml
lib/rules/web/admin_console/4.14/actions.xyaml

In CI logs, sometimes we can see the element `xpath: //h1[contains(.,'<resource_name>')]/ancestor::tr//td/div[contains(@class,'dropdown')]` can be found but clicking doesn't open the kebab button as we expect
Changed the element definition to `button`

fix kebab action rule

---

features/machine/machine.feature
lib/openshift/machine_machine_openshift_io.rb

Some resource name in clustomer vpc clusters don't have random string, this causing case failed. This pr will fix this issue.
```
errorMessage: 'failed to reconcile machine "default-valued-33058-v4bkl": network.SubnetsClient#Get:
Failure responding to request: StatusCode=404 -- Original Error: autorest/azure:
Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource
''Microsoft.Network/virtualNetworks/sdli-az410-gkkk4-vnet'' under resource group
''sdli-az410-gkkk4-rg'' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"'
errorReason: InvalidConfiguration
```
Before: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/817722/console …

fix OCP-33058 to support customer vpc

---

lib/rules/web/admin_console/4.10/dashboards.xyaml
lib/rules/web/admin_console/4.11/dashboards.xyaml
lib/rules/web/admin_console/4.12/dashboards.xyaml
lib/rules/web/admin_console/4.13/dashboards.xyaml
lib/rules/web/admin_console/4.14/dashboards.xyaml
lib/rules/web/admin_console/4.9/dashboards.xyaml

Add function of send filter option before clicking the button, to make sure the option is listed in the dropdown list
This issue is found in CI failed log, somehow the option of 'download' is not listed in the Workload dropdown list in Observe -> Dashboards page, as below shown:
Pass log:
4.14: /Runner/821829/
4.13: /Runner/821834/
4.12: /Runner/821832/
4.11: /Runner/821833/
4.10: /Runner/821831/
4.9: /Runner/821830/

Optimization OCP-27601 for CI failure

---

doc/prow/query_critical.json

Hypershift wants to run only critical cucushift tests, so add the query to tag test cases with critical.

Add query for critical test cases to support hypershift tests

---

lib/rules/web/admin_console/4.7/dashboards.xyaml
lib/rules/web/admin_console/4.8/dashboards.xyaml
lib/rules/web/admin_console/4.9/dashboards.xyaml
lib/rules/web/admin_console/4.9/operator_hub.xyaml

two affected cases are passing on 4.9 cluster, see /Runner/823214/console (the only failure OCP-24478:UserInterface Configure Knative Serving from Cluster Settings can be ignored since no changes about it)

rule fixes

---

features/cli/deploy.feature
features/cli/oc_import_image.feature
features/cli/oc_volume.feature
features/cli/route.feature
features/cli/serviceaccount.feature
features/step_definitions/cli.rb
lib/rules/cli/4.14.yaml

as of 4.13, The OCP internal registry supports importing images with local reference policy and import mode preserveOriginal, we need to enable it for multi-arch compute nodes clusters.
test job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/827036/console

Fix some cases on multi-arch compute nodes clusters

---

features/upgrade/sdn/service-upgrade.feature

cc @anuragthehatter @zhaozhanqi 
Prepare
<pre>
bundle exec cucumber features/upgrade/sdn/service-upgrade.feature:80
Using the default, devel and _devel profiles...
Feature: service upgrade scenarios
@admin @upgrade-prepare @4.13 @4.12 @4.11 @4.10 @4.9 @4.8 @4.7 @4.6 @vsphere-ipi @openstack-ipi @nutanix-ipi @ibmcloud-ipi @gcp-ipi @baremetal-ipi @azure-ipi @aws-ipi @alicloud-ipi @vsphere-upi @openstack-upi @nutanix-upi @ibmcloud-upi @gcp-upi @baremetal-upi @azure-upi @aws-upi @alicloud-upi @proxy @noproxy @disconnected @connected @upgrade @network-ovnkubernetes @network-openshiftsdn @network-networkpolicy @heterogeneous @arm64 @amd64 @hypershift-hosted
Scenario: Check the nodeport service works well after upgrade - prepare …

Fix the script to use correct node and its IP

---

features/machine/autoscaler.feature

This if for https://issues.redhat.com/browse/OCPQE-15975. Add time to keep consistent with golang https://github.com/openshift/openshift-tests-private/blob/master/test/extended/util/machine_helpers.go#L187
https://github.com/openshift/openshift-tests-private/blob/master/test/extended/util/machine_helpers.go#L244
@sunzhaohua2 @miyadav @jhou1 PTAL, thanks!
without the pr, failed.
```
07-18 14:50:31.146        expression returned non-positive status: false
07-18 14:50:31.146        left_operand: 3, 
07-18 14:50:31.146        right_operand: 1
07-18 14:50:31.146         (RuntimeError)
07-18 14:50:31.146        ./features/step_definitions/common.rb:168:in `/^(?:the )?expression should be true> (.+)$/'
07-18 14:50:31.146        ./features/step_definitions/transform.rb:33:in `call'
07-18 …
```

add time for OCP-28108

---

features/networking/egress-ingress.feature
features/step_definitions/networking.rb
features/upgrade/sdn/egress-upgrade.feature

Egressfirewall/Egressnetworkpolicy cases cannot run on proxy cluster, but was always selected into proxy cluster in CI. I used to update some CI profiles for correct tags but it seems like still having many without correct filters.   In order to let the egressfirewall cases were not affected by that, added a proxy check in our cases to skip the proxy cluster. 
Test log:
proxy cluster: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/6393/console
no proxy cluster:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/6395/console
@zhaozhanqi @anuragthehatter  PTAL, thanks!

add proxy check for egressfirewall

---

lib/rules/web/admin_console/4.6/user_management.xyaml
lib/rules/web/admin_console/4.7/user_management.xyaml

-  The fix only for OCP4.7 and 4.6
-  Add missing function filter_user_from_user_list
Pass log for 4.7: /Runner/845589/
For Ticket: https://issues.redhat.com/browse/OCPQE-16113

Fix OCP-25765 rules miss error

---

lib/rules/web/admin_console/4.6/common_ui_elements.xyaml
lib/rules/web/admin_console/4.6/goto.xyaml
lib/rules/web/admin_console/4.7/common_ui_elements.xyaml
lib/rules/web/admin_console/4.7/goto.xyaml
lib/rules/web/admin_console/4.8/common_ui_elements.xyaml

- Fix only for OCP 4.6, 4.7, 4.8
- For OCP-19653, update rules check_page_match
- For OCP-24306, update rules check_page_match and add goto_cluster_buildconfig_api_explore_page
Pass log for 4.7: Runner/845577/, Runner/846131/
Fix Ticket: https://issues.redhat.com/browse/OCPQE-16111
https://issues.redhat.com/browse/OCPQE-16119
https://issues.redhat.com/browse/OCPQE-16125

Fix OCP-24306 and OCP-19653 rules

---

lib/rules/web/admin_console/4.6/goto.xyaml
lib/rules/web/admin_console/4.7/goto.xyaml

-   Add the miss rule goto_one_daemonsets_page
Pass log for 4.7: Runner/845591/
Resolved Ticket: https://issues.redhat.com/browse/OCPQE-16115

Fix OCP19817 miss rule issue in 4.6 4.7

---

lib/rules/web/admin_console/4.6/projects.xyaml
lib/rules/web/admin_console/4.7/projects.xyaml

-   Changes are only for OCP 4.6 and 4.7
-   Update two functions check_memory_data_for_one_project_in_table & check_cpu_data_for_one_project_in_table
-   The action of filter_by_name is updated in PR#3399
The case pass in local, as PR#3399 is not merged yet, so could not provide Jenkins pass log
Ticket: https://issues.redhat.com/browse/OCPQE-16127

Update rule for OCP-26984

---

features/networking/ovn_ipsec.feature

IBMCloud uses NAT-T NAT traversal UDP encapsulation because it can't use ESP
https://issues.redhat.com/browse/SDN-2629

SDN-3800: disable IPsec ESP tests on IBMCloud 

---

features/step_definitions/networking.rb

using `ip -4` is not suitable for ipv6 singlestack cluster. 
Consider for ovn, it's always using 'br-ex' as default, here update using br-ex directly. 

update the default interface

---

tools/jenkins/slaves/Dockerfile.rhel8

```
+ curl -sSL https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
+ bsdtar --no-same-owner --no-same-permissions -xvf - -C /usr/local/bin
x chromedriver-linux64/LICENSE.chromedriver
x chromedriver-linux64/chromedriver
......
+ chmod +x /usr/local/bin/chromedriver /usr/local/bin/geckodriver
chmod: cannot access '/usr/local/bin/chromedriver': No such file or directory
```

Fix path for chromedriver

---

tools/openshift-ci/Dockerfile

```
And I open admin console in a browser
Message:
session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.110 with binary path /usr/bin/google-chrome (Selenium::WebDriver::Error::SessionNotCreatedError)
```
```
+ CHROME_VERSION=116.0.5845.96
+ npx @puppeteer/browsers install chrome@116.0.5845.96
npm WARN exec The following package was not found and will be installed: @puppeteer/browsers@1.7.0
chrome@116.0.5845.96 /chrome/linux-116.0.5845.96/chrome-linux64/chrome
npm notice
npm notice New minor version of npm available! 9.6.7 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice
+ npx @puppeteer/browsers install …
```

Fix "Selenium::WebDriver::Error::SessionNotCreatedError"

---

tools/openshift-ci/Dockerfile

```
Scenario: OCP-25816:UserInterface Expose console_url metrics in console-operator metric
And I open admin console in a browser
Message:
Unable to find chromedriver. Please download the server from
https://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH.
More info at https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/?language=ruby.
(Selenium::WebDriver::Error::WebDriverError)
./lib/webauto/web4cucumber.rb:151:in `new'
./lib/webauto/web4cucumber.rb:151:in `browser'
./lib/webauto/web4cucumber.rb:490:in `goto_url'
./lib/webauto/web4cucumber.rb:240:in `block in run_action'
./lib/webauto/web4cucumber.rb:236:in `each'
./lib/webauto/web4cucumber.rb:236:in `run_action'
./features/step_definitions/admin_console.rb:25:in `/^I open …
```

OCPQE-16557: [ProwCI] Add chromedriver into PATH

---

tools/jenkins/slaves/Dockerfile.rhel8

```
08-28 05:24:50.296        [05:24:49] INFO> Launching Chrome
08-28 05:24:50.296        unknown error: Chrome failed to start: exited abnormally.
08-28 05:24:50.296          (unknown error: DevToolsActivePort file doesn't exist)
08-28 05:24:50.296          (The process started from chrome location /chrome/chrome-linux64/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Selenium::WebDriver::Error::UnknownError)
```
The `chrome` installed via `npx` does not work well with `selenium-webdriver (4.8.0)`. And we can not bump up selenium-webdriver due to the requirement of ruby 3.0+ since 4.9.1
So revert the old way to install `chrome`, and using the new way to install `chromedriver`.
The image build passed (with chrome 116.0.5845.110-1 and chromedriver …

OCPQE-16557: Fix chrome and chromedriver

---

lib/rules/web/admin_console/4.14/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPQE-16575
due to 4.14 UI changes, the 4 cases failed at "silence_alert_from_detail_if" action, root cause is in check_silence_detail action
```
check_silence_detail:
element:
selector:
xpath: //span[text()='Silence details']
```
4.13 xpath
```
<h2 class="co-section-heading" data-test-section-heading="Silence details"><span class="">Silence details</span></h2>
```
4.14 changed to
```
<h2 class="co-section-heading" data-test-section-heading="Silence details">Silence details</h2>
```
update xpath for 4.14 only to
```
check_silence_detail:
element:
selector:
xpath: //h2[@class='co-section-heading' and text()='Silence details']
```
runner job passed:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/853 …

Fix check silence detail xpath for 4.14 due to UI change

---

lib/rules/web/admin_console/base/logout.xyaml

Replace ruby regex which often fail in jenkins. 
log on 4.14: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/853360/console

fix OCP-22330

---

lib/rules/web/admin_console/4.14/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPQE-16577, OCP-29300 failed due to 4.14 UI change.
update xpath for "uncheck_start_from_now" and "ensure_start_from_now_checked" actions , the only change is changed from `span` to `h2` in 4.14
```
uncheck_start_from_now:
element:
selector:
xpath: //h2[text()='Duration']/ancestor::div[@class='co-m-pane__body-group']//input[@type='checkbox']
op: click
```
and
```
ensure_start_from_now_checked:
element:
selector:
xpath: //h2[text()='Duration']/ancestor::div[@class='co-m-pane__body-group']//input[@type='checkbox'][@checked]
```
runner job passed:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/854012/console

Fix OCP-29300 due to 4.14 UI change

---

features/storage/NoDiskConflict.feature
features/storage/cloud_provider.feature
features/storage/csi.feature
features/storage/csi_resize.feature
features/storage/csi_snapshot.feature
features/storage/dynamic_provisioning.feature
features/storage/fsType.feature
features/storage/hostpath.feature
features/storage/negative.feature
features/storage/nfs.feature
features/storage/node_operations.feature
features/storage/persistent_volume.feature
features/storage/pre-bind.feature
features/storage/quota.feature
features/storage/reclaim_policy.feature
features/storage/regression.feature
features/storage/security.feature
features/storage/storage_class.feature

Adding "rosa/osd/aro" for service clusters, in our ci we will filter the case with platform, so it is safe to add this "@rosa @osd_ccs @aro".

Adding rosa/osd/aro tag

---

features/step_definitions/networking.rb

Post OVN IC, ovnkube-master ds is gone
Improving this step to check `ovnkube-node` ds regardless of releases while `ovnkube-master` ds only on < 4.14

improved ovn functional step

---

features/storage/security.feature

- For several storage new added CI profiles we changed the default storageClass to the fileshare one, then some cases which use the default storageClass still want to provision a block volume/ volume securify check will be failed.
- https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/all/430754
- Create a new block storageclass used by pvcs do the tests
`Runner-v3-smoke/6589/console`
```console
57 steps (57 passed)
2m8.348s
```

OCPQE-16695: Fix OCP-9699

---

features/step_definitions/storage_class.rb

- After CSI Migration the default volumeType change to 'gp3', but most aws local zones nodes/outposts clusters don't support gp3 type volume, many cases use the `creates new in-tree storageclass` step maybe failed .
- Use gp2 type create aws in-tree storageclass
`Runner-v3-smoke/6619/console`
```console
[06:44:04] INFO> === End After Scenario: OCP-17563:Storage Using multiple block volumes ===
14 steps (14 passed)
```

Fix: use gp2 type create aws in-tree storageclass

---

features/step_definitions/helper_services.rb

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/857223/console
@kasturinarra  to fix https://issues.redhat.com/browse/OCPQE-16763 , that's because https://issues.redhat.com/browse/IR-300 , we need to use `oc create deployment` to replace the `oc new-app` for multi-arch cluster .

replace newapp by create for registry app server

---

features/cli/serviceaccount.feature

Changing to deployment instead of using deploymentconfig to avoid failure error message:` Error from server (NotFound): the server could not find the requested resource (post deploymentconfigs.apps.openshift.io)`
Execution Result : job/Runner/861032/console

[OCP-10642] Remove deploymentconfig checks to streamline baselinecaps tests

---

tools/jenkins/slaves/Dockerfile.rhel8
tools/openshift-ci/Dockerfile

This reverts commit 90708dff0e3e351610ce09eb447ded7a99e818c0.
Still not working as expected,
```
session not created: Chrome failed to start: exited normally.
(session not created: DevToolsActivePort file doesn't exist)
(The process started from chrome location /usr/local/bin/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Selenium::WebDriver::Error::SessionNotCreatedError)
```

Revert "Use fixed chromedriver/chrome 117.0.5938.88 (#3440)"

---

tools/jenkins/slaves/Dockerfile.rhel8
tools/openshift-ci/Dockerfile

When installing nodejs via `curl --silent --location https://rpm.nodesource.com/setup_18.x | bash -`, the install succeed, however, we got below warning info,
```
================================================================================
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
================================================================================
SCRIPT DEPRECATION WARNING                    
This script, located at https://rpm.nodesource.com/setup_X, used to
install Node.js is deprecated now and will eventually be made inactive.
Please visit the NodeSource distributions Github and follow the
instructions to migrate your repo.
https://github.com/nodesource/distributions
The NodeSource Node.js Linux distributions GitHub repository …
```

Use the supported way to install nodejs

---

Gemfile

with latest version of active support  observing the below error in runner jobs.
/cc @pruan-rht @liangxia @JianLi-RH @jhou1 @mffiedler 
https://redhat-internal.slack.com/archives/CH76YSYSC/p1696593330277919 
/usr/share/gems/gems/activesupport-7.1.0/lib/active_support/core_ext/time/conversions.rb:62:in `<class:Time>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
Did you mean?  deprecate_constant

add specific version of active support

---

features/logging/cluster_logging_operator.feature

Fix Logging case OCP-33721.
The graph has been renamed to "FluentD Buffer Usage" and the query has been fixed to show the maximum buffer usage.
Bug: [LOG-4578](https://issues.redhat.com/browse/LOG-4578)
Smoke test: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/866304/

Update OCP-33721 after LOG-4578 fix

---

lib/launchers/openstack.rb
tools/cloud_watch.rb
tools/resource_monitor.rb

adding watch for Openstack usage and post warnings to a new dedicated channel #ocpqe_cloud_usage.  Currently it only prints out a warning message when it's over 95% and there's no auto removal of staled volume PTAL.  @liangxia @jiajliu @duanwei33

added support for monitoring openstack usage

---

features/step_definitions/storage_class.rb

Hi Team, 
PTAL. 
Fix for: https://issues.redhat.com/browse/OCPQE-17051 
Failure log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/864376/console
10-02 13:06:49.454        Unsupported platform `none` (RuntimeError)
10-02 13:06:49.454        /home/jenkins/ws/workspace/ocp-common/Runner/features/step_definitions/storage_class.rb:251:in `/^admin creates new in-tree storageclass with:$/'
10-02 13:06:49.454        features/tierN/storage/dynamic_provisioning.feature:192:in `admin creates new in-tree 
10-02 13:07:01.608  1 scenario (1 failed)
10-02 13:07:01.608  14 steps (1 failed, 12 skipped, 1 passed)
Jenkins logs to skip for None platform:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/8643 …

fix none platform

---

features/machine/machine.feature
lib/openshift/machine_machine_openshift_io.rb
testdata/cloud/ms-vsphere/ms_default_values.yaml

OCP-33380 and OCP-35421 failed because the networkName is not right, change it to get from machine. @sunzhaohua2 @miyadav @jhou1 PTAL, thanks!
before change the machine created failed and the cases failed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/874198/console
after change, the cases pass: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/874457/console
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/874459/console

get networkName

---

features/storage/storage_class.feature

- After [STOR-1061](https://issues.redhat.com/browse/STOR-1061) complete, when cluster have multiple storage classe, it won't be broken for the non specified storage class provision, it will use the latest created one(storage class createTimestamp newest) provision the pv. So we should remove the versions 4.13-4.15 for this test case.

OCPQE-17806: Update OCP-12226 support versions

---

features/step_definitions/helper_services.rb

Flake record on `profilename:78_IPI on OSP & Set default node selector on manila nic` (testrun:20231016-1323)
```console
#<RuntimeError: iSCSI pod did not become ready>
[features/step_definitions/helper_services.rb:534](https://github.com/openshift/verification-tests/blob/9ac66de42237607da56a48350d2ed1757f3cdcb9/features/step_definitions/helper_services.rb#L534):in `/^I have a iSCSI setup in the environment$/'
[features/tierN/storage/iscsi.feature:92](https://github.com/openshift/cucushift/blob/9ac66de42237607da56a48350d2ed1757f3cdcb9/features/tierN/storage/iscsi.feature#L92):in `I have a iSCSI setup in the environment'
apiVersion: v1
kind: Pod
metadata:
annotations:
openshift.io/description: iscsi target
openshift.io/scc: node-exporter
creationTimestamp: "2023-10-16T14:35:11Z"
labels: …
```

OCPQE-17366: Fix iSCSI cases failed on defaultNodeSelector enabled cluster

---

lib/rules/web/admin_console/OWNERS

Since @yapei is on maternity leave, add @yanpzhan as another approvers for admin_console.
/cc @yufchang @pruan-rht @jhou1

Add yanpzhan as approvers for admin_console

---

features/upgrade/storage/OWNERS

So that storage team can self approve their PRs.

Add OWNERS for storage upgrade

---

features/upgrade/node/hpa/upgrade.feature

add tag 4.13,4.15 to support upgrade path 4.13 and 4.15 for OCP-13016. 
(the job [https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/all/473748](url) failed due to the case OCP-13016 is not executed in ccushift-prepare step [https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.13-gcp-ipi-ovn-ipsec-f28/1728672649476837376/artifacts/gcp-ipi-ovn-ipsec-f28/cucushift-upgrade-prepare/build-log.txt](url))

fix OCP-13016

---

tools/jenkins_mongo.rb

previously, the code was just assuming the port to be the standard.   @liangxia @dis016 PTAL

use the port information in the config.yaml to access mongodb

---

features/step_definitions/pod.rb

to debug the failure https://issues.redhat.com/browse/OCPQE-3204. 
@kasturinarra Please help review ,  no idea why the build pod not present, so add check the project events .

add get events for pod not present

---

features/upgrade/storage/upgrade.feature

- The prepare case OCP-23501 is not executed in [cucushift-upgrade-prepare step](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.13-gcp-ipi-ovn-ipsec-f28/1728672649476837376/artifacts/gcp-ipi-ovn-ipsec-f28/cucushift-upgrade-prepare/), this is the reason why failed in [cucushift-upgrade-check step](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.13-amd64-nightly-4.13-upgrade-from-stable-4.13-gcp-ipi-ovn-ipsec-f28/1728672649476837376/artifacts/gcp-ipi-ovn-ipsec-f28/cucushift-upgrade-check/), the job upgrade path is from 4.13-stable to 4.13 nightly …

OCPQE-17992: Fix OCP-23501

---

features/routing/haproxy-router.feature
features/routing/route.feature
features/routing/timeout.feature
features/routing/websocket.feature

remove hypershift-hosted tag from cucushift cases which using client pod inside the cluster
@lihongan @melvinjoseph86 please help review the changes, thanks.

updated for OCPQE-18363(remove hypershift-hosted tag)  for verification-tests

---

lib/rules/web/admin_console/4.15/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPQE-18274
1. update 4.15 xpath for "Clear all filters"
2. add set_span_class action, since set_input_class action is defined in https://github.com/openshift/verification-tests/blob/master/lib/rules/web/admin_console/4.15/common_ui_elements.xyaml#L266, don't want to change it.
3. add timeout: 60 for click_actions_button action
4. add wait_exipre_silence_loaded action to wait for "Expire silence" button shows, and use the action in expire_alert_from_actions action

Fix 415 UI cases due to changes

---

lib/rules/web/admin_console/4.15/monitoring_metrics.xyaml

see from https://issues.redhat.com/browse/OCPQE-18472
update xpath for click_pod_chart_link, and click_pod_chart_link action is only used in OCP-21263, so it won't affect other cases
runner job passed:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/890212/console

update xpath for click_pod_chart_link for OCP-21263

---

lib/rules/web/admin_console/4.15/style.xyaml
lib/rules/web/admin_console/4.16/style.xyaml

see from https://issues.redhat.com/browse/OCPQE-18476
xpath for check_chart_using_victory is changed since 4.15, this PR updates the xpath for 4.15
runner job passed:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/891522/console
also update it for 4.16, the master branch is 4.16 now

update xpath for check_chart_using_victory

---

lib/rules/web/admin_console/4.16/monitoring_metrics.xyaml

https://github.com/openshift/verification-tests/pull/3497 is merged to
4.15: https://github.com/openshift/verification-tests/blob/master/lib/rules/web/admin_console/4.15/monitoring_metrics.xyaml#L298
but not merged to 4.16
4.16: https://github.com/openshift/verification-tests/blob/master/lib/rules/web/admin_console/4.16/monitoring_metrics.xyaml#L298
this PR updates the change to 4.16
passed on 4.16 runner job:
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/891589/console

merge #3497 to 4.16

---

tools/jenkins/slaves/Dockerfile.rhel8
tools/openshift-ci/Dockerfile

The old way to install nodejs got error,
```
+ yum -y install nodejs --setopt=nodesource-nodejs.module_hotfixes=1
Nsolid Packages for Linux RPM based distros - x 564 kB/s | 146 kB     00:00    
Node.js Packages for Linux RPM based distros -  2.0 MB/s | 700 kB     00:00    
Dependencies resolved.
======================================================================================== 
Package               Arch    Version                          Repository          Size
========================================================================================
Installing:
nodejs                x86_64  2:18.19.0-1nodesource            nodesource-nodejs   34 M
Installing dependencies:
platform-python-pip   noarch  9.0.3-23.el8                     baseos             1.7 M 
python3-pip …
```

OCPQE-18716: Install nodejs from Red Hat

---

lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
lib/rules/web/admin_console/4.16/common_ui_elements.xyaml

-   update rule of check_column_header/missing
-   update xpath, changing from relative checking to absolute checking
When checking whether the 'Namespaces column' is included in Installed operator page for a specific namespace. the relative checking will bring error as below:
`[07:39:32] INFO> running web action check_column_header_missing ... 
[07:39:32] INFO> element..
[07:39:32] INFO> found 1 element elements with selector: {:xpath=>"//th[contains(@data-label,\"Namespace\")]"}
[07:39:33] INFO> found 1 element elements with selector: {:xpath=>"//th[contains(@data-label,\"Namespace\")]"}
`
Pass log: job/Runner/894907/

Fix OCP-29724 in 4.15&4.16

---

lib/polarshift/test_record.rb

With the latest rail builds, the formatlinks render the link correctly now.  The hack is messing up the rendering actually, so I'm taking it out.  I verified this by editing the comments section from the Polarshift UI.  For more details, please refer https://issues.redhat.com/browse/OCPQE-18927.

fix issues with link rendering

---

features/storage/vsphere.feature

**Root Cause**
From 4.13 all fresh installed vsphere ocp clusters enabled CSIMigration, the diskformat parameter will be not supported.
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/release-2.4/docs/book/features/vsphere_csi_migration.md#things-to-consider-before-turning-on-migration-
Falke recore -> `testrun:20240126-1132`
**Fix solution**
Exclude vSphere CSI unsupported scenarios for 4.13 above
Reminder to @Phaow update the polarion as well after it merged.

OCPQE-19162: Exclude vSphere CSI unsupported scenarios for 4.13 above

---

features/cli/deploy.feature

with the existing code test fails with error to reterieve `application-template-stibuild.json` fixing the code to make sure that the json file is retreived well.
Run logs: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/905649/console

Fix failure for case OCP-16443

---

features/networking/multus.feature

Fix Failure breakdown for polarion run '20240205-0719'
Test log for OCP-46116:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/7164/console
Test log for OCP-24467:https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/7166/console

Update OCP-46116 and OCP-24467

---

features/networking/ovn_ipsec.feature
features/networking/service.feature

IPSec was never supported on hosted clusters so we need to remove this tag.
Also marking a case inactive where we never saw any issue since 4.2+

IPsec not supported on Hosted and inactive case

---

features/admin/scc.feature
features/cli/deploy.feature
features/cli/oc_patch_apply.feature
features/cli/oc_volume.feature
features/cli/resources.feature
features/cli/secrets.feature

Adding https://github.com/workloads so that these cases will be excluded when running a cluster with profile baselinecaps set to none.

Adding @workloads tag

---

lib/rules/web/admin_console/4.15/dashboards.xyaml
lib/rules/web/admin_console/4.16/dashboards.xyaml
lib/rules/web/admin_console/4.16/operator_hub.xyaml

according to https://issues.redhat.com/browse/OCPBUGS-25878, monitoring charts has no plan to migrate to PF5 as of now, so fix the rules

fix OCP-27901

---

features/networking/ovn_ipsec.feature

Due to changes in IPsec features in version 4.15 and the presence of different configurations for enabling/disabling IPsec at runtime, just remove tag @4.16 and @4.15  
New OCP-71024 is for testing enable/disable IPsec at runtime for version 4.15 and beyond

OCP-40569 will not be supported after 4.15

---

features/step_definitions/networking.rb

As see http://ocpqe-webapp-aosqe.apps.ocp-c1.prod.psi.redhat.com/prow_test_cases/OCP-37591,  step `the IPsec is enabled on the cluster` failed in 4.15+ non-ipsec clusters. Fixed it.
4.15+
ipsec enable cluster,passed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/915369/console
non-ipsec cluster,skipped: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/915350/console
before  4.15
ipsec enabled cluster, passed: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/915360/console
non-ipsec enabled cluster,skipped: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/915373/console …

fix ipsec checking function

---

features/networking/ovn.feature

For cases tagged with @hypershift-hosed, `Given the env is using "OVNKubernetes" networkType` don;t make sense as hosted cluster has no network operator and since cases are tagged as @network-ovnkubernetes already, that makes the step redundant @openshift/team-sdn-qe PTAL

redundant step

---

features/networking/metrics.feature

Couple of cases needs to be deprecated until 4.13 as metrics on 4.14+ (IC) are being tracked under https://github.com/openshift/openshift-tests-private/blob/release-4.14/test/extended/networking/metrics.go

limiting metrics cases until 4.13

---

features/networking/sctp.feature

As we moved  OCP-29645 to go in https://github.com/openshift/openshift-tests-private/blob/master/test/extended/networking/sctp-dualstack.go#L504, remove tags from cucushift.
@zhaozhanqi @anuragthehatter PTAL, thanks!

remove some version tags for OCP-29645

---

features/upgrade/workloads/descheduler-upgrade.feature

From 4.15 kubedescheduler operator version has changed from 4.x to 5.x, adding new case to ensure that the validation works and removing 4.15 & 4.16 from tag from the old case.

Update right version for kubedescheduler

---

lib/rules/web/admin_console/4.16/goto.xyaml

While running [openshift/cucushift](https://github.com/openshift/cucushift) tests from `features/tierN`.  Following test case fails due to incorrect URL.
```
features/tierN/web/monitoring/query-browser.feature:587 # Scenario: OCP-21263:ClusterObservability Show correct and same CPU/Memory/Filesystem usage both in prometheus and Grafana UI 
```
Updating the monitoring dashboard's `k8s-resources-pod` URL for OCP 4.16.0 release.
cc: @aleskandro

Update dashboard URL for OCP 4.16

---

features/upgrade/workloads/descheduler-upgrade.feature

Removing 4.15 & 4.16 tags because from 4.15 descheduler is being released via CPASS and not part of ocp corepayload so will move the upgrade testing for these versions to golang.
cc: @dis016

Removing 4.15 and 4.16 tags

---

features/machine/machine.feature

@sunzhaohua2 @huali9 @shellyyang1989 @liangxia , @jhou1 PTAL when time permits 
from 4.14 it is in [ginkgo](https://github.com/openshift/openshift-tests-private/blob/release-4.14/test/extended/clusterinfrastructure/machines.go)

this is converted to ginkgo from 4.14 onwards

---

features/routing/operator.feature

OCP-27594 is shifted to ginkgo framework(https://github.com/openshift/openshift-tests-private/pull/15812 ), removed executing this case from 4.12+
@lihongan @ShudiLi  please help review the update, thanks.

removing ocp-27594 from 4.12+ branches

---

features/networking/sdn.feature

Updating test case OCP-25933 to grep correct veth interfaces.
cc: @aleskandro

Updating OCP-25933 for ppc64le

---

features/step_definitions/networking.rb

as this cases `Allow_from_router_network_policy_allows_traffic_from_router` always be chosen by the test run on cloud provider even though the tag for cloud platform is not exit.   here replace the raise the error using skip cases scenarios 
https://s3.upshift.redhat.com/cucushift-html-logs/logs/2024/04/12/01%3A48%3A33/Allow_from_router_network_policy_allows_traffic_from_router-OCP-40898_SDN_router-ingress?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=OFB641O8HD3MWZW5AUE3%2F20240415%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240415T064928Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a76ebd07cc3ac25725126ebfcaf72844734fe68e867abdea444b744ccee3b454
@asood-rh @openshift/team-sdn-qe ^^

replace raise error with skip cases

---

lib/openshift/service_account.rb

There are failures for `Given I find a bearer token of the demo service account` due to the `map` method is applied on a `nil`. The failure stack:
```
Given I find a bearer token of the demo service account                                                                     # features/step_definitions/user.rb:25
undefined method `map' for nil:NilClass (NoMethodError)
/verification-tests/lib/openshift/service_account.rb:36:in `get_secret_names'
/verification-tests/lib/openshift/service_account.rb:41:in `get_secrets'
/verification-tests/lib/openshift/service_account.rb:29:in `load_bearer_tokens'
/verification-tests/features/step_definitions/user.rb:26:in `/^I find a bearer token of the(?: (.+?))? service account$/'
features/cli/serviceaccount.feature:31:in `I find a bearer token of the demo …
```

OCPQE-21203: Fix get_secret_names undefined method `map' for nil when image registry is disabled

---

lib/rules/web/admin_console/4.11/goto.xyaml
lib/rules/web/admin_console/4.12/goto.xyaml
lib/rules/web/admin_console/4.13/goto.xyaml
lib/rules/web/admin_console/4.14/goto.xyaml
lib/rules/web/admin_console/4.15/goto.xyaml
lib/rules/web/admin_console/4.16/goto.xyaml

"wait_box_loaded" will check table loaded, but some clusters have not machineconfigpool listed. Replace it with other selector.
pass log on 4.16 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/942624/console 
@yapei

fix OCP-22308

---

features/networking/isolation.feature
features/networking/ovn.feature

Those two test cases were missed when batch add case ID and subteam info to the test name.

Add case ID and subteam info

---

features/storage/csi.feature

**Root cause**
- OCP-34144 check the CSI Driver Operator installation should be excluded for hcp jobs since the csi driver controller and operator are in the control plane which only could be access from mgmt cluster
[failure record](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/1260/557050/69991570/69992557/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26launchesLimit%3D1000%26isLatest%3Dfalse%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D1%26filter.in.issueType%3Dti001%252Cti_1hrghcxlbgshc%252Cti_s4scyws6guht%252Cti_sok676b1k8j5%252Cti_r1ifkmkw19o1%26filter.cnt.name%3D%253AStorage)
```console
$ oc -n clusters-hypershift-ci-282780 get po | grep 'aws-ebs-csi-' …
```

OCPQE-22037: Exclude OCP-34144 for hcp

---

lib/rules/web/admin_console/4.14/operator_hub.xyaml
lib/rules/web/admin_console/4.15/operator_hub.xyaml
lib/rules/web/admin_console/4.16/operator_hub.xyaml

- According to the new change in OCPBUGS-32741- Change the display text of the filtering option for FIPS to “Designed for FIPS, 
- The changes will impact 4.16, 4.15, 4.14
Pass log: 
4.16:job/Runner/957154/

Update rule for OCP-29198

---

lib/environment.rb

To support https://github.com/openshift/release/pull/51675
Follow up of https://github.com/openshift/verification-tests/pull/3600, as we also need this for projects created for "oc debug"

Workaround for wrong oc client version in 'oc debug'

---

lib/rules/web/admin_console/4.13/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.14/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.15/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.16/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.17/monitoring_alerts.xyaml

see from [OCPQE-22458](https://issues.redhat.com/browse/OCPQE-22458)
change in https://github.com/openshift/verification-tests/pull/3593 caused OCP-32858,OCP-21144,OCP-32857 failed. revert the xpath for `click_actions_button:` from
`xpath: //button[contains(@class,'dropdown__toggle')]`
to
`xpath: //button[@class='pf-c-dropdown__toggle']`
would make the cases passed. details please see from [OCPQE-22458](https://issues.redhat.com/browse/OCPQE-22458)
[4.13 runner job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/965186/console) passed
[4.14 runner job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/965187/console) passed
[4.15 runner …

revert change in #3593

---

features/step_definitions/storage_class.rb

[Flake record](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/1198/485118?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26launchesLimit%3D1000%26isLatest%3Dfalse%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D1%26filter.in.issueType%3Dti001%252Cti_1hrghcxlbgshc%252Cti_s4scyws6guht%252Cti_sok676b1k8j5%252Cti_r1ifkmkw19o1%26filter.cnt.name%3D%253AStorage) 
```console
Message: failed OCP-22018:Storage Admin can change default storage class to non-default
Type: failed
Text:
Scenario: OCP-22018:Storage Admin can change default storage class to non-default
And the output should contain 1 times:
Message:
$ omc get sc
No resources storageclasses.storage.k8s.io found in default namespace. 
```
**Root …

OCPQE-18518: Fix OCP-22018 flake on external

---

features/machine/autoscaler.feature
features/machine/machine.feature
features/machine/machine_healthcheck.feature
features/machine/machine_misc.feature
features/machine/upi_gcp.feature
features/networking/operator.feature
features/upgrade/machines/machines.feature

As IBMCloud/gcp will not delete the resources that prefix is not infrastructureName, so if the cases were interrupted due to some reason like timeout, the resources will not be removed automatically when destroy cluster. This will update all machineset name prefix with infrastructureName. cc @MayXuQQ
@huali9 @miyadav @shellyyang1989 PTAL
OCP-25436 https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/964372/console

OCPQE-21298: Update machineset name with infrastructureName

---

Gemfile
tools/jenkins/slaves/Dockerfile.rhel8

This is part of the effort to migrate our CI tool chains off ocp-c1 cluster.
I'm trying to build the Jenkins agent images on the gpc cluster, and got
```
+ gem install reportportal-1.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing reportportal-1.0.gem:
ffi requires RubyGems version >= 3.3.22. The current RubyGems version is 3.1.6. Try 'gem update --system' to update RubyGems itself.
```
Following the advice, and run `gem update --system`,
```
bash-4.4# gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
ERROR:  While executing gem ... (NoMethodError)
undefined method `version' for nil:NilClass
```
I think we don't have the plan to …

OCPQE-22529: Remove reportportal-agent-ruby from Jenkins agents

---

tools/openshift-ci/Dockerfile

centos:stream8 reach EOL on May 31.
As a follow up of https://github.com/openshift/release/pull/52933

OCPQE-22684: Switch base image from centos:stream8 to rhel-8

---

features/step_definitions/web.rb
lib/admin_credentials.rb
test/lib/launchers/o_c_m_cluster_test.rb

Since ruby 2.2.0 File.exists? is deprecated use instead File.exist?  Although older ruby has been lenient with this deprecation, for ruby > 3.2 this will be flagged as an error.  @liangxia PTAL.
https://ruby-doc.org/core-2.2.0/File.html#exist-3F-method

udpate method name to exist, instead of the deprecated exists

---

tools/openshift-ci/Dockerfile

Log [link](https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/pr-logs/pull/openshift_release/53079/rehearse-53079-periodic-ci-openshift-openshift-tests-private-release-4.16-automated-release-azure-ipi-marketplace-mini-perm-f360/1800737927513247744/artifacts/azure-ipi-marketplace-mini-perm-f360/cucushift-e2e/build-log.txt), 
```
+ cucumber --tags '@4.16 and @amd64 and @azure-ipi and @network-ovnkubernetes and not @fips and @level0 and not @customer
and not @flaky
and not @inactive
and not @prod-only
and not @qeci
and not @security
and not @stage-only
and not @upgrade-check
and not @upgrade-prepare
and not @destructive and not @long-duration and ((@console and @smoke) or @serial)' -p junit
warning: unable to access '/opt/app-root/src/.config/git/config': …
```

Fix warning: unable to access '/opt/app-root/src/.config/git/config'

---

tools/openshift-ci/Dockerfile

Since https://github.com/openshift/verification-tests/pull/3613, several cucushift-upgrade prow ci steps hit such issues:
```
Extracting oc
error: reading registries.conf.d: lstat /opt/app-root/src/.config/containers/registries.conf.d: permission denied
```
Manually reproduce it locally.
```
$ podman run --rm -ti --entrypoint /bin/bash --user 1001:1001 registry.ci.openshift.org/ci/verification-tests:latest
bash-4.4$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.16.0-rc.3-x86_64
error: reading registries.conf.d: lstat /opt/app-root/src/.config/containers/registries.conf.d: permission denied
bash-4.4$ ls .config/
ls: cannot open directory '.config/': Permission denied
bash-4.4$ ls -ld .config
drwx------. 3 root root 25 Jun 11 09:34 .config
```
If run the container using …

OCPQE-22684: fix permission issue of loading .config/containers/registries.conf.d

---

tools/jenkins/slaves/Dockerfile.gpc.rhel8

Building base image is a little different on OCP-C1 and GPC cluster. So add a new dockerfile for building the image on GPC, to not interfere with OCP-C1.

OCPQE-22529: Add dockerfile for base image on GPC cluster

---

features/step_definitions/env.rb

print out actual master version to help with debugging.
current error message is `master version not >= 4.5`
new error message is something like `master version '4.16.0-rc.6' not >= '4.26'`

print out actual master version

---

features/networking/multicast.feature
features/step_definitions/networking.rb

1.  the match should be `5/0/100%` not `5/0/0%` when the package is lost 100%
2.  Sometimes the result has not output yet. so here check the following will be pass. But actually it's not. 
```
And the output should not match:
| <%= cb.pod1ip %>.*multicast, xmt/rcv/%loss = 5/0/100% |
| <%= cb.pod2ip %>.*multicast, xmt/rcv/%loss = 5/0/100% |
```
so here we need to make sure the result is existing firstly.
```      
| <%= cb.pod1ip %>.*multicast, xmt/rcv/%loss |
| <%= cb.pod2ip %>.*multicast, xmt/rcv/%loss |
```
3.  Update the annatation with overwrite=true

update multicast receive packet not 100 lost

---

features/storage/persistent_volume.feature

I don't believe these PV negative cases warrant a "critical" designation. We don't need to include them in the critical CI profiles, so let's remove them.

remove @critical to some persistent_volume cases

---

features/cli/serviceaccount.feature

@xingxingxia Please help review this PR to skip auth cap failure due to missing ImageRegistry baseline capabilities
Below is the execution result:
With enabled baselinecap ImageRegistry: https://privatebin.corp.redhat.com/?d9be5ce58aa8e22a#Q2qxSXkv2qp7XXpz28QBnDVTJrrvL5m5zg64KEZb9t4 
Without enabled baselinecap ImageRegistry: https://privatebin.corp.redhat.com/?44a4ba7072b0638f#BY2ELCtn3CZem6rFAn7xZrB9LUBmCr4qaYiXnoTvuuxP

[OCPQE-22132] Skip auth missing ImageRegistry baselinecap test failure

---

tools/jenkins/slaves/Dockerfile.gpc.rhel8

Even though Fedora EPEL repository's configuration points to an HTTPS location, the default location of `mirrors.fedoraproject.org` is a redirect service that redirects to a close-by but non-deterministic mirror. It's hard to define the ingress/egress rules for a non-deterministic url. Since most of the mirrors urls are Denied by default, it loops though those mirrors which take a long time (more than an hour) to get repo/packages info.
This PR aims to help in pinning down the repository location to a known FQDN `mirrors.edge.kernel.org`, so it can be set in the allowlists, without affecting the performance of downloads.
I've tested this, with another change in the gitlab  (merge_requests/2244 in the jcasc repo), the time cost in command `dnf install xxx` from epel decreased from hours to …

OCPQE-22529: Pin down epel repository location

---

lib/launchers/openstack.rb

the method to get volume url has been broken for almost two months due to changed in the volume type name from 'volume2' to 'volume3'

volume type name changed over a month ago

---

features/step_definitions/oauth.rb
features/step_definitions/operators.rb
features/test/operators.feature

Sometimes there were failures like [OCPQE-24496](https://issues.redhat.com//browse/OCPQE-24496). For such, it is often due to other system issue, for example, some master nodes may be not Ready, et al ..., therefore the auth pods on some master nodes are Pending or so. Thus adding such debugging info via this PR to easier exclude auth cause.
Test demo log: /job/Runner-v3-smoke/7616/console as below
```
Given operator "authentication" becomes available/non-progressing/non-degraded within 30 seconds # features/step_definitions/operators.rb:188
[09:59:54] INFO> #### Operator authentication Expected conditions: {"Available"=>"True", "Progressing"=>"False", "Degraded"=>"False"}
[09:59:54] INFO> #### After 1.0035127690061927 seconds and 1 iterations operator authentication becomes: …
```

[OCPQE-24496] Add pods/nodes debugging info when clusteroperator does not transition to expected status

---

features/networking/multus.feature

Test case randomly failed as mentioned in https://redhat-internal.slack.com/archives/GLDDW02SJ/p1723794433778909
Add cleanup steps to delete addintionalnetworks configuration in CNO.
Test log: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/7645/console

Defer additionalnetworks configuration

---

features/step_definitions/node.rb
features/step_definitions/project.rb

Hi Team, 
PR fix for: https://issues.redhat.com/browse/OCPQE-25056
2 Solutions on TC: OCP-18737, 
1. Add toleration to pods/deployment
2. Deploy the pods on non tainted nodes: Implemented this one currently
Jenkins Logs:
oc get nodes | grep "worker"
NAME                          STATUS   ROLES                  AGE     VERSION
ip-10-0-128-33.ec2.internal   Ready    edge,worker,wscan      5h49m   v1.30.3
ip-10-0-52-209.ec2.internal   Ready    worker,wscan           6h6m    v1.30.3
ip-10-0-79-213.ec2.internal   Ready    worker,wscan           6h7m    v1.30.3
ip-10-0-95-138.ec2.internal   Ready    worker,wscan           6h6m    v1.30.3
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1022559/console
Pod got deployed on node: …

[storage] [hotfix] [OCP-18737,OCP-14665,OCP-14673]

---

lib/rules/web/admin_console/4.17/monitoring_metrics.xyaml

see https://issues.redhat.com/browse/OCPQE-25335, OCP-44791 failed in 4.17 due to 4.17 UI change, update 4.17 xpath for choose_metrics_query and click_metrics_query_dropdown action for OCP-44791

update 4.17 xpath for choose_metrics_query and click_metrics_query_dropdown action for OCP-44791

---

features/routing/haproxy-router.feature

OCP-11619 is shifted to ginkgo framework(https://github.com/openshift/openshift-tests-private/pull/19337), removed executing this case from 4.12+
@lihongan @ShudiLi @rhamini3 please help review the update, thanks.

removing ocp-11619 from 4.12+ branches

---

features/upgrade/monitoring/monitoring-upgrade.feature

alertmanager API version v1 is deprecated, use v1 would get deprecated error now, change to v2 version
```
$ token=`oc create token prometheus-k8s -n openshift-monitoring`
$ oc -n openshift-monitoring exec -c prometheus prometheus-k8s-0 -- curl -k -H "Authorization: Bearer $token" 'https://alertmanager-main.openshift-monitoring.svc:9094/api/v1/alerts'
"status":"deprecated","error":"The Alertmanager v1 API was deprecated in version 0.16.0 and is removed as of version 0.28.0 - please use the equivalent route in the v2 API"}
```
no issue with v2
```
$ oc -n openshift-monitoring exec -c prometheus prometheus-k8s-0 -- curl -k -H "Authorization: Bearer $token" 'https://alertmanager-main.openshift-monitoring.svc:9094/api/v2/alerts'
[{"annotations":{"description":"Failure to retrieve updates …
```

update alertmanager API version to v2

---

features/networking/service.feature

A non-relevant usecase for hosted cluster scenario due to masters absense. The funcationality however is being checked in various cases in [private repro](https://github.com/openshift/openshift-tests-private/blob/19ba5d028e4ecfb5855927582c7c64f8ef2d34f9/test/extended/networking/services.go) though 

Non relevant case for Hosted cluster

---

README.md

Transform `.adoc` to `.md` format, and add section for "create local dev in container".
Referenced from doc https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Add readme for "create local dev env in container"

---

features/routing/timeout.feature

Converted OCP-11635 to GO for releases 4.12-4.18
https://issues.redhat.com/browse/OCPQE-20374

remove tags for releases converted to GO

---

features/step_definitions/helper_services.rb
features/step_definitions/pv.rb

**Root cause**
- ipv6 address with port needs add '[]' to meet the ipv6 standard.
[failure record](https://reportportal-openshift.apps.ocp-c1.prod.psi.redhat.com/ui/#prow/launches/1572/639299/90583247/90583460/log?item0Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26launchesLimit%3D1000%26isLatest%3Dfalse%26filter.in.status%3DFAILED%252CINTERRUPTED%26page.page%3D1%26filter.in.issueType%3Dti001%252Cti_1hrghcxlbgshc%252Cti_s4scyws6guht%252Cti_sok676b1k8j5%252Cti_r1ifkmkw19o1%26filter.cnt.name%3D%253AStorage)
```console
[36m---[0m
[36mapiVersion: v1[0m
[36mkind: PersistentVolume[0m
[36mmetadata:[0m
[36m  name: pv-rvp0m[0m
[36mspec:[0m
[36m  capacity:[0m
[36m    storage: 5Gi[0m
[36m  accessModes:[0m
[36m  - ReadWriteOnce[0m
[36m …
```

OCPQE-26258: Fix: iscsi targetPortal format for ipv6

---

features/upgrade/api_auth/upgrade.feature
features/upgrade/cloudcredential/upgrade.feature
features/upgrade/machines/machines.feature
features/upgrade/monitoring/monitoring-upgrade.feature
features/upgrade/node/hpa/upgrade.feature
features/upgrade/node/node-upgrade.feature
features/upgrade/node/scc.feature
features/upgrade/routing/upgrade.feature
features/upgrade/sdn/externalIP-upgrade.feature
features/upgrade/sdn/ipsec-upgrade.feature
features/upgrade/sdn/multicast-upgrade.feature
features/upgrade/sdn/multus-upgrade.feature
features/upgrade/sdn/policy-upgrade.feature
features/upgrade/sdn/service-upgrade.feature
features/upgrade/security_compliance/fips.feature
features/upgrade/storage/upgrade.feature
features/upgrade/workloads/oc-upgrade.feature

Several upgrade test cases are missing the version tag 4.17/4.18

Add version tags to several upgrade test cases

---

features/upgrade/node/hpa/upgrade.feature

This fixes the inconsistency in test preparation and test execution.
@liangxia @jiajliu @JianLi-RH @dis016 @weinliu PTAL
--- 
Failure: https://qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.17-aws-ipi-disc-priv-sts-ep-fips-f28/1858044038981095424

Fix node's prepare scenario not in sync with test scenario

---

features/machine/machine_misc.feature

the test sometimes takes 13 mins for pod to provision post password change , it is causing to show failures when there is no issue functionally 
```
`miyadav@miyadav-thinkpadx1carbongen8:~/vsphere$ oc get pods
NAME                                                 READY   STATUS    RESTARTS       AGE
cluster-autoscaler-operator-6c875884bd-d2dsl         2/2     Running   1 (107m ago)   122m
cluster-baremetal-operator-7d69448795-94hqh          2/2     Running   1 (107m ago)   123m
control-plane-machine-set-operator-c96b97f4b-fbkjj   1/1     Running   1 (107m ago)   123m
machine-api-controllers-6f89cc6d8c-4qpnd             7/7     Running   0              14m
machine-api-operator-5c98b8cd69-74w7m                2/2     Running   1 (108m ago)   123m
mypod …
```

Added flaky to test as it is too slow

---

lib/rules/web/admin_console/4.18/monitoring_alerts.xyaml

see from https://issues.redhat.com/browse/OCPBUGS-44797
4.18 OCP-29300 is failed due to click_actions_button action for 4.18+, debugged, need to update the xpath for it, only affect 4.18+, also update click_duration_dropdown_button xpath

fix OCP-29300 for 4.18+

---

lib/rules/web/admin_console/4.18/monitoring_alerts.xyaml

see [OCPBUGS-44797](https://issues.redhat.com/browse/OCPBUGS-44797), to fix OCP-32857 error, need to update click_alert_filter_item action for 4.18+, update xpath from
```
xpath: //input[@id='<filter_item>'] 
```
to
```
xpath: //label[@id='<filter_item>'] 
```
can fix the issue.
4.18 [runner job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1071678/console) passed

fix OCP-32857 for 4.18+

---

.editorconfig
tools/cmd/check-upgrade-tags/main.go

The tag mismatch between `upgrade-prepare` and `upgrade-check` cause upgrade CI jobs to fail, and then affect auto-release jobs. So add this tool to check upgrade tags.
Local usage,
```
$ find features/upgrade/ -name "*.feature" -exec go run tools/cmd/check-upgrade-tags/main.go {} \;
```
After this PR merged, I'd like to introduce a new job into OpenShift CI to gate the PR merge in this repo whenever there are changes in folder `features/upgrade`

Add tool to check upgrade tags

---

testdata/authorization/scc/PodSecurityPolicyReview.json
testdata/authorization/scc/PodSecurityPolicySubjectReview.json
testdata/authorization/scc/PodSecurityPolicySubjectReview_privileged_false.json
testdata/authorization/scc/PodSecurityPolicySubjectReview_privileged_true.json

Due to the 4.18 rebase PR https://github.com/openshift/openshift-apiserver/pull/458 brought API changes to the PodSecurityPolicyXXXXReview resources, related Auth cases failed; checked the response body when it failed, it showed like:
```
The PodSecurityPolicySelfSubjectReview "" is invalid: metadata: Invalid value: v1.ObjectMeta{Name:"pspsr", ...}: must be empty
```
https://github.com/openshift/openshift-apiserver/pull/458/files indeed introduced the `must be empty` validations.
Fixing it by removing .metadata from the test files.
Tested both 4.17 and 4.18. Both passed:
4.17 logs /job/ocp-common/job/Runner/1073944/console
4.18 logs /job/ocp-common/job/Runner/1073943/console

OCPQE-27132: Fix for PodSecurityXXXReview due to 4.18 APIs change

---

features/routing/route.feature

After Migrating tests to Ginkgo, removing the tags on the cucushift repo
JIRA: https://issues.redhat.com/browse/OCPQE-26803

removing tags for insecureEdge tests for OCPQE-26803

---

features/step_definitions/project.rb

Hi Team,
Fix for the issue: https://issues.redhat.com/browse/OCPQE-27283. PTAL. 
It is selecting random schedulable worker node instead from the saved clipboard nodes 
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1076543/console
12-02 13:14:01.893        [07:43:45] INFO> Exit Status: 0
12-02 13:14:01.893        [07:43:46] INFO> here checking !!!!!!!! ropatil-122az1-jtxss-ingress-4nfvw
12-02 13:14:01.893        [07:43:46] INFO> here checking !!!!!!!! ropatil-122az1-jtxss-worker-westus-89f9g
12-02 13:14:01.893        [07:43:46] INFO> here checking !!!!!!!! ropatil-122az1-jtxss-ingress-4nfvw
12-02 13:14:01.893        [07:43:46] INFO> here checking !!!!!!!! ropatil-122az1-jtxss-worker-westus-89f9g
12-02 13:14:01.894        [07:43:47] INFO> …

fix [ocp-14665, 14673] select nodes from clipboard

---

features/step_definitions/oauth.rb

In 4.18+, with OCPBUGS-45051 fix, given the auth operator reports Progressing=False for a rollout, the Terminating (Running) old-generation operand pod should already disappear. In https://github.com/openshift/cucushift/pull/8378 years earlier, noticed this issue, but didn't consider it a bug. This PR covers the bug fix in auto for all cases that trigger auth rollout and wait for Progress=False (i.e. those that call `And authentication successfully rolls out after config changes` step).
4.18 pass log: /job/ocp-common/job/Runner/1077780/console (no Terminating, i.e. running pod of old generation)
4.17 pass log: /job/ocp-common/job/Runner/1077782/console (no bug fix backport to 4.17 thus the issue is still seen, as the pasted log snippet as below)
```
12-04 16:24:43.646        [08:24:34] …
```

Update e2e tests for progressing=false checkpoint for OCPBUGS-23435 bug fix

---

features/cli/pod.feature

This case failed many times in 4.18 due to error like: 
STDERR:
error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead
This pr fix above error and test passed in https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/1078232/

Fix OCP-11055

---

features/upgrade/machines/machines.feature

Found a small typo in our upgrade scenarios.  Using it to test out the newly added presubmit check job, [check-upgrade-tags](https://github.com/openshift/release/pull/59493).
Currently the job is optional, we will move it as gate jobs ( must pass ) after several verification PRs.

Verify presubmit job check-upgrade-tags

---

features/machine/machine_misc.feature

The in-tree to out-tree migration resulted in below change . 
Validation - https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1081033/console
```
`curl -H "Authorization: Bearer xxxxxxxxxxxxxxx" https://prometheus-k8s-openshift-monitoring.apps.miyadav-1112v.qe.devcluster.openshift.com/api/v1/query?query=vsphere_vcenter_info --insecure
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"vsphere_vcenter_info","api_version":"8.0.3.0","build":"24322831","container":"vsphere-problem-detector-operator","endpoint":"vsphere-metrics","instance":"10.130.0.17:8444","job":"vsphere-problem-detector-metrics","namespace":"openshift-cluster-storage-operator","pod":"vsphere-problem-detector-operator-867cb6c87d-c7g4j","service":"vsphere-prob …
```

OCPBUGS-42799 - modifying metrics name

---

features/cli/secrets.feature

These 2 cases failed many times in 4.18 due to error like:
STDERR:
error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead
This pr fix above error and test passed in https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1080972/

fix OCP-12281 and OCP-12310

---

lib/rules/web/admin_console/4.12/common_ui_elements.xyaml
lib/rules/web/admin_console/4.13/common_ui_elements.xyaml
lib/rules/web/admin_console/4.14/common_ui_elements.xyaml
lib/rules/web/admin_console/4.15/common_ui_elements.xyaml
lib/rules/web/admin_console/4.16/common_ui_elements.xyaml
lib/rules/web/admin_console/4.17/common_ui_elements.xyaml
lib/rules/web/admin_console/4.18/common_ui_elements.xyaml
lib/rules/web/admin_console/4.19/common_ui_elements.xyaml

Fixes https://issues.redhat.com/browse/OCPQE-27746
some unexpected Close button got matched so closing doesn't happen as we expected, thus case fail
updated xpath rules to make the matching unique

fix some rules

---

lib/rules/web/admin_console/4.18/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see https://issues.redhat.com/browse/OCPBUGS-47492, due to 4.18+ UI change, update set_silence_duration_null xpath for 4.18/4.19, 4.19 also updated click_duration_dropdown_button due to 4.19 UI change only
[4.18 runner job](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1087067/console) passed
[4.19 runner job](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1087071/console) passed

update set_silence_duration_null xpath for 4.18/4.19

---

features/machine/machine_misc.feature

@sunzhaohua2 @huali9 PTAL when time permits . 
for Cucushift test failures on OCP 4.18(ppc64le) installed using Agent Based Installer the infra was None , yet our test was executing and getting failed .

skip case if infrastructure is none

---

features/upgrade/node/node-upgrade.feature

in 4.17 and 4.18, the kubeletconfig format changed from json to yaml, this pr fix the issue.
Test passed in https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1081067/console

fix the format of output for OCP-13022

---

features/step_definitions/node.rb
features/test/fips.feature

This PR adds support to check a cluster's FIPS status and save it to the global @clipboard[:fips_enabled] variable without exiting the step.  This minor feature is requested by @ropatil010.  PTAL @liangxia

added steps to support FIPS check without exiting

---

features/upgrade/sdn/externalIP-upgrade.feature

Remove ocp44790 from 4.19 and 4.18, will cover it in ginkgo framework, then we can test UDN and default network together, please refer to PR https://github.com/openshift/openshift-tests-private/pull/23027
@openshift/team-sdn-qe PTAL, thanks a lot!

remove ocp44790 from 4.19 and 4.18

---

features/machine/machine.feature

Based on failures mentioned in Jira , we think it is ok to remove hypershift-hosted tags for these test.
@sunzhaohua2 @huali9 PTAL , when time permits.

OCPQE-28450 remove tag for hypershift hosted cluster

---

features/step_definitions/helper_services.rb

Failed to contact to ldap server on ipv6 due to the ipv4 adress hard code 
```
Shell Commands: oc exec ldapserver  --kubeconfig=/tmp/dir8/workdir/ocp4_testuser-8.kubeconfig -n stx3u  -i -- ldapadd -x -h 127.0.0.1 -p 389 -D cn\=Manager,dc\=example,dc\=com -w admin␛[0m␛[0m
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
```
```
cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

OCPQE-28472: Update ldap server contact for ipv6

---

lib/rules/web/admin_console/4.19/check_links.xyaml

Update 26910 as UI removed developer perspective in OCP4.19 only
Pass log: /Runner/1108310/
For ticket: https://issues.redhat.com/browse/OCPQE-28643 and https://issues.redhat.com/browse/OCPQE-28611

Update 26910 as UI removed developer perspective

---

lib/rules/web/admin_console/base/logout.xyaml

Fix OCP-22330 & 22640 dropdown xpath on 4.19
Pass log: job/Runner/1110608/   (OCP-22330)
job/Runner/1110619/   (OCP-22640)
For ticket: https://issues.redhat.com/browse/OCPQE-28734

Fix OCP-22330 & OCP-22640 dropdown xpath on 4.19

---

lib/rules/web/admin_console/4.19/node.xyaml

Fix OCP-23044 Xpath for 'edit node taints' on 4.19
Pass log: job/Runner/1110647/
For ticket: https://issues.redhat.com/browse/OCPQE-28736

Fix OCP-23044 edit node taints xpath on 4.19

---

lib/rules/web/admin_console/4.19/overview.xyaml

Update Xpath for OCP-27586 on 4.19
Note: OCP-29799 is affected by this change, and since multiple parts need to be updated for that case. The update will be submitted in a separate PR
Pass log: /job/Runner/1113513/

Update Xpath for OCP-27586 on 4.19

---

lib/rules/web/admin_console/4.19/environments.xyaml

Update Xpath for OCP-20954 on 4.19 
- The issue occurs because two elements match on the page, causing the dropdown click action to fail
Pass log: job/Runner/1113814/
For ticket: https://issues.redhat.com/browse/OCPQE-28877

Update Xpath for OCP-20954 on 4.19

---

lib/rules/web/admin_console/4.19/route.xyaml

Added action for OCP-19608 on 4.19 to fix the dropdown menu not closing without the click, it will impact to click the 'Clear All Filters' button
Pass log:job/Runner/1113826/
For ticket: https://issues.redhat.com/browse/OCPQE-28886

Add action for OCP-19608 on 4.19

---

lib/rules/web/admin_console/4.19/route.xyaml

Remove pf-v5 from OCP-42112 & OCP-26040 on 4.19
Pass log: job/Runner/1114111/
For ticket: https://issues.redhat.com/browse/OCPQE-28965

Remove pf-v5 from OCP-42112 & OCP-26040 on 4.19

---

features/networking/ovn_ipsec.feature
features/upgrade/sdn/ipsec-upgrade.feature

As all the ipsec cases have been moved to go, removing the 4.15+ tags from ipsec cases
@anuragthehatter @zhaozhanqi PTAL, thanks!

remove 4.15+ tags from ipsec

---

features/step_definitions/machine.rb

@huali9 @miyadav PTAL
discussion https://redhat-internal.slack.com/archives/CH76YSYSC/p1744944722558809
Example job: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1115414/console 
Fix job: https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1115415/console
```
04-18 17:32:38.169        [09:32:37] WARN> There are rhel nodes and rhel nodes may created by machineset, tests running by copying existing machinesets will fail.
04-18 17:32:38.169        [09:32:37] WARN> We will skip this scenario, even though it is IPI deployment
```

skip rhel nodes only for versions < 4.19

---

features/storage/csi_resize.feature

- In 4.19 we enable the recover the resize failure feature gate by default which makes resize failure message changes a bit.
https://github.com/openshift/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L2426-L2434
<details> <summary>Click to expand full logs</summary>
```console
$ cucumber ./features/storage/csi_resize.feature:109
Using the default, devel and _devel profiles...
Feature: CSI Resizing related feature
@singlenode @proxy @noproxy @disconnected @connected @network-ovnkubernetes @network-openshiftsdn @s390x @ppc64le @heterogeneous @arm64 @amd64 @4.19 @4.18 @4.17 @4.16 @4.15 @4.14 @4.13 @4.12 @4.11 @4.10 @4.9 @4.8 @4.7 @4.6 @storage
Scenario Outline: Resize negative test                                    # ./features/storage/csi_resize.feature:77
Given I have a …
```

OCPQE-29446: fix OCP-25809 resize failure message check

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see from
https://issues.redhat.com/browse/OCPBUGS-55802
https://issues.redhat.com/browse/OCPQE-29279
this PR fix OCP-32857 due to 4.19 UI changes
changes: 
1. 4.19 xpath for Disable_all_filters changed, the xpath now is updated to `//button/span[text()='Clear all filters']`
2. 4.19 xpath for click_alert_link_with_text changed, the xpath now is updated to `//a[text()='<alert_name>' and @data-test-id='alert-resource-link' and contains(@href, '/monitoring/alerts')]`
3. added expand_alert_button action to open_alert_detail
4. updated input_silence_comments action
5. updated xpath for status_specific_alert_no_clear to `//tbody[@class='pf-v6-c-table__tbody']//td[text()='<status>'][1]`
6. added click_silence_link_with_text action and replaced click_alert_link_with_text action in …

fix OCP-32857 due to 4.19 UI change

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see [MON-4236](https://issues.redhat.com/browse/MON-4236), fix error for OCP-29300
this PR fixed xpath for click_duration_dropdown_button and set_silence_duration_null

fix xpath for OCP-29300

---

features/routing/rate-limit.feature

Removing rate limit tests from cucushift repo due to migration into ginkgo
JIRA: https://issues.redhat.com/browse/OCPQE-29445 
CC @melvinjoseph86 @ShudiLi @lihongan

remove rate limit tests due to migration OCPQE-29445

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see [MON-4241](https://issues.redhat.com/browse/MON-4241)
fix OCP-21334 due to 4.19 UI change
this PR updates
1. update xpath for status_specific_alert action
2. update aria_label_text for click_first_action_icon action

fix OCP-21334 due to 4.19 UI change

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see [MON-4250](https://issues.redhat.com/browse/MON-4250)
this PR updates:
1. added click_alertrules_link_with_text action and replaced click_alert_link_with_text for open_alertrules_detail action
2. added set_until_input_simple action and replaced set_label_input_simple for set_invalid_end_time_silence action
4.19 runner [job](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1115975/console) passed

fix xpath for OCP-21150/OCP-29061 due to 4.19 UI changes

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see [MON-4252](https://issues.redhat.com/browse/MON-4252)
this PR updates:
1. xpath for check_rule_name action
2. xpath for check_silence_name action
3. update text for check_view_metrics and click_view_metric actions
4. fix typo

update xpath for OCP-21132/OCP-21192 due to 4.19 UI changes

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.19/monitoring_metrics.xyaml

see [MON-4253](https://issues.redhat.com/browse/MON-4253)
this PR updated:
1. updated xpath for click_chart_zoom_dropdown,click_zoom_value_button,click_reset_zoom_button,check_zoom_value actions
2. updated xpath for check_specific_alert action

fix OCP-24601/OCP-32859 due to 4.19 UI change

---

lib/rules/web/admin_console/4.19/monitoring_metrics.xyaml

see [MON-4258](https://issues.redhat.com/browse/MON-4258)
click_run_queries_button action missed op: click in PR: https://github.com/openshift/verification-tests/commit/1fe63f62e411f15719ad2e5436a49694c93feb72
this PR added "op: click" for click_run_queries_button action, and click_run_queries_button is only used for OCP-43747 now, won't affect other cases
4.19 runner [job](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1116066/console) passed

add "op: click" for click_run_queries_button action

---

lib/rules/web/admin_console/4.19/monitoring_alerts.xyaml

see [MON-4259](https://issues.redhat.com/browse/MON-4259)
this PR added expand_alert_button action to open_alert_detail_href action
4.19 runner [job](https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/Runner/1116069/console) passed

add expand_alert_button action to open_alert_detail_href

---

features/routing/haproxy-router.feature

Since OCP-10043 and OCP-11679 were migrated(https://github.com/openshift/openshift-tests-private/pull/25777), removed them from the verification-tests
@lihongan @melvinjoseph86 @rhamini3 please help review, thanks.

removed OCP-10043 and OCP-11679

---

testdata/infrastructure/cluster-capacity/cluster-capacity-configmap.yaml

add `terminationGracePeriodSeconds: 30` for small-pod spec to fix stage testing failure mentioned in [OCPBUGS-53048](https://issues.redhat.com/browse/OCPBUGS-53048)

OCPBUGS-53048 add spec.terminationGracePeriodSeconds with default value 30s

---

features/cli/limits.feature

We need the case_id and subteam info to group the tests and that determines how it's displayed in ReportPortal.

Add case_id and subteam info for OCP-12286

---

features/cli/oc_volume.feature
features/storage/NoDiskConflict.feature
features/storage/cinder.feature
features/storage/cloud_provider.feature
features/storage/csi.feature
features/storage/csi_clone.feature
features/storage/csi_resize.feature
features/storage/csi_snapshot.feature
features/storage/dynamic_provisioning.feature
features/storage/fsType.feature
features/storage/hostpath.feature
features/storage/nfs.feature
features/storage/node_operations.feature
features/storage/persistent_volume.feature
features/storage/pre-bind.feature
features/storage/quota.feature
features/storage/regression.feature
features/storage/security.feature
features/storage/storage_class.feature

We will deprecate storage cucushift cases from 4.20, so we will remove the tags.

STOR-2505: remove 4.20 tag for storage cases
