openshift/verification-tests

config/config.yaml

hotfix, didn't realize old format will make the same object and then 
further config will apply to both places where it should only apply to one of them

avoid making AWS and AWS-CI the same object

---

features/step_definitions/pv.rb

@akostadinov @pruan-rht Trying to add some negative coverage to persistent volume. Logger is enough, raise will fail the negative scenarios.

Log error is enough when failed to create pv

---

Gemfile
lib/webauto/web4cucumber.rb
tools/jenkins/slaves/Dockerfile

Seeingsome failures in smoke runs related to webdriver-browser communication. I think updating web gems can help this. Also ff legacy is unreliable and we don't use it anymore. It doesn't work with the new gems.

update webauto libs and remove ureliable ff legacy support

---

tools/openshift-ci/Dockerfile.centos

By using this base image, we will make sure that we are using the latest origin clients as well. Suggested by @kargakis [here](https://github.com/openshift/verification-tests/pull/37#discussion_r239776599)

change base and remove oc installation

---

tools/openshift-ci/Dockerfile.centos

We already copy the oc client in the runtime. There is no need to base on `origin-cli`
https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml#L64-L72
https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-src.yaml#L106

Change base to centos.

---

config/config.yaml
lib/admin_credentials.rb

https://projects.engineering.redhat.com/browse/OPENSHIFTQ-12575

ocp4 admin credentials

---

lib/environment.rb
lib/host.rb
lib/openshift/node.rb
lib/ssh.rb

first it is not necessary to specify all nodes in host spec.
nodes with missing hosts will try to use node hostname from the Node object.
By default as bastion host will be used the firsts master. But if you
set a ole to some host as bastion - it will be used instead.
So you can also have completely internal cluster if you setup a special
bastion host.
The main idea though is that you can directly feed host.spec from
flexy into jenkins and have everything working automatically.
HTH

nodes auto-discovery and accessing on private IPs

---

lib/login.rb

```
$ curl --http1.1 https://qe-chuan-api.qe.devcluster.openshift.com:6443/.well-known/oauth-authorization-server -k -i
HTTP/1.1 200 OK
Audit-Id: dadda4da-61a8-48c3-846d-634e1878c48f
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 30 Jan 2019 10:04:47 GMT
Content-Length: 606
{
"issuer": "https://o.apps.qe-chuan.qe.devcluster.openshift.com",
"authorization_endpoint": "https://o.apps.qe-chuan.qe.devcluster.openshift.com/oauth/authorize",
"token_endpoint": "https://o.apps.qe-chuan.qe.devcluster.openshift.com/oauth/token",
"scopes_supported": [
"user:check-access",
"user:full",
"user:info",
"user:list-projects",
"user:list-scoped-projects"
],
"response_types_supported": [
"code",
"token"
],
"grant_types_supported": [
"authorization_code",
"implicit"
], …
```

fix get bearer token issue for splitted oauth server endpoint

---

lib/cli_executor.rb

Recent https://github.com/openshift/origin/pull/21434 is merged
This makes auto fail:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/38503/console
```
[02:43:06] INFO> Shell Commands: oc version --config=/tmp/kubeconfig20190226-370-182k0n1
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.0-0.183.0", GitCommit:"99fca4beb8", GitTreeState:"", BuildDate:"2019-02-23T23:55:36Z", GoVersion:"", Compiler:"", Platform:""}
[02:43:06] INFO> Exit Status: 0
undefined method `[]' for nil:NilClass (NoMethodError)
/home/jenkins/workspace/Runner-v3/lib/cli_executor.rb:68:in `get_version_for'
/home/jenkins/workspace/Runner-v3/lib/cli_executor.rb:259:in `version'
/home/jenkins/workspace/Runner-v3/lib/cli_executor.rb:249:in `executor' …
```

fix for oc version

---

lib/openshift/project.rb

Update project step for 4.x
```
Given the "<%= cb.prj_name %>" project is deleted                                      # features/step_definitions/project.rb:192
project.project.openshift.io "56m0m" deleted
[07:09:11] INFO> Exit Status: 0
error getting project '56m0m' existence: 
STDERR:
Error from server (Forbidden): projects.project.openshift.io "56m0m" is forbidden: User "pm1" cannot get resource "projects" in API group "project.openshift.io" in the namespace "56m0m"
(RuntimeError)
../redhat/verification-tests/lib/openshift/project.rb:27:in `visible?'
```

update the project delete step

---

lib/admin_credentials.rb

similiar to #83, but accept kubeconfig that's stored locally.  This will be helpful in case the URL is not accesible.  You can set environment variable like so
`export OPENSHIFT_ENV_OCP4_ADMIN_CREDS_SPEC=~/.kube/config`

added support when user specify a local kubeconfig location

---

lib/rules/cli/4.0.yaml

For https://github.com/openshift/verification-tests/pull/89#issuecomment-467819874
Local test passed:
For:
```
Scenario: Test oc version
When I run the :version client command
Then the step should succeed
And evaluation of `@result[:props][:oc_version]` is stored in the :oc_version clipboard
And evaluation of `@result[:props][:kubernetes_server_version]` is stored in the :k8s_s_version clipboard
And I pry
```
Got:
```
Then the step should succeed
And evaluation of `@result[:props][:oc_version]` is stored in the :oc_version clipboard
And evaluation of `@result[:props][:kubernetes_server_version]` is stored in the :k8s_s_version clipboard                                                  
[1] pry(#<BushSlicer::DefaultWorld>)> cb.oc_version
=> "4.0.17"
[2] pry(#<BushSlicer::DefaultWorld>)> …
```

4.0 oc rules in new file

---

features/networking/pod.feature

I often met the following error when I execute this case:
```
[07:29:59] INFO> Shell Commands: oc exec iperf-rc-r8zsr  --config=/home/jenkins/workspace/Runner-v3/workdir/cucushift-oc311-standard-slave-94c71-0/ose_zzhao.kubeconfig -n nx8d9  -- sh -c iperf3\ -c\ 10.130.0.128\ -i\ 1\ -t\ 12s\ \|\ grep\ \"1.99\ Mbits\"
STDERR:
command terminated with exit code 1
```
but it can work when I deleted `\ \|\ grep\ \"1.99\ Mbits\`. I did not find the reason, So I changed the current way to implement.
And also 1.99 Mbits is not stable from the logs. sometimes it's 1.xx or 2.xx. So I changed to regrex [12].[0-9][0-9]
```
[07:13:47] INFO> Shell Commands: oc exec iperf-rc-fk9wj  --config=/home/jenkins/workspace/Runner-v3/workdir/cucushift-oc311-standard-slave-2sblr-0/ose_zzhao.kubeconfig -n 7n21w  -- …
```

Delete 'grep' in sh and update it to scan

---

lib/collections.rb
lib/configuration.rb

@gpei FYI
Issue was when we use ancoring in YAML and then merge them. When anchoring is
uses, the same Hash object can be present in multiple places within the
parsed Hash object. Then merging the Hashes in place results in changing
Hash in all places while only in one part of the tree it needs to be merged.
Now we always non-destructive merge hashes to avoid this situation.

fix issue when YAML uses anchoring

---

lib/jira_rht.rb

`issue.fetch` always results in `bad request`. Also I don't think we need this fetch to begin with so I remove it. If anybody needs, then it can be called later.
/assign @pruan-rht

make jira create issue work and allow running on command line

---

features/networking/pod.feature

This is clone of PR 91 (https://github.com/openshift/verification-tests/pull/91) to be merged in v3 branch as the scenario is not supported right now on 4.x version and master now points to 4.x. All the reviewers comment has been taken care of except passing on 4.x version. The scenario is gated to be work on <=3.11 version. 
@bmeng @zhaozhanqi @pruan-rht @akostadinov 
Discussed with @bmeng and @pruan-rht.
Passing logs : https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/282/console

Adding scenario OCP-19810 for v3

---

features/networking/sdn.feature
features/step_definitions/networking.rb
features/step_definitions/node.rb
lib/platform/node_service.rb

The node service in 4.0 and 4.1 cluster is kubelet.service, which was atomic-openshift-node.service in 3.x.
Fix the node service name to make some of the node verification steps work
[root@ip-10-0-130-247 ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2019-03-26 06:18:41 UTC; 1h 58min ago
Process: 934 ExecStartPre=/bin/rm -f /var/lib/kubelet/cpu_manager_state (code=exited, status=0/SUCCESS)
Process: 932 ExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
Main PID: 941 (hyperkube)
Tasks: 24 (limit: 26213)
Memory: 220.1M
CGroup: /system.slice/kubelet.service
└─941 /usr/bin/hyperkube kubelet …

fix the name of node service for 4.x

---

features/step_definitions/route.rb

the labels of default route pods in latest 4.1 build has been changed, like
```
$ oc get pod -n openshift-ingress --show-labels
NAME                              READY   STATUS    RESTARTS   AGE     LABELS
router-default-7bdf75c8d7-snbnw   1/1     Running   0          5h51m   ingress.operator.openshift.io/ingress-controller-deployment=default,pod-template-hash=7bdf75c8d7
```
@pruan-rht Please help merge, thanks

update router pod label

---

features/step_definitions/images/jenkins.rb
lib/environment.rb
lib/rules/web/images/jenkins_2/jenkins_2.xyaml

[jenkins log](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/38703/console)
@openshift/devexp-qe please help review

Modify jenkins steps to adjust 4.0 change

---

features/step_definitions/helper_services.rb

@chao007  @weherdh  Please take a look.
More detail in https://bugzilla.redhat.com/show_bug.cgi?id=1687722#c7

Skip node InitatorName config for iscsi as no need in 4.0

---

features/step_definitions/images/jenkins.rb

@openshift/devexp-qe 
We need cover two jenkins agent images and two slave images in 3.11 errata image lists
jenkins-agent-maven-35-rhel7 
jenkins-agent-nodejs-8-rhel7
jenkins-slave-nodejs-rhel7
jenkins-slave-base-rhel7
Add  the step to change default image using slave image in jenkins server.

Change jenkins agent images to slave images

---

features/svc-catalog_asb/asb.feature

OCP-15395 is `HIGH` importance case, which will not run in smoke runs, and it is already in tierN, remove the duplicated one in tier1 level.
@akostadinov please help review and merge, thanks.

remove case OCP-15395 in tier1

---

features/svc-catalog_asb/asb.feature

OCP-15395 is `HIGH` importance case, will not run in smoke runs, and it is already in tierN, remove the duplicated one in tier1 level.
@akostadinov please help review and merge, thanks.

remove OCP-15395 in tier1

---

features/step_definitions/cluster_service_broker.rb
features/svc-catalog_asb/asb.feature

In V4.0, ASB namespace changed from `openshift-ansible-service-broker` to 'ansible-service-broker`. 
Update namespace in cases.
Here's log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39499/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39498/console
@chengzhang1016 @pruan-rht @akostadinov  please help review and merge. Thanks.

update asb namespace in v4.0

---

features/step_definitions/helper_services.rb
lib/rules/web/console/base/login.xyaml

This PR is trying to fix the problem of the web console logging. The web console logging will fail as some logging workflow change. You can find the failed log as bellow(log1).
The log for this PR is as bellow, log2.
log1:https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39419/console
log2:https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39414/console
@yasun1 could you help review this PR? Thanks

modify the rules for web login

---

README.adoc
doc/configuration.adoc

This PR adds instructions for download and installing the web driver for both Firefox and Chrome. Several test cases require a web driver otherwise they fail and this requirement was not documented anywhere previously. Instructions should be identical for all branches.
This is identical to https://github.com/openshift/verification-tests/pull/144 but for the master branch.

Add instructions for downloading and installing Web Driver

---

features/networking/operator.feature

This is negative usecase to make sure that network operator version is still reflected post bad network config 
Ref: OCP-22706
Test logs: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/325/console
@bmeng @zhaozhanqi PTAL

Added Scenario for OCP-22706

---

features/networking/operator.feature
features/step_definitions/networking.rb

Nothing big but just changed 'Failing' type to 'Degraded' in scenarios due to https://github.com/openshift/cluster-network-operator/pull/147 .Confirmed Tests works fine after this change
PTAL @bmeng @zhaozhanqi

'Failing' type to 'Degraded' change in nw operator use cases

---

features/networking/multus.feature
features/step_definitions/networking.rb

https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/39878/console
Add a new step to run network related command on the sdn pod (since the sdn pod is running as hostnetwork).
Automated some more multus test cases.
@zhaozhanqi @anuragthehatter PTAL

[networking] automated multus cases for multiple cni plugins

---

features/step_definitions/route.rb

Dev changed the default labels of router pod (see below) again, so updating the auto scripts accordingly.
```
$ oc get pod -n openshift-ingress --show-labels
NAME                              READY   STATUS    RESTARTS   AGE   LABELS
router-default-689bfdcf95-97hw9   1/1     Running   0          48m   ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default,pod-template-hash=689bfdcf95
```
@akostadinov @pruan-rht Please help merge. It has been tested and passed.

update default router pod label

---

lib/rules/cli/3.3.yaml

@akostadinov @pruan-rht
It happens when running 3.x testing with master branch,
Jenkins log, Runner-v3/40647

[Hotfix] no rules found for option: wait

---

features/step_definitions/cluster_service_broker.rb
features/svc-catalog_asb/asb.feature

Change the namespace name back to `openshift-ansible-service-broker` as v4.1 requirement.
@jianzhangbjz  @akostadinov @pruan-rht  please help review and merge. Thanks.

project name change back to openshift-

---

features/step_definitions/pv.rb

Update the step `Given /^I have a(?: (\d+) GB)? volume and save volume id in the#{OPT_SYM} clipboard$/ do |size, cbname|`
So we can use it in the OCP4.x when create ebs volume
@liangxia  @weherdh  please help review 
Jenkins log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/40810/console

Update step about have volume and save volume id in the clipboard

---

features/networking/multus.feature
features/step_definitions/networking.rb

pod will cannot be created when the node do not have the 'eth0' interface. so update it to the default interface.
pass logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/40826/consoleFull
@bmeng @anuragthehatter

update to the default interface of node for multus

---

features/svc-catalog_asb/svc-catalog.feature

Same as https://github.com/openshift/cucushift/pull/6984 but for OCP-15600 test case automation scenario.

deprecated the 'new-app' command for OCP-15600

---

features/svc-catalog_asb/apb-update.feature
features/svc-catalog_asb/asb.feature
features/svc-catalog_asb/svc-catalog.feature

In OCP 4.1, the new-app command has been deprecated. Like the below shows, see bug https://bugzilla.redhat.com/show_bug.cgi?id=1671528 for more details. 
By using ` When I run the :new_app client command with` we're facing the following issue:
```
STDERR:
error: The template contained an object type unknown to `oc new-app`.  Use `oc process -f <template> | oc create -f -` instead.  Error details: no kind "ClusterServiceBroker" is registered for version "servicecatalog.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/kubectl/scheme/scheme.go:28"
[16:10:10] INFO> Exit Status: 1
| file  | https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/svc-catalog/ups-broker-template.yaml |
| param | UPS_BROKER_PROJECT=<%= project.name %> …
```

deprecated the 'new-app' command for asb/tsb test scenarios

---

lib/host.rb

under jenkins for archiving artifacts it is better to use predictable path
WORKSPACE is already unique to executor so no conflicts possible
/assign @pruan-rht

predictable workdir under Jenkins

---

lib/rules/cli/svcat-4.1.yaml

Fix the error `unknown rules source 'String': /Users/jianzhang/project/verification-tests/lib/rules/cli/svcat-4.1.yaml (RuntimeError)`, details as below. @akostadinov @pruan-rht @jianzhangbjz @zihantang-rh @scolange @bandrade Please have a review, thanks!
```console
#get help info
When I run the :provision admin command with:                                                 # features/step_definitions/cli.rb:31
[08:57:11] INFO> Shell Commands: rm  -f -- /Users/jianzhang/workdir/mac-jianzhang/ocp4_admin.kubeconfig
[08:57:11] INFO> Exit Status: 0
[08:57:11] INFO> Shell Commands: oc config set-credentials admin --client-certificate=/Users/jianzhang/workdir/mac-jianzhang/clcert20190524-55066-yo6fgo …
```

enable svcat in 4.1

---

features/networking/sdn.feature
features/step_definitions/networking.rb

This is similar to #194  but relevant to v3 branch. As @akostadinov suggested to keep changes separate for separate branches. networking.rb is fixed accordingly and gating criteria in scenario is clear now. Please help merging it. As per recent testing, there is lot of work to be involved to make this work on >=3.7 and <3.10 which comparatively get less testing request as compare to 3.10,3.11 and 4.x branch. So i suggest we merge it to avoid manual investigation in demanding branches during regression and needless to say, we can always keep working on it to support max branches in future
@bmeng @zhaozhanqi

OCP_16217 fixes to be merged in v3 branch

---

features/networking/operator.feature
features/networking/sdn.feature
features/step_definitions/networking.rb

Fixing OCP-16710 to support 3.11 and 4.1. Broke every time during 3.11 or 4.x regression
Pass logs on 3.11 - https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/338/console
Pass logs on 4.1 - https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/339/console
@bmeng @zhaozhanqi

Fix scenarios

---

features/storage/pre-bind.feature

@chao007 @weherdh 
Add storage class to nfs PV/PVC so it does not interfere with each other.
Tested on bare metal (where there are pre-created iSCSI/NFS PVs) and vSphere (where there is default storage class), both work.

Update OCP-9940 for 4.x to not interfere with each other

---

features/cli/build.feature

Need authentication when pull image from registry.redhat.io,  after tag openshift images into user project  image streams, so using docker.io image. 
[pass log](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/41355/console)
@openshift/devexp-qe pls help to review it, thx

Fix OCP-11943

---

features/storage/nfs.feature

@chao007 @weherdh 
```
STDERR:
Error from server (BadRequest): error when creating "STDIN": PersistentVolume in version "v1" cannot be handled as a PersistentVolume: v1.PersistentVolume.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 1, error found in #10 byte of ...|.io/gid":111111},"na|..., bigger context ...|ata":{"annotations":{"pv.beta.kubernetes.io/gid":111111},"name":"nfs-s47iu"},"spec":{"accessModes":[|...
```

Fixing yaml (from integer to string)

---

features/step_definitions/pv.rb
features/step_definitions/secrets.rb
features/storage/aws.feature
features/storage/cloud_provider.feature
features/storage/csi.feature
features/storage/dynamic_provisioning.feature
features/storage/glusterfs.feature
features/storage/quota.feature
features/storage/rbd.feature
features/storage/storage_class.feature
features/storage/vsphere.feature
features/test/pvc.feature

From k8s [docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class),
In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working, however it will become fully deprecated in a future Kubernetes release.
@chao007 This should addressed your concern in https://github.com/openshift/verification-tests/pull/228#issuecomment-499010882
@pruan-rht @akostadinov

Use attribute storageClassName to replace annotations

---

lib/bushslicer.rb
lib/launchers/cloud_helper.rb
lib/launchers/packet.rb

packet support for upi on baremetel
Since the provision and destroy part will be implemented by launch template, so no `terminate_by_launch_opts` for packet and also `launch_instances`

Add packet support

---

features/step_definitions/admin_console.rb
lib/environment.rb
lib/rules/web/console/base/login.xyaml

Using the `first` IDP blocks console automation because the first IDP is `kube:admin` on OCP clusters , running automation with `kube:admin` is dangerous and not allowed in cucushift
```
[09:15:09] INFO> Exit Status: 0
system projects visible to user kube:admin, clean-up too dangerous (RuntimeError)
/Users/yapei/repo/verification-tests/lib/openshift/user.rb:119:in `clean_projects'
```
So we wonder if we can add IDP option as environment variables, that will be much easier/better.  
@yasun1 Can you please review the changes to see how online cases will be affected?
FYI @yanpzhan  @SSshahan  @xiaocwan

update login flow, add IDP option

---

features/storage/iscsi.feature

@akostadinov @pruan-rht 
We have fixed the typo in master branch and in Polarion, but forgot to back-port the fix to v3.

Fix typo of OCP-9638

---

features/storage/nfs.feature

@chao007 
```
09:05:28 INFO> HTTP GET https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/storage/nfs/pv-gid.json
09:05:28 INFO> HTTP GET took 0.499 sec: 200 OK | text/plain 392 bytes
09:05:28 INFO> Creating PV:
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: nfs-il9xm
annotations:
pv.beta.kubernetes.io/gid: 1234
spec:
capacity:
storage: 1Gi
accessModes:
- ReadWriteMany
nfs:
path: "/"
server: 172.30.155.32
persistentVolumeReclaimPolicy: Retain
09:05:28 INFO> Shell Commands: oc create -f - --config=/home/jenkins/workspace/Runner-v3/workdir/ose_admin.kubeconfig
STDERR:
Error from server (BadRequest): error when creating "STDIN": PersistentVolume in version "v1" cannot be handled as a PersistentVolume: [pos 101]: json: expect char '"' but got char '1'
09:05:29 INFO> …
```

Fix PV gid type (from int to string)

---

features/routing/f5-router.feature
lib/rules/cli/3.3.yaml

Since f5 router is deprecated since 3.11 so I'd like to merge this to branch v3 only.
This case is for smoke testing and ose-f5-router image testing as well.
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/41784/consoleFull

add one f5 router case

---

features/networking/pod.feature
features/networking/service.feature
features/step_definitions/networking.rb

These tests are required to cover Cases connected to Blocking Machine-config-server port
Pass logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/366/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/365/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/364/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/363/console
OCP-23893 needs a valid_ip as an input variable during the test
@zhaozhanqi  PTAL

Adding various scenarios to support SDN 411 - Blocking Machine-config-server port

---

features/storage/storage_class.feature

@chao007 @akostadinov @pruan-rht 
1. The logic of delete the default storage class, then create a new default storage class looks weird.
2. Default storage class can not be deleted in 4.x (Automation will quit prematurely due to failed to recover the deleted default storage class as it already exist).

Simplify the logic of default storage class

---

features/cli/policy.feature

In 4.x, the error is `Error from server (Forbidden): persistentvolumes is forbidden: User "testuser-23" cannot list resource "persistentvolumes" in API group "" at the cluster scope`

Fix OCP-10465

---

features/cli/policy.feature

Error in 4.x is `Error from server (Forbidden): persistentvolumeclaims "pvc-q-lbw" is forbidden: User "testuser-24" cannot delete resource "persistentvolumeclaims" in API group "" in the namespace "q-lbw"
`

Fix OCP-10467

---

features/storage/NoDiskConflict.feature
features/storage/aws.feature
features/storage/csi.feature
features/storage/dynamic_provisioning.feature
features/storage/fsType.feature
features/storage/glusterfs.feature
features/storage/nfs.feature
features/storage/persistent_volume.feature
features/storage/pre-bind.feature
features/storage/quota.feature
features/storage/rbd.feature
features/storage/reclaim_policy.feature
features/storage/security.feature
features/storage/storage_class.feature
features/storage/vsphere.feature

Since project name is unique, and pvc/pod are resources in project. Use simpler pvc/pod name can save a lot of typing when debugging failures. Saving more typing when using command history.

Use simpler pvc/pod name to easier debug as they are in unique project

---

features/networking/sdn.feature

This was a test case created for SDN-341.
Logs: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/410/console
Not sure if :239 is right way to define sudo or if there is a step which can facilitate that. Pleas advise
Thanks.
@zhaozhanqi

ocp 23543 - iptables binary and rules on sdn containers should be the same as host

---

features/cli/secrets.feature
features/images/jenkins.feature
features/quickstarts/quickstarts.feature
features/storage/quota.feature

Alpha annotation storage-class is obsoleted since 3.4, and 3.4/3.5 reach EOL in April 2019.
@stuartchuan  for secrets.feature
@wzheng1  for jenkins.feature and quickstarts.feature
@chao007  for quota.feature
@akostadinov @pruan-rht

Remove alpha annotation storage-class (obsoleted since 3.4)

---

features/step_definitions/images/jenkins.rb
lib/rules/web/images/jenkins_2/jenkins_2.xyaml

If there are multiple idp, need pass idp type when jenkins enables openshift oauth.
@openshift/devexp-qe Please help review, thx

Pass idp type when jenkins enables openshift oauth

---

features/build/dockerbuild.feature

Now, in 4.x, no command: "oc expor", so fix the case. @openshift/devexp-qe please help to review it, thanks

Fix OCP-12855

---

features/routing/ipfailover.feature
lib/rules/cli/3.3.yaml

This case is for CVP in 3.x release and just ensure no issue with ipfailover image and the pod can be `Running`.
@zhaozhanqi Please help review. Thanks.
log: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/42475/consoleFull

auto OCP-9767

---

features/step_definitions/oauth.rb

Add more time for oauth restore step, in case of it not finish when next scenario started.

Add more time for oauth restore step

---

features/step_definitions/storage_class.rb

The code was added in https://github.com/openshift/verification-tests/pull/142 for 4.1 (as we add volumeBindingMode to WaitForFirstConsumer on AWS ).
We are now adding topology aware dynamic provisioning for more clouds (Azure, OpenStack, GCE) for 4.2 in https://github.com/openshift/cluster-storage-operator/pull/42 and https://github.com/openshift/cluster-storage-operator/pull/43
Immediate do means PV/volume is created before pod is scheduled, which can cause volume in zone1, while pod is scheduled on a node which is in zone2, sometimes.
We should fix some PVC checking steps in  following up PRs.

Use topology aware dynamic provisioning in the clouds

---

features/storage/pre-bind.feature

Some cleanup in master branch is done for 4.x, then polarion is updated, then 3.x is broken due to parameters are changed.
This PR sync the parameters with 4.x/polarion.

Fix parameters for OCP-10108/10112

---

features/step_definitions/cluster_configuration/csi.rb
features/storage/persistent_volume.feature
features/storage/storage_class.feature
features/web/pvc.feature

The step `default storage class is deleted` will recover the storage class in after hooks. As default storage class will be automatically recovered by cluster-storage-operator, the after hook will fail, which will cause auto execution quit prematurely.
@chao007 @qinpingli @jhou1 @akostadinov @pruan-rht

Default storage class can not be deleted in 4.x

---

features/step_definitions/admin_console.rb

@yapei, please see if this will get you browser.yml respected. Order in which rules are specified is important to find the additional opts.

WIP admin console must read browser_opts.yml

---

lib/admin_credentials.rb
lib/openshift/cluster_role.rb
lib/openshift/config_samples_operator_openshift_io.rb
lib/openshift/resource.rb
lib/openshift/security_context_constraints.rb
lib/world.rb

@xiuwang, please test whether this will help #308
you can refer to the name "cluster" of kind "config.samples.operator.openshift.io" by `config_samples_operator_openshift_io("cluster")`. And let me know!
@pruan-rht, notice file URL change here

support resources with dots in their Kind field

---

lib/launchers/openstack10.rb

```
[1] pry(#<BushSlicer::DefaultWorld>)> iaas = iaas_by_service("openstack_upshift")
[2] pry(#<BushSlicer::DefaultWorld>)> iaas.get_floating_ips
[3] pry(#<BushSlicer::DefaultWorld>)> iaas.allocate_floating_ip("provider_net_shared_2")
=> {"router_id"=>nil,
"status"=>"DOWN",
"description"=>"IP allocated automatically by OpenShift verification-tests",
"tags"=>[],
"tenant_id"=>"542c6ebd48bf40fa857fc245c7572e30",
"created_at"=>"2019-08-26T22:36:46Z",
"updated_at"=>"2019-08-26T22:36:46Z",
"floating_network_id"=>"14c15d33-175c-424e-88ba-361a875e0c5c",
"fixed_ip_address"=>nil,
"floating_ip_address"=>"10.0.79.234",
"revision_number"=>0,
"project_id"=>"542c6ebd48bf40fa857fc245c7572e30",
"port_id"=>nil,
"id"=>"d9a898a3-7767-4ace-8315-608974ca10da",
"qos_policy_id"=>nil}
[4] …
```

add set_floating_ip function for IPI on OSP routes record

---

lib/rules/web/admin_console/3.11/environments.xyaml
lib/rules/web/admin_console/4.1/environments.xyaml
lib/rules/web/admin_console/4.1/status.xyaml
lib/rules/web/admin_console/4.2/environments.xyaml
lib/rules/web/admin_console/4.2/status.xyaml

- text checking are removed since we often meet
```
Unable to locate element collection from {:visible_text=>/No Workloads Found/i} due to changing page (Watir::Exception::LocatorException)
```
- Update environment rules

some fixes

---

features/test/new_api.feature
lib/openshift/flakes/route_spec.rb
lib/openshift/route.rb

@yanpzhan, this PR adds route spec property support.  Example usage is `route('grafana').spec.host`.  There's a similar PR (#346 by @yapei).  Both PRs accomplishes the same end result (different ways of calling methods) but with different internal implementation.  @akostadinov, can you PTAL both and see which one you prefer?  Thanks!

helper for https://github.com/openshift/cucushift/pull/7083

---

lib/cli_executor.rb

Now latest 4.2 oc version output changed:
$ oc version
Client Version: v4.2.0
Server Version: 4.2.0-0.nightly-2019-09-17-232025
Kubernetes Version: v1.14.6+e353665
Pass log: http://pastebin.test.redhat.com/798708
@akostadinov  @pruan-rht , pls help to review, thanks!

fix for oc version output change

---

features/networking/egress-ingress.feature
features/networking/egress-ip.feature

These are some updates for cases:13509, 15017, 13507, 15465.
13507,15017 was updated because original way checking OVS rules from node  failed in 4.x. Instead of that, check OVS rules from SDN pod.
15465 need add @admin tag before the case.
13509 use yahoo.com to replace www.yahoo.com, sometimes nslookup of www.yahoo.com got less than 3 ip addresses that cause the case failing. Moreover, the default dns-egresspolicy2.json match yahoo.com and we don't need to change it anymore.
logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/44103/console
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/44104/console
Any comments will be welcomed, thanks!
@zhaozhanqi @anuragthehatter @lihongan

Update ocp-13509, 15017, 13507, 15465

---

features/storage/quota.feature

In 4.2, the pvc can not bind due to `VolumeBindingMode` defaults to `WaitForFirstConsumer`.
First tried removing PVC binding check, then it failed again later since we use "#{ pvc.volume_name }" to get PV name in the following steps. Then comes with this solution.
@chao007 @duanwei33

Fix OCP-14382

---

features/storage/regression.feature

Previously, error msg is "volume is already exclusively attached to another node", now the error msg is "1 node(s) had volume node affinity conflict"
@chao007 @duanwei33

Fix OCP-16485

---

features/networking/pod.feature
features/networking/sdn.feature

These are some updates about cases:OCP-13847 OCP-18535 OCP-14986 OCP-10817.
Cases fail due to run commands on node.  Change to run commands in SDN pods.
Any comments will be welcomed, thanks!
@zhaozhanqi @anuragthehatter @lihongan
Logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/44405/console

Update case OCP-13847 OCP-18535 OCP-14986 OCP-10817

---

features/cli/job.feature

Failure: http://ci-qe.../userContent/cucushift/v3/2019/08/30/10:24:32/Create_job_with_pod_parallelism/console.html
Reason: 1. previous step's terminating pod "zero-5tkh5 0/1 Terminating 0 16s" still does not disappear; 2. another previous step "all existing pods die with labels", die means 'matched status for pods zero-5tkh5: 'succeeded' while expecting '[:failed, :succeeded, :missing]', die does not mean disappear.
Fix: wait previous pods to disappear
@zhouying7780 @akostadinov please review/merge, thanks!

Fix OCP-11539

---

features/cli/policy.feature

As the test case is checking that storage-admin can create/delete/update/get PVs, replacing aws PV with hostpath PV does no harm.
Why replacing aws PV to hostpath PV ?
Because we do volume validation now in 4.x, the test case will works on AWS only if we use aws PV.
```
Then I run the :create client command with:                                                                              # features/step_definitions/cli.rb:13
[06:30:53] INFO> Shell Commands: oc create -f pv-rwo.yaml --config=/home/lxia/workdir/ocp-lxia/ose_testuser-46.kubeconfig
STDERR:
Error from server (Forbidden): error when creating "pv-rwo.yaml": persistentvolumes "pv-6qvej" is forbidden: error querying AWS EBS volume qe-lxi-fzkpq-dynamic-pvc-454c9ed2-14c4-41f9-b76c-9d3bd3da261b: unable to read AWS cloud provider …
```

Update OCP-10466 so it cross platforms

---

features/step_definitions/logging.rb
lib/environment.rb

@anpingli @akostadinov @pruan-rht  PTAL, thanks.
I'm adding a new environment variable `subscription_opsrc_name`, I add this because when running logging test, the opsrc we used to create subscription can be changed due to a lot of reasons.
And this variable could be used for all the testing related to creating subscriptions via OLM. I set the default value to `redhat-operators`.
Here is an example:
```
export BUSHSLICER_CONFIG='                                                        
environments:
ocp4:
version: "4.3"
subscription_opsrc_name: "redhat-operators-art"
'
```
Log: https://url.corp.redhat.com/d7f0207

add new steps to get `opsrc` name

---

features/admin/pod.feature
features/step_definitions/node.rb
lib/rules/cli/4.0.yaml

Tested with features/admin/pod.feature:58 on a 4.2 Azure cluster, and the scenario itself failed, but cordon node in the step and uncordon node in the clean-up are working fine.
@chengzhang1016 Help review the changes for pod.feature, @zhaozhanqi for node.rb
@akostadinov @pruan-rht

[Blocker] Replace obsoleted oadm_manage_node with oadm_cordon/uncordon_node

---

lib/rules/web/console/base/login.xyaml

@akostadinov  When defaulting IDP to the first one, it's always `kube:admin` and always failed (Found in CI).  So updated to use the last one, also the changes applies to our CI (which the only and last option is `flexy-htpasswd-provider`)

change default IDP to the last one

---

features/logging/collector.feature
lib/openshift/cluster_logging.rb

There are some differences in `pipeline_metadata` between logging 4.1 and logging 4.2, so I open this PR to create new scenarios for logging 4.1 to make the automation more reliable. @anpingli PTAL, thanks.
Run log:  https://url.corp.redhat.com/d061981

enhancements for logging 4.1

---

features/logging/collector.feature

this pr fixes the error when executing the case using Runner-v3 job:
```
And evaluation of `@pods.map {|n| n.node_ip}.uniq` is stored in the :node_ips clipboard              # features/step_definitions/common.rb:128
undefined method `map' for nil:NilClass (NoMethodError)
(eval):1:in `block in <top (required)>'
/home/jenkins/workspace/Runner-v3/features/step_definitions/common.rb:130:in `eval'
/home/jenkins/workspace/Runner-v3/features/step_definitions/common.rb:130:in `/^evaluation of `(.+?)` is stored in the(?: :(\S+))? clipboard$/'
features/logging/collector.feature:44:in `And evaluation of `@pods.map {|n| n.node_ip}.uniq` is stored in the :node_ips clipboard'
```
@anpingli  PTAL.
Pass log: https://url.corp.redhat.com/c50bb62

fix issue: undefined method `map' for nil:NilClass (NoMethodError)

---

features/machine/machine.feature

Occasionally, the following line returns secret `prometheus-k8s-dockercfg-g7488` where we want the secret to be `prometheus-k8s-token-*`. This PR fixes the test flake.
```
And evaluation of `secret(service_account('prometheus-k8s').get_secret_names.first).token` is stored in the :token clipboard # features/step_definitions/common.rb:128
[22:12:26] INFO> Shell Commands: oc get secrets prometheus-k8s-dockercfg-g7488 --output=yaml --config=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig --namespace=openshift-monitoring
```
I've run the test and it had passed
```
[10:02:26] INFO> === After Scenario: MAO metrics is exposed on https ===
[10:02:26] INFO> Shell Commands: rm -r -f -- /Users/houjianwei/workdir/jhouMacBookPro-houjianwei
[10:02:26] INFO> Exit Status: 0
[10:02:26] …
```

Ensure secret prometheus-k8s-token-xxx is returned

---

features/storage/pre-bind.feature

Once the project name is numeric, the creation of PV will fail due to type check failed.
```
23:44:11 INFO> Creating PV:
---
kind: PersistentVolume
apiVersion: v1
metadata:
name: pv-10631
annotations:
volume.beta.kubernetes.io/storage-class: 10631
labels:
type: local
spec:
capacity:
storage: 5Gi
accessModes:
- ReadWriteOnce
hostPath:
path: "/tmp/data01"
persistentVolumeReclaimPolicy: Retain
23:44:12 INFO> Shell Commands: oc create -f - --config=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig
STDERR:
Error from server (BadRequest): error when creating "STDIN": PersistentVolume in version "v1" cannot be handled as a PersistentVolume: v1.PersistentVolume.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found 1, error found in #10 byte of …
```

Make sure storageClassName is a string

---

features/machine/machine.feature

Added more test cases using scenario outline. 
Validated the tests:
```
[08:38:45] INFO> Exit Status: 0
[08:38:45] INFO> === End After Scenario: Metrics is exposed on https, Examples (#3) ===
3 scenarios (3 passed)
0m15.527s
```

Testing metrics is exposed on https

---

features/networking/service.feature

Some times the pod with an invalid image is not in `ImagePullBackOff` status, maybe in `ErrImagePull` status too.
So I updated the test scripts to involve this situation.
The test log is: https://privatebin-it-iso.int.open.paas.redhat.com/?82dcf601db52f206#TVnG/4SXlgXIK5fuTiD+q61F/LCKBS822M1TI8nfrWY=
@zhaozhanqi @huiran0826 Please help reveiw.

Bug fix for OCP-21814

---

features/storage/node_operations.feature

In 4.x cluster, generally there are 3 nodes in 3 zones. When we drain node (node in zone1 with persistent volume in zone1 ), those pods are not schedulable as there are no available node in zone1.
This PR uncordon the node so that pods are back after drain-node.
@chao007 @duanwei33

Uncordon node so pods are schedulable

---

features/step_definitions/logging_metrics.rb
features/step_definitions/metering.rb
features/step_definitions/net.rb
features/step_definitions/web.rb
features/support/env.rb
lib/bushslicer.rb
lib/cli_executor.rb
lib/common.rb
lib/environment.rb
lib/http.rb
lib/login.rb
lib/openshift/route.rb
lib/platform/master_service.rb
lib/rest.rb
lib/rules/cli/4.0.yaml
lib/webauto/chrome_extension.rb
lib/webauto/resource/chrome_crx3/README
lib/webauto/resource/chrome_crx3/crx3.pb.rb
lib/webauto/resource/chrome_crx3/crx3.proto
lib/webauto/resource/chrome_proxy/background.js.erb
lib/webauto/resource/chrome_proxy/manifest.json
lib/webauto/web4cucumber.rb
lib/webauto/webconsole_executor.rb
tools/shell_proxy.sh

/hold until complete and tested
Example scenario with private cluster using cli, REST and route access:
https://privatebin-it-iso.int.open.paas.redhat.com/?e8cc6f863af24aaf#YQbVi+LCNs0Rgfbjum+Uje7W+Ui7LnWmCTbY+cfKqWU=
Web scenarios seem to request password for proxy even though it is in uri already. But I don't see them working presently so we can leave that for later PR. If proxy does not require passowrd it is fine. This is *not* a regression.

private cluster proxy support

---

features/machine/machine.feature
features/step_definitions/machine.rb
features/step_definitions/machine_set.rb
lib/openshift/machine.rb
lib/openshift/machine_set.rb

As a follow up of discussion at https://github.com/openshift/verification-tests/pull/423#discussion_r340892440, simplified the steps for scaling machinesets. The test is now more efficient by reducing the steps.

Simplify machine steps

---

features/step_definitions/helper_services.rb

@openshift/devexp-qe please check it, thanks
Now proxy server label is as follow:
$ oc describe pod/squid-proxy-1-bqsbp 
Name:         squid-proxy-1-bqsbp
Labels:       deployment=squid-proxy-1
deploymentconfig=squid-proxy

Update proxy server  label

---

OWNERS

Hi, I'm from a team maintaining OpenShift Prow instance which is
configured to perform some actions on this repo. One of the actions
is automatically selecting two reviewers for a repo which are not
the PR authors. This means that for OWNERS files containing just two
logins we occasionally do not have enough reviewers to choose from.
Thus, adding `reviewers` to the `OWNERS` file from the people who
seem to be already reviewing PRs in this repo. This list only controls
the automated reviewer selection, it does not change any rights or
permissions to do anything.

Add reviewers to OWNERS

---

lib/instance_summary.rb
lib/jenkins.rb
lib/launchers/amz.rb
lib/launchers/azure.rb
lib/launchers/gce.rb
lib/launchers/openstack10.rb
tools/cloud_cop.rb

usage is `./tools/cloud_cop.rb aws` to get summary of all regions or `./tools/cloud_cop.rb aws --region=us-east-2` to just get the summary for that region.  Currently only support AWS, will add other cloud providers later.  Here's an example output
http://pastebin.test.redhat.com/804638

utilty to summarize instance usages for various cloud vendors

---

features/build/buildconfig.feature
features/build/env.feature
features/cli/build.feature
features/images/jenkins.feature

@openshift/devexp-qe Please help review, thanks~
Since 4.x, no need update the slave image on the jenkins console managed page, so remove the login steps for the pipeline build cases.

Remove jenkins login steps from pipeline cases

---

features/machine/machine_healthcheck.feature
features/step_definitions/machine_healthcheck.rb
lib/openshift/machine_set.rb
lib/openshift/machinehealthcheck.rb

The test verifies a machine is remediated when it has the unhealthyCondition defined in a mhc resource.

Add machine-healthcheck scenarios

---

features/routing/route.feature
features/step_definitions/route.rb

The step `I store default router IPs in the#{OPT_SYM} clipboard` cannot work for private cluster since no public DNS for route.
In the new step, we execute curl command on the pod inside the cluster so can solve above problem.
Actually, nslookup command can be used here but using curl can workaround the DNS misconfiguration issue for few clusters (vSphere/Baremetal and adding RHEL worker). When the DNS issue resolved then we can change back to use nslookup command.

new step to get available router ip

---

features/networking/multus.feature

https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/50818/console
@weliang1 @anuragthehatter @huiran0826 @rbbratta 
1. 
`| ["spec"]["config"]["eth0"]| <%= cb.default_interface %> |` cannot be parsed for now, and I did not find a way to replace one parameter (`master`) in `config`. so here I replace the whole `config` with specfied '<%= cb.default_interface %>'
2. 
```
cb[cb_name] = @result[:response].chomp.split[0] 
```
is for issue https://github.com/openshift/verification-tests/issues/492

update multus failed cases

---

features/step_definitions/storage_class.rb

We have bump up the API version in the test files via https://github.com/openshift-qe/v3-testfiles/pull/1190, and OCP < 3.6 is already EOL, so no need to do the version check now.
/cc @chao007 @duanwei33 @pruan-rht @akostadinov

Bump up storage apiVersion from v1beta1 to v1

---

lib/openshift/package_manifest.rb

```$ oc api-resources --api-group=packages.operators.coreos.com
NAME               SHORTNAMES   APIGROUP                        NAMESPACED   KIND
packagemanifests                packages.operators.coreos.com   true         PackageManifest
```
The packagemanifests should be namespaced resource.
@yapei @pruan-rht  please help to review, thanks

fix namespaced scope for packagemanifests

---

features/networking/build.feature

Add more time since sometimes the build logs did not come out in 100 second.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/57667/
@huiran0826 @anuragthehatter @weliang1 @rbbratta

update time to 200 second

---

lib/rules/cli/4.1.yaml

@jhou1 @pruan-rht @yapei @xiaocwan 
```
required command option not supplied: resource_type (RuntimeError)
/home/lxia/github.com/verification-tests/lib/rules_command_executor.rb:280:in `block in build_command_line'
/home/lxia/github.com/verification-tests/lib/rules_command_executor.rb:268:in `gsub!'
/home/lxia/github.com/verification-tests/lib/rules_command_executor.rb:268:in `build_command_line'
/home/lxia/github.com/verification-tests/lib/rules_command_executor.rb:53:in `run'
/home/lxia/github.com/verification-tests/lib/cli_executor.rb:314:in `exec'
/home/lxia/github.com/verification-tests/lib/api_accessor.rb:71:in `cli_exec'
/home/lxia/github.com/verification-tests/lib/openshift/cluster_resource.rb:41:in `create'
/home/lxia/github.com/verification-tests/features/step_definitions/pv.rb:1 …
```

Revert part of #PR579

---

features/containers/containers.feature

New output looks like:
```bash
id
uid=1001520000(1001520000) gid=0(root) groups=0(root),1001520000
```

Update regexp to match new output format.

---

features/build/buildlogic.feature
features/cli/secrets.feature
features/web/secrets.feature
lib/rules/cli/4.1.yaml

@pruan-rht @xiuwang 
Following the CLI rules, replace `oc_secrets_new_sshauth` with `secrets_new_sshauth`.
Will remove CLI rule `oc_secrets_new_sshauth` in another PR after all commands are replaced.

Fix CLI format of "oc secrets new"

---

features/networking/operator.feature

Found during CI run that 60 seconds may not be enough and there is no polling mechanism for this feature. Hence ,doubling the timeouts. 
@pruan-rht Can you help merge this small change?
Logs: http://pastebin.test.redhat.com/825754

Adjusted timeouts to support various releases

---

features/machine/alerting.feature

Verify that alert is fired when its relevant operator is down.
I've verified my tests locally.
```
[07:41:26] INFO> Exit Status: 0
[07:41:26] INFO> === End After Scenario: Alert should be fired when operator is down, Examples (#2) ===
2 scenarios (2 passed)
26 steps (26 passed)
6m38.954s
```

Alert testing for machine-api operators

---

features/step_definitions/secrets.rb

Fail [log](http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/01/08/04:58:02/Azure_file_with_secretNamespace_parameter_of_different_project/console.html)
The main diff is that pvc.json do not use beta annotations (replaced by spec.storageClassName).
@duanwei33 @chao007

Use common PVC template to get rid of beta annotations

---

features/machine/alerting.feature

Adding a scenario to the previous test: when machine-approver is down, alert is fired.
Tested my tests locally.
```
[06:21:12] INFO> Exit Status: 0
[06:21:12] INFO> === End After Scenario: Alert should be fired when operator is down, Examples (#3) ===
3 scenarios (3 passed)
30 steps (30 passed)
3m44.324s
```
@liangxia @pruan-rht Would you please review?

Adding machine-approver alerts

---

features/cli/deploy.feature
features/cli/oc_env.feature
features/cli/oc_set_env.feature
features/routing/haproxy-router.feature
features/routing/logging.feature
lib/rules/cli/4.1.yaml

\# The cmd :env can be removed after 3.1 EOL (nov 2018).
\# We have both :env and :set_env since 3.2.
\# Removed :env in 3.11.
@pruan-rht @akostadinov @zhouying7780

Replace obsoleted "oc env" with "oc set env"

---

features/logging/cluster_logging_operator.feature

When checking the executing logs, this case failed many times due to the gen_uuid_2 is nil, so add a step to wait for the gen_uuid to be generated. 
@anpingli  PTAL.

fix issue when executing case OCP-22492

---

features/step_definitions/storage_class.rb

When we use below step to clone from storage class which does not have parameters(E.g, on OpenStack), it will fail.
```
And admin clones storage class "storageclass-<%= project.name %>" from ":default" with:
| ["parameters"]["fstype"] | <fstype> |
```
Pass [log](https://privatebin-it-iso.int.open.paas.redhat.com/?9c771e5fc0409aa7#mIAssdpGUnPIA8ALPWQSyPplA5UTYpJnHvtqzyZA1eM=) on OpenStack.
@chao007 @duanwei33 @pruan-rht @akostadinov

Fix clone from storage class without parameters

---

features/step_definitions/admin_console.rb
lib/rules/web/admin_console/4.2/check_links.xyaml
lib/rules/web/admin_console/4.3/check_links.xyaml

Since OCP-25802 is to check default download links across multiple OS, OCP-24287 is to check customization for oc download links, I move the step check_default_oc_download_links into OCP-25802: 
OCP-24287 is for 4.2 & 4.3, only keep `check_default_odo_download_links` and mainly check customization links.
OCP-25802 is for checking default links.
@yapei Plz review, thanks!

Update rules: Auto OCP-25802 and update OCP-24287

---

features/storage/persistent_volume.feature
features/storage/reclaim_policy.feature
features/storage/storage_class.feature

They are marked as destructive because we have created PV in those scenarios, and PV can interfere with PVCs created in other scenarios.
Now we limit PV/PVC in specific storage classes, so they no longer interfere with other PVs/PVCs.

Rewrite scenarios to be non-destructive

---

features/admin/pod.feature

A master node is picked for getting disabled, a po will not be scheduled there by default. This will make the checking step failed.
Failed log:
`[weinliu@vm251-93 0119]$ oc get no
NAME                                        STATUS                     ROLES    AGE    VERSION
ip-10-0-58-76.us-east-2.compute.internal    Ready,SchedulingDisabled   master   3h3m   v1.14.6+cebabbf4a
ip-10-0-60-56.us-east-2.compute.internal    Ready                      worker   173m   v1.14.6+cebabbf4a
ip-10-0-61-83.us-east-2.compute.internal    Ready                      master   3h3m   v1.14.6+cebabbf4a
ip-10-0-66-137.us-east-2.compute.internal   Ready                      worker   172m   v1.14.6+cebabbf4a
ip-10-0-78-225.us-east-2.compute.internal   Ready                      master   3h3m   v1.14.6+cebabbf4a …

Fixing OCP-11925,picking a worker node to get unschedulable

---

features/cli/deploy.feature

Failed log:
`
When I get project pod                                                              # features/step_definitions/project.rb:255
[07:24:05] INFO> Shell Commands: oc get pod --config=/home/weinliu/workdir/vm251-93-weinliu/ocp4_testuser-0.kubeconfig -n 6jhvt
NAME             READY   STATUS              RESTARTS   AGE
hooks-1-wrcsm    1/1     Terminating         0          15s
hooks-2-deploy   0/1     ContainerCreating   0          9s
[07:24:07] INFO> Exit Status: 0
Then the output should match:                                                       # features/step_definitions/common.rb:33
| hooks-2.*Running |
`
The changes fix this

Add 60s waiting to fixing the issues, when hooks pods get into "running" late

---

features/step_definitions/networking.rb

The existing definition is breaking on a cluster with mixed nodes as noted in CI runs. The reason is cluster with rhel7+rhcos nodes might have different master interface names on them respectively. Existing definition calls another step in it which changes course from existing node to a different one. We need to make sure the definition should execute on a single node itself from starting to end.
We could have shortened this definition by executing on host but i prefer to get inf names via network pods due to sometime we get STDERR on host commands.
Confirmed via logs that this whole def is executing on a single node now http://pastebin.test.redhat.com/830405
@pruan-rht Can you help merging it?

Changing definition to support mixed nodes

---

lib/cli_executor.rb

@elenagerman reported the issue with oc in slack,
```
[kni@provisionhost-0 verification-tests]$ oc version -o yaml
clientVersion:
buildDate: "2020-01-31T08:08:24Z"
compiler: gc
gitCommit: e0666000dfa8cb634a6fa712dd80ecf132d162a7
gitTreeState: clean
gitVersion: openshift-clients-4.3-2-ge0666000
goVersion: go1.12.12
major: ""
minor: ""
platform: linux/amd64
```
/cc @akostadinov @pruan-rht

Split minor version from "-"

---

features/svc-catalog_asb/svc-catalog.feature

Add the auto scrip OCP-15603 ocp-15605 to verification-tests.
runner v3 test log:
@admin @destructive
Scenario: Create/get/update/delete for ServiceBinding resource                          # features/svc-catalog_asb/svc-catalog.feature:280
[05:06:33] INFO> === Before Scenario: Create/get/update/delete for ServiceBinding resource ===
[05:06:33] INFO> === End Before Scenario: Create/get/update/delete for ServiceBinding resource ===
...
[05:07:53] INFO> HTTP DELETE took 0.402 sec: 200 OK | application/json 235 bytes
[05:07:53] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
[05:07:53] INFO> Exit Status: 0
[05:07:53] INFO> === End After Scenario: Create/get/update/delete for ServiceBinding resource ===
waiting for …

Add the OCP-15603 ocp-15605

---

lib/cli_executor.rb

Work around for changing major version from 1 to 3 (used for 3.1~3.5) is no longer needed.
v[1] is split by '.' in str_version, no need to split by '.' again.

Remove oc version check for 3.y

---

lib/rules/web/admin_console/4.4/goto.xyaml

@yanpzhan   same rule name `goto_project_details_page` only changed the url for 4.4.

update project Details tab page url for 4.4

---

features/machine/alerting.feature
features/step_definitions/prometheus.rb

Per the [discussion](https://github.com/openshift/cucushift/pull/7356#issuecomment-577745707) with @pruan-rht and @liangxia , we'd like to simplify the prometheus queriy steps. Instead of running the `oc exec` on the `prometheus-k8s-0` or `prometheus-k8s-1` pod, we query the prometheus route, this makes sure the data is always consistent.
Verified my tests locally:
```
[07:43:19] INFO> === End After Scenario: Alert should be fired when operator is down, Examples (#3) ===
3 scenarios (3 passed)
24 steps (24 passed)
4m25.926s
```

Simplify steps to query prometheus

---

features/machine/machine.feature

The machine number is restored after scenario, but we did not wait for the node number to be restored. This PR address the enhancement.
@qinpingli Will you PTAL?

Ensure machines and nodes are restored after scenario

---

features/networking/isolation.feature

Delete "Given the env is using multitenant network" in the script to let it run in network-policy by default
Testing log:
http://pastebin.test.redhat.com/834589
@zhaozhanqi @huiran0826 @rbbratta

Run OCP-9565 in network-policy by default

---

lib/cli_executor.rb
lib/rules/cli/4.1.yaml

Hi @akostadinov and @pruan-rht 
Could we use `--kubeconfig` instead of `--config` since `--config` has been deprecated? I suggest to switch to the right flag for the oc 4.4.
$ oc version
Client Version: openshift-clients-4.4-23-g37623bc8
Server Version: 4.4.0-0.nightly-2020-02-05-181112
Mac using the latest oc version failed to run cucushift unless change `--config` to `--kubeconfig` as this PR did.

Update to run cucushift on oc 4.4 using --kubeconfig instead of --config

---

lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

For 4.1/4.2/4.3, `oc config --kubeconfig` does not generate kubeconfig , then automation will fail with error,
error: stat /home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig: no such file or directory
For 4.4, when --config is used, there is a waring message which will cause an issue describe in https://github.com/openshift/verification-tests/pull/694
So we copy 4.1 to 4.4, and switch to --kubeconfig in 4.4

[Blocker] Switch to --kubeconfig only in 4.4 as some cmd in 4.3 does not support it.

---

features/routing/route.feature

The HAProxy in router is upgrade to 2.0 in OCP 4.4 and some heads are changed to lowercase like below, so remove the capitalized "L" from match strings.
```
< HTTP/1.1 302 Found
< content-length: 0
< location: https://console-openshift-console.apps.example.com/
```

update the match strings to avoid case-sensitive

---

features/machine/machine.feature
features/step_definitions/machine_set.rb
lib/openshift/machine.rb

This enhancement makes sure that if there were machine in 'Deleting' phase, the machine and its node must disappear. If machine phase is not 'Deleting', the machine must have a nodeRef and the node must be 'Running'.
This guarantees a consistent environment during test and after test tear down.
@sunzhaohua2 @miyadav Please review. @qinpingli FYI.

Ensure machine/node consistency after scenario

---

features/upgrade/machines/machines.feature

As subject, I'd like to to have CI automatically cover upgrade test scenarios. I've tested them locally. @geliu2016 @pruan-rht @akostadinov Would you please review? 
```
4 scenarios (4 passed)
31 steps (31 passed)
5m59.788s
[08:29:37] INFO> === At Exit ===
```

Verify machine-api components are functional after upgrade

---

lib/rules/web/admin_console/4.3/actions.xyaml
lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
lib/rules/web/admin_console/4.4/actions.xyaml
lib/rules/web/admin_console/4.4/common_ui_elements.xyaml

Update for both 4.3 and 4.4 for stable:
1) expect the kebab actions list open then choose the item
2) submit_changes actually existed then click it
Console 4.x framework is using ::after and ::before a lot, which makes our xpath unstable.
Refer to https://css-tricks.com/almanac/selectors/a/after-and-before/
Suggest solutions:
1) use expect before the click option (or before the next move, such as goto actions)
2) use CSS instead of xpath for more stable
Either one is okay.
This affects **OCP-25763** and **OCP-25800**, used to be failed: http://pastebin.test.redhat.com/835297
So I update it by 1st solution.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/68535/console
@yapei @SSshahan @yanpzhan I suggest to have a discussion about this.
@yapei For this case, …

add a rule to make sure kebab actions list open before next click

---

features/routing/rate-limit.feature
features/routing/route.feature

OCP-18482: Since the max concurrent connections is related the number of router pods as well as the clould LB, we cannot tested it with `curl` anymore. The new solution is more straightforward and just check haproxy.conf in router pod. 
OCP-9650: remove the redundant matching string, if the output contains `Hello-OpenShift` then that means the HTTP status code should be `200`.

update OCP-18482 and OCP-9650

---

features/machine/machine.feature
lib/openshift/machine.rb

Automate test case OCP-25608: Machine should have immutable field providerID and nodeRef.
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/70717/console
@jhou1 @miyadav please help to review, thanks.

Auto OCP-25608

---

lib/rules/web/admin_console/4.2/common_ui_elements.xyaml
lib/rules/web/admin_console/4.3/actions.xyaml
lib/rules/web/admin_console/4.3/common_ui_elements.xyaml
lib/rules/web/admin_console/4.3/user_management.xyaml
lib/rules/web/admin_console/4.3/users.xyaml
lib/rules/web/admin_console/4.4/common_ui_elements.xyaml
lib/rules/web/admin_console/4.4/user_management.xyaml
lib/rules/web/admin_console/4.4/users.xyaml

During debugging for OCP-24232, I found that the action `click_one_operation_in_kebab|Cancel Build` always fail at clicking at `Cancel Build` button at the first time, it only succeeded at the 2nd time
```
When I perform the :click_one_operation_in_kebab web action with:
| resource_name  | ruby-sample-3 |
| kebab_item     | Cancel Build  |
Then the step should succeed
When I perform the :confirm_cancel_action web action with:
| cancel | true |
Then the step should succeed
```
Then I found when we open kebab button, the list items in kebab are disabled at first then enabled if user has enough permission. So I added `not(contains(@class,'pf-m-disabled')` to make sure kebab list item is enabled then it can be clicked at anytime
```
//button[contains(@class,'pf-c-dropdown__menu-item') and …
```

fix kebab list item issue

---

features/step_definitions/machine_healthcheck.rb

Due to a recent change in 4.4, we no longer need to annotate the machine to ensure a successful deletion of when it has unreachable nodes. This PR addresses it.
@sunzhaohua2 @miyadav @pruan-rht PTAL

No need to not annotate machine after version 4.4

---

lib/openshift/machine.rb

@miyadav once this PR is merged, then you can reduce your scenario to these two lines
```
And evaluation of `BushSlicer::Machine.list(user: admin, project: project('openshift-machine-api'))` is stored in the :machines clipboard
Then the expression should be true> cb.machines.select {|m| m.instance_state == m.annotation_instance_state }.count == cb.machines.count
```

helper for pr731

---

lib/openshift/cron_job.rb
lib/openshift/pod_replicator.rb

PR #733 introduced the warning message 
```
/home/pruan/workspace/bushslicer/lib/openshift/pod_replicator.rb:115: warning: circular argument reference - user
/home/pruan/workspace/bushslicer/lib/openshift/cron_job.rb:42: warning: circular argument reference - user
```

fix warning introducted by PR 733

---

features/step_definitions/machine_healthcheck.rb

In 4.3, to make a node NotReady, kill the `hyperkube` process; in >= 4.4, kill the `kubelet` process. Add a condition so that the case runs well for 4.3.
At the same time, increase the timeout because on Azure and OSP, the instance creation/deletion is slower. 
@sunzhaohua2 @miyadav @liangxia PTAL

Enhance machine healthcheck test for 4.3

---

lib/webauto/web4cucumber.rb

I tried using `BUSHSLICER_CONFIG='{"global": {"browser": "chromium"}}'`
Previously printed error:
```
Not implemented yet (RuntimeError)
```
which was vague, I thought maybe the step definition was unimplemented?
now shows:
```
Web4Cucumber: browser type 'chromium' not supported (RuntimeError)
```
(turns out I want "chrome" not "chromium")

Clearer error message when BUSHSLICER_CONFIG "browser" value is bad

---

features/step_definitions/networking.rb

Run `ovs-appctl -t /var/run/ovn/ovnnb_db.ctl cluster/status OVN_Northbound`
on any ovnkube-master node and parse the output to find the leader pod

OCP-26089: add step to find OVN Raft leader pod

---

features/machine/machine.feature

We implemented a step to clone a machineset, we'd like to use the cloned machineset to scale up and down. This way it is less likely to interrupt the cluster and is easier to clean up after scenario.
@sunzhaohua2 @miyadav @liangxia @pruan-rht PTAL, thank you.

Use a cloned machineset to scale up and down

---

lib/rules/cli/4.4.yaml

https://github.com/openshift/verification-tests/pull/763 adds `oc create_deployment` in 4.1/4.2/4.3. We also need it in 4.4+

Adding support for oc create_deployment in 4.4+

---

features/step_definitions/helper_services.rb

For some reason the current the other regexp wasn't workng for me with quotes,
so I tried switching to OPT_QUOTED.
We probably should switch to the regular OPT_QUOTED regexp anyway.

pod-for-ping: switch to OPT_QUOTED

---

features/upgrade/olm/upgrade.feature

Now, it uses the cluster-scope etcd-operator in https://github.com/openshift/verification-tests/blob/master/features/upgrade/etcd/upgrade.feature#L6.
After the above test finished the `prepare` scenario, the following subscription of etcd-operator will be blocked even if you use namespace-scoped one. See logs: http://virt-openshift-05.lab.eng.nay.redhat.com/buildcorp/Runner-v3/74178/console
```cucumber
...
STDERR:
Error from server (NotFound): deployments.extensions "etcd-operator" not found
deployment "etcd-operator" did not appear within timeout (RuntimeError)
/home/jenkins/workspace/Runner-v3/features/step_definitions/resources.rb:151:in `/^(I|admin) waits? for the "(.+?)" (\w+) to appear(?: in the(?: "(.+?)")? project)?(?: up to (\d+) seconds)?$/' …
```

remove the etcd-operator part from OLM

---

features/upgrade/svcat/upgrade.feature

Upgrade the svcat OCP-22621 , Please help  review it @jianzhangbjz  @chengzhang1016 . Thank you.
The test log:
@admin @upgrade-prepare @users=upuser1,upuser2
Scenario: upgrade svcat - prepare                                                                         # features/upgrade/svcat/upgrade.feature:9
[12:04:43] INFO> === Before Scenario: upgrade svcat - prepare ===
[12:04:44] INFO> === End Before Scenario: upgrade svcat - prepare ===
Given the "service-catalog-apiserver" operator version matchs the current cluster version               # features/step_definitions/operators.rb:29
[12:05:02] INFO> Exit Status: 0
| resource      | ServiceCatalogControllerManager         |
| resource_name | cluster                                 |
| p             | {"spec":{"managementState": …

Auto the upgrade of svcat

---

features/step_definitions/networking.rb

we often met error : 192.168.1.1 is already used .
try to debug, found sometimes the dnsmasq.conf will be append two times.
So update '>>' to ">'. and file the dnsmasq config with 
https://github.com/openshift-qe/v3-testfiles/pull/1234
@anuragthehatter @huiran0826 @weliang1 @rbbratta

update dnsmasq config file

---

features/step_definitions/logging_metrics.rb
lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

Hawkular is replaced by cluster monitoring.
`oc adm diagnostics` is replaced by operator-based diagnostics.

Remove adm_diagnostics from 4.x as it is an 3.x command

---

features/test/registry.feature
lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

`oc adm registry` is replaced by the Image Registry Operator.

Remove adm_registry from 4.x as it is an 3.x command

---

features/machine/machine_healthcheck.feature

The difference with test OCP-25897 is this scenario create unhealthy machine before creating MHC. This is extends the coverage for MHC.
```
[05:39:08] INFO> Exit Status: 0
[05:39:08] INFO> === End After Scenario: Create a machinehealthcheck when there is already an unhealthy machine ===
8 steps (8 passed)
17m43.191s
```
@sunzhaohua2 @miyadav Please review.

Automate test case OCP-26311

---

lib/webauto/web4cucumber.rb

Some UI test cases are failed due to the opened window is too small to click. Require Chrome likes firefox to support resizing the window too. Please help review. Thanks.

allow resizing window for Chrome

---

features/step_definitions/helper_services.rb

The NFS server need privileged SCC, so ensure admin tagged.

Ensure admin tag for NFS server as it needs SCC

---

features/machine/machine_healthcheck.feature

Having multiple MHC for same machineset, the machine can be remediated. @sunzhaohua2 @miyadav PTAL.
```
[02:41:45] INFO> === End After Scenario: Create multiple MHCs to monitor same machineset ===
11 steps (11 passed)
17m12.245s
```

Automate OCP-25734

---

features/upgrade/svcat/upgrade.feature

Remove the Upgradeable status check before upgrade the cluster since it is not the same in OCP 4.3 4.2 4.1.

modify the status of upgradeable

---

lib/rules/web/admin_console/4.4/configmap.xyaml

Affect case OCP-24342
Now the xpath has been updated. 
@yapei Please help to review. Thanks!
PASS on 4.4: https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/75851/console

Fix rule check_binary_data_contains for 4.4

---

lib/openshift/pod.rb

This function is to get pod.nominatedNodeName to test priority/preemption scheduling

Add support to get pod nominatedNodeName

---

features/cli/oc_volume.feature

Fix the failed case with deprecated OC command.
> Command "new" is deprecated, use oc create secret
[Pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?9c2dba6b7dc31c52#i7IPi4WivzM7Ek4fEUkNByV2OZYzhRuU4/3sS+cviLs=)

Updtae: Fix OCP-11906

---

features/storage/security.feature

For 4.x, AWS, GCE, and Azure will be deployed in multiple zones by default, so for cases OCP-9700 and OCP-9699 will hit the volume attach failed error, if the volume and pod are not in the same zone.
This pr bases on all the default sc's binding mode is `WaitForFirstConsumer` in OCP4.x, this will avoid the attached failed issue in a multiple zones cluster.
So, in this pr, use the pvc instead of pv.

Bug fix for volume attached failed when volume and pod are in different zones

---

features/networking/operator.feature

the old steps often caused error: 
```
[08:17:03] INFO> === After Scenario: The clusteroperator should be able to reflect the realtime status of the network when a new node added ===
[08:17:03] INFO> Step: I run the :scale admin command with:
| resource | machineset                  |
| name     | qeci-2891-2jv2j-worker-us-east-2a        |
| replicas | 1 |
| n        | openshift-machine-api       |
[08:17:03] INFO> Shell Commands: http_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@ec2-3-15-229-24.us-east-2.compute.amazonaws.com:3128
https_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@ec2-3-15-229-24.us-east-2.compute.amazonaws.com:3128
oc scale machineset qeci-2891-2jv2j-worker-us-east-2a --replicas=1 --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig -n …
```

update cases ocp-22202

---

lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

In 4.x, Certificates are managed by Operators internally.
```
$ oc/oc-4.1.35-202002140309.git.0.7bfae40.el7 adm --help
Administrative Commands
Actions for administering an OpenShift cluster are exposed here.
Usage:
oc adm [flags]
Cluster Management:
upgrade                            Upgrade a cluster
top                                Show usage statistics of resources on the server
must-gather                        Launch a new instance of a pod for gathering debug information
Node Management:
drain                              Drain node in preparation for maintenance
cordon                             Mark node as unschedulable
uncordon                           Mark node as schedulable
taint                              Update the taints on one or more nodes
node-logs …
```

Remove adm_ca from 4.x as it is an 3.x command

---

features/step_definitions/logging.rb

I open this PR to extend time to waiting for logging resources to appear and use another method to get the channel name when subscribe logging operators. @anpingli PTAL, thanks.

extend time to waiting for logging resources to appear

---

features/machine/autoscaler.feature
lib/openshift/machine_set.rb

This should fix the issue in https://issues.redhat.com/browse/OCPQE-34. It includes fixes to:
-  `the expression should be true` was incorrectly used which always returns true
- Update the `#ready?` to firmly check machineset has consistent `availableReplicas`, `readyReplicas`, `replicas` and `fullyLabeledReplicas`. Description of these fields are in https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_03_machineset.crd.yaml#L223
I've tested all autoscaler test on GCP which we fail often, now they are all passing.
@sunzhaohua2 @miyadav PTAL

Fixing autoscaler test flakes

---

features/networking/sdn.feature

With openshift/verification-tests#626 we can
save the node yaml and use it to re-create
the node after deletion

OCP-14985: re-create the node after deletion

---

features/step_definitions/machine.rb

Thanks to @miyadav reporting, fix the step definition so that test will fail on UPI because the way UPI is installed, it has no valid machinesets.

Fix step definition because #ready? returns a hash not a boolean

---

features/machine/autoscaler.feature

Automated autoscaler test case OCP-23745.
```
[02:57:36] INFO> === End After Scenario: Delete machineautoscaler related machineset doesn't exist ===
10 steps (10 passed)
0m27.352s
```
@jhou1 @miyadav please help to review, thanks.

auto OCP-23745

---

lib/environment.rb

Problem:
We re-use the service project each time we do step
"run commands on the host"
the clean_up method deletes the project.
When running lots of commands on the host
the after cleanup and before the next access
the service_project can be in the `Terminating` phase
```
[15:43:58] INFO> Shell Commands: oc get projects tests-cucushift-oc44-standard-slave-gtknl-0 --output=yaml --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig
apiVersion: project.openshift.io/v1
kind: Project
....
status:
phase: Terminating
[15:43:59] INFO> Exit Status: 0
[15:43:59] INFO> Shell Commands: oc debug  --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig -n tests-cucushift-oc44-standard-slave-gtknl-0 node/qeci-3419-8s8xx-control-plane-0 -- chroot /host/ bash -c …
```

fix service_project.exists? race condition

---

tools/openshift-ci/Dockerfile.centos

From https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_verification-tests/784/pull-ci-openshift-verification-tests-master-images/2689
--> RUN scl enable rh-ror50 /verification-tests/tools/hack_bundle.rb
$ bundle install --gemfile=/verification-tests/tools/hack_gemfiles/Gemfile_nokogiri
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Resolving dependencies...
Using bundler 2.1.4
Using nokogiri 1.7.0.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle install --gemfile=/verification-tests/tools/Gemfile
Don't run Bundler as root. Bundler can ask for …

Bump up ruby24 to ruby26

---

features/networking/pod.feature
features/networking/sdn.feature

This test case was created during 4.2 but eluded testing on 4.3 and 4.4 but its working as expected..phewww. We don't know why the future release versions were never updated in Polarion for this case. I have manually fixed it now and get this automated.
Logs: http://pastebin.test.redhat.com/846486
@weliang1 @zhaozhanqi @huiran0826 @rbbratta 
(Thanks @pruan-rht for helping catching an issue here as i was checking pod running status instead should have checked Ready. Learnt that in pod state table, running comes earlier than Ready :) . So if you check a pod ip on running status it may may not get assigned but definitely get assigned in Ready state)

OCP-25294, OCP-25787 and OCP-26373

---

features/step_definitions/networking.rb

@pruan-rht Can you help merging this?
This step sometimes fails on misc clusters complaining say 192.168.1.1 is already in use. arp -a output will always help us regardless of fail or pass. Its not reproducible on personal setups.Thanks!

Add arp command to help debug

---

features/step_definitions/node.rb

Adding a library to set all the worker nodes in the cluster to unschedulable state.

Add lib to set all workers as unschedulable

---

features/machine/machine_healthcheck.feature

Scenario: prevent remediation with `maxUnhealthy`. Also combines the test scenario with OCP-25687 for testing the together in automation is easier.
Tested and passed
```
[10:06:53] INFO> === End After Scenario: Use "maxUnhealthy" to prevent automated remediation ===
11m49.742s
```
@sunzhaohua2 @miyadav PTAL

Automate OCP-25691

---

features/step_definitions/networking.rb

Fixing a step definition impacted by BUSHSLICER_HOME changes. Its causing couple of dependent cases to fail. Also making quick debug steps more clear. 
@pruan-rht PTAL and help merging it
Re-ran Logs: http://pastebin.test.redhat.com/848845
cc @zhaozhanqi

Fixing a step definition impacted by BUSHSLICER_HOME changes

---

features/build/buildconfig.feature
features/build/buildlogic.feature
features/build/stibuild.feature
features/cli/build.feature
features/routing/rate-limit.feature
features/routing/wildcard-route.feature

Using short parameters can adapt to the URL change, e.g, from v3-testfiles to integrate test files (or any other changes like this in the future), without any change in Polarion in future.
Also, a shorter parameter is more readable.
/cc @xiuwang @zhaozhanqi @lihongan

Shorten the parameters

---

features/cli/policy.feature
features/test/http.feature

As the change from v3-testfiles to integrated test files, some steps that use 'download a file from' is no longer needed.

Fix step that download file from relative path

---

lib/webauto/web4cucumber.rb

To resolve issue:
unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed (Session info: chrome=80.0.3987.116)
Selenium::WebDriver::Error::UnknownError
……
[07:25:14] ERROR> Test Execution will finish prematurely.
invalid session id (Selenium::WebDriver::Error::InvalidSessionIdError)
#0 0x559cd1a6bd29 <unknown>
The fix is for chrome to provide more disk. Run batch of jobs against chrome, no this kind of error now: http://pastebin.test.redhat.com/849034
@liangxia @akostadinov @pruan-rht pls help to review, thanks!

Fix browser exit for invalid session id

---

features/networking/operator.feature

in 4.1. the error message is 
```
message: 'Not applying unsafe configuration change: invalid configuration: [cannot
change openshift-sdn configuration]. Use ''oc edit network.operator.openshift.io
cluster'' to undo the change.'
```
update this for it can be compatible.
@anuragthehatter @huiran0826 @weliang1 @rbbratta

update the error message

---

lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

- Add create_poddisruptionbudget for 4.4+ (already have that in 4.1.yaml)
```
$ ~/oc/oc-4.4.0-202003060720.git.0.f2e420d.el7 create poddisruptionbudget --help
Create a pod disruption budget with the specified name, selector, and desired minimum available pods
Aliases:
poddisruptionbudget, pdb
Usage:
oc create poddisruptionbudget NAME --selector=SELECTOR --min-available=N [--dry-run] [flags]
```
- Sync oadm_inspect in 4.1/4.4 (We have the command in 4.1 and 4.4, but some options with different names)
```
features/registry/registry.feature:    When I run the :oadm_inspect admin command with:
features/registry/registry.feature-      | resource_type | co             |
features/registry/registry.feature-      | resource_name | image-registry |
features/registry/registry.feature-    Then the …
```

Add create_poddisruptionbudget for 4.4, sync oadm_inspect in 4.1/4.4

---

tools/openshift-ci/Dockerfile.centos

++ curl -sSL https://api.github.com/repos/mozilla/geckodriver/releases/latest
++ grep -E 'browser_download_url.*linux64'
++ sed -E 's/.*(https[^"]*).*/\1/'
+ GECKODRIVER_DOWNLOAD_URL=https://github.com/vladikoff
+ curl -sSL https://github.com/vladikoff
+ bsdtar -xvf - -C /usr/local/bin
bsdtar: Error opening archive: Unrecognized archive format
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN set -x &&     SCL_BASE_PKGS="centos-release-scl scl-utils-build" &&     INSTALL_PKGS="rh-ruby26 rh-ruby26-ruby-devel rh-git218 bsdtar" &&     yum -y update &&     yum install -y --enablerepo=centosplus $SCL_BASE_PKGS &&     yum install -y --enablerepo=centosplus $INSTALL_PKGS &&     GECKODRIVER_DOWNLOAD_URL="$(curl -sSL …

Fix occacional failure of ci job

---

features/machine/machine_healthcheck.feature
features/step_definitions/machine.rb
features/step_definitions/machine_set.rb
testdata/cloud/autoscaler-auto-tmpl.yml

Increase wait time to make the tests more stable. Currently scale down takes longer than scale up, and sometimes test exit before nodes are scaled down. @sunzhaohua2 @miyadav PTAL

Making test more stable

---

lib/rules/web/admin_console/4.4/goto.xyaml

I've been wanting to suggest the change since 3.x. Since 4.x has some changes on console rendering, automation sometimes fail when page is directing and automation is doing some operation(like click) simultaneously.
The reason I update goto rules:
Test step itself should ensure the current action succeed, not the following step wait for the following checkpoint, it’s not clear for debug.
The wait_box_loaded (_css: .loading-box__loaded_) will be succeed even when the page has no item (but not a total empty crashed page), it makes sure the current page finished loading, that's the complete operation for goto action. IMO this can not rely on following steps, also the timeout for next step may not be enough.
I tested each page updated for the goto action.
So far I only update the …

Ensure goto action complete loading current page

---

features/node/proxy.feature

This covers the proxy config validation for node, verified it works. @sunilcio @weinliu @lyman9966 PTAL.
```
[09:10:07] INFO> Exit Status: 0
[09:10:07] INFO> === End After Scenario: Proxy config should be applied to kubelet and crio, Examples (#2) ===
2 scenarios (2 passed)
16 steps (16 passed)
0m43.251s
```

Node proxy config verification

---

features/cli/policy.feature

Tested with 4.1.0-0.nightly-2020-04-06-191437 locally,
```
[10:14:13] INFO> Exit Status: 0
[10:14:13] INFO> === End After Scenario: Could get projects for new role which has permission to get projects ===
9 steps (9 passed)
0m55.332s
[10:14:13] INFO> === At Exit ===
```

Fix OCP-12430

---

lib/ssh.rb
lib/test_case_manager.rb

Even though we waited for SCP channel to close when uploading,
seems like closing session too early after channel shows inactive causes
the thread doing `session.process` to fail.
I don't know why timing makes a difference but either way it makes
sense to wait for all channels to become inactive, disable error reporting
of thread and kill it before closing the session.
tested with Runner-v3/83430 and last scenario indeed gets log uploaded

SSH session closed while IO thread listening

---

lib/rules/web/admin_console/4.3/projects.xyaml

Rule needs fix, there is a Chinese colon character.
Failed log which terminated run by OCP-26910:
```
/home/jenkins/workspace/Runner-v3/lib/rules/web/admin_console/4.3/projects.xyaml
http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/04/05/23:38:57/Check_resource_events/console.html
(/home/jenkins/workspace/Runner-v3/lib/rules/web/admin_console/4.3/projects.xyaml): could not find expected ':' while scanning a simple key at line 17 column 1
Psych::SyntaxError
```
@liangxia Please review. Thx

fix rule for a Chinese colon character

---

features/quickstarts/quickstarts.feature

OCP-9570 only applies to OCP 3.2~3.4, and it's in Inactive status now.
Should be safe to remove from master branch (for 4.x), as we still have it in v3 branch (for 3.x)
/cc @dongboyan77  @wzheng1  @pruan-rht @akostadinov

Clean-up OCP-9570 (3.x scenarios, not suitable for 4.x)

---

features/networking/sdn.feature

This CI case found errorneous during CI run on 4.3 however works fine on 4.4. Made it compatible on both 
@zhaozhanqi @pruan-rht 
4.3 logs: http://pastebin.test.redhat.com/848931
4.4 logs: http://pastebin.test.redhat.com/848927

modifed OCP-25787 to support 4.3 and 4.4 releases

---

features/networking/egress-ip.feature

OCP-21812 - [bz1609112][egressIP] Should remove the egressIP from the array if it was not being used
OCP-15473 - [egressIP] The related iptables/openflow rules will be removed once the egressIP gets removed from netnamespace
Multiple test cases pointing to the same scenario (not scenario outline) does not look correct to me.
I'm removing the "wrong" ID OCP-15473 here based on the test case title, and moved OCP-15473 to not automated in Polarion.
@huiran0826  Please take follow up action for the test cases in Polarion.
/cc @akostadinov @pruan-rht

Fix case ID

---

features/machine/autoscaler.feature

This pr will fix the failer `pattern not found: (?-mix:Annotations:\s+<none>) (RuntimeError)` in 4.5 env,  this failed beacause in 4.5  machines have annotations by default  in order to support autoscaler scale from zero. @jhou @miyadav Please help to take a look? Tested on 4.4 and 4.5 env.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/84393/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/84392/console

fix machine annotations don't match the output

---

lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

Fix the error as follow:
$oc new-build --binary true --name=multistage-test 
STDERR:
error:  local file access failed with: stat true: no such file or directory
error: unable to locate any images in image streams, templates loaded in accessible projects, template files, local docker images with name "true"
@openshift/devexp-qe  please check it, thanks

Fix new-build with binary option

---

features/step_definitions/networking.rb

In step:
Given /^I wait for the networking components of the node to become ready$/ do
we don't use the admin user to check the pods so we fail with
```
Error from server (Forbidden): pods "sdn-cxjsw" is forbidden: User "testuser-0" cannot get resource "pods" in API group "" in the namespace "openshift-sdn"
```
Normally we switch to the admin user for these tests, but in the cases when we don't
we should use the correct user in the step.

use admin for checking OpenShiftSDN pods

---

features/networking/service.feature

Timeouts >= 8 seconds work, but less than that the service
doesn't seem to unidle in time.

OCP-26035: increase unidle check timeout to 30 seconds.

---

features/networking/multus-ipv6.feature
testdata/networking/multus-cni/NetworkAttachmentDefinitions/IPv6/macvlan-bridge-v6.yaml
testdata/networking/multus-cni/Pods/IPv6/1interface-macvlan-bridge-v6.yaml

Auto cases OCP-28968: IPv6 testing for OCP-21151: Create pods with multus-cni - macvlan bridge mode	
Test case in polarion:
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-28968
Automation logs:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3-smoke/855/console
Please help to review both test case and automation scripts, thanks!

Automate OCP-28968

---

features/storage/add_update_delete_volume.feature

previously tested with client 4.2 and pass.  But when I switched to client version 4.3.x and 4.4.x, it failed due to label mismatch.

more update for ocp 10284 

---

features/storage/hostpath.feature

[Those test cases](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitems?query=id%3A(OCP%5C-9640%20OCP%5C-11726)) only apply to OCP 3.x, should be safe to remove from master branch which is for 4.x, as we still have it in v3 branch (for 3.x)
/cc @qinpingli @chao007 @pruan-rht @akostadinov

Clean-up OCP-9640/11726 (3.x scenarios, not suitable for 4.x)

---

features/svc-catalog_asb/svc-catalog.feature

Update the way about how to clean up the ups-broker.
test result:
@admin @destructive
Scenario: service-catalog walkthrough example                                                           # features/svc-catalog_asb/svc-catalog.feature:7
[03:18:20] INFO> === Before Scenario: service-catalog walkthrough example ===
[03:18:20] INFO> === End Before Scenario: service-catalog walkthrough example ===
Given I have a project                                                                                # features/step_definitions/project.rb:7
[03:18:20] INFO> HTTP GET https://api.qe431316.qe.devcluster.openshift.com:6443/.well-known/oauth-authorization-server
[03:18:20] INFO> HTTP GET took 0.429 sec: 200 OK | application/json 648 bytes
[03:18:20] INFO> HTTP GET …

Update the way to cleanup the ups-broker

---

lib/openshift/deployment.rb

helper method to get the containers spec within a deployment object (https://github.com/openshift/cucushift/pull/7588)

added method to get the containers spec

---

features/step_definitions/operators.rb

Modify operators.rb to judge whether it's OCP-4.1 since no Upgradeable condition in OCP-4.1

Modify operators.rb to judge whether it's OCP4.1 since no Upgradeable

---

features/machine/machine_healthcheck.feature

The test fails on 4.3 because we wanted to catch too many texts. Now catch only what is important from the controller log.

Match only positive text for version<=4.3

---

lib/launchers/amz.rb

Make framework can use standard credentials file like following:
```
[default]
aws_access_key_id = xxxx
aws_secret_access_key = xxx
```
And then the creds can be shared with other AWS SDKs.

Align to standard aws credential file format

---

features/machine/machine.feature

hi @akostadinov  , As you suggested to creating a pull request 
logs : 
.
.
.waiting for operation up to 3600 seconds..
Then I run the :get admin command with:                                                                                            # features/step_definitions/cli.rb:31
[02:28:07] INFO> Shell Commands: oc get machine miyadav-2603-gcsjd-worker-us-east-2a-xsngw -o yaml --config=/root/workdir/efd4aeb4bf8d-/ocp4_admin.kubeconfig
STDERR:
Error from server (NotFound): machines.machine.openshift.io "miyadav-2603-gcsjd-worker-us-east-2a-xsngw" not found
[02:28:07] INFO> Exit Status: 1
| resource      | machine           |
| resource_name | <%= cb.machine %> |
| o             | yaml              |
And I save the output to file>machines_to_taint.yml …

OCP-24363 - Reconciling machine taints with nodes

---

lib/openshift/machine.rb

Validated the update to code 
[05:53:45] INFO> Exit Status: 0
Then the expression should be true> cb.machines.select{|m|m.instance_state == m.annotation_instance_state}.count == cb.machines.count     # features/step_definitions/common.rb:133
[05:53:45] INFO> === After Scenario: Verify all machine instance-state should be consistent with their providerStats.instanceState ===
[05:53:45] INFO> Shell Commands: rm -r -f -- /root/workdir/c92ee1977c9c-
[05:53:45] INFO> Exit Status: 0
[05:53:45] INFO> === End After Scenario: Verify all machine instance-state should be consistent with their providerStats.instanceState ===
3 steps (3 passed)
0m7.197s
[05:53:45] INFO> === At Exit ===

Update to handle instanceState node changed to vmState in Azure clusters

---

features/machine/machine.feature

According to this test: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/87184/consoleFull, this step failed "`Failed to restore cluster, expected number of nodes 9, got 6 (RuntimeError)`". It is because the cluster was not restored. @jhou1 @miyadav Please help to take a look.

fix OCP-27609

---

features/networking/sdn.feature
features/step_definitions/networking.rb

Just modifying couple of inf names in OVN due to underlying (merged ) dev PRs
https://github.com/ovn-org/ovn-kubernetes/pull/1165
https://github.com/ovn-org/ovn-kubernetes/pull/1181
This is causing CI failures in tests dependent on earlier inf names. Please merge it on urgent basis if possible @pruan-rht 
cc @zhaozhanqi @rbbratta @weliang1 
re-ran couple of tests: http://pastebin.test.redhat.com/859952

Modifying interface names on OVN

---

features/machine/autoscaler.feature
features/machine/machine.feature
features/machine/machine_healthcheck.feature
features/step_definitions/machine_set.rb
features/upgrade/machines/machines.feature

made the change using - find /home/miyadav/verification/verification-tests -type f -exec sed -i 's/machineset named/machineset and name it/g' {} \;
Ran one of the cases involving changes , it works fine 
instanceId: i-03e5945954debaed4
instanceState: running
kind: List
metadata:
resourceVersion: ""
selfLink: ""
[06:14:26] INFO> Exit Status: 0
Then the expression should be true> cb.machines.select{|m|m.instance_state == m.annotation_instance_state}.count == cb.machines.count     # features/step_definitions/common.rb:133
[06:14:26] INFO> === After Scenario: Verify all machine instance-state should be consistent with their providerStats.instanceState ===
[06:14:26] INFO> Shell Commands: rm -r -f -- …

Making more readable clone machineset step

---

features/networking/multus.feature

OCP-25915: update to use "master": "<%= cb.default_interface %>"
Log:https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1001/console
OCP-28518: update to use "paths" from "path:
Log:https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1003/console
OCP-24489: update to use public repo not private repo
Log:https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1002/console
@anuragthehatter @rbbratta @zhaozhanqi @huiran0826

Fix OCP-25915 OCP-24489 OCP-28518

---

features/step_definitions/file.rb

if the user input the correct path like `<%= BushSlicer::HOME %>/features/tierN/testdata/daemon/daemonset.yaml` into the method, the error message currently prints the correct path which is misleading.  We should print the actual paths that were tried instead.   
>     Given I obtain test data file "<%= BushSlicer::HOME %>/features/tierN/testdata/templates/OCP-12856/push-generic-build-args.json" # features/step_definitions/file.rb:1
>       could not find test file in '["/Users/pruan/workspace/BushSlicer/testdata//Users/pruan/workspace/BushSlicer/features/tierN/testdata/templates/OCP-12856/push-generic-build-args.json", "/Users/pruan/workspace/BushSlicer/features/tierN/testdata//Users/pruan/workspace/BushSlicer/features/tierN/testdata/templates/OCP-12856/push-generic-build-args.json"]' …

Print out all of the actual tried paths

---

features/logging/cluster_logging_operator.feature
features/logging/collector.feature
features/logging/elasticsearch.feature
features/logging/elasticsearch_operator.feature
features/step_definitions/logging.rb
features/support/clusterlogging_env.rb
features/test/logging_metrics.feature
lib/openshift/cluster_logging.rb
testdata/logging/clusterlogging/example_indexmanagement.yaml

There have some differences between logging 4.5 and logging 4.1~4.4, I update some steps to make them could match logging 4.5. @anpingli PTAL, thanks.
I have executed all the existing cases with these changes in logging 4.4, the logs are in the below:
Logs: https://url.corp.redhat.com/496eeb6 (2 cases failed, but weren't caused by these changes)

update steps to match logging 4.5

---

features/logging/collector.feature

Pass log: 
`      [11:24:35] INFO> Exit Status: 0
"""
Then I perform the HTTP request on the ES pod with labels "es-node-master=true":
| relative_url | _search?pretty&size=0' -H 'Content-Type: application/json' -d'{"aggs" : {"exists_field_kubernetes" : {"filter": {"exists": {"field":"kubernetes"}},"aggs" : {"distinct_fluentd_ip" : {"terms" : {"field" : "pipeline_metadata.collector.ipaddr4"}}}}}} |
| op           | GET     |
Then the step should succeed
Given evaluation of `JSON.parse(@result[:response])['aggregations']['exists_field_kubernetes']['distinct_fluentd_ip']['buckets'].map {|furn| furn["key"]}` is stored in the :kuber_ips clipboard
And the expression should be true> Set.new(cb.collector_pod_ips) == Set.new(cb.kuber_ips)
And I perform the HTTP request on the ES pod with labels …

fix issue for logging 4.1

---

lib/openshift/project.rb
lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

`Command "can-i" is deprecated, use 'oc auth can-i'`
at least since 4.2, so we might as well fix it
Fixing in 4.4 for now

oc policy can-i is deprecated

---

features/step_definitions/machine.rb
features/step_definitions/machine_set.rb

In IPI env, if there is one machineset with replicas=0 the test will be aborted. This PR will fix this issue. As long as there is one machineset with replicas > 0, the test will continue.  @jhou @miyadav Please help to take a look.

fix IPI abort test

---

features/networking/multus.feature

Fixing few code smells here which are causing "Test execution finished prematurely" errors in nightly runs. Small change and can be merged asap to avoid futrther issues @pruan-rht 
cc @weliang1 @rbbratta @zhaozhanqi @huiran0826 
When we create a bridge type net-attach-def, a bridge interface is created on the node only when a pod using that def gets created. The bridge interface doesn't gets created immediately post net-attach-def creation. So the bridge cleanup should definitely be after pod creation step.
Right now ,such tests are throwing premature failure errors due to the fact that say, a net-attach def is successfully created but test fails at pod creation step. However the cleanup is defined post  net-attach-def. So, as we never reached to a pod creation step and hence there is no …

Moving Cleanup steps to the appropriate locations

---

lib/rules/web/admin_console/4.1/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.5/common_ui_elements.xyaml
lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml

Change code to make monitoring UI cases can work on 4.5 and previous releases
Depend on PR:
https://github.com/openshift/cucushift/pull/7665
The PR also fixed intermittent test failure when integration run
https://issues.redhat.com/browse/OCPQE-231
https://issues.redhat.com/browse/OCPQE-232
V3 job on 4.4: all UI cases pass
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/87917/
V3 job on 4.5: all UI cases pass
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/88145/console

Hongyli alert browser 4.5

---

features/networking/multus.feature

Automate: Bug 1827377 - Multus namespaceIsolation should allow references to CRD in the default namespace
Test log: https://privatebin-it-iso.int.open.paas.redhat.com/?b24f41d3c9134d49#d8cj4BjfWcni7BrV1LYS7QTae8vBExEMhC5PM/ri2qY=
@anuragthehatter @rbbratta @zhaozhanqi @huiran0826

Automate BZ-1827377

---

features/networking/multus.feature

Fixed OCP-21793 due to bug https://bugzilla.redhat.com/show_bug.cgi?id=1827375. We should not create net-attach-def in default namespace now. 
Also fixed OCP-24466, we added some debug steps to it earlier to see arp entries and seems like it fails because 192.168.1.1 was already assigned in openstack cluster due to NAT'ing used there. ALl nodes seems ot be in 192.168 subnet and we use same in test http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/04/30/13:07:05/CNO_manager_macvlan_configured_manually_with_DHCP/console.html
I am simply now using rare subnet like 87.8.x.x which shouldn't have any problem.
cc @rbbratta @weliang1 
Re-ran logs, OCP-24466: http://pastebin.test.redhat.com/861157
OCP-21793: http://pastebin.test.redhat.com/861657

fixed scenarios post few bugs

---

lib/launchers/alicloud.rb

One cannot create requests knowing access key only. Also this key has been invalidated. Thus removing to keep the good example.
Reverts openshift/verification-tests#1051

Revert "remove invalid creds"

---

lib/rules/web/admin_console/4.3/operator_hub.xyaml
lib/rules/web/admin_console/4.4/operator_hub.xyaml
lib/rules/web/admin_console/4.5/check_links.xyaml
lib/rules/web/admin_console/4.5/operator_hub.xyaml
lib/rules/web/admin_console/4.5/user_management.xyaml

Fix for 4.5:
OCP-25762  click_add_more_users 
4.5 log: http://pastebin.test.redhat.com/863136
OCP-25817 change click_button_text to click_button 
4.5 log: http://pastebin.test.redhat.com/863145
4.4 log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89817/console
OCP-24287 browse_to_cli_tools_page   
4.5 log: http://pastebin.test.redhat.com/863155
OCP-24286 check_consolelink
4.5 log: http://pastebin.test.redhat.com/863175
OCP-24340 fix:  click_button web action with:
| button_text  | Edit Form |
4.5 log: http://pastebin.test.redhat.com/863203
4.4 log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/89822/console
@yapei or @hasha pls help to review, thanks!

fix web cases

---

lib/environment.rb

The command returns an hash, while we expect a string.
Also, the version does not match `/^[\d.]+$/`, e.g 4.5.0-0.nightly-2020-05-08-015855, so updated the check.
Thank you @zhouying7780 for reporting the issue.

Fix get_version from cluster version

---

features/machine/machine.feature
features/step_definitions/machine_set.rb

Automate test case OCP-29199: Required configuration should be added to the ProviderSpec to enable spot instances - AWS @jhou1 @miyadav Please help to take a look.
```
[08:50:31] INFO> === End After Scenario: Required configuration should be added to the ProviderSpec to enable spot instances, Examples (#1) ===
12 steps (12 passed)
8m13.898s
```

auto OCP-29199

---

features/step_definitions/machine_set.rb

@jhou1 @miyadav Please help to review, this will fix the below error: 
```
wrong number of arguments (given 0, expected 1..4) (ArgumentError)
/home/jenkins/workspace/Runner-v3/features/step_definitions/machine_set.rb:4:in `select'
/home/jenkins/workspace/Runner-v3/features/step_definitions/machine_set.rb:4:in `/^I pick a random machineset to scale$/'
/opt/rh/rh-ruby26/root/usr/share/ruby/forwardable.rb:230:in `invoke_dynamic_step'
/home/jenkins/workspace/Runner-v3/features/step_definitions/machine_set.rb:62:in `/^I clone a machineset named "([^"]*)"$/'
features/machine/machine.feature:128:in `And I clone a machineset named "machineset-clone-27609"'
```
Test: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/90659/console

fix wrong arguement

---

features/step_definitions/operators.rb
features/upgrade/marketplace/upgrade.feature

Fix issue: https://issues.redhat.com/browse/OCPQE-364, the CSC resource is deprecated in 4.5.
Before the upgrade, logs: http://pastebin.test.redhat.com/864064
After the upgrade, logs: http://pastebin.test.redhat.com/864092

support for 4.5

---

features/test/version_compare.feature
lib/environment.rb

In the earlier 3.x (3.4 and earlier), we use major version 3 for OSE, while major version is 1 for origin. So we need the logic to deal with the specific versions. They are not needed now (as we are in 4.x and 3.4 and earlier reached EOL).

Remove unnecessary version check

---

features/networking/sriov.feature

add sriov stage testing cases:
`
And all existing pods are ready with labels:
| app=network-resources-injector  |
And all existing pods are ready with labels:
| app=operator-webhook            |
And all existing pods are ready with labels:
| app=sriov-network-config-daemon |
And status becomes :running of exactly 1 pods labeled:
| name=sriov-network-operator     |
"""
[09:25:13] INFO> === After Scenario: sriov operator can be setup and running well ===
[09:25:13] INFO> Shell Commands: rm -r -f -- /home/zzhao/workdir/dhcp-140-240-zzhao
[09:25:13] INFO> Exit Status: 0
[09:25:13] INFO> === End After Scenario: sriov operator can be setup and running well ===
3 steps (3 passed)
`

auto sriov stage case

---

features/svc-catalog_asb/svc-catalog.feature

Let the run-test failed without "Test Execution will finish prematurely" if the cluster doesn't enable svcat.
test result:
**### 1. the cluster disable svcat**
[09:38:42] INFO> Exit Status: 1
| resource | clusterservicebroker |
Then the step should succeed                                                                          # features/step_definitions/common.rb:4
the step failed (RuntimeError)
/home/jenkins/workspace/Runner-v3/features/step_definitions/common.rb:6:in `/^the step should( not)? (succeed|fail)$/'
features/svc-catalog_asb/svc-catalog.feature:11:in `Then the step should succeed'
[09:38:50] INFO> Exit Status: 0
[09:38:50] INFO> === End After Scenario: service-catalog walkthrough example ===
Failing Scenarios:
cucumber -p polarshift -p dir_embedder …

Add the test of clusterservicebroker

---

features/machine/autoscaler.feature
features/machine/machine.feature
features/machine/machine_healthcheck.feature
features/step_definitions/machine.rb
features/step_definitions/machine_healthcheck.rb
features/step_definitions/machine_set.rb
features/upgrade/machines/machines.feature
lib/openshift/machine.rb

As suggested by @sunzhaohua2 and @miyadav in test tear down we only have to wait machine to be deleted because machine will be deleted only after node is deleted. Updated the the code with fixes to several logic. Have been testing them for more than a week on different cloud.

Improve cloud tests

---

features/upgrade/marketplace/upgrade.feature

Set the value of the `NAMESPACE` instread of the default. to fix the errors below:
qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/05/15/08:03:03/upgrade_Marketplace_-_prepare/console.html
```
WhenI process and create: ==>@  features/step_definitions/cli.rb:143
f	<%= BushSlicer::HOME %>/testdata/olm/operatorsource-template.yaml
p	NAME=test-operators
p	SECRET=
p	DISPLAYNAME=Test Operators
p	REGISTRY=jiazha
08:03:19 INFO> Shell Commands: oc process -f /home/jenkins/workspace/Runner-v3/testdata/olm/operatorsource-template.yaml -p NAME\=test-operators -p SECRET\= -p DISPLAYNAME\=Test\ Operators -p REGISTRY\=jiazha --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig
STDERR:
error: unable to process template
namespaces "aos-qe-ci" not found
08:03:19 INFO> …
```

fix namespaces aos-qe-ci not found

---

features/step_definitions/networking.rb

Quick fix to avoid few test execution premature errors we have been seeing few times or rarely due to this particular step. In test env like all-in-one (node acting as both worker and master). a test interface or bridge is tried to be deleted couple of times and hence tests exit prematurely when it tries to delete an already deleted interface or bridge. This will solve this issue. Thanks
re-ran the tests to make sure
@rbbratta @zhaozhanqi @weliang1 @huiran0826

check inf first and then perform operation

---

features/machine/machine_healthcheck.feature
testdata/cloud/mhc/mhc_configurabletimeout.yaml

https://issues.redhat.com/browse/OCPCLOUD-774
V3 runner link - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/92814/console

OCP-28718 - Configurable timeout for mhc 

---

features/machine/machine.feature
features/step_definitions/machine_set.rb

I want to merge OCP-29389 into OCP-29199, and I will delete case OCP-29389. @jhou1 @miyadav Please help to review, thanks.
```
[02:10:08] INFO> === End After Scenario: Required configuration should be added to the ProviderSpec to enable spot instances, Examples (#1) ===
6m4.734s
```

merger OCP-29389 into OCP-29199 

---

features/step_definitions/logging_metrics.rb

Quick fix for the issue when running `exec` command with oc 4.5.
@pruan-rht PTAL, thanks.

fix issue running exec command with oc 4.5

---

lib/launchers/openstack.rb

```
[1] pry(#<BushSlicer::DefaultWorld>)> iaas = iaas_by_service("openstack_upshift")
[2] pry(#<BushSlicer::DefaultWorld>)> network = iaas.create_network("wjiang_test_user_defined")
=> {"ipv6_address_scope"=>nil,
"revision_number"=>3,
"port_security_enabled"=>true,
"id"=>"21e90ca6-b7f8-425c-95ae-0e8b5942bd1a",
"router:external"=>false,
"availability_zone_hints"=>[],
"availability_zones"=>[],
"ipv4_address_scope"=>nil,
"shared"=>false,
"project_id"=>"542c6ebd48bf40fa857fc245c7572e30",
"l2_adjacency"=>true,
"status"=>"ACTIVE",
"subnets"=>[],
"description"=>"",
"tags"=>[],
"updated_at"=>"2020-05-20T09:45:43Z",
"is_default"=>false,
"name"=>"wjiang_test_user_defined",
"qos_policy_id"=>nil,
"admin_state_up"=>true,
"tenant_id"=>"542c6ebd48bf40fa857fc245c7572e30", …
```

[IPI on OSP] add funtions to operate network, subnet and router

---

features/networking/multus.feature

Apparently this case depicted few failures when it ran on mixed node clusters. The reason is uniform cluster like with all RHCOS nodes, they share same master interface naming convention but if we add a RHEL worker to an existing uniform cluster, that might come up with different master interface name. We want to make sure we check IPVLAN functionality on a specific node only and that node master interface should be used in further configurations. Just a small change to alleviate CI failures.
@pruan-rht @weliang1 @rbbratta @zhaozhanqi @huiran0826 
Re-ran Logs: https://privatebin-it-iso.int.open.paas.redhat.com/?27da8e5f3fd5c146#TU8Y4xibWlmjhxQKjjwFIFHZqSfJ4o0bN5JPOIv3RPI=

Forcing scenario to execute on specific node only

---

features/step_definitions/helper_services.rb
testdata/templates/ssh-git/ssh-git-dc.yaml

Passed locally http://pastebin.test.redhat.com/868496
In 4.5, run cmd deprecated deploymentconfig, change to use dc template.

run cmd deprecated deploymentconfig, change to use dc template.

---

lib/host.rb
lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml

sometime disconnected cluster don't have the
registry.redhat.io/rhel7/support-tools image installed
so we can't run oc debug normally.
The oc debug command allows the user to override the image
so we can use can existing image, e.g. multus image or any other
existing image to run debug commands, give that we always chroot
Add the `OPENSHIFT_ENV_OCP_HOST_DEBUG_IMAGE` option to disable
using the multus image by default

always use multus image as oc debug image

---

lib/login.rb

This step is for further debugging the `Error getting bearer token` issue during login procedure.
The new added step is harmless and won't block the test execution but just print the result of HTTP.GET of console url before starting the login with normal user.  
Example:
```
Given I have a project                                                                # features/step_definitions/project.rb:7
[02:06:29] INFO> HTTP GET https://console-openshift-console.apps.hongli-pl212.qe.gcp.devcluster.openshift.com
[02:06:35] INFO> HTTP GET took 5.942 sec: 200 OK | text/html 3372 bytes
[02:06:35] INFO> HTTP GET https://api.hongli-pl212.qe.gcp.devcluster.openshift.com:6443/.well-known/oauth-authorization-server
[02:06:41] INFO> HTTP GET took 5.707 sec: 200 OK | application/json 672 bytes …
```

add debug step to isolate the auth issue

---

features/upgrade/build/build-upgrade.feature
lib/rules/cli/4.1.yaml
lib/rules/cli/4.4.yaml
lib/rules/cli/4.5.yaml

upgrade from 4.4 to 4.5: 
upgrade-prepare using oc 4.4 client , it passed [log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/98313/)
upgrade-check  using 4.5 client also passed [log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/98314/console)
@openshift/devexp-qe pls review it, thanks

Fix OCP-13025

---

features/upgrade/storage/upgrade.feature

Currently, iscsi provisioner doesn’t work smoothly during upgrade, this case is only performed on BareMetal before upgrade and after upgrade (v.s. OCP-23501):
1. The cluster operator storage should be in the correct status before and after the upgrade.
2. The cluster operator storage operator version should match the current cluster version after upgrade
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?efbbf8b6ed07e308#zlCHYPHk07qHFuHZi+q8sFzaiilIWxZwOqBPok4/cCc=)

Automate OCP-31331

---

features/step_definitions/registry.rb

After patch to enable default route, the-route need times to show up depend on the cluster performance.

Wait default-route appearing for image-registry svc

---

lib/rules/cli/4.5.yaml

use the  multus cluster image logic so we don't have to access quay.io
see #983

remove oc debug default image for 4.5

---

features/upgrade/api_auth/upgrade.feature

The case OCP-19470 is a destructive one, if it run before case OCP-13025, the original code will forbid build strategy Docker cluster role, the case OCP-13025 will run into error. To change clusterrole to build-strategy-custom, will avoid this.
Run passed case result of upgrade-prepare: -Jenkins server-/job/Runner-v3/100682/console
Run passed case result of upgrade-check: -Jenkins server-/job/Runner-v3/100732/console

OCP-19470 fix Change clusterrole to build-strategy-custom

---

features/step_definitions/machine_set.rb
lib/openshift/machine_set.rb
testdata/cloud/autoscaler-auto-tmpl.yml
testdata/cloud/mhc/kubelet-killer-pod-43.yml
testdata/cloud/mhc/kubelet-killer-pod.yml

By adding taints, only our pods with toleration can schedule to the nodes we had scaled up. No other pods can schedule there and this prevents unexpected failures in other teams' tests. For example even though our tests run in destructive mode daemonset and statefulset can still schedule pods to our nodes. This pr prevents that.
Tested and it's working well. @sunzhaohua2 @miyadav PTAL

Using taints to prevent pods from scheduling to test nodes

---

features/upgrade/node/hpa/upgrade.feature

running log: http://pastebin.test.redhat.com/872206
Adding a step of creating a pod using the configmap after the upgrade, checking it's still available after upgrade.
@jhou1 @sunilcio @lyman9966 could you help with the review? Thanks,

Fix pod using congfigmap checking issues

---

features/machine/machine_healthcheck.feature
features/step_definitions/machine_healthcheck.rb

Tested, verified. @miyadav @sunzhaohua2 PTAL
```
[03:35:31] INFO> Exit Status: 0
[03:35:31] INFO> === End After Scenario: Remediation should be applied when machine has nodeRef but node is deleted ===
12 steps (12 passed)
11m45.231s
```

Automate OCP-25727

---

features/machine/autoscaler.feature

I want to merger OCP-31315 into OCP-28108, and I will delete case OCP-31315. @jhou1 @miyadav Please help to review, thanks.
OCP-31315: DeletionCandidateOfClusterAutoscaler and ToBeDeletedByClusterAutoscaler taints should be deleted when min nodes is reached
OCP-28108: Cluster could automatically scale up and scale down with ClusterAutoscaler deployed
```
[08:50:49] INFO> === End After Scenario: Cluster should automatically scale up and scale down with clusterautoscaler deployed ===
25 steps (25 passed)
13m21.889s
```

merger OCP-31315 into OCP-28108

---

features/step_definitions/networking.rb

The case failed in ipi-vsphere ci run due to in some node, there are two IPs.  Fix the codes to just catch the first one.
Re-run logs in ipi-vsphere.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/102520/consoleFull
@zhaozhanqi @weliang1 @anuragthehatter @rbbratta

fix OCP-23893

---

features/step_definitions/pod.rb

For OVN we sometimes need to execute on a specific container
in the pod in order to directly connect to the database over
unix socket and avoid SSL network connections.

pod: allow specifying container in pod to execute on

---

features/routing/rate-limit.feature
testdata/routing/routetimeout/edge-route_edge.json
testdata/routing/routetimeout/edge-service_unsecure.json
testdata/routing/routetimeout/reencrypt-route_reencrypt.json
testdata/routing/routetimeout/reencrypt-service_secure.json
testdata/routing/routetimeout/unsecure-route_unsecure.json
testdata/routing/routetimeout/unsecure-service_unsecure.json

In order to effectively utilize the `Obtain` expression, soft links to the relevant test data files have been added to ensure the test cases get executed properly. In the current state, without this change, the `Examples` expression basically passes the raw values for the variables in the steps which cause `file/directory not found` error to occur when fetching the test data files and the execution fails. 
Due to some transient environment issues as of writing, I will share the V3-runner test with the modified test case, shortly.

OCP-18482: Modify testdata file locations

---

features/logging/elasticsearch_operator.feature
lib/openshift/elasticsearch.rb

When running automation on 4.5, some cases always failed, e.g. https://url.corp.redhat.com/5045bcf , so I updated the method to make the ES cluster unhealthy, @anpingli PTAL, thanks.

update steps to make ES cluster unhealthy

---

features/cli/deploy.feature

Replace step Given I wait for the pod named "hooks-3-deploy" to die with Given I wait for the "hooks-3-deploy" pod to die as cucumber says the step is undefined.

Remove undefined step from the script

---

features/storage/reclaim_policy.feature

Fix the issue `No such file or directory @ rb_sysopen - cinder/pv-rwx-default.json`
@qinpingli @duanwei33 Please help to check.
Cinder env is now has some issue.
I have tested similar cases on aws.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/105022/console

Fix issue about could not find files

---

features/upgrade/samples_operator/upgrade.feature

To fix: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/06/19/04:55:24/OpenShift_can_upgrade_when_image-registry_sample_operator_is_unmanaged/console.html

Fix error about cannot find project

---

features/upgrade/node/scc.feature

Fixes **OCP-13065 - could not find all scenarios**,  [build url](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/106318/console)
Scenarios names should be consistent in upgrade-prepare and upgrade-check to make sure test gets executed before and after upgrade. 
Example:
upgrade-prepare: Seccomp part of SCC policy should be kept and working after upgrade - prepare
upgrade-check: Seccomp part of SCC policy should be kept and working after upgrade

Fix ocp-13065 test flake

---

tools/jenkins/slaves/Dockerfile.centos
tools/jenkins/slaves/Dockerfile.rhel7

pip and minio are added in https://github.com/openshift/verification-tests/pull/987
We also do install python3, pip and several other packages via pip in oc4x dockerfiles, so the decision is that we move them (python3 and so on from oc4x image, and pip, minio from cucushift-public image) into cucushift-base image, to reduce some duplicate effort and building resource/time.

Remove pip and minio

---

tools/jenkins/slaves/Dockerfile.rhel7

The repo `rhel-7-server-htb-rpms` is enabled in our based image `openshift3/jenkins-slave-base-rhel7:v3.11` unexpected, causing several images updated unexpectedly, causing package conflict in our automation images building.
/cc @akostadinov @pruan-rht @jhou1

Disable unexpected repos

---

features/step_definitions/pod.rb

Incorrect constant replacement without testing.

OCPQE-933: Fix bad regexp replacement

---

features/step_definitions/metering.rb
lib/openshift/metering_config.rb
lib/openshift/package_manifest.rb
lib/openshift/storage_class.rb
lib/openshift/subscription.rb
testdata/metering/configs/metering_operatorgroup.yaml
testdata/metering/configs/metering_subscription.yaml
testdata/metering/configs/meteringconfig_sharedPVC.yaml
testdata/metering/configs/pv_metering.yaml
testdata/metering/deploy/olm/metering.catalogsource.yaml
testdata/metering/deploy/olm/metering.operatorgroup.yaml
testdata/metering/deploy/olm/metering.subscription.yaml

1. HDFS storage is for development and not production ready.  Change the default storage to use NFS/sharedPVC approach.
2. added support to install metering using OLM via CLI (quicker than from UI)
3. added support methods
4. testdata templates and actual examples.
run log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/1639/console

metering deploy refactor to use sharedPVC as default

---

features/step_definitions/helper_services.rb
features/step_definitions/pod.rb

We seem to be getting frequent pods stuck in `:pending` status
when using "pods become ready with labels:" step.
This step calls `wait_till_status`, so if we fail
we can run `oc describe pod` to try to debug the pod failure
```
Given 1 pods become ready with labels:                                                                                     # features/step_definitions/pod.rb:136
[05:56:03] INFO> oc get pods --output=yaml -l name\=test-pods --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_testuser-0.kubeconfig -n sx5hd
[05:56:03] INFO> 1 iterations for 0 sec, returned 1 pods, 1 matching
[05:56:04] INFO>
[06:11:03] INFO> After 531 iterations and 900 seconds:
matched status for pods test-rc-dgbzv: 'pending' while expecting '[:running, :succeeded, :missing]'
| …
```

debug Pending status with describe pod

---

features/infrastructure/cluster-capacity.feature
features/step_definitions/admin.rb
testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml

1.  Adding SA part to avoid access issue
2. Store shcedulable workers node only for masters are not counted in capacity
3. secret_new is deperated, re-write to using create_secret instead
running log on:
$ oc version
Client Version: 4.4.0-rc.10
Server Version: 4.5.0-rc.2
Kubernetes Version: v1.18.3+91d0edd
https://privatebin-it-iso.int.open.paas.redhat.com/?79d772b64ad3e7cf#ihVIjidhZrCQKV6V2g3KvYavN6AlI4gyz0UTA4VaSMk=
@jhou1 @sunilcio @lyman9966  could you help take a look?

Fix OCP-14799

---

features/logging/kibana.feature
features/step_definitions/logging.rb
features/step_definitions/logging_metrics.rb
lib/rules/web/admin_console/4.1/logging_kibana.xyaml
lib/rules/web/admin_console/4.2/logging_kibana.xyaml
lib/rules/web/admin_console/4.3/logging_kibana.xyaml
lib/rules/web/admin_console/4.4/logging_kibana.xyaml

Start from 4.5, the fluentd and kibana are created after the ES, so I update the steps to check ES status first.
Besides, I add some steps to cover https://bugzilla.redhat.com/show_bug.cgi?id=1835578.

check ES status first

---

testdata/logging/logforwarding/elasticsearch/secure/configmap.yaml
testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml

Currently, after deploy secured external ES sever, we need to create an user by manual, that means every time the  pod restarted, we all need to create user, that's may cause failure when run automation. Here update the deployment and configmap to make it add the user after the pod start automatically.

update external ES

---

features/logging/cluster_logging_operator.feature
features/logging/elasticsearch.feature

To fix the below failure:
```
I wait for the "elasticsearch-cdm-<%= cb.es_genuuid %>-1" deployment to appear ==>@  features/step_definitions/resources.rb:144
06:00:56 INFO> oc get deployments elasticsearch-cdm--1 --output=yaml --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig --namespace=openshift-logging
06:01:56 INFO> After 44 iterations and 60 seconds:
STDERR:
Error from server (NotFound): deployments.apps "elasticsearch-cdm--1" not found
```

fix issue: get empty genUUID

---

features/machine/machine_healthcheck.feature

Sometimes this case will meet below error.  @jhou1 @miyadav Please help to take a look.
```
[10:19:37] INFO> Exit Status: 0
| resource_name | <%= pod.name %>                |
| c             | machine-healthcheck-controller |
Then the output should match:                                                           # features/step_definitions/common.rb:33
| maxUnhealthy: 1%             |
| Short-circuiting remediation |
pattern not found: (?-mix:Short-circuiting remediation) (RuntimeError)
/home/sunny/code/verification-tests/features/step_definitions/common.rb:103:in `block (3 levels) in <top (required)>'
/home/sunny/code/verification-tests/features/step_definitions/common.rb:97:in `each'
/home/sunny/code/verification-tests/features/step_definitions/common.rb:97:in `block (2 levels) in <top …
```

fix OCP-28859

---

features/cli/oc_delete.feature

The test flakes because it assumes after 25 seconds the pod is removed from the project, which is usually not true. @sunilcio @lyman9966 @weinliu PTAL

Make OCP-12144 test more robust

---

features/machine/machine.feature

auto OCP-32620: Labels specified in a machineset should propagate to nodes. @jhou1 @miyadav help to take a look. 
```
[07:58:20] INFO> === End After Scenario: Labels specified in a machineset should propagate to nodes ===
9m37.115s
```

auto OCP-32620

---

features/cli/oc_set_probe.feature

Some versions are not include info "probe failed", so updated it
[Pass log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/100644/console)
@openshift/devexp-qe ptal, thanks

Fix OCP-31241

---

features/step_definitions/project.rb

Before the update,  the node chosen might be a master node, in OCP4.x, the pod without tolerations created in this project can not be scheduled successfully.

Update the step to avoid choosing a master node

---

lib/platform/systemd_service.rb

Try to debug systemd restart failures by
running systemctl status after systemctl restart

show systemctl status after restart

---

features/upgrade/node/node-upgrade.feature

I extend the waiting time of machineconfigpool check from 20mins to 33 mins. Because one master needs about 9-10mins to finish kubeletconfig sync and restart according to UpgradeCI log(Though it only cost about 5 mins per master in manual test), so I leave 11 mins per master and it's should be secure.

fix ocp-13022

---

features/step_definitions/scheduler.rb

Cases fail if run immediately after the scheduler operator cases, fixing the same using the PR so that no failures are seen.

Fix restore steps for scheduler

---

features/upgrade/samples_operator/upgrade.feature

Missing destructive tag , so the scenario no executed. @openshift/devexp-qe Please review, thanks!

Add destructive tag

---

features/cli/oc_volume.feature

@jhou1 @sunilcio @lyman9966  could you help to take a look?
[Last fix](https://github.com/openshift/verification-tests/pull/1180/files)  passed may because the env was not clean, old dc still existed. 
Fixing this by replacing the wrong step to a working one, creating a deploy config.
log: http://pastebin.test.redhat.com/886637

OCP-12194 fix dc creating issue

---

features/machine/machine.feature
features/step_definitions/machine_set.rb

Auto  OCP-32126: Required configuration should be added to the ProviderSpec to enable spot instances - GCP  
```
[07:48:11] INFO> === End After Scenario: Required configuration should be added to the ProviderSpec to enable spot instances, Examples (#1) ===
7m10.400s
```

auto OCP-32126

---

testdata/storage/csi/csi-hostpath-driverinfo.yaml

OCP4.4 does not support v1 version.
And test that OCP4.6 can using v1beta1 version.
So Update this csidriver to v1beta1.
@qinpingli @duanwei33 Please help to review.

Update csidriver version

---

lib/iaas/iaas.rb
lib/launchers/openstack.rb

@duanwei33 @pruan-rht Please help review.
This is the test log:
And I verify that the IAAS volume with id "<%= cb.volumeID %>" was deleted                        # features/step_definitions/pv.rb:187
[11:54:08] INFO> Shell Commands: oc get infrastructures.config.openshift.io cluster --output=yaml --kubeconfig=/root/workdir/Tester-OCP-qinping/ocp4_admin.kubeconfig
<--snip-->
[11:54:19] INFO> HTTP GET took 1.624 sec: 404 Not Found
waiting for operation …

Bug fix for connection with openstack

---

lib/cli_executor.rb

\# get `oc` version on some host running as some username
As the comment stated, we only need the client version, no need to wait to connect to server (so can also get rid of server connection issue).
/cc @pruan-rht @akostadinov @xingxingxia @barleyer 
```
$ ~/oc/oc-4.1.35-202002140309.git.0.7bfae40.el7 version -o yaml --client
clientVersion:
buildDate: "2020-02-14T03:21:57Z"
compiler: gc
gitCommit: 7bfae4041
gitTreeState: clean
gitVersion: v4.1.35
goVersion: go1.11.13
major: "4"
minor: 1+
platform: linux/amd64
$ ~/oc/oc-4.2.20-202002140432.git.1.5dc67c9.el7 version -o yaml --client
clientVersion:
buildDate: "2020-02-14T04:52:39Z"
compiler: gc
gitCommit: 7207690010f08f2ae526ee3300d4a18ea65997fe
gitTreeState: clean
gitVersion: v4.2.20
goVersion: go1.12.8
major: ""
minor: ""
platform: …
```

Fix OCPQE-1448

---

features/networking/pod.feature

Sometimes fail on mixed cluster with Rhel node. Forcing scenario to continue execution on specific node only. Little fix
@zhaozhanqi @weliang1 @rbbratta @huiran0826 
OVN logs: https://privatebin-it-iso.int.open.paas.redhat.com/?abe155052ddcb623#jX6XruTDlXvkQyucvTlDAmKVTBrF0OfATOoqNP51IxA=
SDN logs: https://privatebin-it-iso.int.open.paas.redhat.com/?015a7103cededa8e#NxHJ0679lnnyHEQMM+rxvzao0p0xCnZCCfy17+1aND4=

Forcing OCP-26822 to single node

---

tools/openshift-ci/Dockerfile.centos

```
$ curl -sSL https://api.github.com/repos/mozilla/geckodriver/releases/latest  > geckodriver
$ grep -Eo 'http.*linux64.tar.gz'  geckodriver | sed -E 's/.*(https[^"]*).*/\1/'
https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
```
/cc @pruan-rht @akostadinov @jhou1 
Currently this is blocking auto merge in this repo.

Fix gecokdriver download url

---

features/cli/oc_volume.feature
features/step_definitions/pv.rb
features/step_definitions/storage_class.rb

1. oc get deployment service-ca -n openshift-service-ca  -o jsonpath={.spec.template.spec.containers[*].volumeMounts} cmd, in the latest version, it returns:
[{"mountPath":"/var/run/secrets/signing-key","name":"signing-key"},{"mountPath":"/var/run/configmaps/signing-cabundle","name":"signing-cabundle"}]
2. oc get cmd does not support export option now.
3. add the new volume type csi.
@duanwei33 @chao007  Please help review.

Bug fix for the new changes in the latest oc version

---

lib/iaas/iaas.rb
lib/launchers/azure.rb

@duanwei33  @pruan-rht Please help review.
logs:
And I verify that the IAAS volume with id "<%= cb.volumeID %>" was deleted                        # features/step_definitions/pv.rb:187
[10:03:32] INFO> Shell Commands: oc get infrastructures.config.openshift.io cluster --output=yaml --kubeconfig=/root/workdir/Tester-OCP-qinping/ocp4_admin.kubeconfig
<--skip-->
[10:03:36] INFO> Exit Status: 0
[10:03:36] INFO> Shell Commands: oc get secrets azure-credentials --output=yaml --kubeconfig=/root/workdir/Tester-OCP-qinping/ocp4_admin.kubeconfig --namespace=kube-system
<--skip-->
[10:03:38] INFO> Exit Status: 0
waiting for …

Bug fix for azure connection and get disk by name

---

features/machine/machine_healthcheck.feature

[New requirement for 4.6 ](https://issues.redhat.com/browse/OCPCLOUD-911)
Closing this one - https://github.com/openshift/verification-tests/pull/1411 , as it might results in failing cases for 4.5 , so instead I have kept 4.5 as is and new case for 4.6 , once  backported will remove 4.5 case .
Here are the results - 
[05:21:16] INFO> Exit Status: 0
And I switch to cluster admin pseudo user                       # features/step_definitions/user.rb:13
Then I use the "openshift-machine-api" project                  # features/step_definitions/project.rb:97
[05:21:16] INFO> Shell Commands: oc project openshift-machine-api --config=/root/workdir/26351978eef8-/ocp4_admin.kubeconfig
Now using project "openshift-machine-api" on server …

mhc validation before sending data to server to create mhc resource

---

features/cli/oc_import_image.feature
features/registry/is.feature
features/registry/remote.feature

Now ruby: latest is point to 2.7 in openshift project, build cases failed, devel have no idea how to update repo, so update cases to let pass.
@openshift/devexp-qe PTAL, thanks.
command: "oc new-app ruby~https://github.com/sclorg/ruby-ex" has below error:
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source ...
---> Building your Ruby application from source ...
---> Running 'bundle install --retry 2 --deployment --without development:test' ...
/opt/rh/rh-ruby27/root/usr/share/rubygems/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.16.4) required by your /opt/app-root/src/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install …

Update ruby to 2.5 when using ruby-ex repo to build

---

features/networking/pod.feature
lib/rules/web/admin_console/4.2/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.2/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.3/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.3/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.4/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.4/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.5/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.5/monitoring_metrics.xyaml
lib/rules/web/admin_console/4.6/monitoring_alerts.xyaml
lib/rules/web/admin_console/4.6/monitoring_metrics.xyaml

Depend on PR:
https://github.com/openshift/cucushift/pull/8014
Updated 3 test cases
OCP-21124 - Show a detailed and complete view of an Alert
OCP-21132 - Show a detailed and complete view of an alerting rule
OCP-21192 - Show a detailed and complete view of Alertmanager Silence, "Firing Alerts" list is in Silence details page
Fixed failure for 3 cases
OCP-24343 - navigate to the query browser via the left side OpenShift console menu
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-28106
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-27830
v3 job:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/127867/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/128188/co …

update 3 test cases according new features and fix all UI test failures

---

features/machine/machine.feature
lib/openshift/infrastructure.rb
lib/openshift/machine.rb
testdata/cloud/ms-aws/ms_default_values.yaml
testdata/cloud/ms-azure/ms_default_values.yaml
testdata/cloud/ms-gcp/ms_default_values.yaml

[10:57:16] INFO> Shell Commands: rm -r -f -- /root/workdir/d63db26e8a09-
[10:57:16] INFO> Exit Status: 0
[10:57:16] INFO> === End After Scenario: Implement defaulting machineset values for AWS/GCP/Azure/Vsphere, Examples (#1) ===
8 steps (8 passed)
Has flakes

Default values for Different IaaS - aws/azure/gcp/ 

---

features/step_definitions/scc.rb

We need some operations to persistent in pre-upgrade, E.g, adding scc to user/service account.

Allow operations without teardown to support upgrade

---

features/upgrade/storage/upgrade.feature

In OCP 4.6, we cannot get the default storage class from co storage, before a better solution, I'd like to update it to unblock all the failure upgrade to 4.6, now it still work for default sc check.
[pass log](https://privatebin-it-iso.int.open.paas.redhat.com/?bb2482b18913c241#3G6JxYKji5H1DV/WTnyUP3sPTU5qQ6CR7HzQ2c4PR2w=)
@qinpingli @chao007 Please help review.

Fix OCP-23501

---

features/upgrade/monitoring/monitoring-upgrade.feature

Fix upgrade failure by updating metric name which is applicable to 4.4, 4.5 and 4.6
https://issues.redhat.com/browse/OCPQE-1847

fix upgrade failure for metric name change

---

lib/openshift/pod.rb

fix: add pod method "reviseVersion" which can return reviseVersion attribute to check if a pod has been redeployed.
This fix will support case OCP-33816 and OCP-33818

add pod method "reviseVersion"

---

features/cli/build.feature

failed due to
1. obtain testdata was call AFTER oc create, corrected the ordering.
2. testdata file path is inocorrect dude to file_name had the extra
`tc525736` in it.

fix OCP-11580 test failure

---

features/step_definitions/scc.rb
features/test/scc.feature

/cc @akostadinov @pruan-rht @chao007 
```
Given SCC "privileged" is added to the "csi-provisioner" service account without teardown                         # features/step_definitions/scc.rb:65
[02:47:05] INFO> Shell Commands: oc adm policy add-scc-to-user privileged system:serviceaccount:csihostpath:csi-provisioner --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig
securitycontextconstraints.security.openshift.io/privileged added to: ["system:serviceaccount:csihostpath:csi-provisioner"]
[02:47:05] INFO> Exit Status: 0
could not give csi-provisioner service account the privileged scc (RuntimeError)
/home/jenkins/workspace/Runner-v3/features/step_definitions/scc.rb:121:in `/^SCC "(.+?)" is (added to|removed from) the …
```

Fix upgrade-prepare without teardown

---

features/networking/sdn.feature
features/step_definitions/networking.rb

For 4.4 if we partially remove rules it does not
trigger an iptablesSync (BZ-1810316)
Check if the partial removal works and then
do a full table flush and chain deletion.
This requires breaking the iptable verification step into two parts,
checking the rules and then deciding if the rule check should fail
depending on version
General fixes
`"openshift-ovs-networkpolicy"` is now the default in 4.x
Remove 3.x version specific iptables rules
When using oc debug commands the `:response` seems to always include
`STDERR` appended which doesn't work for matching the `MASQUERADE` rule so use
`:stdout.to_s` instead

OCP-11286 iptables rules test updated for 4.x

---

lib/openshift/resource.rb

the output of for `oc get <resource> <resource_name>` seems to have changed from 4.4 and 4.5 ```
pruan@fedora-vm ~ $ oc get meteringconfig openshift-metering -n openshift-metering
error: the server doesn't have a resource type "meteringconfig"
pruan@fedora-vm ~ $ oc version
Client Version: 4.4.0-rc.8
Server Version: 4.5.0-0.nightly-2020-06-10-224736
Kubernetes Version: v1.18.3+91d0edd
pruan@fedora-vm ~ $ oc version
Client Version: 4.4.0-rc.8
Server Version: 4.4.8
Kubernetes Version: v1.17.1+3f6f40d
pruan@fedora-vm ~ $ oc get meteringconfig openshift-metering -n openshift-metering
Error from server (NotFound): meteringconfigs.metering.openshift.io "openshift-metering" not found
```

resource existance output has changed for 4.5

---

features/node/seccomp.feature

This fixes a frequently failed test. The test fails because we were only fetching the mcp's updating condition, but there could be a chance that the mcp has not started to update and returns 'Updating: false' to the client. With this fix we strictly verifies mcp has successfully rolled up new machineconfig before having the next verification step.
@sunilcio @weinliu @lyman9966 PTAL.
```
9m2.542s
```

Properly wait for mcp to roll out

---

features/machine/machine_healthcheck.feature
testdata/cloud/mhc/mhc_validations.yaml

It has testcases to cover - [Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1865779 ) and a related story
Working fine
results at - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/134723/console
@jhou1  @sunzhaohua2  PTAL ...

Improved cases 33714, added 34095 to have timeout validations

---

features/cli/deploy.feature

@kasturinarra  Please help review , the old yaml file has error , will cause the case run last  1 hour. 
The old job: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/08/18/02:53:00/Start_new_deployment_when_deployment_running/console.html. 
The new run time: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/137940/console

update for OCP-11769

---

features/admin/scc.feature

```
oc create -f - --kubeconfig=***/ocp4_admin.kubeconfig
STDERR:
Error from server (NotFound): error when creating "STDIN": namespaces "aos-qe-ci" not found
```
@xingxingxia @rhpmali PTAL!
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/138022/console

Fix error when creating STDIN: namespaces aos-qe-ci not found.

---

features/node/seccomp.feature

With the previous PR the pass ratio of test case OCP-32065 has increased, but occasionally it fails. I looked at all the test logs of the failure, they are all failing because mcp did not successfully roll out within 900 seconds. Now increase the wait to 1200 seconds and hopefully we can see improvements.
@sunilcio @weinliu @lyman9966 PTAL.

Increase wait time

---

features/logging/elasticsearch.feature
features/step_definitions/logging.rb
lib/openshift/cluster_logging.rb

Fix the below issue and remove collector type `rsyslog` since we never support it.
```
fluentd did not become ready within 300 seconds
RuntimeError
/home/jenkins/workspace/Runner-v3/lib/openshift/cluster_logging.rb:128:in `wait_until_fluentd_is_ready'
/home/jenkins/workspace/Runner-v3/features/step_definitions/logging.rb:160:in `/^I wait for clusterlogging(?: named "(.+)")? with "(.+?)" log collector to be functional in the(?: "(.+?)")? project$/'
features/logging/elasticsearch.feature:47:in `Given I wait for clusterlogging with "fluentd" log collector to be functional in the project'
```
Log: https://url.corp.redhat.com/3153b7e
@anpingli @pruan-rht PTAL, thanks.

fix issue: fluentd is not ready

---

testdata/infrastructure/cluster-capacity/cluster-capacity-pod.yaml

Fixing the image issue.
@jhou1 @sunilcio @lyman9966  could you help take a look?
```        [11:22:38] INFO> Exit Status: 0
[11:22:38] INFO> === End After Scenario: Cluster capacity image support: Cluster capacity can work well with a simple pod ===
16 steps (16 passed)
1m41.873s
[11:22:38] INFO> === At Exit ===
[weinliu@rhel8 verification-tests]$ 
```
log (large):https://privatebin-it-iso.int.open.paas.redhat.com/?44e2580980b5311f#SUbsACEYv3qPqLlm+Yk24EHlBWfSFR8FBN9a5BRNc0w=

fix image issue - OCP-14799

---

features/step_definitions/logging.rb

I found the `status` field in clusterlogging/instance is empty, that makes logging automation testing failed. To unblock the testing, I remove the step to check the status in clusterlogging when deploy EFK pods.
@anpingli @pruan-rht PTAL.  Thanks.

remove checking status in clusterlogging

---

features/storage/nfs.feature
lib/openshift/service.rb

@zhaozhanqi  @duanwei33 @chao007 Please help review, thx!
IPV4 test result:
```
Given admin creates a PV from "pv-retain.json" where:           # features/step_definitions/pv.rb:147
[06:03:51] INFO> Creating PV:
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: pv-84fjp
spec:
capacity:
storage: 5Gi
accessModes:
- ReadWriteMany
nfs:
path: "/"
server: 172.30.131.179
persistentVolumeReclaimPolicy: Retain
storageClassName: sc-84fjp
```
IPV6 test result(it's a fake ipv6 test, just set the raw ip manually):
```
Given admin creates a PV from "pv-retain.json" where:           # features/step_definitions/pv.rb:147
[06:49:43] INFO> Creating PV:
---
apiVersion: v1
kind: PersistentVolume
metadata:
name: pv-wy4ul
spec:
capacity:
storage: 5Gi
accessModes:
- ReadWriteMany
nfs:
path: "/"
server: …
```

Bugfix for making nfs pv is valid for ipv4 and ipv6

---

lib/rules/web/admin_console/4.6/common_ui_elements.xyaml

On 4.6 dev console, now the tour guide pop-up message box only need to click close button one time, not twice.
Caused many cases failed, Eg. http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/09/05/04:20:49/Check_route_list_and_detail_page/console.html
Updated for it and test on some cases:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/146480/console
@yapei Please review. Thanks!

fix close tour on dev console

---

features/step_definitions/networking.rb
lib/rules/cli/4.4.yaml
lib/rules/cli/4.5.yaml

a `kube-rbac-proxy` container was added to the sdn pod,
so the regular `oc logs -l app=sdn` command won't work
anymore, we need to either specify the container or
use `--all-containers=true`
```
STDERR:
error: a container name must be specified for pod sdn-w7bwn, choose one of: [sdn kube-rbac-proxy]
```

fix oc logs for SDN, add --all-containers and --prefix options

---

features/step_definitions/operators.rb

To fix the issue, _namespaces "aos-qe-ci" not found_.
The case is run on local environment. The log is pasted in [here](http://pastebin.test.redhat.com/901813).

OCP-22618 Add project

---

features/networking/egress-ingress.feature
features/step_definitions/networking.rb
testdata/networking/ovn-egressfirewall/limit_policy.json

Update some egressnetworkpolicy cases to be compatible with OVN egressfirewall
case:OCP-11639
SDN logs:https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/133929/console
OVN logs:https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/133871/console
@anuragthehatter @zhaozhanqi @weliang1 @rbbratta

Update some egressnetworkpolicy case to be compatiable with OVN 

---

testdata/cloud/autoscaler-auto-tmpl.yml
testdata/cloud/mhc/kubelet-killer-pod-43.yml
testdata/cloud/mhc/kubelet-killer-pod.yml

@jhou1 @miyadav please help to take a look, I have changed all images to sha256 format to support disconnected cluster testing, or we will get `ImagePullBackOff`.

change image to sha256 format for disconnected cluster testing

---

features/upgrade/storage/upgrade.feature

Test case OCP-29741 with cmd `oc patch scc privileged -p {} --type merged` will cause existed serviceaccount lost priviled scc.
This will impact OCP-28630.
So as a WA, adding scc back to serviceaccount csi-xxx in post-checking.
@qinpingli @duanwei33 Please help to reivew.

Add WA for OCP-28630

---

features/machine/machine.feature
lib/openshift/node.rb
testdata/cloud/pod-34718.yml
testdata/cloud/pvc-34718.yml

Auto OCP-34718: Node labels and Affinity definition in PV should match. This is for bug https://bugzilla.redhat.com/show_bug.cgi?id=1860128. @jhou1 @miyadav please help to review, thanks!
```
[07:08:21] INFO> === End After Scenario: Node labels and Affinity definition in PV should match ===
18 steps (18 passed)
1m2.072s
```

auto OCP-34718

---

features/networking/egress-ingress.feature

`1 pod becomes ready`/`2 pods become ready`
/cc @pruan-rht @akostadinov @huiran0826

Use proper step

---

features/step_definitions/networking.rb

In 4.6, there are two containers in sdn pod, the original exec command failed as not clearly identify which containers the command run. 
Specify the "sdn" container to execute the command.
Snippet of the result:
[08:39:04] INFO> Shell Commands: oc exec sdn-2v6mn  --kubeconfig=/Users/hrwang/workdir/huiran-mac-hrwang/ocp4_admin.kubeconfig -n openshift-sdn  --container=sdn -- bash -c ip\ -4\ -brief\ a\ show\ \"ens192\"\ \|\ awk\ \'\{print\ \$3\}\'
136.144.52.213/26
[08:39:06] INFO> Exit Status: 0 

Fix exec on sdn pods

---

features/cli/oc_idle.feature

Fix the output match for OCP-10941, for the output is different between 4.6 and 4.5.
logs are: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2353/console
@jhou1 @sunilcio @weinliu  Can you help to take a look? Thanks

fix OCP-10941

---

features/storage/nfs.feature
features/storage/persistent_volume.feature

Even some of the steps in the middle failed, e.g, pod failed to be ready for any reason, there will be clean-up for the PVC to unblock the clean-up of PV.
As a follow up of https://github.com/openshift/verification-tests/pull/1547
/cc @akostadinov @qinpingli @chao007 @duanwei33

Ensure pvc clean-up, regardless of test step failures

---

features/networking/sctp.feature
features/step_definitions/networking.rb

When using oc debug node to grep sctp, automation will fail intermittently on step of "lsmod | grep sctp". 
Update scripts to use "host.exec_admin" to grep sctp module in each nodes. 
Test log: http://file.rdu.redhat.com/~weliang/sctp_testlog.txt

Update SCTP cases

---

lib/openshift/network_attachment_definition.rb

Fix https://github.com/openshift/verification-tests/pull/1380#discussion_r494296702
```
$ oc api-resources | grep -E 'NAME|attachment'
NAME                                  SHORTNAMES       APIGROUP                              NAMESPACED   KIND
network-attachment-definitions        net-attach-def   k8s.cni.cncf.io                       true         NetworkAttachmentDefinition
```

Fix resource type of NetworkAttachmentDefinition

---

features/upgrade/workloads/scheduler-upgrade.feature

@kasturinarra  The case will failed with ocp4.4. need to specify the container for `oc logs` .  And the output for ocp4.4 is also different from ocp4.6 . So short the output check.

add specify for container

---

testdata/storage/secret/secret.yaml

The previous secret yaml file has bad indentation, which makes the secret has no real data.

Fix the manifest issue

---

lib/rules/web/admin_console/4.4/dashboards.xyaml
lib/rules/web/admin_console/4.5/dashboards.xyaml
lib/rules/web/admin_console/4.6/dashboards.xyaml
lib/rules/web/admin_console/4.6/logs.xyaml
lib/rules/web/admin_console/4.6/node.xyaml
lib/rules/web/admin_console/4.6/user_management.xyaml

fixed
OCP-24281 RBAC check to normal operations for users with view access - rule update
OCP-20688 Check log streaming - rule update
OCP-28297 Cluster Inventory block has a full list of required items - remove `s` to reduce instability caused by single and plural nouns 
OCP-19722 Check nodes list columns and terminal tab - feature changed and there is no need to choose namespace, rule updated

rules update

---

features/networking/ovn.feature

It seems that `ovn-nbctl list logical_switch_port`
outputs too much info so if we don't grep
server-side the step now always fails
Without the `grep` `oc exec` fails witn the error:
```
E1008 07:03:23.823290  655435 v2.go:105] write tcp 172.16.16.22:41846->15.222.201.132:6443: write: connection reset by peer
```
Also change the wait for all pods in the "openshift-ovn-kubernetes" project
timeout to 60 seconds, because it is taking longer, maybe due to the
new OVN database checking

OVN: grep for port in list logical_switch_port

---

features/logging/cluster_log_forwarder.feature
lib/openshift/cluster_log_forwarder.rb
testdata/logging/clusterlogforwarder/multiple_receiver/clusterlogforwarder.yaml
testdata/logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml

Per https://bugzilla.redhat.com/show_bug.cgi?id=1884275, update clusterlogforwarder to namespaced resource.

update clusterlogforwarder to namespaced resource

---

features/machine/machine.feature
lib/openshift/machine.rb
testdata/cloud/ms-vsphere/ms_default_values.yaml

Validation is passed .
.
[13:11:31] INFO> Exit Status: 1
[13:11:31] INFO> Shell Commands: rm -r -f -- /home/jenkins/workspace/Runner-v3/workdir
[13:11:31] INFO> Exit Status: 0
[13:11:31] INFO> === End After Scenario: Implement defaulting machineset values for vsphere ===
17 steps (17 passed)
0m26.773s
Randomized with seed 21881
[13:11:32] INFO> === At Exit ===
Archiving artifacts
Finished: SUCCESS
Job URL - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/174961/console
This is related to - https://issues.redhat.com/browse/OCPCLOUD-883

Defaulting machinset values in vsphere cluster

---

features/networking/service.feature

due to the firewall restricted for different platform. update this scenario with localhost with specified nodeport
```
Removing debug pod ...
error: non-zero exit code from debug container
[03:13:50] INFO> Exit Status: 1
[03:13:50] INFO> Shell Commands: oc delete projects tests-dhcp-140-240-zzhao --wait=false --kubeconfig=/home/zzhao/workdir/dhcp-140-240-zzhao/ocp4_admin.kubeconfig
project.project.openshift.io "tests-dhcp-140-240-zzhao" deleted
[03:13:52] INFO> Exit Status: 0
[03:13:52] INFO> Shell Commands: rm -r -f -- /home/zzhao/workdir/dhcp-140-240-zzhao
[03:13:52] INFO> Exit Status: 0
[03:13:52] INFO> === End After Scenario: User can expand the nodePort range by patch the serviceNodePortRange in network ===
13 steps (13 passed)
1m46.773s
```
@liangxia @pruan-rht

update nodeport cases with localhost access

---

features/machine/upi_gcp.feature
features/step_definitions/machine.rb

Because upi gcp supports creating compute machines while installation, so upi gcp manual cases could be automated.@jhou1 @miyadav  Please help to review, if you think this is ok I will modify all upi gcp templates and add disable_worker_machineset: "no" to support our automation.

add upi gcp automation test

---

config/config.yaml
doc/configuration.adoc
features/step_definitions/web.rb
lib/webauto/web4cucumber.rb
lib/webauto/webconsole_executor.rb

Motivation: I want to run tests in development with browser in one container but cucumber running outside it / in another container.
Not 100% sure how I'll end using this, but gives flexibility.  Any objections?
```
$ podman run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug
$ export BUSHSLICER_CONFIG='{"global": {"browser": "chrome", "selenium_url": "http://localhost:4444/wd/hub"}}'
```
- Didn't check with separate selenium hub.
- Don't know if openshift's test work in this config as I'm not actually running them :smile: 
I'm from dev team of cloud.redhat.com/openshift site, and what I actually care about are the "ocm" tests in https://github.com/xueli181114/verification-tests & https://github.com/xueli181114/cucushift forks.
- I'm new to WebDriver / …

Add option for remote selenium URL

---

features/upgrade/workloads/scheduler-upgrade.feature

Fixing the code as i see that kube-scheduler container is not present in ocp4.3, so changing the upgrade-prepare code runs fine on OCP4.3, 4.4, 4.5 & 4.6

Fix test as it fails with ocp4.3

---

features/networking/multus.feature
features/step_definitions/networking.rb

We keep getting automation failures because of existing VLANs
before the test.
Dump the VLAN information before we run the test.
To do this we have to pick a node first, then put the pod
on that node.
Failures:
```
/sbin/bridge\ vlan\ show
port	vlan ids
cni0	 1 PVID Egress Untagged
bridge3	 1 PVID Egress Untagged
veth9056d1f1	 1 PVID Egress Untagged
```

OCP-24488: debug VLAN errors by dumping info before

---

testdata/routing/operator/ingressctl-nsowner.yaml

`HostNetwork` might causes port conflict (rarely but possibly) when running parallel CI jobs on some platforms, so replace it with `NodePortService`, and `nodePlacement` part is not required any more.
@quarterpin please help review.

update test ingresscontroller to use NodePort instead of HostNetwork

---

features/networking/service.feature
testdata/networking/nodeport_test_pod.yaml
testdata/networking/nodeport_test_service.yaml

update this with separate file for pod and service since the pod and service cannot create successfully at same time since before it always return with `exit 1`
```
horization"=>"Bearer <oauth_token>"}}, opts: {:token_to_delete=>"sha256~8nmjf_vi8x2PYJgBdWbFKqGxDdOYl9atxgU7-aar2pY"}
[10:41:53] INFO> HTTP DELETE https://api.wsunawsnlb.qe.devcluster.openshift.com:6443/apis/oauth.openshift.io/v1/oauthaccesstokens/sha256~8nmjf_vi8x2PYJgBdWbFKqGxDdOYl9atxgU7-aar2pY
[10:41:54] INFO> HTTP DELETE took 0.992 sec: 200 OK | application/json 242 bytes
[10:41:56] INFO> Shell Commands: oc debug  --kubeconfig=/home/zzhao/workdir/dhcp-140-240-zzhao/ocp4_admin.kubeconfig -n tests-dhcp-140-240-zzhao --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8f4882cff3c2f9521215eac681c5abda42876e3e955431c1 …
```

update the nodeport pod and service with separate file

---

features/networking/sdn.feature

bash c to enable treating string with pmtrs as a whole single command
This will fix glitches in OCP-25787
@pruan-rht (same as #1615 which was closed to to squashing issue)

OCP-25787 quick fix

---

features/machine/machine_misc.feature
features/step_definitions/deployment.rb

Related bug - https://bugzilla.redhat.com/show_bug.cgi?id=1870158
Below step is failing : 
_When as admin I successfully merge patch resource "mutatingwebhookconfiguration.admissionregistration.k8s.io/machine-api" with:           # features/step_definitions/cli.rb:210
[09:37:21] INFO> Shell Commands: oc patch mutatingwebhookconfiguration.admissionregistration.k8s.io machine-api -p \{\"webhooks\[0\]\":\[\{\"clientConfig\":\{\"service\":\{\"port\":444\}\}\}\]\} --type=merge --config=/root/workdir/febf767459e0-/ocp4_admin.kubeconfig
mutatingwebhookconfiguration.admissionregistration.k8s.io/machine-api patched (no change)
[09:37:24] INFO> Exit Status: 0
| {"webhooks[0]":[{"clientConfig":{"service":{"port":444}}}]} |
patch failed to apply at []! deployment.apps/machine-api-operator scaled_ …

Reconciliation of MutatingWebhookConfiguration values should happen

---

lib/login.rb

As described in https://bugzilla.redhat.com/show_bug.cgi?id=1890724, there are API server flappings, which can cause automation test execution job quit.
The server can recover itself after some time, we should continue the test as well, so add retry for oauth_bearer_token_challenge, or else we will fail with "Error getting bearer token"
/cc @akostadinov @pruan-rht @jhou1 @kasturinarra

Add retry for oauth_bearer_token_challenge

---

testdata/networking/multicast-rc.json

Update multicast pod to use quay.io/openshifttest/mcast-pod instead of lihongan/mcast-pod
Test log: https://privatebin-it-iso.int.open.paas.redhat.com/?348b8a406f722a56#7CoUxpdCgDSqH3cS9dJW6HBssRcyHxQzM2H2jPK8znPr

Update multicast pod to use quay.io/openshifttest/mcast-pod

---

features/networking/sctp.feature
features/step_definitions/networking.rb

Update sctp script to:
1. Only check sctp module in worker nodes, no need check sctp modules in all the nodes.
2. Add step wait up to 60 seconds for sctpserver pod too avoid randomly see below failure
When I run the :exec background client command with:                              # features/step_definitions/cli.rb:13
[17:56:14] INFO> Shell Commands: oc exec sctpserver  --kubeconfig=/home/weliang/workdir/weliang-weliang/ocp4_testuser-0.kubeconfig --namespace=y2fh9  -- sh -c /usr/bin/nc\ -l\ 30102\ --sctp\ -k\ -m\ 5\ -w\ 60
STDERR:
sh: /usr/bin/nc: No such file or directory
command terminated with exit code 127
Test logs: http://file.rdu.redhat.com/~weliang/sctp.log

Only check sctp module in worker nodes

---

features/networking/egress-ip.feature

As vSphere migrated to vmc, updated ifconfig.me/ifconfig.io to ipecho_url which is installed in a vm in  vmc.
Logs: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/198304/console

Update egressip curl url to ipecho url

---

features/networking/service.feature

`service.url` has been fixed to IPv6 bracket encode
addresses, e.g.`[fd::1]:1234` etc.
We don't want to use `service.ip` because it doesn't
work for IPv6 URLs that need brackets

OCP-26035: use service.url to generate URL

---

lib/openshift/cluster_service_version.rb

indentation was wrong
```
def ready?(user: nil, quiet: false, cached: false)
res = get(user: user, quiet: quiet)
res[:success] = res[:parsed]["status"]["phase"] == "Succeeded" && res[:parsed]["status"]["reason"] == "InstallSucceeded" if res[:success]
return res
end
```

fix cirucular refrence in arg and indentation issue

---

testdata/networking/multus-cni/Pods/generic_multus_pod_net_raw.yaml
testdata/networking/multus-cni/Pods/multus-default-route-pod.yaml
testdata/networking/sctp/sctpclient.yaml
testdata/networking/sctp/sctpserver.yaml

Pods run the entrypoint as PID 1, whatever process is run as PID 1 won't receive SIGTERM and won't shutdown quickly (< 1min)
We need to trap SIGTERM and exit immediately
See:
https://github.com/openshift/cluster-network-operator/pull/859/files#diff-6f3fb59cc9404c296e2f7aa6b442137bdb2d4559ced7bfc51b7a188c2b64233fR65
https://github.com/openshift/cluster-dns-operator/issues/65
We should:
> Listen for SIGTERM explicitly
> Always `sleep X & wait` instead of just `sleep X`
https://vagga.readthedocs.io/en/latest/pid1mode.html
https://hynek.me/articles/docker-signals/
The current `["/bin/bash", "-c", "sleep 2000000000000"]` is causing us to sleep ~42 seconds each time we delete the pod.
So we need to trap SIGTERM and then exit
```shell
command: ["/bin/bash", "-c", "trap 'kill $(jobs -p); exit 0' …
```

handle SIGTERM to not delay pod deletion

---

lib/polarshift/test_case.rb

match test case based on absolute path
Certain test-runners (Rubymine) force the use of the abspath of the
`.feature` files on the cucumber command line.  If the `scenario.file`
is an abspath then testing strict string equaliy will fail.
Instead compare the absolute path with the `automation_file`
relative to `BushSlicer::HOME`
Example:
```
scenario.file = /home/rbrattai/workspace/verification-tests/features/tierN/networking/network-policy.feature
automation_file = features/tierN/networking/network-policy.feature
```

match test case based on absolute path

---

tools/jenkins/slaves/Dockerfile.rhel7

Failed to build ocxx image due to the repo unavailable
```
--> RUN curl https://***/jenkins-jcasc-n/-/raw/master/agents/dockerfiles/cucushift-oc42/aos-devel-4_2.repo -o /etc/yum.repos.d/puddle.repo &&     yum -y install atomic-enterprise-service-catalog-svcat openshift-clients &&     yum clean all -y &&     rm -rf /var/cache/yum /tmp/*
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   156  100   156    0     0    587      0 --:--:-- --:--:-- --:--:--   590
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 503 - Service Unavailable
Trying other mirror. …
```

Skip google-chrome repo if unavailable

---

lib/webauto/web4cucumber.rb

Chrome should accept insecure certs by default to avoid error

accept insecure certs automatically for chrome

---

features/networking/sctp.feature

Existing script failed on:
Shell Commands: oc exec sctpclient  --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_testuser-40.kubeconfig --namespace=j8x39  -- sh -c echo\ test-openshift\ \|\ /usr/bin/nc\ -v\ 10.131.2.8\ 30102\ --sctp
STDERR:
sh: /usr/bin/nc: No such file or directory
command terminated with exit code 127
Seems like script try to use nc just after pod is ready and get failed, add the steps of "which nc" after pod ready, then start to us nc for sctp testing
Here is the new testing log:
And I wait up to 20 seconds for the steps to pass:                    # features/step_definitions/meta_steps.rb:33
[20:29:44] INFO> Shell Commands: oc exec sctpclient  --kubeconfig=/home/weliang/workdir/weliang-weliang/ocp4_testuser-0.kubeconfig -n z5fs1  -i -- bash -c which\ nc …

sctp fix no nc file

---

features/cli/deploy.feature

Sometimes script proceeds when the latestVersion is 0 due to which the test script is failing with run time error, so fixing the issue. One example is as below
http://virt-openshift-05.lab.eng.nay.redhat.com/buildcorp/Runner-v3/198456/console

Fix OCP-11695

---

lib/rules/web/ocm_console/cluster_detail.xyaml
lib/rules/web/ocm_console/cluster_detail_support_tab.xyaml
lib/rules/web/ocm_console/cluster_list_page.xyaml
lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
lib/rules/web/ocm_console/install_page.xyaml

Update OCP-28797 cluster log, OCP-26380 pre-release page, OCP-25175 crc page, OCP-21339 cluster list, OCP-21090 action list of detail page, OCP-29659 byoc creation page, OCP-27839 rhv ipi, OCP-24070 baremetal upi.
Add OCP-36001 rhv upi, OCP-36034 baremetal ipi, OCP-28135 permission of subscription settings, OCP-33436 transfer ui, OCP-36294 permission of support tab, OCP-35651 support tab ui.
Here is Jenkins log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/208015/console.
Please help review cases, thanks. @yasun1 @xueli181114 @yuwang-RH

Fix and add multi OCM ui cases

---

features/registry/registry.feature

Fix the issue,
```
$ tools/polarshift.rb update-automation OCP-29696 OCP-29706
8: from tools/polarshift.rb:488:in `<main>'
7: from tools/polarshift.rb:262:in `run'
6: from /home/lxia/.rvm/gems/ruby-2.7.0/gems/commander-4.5.2/lib/commander/delegates.rb:15:in `run!'
5: from /home/lxia/.rvm/gems/ruby-2.7.0/gems/commander-4.5.2/lib/commander/runner.rb:68:in `run!'
4: from /home/lxia/.rvm/gems/ruby-2.7.0/gems/commander-4.5.2/lib/commander/runner.rb:452:in `run_active_command'
3: from /home/lxia/.rvm/gems/ruby-2.7.0/gems/commander-4.5.2/lib/commander/command.rb:155:in `run'
2: from /home/lxia/.rvm/gems/ruby-2.7.0/gems/commander-4.5.2/lib/commander/command.rb:184:in `call'
1: from tools/polarshift.rb:64:in `block (2 levels) in run' …
```

Remove trailing whitespace

---

features/admin/pod.feature
features/storage/nfs.feature

Those test cases have been removed in Polarion, clean-up related script so it will not interrupt batch synchronizing tags between code and Polarion using polarshift.rb
/cc @jhou1 @chengzhang1016 @chao007

Clean-up script which test case is removed in Polarion

---

features/cli/oc_import_image.feature
features/registry/is.feature

OCP-12765 fails a lot in CI, so a new fix is made:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/runner-v3/209832/console
Fix OCP-19196:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/runner-v3/209837/console

Fix error for OCP-12765

---

features/admin/scc.feature

I see that the file name used to run oc create -f is incorrect, so adding the right file name.

Fix case OCP-11762

---

features/step_definitions/networking.rb

As per analysis done here
https://issues.redhat.com/browse/OCPQE-2793?focusedCommentId=15506276&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15506276
It was observed that deletion of bridge interfaces via ```oc debug node``` takes some time as cucushift create projects to execute commands like ```oc debug``` under project name like ```tests-psiv45-cucushift-oc44-standard-slave-zcgh9-0``` and if the project stuck in deletion state causes upcoming test to exit as premature as upcoming test also try to create project with same naming convention (as observed in http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/11/24/10:45:46/Pods_cannot_communicate_each_other_with_different_vlan_tag/console.html) This is not getting repro'ed on local env …

Modifying bridge deletion procedure via network pods

---

features/step_definitions/metering.rb

https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/213077/console

for older OCP version, the label doesn't have  take it out

---

testdata/pods/pod_with_special_fsGroup.json

Fixes:
```
cucumber -p polarshift features/cli/create.feature:6 # Scenario: Process with special FSGroup id can be ran when using RunAsAny as the RunAsGroupStrategy 
```
When run in disconnected setup, this image `openshift/hello-openshift` can not be pulled see [log](https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/212762/consoleFull). Now update the image reference so that in disconnected it works as well. Image picked from https://gitlab.cee.redhat.com/aosqe/flexy-templates/-/blob/master/functionality-testing/aos-4_6/hosts/image-list-digest.txt
@zhouying7780 @kasturinarra PTAL.

Using digest for disconnected

---

features/machine/machine.feature
testdata/cloud/ms-azure/ms_disconnected_env.yaml

Related to -- https://bugzilla.redhat.com/show_bug.cgi?id=1889620
we can wait for bug to be verified status(with new nightly) before merging , already verified with Danil though ..
Output 
:"mapi","value":"mapi_test"}],"providerSpec":{"value":{"publicIP":true,"location":null,"osDisk":{"diskSizeGB":128}}}}}}}
[12:42:38] INFO> Shell Commands: http_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@23.99.177.119:3128
https_proxy=http://proxy-user1:JYgU8qRZV4DY4PXJbxJK@23.99.177.119:3128
oc create -f - --config=/root/workdir/9fb4c01f2a99-/ocp4_admin.kubeconfig
STDERR:
Error from server (providerSpec.publicIP: Forbidden: publicIP is not allowed in Azure disconnected installation): error when creating "STDIN": admission webhook "validation.machineset.machine.openshift.io" denied the request: …

 Negative test for Azure Disconnected cluster to not allow publicIp

---

features/networking/ovn_winc.feature

Setting run-level is not needed not in 4.7. Small change
@zhaozhanqi @huiran0826 @rbbratta @weliang1

removing unwanted runlevel block

---

features/networking/operator.feature

this cases failed due to normal user cannot get machines in `clean up` steps
```
^[[36mError from server (Forbidden): machines.machine.openshift.io "qeci-11104-qkwcq-worker-us-east-2c-mclf6" is forbidden: User "testuser-40" cannot get resource "machines" in API group "machine.openshift.io" in the namespace "aos-qe-ci"^[[0m
```
Add one step to make use 'admin' user
logs: http://pastebin.test.redhat.com/921515
@anuragthehatter @huiran0826 @rbbratta @weliang1 ^^
@liangxia @pruan-rht  No big changes

update case OCP-22202 to use admin user

---

features/test/sctp.feature

In e2e CI testing, sctp failed on:
cat: /sys/module/sctp/initstate: No such file or directory
This PR will not fix any failed issue, it is only to add several debug steps to troubleshoot why
the scripts intermittently failed in QE e2e CI testing.
@pruan-rht @liangxia
Please help to merge, the debug information will be useful for a real fixing PR.

Debug sctp failed cases

---

testdata/authorization/scc/ocp11207/pod2.json

We map test case ID 511602 in TCMS (obsoleted test case manage system), to ID 11207 in Polarion (Currently in use test case manage system), via https://github.com/openshift/cucushift/pull/8255/files#diff-439c289cb76ddf7ad0f35ed591aaa8a100e9d819aa8f118c29329a721b4fd000L460
Then we update the test data path in verification-tests to reflect the change, via https://github.com/openshift/verification-tests/pull/1687/files#diff-26928b8ac649356f4cdb0045068eb79ce9c37cafdd2c66860b363fce5e33879a
And we found the test data also exist in cucushift, so we remove that via https://github.com/openshift/cucushift/pull/8255/files#diff-1a2c1833135545e38afdfd5bca283a70b21b0cd5aee7e7eb318c473d145c7166
Unfortunately, only test data `pod1.json` was check (it's the same in verification-tests and in cucushift), …

Fix OCP-11207

---

testdata/downwardapi/ocp10707/pod-downwardapi-env.yaml
testdata/pods/allinone-volume/allinone-normal-pod.yaml
testdata/pods/initContainers/init-containers-deadline.yaml
testdata/pods/initContainers/init-containers-fail.yaml
testdata/pods/initContainers/init-containers-privilege.yaml
testdata/pods/initContainers/init-containers-quota-1.yaml
testdata/pods/initContainers/init-containers-quota-2.yaml
testdata/pods/initContainers/init-containers-readiness.yaml
testdata/pods/initContainers/init-containers-sleep.yaml
testdata/pods/initContainers/init-containers-success.yaml
testdata/pods/initContainers/volume-init-containers.yaml
testdata/pods/securityContext/both-level.yaml
testdata/pods/securityContext/container-selinux.yaml
testdata/pods/securityContext/pod-selinux.yaml
testdata/pods/tolerations/defaultTolerationSeconds-override.yaml
testdata/secrets/mapping-secret-volume-pod.yaml
testdata/secrets/pod-secret-datastring-image-volume.yaml
testdata/secrets/secret-pod-1.yaml

/cc @jhou1 @xiuwang @pruan-rht 
Action item from automation bi-weekly meeting on Dec 2nd.
Why we switch from docker to quay ?
1. There are rate limit added recently on docker, which will result pulling image to fail as we reach the threshold.
2. We have mirror the image from quay to internal registry for disconnect testing.

Replace image from docker to quay

---

features/networking/ovn.feature

We where checking iperf
`['end']['sum']['jitter_ms'].to_f < 1`
Increase it to 5 ms.
`['end']['sum']['jitter_ms'].to_f < 5`
Anytning less than 20ms is supposed to be good
for VOIP calls, but we want to be better.
It seems the minimum resolution is 1ms as well.

OCP-26139: increase jitter check

---

testdata/routing/abrouting/abtest-websrv1.yaml
testdata/routing/abrouting/abtest-websrv2.yaml
testdata/routing/abrouting/abtest-websrv3.yaml
testdata/routing/abrouting/abtest-websrv4.yaml
testdata/routing/web-server-1.yaml
testdata/routing/web-server-rc.yaml

enable nginx server to listen on both IPv4 and IPv6 address.
```
~ $ netstat -anlp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 :::8080                 :::*                    LISTEN      1/nginx: master pro
tcp        0      0 :::8443                 :::*                    LISTEN      1/nginx: master pro
```
@quarterpin please take a look. thanks

update nginx-alpine image to support IPv6

---

features/networking/multus.feature

Due to 1875324, the test flakes with an error:
```
Scenario: The multus admission controller should be able to detect the syntax issue in the net-attach-def ==>@  features/networking/multus.feature:560
Error from server (NotFound): error when creating "STDIN": namespaces "aos-qe-ci" not found
```
This PR workarounds that and ensures the test no longer fails hereafter: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/218605/console
@zhaozhanqi @anuragthehatter PTAL.

Fix a test flake due to 1875324

---

features/networking/ovn_winc.feature

We Should have a quick LB svc check for window container as well like we do for linux 
Logs: https://privatebin-it-iso.int.open.paas.redhat.com/?4513f4efce5d3048#9nJ1G2onaUnGxqU3RjjMMGrkbtHwNy6CgKGKd4c6jocZ
@rbbratta @zhaozhanqi @huiran0826 @weliang1 @brahaney @asood-rh

Window container case for Loadbalancer svc

---

lib/polarshift/request.rb
lib/polarshift/test_record.rb

Reverts openshift/verification-tests#1701 due to:
```
timeout ("360" seconds) updating run "20201215-0157" in project "OSE":
{"error":"no test case results updated","description":"Most probably due to concurrent modification these cases' state is not what you expected: [\"OCP-10181\"]"} (RuntimeError)
/home/jenkins/ws/workspace/Runner-v3/lib/polarshift/request.rb:320:in `update_caseruns_smart'
/home/jenkins/ws/workspace/Runner-v3/lib/polarshift/test_record.rb:122:in `update_to!'
/home/jenkins/ws/workspace/Runner-v3/lib/polarshift/test_record.rb:94:in `reserve!'
/home/jenkins/ws/workspace/Runner-v3/lib/polarshift/test_suite.rb:76:in `block in test_case_next!'
/home/jenkins/ws/workspace/Runner-v3/lib/polarshift/test_suite.rb:76:in `each' …
```

Revert "Add update_caseruns_smart"

---

features/upgrade/workloads/oc-upgrade.feature

Old image hit docker pull limitation issue, so changing the image name to point to quay.io

Fix image issue

---

features/step_definitions/registry.rb

On openstack, intergrated registry is default setting to Removed.
We add post action to change registry to Managed, but not ipv6 and ipv4 in edge team. Since set registry here in case registry are setting to Removed scenarios.

fix OCP-21482 and OCP-18998

---

features/networking/egress-ip.feature
features/networking/ovn-egress-ip.feature
features/step_definitions/networking.rb

ocp-33704 sometimes failed as the hello-pod may located on same node as reboot node which will cause the pod killed after reboot, fix it by explicitly specifying  the node for the pod .
ocp-34938 failed as it get the event from project aos-qe-ci namespace which is incorrect,  fix it by explicitly using the default project to get event.
Logs:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2622/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2621/console

fix ocp-33704 ocp-34938

---

features/networking/service.feature

Intermittent externalIP automation failed due to waiting time is not enough:
http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/12/18/04:29:14/externalIP_defined_in_service_with_set_ExternalIP_in_allowedCIDRs/console.html
STDERR: Error from server (Forbidden): error when creating "STDIN": services "service-unsecure" is forbidden: spec.externalIPs: Forbidden: externalIPs have been disabled
Update script from waiting 300s to 500s when update externalIP policy

Wait for more time when update externalIP policy

---

features/machine/machine_misc.feature

Here are validation results - https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/227715/console
This is to cover  -https://bugzilla.redhat.com/show_bug.cgi?id=1907380
@sunzhaohua2  @jhou1  PTAL

 logs verbosity validation for kube-rbac containers

---

features/machine/machine.feature

Auto OCP-37706: baremetal clusteroperator should be disabled in any deploy that is not baremetal @jhou1 @miyadav please help to take a look.
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/226815/console

auto OCP-37706

---

features/logging/cluster_log_forwarder.feature
features/step_definitions/logging.rb
testdata/logging/clusterlogforwarder/elasticsearch/insecure/clusterlogforwarder.yaml
testdata/logging/clusterlogforwarder/elasticsearch/secure/clusterlogforwarder.yaml
testdata/logging/clusterlogforwarder/fluentd/insecure/clusterlogforwarder.yaml
testdata/logging/clusterlogforwarder/fluentd/secure/clusterlogforwarder.yaml
testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC3164.yaml
testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_RFC5424.yaml
testdata/logging/clusterlogforwarder/rsyslog/rsys_clf_default.yaml

Fixes:
1. check CSV status when subscribing operators
2. deploy external log stores in different projects

deploy external log stores in different projects and other fixes

---

features/logging/kibana.feature
lib/rules/web/admin_console/4.7/logging_kibana.xyaml

Fix failure:
```
[05:35:09] INFO> found 0 element elements with selector: {:xpath=>"//h2[@class=\"index-pattern-label\" and @id=\"index_pattern_id\" and contains(., \"app*\")] | //span[contains(., \"app*\")]"}
[05:35:09] INFO> embedding "2021-01-05T05:35:09+00:00-screenshot.png"
[05:35:09] INFO> embedding "2021-01-05T05:35:09+00:00.html"
| index_pattern_name | app* |/home/jenkins/ws/workspace/Runner-v3/features/support/cucu_formatter.rb:258: warning: URI.escape is obsolete
Then the step should succeed                                                               # features/step_definitions/common.rb:4
the step failed (RuntimeError)
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/common.rb:6:in `/^the step should( not)? (succeed|fail)$/'
features/logging/kibana.feature:89:in …
```

fix failure when finding the index patterns in kibana

---

features/networking/service.feature

Fix OCP-11645, the case failed due to the the image listening port changed, updated it accordingly.
Log: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/238388/console

fix ocp-11645

---

features/machine/machine.feature

Validated :
```
[10:09:55] INFO> Exit Status: 0
"""
When I run the :logs admin command with:
| resource_name | <%= pod.name %> |
| c             | #{cb.id}        |
Then the output should contain:
| attempting to acquire leader lease openshift-machine-api/cluster-api-provider|
"""
[10:09:55] INFO> === After Scenario: Run machine api Controllers using leader election ===
[10:09:55] INFO> Shell Commands: rm -r -f -- /root/workdir/ab65b6d5c5b5-
[10:09:55] INFO> Exit Status: 0
[10:09:55] INFO> === End After Scenario: Run machine api Controllers using leader election ===
6 steps (6 passed)
0m26.875s
[10:09:55] INFO> === At Exit ===
```
It failed in the CI run for 4.7 today ..

Space issue fixed by dev a extra space was there earlier

---

features/networking/service.feature
testdata/networking/externalip_pod.yaml
testdata/networking/externalip_service1.json

In current service externalIP scripts, pod use testdata/routing/web-server-1.yaml
Other team's PR https://github.com/openshift/verification-tests/pull/1770  caused all service externalIP script cases failed.
The web-server-1.yaml is not must for our service externaip pod, the fix is to create our own pod file saved in testdata/networking dir and not use other team file any more.
Test logs:
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2780/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2782/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2785/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2786/console …

Use new YAML file for externalip_pod

---

features/step_definitions/logging.rb

Fix failure:
```
[01:38:29] INFO> Exit Status: 0
what ClusterServiceVersion are you talking about? (RuntimeError)
/home/jenkins/ws/workspace/Runner-v3/lib/world.rb:313:in `project_resource'
/home/jenkins/ws/workspace/Runner-v3/lib/world.rb:141:in `cluster_service_version'
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/logging.rb:87:in `block (2 levels) in <top (required)>'
/home/jenkins/ws/workspace/Runner-v3/lib/base_helper.rb:153:in `wait_for'
/home/jenkins/ws/workspace/Runner-v3/features/step_definitions/logging.rb:85:in `/^logging operators are installed successfully$/'
/opt/rh/rh-ruby27/root/usr/share/ruby/forwardable.rb:235:in `invoke_dynamic_step'
/home/jenkins/ws/workspace/Runner-v3/features/support/clusterlogging_env.rb:3:in `Before'
```

fix failure when deploy operators

---

features/machine/machine_misc.feature

This is to automate OCP- 37180 , below is validation :
.
```
.
[03:45:04] INFO> Exit Status: 0
[03:45:04] INFO> HTTP GET https://prometheus-k8s-openshift-monitoring.apps.jima011401.qe.devcluster.openshift.com/api/v1/query?query=cloudprovider_vsphere_vcenter_versions
[03:45:05] INFO> HTTP GET took 1.293 sec: 200 OK | application/json 501 bytes
| path  | /api/v1/query?                         |
| query | cloudprovider_vsphere_vcenter_versions |
Then the step should succeed                                                                             # features/step_definitions/common.rb:4
And the expression should be true> @result[:parsed]["data"]["result"][0]["metric"]["version"] == "7.0.0" # features/step_definitions/common.rb:133
waiting for …
```

get vCenter version to telemetry

---

features/step_definitions/helper_services.rb

In today auto run 20210116-2057 (connected env), cases failed like https://url.corp.redhat.com/Sync-ldap-group-to-openshift-group-with-paging-from-ldap-server and so on ...
The cause should be docker.io limits pull. Thus fix with quay.io. Pass log: Runner-v3/254308/console
@rhpmali @barleyer please review, thx

Fix ImagePullBackOff for "I have LDAP service in my project" cases

---

features/upgrade/workloads/scheduler-upgrade.feature

Removing the code which was added for 4.3 as wanted to make sure that case works fine for upgrades from 4.4 to higher. For 4.3 upgrades will deal separately or keep it manual.

Fix upgrade failures

---

features/machine/machine.feature

Update windows template on vsphere, confirmed with sgao, we will use template `openshift-qe-template-windows-2019` and try to keep the name unchanged in the future. @jhou1 @miyadav please help to take a look.

update windows machine template

---

lib/launchers/amz.rb

The precedence (try envvars if fails then consult configuration) is aligned to common handling used in Dynect or OSP.

Provide AWS credentials as envvar

---

lib/rules/web/admin_console/4.5/catalog.xyaml
lib/rules/web/admin_console/4.6/catalog.xyaml
lib/rules/web/admin_console/4.7/catalog.xyaml

Some operators, NFD, for example, don't have the `monitor` checkbox in the Subscribe/Install page in the OperatorHub page
4.6 https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/269817/console
4.7 https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3-smoke/2850/console

update rule to make checkbox for monitoring optional 

---

tools/jenkins/slaves/Dockerfile.rhel7

Another repo `rhel-7-for-power-le-rpms` enabled unexpectedly in redhat.repo. So disable all repos by default to prevent such issue from happen again.

Disable all repos by default

---

testdata/pods/ocp10031/pod.json

Updating the image for the testcase as the previous image was missing/invalid causing `ImagePullBackOff`
Test could be: `bundle exec cucumber features/networking/pod.feature:24`

Change the pod image to a valid image

---

features/upgrade/routing/upgrade.feature
testdata/routing/operator/ingressctl-ns-shards.yaml

Ensure the "shards" ingresscontroller always use the same LB scope to the default ingresscontroller, so the case can be executed on private cluster as well.
log
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/276980/console
@quarterpin Please help take a look. Thanks
cc @jechen0648

enhancce OCP-38812 to support private cluster

---

features/support/cucu_formatter.rb

`/home/jenkins/ws/workspace/Runner-v3/features/support/cucu_formatter.rb:258: warning: URI.escape is obsolete
`https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/279366/console
https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/279368/console

URI.escape is deprecated, replace with encode_www_form_component instead

---

lib/rules/web/ocm_console/archived_cluster_detail.xyaml
lib/rules/web/ocm_console/cluster_list_page.xyaml
lib/rules/web/ocm_console/install_page.xyaml

1.Update breadcrumbs because of the new changes about creation page, this update related with all of the install page cases: OCP-24068,OCP-24069,OCP-24070,OCP-24071,OCP-24072,OCP-25174,OCP-25176,OCP-26297,OCP-26380,OCP-27839,OCP-28794,OCP-28795,OCP-28796,OCP-30121,OCP-36001,OCP-36034
2.Update archive button and title because of the new changes about archive page, this update related with: OCP-28142,OCP-21339. 
3.Update the link of bare metal RHCOS in OCP-24070, this change comes from new story.
Here is the Jenkins result: https://mastern-jenkins-csb-openshift-qe.cloud.paas.psi.redhat.com/job/Runner-v3/280033/console (OCP-21339 failed because of the known bug)
@yasun1 @xueli181114 @yuwang-RH Please help review cases.

Update OCM rules because of the new changes

---

features/networking/multus.feature

PR is to fix https://issues.redhat.com/browse/OCPQE-3372
Any parallel running  multus cases can cause this case fail in checking the number of network_attachment_definition_instances{networks="any"} 
Simple solution is move this case to be a '@destructive' case
@zhaozhanqi @anuragthehatter @huiran0826 @rbbratta @asood @brahaney @kedark3

Move this case to be a '@destructive' case

---

features/networking/build.feature

sometimes build logs has not shown in 100 or 200 seconds, here add more times 
logs: 
http://pastebin.test.redhat.com/941913
@anuragthehatter @huiran0826 @rbbratta @asood-rh @weliang1 @kedark3

update more time for checking build logs

---

testdata/logging/logforwarding/elasticsearch/secure/configmap.yaml
testdata/logging/logforwarding/elasticsearch/secure/deployment.yaml

Per https://bugzilla.redhat.com/show_bug.cgi?id=1927537, the username and password are removed from the fluentd conf.
Same configuration as https://github.com/openshift/verification-tests/pull/1697
/cc @gkarager @anpingli

remove username and password

---

features/machine/machine.feature
testdata/cloud/ms-azure/ms_encrypt_at_rest.yaml

@jhou1 @sunzhaohua2 PTAL , whenever you get time
Auto test to validate changes by - https://bugzilla.redhat.com/show_bug.cgi?id=1900454
```
.
.
.
[11:23:46] INFO> Exit Status: 0
[11:23:46] INFO> Shell Commands: oc delete machines encrypt-at-rest-39639-6bq5t --wait=false --config=/root/workdir/d97593744bfd-/ocp4_admin.kubeconfig --namespace=openshift-machine-api
machine.machine.openshift.io "encrypt-at-rest-39639-6bq5t" deleted
[11:23:48] INFO> Exit Status: 0
[11:23:50] INFO> oc get machines encrypt-at-rest-39639-6bq5t --output=yaml --config=/root/workdir/d97593744bfd-/ocp4_admin.kubeconfig --namespace=openshift-machine-api
[11:25:49] INFO> After 45 iterations and 121 seconds:
STDERR:
Error from server (NotFound): machines.machine.openshift.io "encrypt-at-rest-39639-6bq5t" not found …
```

 test machine with spec securityProfile encryption at rest as "true"

---

lib/environment.rb

30 seconds is not enough it seems
Scenario: SDN pod should be working well after the node service is restarted
seems to cause the `oc get projects` to take too long
```
[04:46:32] INFO> Exit Status: 0
[04:46:33] INFO> oc get projects tests-psiv43-cucushift-oc46-standard-agent-cl40f-0 --output=yaml --kubeconfig=/home/jenkins/workspace/Runner-v3/workdir/ocp4_admin.kubeconfig
[04:47:03] INFO> After 19 iterations and 31 seconds:
apiVersion: project.openshift.io/v1
kind: Project
status:
conditions:
- lastTransitionTime: "2020-10-14T04:35:13Z"
message: 'Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request'
reason: DiscoveryFailed
status: "True"
type: …
```

increase service project wait timeout to 60s

---

features/step_definitions/logging.rb
features/test/logging_metrics.feature
lib/environment.rb

Start from logging 5.0, there have several different channels, to testing different channels, it's hard to determine the channel name in scenarios. To match logging testing requirements, adding two env vars `logging_catsrc` and `logging_channel_name`.
An example about how to set them:
```
export BUSHSLICER_CONFIG='
global:
browser: chrome
environments:
ocp4:
admin_creds_spec: "https://example.com/auth/kubeconfig/*view*/"
version: "4.8"
logging_catsrc: "example-registry"
logging_channel_name: "5.0"
idp: "example-idp"
admin_console_url: "https://console-openshift-console.apps.example.com"
'
```
/cc @anpingli

add env vars for logging to set catsrc and channel

---

features/step_definitions/helper_services.rb
testdata/storage/iscsi/iscsi-target.json
testdata/storage/iscsi/service.json

In our daily test, we found the worker node might be in "NotReady" status for the OOM, if the iscsi target pod is scheduled to the woker node and the node status is "NotReady", then the test cases for the iscsi will be blocked.
@duanwei33 @chao007 Please help review.

Update iscsi prepare step

---

lib/configuration.rb

We can use it in config.yaml for Flexy.
`FlexyEnvFile` class like:
```
services:
AWS-CI:
host_opts:
ssh_private_key: !ruby/object:BushSlicer::FlexyEnvVariable
var_name: ENVVAR1
```
where environment variable `ENVVAR1` contains the real (base64 encoded) key.
`FlexyEnvVariable` class like:
```
services:
openstack_upshift:
url: !ruby/object:BushSlicer::FlexyEnvVariable
var_name: ENVVAR1
```
where environment variable `ENVVAR1` contains the real URL.

Introduced FlexyEnvVariable and FlexyEnvFile helper classes

---

tools/launch_instance.rb

to get rid of warnings like 
`12:15:19  tools/launch_instance.rb:202: warning: URI.unescape is obsolete
`

Replace deprecated call URI::decode with URI::decode_www_from

---

features/node/proxy.feature

More contexts are in OCPQE-3579, the real issue is: `oc get proxy` is issued against the ci agent's ocp cluster, rather than the cluster under test, which keeps returning an empty proxy and making the test fail. Adding step `And I use the "xxx" project'` as a workaround.
Issue example: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/03/08/09:30:29/Proxy_config_should_be_applied_to_kubelet_and_crio-etc_systemd_system_kubelet_service_d_1_1751551161/console.html
@sunilcio pls review

fix proxy test in ci agents

---

features/routing/OWNERS
features/routing/idle.feature

After idling the service, the pod is still in `Terminating` state for a while (might be stuck on abnormal cluster), but the replicas of ReplicationController has been changed to "0" and cause the following wake up step unstable,
So replacing the checkpoint with `wait for the resource "pod" named "<%= cb.pod_name %>" to disappear within 120 seconds` to ensure the old pod is deleted before going to the next step. And we also can get correct information from the log if get stuck in Terminating.
Removed the useless step `wait until number of replicas match "1" for replicationController` since the following step `a pod becomes ready` can do the same thing.
@quarterpin @jechen0648  please help take a look. Thanks.
log:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Ru …

update idling cases

---

features/storage/aws.feature
features/storage/cinder.feature
features/storage/cloud_provider.feature
features/storage/dynamic_provisioning.feature
features/storage/glusterfs.feature
features/storage/hostpath.feature
features/storage/nfs.feature
features/storage/rbd.feature
features/storage/reclaim_policy.feature
features/storage/security.feature
features/storage/storage_class.feature
features/storage/storage_object_in_use_protection.feature
features/storage/vsphere.feature

Change the pod yaml file from v3-testfile to verification-tests/testdata as openshift-qe/v3-testfiles is deprecated now.
See discussion here: https://coreos.slack.com/archives/CPJQCSN49/p1612767945263600
@qinpingli @liangxia PTAL

Change storage v3-testfile to verification-tests/testdata

---

features/networking/ovn_ipsec.feature

see failed logs: http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/03/17/08:29:28/pod_to_pod_traffic_on_different_nodes_should_be_ESP_encrypted/console.html
@rbbratta @kakkoyun @weliang1 @huiran0826

update ipsec packets with correct match

---

testdata/routing/edge/route_edge.json
testdata/routing/reencrypt/reencrypt-without-all-cert.yaml
testdata/routing/reencrypt/route_reencrypt.json
testdata/routing/route_withouthost1.json
testdata/routing/unsecure/route_unsecure.json
testdata/routing/wildcard_route/route_edge.json
testdata/routing/wildcard_route/route_pass.json
testdata/routing/wildcard_route/route_reencrypt.json

see below warning message if using old apiVersion, so update related routes in testdata to use `route.openshift.io/v1`.
```
W0317 11:12:03.889137    6752 shim_kubectl.go:55] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "route.openshift.io/v1" for your resource
route.route.openshift.io/secured-edge-route created
```
@quarterpin @jechen0648 please help take a look. thanks.

update apiVersion for the routes

---

features/step_definitions/local_storage.rb

We need to feed the method and set `cached` to be `false` to force it to fetch new values since it's a status field

fix step to use cache: false

---

features/machine/machine_healthcheck.feature

Auto OCP-37139: Check the remediationsAllowed is visible in the MHC status @jhou1 @miyadav please help to take a look.
```
[04:29:43] INFO> === End After Scenario: Use "maxUnhealthy" to prevent automated remediation ===
18 steps (18 passed)
7m5.779s
```

auto OCP-37139

---

features/step_definitions/networking.rb

this kind of case will scale up node (eg. OCP-28108).  The nodes will be restore when the case is finished. However the multus DESIRED number will not be updated in short time.  see below logs:  the node number is 6. however multus DESIRED is still 7 in short time
```
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-135-35.us-east-2.compute.internal    Ready    master   62m   v1.20.0+e1bc274
ip-10-0-153-194.us-east-2.compute.internal   Ready    worker   57m   v1.20.0+e1bc274
ip-10-0-164-171.us-east-2.compute.internal   Ready    worker   61m   v1.20.0+e1bc274
ip-10-0-164-252.us-east-2.compute.internal   Ready    master   66m   v1.20.0+e1bc274
ip-10-0-196-233.us-east-2.compute.internal   Ready    master   62m   v1.20.0+e1bc274 …
```

update multus judgment in case DESIRED multus still not be updated when node remove

---

tools/jenkins/slaves/Dockerfile.rhel7

We have met twice that a repo is enabled unexpectedly in redhat.repo. So disable all repos by default to prevent such issue from happen again.
/cc @akostadinov @jhou1 @jianlinliu

Disable all repos except several needed ones

---

features/logging/elasticsearch.feature
features/step_definitions/logging.rb

A workaround to https://bugzilla.redhat.com/show_bug.cgi?id=1890838. Once the change is merged to 4.6. We will drop the 4.6 branch.

Use new cronjob names according to BZ1919075

---

features/step_definitions/networking.rb
features/upgrade/sdn/policy-upgrade.feature
testdata/networking/networkpolicy/allow-ns-and-pod.yaml

The PR automates the network policy managing access to the application ensuring it is functional post upgrade.
The network policy allows access to application only from a specific namespace.
Testing:-
Pre upgrade:-
bundle exec cucumber features/upgrade/sdn/policy-upgrade.feature:86
47 steps (47 passed)
1m6.249
Post upgrade:-
bundle exec cucumber features/upgrade/sdn/policy-upgrade.feature:164
20 steps (20 passed)
0m36.166s

OCP-38751-[Bug 1914284] The namespace networkpolicy for an application is functional post upgrade

---

features/networking/sriov.feature

It's blocking batch syncing scripts/tags from code back to Polarion.
```
{"error":"some test cases do not exist","description":"cases do not exist: OCP-24776"}
```
/cc @zhaozhanqi @jhou1

Remove OCP-24776 as it's no longer valid

---

features/step_definitions/logging.rb
features/upgrade/logging/upgrade_with_clf.feature
lib/openshift/cluster_logging.rb
lib/openshift/subscription.rb
testdata/logging/clusterlogforwarder/clf-multiple-external-logstore-template.yaml

case: https://url.corp.redhat.com/f0086ba
upgrade-prepare: https://url.corp.redhat.com/b72f05c
upgrade-check: https://url.corp.redhat.com/5b5458d
/cc @anpingli @gkarager

add upgrade case to test clusterlogforwarder

---

features/logging/logging_acceptance.feature
features/step_definitions/logging.rb

For some design limitation, all logging cases are belong to destructive cases. thus logging cases may be skipped in some testing.
For some known issues(resource limitation, unstable mirror registry in disconnect cluster,  no mirror images in some cluster), some critical logging cases are tagged as flaky and won't be executed in our automated framework. 
To minimal the risk  in openshift and openshift-logging testing.  We want to make this acceptance case to be the only one non-destructive case and can be running one any platform. As this is the only one case in no-destructive bucket.  I suggest we didn't  flaky it unless it block the other cases.  Logging QE will treat this case failure as high priority.  We will continue to enhance it and  integrate more feature into it.
@QiaolingTang …

remove flack and destructive cases

---

features/networking/service.feature
features/step_definitions/networking.rb

Developers pointed out in the bz https://bugzilla.redhat.com/show_bug.cgi?id=1930446 that we should not need to use NetworkManager during modification of MTU. In order to align with that, I updated the test case.
The Test works as expected, it is able to modify the MTU successfully on a new cluster. But as soon as we modify the MTU, the cluster breaks and starts acting weird(sometimes, more likely in the case where your test picks master node to modify mtu). What that means is we cannot actually reliably execute the test successfully. The bug associated with the test is open and awaiting fix. https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/28355/console
cc @rbbratta @weliang1 @asood-rh @zhaozhanqi @huiran0826  @brahaney @pruan-rht

Fix small mtu test

---

features/networking/ipv6_dualstack.feature
lib/openshift/pod.rb
lib/openshift/service.rb
testdata/networking/list_for_pods_ipv6.json
testdata/networking/networkpolicy/multitenant_policy.yaml

for dual stack cluster .we have ipv4 and ipv6 ip for pod and service, see 
pod:
```
f:ip: {}
hostIP: 192.168.123.71
podIP: 10.130.0.94
podIPs:
- ip: 10.130.0.94
- ip: fd01:0:0:3::5e
```
service:
```
spec:
clusterIP: 172.30.133.189
clusterIPs:
- 172.30.133.189
- fd02::1cd8
ipFamilies:
```
@akostadinov @pruan-rht @liangxia  could you help take a look?
cc @rbbratta @weliang1 @huiran0826 @asood-rh @kakkoyun @brahaney

add get ipv6 address for pod and service

---

features/networking/ovn_ipsec.feature

Automate [SDN-1571] OCP-40569 Allow enablement/disablement ipsec at runtime
Test case: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-40569
Test Log: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/2998/console
@zhaozhanqi @anuragthehatter @huiran0826 @rbbratta @asood @brahaney @kedark3

Automate OCP-40569 Allow enablement/disablement ipsec at runtime

---

features/step_definitions/scheduler.rb
features/upgrade/workloads/scheduler-upgrade.feature

With the existing code, cannot restore the cluster object to the right state if any additional child elements like tlsSecurityProfile is added to the spec, so modified the code a little to handle the same.

Fix scheduler

---

features/networking/sdn.feature

Found this issue in daily failed cases https://polarion.engineering.redhat.com/polarion/#/project/OSE/wiki/Networking/Networking%20failed%20cases
and the failed logs http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2021/04/18/04:21:11/NetworkManager_should_consider_OVS_interfaces_as_unmanaged/console.html
some OVN cluster may not contain `br-local` and `ovn-k8s-gw0` when using 'nmcli`. I did not research more for it. if you know please help comment it.  thanks

update case OCP-25933

---

features/logging/collector.feature

Fix failure:
```
809: unexpected token at 'STDERR:
E0422 02:48:02.284740  236409 v2.go:105] read /dev/stdin: invalid argument
' (JSON::ParserError)
(eval):1:in `block in <top (required)>'
/root/go/src/github.com/openshift/verification-tests/features/step_definitions/common.rb:130:in `eval'
/root/go/src/github.com/openshift/verification-tests/features/step_definitions/common.rb:130:in `/^evaluation of `(.+?)` is stored in the(?: :(\S+))? clipboard$/'
```
/cc @anpingli @gkarager

fix failure

---

features/logging/OWNERS
features/logging/elasticsearch.feature
features/logging/logging_acceptance.feature
features/step_definitions/logging.rb
testdata/logging/clusterlogging/cl-storage-with-im-template.yaml

https://issues.redhat.com/browse/OCPQE-3916
/cc @anpingli @gkarager

fix failures in logging 5.1

---

features/logging/kibana.feature

Fix failure:
```
When I perform the :kibana_find_index_pattern web action with:                               # features/step_definitions/web.rb:1
[00:54:13] INFO> running web action kibana_find_index_pattern ... 
[00:54:13] INFO> elements..
| index_pattern_name | *infra |
Unable to locate element collection from {:xpath=>"//h2[@class=\"index-pattern-label\" and @id=\"index_pattern_id\" and contains(., \"*infra\")] | //span[contains(., \"*infra\")]"} due to changing page (Watir::Exception::LocatorException)
```
and
```
When I run the :logs client command with:                                                  # features/step_definitions/cli.rb:13
[01:15:56] INFO> Shell Commands: oc logs kibana-78447cb644-lkj44 -c kibana --kubeconfig=/home/qitang/workdir/localhost-qitang/ocp4_testuser-43.kub …
```

fix kibana cases

---

features/networking/egress-ingress.feature

When creating the EgressFirewall, it may takes some time to generate the rule, but in auto run, the step is fast, so add timeout here to wait for the rule generated and status updated.
And run it multiple times for the fix and it passed.
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3067/console
@zhaozhanqi @anuragthehatter @rbbratta @weliang1

fix OCP-41179

---

features/machine/upi_gcp.feature

Auto OCP-34697: MachineSets in GCP should create Machines in a Shared (XPN) VPC environment @jhou1 @miyadav please help to take a look
```
[05:30:18] INFO> === End After Scenario: MachineSets in GCP should create Machines in a Shared (XPN) VPC environment ===
1 step (1 passed)
0m14.550s
```
Enable upi xpn gcp machinesets pr: https://gitlab.cee.redhat.com/aosqe/flexy-templates/-/merge_requests/526

auto OCP-34697

---

tools/jenkins/slaves/Dockerfile.rhel7

Both steps `yum repolist all` and `yum-config-manager --disable \*` are really time consuming as there are many repositories.
1. Use `yum repolist enabled` to replace `yum repolist all`, as generally we only cares about the enabled repos.
2. Use `yum-config-manager --disable $OLD_REPOS` to replace `yum-config-manager --disable \*`, as there are no need to iterate those disabled repos.
/cc @pruan-rht @jhou1 @JianLi-RH

Opt out the time consuming steps in base image's dockerfile

---

features/support/env.rb
lib/manager.rb
lib/polarshift/test_suite.rb
lib/test_case_manager_filter.rb

conflict here means that another executor has taken this scenario already
so we need to skip it to avoid double execution

[hotfix] skip scenario skipping on conflict

---

testdata/quota/pod-completed.yaml

With the previous image the test case was hitting docker pull limit, so changing the image so that it can be pulled from quay.io

Fix image name

---

config/cucumber.yml

by default, there's this marketing banner from cucumber...this should suppress it.
```
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this …
```

avoid printing report outline by default

---

lib/gherkin_parse.rb

Might be a side effect of migration to cucumber 5.x
/cc @jhou1 @pruan-rht @kasturinarra @JianLi-RH 
Failure message,
```
$ tools/polarshift.rb update-automation OCP-41580
13: from tools/polarshift.rb:492:in `<main>'
12: from tools/polarshift.rb:262:in `run'
11: from /usr/share/gems/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
10: from /usr/share/gems/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
9: from /usr/share/gems/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
8: from /usr/share/gems/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
7: from /usr/share/gems/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
6: from tools/polarshift.rb:65:in `block (2 levels) in run'
5: from …
```

Fix update-automation of polarshift.rb

---

features/upgrade/sdn/policy-upgrade.feature

Fix for issue https://issues.redhat.com/browse/OCPQE-3886 
First validation done immediately after applying policy to namespace fails.
The fix is to add wait of 10 second in both the runs before running validation checks.
Local run
Pre upgrade
34 steps (34 passed)
1m22.300s
Post upgrade 
0m36.182s
[14:15:37] INFO> === At Exit ===

Add wait before validating to ensure the policy has been applied

---

features/node/kata/install_uninstall.feature
features/step_definitions/kata.rb

1. skip kata installation steps if there's an existing kataconfig
2. fix a typo in a step
3. default kata project is now 'openshift-sandboxed-containers-operator'

skip installation steps if there's an existing kataconfig

---

features/step_definitions/helper_services.rb
lib/environment.rb

@duanwei33 @chao007 @liangxia @pruan-rht Please help review this PR.
This PR is for there is default scheduler is set in the cluster, such as:
```
$ oc get scheduler cluster -ojson|jq .spec
{
"defaultNodeSelector": "node-role.kubernetes.io/worker=",
"mastersSchedulable": false,
"policy": {
"name": ""
}
}
```
The update in `helper_services.rb` file is for the iscsi test, our iscsi target pod is scheduled to the master node, so if we still use the `default` ns, then there will be some conflict in the node selector config.
The update in `enviorment.rb` file is for the cmd `oc debug node`, if we created a namespace without overwrite the cluster wide scheduler, then the `oc debug node` cmd will fail.

Add supports if the default scheduler is set

---

features/networking/multus.feature

Seems like the upstream/downtream multus has finally corrected this minor english mistake and backported to earlier releases. Hence test case needs to be adjusted accordingly to avoid CI failures
Re-ran to make sure : http://pastebin.test.redhat.com/964530

OCP-22504 quick fix

---

Gemfile

Psych 4.x and our cuke5 migration doesn't seem to play well as described in JIRA [OCPQE-4052](https://issues.redhat.com/browse/OCPQE-4052).  To unblock folks, specify the Psych (ruby YAML lib) to 3.x

workaround for OCPQE-4052

---

features/step_definitions/scheduler.rb

When the crd is Scheduler restore logic  tries Scheduler instead of kubescheduler so it fails, fixing the same.

Fix restore logic of scheduler

---

features/routing/haproxy-router.feature
features/routing/route.feature

We found some v3 test cases were failed due to image pull rate limit issue of docker.io, since the old  `openshift-qe/v3-testfiles` repo is deprecated, so update the test cases to use the testdata (master branch) that already consumed the images from `quay.io/openshifttest`.
@quarterpin @jechen0648 Please help take a look. Thanks.

[v3] update some critical routing cases to use images from quay

---

features/step_definitions/networking.rb

On Single Node OpenShift there is no OVN leader, `leader_id` is nil.
Instead of
```
NoMethodError: undefined method `[]' for nil:NilClass
```
use the regular error message

OVN: error if no leader

---

features/networking/sctp.feature

sctp testing failed more often than before in https://polarion.engineering.redhat.com/polarion/#/project/OSE/wiki/Networking/Automation%20-%20Networking%20Failed%20Tests
Update script to execute nc at background for sctp server pod. 
Testing log: http://file.rdu.redhat.com/~weliang/sctp_log.txt

Execute nc at background for sctp server pod

---

features/cluster_configuration/create_index_catalog.feature
features/node/kata/install_uninstall.feature
features/step_definitions/cluster_configuration/cluster_config.rb
features/step_definitions/kata.rb
testdata/catalogsource/catalog_source.yaml
testdata/catalogsource/image_content_soruce_policy.yaml

1. added smoke test for kata
2. added check for `qe-app-registry` which is needed in order to run the installation
3. added step to create the `qe-app-registry` if it does not exist.
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3081/console

added case OCP-41813 and check for qe-app-registry

---

features/step_definitions/scheduler.rb

Currently when the scheduler cluster has profile in the spec, restore logic does not handle it the right way, so fixing the same.

Fix scheduler restore logic

---

features/machine/machine_misc.feature

@jhou1 @sunzhaohua2 , Please have a look whenever possible 
Modified to make sure it doesnt fail till the time vsphere version changes are minor releases :) 
```
.
.
.
[07:10:19] INFO> HTTP GET https://prometheus-k8s-openshift-monitoring.apps.miyadav-31.qe.devcluster.openshift.com/api/v1/query?query=cloudprovider_vsphere_vcenter_versions
[07:10:20] INFO> HTTP GET took 1.261 sec: 200 OK | application/json 511 bytes
| path  | /api/v1/query?                         |
| query | cloudprovider_vsphere_vcenter_versions |
And evaluation of `@result[:parsed]["data"]["result"][0]["metric"]["version"]` is stored in the :vsphere_version clipboard # features/step_definitions/common.rb:128
Then the output should contain: …
```

 vpshere version gets changed, ex- as now it is 7.0.1

---

features/step_definitions/scheduler.rb

currently when etcd cluster is patched to redeploy openshift-etcd pods there is no way to restore the etcd cluster back after the test, adjusting the function here to do the same.

Add code to remove forcedeploymentreason

---

features/step_definitions/replicas.rb

example usage `Given there are 6 "daemon_set" replicas in the "openshift-monitoring" project`.  Should help with PR #2029
@lihongyan1 this should help with your PR

helper step to check for number of replicas for a cluster resource

---

features/step_definitions/kata.rb

Extend the timeout value to 1000 seconds instead of 900.  Also print the kata operator image information

extend timeout for install and uninstall

---

.gitignore
tools/launch_instance.rb

needs testing to allow setting stdin to `shell_commands`
This can workaround `gcloud` issue where it crashes if
`stdin` is closed with
```
ERROR: gcloud crashed (AttributeError): 'NoneType' object has no attribute 'isatty'
If you would like to report this issue, please run the following command:
gcloud feedback
To check gcloud for common problems, please run the following command:
gcloud info --run-diagnostics
```
So a tast to workaround this would look like
```
install_sequence:
- type: shell_command
stdin: :empty
cmd:
- bash
- "-c"
- |
gcloud auth activate-service-account "some-serviceaccount@whatever.iam.gserviceaccount.com" --key-file /tmp/openshift-qe-gce_v4.json
```
FYI the `gcloud` reproducer
```
ssh -T installer3@hostname 'exec 0<&- ; gcloud auth activate-service-account …
```

allow setting stdin in flexy launcher commands

---

features/networking/multicast.feature

This case will test multicast in both SDN and OVN cluster.
Testing always failed in OVN cluster due to Bug 1879241 - [OVN] Pods always lose one multicast packets
Testing randomly failed in SDN and OVN due to 10 seconds is not enough for pod to collect multicast traffic log
Fixing:
1. In old code, the server send 5 multicast packets, and client expect to receive 5, new code is updated to check not all 5 packets lost in the client side.
2. Increase 10 to 20 seconds to wait pod to collect multicast log
Testing log:
http://file.rdu.redhat.com/~weliang/log-OVN
http://file.rdu.redhat.com/~weliang/log-SDN

Fixing for BZ-1879241

---

lib/rules/web/admin_console/4.8/check_links.xyaml
lib/rules/web/admin_console/4.8/common_ui_elements.xyaml
lib/rules/web/admin_console/4.8/operator_hub.xyaml
lib/rules/web/admin_console/4.8/search.xyaml
lib/rules/web/admin_console/4.8/storage.xyaml

OCP-27601		Multiple resources could be selected on event page    
OCP-27550		Allow users to search for more than one resource type on search page        
OCP-24415		Select container when attach/remove volume        
OCP-24106		[admin] Check breadcrumb on resource detail page      
OCP-19532             Check resource events      
OCP-21461		[admin] check monitoring routes on web console        
OCP-28832		[admin] Basic sync of YAML and Form for creating operator instance    
Fix rules for cases above, will paste log jobs when available.

fix for web rules

---

features/machine/machine.feature

Fix  OCP-34718, @miyadav @jhou1 please take a look. From 4.8 this changed from `failure-domain.beta.kubernetes.io/region` to `topology.kubernetes.io/region`.
And on azure,zone has no value, so removed the verification of the zone.
```
Node Affinity:
Required Terms:
Term 0:        failure-domain.beta.kubernetes.io/region in [northcentralus]
✘ oc get machine
NAME                                               PHASE     TYPE              REGION           ZONE   AGE
wduan-0615c-az-jfkrj-master-0                      Running   Standard_D8s_v3   northcentralus          3h2m
wduan-0615c-az-jfkrj-master-1                      Running   Standard_D8s_v3   northcentralus          3h2m
wduan-0615c-az-jfkrj-master-2                      Running   Standard_D8s_v3   northcentralus          3h2m …
```

fix OCP-34718

---

features/networking/sctp.feature

Fix nc connection refused issue in https://issues.redhat.com/browse/OCPQE-2668
Current script sometimes cause nc connection refused due to nc -k option is used in the sctp server and nc -w option is used in sctp client.
New update delete both nc options and will continue trying open nc connection in both sctp server and client sides at the same time for 60 seconds to avoid randomly nc connection refused.
Continue testing new script in both ovn and sdn clusters for more than 1 hours, no connection failure happen, the script is more reliable now. 
Testing logs:
OVN: http://file.rdu.redhat.com/~weliang/ovn-log
SDN: http://file.rdu.redhat.com/~weliang/sdn-log

Fix nc connection refused issue

---

lib/rules/web/ocm_console/cluster_detail.xyaml
lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
lib/rules/web/ocm_console/login.xyaml
lib/rules/web/ocm_console/osd_creation_page.xyaml

As for OCP-21100, the script for the automation test creating an advanced OSD cluster, there quite a few errors that prevent the automation from successfully running, I fixed those. The first things I fixed are some small errors where the name is not up-to-date, such as I fixed the outdated name "Location" to the new name "Region".
The next thing is I fixed the automation go to the add-on tab in the cluster overview page and select the appropriate add-on and install it. The script works only for the old UI and now it needs updates.
I also fixed the place where the add-on failed and we need to check whether there is a "Contact Support". Again, the script only works for the old UI, it needs updates
Next, the automation can't successfully selected the correct button for selecting the Machine …

Fixed the error associated with OCP-21100

---

features/step_definitions/common.rb

Added support for more verbose printing when eval is called and the result is false.
Current printout:
```
Then the expression should be true> cb.tmp.size > 5                       # features/step_definitions/common.rb:133
expression "cb.tmp.size > 5" returned non-positive status: false
```
New more verbose printout:
```
expression "cb.tmp.size > 5" returned non-positive status: false
left_operand: 5, right_operand: 5
```

more verbose eval print

---

features/logging/logging_acceptance.feature

This is a PR to add wait before Web Console validation for log acceptance scenario.
Previous Runner job was failing due to the Elastic Cluster Status not appearing on web console validation. 
(Sample Failed Job: https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/79818/console)
New Runner smoke job success after adding wait.
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3179/console
Please review and approve @anpingli @QiaolingTang @gkarager

Adding wait for log acceptance feature on webconsole validation

---

lib/rules/web/ocm_console/cluster_detail.xyaml
lib/rules/web/ocm_console/cluster_detail_addons_tab.xyaml
lib/rules/web/ocm_console/cluster_detail_networking_tab.xyaml
lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
lib/rules/web/ocm_console/login.xyaml
lib/rules/web/ocm_console/osd_creation_page.xyaml

Debug cases OCP-37144 OCP-37143 OCP-35970
Updated June 24.
The errors mainly are associated with the add-on installation page. The new UI will have to require the user to first click on the article of a specific add-on, and then do operations on it. I modified the automation script to accommodate for this change.
The successful automation log can be found here http://pastebin.test.redhat.com/974134

Fixed the error associated with OCP-37144 OCP-37143 OCP-35970

---

features/logging/cluster_logging_operator.feature
features/logging/elasticsearch.feature
features/logging/elasticsearch_operator.feature
features/step_definitions/logging.rb

Fix following issues:
1. remove unused key `ca.key` when creating pipeline secret
2. add a wait block when checking logging dashboards to wait for the web page to be fully loaded
3. fix typo when testing index management scripts
/cc @anpingli @kabirbhartiRH

fix some automation issues

---

features/step_definitions/kata.rb
features/test/kata.feature
lib/openshift/project_resource.rb

1. optimized pods in all namespace for kata. It was printing out all of the pods in all namespaces which resulted in a massive print so the run log is over 4Meg as a result.  Now we filter out using jsonpath, using two `oc` calls.  Not sure if it's possible to get multiple values in one `oc` call
2. added methods for getting `metadata.ownerReferences` for project resource objects.  This is needed to determine the proper resource to remove in order to delete a pod.  For example, pods that are generated via `Deployment` or `DeploymentConfig`, we'll need to delete that resource instead of the kata pod to prevent it from regenerated
3. Added extra duty during the remove kataconfig step to remove all existing kata-pods in the cluster instead of raising an exception and exit.
runlog: …

added support to remove all kata pods in a cluster

---

features/upgrade/sdn/policy-upgrade.feature

The network policy is tweaked to change the pod labels to ensure ACLs are recreated if the policy is modified.
Pod label controlled by policy is hello-idle instead of test-pods.
pod4->pod3ip passed prior to modification but fails as expected
pod5->pod2ip failed but succeeds post modification.
pod5->pod3ip (positive test case step)
Testing:-
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3206/console (Upgrade prepare)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3206/console (Post upgrade)

Add steps to modify the policy post upgrade to verify it works well

---

features/step_definitions/networking.rb
testdata/networking/networkpolicy/allow-from-hostnetwork.yaml
testdata/networking/networkpolicy/allow-from-router-ingress.yaml
testdata/networking/networkpolicy/allow-from-router.yaml

The network policies moved from private repo to public repo as these are going to be used for upgrade scripts.
Added a step to obtain multus pod on master nodes to ensure allow from hostnetwork policy is actually tested.
If the test pod end up on same node from where multus pod is scheduled then the network policy does not have anything to do so it is not really tested. This step makes sure multus pod used for testing is running on one of master node.
Test logs can be found here:-
vSphere
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3223/console OCP-41944
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3224/console (OCP-40898 and OCP-40899)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.re …

Change location of policy files to public repo and use multus pod from naster node

---

features/machine/machine.feature
lib/openshift/machine.rb
testdata/cloud/ms-gcp/ms_default_values.yaml

This is to make sure machine doesnt get stuck in provisioned state as that can cause , machine to be in deletion phase indefinitely
which might result in Premature failures and other tests from running , leaving it to be a machine without node condition .
@sunzhaohua2 @jhou1  PTAL 
Results : https://url.corp.redhat.com/ocp33056

SA warning prevents , node creation , adding that to default machineset

---

features/upgrade/sdn/policy-upgrade.feature

All three policies (allow from router- new label, allow from router -old label and allow from hostnetork )are applied respectively to three projects.
The test case ensures the policies do what they are supposed (postive path).
Default deny policies are also applied but no validation around it, just assuming the policies do deny traffic to the project.
Testing:-
vSphere (Hostnetwork)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3266/console (pre upgrade)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3267/console (post upgrade)
AWS (LoadBalancer Service)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3268/console (pre upgrade) …

OCP-40620 - allow from router and allow from host network policy in upgrade scenario

---

features/machine/machine.feature

increase the time to create the machineset @miyadav @jhou1 please help to take a look.
```
[04:13:04] INFO> === End After Scenario: Implement defaulting machineset values for azure ===
2 scenarios (2 passed)
30 steps (30 passed)
15m16.543s
```

Fix OCP-33058

---

features/step_definitions/common.rb

currently, this is wrong `unless expr.scan(ruby_special_op)`.  Should be gauged by `.count > 0` instead.  Original PR #2128 introduced the bug of not interpreting the expression correctly.

fix string.scan check

---

features/logging/cluster_logging_operator.feature
features/step_definitions/logging.rb

Fix issue when deploy logging operators:
```
[2021-07-02T00:47:57.737Z] [36m[33m[00:47:56] INFO> Shell Commands: oc get packagemanifests cluster-logging --output=yaml --config=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_admin.kubeconfig[0m[0m
[2021-07-02T00:47:57.737Z] [36m[0m
[2021-07-02T00:47:57.737Z] [36mSTDERR:[0m
[2021-07-02T00:47:57.737Z] [36mError from server (NotFound): namespaces "aos-qe-ci" not found[0m
```

fix: Error from server (NotFound): namespaces "aos-qe-ci" not found

---

features/logging/logging_acceptance.feature

Fix failure:
```
07-06 16:07:12.242        Logged into "https://api.xxxxxxxxx.com:6443" as "testuser-36" using the token provided.
07-06 16:07:12.242        
07-06 16:07:12.242        You don't have any projects. You can try to create a new project, by running
07-06 16:07:12.242        
07-06 16:07:12.242            oc new-project <projectname>
07-06 16:07:12.242        
07-06 16:07:12.242        
07-06 16:07:12.242        [08:07:09] INFO> Exit Status: 0
07-06 16:07:12.242        [08:07:10] INFO> Shell Commands: oc project openshift-marketplace --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_testuser-36.kubeconfig
07-06 16:07:12.242        
07-06 16:07:12.242        STDERR:
07-06 16:07:12.242        error: You are not a member of project "openshift-marketplace". …
```

fix failure 'You are not a member of project openshift-marketplace.'

---

lib/rules/web/ocm_console/archived_cluster_detail.xyaml
lib/rules/web/ocm_console/archived_clusters.xyaml
lib/rules/web/ocm_console/cluster_detail.xyaml
lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
lib/rules/web/ocm_console/ocm_workflow.xyaml
lib/rules/web/ocm_console/subscription_page.xyaml

@xueli181114 When I do removing the registered 'clean up', I found that the rules for the cases(related to archived cluster) are out-of-date or dirty, just do a simple changes. Assume in future, we need to reorganize the steps/rules for these cases. Please help review.
The related cucushift PR: https://github.com/openshift/cucushift/pull/8636

remove the registered 'clean up' from ocm

---

features/step_definitions/pv.rb
features/storage/fsType.feature

1. Update the fsType.feature to make sure the args are as same as in the polarion
2. Update the cleanup step, in previous code, only deleting pv (which is bound to pvc) doesn't work. It always hung for the timeout.
[pass log](https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3-smoke/3282/console)
@chao007 @jhou1 PTAL

Fix the v3 script to use the same args with 4.x

---

features/upgrade/node/hpa/upgrade.feature

@sunilcio @lyman9966 @rhpmali ,could you help take a look?
Adding a step to ensure the `node-upgrade` project is deleted before execution
```
And the pod named "dapi-test-pod-1" status becomes :succeeded                    # features/step_definitions/pod.rb:77
[07:59:10] INFO>
[07:59:12] INFO> After 2 iterations and 3 seconds:
matched status for pods dapi-test-pod-1: 'succeeded' while expecting '[:succeeded]'
[07:59:12] INFO> === After Scenario: Upgrade - Make sure multiple resources work well after upgrade - prepare ===
[07:59:12] INFO> Shell Commands: rm -r -f -- /home/weinliu/workdir/rhel8-weinliu
[07:59:13] INFO> Exit Status: 0
[07:59:14] INFO> === End After Scenario: Upgrade - Make sure multiple …
```

fix the node-upgrade project not deleted issue

---

features/step_definitions/kata.rb

A recent run failed due to only 2/3 worker-nodes were removed within the timeout 1200 seconds, extend it 5 more minutes.
```
07-08 22:22:57.735          unInstallationStatus:
07-08 22:22:57.735            completed:
07-08 22:22:57.735              completedNodesCount: 2
07-08 22:22:57.735              completedNodesList:
07-08 22:22:57.735              - qeci-49-6tl5h-worker-a-lh6s5.c.openshift-qe.internal
07-08 22:22:57.735              - qeci-49-6tl5h-worker-b-7g4fc.c.openshift-qe.internal
07-08 22:22:57.735            errorMessage: Existing pods using Kata Runtime found. Please delete the pods manually
07-08 22:22:57.735              for KataConfig deletion to proceed
07-08 22:22:57.735            failed: {}
07-08 22:22:57.735            inProgress:
07-08 22:22:57.735 …
```

extend timeout for kataconfig deletion

---

features/networking/pod.feature
features/networking/service.feature
testdata/networking/custom_kubelet.yaml
testdata/networking/max-pods-without-consume-memory.yaml

@weliang1  could you help check the steps are correct here. 
I tested the script locally on IPI aws with `vm_type_workers: 'm5.xlarge'`, using normal cluster in our CI often caused the worker become not ready. 
and this case may cost 30 Mins to run it. 
@mffiedler this is the case we talked about in watch list docs need to run on large cluster.  Could you help review it and How to choose this case and run on perf cluster.

add auto case 41666

---

lib/rules/web/admin_console/4.1/common_ui_elements.xyaml
lib/rules/web/admin_console/4.2/common_ui_elements.xyaml

check_resource_item_name is used in console upgrade case. In upgrade ci, there are still 4.1/4.2 original version, console case would fail in these runs.

fix rule for console upgrade case

---

features/networking/sdn.feature
features/networking/service.feature

according to comment in https://bugzilla.redhat.com/show_bug.cgi?id=1983951#c8,  whatever the cluster is share gateway or local gateway.  we need to make sure service can be accessed from worker. 
So here I added one checkpoint in this case
tested on my local
```
[07:29:55] INFO> Exit Status: 0
[07:29:56] INFO> Shell Commands: oc debug  --kubeconfig=/home/zzhao/workdir/dhcp-140-240-zzhao/ocp4_admin.kubeconfig -n tests-dhcp-140-240-zzhao --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:56560421f15944c7282635c86e852a49147bfbe2d627bb93663f781c316d816d node/dell-per740-35.rhts.eng.pek2.redhat.com -- chroot /host/ bash -c cd\ \'/tmp/workdir/dhcp-140-240-zzhao\''
'curl\ --connect-timeout\ 5\ 172.30.150.178:27017
% Total    % Received % Xferd  Average Speed …
```

add checkpoint from worker to access service

---

features/machine/machine_healthcheck.feature

@sunzhaohua2 @jhou1  PTAL ..
Test runs fine on UPI clusters 
```
STDERR:
The MachineHealthCheck "mhc-malformed" is invalid: spec.maxUnhealthy: Invalid value: "": spec.maxUnhealthy in body should match '^((100|[0-9]{1,2})%|[0-9]+)$'
[06:22:07] INFO> Exit Status: 1
"""
When I run oc create over "mhc_validations.yaml" replacing paths:
| ["spec"]["maxUnhealthy"] | #{cb.resource} |
Then the output should match:
| maxUnhealthy: Invalid value: ".*": spec.maxUnhealthy |
"""
[06:22:07] INFO> === After Scenario: Leverage OpenAPI validation within MHC ===
[06:22:07] INFO> Shell Commands: rm -r -f -- /root/workdir/7ed35be48865-
[06:22:08] INFO> Exit Status: 0
[06:22:09] INFO> === End After Scenario: Leverage OpenAPI …
```

Remove IPI check, as test runs on UPI too

---

features/networking/multicast.feature
features/step_definitions/networking.rb

Multicast is a k8s upstream feature, it makes no sense to keep openshift multicast cases separately in cucushift and verification-tests.
This PR will make below changes:
1. Copy OCP-12928/OCP-12929/OCP-12966 from cucushift to verification-tests, after this PR merging and updating Automation path in polarion, all the multicast cases will be executed from verification-tests.
2. Update OCP-12928/OCP-12929/OCP-12966  to be executed in both SDN and OVN cluster, right now these three cases can only be executed in SDN.
3. Update OCP-12928/OCP-12929/OCP-12966  to expect not all 5 packets lost in the client side due to Bug 1879241 - [OVN] Pods always lose one multicast packets
4.  Update OCP-12928/OCP-12929/OCP-12966  to allow 10 seconds for the multicast igmp group information shown up when …

Execute all multicast cases in verification-tests

---

features/machine/machine.feature

The `@admin` tag is missing from the test scenario, which results in a failure in Prow. @sunzhaohua2 @miyadav @liangxia PTAL
```
Scenario: Machines should be linked to nodes
Given I have an IPI deployment
Message:
unknown credentials specification: /tmp/kubeconfig-269162583 (RuntimeError)
./lib/admin_credentials.rb:96:in `get'
./lib/environment.rb:113:in `admin'
./lib/world.rb:124:in `admin'
./features/step_definitions/machine.rb:3:in `/^I have an IPI deployment$/'
features/machine/machine.feature:7:in `I have an IPI deployment'
```

Machine tests needs @admin

---

features/networking/sdn.feature
features/step_definitions/networking.rb

restarting kubelet seems to be an old 3.x step
that seems to fail frequently and might be of dubious utility
remove the kubelet restart step and just restart the network service.
The iptables rules should be re-created already as part of the test.
Also replace `puts` with `logger.info` as per deprecation notice.

OCP-11286: don't restart kubelet to avoid test failures

---

testdata/networking/sctp/sctpclient.yaml
testdata/networking/sctp/sctpserver.yaml

Currently, sctp use ubi image plus ["dnf install -y nc && sleep inf"] for sctpserver and sctpclient pod, in disconnected cluster, pod can not execute  ["dnf install -y nc && sleep inf"] and sctp testing will fail in disconnected cluster.
This PR is to update pod image to use quay.io/openshifttest/centos-network which include nc utility being used for sctp testing.
Test log from a disconnected cluster/edge50 bare metal machine:
http://file.rdu.redhat.com/~weliang/sctp.log

Update pod image for sctp testing

---

lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml

in 4.9, developer console, Monitoring is changed to Observe, 
see from https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/321361/artifact/embedded_files/2021-08-17T08%3A44%3A02+00%3A00-screenshot.png
change the 4.9 rule accordingly.
4.9 run pass:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/Runner-v3/321363/consoleFull

change Monitoring to Observe for 4.9 due to change

---

features/cli/job.feature

Failure at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21446/rehearse-21446-periodic-ci-openshift-release-master-nightly-4.9-e2e-cucushift-aws-ipi/1432336610912899072
In the expected output, `End` -> `end`
@liangxia @pruan-rht @geliu2016 PTAL

Fix expected output

---

config/cucumber.yml

Avoid printing report outline with profile polarshift

---

tools/openshift-ci/Dockerfile

This fixes the following [failure in Prow](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/21446/rehearse-21446-periodic-ci-openshift-release-master-nightly-4.9-e2e-cucushift-aws-ipi/1433059395142422528/build-log.txt)
```
Scenario: Copying files from host to container using oc rsync command with --watch test
Given I wait for the steps to pass:
Message:
pattern not found: test (RuntimeError)
...
WARNING: rsync command not found in path. Please use your package manager to install it
```
Tested on my laptop which has `rsync` -- test passed
Tested on the verification-tests image which has no `rsync` -- failure reproduced.
@liangxia @pruan-rht PTAL

Add pkg rsync

---

features/step_definitions/logging.rb

Fix failure when checking the new CSV version after changing the channel/source in subscription. With this fix, the case can pass when the channel name is  `5.0`, `stable-5.1`, `stable-5.2`, but it will fail when the channel name is `stable`. Currently I have no idea about how to determine the CSV version of `stable` channel.
```
08-31 20:34:30.212        [12:34:03] INFO> Shell Commands: oc get subscriptions.operators.coreos.com elasticsearch-operator --output=yaml --kubeconfig=/home/jenkins/ws/workspace/ocp-common/Runner/workdir/ocp4_admin.kubeconfig --namespace=openshift-operators-redhat
08-31 20:34:30.212        apiVersion: operators.coreos.com/v1alpha1
08-31 20:34:30.212        kind: Subscription
08-31 20:34:30.212        metadata:
08-31 20:34:30.212          creationTimestamp: …
```

fix upgrade failure

---

lib/environment.rb

In some rarely cases, the EXECUTOR_NAME might be suffix with chars that are not valid for project names.
/cc @jhou1 @pruan-rht

Fix invalid project name in some rarely cases

---

lib/environment.rb

Fix error as below in https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/21446/rehearse-21446-periodic-ci-openshift-release-master-nightly-4.9-e2e-cucushift-aws-ipi/1435228405472694272/build-log.txt
```
[14:16:44] INFO> Shell Commands: oc debug  --kubeconfig=/tmp/dir1/workdir/ocp4_admin.kubeconfig -n proj-e2e-cucushift-aws-ipi-cucushift-aws-ipi-s --image=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:61e9bf24b15ed423b01099d56850b491ea156bf97d25eae9be903c978db28940 node/ip-10-0-182-213.us-west-1.compute.internal -- chroot /host/ bash -c mkdir\ -v\ -p\ \'/tmp/workdir/e2e-cucushift-aws-ipi-cucushift-aws-ipi-\'
STDERR:
Error from server (Forbidden): pods "ip-10-0-182-213us-west-1computeinternal-debug" is forbidden: unable to create new content in namespace …
```

Extend debug project wait time

---

lib/bushslicer.rb
lib/environment.rb

`EXECUTOR_NAME` is generated via below code in `lib/bushslicer.rb`. And it's used as part of project name and workdir. We need to make sure it ends with a proper char which is valid for project name and workdir.
```
if ENV["NODE_NAME"]
EXECUTOR_NAME = "#{ENV["NODE_NAME"]}-#{ENV["EXECUTOR_NUMBER"]}".freeze
else
EXECUTOR_NAME = "#{HOSTNAME.split('.')[0]}-#{LOCAL_USER}".freeze
end
```

Make sure EXECUTOR_NAME always end with proper char

---

lib/webauto/web4cucumber.rb

```
[06:33:51] INFO> Exit Status: 0
[06:33:52] INFO> running web action goto_admin_console_root ... 
[06:33:52] INFO> url..
[06:33:52] INFO> Navigating to: https://console-openshift-console.apps.qe-ui49-0908.qe.devcluster.openshift.com/
[06:33:54] INFO> Launching Chrome
[06:34:14] INFO> Chrome version is 93.0.4577.63
[06:34:14] INFO> Chromedriver version is 93.0.4577.15 (660fc11082ba57405eca2e8c49c3e1af756fbfae-refs/branch-heads/4577@{#203})
```
```
[06:39:25] INFO> Exit Status: 0
[06:39:25] INFO> running web action goto_admin_console_root ... 
[06:39:25] INFO> url..
[06:39:25] INFO> Navigating to: https://console-openshift-console.apps.qe-ui49-0908.qe.devcluster.openshift.com/
[06:39:26] INFO> Launching Firefox Marionette/Geckodriver
[06:39:41] INFO> Firefox Marionette version is 92.0 …
```

print browser and driver version for debugging

---

features/networking/multus.feature

Tests that does `oc debug ` are not expected to run concurrently, they are likely to fail when initiating the `oc debug node` together. Prove is https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/21446/rehearse-21446-periodic-ci-openshift-release-master-nightly-4.9-e2e-cucushift-aws-ipi/1435443859713691648/build-log.txt
Noticed both tests have failed and their failure time are very close. I manually verified that running the `oc debug` with same arguments at the same time in two terminals, one of them always fails. To work around issues like this, the `@serial` tag is added to ensure these tests run one by one. I'll be adding this tag as I'm monitoring the ci results.
Scenario: Create pod with Multus bridge CNI plugin without vlan
```
[36m[33m[04:22:48] INFO> …
```

Add serial tag

---

lib/bushslicer.rb

Fix warning as below,
```
$ bundle exec cucumber -P features/tierN/storage/regression.feature
Disabling profiles...
/home/lxia/code-bases/github.com/verification-tests/lib/bushslicer.rb:53: warning: already initialized constant BushSlicer::EXECUTOR_NAME
/home/lxia/code-bases/github.com/verification-tests/lib/bushslicer.rb:51: warning: previous definition of EXECUTOR_NAME was here
```

Fix warning: already initialized constant BushSlicer::EXECUTOR_NAME

---

features/cli/job.feature

Test was failing because it was expecting a 'E' where as it got a small 'e', so fixing that.
@zhouying7780 i have run the case across 4.6, 4.7 & 4.8 and it all passed. Below are the run logs, could you please help review ? Thanks !!
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/166841/console -> 4.6
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/166786/console -> 4.7
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/166842/console -> 4.8

Fix validation of output

---

features/cli/OWNERS

Add @kasturinarra as reviewer/approver for CLI, to speed up PRs like https://github.com/openshift/verification-tests/pull/2268 
After this PR is merged, you are able to merge CLI PRs by adding `/lgtm` (on a separate line). More detail bot process can be find in https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#the-code-review-process
/cc @kasturinarra @zhouying7780

Adjust owners for CLI

---

features/logging/logging_acceptance.feature

Fix failure:
```
Given cluster logging operator is ready                                                                                                                                                                                                                                                                                                                                                                                                                                                                           # features/step_definitions/logging.rb:243
[07:14:40] INFO> Shell Commands: oc project openshift-logging --kubeconfig=/home/qitang/workdir/rhel-8-qitang/ocp4_testuser-30.kubeconfig
STDERR:
error: A project named "openshift-logging" does not …
```

fix failure: can not switch to project openshift-logging

---

features/cli/job.feature

Per the failures in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.9-e2e-cucushift-aws-ipi/1437838750108356608, the output is `end of range` is stead of `End of range`. @kasturinarra made a commit to change the test using `e` -> `E` recently, so I believe the output message contains either `end of range` or `End of range` depending on the versions.
I think no matter it's uppercase or lowercase, the checkpoint needs to be made more robust to evaluate the step as **Passed**.
@kasturinarra @liangxia PTAL.
I've tested this
```
[03:19:02] INFO> === End After Scenario: User can schedule a Cronjob execution with cron format time ===
66 steps (66 passed)
1m2.128s
[03:19:02] INFO> === At Exit ===
```

make the output checkpoint more robust

---

lib/rules/web/admin_console/4.9/monitoring_metrics.xyaml

Developer query browser feature - common user
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-28106
Developer query browser feature - cluster admin
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-27830
error:
[12:07:51] INFO> found 0 input elements with selector: {:xpath=>"//div[@class='co-namespace-selector']//input[@placeholder='Select Project...']"}
1. xpath is changed to {:xpath=>"//div[@class='co-namespace-dropdown']//input[@placeholder='Select project...']"}in 4.9
2. also there is `Show default projects` toggle, need to enable it to see all projects for cluster-admin, for normal user there is not such setting, so
```
click_projects_dropdown_developer_mode_admin:
element:
selector:
xpath: …
```

change xpath and function due to 4.9 change

---

features/build/dockerbuild.feature

The checkpoint of the scenario is: verify source secret is mounted into builder container when using dockerstrategy to build.
Removing the `yum install` docker step does not help/harm the checkpoints. But it do saves test execution time and produce less execution logs.
From my testing, the scenario passed both with and without the `yum install` step.
But the execution time decreased from `2m22.360s` to `1m16.346s`, and the log size decrease from `30K (577 lines)` to `24K (475 lines)`

Simplify docker build

---

features/step_definitions/descheduler.rb

Add code to make sure descheduler restore happens succesfully when /spec/profileCustomizations is present

Fix restore descheduler func to handle more cases

---

features/routing/rate-limit.feature

@lihongan @quarterpin @melvinjoseph86 
Please help to view the changes: I have changed to A15 to A20 for fixing the IPv6 cluster issue, also I have changed the waiting time from 30 to 60 seconds to make sure getting the info.
Please refer to the log link below:
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/173056/console

Updated OCP-18482 on IPv6 Cluster

---

testdata/networking/nodeport_test_pod.yaml

@openshift/team-sdn-qe we need to use `ReplicationController` in upgrade cases in order to keep the pod

update pod with ReplicationControllor in order to upgrade

---

Gemfile
tools/instance_summary.rb
tools/openshift_qe_slack.rb

1. Gemfile needs to be update to install slack-ruby-client
2. Must use a different name than 'Slack' since the 'slack-ruby-client'
has the same class name.

fix slack class name collision

---

features/networking/service.feature

since this change https://github.com/openshift/verification-tests/pull/2304
So now pod is named with 'hello-pod' prefix 

check pod with label

---

features/networking/isolation.feature

This resolves OCPQE-5737.
Once tag is added, the test is skipped from Prow. Former failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21988/rehearse-21988-periodic-ci-openshift-verification-tests-master-4.9-e2e-cucushift-gcp-ipi/1440601527981969408
@liangxia @zhaozhanqi PTAL

Tag network-multitenant test case

---

features/upgrade/sdn/externalIP-upgrade.feature
testdata/networking/externalip_pod.yaml

Automate OCP-44790 externalIP-upgrade-test
Test log:
http://file.rdu.redhat.com/~weliang/externalIP-pre-log
http://file.rdu.redhat.com/~weliang/externalIP-post-log

Automate OCP-44790 externalIP-upgrade-test

---

features/cli/build.feature

Fix failures in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/21988/rehearse-21988-periodic-ci-openshift-verification-tests-master-4.9-e2e-cucushift-gcp-ipi/1441255657092157440
Changes,
1. Replace deprecated option `--docker-image` with `--image`
2. Remove non-exist image stream `mongodb`
```
When I run the :new_app client command with:                                         # features/step_definitions/cli.rb:13
| image_stream      | openshift/mongodb:latest                             |
| image_stream      | openshift/mysql                                      |
| docker_image      | registry.access.redhat.com/rhscl/postgresql-96-rhel7 |
| env               | MONGODB_USER=test                      |
| env               | MONGODB_PASSWORD=test …
```

Fix OCP-11139 failure in PROW

---

features/storage/regression.feature

Instead of checking the output, check the number of available and unavailable pods.
@liangxia @duanwei33 PTAL
```
status:
currentNumberScheduled: 3
desiredNumberScheduled: 3
numberAvailable: 1
numberMisscheduled: 0
numberReady: 1
numberUnavailable: 2
observedGeneration: 1
updatedNumberScheduled: 3
[11:30:59] INFO> Exit Status: 0
[11:30:59] INFO> === After Scenario: RWO volumes are exclusively mounted on different nodes ===
[11:30:59] INFO> cleaning-up user testuser-0 projects
[11:31:08] INFO> Shell Commands: oc delete projects --all --kubeconfig=/tmp/workspace/workdir/ocp4_testuser-0.kubeconfig
project.project.openshift.io "h-7ek" deleted
[11:31:22] INFO> Exit Status: 0
[11:31:22] INFO> waiting up to 30 seconds for user clean-up to take place
[11:31:28] INFO> REST delete_oauthaccesstoken …
```

Fix a possible test flake in 4.9

---

features/networking/sctp.feature

No sctp module installed (RuntimeError) is reported in both https://issues.redhat.com/browse/OCPQE-5056 and https://issues.redhat.com/browse/OCPQE-4976. 
One potential reason is the rebooting nodes are not in the Ready state. Add a step to show all the nodes state before checking sctp module status.
Test log: 
http://file.rdu.redhat.com/~weliang/update-sctp-log

Update sctp to check nodes state

---

features/logging/cluster_logging_operator.feature
features/logging/elasticsearch_operator.feature
features/step_definitions/admin_console.rb
features/step_definitions/web.rb
features/test/webconsole.feature
lib/world.rb

Add method to force console scenarios are tagged with console tag, to support tests in Prow.

Add ensure_console_tagged

---

features/upgrade/logging/upgrade.feature

Adding a step to deploy logging operators before create clusterlogging.
https://issues.redhat.com/browse/OCPQE-5975
/cc @anpingli

missing a step to deploy logging operators

---

features/logging/cluster_log_forwarder.feature
features/logging/cluster_logging_operator.feature
features/logging/collector.feature
features/logging/logging_acceptance.feature
features/step_definitions/logging.rb
lib/openshift/cluster_logging.rb

- Use different daemon-set name and label in In Logging 5.3.
- Fix the exception error when no status in clusterlogging/instance.
- Fix the no openshift-logging record issue when no any pods under openshift-logging namespace.
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/181687/console (Test Failed due to https://issues.redhat.com/browse/LOG-1774)
https://mastern-jenkins-csb-openshift-qe.apps.ocp4.prod.psi.redhat.com/job/ocp-common/job/Runner/181698/console
logging_acceptance.feature pass on both 5.2 and 5.3

Support Logging5.3

---

features/upgrade/etcd/upgrade.feature

Fix for OCP-22606 .
As a result of the [bz-1979550](https://bugzilla.redhat.com/show_bug.cgi?id=1979550), we had to get a workaround for this test.
As per the etcd-cluster.yaml
`apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
name: example
annotations:
etcd.database.coreos.com/scope: clusterwide
namespace: default
spec:
size: 3
version: 3.2.13
`
the script verifies the creation of etcdcluster with name "example".
Please find the link of the successful execution [log](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/Runner-v3-smoke/3670/parameters/)
Hi @geliu2016 , @jhou1  , @pruan-rht ,
could you please have a look.

fix OCP-22606 

---

features/upgrade/sdn/policy-upgrade.feature

As a part of pre-upgrade we are creating client pod and nodeport service. During post upgrade, which will bump up OVS version as well, we want to make sure conntrack entries under observations are statefully populated
Pre-upgade logs:https://privatebin-it-iso.int.open.paas.redhat.com/?98f9b46555ec6839#AggSwn8HNa2iLuc6PzTsDMW2EVAabm3RvZXd5WBuT8a3
Post upgrade logs:https://privatebin-it-iso.int.open.paas.redhat.com/?948e52bbc75c4f97#BnRXjpp8AbQoDWdNCgaiJr46rGX99cdrGBYDe2y2V7P1

Conntrack case for upgrade scenario (Networking Quality OKR)
